TBOX: src/tbox/container/list_entry.h File Reference
list_entry.h File Reference
Container
#include "prefix.h"
#include "iterator.h"
Data Structures
struct tb_list_entry_t
struct tb_list_entry_head_t
the list entry head type
Macros
#define tb_list_entry(head, entry) ((((tb_byte_t*)(entry)) - (head)->eoff))
the list entry
#define tb_list_entry_init(list, type, entry, copy) tb_list_entry_init_(list, tb_offsetof(type, entry), sizeof(type), copy)
Typedefs
typedef tb_list_entry_t * tb_list_entry_ref_t
the list entry ref type
typedef tb_list_entry_head_t * tb_list_entry_head_ref_t
the list entry head ref type
Functions
tb_iterator_ref_t tb_list_entry_itor (tb_list_entry_head_ref_t list)
tb_void_t tb_list_entry_init_ (tb_list_entry_head_ref_t list, tb_size_t entry_offset, tb_size_t entry_size, tb_entry_copy_t copy)
tb_void_t tb_list_entry_exit (tb_list_entry_head_ref_t list)
Variables
__tb_extern_c_enter__ typedef
tb_void_t(* tb_list_entry_copy_t)(tb_pointer_t ltem, tb_pointer_t rtem)
the list entry copy func type
Detailed Description
The Treasure Box Library
TBox is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 2.1 of the License, or (at your option) any later version.
TBox is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with TBox; If not, see http://www.gnu.org/licenses/
Copyright (C) 2009 - 2015, ruki All rights reserved.
Author
ruki
Definition in file list_entry.h.
Macro Definition Documentation
#define tb_list_entry_init (list, type, entry, copy) tb_list_entry_init_(list, tb_offsetof(type, entry), sizeof(type), copy)
init the list entry
// the xxxx entry type
typedef struct __tb_xxxx_entry_t
{
    // the list entry
    tb_list_entry_t     entry;
    // the data
    tb_size_t           data;
}tb_xxxx_entry_t;
// the xxxx entry copy func
static tb_void_t tb_xxxx_entry_copy(tb_pointer_t ltem, tb_pointer_t rtem)
{
    // check
    tb_assert_return(ltem && rtem);
    // copy it
    ((tb_xxxx_entry_t*)ltem)->data = ((tb_xxxx_entry_t*)rtem)->data;
}
// init the list
tb_list_entry_head_t list;
tb_list_entry_init(&list, tb_xxxx_entry_t, entry, tb_xxxx_entry_copy);
Definition at line 71 of file list_entry.h.
Referenced by tb_thread_pool_init(), and tb_transfer_pool_init().
Function Documentation
tb_void_t tb_list_entry_exit (tb_list_entry_head_ref_t list)
exit list
Parameters
list the list
Definition at line 174 of file list_entry.c.
References tb_list_entry_head_t::next, tb_list_entry_head_t::prev, and tb_list_entry_head_t::size.
Referenced by tb_thread_pool_exit(), and tb_transfer_pool_exit().
tb_void_t tb_list_entry_init_ (tb_list_entry_head_ref_t list, tb_size_t entry_offset, tb_size_t entry_size, tb_entry_copy_t copy)
init list
Parameters
list the list
entry_offset the entry offset
entry_size the entry size
copy the copy func of the entry for algorithm, .e.g sort
Definition at line 146 of file list_entry.c.
References tb_iterator_t::comp, tb_iterator_t::copy, tb_list_entry_head_t::copy, tb_list_entry_head_t::eoff, tb_iterator_t::head, tb_iterator_t::item, tb_list_entry_head_t::itor, tb_iterator_t::last, tb_iterator_t::mode, tb_iterator_t::next, tb_list_entry_head_t::next, tb_iterator_t::prev, tb_list_entry_head_t::prev, tb_iterator_t::priv, tb_iterator_t::remove, tb_iterator_t::remove_range, tb_iterator_t::size, tb_list_entry_head_t::size, tb_iterator_t::step, tb_iterator_t::tail, TB_ITERATOR_MODE_FORWARD, and TB_ITERATOR_MODE_REVERSE.
Referenced by tb_list_init().
tb_iterator_ref_t tb_list_entry_itor (tb_list_entry_head_ref_t list)
the list iterator
Parameters
list the list
Returns
the list iterator
Definition at line 138 of file list_entry.c.
References tb_list_entry_head_t::itor.
Referenced by tb_fixed_pool_clear(), tb_fixed_pool_walk(), tb_thread_pool_task_wait_all(), tb_transfer_pool_kill_all(), and tb_transfer_pool_wait_all().