TBOX: src/tbox/memory/static_buffer.h File Reference
static_buffer.h File Reference
Memory
#include "prefix.h"
Data Structures
struct tb_static_buffer_t
Functions
tb_bool_t tb_static_buffer_init (tb_static_buffer_t *buffer, tb_byte_t *data, tb_size_t maxn)
tb_void_t tb_static_buffer_exit (tb_static_buffer_t *buffer)
tb_byte_t * tb_static_buffer_data (tb_static_buffer_t *buffer)
tb_size_t tb_static_buffer_size (tb_static_buffer_t const *buffer)
tb_size_t tb_static_buffer_maxn (tb_static_buffer_t const *buffer)
tb_void_t tb_static_buffer_clear (tb_static_buffer_t *buffer)
tb_byte_t * tb_static_buffer_resize (tb_static_buffer_t *buffer, tb_size_t size)
tb_byte_t * tb_static_buffer_memset (tb_static_buffer_t *buffer, tb_byte_t b)
tb_byte_t * tb_static_buffer_memsetp (tb_static_buffer_t *buffer, tb_size_t p, tb_byte_t b)
tb_byte_t * tb_static_buffer_memnset (tb_static_buffer_t *buffer, tb_byte_t b, tb_size_t n)
tb_byte_t * tb_static_buffer_memnsetp (tb_static_buffer_t *buffer, tb_size_t p, tb_byte_t b, tb_size_t n)
tb_byte_t * tb_static_buffer_memcpy (tb_static_buffer_t *buffer, tb_static_buffer_t *b)
tb_byte_t * tb_static_buffer_memcpyp (tb_static_buffer_t *buffer, tb_size_t p, tb_static_buffer_t *b)
tb_byte_t * tb_static_buffer_memncpy (tb_static_buffer_t *buffer, tb_byte_t const *b, tb_size_t n)
tb_byte_t * tb_static_buffer_memncpyp (tb_static_buffer_t *buffer, tb_size_t p, tb_byte_t const *b, tb_size_t n)
tb_byte_t * tb_static_buffer_memmov (tb_static_buffer_t *buffer, tb_size_t b)
tb_byte_t * tb_static_buffer_memmovp (tb_static_buffer_t *buffer, tb_size_t p, tb_size_t b)
tb_byte_t * tb_static_buffer_memnmov (tb_static_buffer_t *buffer, tb_size_t b, tb_size_t n)
tb_byte_t * tb_static_buffer_memnmovp (tb_static_buffer_t *buffer, tb_size_t p, tb_size_t b, tb_size_t n)
tb_byte_t * tb_static_buffer_memcat (tb_static_buffer_t *buffer, tb_static_buffer_t *b)
tb_byte_t * tb_static_buffer_memncat (tb_static_buffer_t *buffer, tb_byte_t const *b, tb_size_t n)
Detailed Description
The Treasure Box Library
TBox is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 2.1 of the License, or (at your option) any later version.
TBox is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with TBox; If not, see http://www.gnu.org/licenses/
Copyright (C) 2009 - 2015, ruki All rights reserved.
Author
ruki
Definition in file static_buffer.h.
Function Documentation
tb_void_t tb_static_buffer_clear (tb_static_buffer_t * buffer)
clear the buffer
Parameters
buffer the static buffer
Definition at line 92 of file static_buffer.c.
Referenced by tb_dns_looker_spak(), tb_static_buffer_memnmovp(), and tb_static_string_clear().
tb_byte_t* tb_static_buffer_data (tb_static_buffer_t * buffer)
the buffer data
Parameters
buffer the static buffer
Returns
the buffer data address
Definition at line 68 of file static_buffer.c.
Referenced by tb_static_buffer_memcat(), tb_static_buffer_memcpy(), tb_static_buffer_memcpyp(), tb_static_buffer_memncat(), tb_static_buffer_memncpyp(), tb_static_buffer_memnmovp(), tb_static_buffer_memnsetp(), tb_static_string_clear(), and tb_static_string_cstr().
tb_void_t tb_static_buffer_exit (tb_static_buffer_t * buffer)
exit the static buffer
Parameters
buffer the static buffer
Definition at line 58 of file static_buffer.c.
Referenced by tb_static_string_exit().
tb_bool_t tb_static_buffer_init (tb_static_buffer_t * buffer, tb_byte_t * data, tb_size_t maxn)
init the static buffer
Parameters
buffer the static buffer
data the data
maxn the data maxn
Returns
tb_true or tb_false
Definition at line 45 of file static_buffer.c.
Referenced by tb_dns_looker_init(), and tb_static_string_init().
tb_size_t tb_static_buffer_maxn (tb_static_buffer_t const * buffer)
the buffer data maxn
Parameters
buffer the static buffer
Returns
the buffer data maxn
Definition at line 84 of file static_buffer.c.
tb_byte_t* tb_static_buffer_memcat (tb_static_buffer_t * buffer, tb_static_buffer_t * b)
memcat: b +=> e ...
Parameters
buffer the static buffer
b the concated buffer
Returns
the buffer data address
Definition at line 212 of file static_buffer.c.
References tb_static_buffer_data(), tb_static_buffer_memncat(), and tb_static_buffer_size().
tb_byte_t* tb_static_buffer_memcpy (tb_static_buffer_t * buffer, tb_static_buffer_t * b)
memcpy: b => 0 ...
Parameters
buffer the static buffer
b the copied buffer
Returns
the buffer data address
Definition at line 141 of file static_buffer.c.
References tb_static_buffer_data(), tb_static_buffer_memncpyp(), and tb_static_buffer_size().
tb_byte_t* tb_static_buffer_memcpyp (tb_static_buffer_t * buffer, tb_size_t p, tb_static_buffer_t * b)
memcpy: b => p ...
Parameters
buffer the static buffer
p the start position
b the copied buffer
Returns
the buffer data address
Definition at line 145 of file static_buffer.c.
References tb_static_buffer_data(), tb_static_buffer_memncpyp(), and tb_static_buffer_size().
tb_byte_t* tb_static_buffer_memmov (tb_static_buffer_t * buffer, tb_size_t b)
memmov: b ... e => 0 ...
Parameters
buffer the static buffer
b the moved start position
Returns
the buffer data address
Definition at line 171 of file static_buffer.c.
References tb_static_buffer_memnmovp(), and tb_static_buffer_size().
tb_byte_t* tb_static_buffer_memmovp (tb_static_buffer_t * buffer, tb_size_t p, tb_size_t b)
memmov: b ... e => p ...
Parameters
buffer the static buffer
p the moved destination position
b the moved start position
Returns
the buffer data address
Definition at line 177 of file static_buffer.c.
References tb_static_buffer_memnmovp(), and tb_static_buffer_size().
tb_byte_t* tb_static_buffer_memncat (tb_static_buffer_t * buffer, tb_byte_t const * b, tb_size_t n)
memcat: b ... n +=> e ...
Parameters
buffer the static buffer
b the concated buffer
n the concated count
Returns
the buffer data address
Definition at line 216 of file static_buffer.c.
References tb_static_buffer_data(), tb_static_buffer_memncpy(), tb_static_buffer_resize(), and tb_static_buffer_size().
Referenced by tb_static_buffer_memcat().
tb_byte_t* tb_static_buffer_memncpy (tb_static_buffer_t * buffer, tb_byte_t const * b, tb_size_t n)
memcpy: b ... n => 0 ...
Parameters
buffer the static buffer
b the copied buffer
n the copied count
Returns
the buffer data address
Definition at line 149 of file static_buffer.c.
References tb_static_buffer_memncpyp().
Referenced by tb_static_buffer_memncat(), and tb_static_string_cstrncpy().
tb_byte_t* tb_static_buffer_memncpyp (tb_static_buffer_t * buffer, tb_size_t p, tb_byte_t const * b, tb_size_t n)
memcpy: b ... n => p ...
Parameters
buffer the static buffer
p the start position
b the copied buffer
n the copied count
Returns
the buffer data address
Definition at line 153 of file static_buffer.c.
References tb_static_buffer_data(), and tb_static_buffer_resize().
Referenced by tb_static_buffer_memcpy(), tb_static_buffer_memcpyp(), tb_static_buffer_memncpy(), and tb_static_string_cstrncat().
tb_byte_t* tb_static_buffer_memnmov (tb_static_buffer_t * buffer, tb_size_t b, tb_size_t n)
memmov: b ... n => 0 ...
Parameters
buffer the static buffer
b the moved start position
n the moved count
Returns
the buffer data address
Definition at line 183 of file static_buffer.c.
References tb_static_buffer_memnmovp().
tb_byte_t* tb_static_buffer_memnmovp (tb_static_buffer_t * buffer, tb_size_t p, tb_size_t b, tb_size_t n)
memmov: b ... n => p ...
Parameters
buffer the static buffer
p the moved destination position
b the moved start position
n the moved count
Returns
the buffer data address
Definition at line 187 of file static_buffer.c.
References tb_static_buffer_clear(), tb_static_buffer_data(), tb_static_buffer_resize(), and tb_static_buffer_size().
Referenced by tb_static_buffer_memmov(), tb_static_buffer_memmovp(), and tb_static_buffer_memnmov().
tb_byte_t* tb_static_buffer_memnset (tb_static_buffer_t * buffer, tb_byte_t b, tb_size_t n)
memset: b => 0 ... n
Parameters
buffer the static buffer
b the filled byte
n the filled count
Returns
the buffer data address
Definition at line 119 of file static_buffer.c.
References tb_static_buffer_memnsetp().
tb_byte_t* tb_static_buffer_memnsetp (tb_static_buffer_t * buffer, tb_size_t p, tb_byte_t b, tb_size_t n)
memset: b => p ... n
Parameters
buffer the static buffer
p the start position
b the filled byte
n the filled count
Returns
the buffer data address
Definition at line 123 of file static_buffer.c.
References tb_static_buffer_data(), and tb_static_buffer_resize().
Referenced by tb_static_buffer_memnset(), tb_static_buffer_memset(), tb_static_buffer_memsetp(), tb_static_string_chrcat(), and tb_static_string_chrncat().
tb_byte_t* tb_static_buffer_memset (tb_static_buffer_t * buffer, tb_byte_t b)
memset: b => 0 ... e
Parameters
buffer the static buffer
b the filled byte
Returns
the buffer data address
Definition at line 111 of file static_buffer.c.
References tb_static_buffer_memnsetp(), and tb_static_buffer_size().
tb_byte_t* tb_static_buffer_memsetp (tb_static_buffer_t * buffer, tb_size_t p, tb_byte_t b)
memset: b => p ... e
Parameters
buffer the static buffer
p the start position
b the filled byte
Returns
the buffer data address
Definition at line 115 of file static_buffer.c.
References tb_static_buffer_memnsetp(), and tb_static_buffer_size().
tb_byte_t* tb_static_buffer_resize (tb_static_buffer_t * buffer, tb_size_t size)
resize the buffer size
Parameters
buffer the static buffer
size the new buffer size
Returns
the buffer data address
Definition at line 100 of file static_buffer.c.
Referenced by tb_static_buffer_memncat(), tb_static_buffer_memncpyp(), tb_static_buffer_memnmovp(), tb_static_buffer_memnsetp(), and tb_static_string_strip().
tb_size_t tb_static_buffer_size (tb_static_buffer_t const * buffer)
the buffer data size
Parameters
buffer the static buffer
Returns
the buffer data size
Definition at line 76 of file static_buffer.c.
Referenced by tb_static_buffer_memcat(), tb_static_buffer_memcpy(), tb_static_buffer_memcpyp(), tb_static_buffer_memmov(), tb_static_buffer_memmovp(), tb_static_buffer_memncat(), tb_static_buffer_memnmovp(), tb_static_buffer_memset(), tb_static_buffer_memsetp(), and tb_static_string_size().