TBOX: src/tbox/network/dns/server.c File Reference
server.c File Reference
Network
#include "server.h"
#include "../../utils/utils.h"
#include "../../stream/stream.h"
#include "../../platform/platform.h"
#include "../../container/container.h"
#include "../../algorithm/algorithm.h"
Macros
#define TB_TRACE_MODULE_NAME "dns_server"
#define TB_TRACE_MODULE_DEBUG (0)
#define TB_DNS_SERVER_TEST_TIMEOUT (500)
Functions
tb_bool_t tb_dns_server_init ()
tb_void_t tb_dns_server_exit ()
tb_void_t tb_dns_server_dump ()
tb_void_t tb_dns_server_sort ()
tb_size_t tb_dns_server_get (tb_ipv4_t addr[2])
tb_void_t tb_dns_server_add (tb_char_t const *addr)
Detailed Description
The Treasure Box Library
TBox is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 2.1 of the License, or (at your option) any later version.
TBox is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with TBox; If not, see http://www.gnu.org/licenses/
Copyright (C) 2009 - 2015, ruki All rights reserved.
Author
ruki
Definition in file server.c.
Function Documentation
tb_void_t tb_dns_server_add (tb_char_t const * addr)
add the server
Parameters
addr the server address
Definition at line 496 of file server.c.
References tb_dns_server_init(), tb_ipv4_set(), and tb_vector_insert_tail().
tb_size_t tb_dns_server_get (tb_ipv4_t addr[2])
get the server
Parameters
addr the server address list, addr[0] is the fastest
Returns
the server size
Definition at line 457 of file server.c.
References tb_dns_server_sort(), tb_iterator_item(), and tb_vector_size().
Referenced by tb_dns_looker_init().