TBOX: src/tbox/algorithm/rwalk.h File Reference
rwalk.h File Reference
Algorithm
#include "prefix.h"
Functions
tb_size_t tb_rwalk (tb_iterator_ref_t iterator, tb_size_t head, tb_size_t tail, tb_rwalk_func_t func, tb_cpointer_t priv)
tb_size_t tb_rwalk_all (tb_iterator_ref_t iterator, tb_rwalk_func_t func, tb_cpointer_t priv)
Variables
__tb_extern_c_enter__ typedef
tb_bool_t(* tb_rwalk_func_t)(tb_iterator_ref_t iterator, tb_pointer_t item, tb_cpointer_t priv)
the reverse walk func type
Detailed Description
The Treasure Box Library
TBox is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 2.1 of the License, or (at your option) any later version.
TBox is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with TBox; If not, see http://www.gnu.org/licenses/
Copyright (C) 2009 - 2015, ruki All rights reserved.
Author
ruki
Definition in file rwalk.h.
Function Documentation
tb_size_t tb_rwalk (tb_iterator_ref_t iterator, tb_size_t head, tb_size_t tail, tb_rwalk_func_t func, tb_cpointer_t priv)
the reverse walker
Parameters
iterator the iterator
head the iterator head
tail the iterator tail
func the walker func
priv the func private data
Returns
the item count
Definition at line 34 of file rwalk.c.
References tb_iterator_mode(), TB_ITERATOR_MODE_REVERSE, and tb_rfor.
Referenced by tb_rwalk_all().
tb_size_t tb_rwalk_all (tb_iterator_ref_t iterator, tb_rwalk_func_t func, tb_cpointer_t priv)
the reverse walker for all
Parameters
iterator the iterator
func the walker func
priv the func private data
Returns
the item count
Definition at line 56 of file rwalk.c.
References tb_iterator_head(), tb_iterator_tail(), and tb_rwalk().