TBOX: src/tbox/platform/directory.h File Reference
directory.h File Reference
Platform
#include "prefix.h"
#include "file.h"
Functions
tb_bool_t tb_directory_create (tb_char_t const *path)
tb_bool_t tb_directory_remove (tb_char_t const *path)
tb_size_t tb_directory_temp (tb_char_t *path, tb_size_t maxn)
tb_size_t tb_directory_curt (tb_char_t *path, tb_size_t maxn)
tb_void_t tb_directory_walk (tb_char_t const *path, tb_bool_t recursion, tb_bool_t prefix, tb_directory_walk_func_t func, tb_cpointer_t priv)
tb_bool_t tb_directory_copy (tb_char_t const *path, tb_char_t const *dest)
Variables
__tb_extern_c_enter__ typedef
tb_void_t(* tb_directory_walk_func_t)(tb_char_t const *path, tb_file_info_t const *info, tb_cpointer_t priv)
the directory walk func type
Detailed Description
The Treasure Box Library
TBox is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 2.1 of the License, or (at your option) any later version.
TBox is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with TBox; If not, see http://www.gnu.org/licenses/
Copyright (C) 2009 - 2015, ruki All rights reserved.
Author
ruki
Definition in file directory.h.
Function Documentation
tb_bool_t tb_directory_copy (tb_char_t const * path, tb_char_t const * dest)
copy directory
Parameters
path the directory path
dest the directory dest
Returns
tb_true or tb_false
Definition at line 253 of file directory.c.
References tb_value_t::b, tb_value_t::cstr, TB_PATH_MAXN, and tb_value_t::ul.
tb_bool_t tb_directory_create (tb_char_t const * path)
create the directory
Parameters
path the directory path
Returns
tb_true or tb_false
Definition at line 154 of file directory.c.
References tb_file_info(), and TB_PATH_MAXN.
tb_size_t tb_directory_curt (tb_char_t * path, tb_size_t maxn)
the current directory
Parameters
path the directory path data
maxn the directory path maxn
Returns
the directory path size
Definition at line 221 of file directory.c.
tb_bool_t tb_directory_remove (tb_char_t const * path)
remove the directory
Parameters
path the directory path
Returns
tb_true or tb_false
Definition at line 194 of file directory.c.
References TB_PATH_MAXN.
tb_size_t tb_directory_temp (tb_char_t * path, tb_size_t maxn)
the temporary directory
Parameters
path the directory path data
maxn the directory path maxn
Returns
the directory path size
Definition at line 40 of file directory.c.
References tb_android_jenv().
tb_void_t tb_directory_walk (tb_char_t const * path, tb_bool_t recursion, tb_bool_t prefix, tb_directory_walk_func_t func, tb_cpointer_t priv)
the directory walk
Parameters
path the directory path
recursion is recursion?
prefix is prefix recursion? directory is the first item
func the callback func
data the callback data
Definition at line 233 of file directory.c.
References tb_file_info(), TB_PATH_MAXN, and tb_file_info_t::type.