TBOX: src/container/dlist.h File Reference
dlist.h File Reference
Container
#include "prefix.h"
#include "item.h"
#include "iterator.h"
Typedefs
typedef tb_void_t tb_dlist_t
the dlist type
Functions
tb_dlist_t * tb_dlist_init (tb_size_t grow, tb_item_func_t func)
tb_void_t tb_dlist_exit (tb_dlist_t *dlist)
tb_void_t tb_dlist_clear (tb_dlist_t *dlist)
tb_pointer_t tb_dlist_head (tb_dlist_t const *dlist)
tb_pointer_t tb_dlist_last (tb_dlist_t const *dlist)
tb_size_t tb_dlist_insert_prev (tb_dlist_t *dlist, tb_size_t itor, tb_cpointer_t data)
tb_size_t tb_dlist_insert_next (tb_dlist_t *dlist, tb_size_t itor, tb_cpointer_t data)
tb_size_t tb_dlist_insert_head (tb_dlist_t *dlist, tb_cpointer_t data)
tb_size_t tb_dlist_insert_tail (tb_dlist_t *dlist, tb_cpointer_t data)
tb_size_t tb_dlist_ninsert_prev (tb_dlist_t *dlist, tb_size_t itor, tb_cpointer_t data, tb_size_t size)
tb_size_t tb_dlist_ninsert_next (tb_dlist_t *dlist, tb_size_t itor, tb_cpointer_t data, tb_size_t size)
tb_size_t tb_dlist_ninsert_head (tb_dlist_t *dlist, tb_cpointer_t data, tb_size_t size)
tb_size_t tb_dlist_ninsert_tail (tb_dlist_t *dlist, tb_cpointer_t data, tb_size_t size)
tb_size_t tb_dlist_replace (tb_dlist_t *dlist, tb_size_t itor, tb_cpointer_t data)
tb_size_t tb_dlist_replace_head (tb_dlist_t *dlist, tb_cpointer_t data)
tb_size_t tb_dlist_replace_last (tb_dlist_t *dlist, tb_cpointer_t data)
tb_size_t tb_dlist_nreplace (tb_dlist_t *dlist, tb_size_t itor, tb_cpointer_t data, tb_size_t size)
tb_size_t tb_dlist_nreplace_head (tb_dlist_t *dlist, tb_cpointer_t data, tb_size_t size)
tb_size_t tb_dlist_nreplace_last (tb_dlist_t *dlist, tb_cpointer_t data, tb_size_t size)
tb_size_t tb_dlist_remove (tb_dlist_t *dlist, tb_size_t itor)
tb_size_t tb_dlist_remove_next (tb_dlist_t *dlist, tb_size_t itor)
tb_size_t tb_dlist_remove_head (tb_dlist_t *dlist)
tb_size_t tb_dlist_remove_last (tb_dlist_t *dlist)
tb_size_t tb_dlist_nremove (tb_dlist_t *dlist, tb_size_t itor, tb_size_t size)
tb_size_t tb_dlist_nremove_next (tb_dlist_t *dlist, tb_size_t itor, tb_size_t size)
tb_size_t tb_dlist_nremove_head (tb_dlist_t *dlist, tb_size_t size)
tb_size_t tb_dlist_nremove_last (tb_dlist_t *dlist, tb_size_t size)
tb_size_t tb_dlist_moveto_prev (tb_dlist_t *dlist, tb_size_t itor, tb_size_t move)
tb_size_t tb_dlist_moveto_next (tb_dlist_t *dlist, tb_size_t itor, tb_size_t move)
tb_size_t tb_dlist_moveto_head (tb_dlist_t *dlist, tb_size_t move)
tb_size_t tb_dlist_moveto_tail (tb_dlist_t *dlist, tb_size_t move)
tb_size_t tb_dlist_size (tb_dlist_t const *dlist)
tb_size_t tb_dlist_maxn (tb_dlist_t const *dlist)
tb_void_t tb_dlist_walk (tb_dlist_t *dlist, tb_bool_t(*func)(tb_dlist_t *dlist, tb_pointer_t item, tb_bool_t *bdel, tb_pointer_t priv), tb_pointer_t priv)
Detailed Description
The Treasure Box Library
TBox is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 2.1 of the License, or (at your option) any later version.
TBox is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with TBox; If not, see http://www.gnu.org/licenses/
Copyright (C) 2009 - 2015, ruki All rights reserved.
Author
ruki
Definition in file dlist.h.
Function Documentation
tb_void_t tb_dlist_clear (tb_dlist_t * dlist)
clear dlist
Parameters
dlist the dlist
Definition at line 415 of file dlist.c.
References tb_rpool_clear().
Referenced by tb_dlist_exit().
tb_void_t tb_dlist_exit (tb_dlist_t * dlist)
exit dlist
Parameters
dlist the dlist
Definition at line 400 of file dlist.c.
References tb_dlist_clear(), and tb_rpool_exit().
Referenced by tb_dlist_init(), tb_epool_exit(), tb_mstream_exit(), and tb_mstream_kill().
tb_pointer_t tb_dlist_head (tb_dlist_t const * dlist)
the dlist head item
Parameters
dlist the dlist
Returns
the head item
Definition at line 445 of file dlist.c.
References tb_iterator_head(), and tb_iterator_item().
tb_dlist_t* tb_dlist_init (tb_size_t grow, tb_item_func_t func)
init dlist
Parameters
grow the item grow
func the item func
Returns
the dlist
Definition at line 361 of file dlist.c.
References tb_item_func_t::dupl, tb_item_func_t::repl, tb_item_func_t::size, tb_dlist_exit(), TB_ITERATOR_MODE_FORWARD, TB_ITERATOR_MODE_REVERSE, and tb_rpool_init().
Referenced by tb_epool_init(), tb_mstream_init(), and tb_mstream_kill().
tb_size_t tb_dlist_insert_head (tb_dlist_t * dlist, tb_cpointer_t data)
insert the head item
Parameters
dlist the dlist
data the item data
Returns
the item itor
Definition at line 486 of file dlist.c.
References tb_dlist_insert_prev(), and tb_iterator_head().
tb_size_t tb_dlist_insert_next (tb_dlist_t * dlist, tb_size_t itor, tb_cpointer_t data)
insert the next item
Parameters
dlist the dlist
itor the item itor
data the item data
Returns
the item itor
Definition at line 482 of file dlist.c.
References tb_dlist_insert_prev(), and tb_iterator_next().
tb_size_t tb_dlist_insert_prev (tb_dlist_t * dlist, tb_size_t itor, tb_cpointer_t data)
insert the prev item
Parameters
dlist the dlist
itor the item itor
data the item data
Returns
the item itor
Definition at line 464 of file dlist.c.
References tb_rpool_malloc().
Referenced by tb_dlist_insert_head(), tb_dlist_insert_next(), tb_dlist_insert_tail(), and tb_dlist_ninsert_prev().
tb_size_t tb_dlist_insert_tail (tb_dlist_t * dlist, tb_cpointer_t data)
insert the tail item
Parameters
dlist the dlist
data the item data
Returns
the item itor
Definition at line 490 of file dlist.c.
References tb_dlist_insert_prev(), and tb_iterator_tail().
Referenced by tb_epool_adde(), and tb_mstream_done().
tb_pointer_t tb_dlist_last (tb_dlist_t const * dlist)
the dlist last item
Parameters
dlist the dlist
Returns
the last item
Definition at line 449 of file dlist.c.
References tb_iterator_item(), and tb_iterator_last().
tb_size_t tb_dlist_maxn (tb_dlist_t const * dlist)
the item max count
Parameters
dlist the dlist
Returns
the item max count
Definition at line 459 of file dlist.c.
tb_size_t tb_dlist_moveto_head (tb_dlist_t * dlist, tb_size_t move)
moveto the head item
Parameters
dlist the dlist
itor the item itor
Returns
the move itor
Definition at line 640 of file dlist.c.
References tb_dlist_moveto_prev(), and tb_iterator_head().
tb_size_t tb_dlist_moveto_next (tb_dlist_t * dlist, tb_size_t itor, tb_size_t move)
moveto the next item
Parameters
dlist the dlist
itor the item itor
move the move itor
Returns
the move itor
Definition at line 636 of file dlist.c.
References tb_dlist_moveto_prev(), and tb_iterator_next().
tb_size_t tb_dlist_moveto_prev (tb_dlist_t * dlist, tb_size_t itor, tb_size_t move)
moveto the prev item
Parameters
dlist the dlist
itor the item itor
move the move itor
Returns
the move itor
Definition at line 623 of file dlist.c.
Referenced by tb_dlist_moveto_head(), tb_dlist_moveto_next(), and tb_dlist_moveto_tail().
tb_size_t tb_dlist_moveto_tail (tb_dlist_t * dlist, tb_size_t move)
moveto the tail item
Parameters
dlist the dlist
itor the item itor
Returns
the move itor
Definition at line 644 of file dlist.c.
References tb_dlist_moveto_prev(), and tb_iterator_tail().
tb_size_t tb_dlist_ninsert_head (tb_dlist_t * dlist, tb_cpointer_t data, tb_size_t size)
insert the head items
Parameters
dlist the dlist
data the item data
size the item count
Returns
the first item itor
Definition at line 511 of file dlist.c.
References tb_dlist_ninsert_prev(), and tb_iterator_head().
tb_size_t tb_dlist_ninsert_next (tb_dlist_t * dlist, tb_size_t itor, tb_cpointer_t data, tb_size_t size)
insert the next items
Parameters
dlist the dlist
itor the prev item itor
data the item data
size the item count
Returns
the first item itor
Definition at line 507 of file dlist.c.
References tb_dlist_ninsert_prev(), and tb_iterator_next().
tb_size_t tb_dlist_ninsert_prev (tb_dlist_t * dlist, tb_size_t itor, tb_cpointer_t data, tb_size_t size)
insert the prev items
Parameters
dlist the dlist
itor the prev item itor
data the item data
size the item count
Returns
the first item itor
Definition at line 494 of file dlist.c.
References tb_dlist_insert_prev().
Referenced by tb_dlist_ninsert_head(), tb_dlist_ninsert_next(), and tb_dlist_ninsert_tail().
tb_size_t tb_dlist_ninsert_tail (tb_dlist_t * dlist, tb_cpointer_t data, tb_size_t size)
insert the tail items
Parameters
dlist the dlist
data the item data
size the item count
Returns
the first item itor
Definition at line 515 of file dlist.c.
References tb_dlist_ninsert_prev(), and tb_iterator_tail().
tb_size_t tb_dlist_nremove (tb_dlist_t * dlist, tb_size_t itor, tb_size_t size)
remove the next items
Parameters
dlist the dlist
itor the item itor
size the item count
Returns
the prev item itor
Definition at line 603 of file dlist.c.
References tb_dlist_remove().
tb_size_t tb_dlist_nremove_head (tb_dlist_t * dlist, tb_size_t size)
remove the head items
Parameters
dlist the dlist
size the item count
Returns
the head item itor
Definition at line 613 of file dlist.c.
References tb_dlist_remove_head(), tb_dlist_size(), and tb_iterator_head().
tb_size_t tb_dlist_nremove_last (tb_dlist_t * dlist, tb_size_t size)
remove the last items
Parameters
dlist the dlist
size the item count
Returns
the last item itor
Definition at line 618 of file dlist.c.
References tb_dlist_remove_last(), tb_dlist_size(), and tb_iterator_last().
tb_size_t tb_dlist_nremove_next (tb_dlist_t * dlist, tb_size_t itor, tb_size_t size)
remove the next items
Parameters
dlist the dlist
itor the item itor
size the item count
Returns
the prev item itor
tb_size_t tb_dlist_nreplace (tb_dlist_t * dlist, tb_size_t itor, tb_cpointer_t data, tb_size_t size)
replace the items
Parameters
dlist the dlist
itor the first item itor
data the item data
size the item count
Returns
the first item itor
Definition at line 542 of file dlist.c.
References tb_dlist_replace(), tb_iterator_next(), and tb_iterator_tail().
Referenced by tb_dlist_nreplace_head().
tb_size_t tb_dlist_nreplace_head (tb_dlist_t * dlist, tb_cpointer_t data, tb_size_t size)
replace the head items
Parameters
dlist the dlist
data the item data
size the item count
Returns
the first item itor
Definition at line 554 of file dlist.c.
References tb_dlist_nreplace(), and tb_iterator_head().
tb_size_t tb_dlist_nreplace_last (tb_dlist_t * dlist, tb_cpointer_t data, tb_size_t size)
replace the tail items
Parameters
dlist the dlist
data the item data
size the item count
Returns
the first item itor
Definition at line 558 of file dlist.c.
References tb_dlist_replace(), tb_iterator_last(), tb_iterator_prev(), and tb_iterator_tail().
tb_size_t tb_dlist_remove (tb_dlist_t * dlist, tb_size_t itor)
remove the item
Parameters
dlist the dlist
itor the item itor
Returns
the prev item itor
Definition at line 568 of file dlist.c.
References tb_iterator_next(), and tb_rpool_free().
Referenced by tb_dlist_nremove(), tb_dlist_remove_head(), tb_dlist_remove_last(), tb_dlist_remove_next(), tb_epool_dele(), and tb_mstream_done().
tb_size_t tb_dlist_remove_head (tb_dlist_t * dlist)
remove the head item
Parameters
dlist the dlist
Returns
the head item itor
Definition at line 595 of file dlist.c.
References tb_dlist_remove(), and tb_iterator_head().
Referenced by tb_dlist_nremove_head().
tb_size_t tb_dlist_remove_last (tb_dlist_t * dlist)
remove the last item
Parameters
dlist the dlist
Returns
the last item itor
Definition at line 599 of file dlist.c.
References tb_dlist_remove(), and tb_iterator_last().
Referenced by tb_dlist_nremove_last().
tb_size_t tb_dlist_remove_next (tb_dlist_t * dlist, tb_size_t itor)
remove the next item
Parameters
dlist the dlist
itor the item itor
Returns
the prev item itor
Definition at line 591 of file dlist.c.
References tb_dlist_remove(), and tb_iterator_next().
tb_size_t tb_dlist_replace (tb_dlist_t * dlist, tb_size_t itor, tb_cpointer_t data)
replace the item
Parameters
dlist the dlist
itor the item itor
data the item data
Returns
the item itor
Definition at line 519 of file dlist.c.
Referenced by tb_dlist_nreplace(), tb_dlist_nreplace_last(), tb_dlist_replace_head(), and tb_dlist_replace_last().
tb_size_t tb_dlist_replace_head (tb_dlist_t * dlist, tb_cpointer_t data)
replace the head item
Parameters
dlist the dlist
data the item data
Returns
the item itor
Definition at line 534 of file dlist.c.
References tb_dlist_replace(), and tb_iterator_head().
tb_size_t tb_dlist_replace_last (tb_dlist_t * dlist, tb_cpointer_t data)
replace the tail item
Parameters
dlist the dlist
data the item data
Returns
the item itor
Definition at line 538 of file dlist.c.
References tb_dlist_replace(), and tb_iterator_last().
tb_size_t tb_dlist_size (tb_dlist_t const * dlist)
the item count
Parameters
dlist the dlist
Returns
the item count
Definition at line 453 of file dlist.c.
References tb_rpool_size().
Referenced by tb_dlist_nremove_head(), tb_dlist_nremove_last(), tb_epool_adde(), tb_epool_dele(), tb_epool_post(), tb_epool_size(), tb_mstream_done(), tb_mstream_exit(), and tb_mstream_kill().
tb_void_t tb_dlist_walk (tb_dlist_t * dlist, tb_bool_t(*)(tb_dlist_t *dlist, tb_pointer_t item, tb_bool_t *bdel, tb_pointer_t priv) func, tb_pointer_t priv)
walk list items
be faster than the iterator mode, optimizate to remove items for walking
tb_bool_t tb_dlist_item_func(tb_dlist_t* dlist, tb_pointer_t item, tb_bool_t* bdel, tb_pointer_t priv)
{
        // check
    tb_assert_and_check_return_val(dlist && bdel, tb_false);
        // delete it?
        // *bdel = tb_true;
        // continue or break
        return tb_true;
}
Parameters
dlist the dlist
func the walk func
priv the walk priv
Definition at line 648 of file dlist.c.
References tb_rpool_free().