TBOX: src/tbox/memory/large_pool.c File Reference
large_pool.c File Reference
Memory
#include "large_pool.h"
#include "impl/static_large_pool.h"
#include "impl/native_large_pool.h"
Macros
#define TB_TRACE_MODULE_NAME "large_pool"
#define TB_TRACE_MODULE_DEBUG (0)
#define tb_large_pool_is_native(pool) (((tb_size_t)(pool)) & 0x1)
Functions
tb_large_pool_ref_t tb_large_pool ()
tb_large_pool_ref_t tb_large_pool_init (tb_byte_t *data, tb_size_t size)
tb_void_t tb_large_pool_exit (tb_large_pool_ref_t pool)
tb_void_t tb_large_pool_clear (tb_large_pool_ref_t pool)
tb_pointer_t tb_large_pool_malloc_ (tb_large_pool_ref_t pool, tb_size_t size, tb_size_t *real __tb_debug_decl__)
tb_pointer_t tb_large_pool_malloc0_ (tb_large_pool_ref_t pool, tb_size_t size, tb_size_t *real __tb_debug_decl__)
tb_pointer_t tb_large_pool_nalloc_ (tb_large_pool_ref_t pool, tb_size_t item, tb_size_t size, tb_size_t *real __tb_debug_decl__)
tb_pointer_t tb_large_pool_nalloc0_ (tb_large_pool_ref_t pool, tb_size_t item, tb_size_t size, tb_size_t *real __tb_debug_decl__)
tb_pointer_t tb_large_pool_ralloc_ (tb_large_pool_ref_t pool, tb_pointer_t data, tb_size_t size, tb_size_t *real __tb_debug_decl__)
tb_bool_t tb_large_pool_free_ (tb_large_pool_ref_t pool, tb_pointer_t data __tb_debug_decl__)
Variables
__tb_extern_c__ tb_byte_t * g_large_pool_data = tb_null
__tb_extern_c__ tb_size_t g_large_pool_size = 0
Detailed Description
The Treasure Box Library
TBox is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 2.1 of the License, or (at your option) any later version.
TBox is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with TBox; If not, see http://www.gnu.org/licenses/
Copyright (C) 2009 - 2015, ruki All rights reserved.
Author
ruki
Definition in file large_pool.c.
Function Documentation
tb_void_t tb_large_pool_clear (tb_large_pool_ref_t pool)
clear the pool
Parameters
pool the pool
Definition at line 95 of file large_pool.c.
tb_void_t tb_large_pool_exit (tb_large_pool_ref_t pool)
exit the pool
Parameters
pool the pool
Definition at line 86 of file large_pool.c.
tb_bool_t tb_large_pool_free_ (tb_large_pool_ref_t pool, tb_pointer_t data __tb_debug_decl__)
free data
Parameters
pool the pool
data the data address
Returns
tb_true or tb_false
Definition at line 201 of file large_pool.c.
Referenced by tb_pool_free_(), and tb_pool_ralloc_().
tb_large_pool_ref_t tb_large_pool_init (tb_byte_t * data, tb_size_t size)
init the large pool
Parameters
data the pool data, using the native memory if be null
size the pool size
Returns
the pool
Definition at line 81 of file large_pool.c.
tb_pointer_t tb_large_pool_malloc0_ (tb_large_pool_ref_t pool, tb_size_t size, tb_size_t *real __tb_debug_decl__)
malloc data and fill zero
Parameters
pool the pool
size the size
real the real allocated size >= size, optional
Returns
the data address
Definition at line 119 of file large_pool.c.
Referenced by tb_pool_malloc0_().
tb_pointer_t tb_large_pool_malloc_ (tb_large_pool_ref_t pool, tb_size_t size, tb_size_t *real __tb_debug_decl__)
malloc data
Parameters
pool the pool
size the size
real the real allocated size >= size, optional
Returns
the data address
Definition at line 104 of file large_pool.c.
Referenced by tb_pool_malloc_(), and tb_pool_ralloc_().
tb_pointer_t tb_large_pool_nalloc0_ (tb_large_pool_ref_t pool, tb_size_t item, tb_size_t size, tb_size_t *real __tb_debug_decl__)
malloc data with the item count and fill zero
Parameters
pool the pool
item the item count
size the item size
real the real allocated size >= item * size, optional
Returns
the data address
Definition at line 152 of file large_pool.c.
Referenced by tb_pool_nalloc0_().
tb_pointer_t tb_large_pool_nalloc_ (tb_large_pool_ref_t pool, tb_size_t item, tb_size_t size, tb_size_t *real __tb_debug_decl__)
malloc data with the item count
Parameters
pool the pool
item the item count
size the item size
real the real allocated size >= item * size, optional
Returns
the data address
Definition at line 137 of file large_pool.c.
Referenced by tb_pool_nalloc_().
tb_pointer_t tb_large_pool_ralloc_ (tb_large_pool_ref_t pool, tb_pointer_t data, tb_size_t size, tb_size_t *real __tb_debug_decl__)
realloc data
Parameters
pool the pool
data the data address
size the data size
real the real allocated size >= size, optional
Returns
the new data address
Definition at line 170 of file large_pool.c.
Referenced by tb_pool_ralloc_().