TBOX: src/tbox/memory/small_pool.h File Reference
small_pool.h File Reference
Memory
#include "large_pool.h"
Data Structures
struct tb_small_pool_ref_t
Macros
#define TB_SMALL_POOL_DATA_SIZE_MAXN (3072)
#define tb_small_pool_malloc(pool, size) tb_small_pool_malloc_(pool, size __tb_debug_vals__)
#define tb_small_pool_malloc0(pool, size) tb_small_pool_malloc0_(pool, size __tb_debug_vals__)
#define tb_small_pool_nalloc(pool, item, size) tb_small_pool_nalloc_(pool, item, size __tb_debug_vals__)
#define tb_small_pool_nalloc0(pool, item, size) tb_small_pool_nalloc0_(pool, item, size __tb_debug_vals__)
#define tb_small_pool_ralloc(pool, data, size) tb_small_pool_ralloc_(pool, (tb_pointer_t)(data), size __tb_debug_vals__)
#define tb_small_pool_free(pool, data) tb_small_pool_free_(pool, (tb_pointer_t)(data) __tb_debug_vals__)
Functions
tb_small_pool_ref_t tb_small_pool_init (tb_large_pool_ref_t large_pool)
tb_void_t tb_small_pool_exit (tb_small_pool_ref_t pool)
tb_void_t tb_small_pool_clear (tb_small_pool_ref_t pool)
tb_pointer_t tb_small_pool_malloc_ (tb_small_pool_ref_t pool, tb_size_t size __tb_debug_decl__)
tb_pointer_t tb_small_pool_malloc0_ (tb_small_pool_ref_t pool, tb_size_t size __tb_debug_decl__)
tb_pointer_t tb_small_pool_nalloc_ (tb_small_pool_ref_t pool, tb_size_t item, tb_size_t size __tb_debug_decl__)
tb_pointer_t tb_small_pool_nalloc0_ (tb_small_pool_ref_t pool, tb_size_t item, tb_size_t size __tb_debug_decl__)
tb_pointer_t tb_small_pool_ralloc_ (tb_small_pool_ref_t pool, tb_pointer_t data, tb_size_t size __tb_debug_decl__)
tb_bool_t tb_small_pool_free_ (tb_small_pool_ref_t pool, tb_pointer_t data __tb_debug_decl__)
Detailed Description
The Treasure Box Library
TBox is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 2.1 of the License, or (at your option) any later version.
TBox is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with TBox; If not, see http://www.gnu.org/licenses/
Copyright (C) 2009 - 2015, ruki All rights reserved.
Author
ruki
Definition in file small_pool.h.
Function Documentation
tb_void_t tb_small_pool_clear (tb_small_pool_ref_t pool)
clear the pool
Parameters
pool the pool
Definition at line 256 of file small_pool.c.
References tb_fixed_pool_clear().
tb_void_t tb_small_pool_exit (tb_small_pool_ref_t pool)
exit the pool
Parameters
pool the pool
Definition at line 237 of file small_pool.c.
References tb_fixed_pool_exit().
Referenced by tb_pool_exit(), and tb_small_pool_init().
tb_bool_t tb_small_pool_free_ (tb_small_pool_ref_t pool, tb_pointer_t data __tb_debug_decl__)
free data
Parameters
pool the pool
data the data address
Returns
tb_true or tb_false
Definition at line 539 of file small_pool.c.
References tb_fixed_pool_free_(), and tb_fixed_pool_item_size().
Referenced by tb_pool_free_(), and tb_pool_ralloc_().
tb_small_pool_ref_t tb_small_pool_init (tb_large_pool_ref_t large_pool)
init the small pool only for size <=3KB
Parameters
large_pool the large pool, using the default large pool if be null
Returns
the pool
Definition at line 204 of file small_pool.c.
References tb_large_pool(), and tb_small_pool_exit().
Referenced by tb_pool_init().
tb_pointer_t tb_small_pool_malloc0_ (tb_small_pool_ref_t pool, tb_size_t size __tb_debug_decl__)
malloc data and fill zero
Parameters
pool the pool
size the size
Returns
the data address
Definition at line 315 of file small_pool.c.
References tb_fixed_pool_malloc0_().
Referenced by tb_pool_malloc0_().
tb_pointer_t tb_small_pool_malloc_ (tb_small_pool_ref_t pool, tb_size_t size __tb_debug_decl__)
malloc data
Parameters
pool the pool
size the size
Returns
the data address
Definition at line 271 of file small_pool.c.
References tb_fixed_pool_malloc_().
Referenced by tb_pool_malloc_(), and tb_pool_ralloc_().
tb_pointer_t tb_small_pool_nalloc0_ (tb_small_pool_ref_t pool, tb_size_t item, tb_size_t size __tb_debug_decl__)
malloc data with the item count and fill zero
Parameters
pool the pool
item the item count
size the item size
Returns
the data address
Definition at line 403 of file small_pool.c.
References tb_fixed_pool_malloc0_().
Referenced by tb_pool_nalloc0_().
tb_pointer_t tb_small_pool_nalloc_ (tb_small_pool_ref_t pool, tb_size_t item, tb_size_t size __tb_debug_decl__)
malloc data with the item count
Parameters
pool the pool
item the item count
size the item size
Returns
the data address
Definition at line 359 of file small_pool.c.
References tb_fixed_pool_malloc_().
Referenced by tb_pool_nalloc_().
tb_pointer_t tb_small_pool_ralloc_ (tb_small_pool_ref_t pool, tb_pointer_t data, tb_size_t size __tb_debug_decl__)
realloc data
Parameters
pool the pool
data the data address
size the data size
Returns
the new data address
Definition at line 447 of file small_pool.c.
References tb_fixed_pool_free_(), tb_fixed_pool_item_size(), and tb_fixed_pool_malloc_().
Referenced by tb_pool_ralloc_().