TBOX: src/string/sstring.h File Reference
sstring.h File Reference
String
#include "prefix.h"
#include "../memory/memory.h"
Typedefs
typedef tb_sbuffer_t tb_sstring_t
the static string type
Functions
tb_bool_t tb_sstring_init (tb_sstring_t *string, tb_char_t *data, tb_size_t maxn)
tb_void_t tb_sstring_exit (tb_sstring_t *string)
tb_char_t const * tb_sstring_cstr (tb_sstring_t const *string)
tb_size_t tb_sstring_size (tb_sstring_t const *string)
tb_void_t tb_sstring_clear (tb_sstring_t *string)
tb_char_t const * tb_sstring_strip (tb_sstring_t *string, tb_size_t n)
tb_long_t tb_sstring_strchr (tb_sstring_t const *string, tb_size_t p, tb_char_t c)
tb_long_t tb_sstring_strichr (tb_sstring_t const *string, tb_size_t p, tb_char_t c)
tb_long_t tb_sstring_strrchr (tb_sstring_t const *string, tb_size_t p, tb_char_t c)
tb_long_t tb_sstring_strirchr (tb_sstring_t const *string, tb_size_t p, tb_char_t c)
tb_long_t tb_sstring_strstr (tb_sstring_t const *string, tb_size_t p, tb_sstring_t const *s)
tb_long_t tb_sstring_stristr (tb_sstring_t const *string, tb_size_t p, tb_sstring_t const *s)
tb_long_t tb_sstring_cstrstr (tb_sstring_t const *string, tb_size_t p, tb_char_t const *s)
tb_long_t tb_sstring_cstristr (tb_sstring_t const *string, tb_size_t p, tb_char_t const *s)
tb_long_t tb_sstring_strrstr (tb_sstring_t const *string, tb_size_t p, tb_sstring_t const *s)
tb_long_t tb_sstring_strirstr (tb_sstring_t const *string, tb_size_t p, tb_sstring_t const *s)
tb_long_t tb_sstring_cstrrstr (tb_sstring_t const *string, tb_size_t p, tb_char_t const *s)
tb_long_t tb_sstring_cstrirstr (tb_sstring_t const *string, tb_size_t p, tb_char_t const *s)
tb_char_t const * tb_sstring_strcpy (tb_sstring_t *string, tb_sstring_t const *s)
tb_char_t const * tb_sstring_cstrcpy (tb_sstring_t *string, tb_char_t const *s)
tb_char_t const * tb_sstring_cstrncpy (tb_sstring_t *string, tb_char_t const *s, tb_size_t n)
tb_char_t const * tb_sstring_cstrfcpy (tb_sstring_t *string, tb_char_t const *fmt,...)
tb_char_t const * tb_sstring_chrcat (tb_sstring_t *string, tb_char_t c)
tb_char_t const * tb_sstring_chrncat (tb_sstring_t *string, tb_char_t c, tb_size_t n)
tb_char_t const * tb_sstring_strcat (tb_sstring_t *string, tb_sstring_t const *s)
tb_char_t const * tb_sstring_cstrcat (tb_sstring_t *string, tb_char_t const *s)
tb_char_t const * tb_sstring_cstrncat (tb_sstring_t *string, tb_char_t const *s, tb_size_t n)
tb_char_t const * tb_sstring_cstrfcat (tb_sstring_t *string, tb_char_t const *fmt,...)
tb_long_t tb_sstring_strcmp (tb_sstring_t *string, tb_sstring_t const *s)
tb_long_t tb_sstring_strimp (tb_sstring_t *string, tb_sstring_t const *s)
tb_long_t tb_sstring_cstrcmp (tb_sstring_t *string, tb_char_t const *s)
tb_long_t tb_sstring_cstricmp (tb_sstring_t *string, tb_char_t const *s)
tb_long_t tb_sstring_cstrncmp (tb_sstring_t *string, tb_char_t const *s, tb_size_t n)
tb_long_t tb_sstring_cstrnicmp (tb_sstring_t *string, tb_char_t const *s, tb_size_t n)
Detailed Description
The Treasure Box Library
TBox is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 2.1 of the License, or (at your option) any later version.
TBox is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with TBox; If not, see http://www.gnu.org/licenses/
Copyright (C) 2009 - 2015, ruki All rights reserved.
Author
ruki
Definition in file sstring.h.
Function Documentation
tb_char_t const* tb_sstring_chrcat (tb_sstring_t * string, tb_char_t c)
append charactor
Parameters
string the string
c the appended charactor
Returns
the c-string
Definition at line 245 of file sstring.c.
References tb_sstring_size().
tb_char_t const* tb_sstring_chrncat (tb_sstring_t * string, tb_char_t c, tb_size_t n)
append charactor with the given size
Parameters
string the string
c the appended charactor
n the appended size
Returns
the c-string
Definition at line 253 of file sstring.c.
References tb_sstring_size().
tb_void_t tb_sstring_clear (tb_sstring_t * string)
clear the string
Parameters
string the string
Definition at line 74 of file sstring.c.
Referenced by tb_sstring_strcpy().
tb_char_t const* tb_sstring_cstr (tb_sstring_t const * string)
the c-string pointer
Parameters
string the string
Returns
the c-string
Definition at line 58 of file sstring.c.
Referenced by tb_sstring_cstrirstr(), tb_sstring_cstristr(), tb_sstring_cstrncmp(), tb_sstring_cstrnicmp(), tb_sstring_cstrrstr(), tb_sstring_cstrstr(), tb_sstring_strcat(), tb_sstring_strchr(), tb_sstring_strcmp(), tb_sstring_strcpy(), tb_sstring_strichr(), tb_sstring_strimp(), tb_sstring_strip(), tb_sstring_strirchr(), tb_sstring_strirstr(), tb_sstring_stristr(), tb_sstring_strrchr(), tb_sstring_strrstr(), and tb_sstring_strstr().
tb_char_t const* tb_sstring_cstrcat (tb_sstring_t * string, tb_char_t const * s)
append c-string
Parameters
string the string
s the appended c-string
Returns
the c-string
Definition at line 269 of file sstring.c.
References tb_sstring_cstrncat().
tb_long_t tb_sstring_cstrcmp (tb_sstring_t * string, tb_char_t const * s)
compare c-string
Parameters
string the string
s the compared c-string
Returns
equal: 0
Definition at line 307 of file sstring.c.
References tb_sstring_cstrncmp().
tb_char_t const* tb_sstring_cstrcpy (tb_sstring_t * string, tb_char_t const * s)
copy c-string
Parameters
string the string
s the copied c-string
Returns
the c-string
Definition at line 217 of file sstring.c.
References tb_sstring_cstrncpy().
Referenced by tb_dns_looker_init().
tb_char_t const* tb_sstring_cstrfcat (tb_sstring_t * string, tb_char_t const * fmt, ...)
append format c-string
Parameters
string the string
fmt the appended format c-string
Returns
the c-string
Definition at line 281 of file sstring.c.
References tb_sstring_cstrncat().
tb_char_t const* tb_sstring_cstrfcpy (tb_sstring_t * string, tb_char_t const * fmt, ...)
copy format c-string
Parameters
string the string
fmt the copied format c-string
Returns
the c-string
Definition at line 230 of file sstring.c.
References tb_sstring_cstrncpy().
tb_long_t tb_sstring_cstricmp (tb_sstring_t * string, tb_char_t const * s)
compare c-string and ignore case
Parameters
string the string
s the compared c-string
Returns
equal: 0
Definition at line 312 of file sstring.c.
References tb_sstring_cstrnicmp().
tb_long_t tb_sstring_cstrirstr (tb_sstring_t const * string, tb_size_t p, tb_char_t const * s)
reverse to find c-string position and ignore case
Parameters
string the string
p the start position
s the finded c-string
Returns
the real position, no find: -1
Definition at line 192 of file sstring.c.
References tb_sstring_cstr(), and tb_sstring_size().
Referenced by tb_sstring_strirstr().
tb_long_t tb_sstring_cstristr (tb_sstring_t const * string, tb_size_t p, tb_char_t const * s)
find c-string position and ignore case
Parameters
string the string
p the start position
s the finded c-string
Returns
the real position, no find: -1
Definition at line 161 of file sstring.c.
References tb_sstring_cstr(), and tb_sstring_size().
Referenced by tb_sstring_stristr().
tb_char_t const* tb_sstring_cstrncat (tb_sstring_t * string, tb_char_t const * s, tb_size_t n)
append c-string with the given size
Parameters
string the string
s the appended c-string
n the appended c-string size
Returns
the c-string
Definition at line 274 of file sstring.c.
References tb_sstring_size().
Referenced by tb_sstring_cstrcat(), tb_sstring_cstrfcat(), and tb_sstring_strcat().
tb_long_t tb_sstring_cstrncmp (tb_sstring_t * string, tb_char_t const * s, tb_size_t n)
compare c-string with given size
Parameters
string the string
s the compared c-string #param n the compared c-string size
Returns
equal: 0
Definition at line 317 of file sstring.c.
References tb_sstring_cstr().
Referenced by tb_sstring_cstrcmp(), and tb_sstring_strcmp().
tb_char_t const* tb_sstring_cstrncpy (tb_sstring_t * string, tb_char_t const * s, tb_size_t n)
copy c-string with the given size
Parameters
string the string
s the copied c-string
n the copied c-string size
Returns
the c-string
Definition at line 222 of file sstring.c.
References tb_sstring_size().
Referenced by tb_sstring_cstrcpy(), tb_sstring_cstrfcpy(), and tb_sstring_strcpy().
tb_long_t tb_sstring_cstrnicmp (tb_sstring_t * string, tb_char_t const * s, tb_size_t n)
compare c-string with given size and ignore case
Parameters
string the string
s the compared c-string #param n the compared c-string size
Returns
equal: 0
Definition at line 322 of file sstring.c.
References tb_sstring_cstr().
Referenced by tb_sstring_cstricmp(), and tb_sstring_strimp().
tb_long_t tb_sstring_cstrrstr (tb_sstring_t const * string, tb_size_t p, tb_char_t const * s)
reverse to find c-string position
Parameters
string the string
p the start position
s the finded c-string
Returns
the real position, no find: -1
Definition at line 183 of file sstring.c.
References tb_sstring_cstr(), and tb_sstring_size().
Referenced by tb_sstring_strrstr().
tb_long_t tb_sstring_cstrstr (tb_sstring_t const * string, tb_size_t p, tb_char_t const * s)
find c-string position
Parameters
string the string
p the start position
s the finded c-string
Returns
the real position, no find: -1
Definition at line 152 of file sstring.c.
References tb_sstring_cstr(), and tb_sstring_size().
Referenced by tb_sstring_strstr().
tb_void_t tb_sstring_exit (tb_sstring_t * string)
exit string
Parameters
string the string
Definition at line 50 of file sstring.c.
tb_bool_t tb_sstring_init (tb_sstring_t * string, tb_char_t * data, tb_size_t maxn)
init string
Parameters
string the string
data the data
maxn the maxn
Returns
tb_true or tb_false
Definition at line 45 of file sstring.c.
Referenced by tb_dns_looker_init().
tb_size_t tb_sstring_size (tb_sstring_t const * string)
the string size
Parameters
string the string
Returns
the string size
Definition at line 63 of file sstring.c.
Referenced by tb_sstring_chrcat(), tb_sstring_chrncat(), tb_sstring_cstrirstr(), tb_sstring_cstristr(), tb_sstring_cstrncat(), tb_sstring_cstrncpy(), tb_sstring_cstrrstr(), tb_sstring_cstrstr(), tb_sstring_strcat(), tb_sstring_strchr(), tb_sstring_strcmp(), tb_sstring_strcpy(), tb_sstring_strichr(), tb_sstring_strimp(), tb_sstring_strip(), tb_sstring_strirchr(), and tb_sstring_strrchr().
tb_char_t const* tb_sstring_strcat (tb_sstring_t * string, tb_sstring_t const * s)
append string
Parameters
string the string
s the appended string
Returns
the c-string
Definition at line 264 of file sstring.c.
References tb_sstring_cstr(), tb_sstring_cstrncat(), and tb_sstring_size().
tb_long_t tb_sstring_strchr (tb_sstring_t const * string, tb_size_t p, tb_char_t c)
find charactor position
Parameters
string the string
p the start position
c the finded charactor
Returns
the real position, no find: -1
Definition at line 100 of file sstring.c.
References tb_sstring_cstr(), and tb_sstring_size().
tb_long_t tb_sstring_strcmp (tb_sstring_t * string, tb_sstring_t const * s)
compare string
Parameters
string the string
s the compared string
Returns
equal: 0
Definition at line 297 of file sstring.c.
References tb_sstring_cstr(), tb_sstring_cstrncmp(), and tb_sstring_size().
tb_char_t const* tb_sstring_strcpy (tb_sstring_t * string, tb_sstring_t const * s)
copy string
Parameters
string the string
s the copied string
Returns
the c-string
Definition at line 205 of file sstring.c.
References tb_sstring_clear(), tb_sstring_cstr(), tb_sstring_cstrncpy(), and tb_sstring_size().
tb_long_t tb_sstring_strichr (tb_sstring_t const * string, tb_size_t p, tb_char_t c)
find charactor position and ignore case
Parameters
string the string
p the start position
c the finded charactor
Returns
the real position, no find: -1
Definition at line 109 of file sstring.c.
References tb_sstring_cstr(), and tb_sstring_size().
tb_long_t tb_sstring_strimp (tb_sstring_t * string, tb_sstring_t const * s)
compare string and ignore case
Parameters
string the string
s the compared string
Returns
equal: 0
Definition at line 302 of file sstring.c.
References tb_sstring_cstr(), tb_sstring_cstrnicmp(), and tb_sstring_size().
tb_char_t const* tb_sstring_strip (tb_sstring_t * string, tb_size_t n)
strip the string
Parameters
string the string
n the striped size
Returns
the c-string
Definition at line 85 of file sstring.c.
References tb_sstring_cstr(), and tb_sstring_size().
tb_long_t tb_sstring_strirchr (tb_sstring_t const * string, tb_size_t p, tb_char_t c)
reverse to find charactor position and ignore case
Parameters
string the string
p the start position
c the finded charactor
Returns
the real position, no find: -1
Definition at line 131 of file sstring.c.
References tb_sstring_cstr(), and tb_sstring_size().
tb_long_t tb_sstring_strirstr (tb_sstring_t const * string, tb_size_t p, tb_sstring_t const * s)
reverse to find string position and ignore case
Parameters
string the string
p the start position
s the finded string
Returns
the real position, no find: -1
Definition at line 178 of file sstring.c.
References tb_sstring_cstr(), and tb_sstring_cstrirstr().
tb_long_t tb_sstring_stristr (tb_sstring_t const * string, tb_size_t p, tb_sstring_t const * s)
find string position and ignore case
Parameters
string the string
p the start position
s the finded string
Returns
the real position, no find: -1
Definition at line 148 of file sstring.c.
References tb_sstring_cstr(), and tb_sstring_cstristr().
tb_long_t tb_sstring_strrchr (tb_sstring_t const * string, tb_size_t p, tb_char_t c)
reverse to find charactor position
Parameters
string the string
p the start position
c the finded charactor
Returns
the real position, no find: -1
Definition at line 122 of file sstring.c.
References tb_sstring_cstr(), and tb_sstring_size().
tb_long_t tb_sstring_strrstr (tb_sstring_t const * string, tb_size_t p, tb_sstring_t const * s)
reverse to find string position
Parameters
string the string
p the start position
s the finded string
Returns
the real position, no find: -1
Definition at line 174 of file sstring.c.
References tb_sstring_cstr(), and tb_sstring_cstrrstr().
tb_long_t tb_sstring_strstr (tb_sstring_t const * string, tb_size_t p, tb_sstring_t const * s)
find string position
Parameters
string the string
p the start position
s the finded string
Returns
the real position, no find: -1
Definition at line 144 of file sstring.c.
References tb_sstring_cstr(), and tb_sstring_cstrstr().