TBOX: src/tbox/stream/transfer_pool.h File Reference
transfer_pool.h File Reference
Stream
#include "prefix.h"
#include "transfer.h"
#include "../asio/asio.h"
Data Structures
struct tb_transfer_pool_ref_t
the transfer pool ref type
Functions
tb_transfer_pool_ref_t tb_transfer_pool (tb_noarg_t)
tb_transfer_pool_ref_t tb_transfer_pool_init (tb_aicp_ref_t aicp)
tb_bool_t tb_transfer_pool_exit (tb_transfer_pool_ref_t pool)
tb_void_t tb_transfer_pool_kill (tb_transfer_pool_ref_t pool)
tb_void_t tb_transfer_pool_kill_all (tb_transfer_pool_ref_t pool)
tb_long_t tb_transfer_pool_wait_all (tb_transfer_pool_ref_t pool, tb_long_t timeout)
tb_size_t tb_transfer_pool_size (tb_transfer_pool_ref_t pool)
tb_size_t tb_transfer_pool_maxn (tb_transfer_pool_ref_t pool)
tb_bool_t tb_transfer_pool_done (tb_transfer_pool_ref_t pool, tb_char_t const *iurl, tb_char_t const *ourl, tb_hize_t offset, tb_size_t rate, tb_async_transfer_done_func_t done, tb_async_transfer_ctrl_func_t ctrl, tb_cpointer_t priv)
Detailed Description
The Treasure Box Library
TBox is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 2.1 of the License, or (at your option) any later version.
TBox is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with TBox; If not, see http://www.gnu.org/licenses/
Copyright (C) 2009 - 2015, ruki All rights reserved.
Author
ruki
Definition in file transfer_pool.h.
Function Documentation
tb_transfer_pool_ref_t tb_transfer_pool (tb_noarg_t)
the transfer pool instance
Returns
the transfer pool instance
tb_bool_t tb_transfer_pool_done (tb_transfer_pool_ref_t pool, tb_char_t const * iurl, tb_char_t const * ourl, tb_hize_t offset, tb_size_t rate, tb_async_transfer_done_func_t done, tb_async_transfer_ctrl_func_t ctrl, tb_cpointer_t priv)
done transfer from iurl to ourl
Parameters
pool the transfer pool
iurl the input url
ourl the output url
offset the offset
rate the limited rate, not limit if be zero
done the done func
ctrl the ctrl func
priv the func private data
Returns
tb_true or tb_false
Definition at line 488 of file transfer_pool.c.
References tb_async_transfer_init_istream_from_url(), tb_async_transfer_init_ostream_from_url(), tb_async_transfer_limitrate(), and tb_async_transfer_open_done().
tb_bool_t tb_transfer_pool_exit (tb_transfer_pool_ref_t pool)
exit transfer pool
Parameters
pool the transfer pool
Returns
tb_true or tb_false
Definition at line 403 of file transfer_pool.c.
References tb_fixed_pool_exit(), tb_fixed_pool_walk(), tb_list_entry_exit(), tb_transfer_pool_kill(), and tb_transfer_pool_wait_all().
Referenced by tb_transfer_pool_init().
tb_transfer_pool_ref_t tb_transfer_pool_init (tb_aicp_ref_t aicp)
init transfer pool
Parameters
aicp the aicp, using the default aicp if be null
Returns
the transfer pool
Definition at line 280 of file transfer_pool.c.
References tb_aicp(), tb_aicp_maxn(), tb_list_entry_init, tb_lock_profiler(), tb_lock_profiler_register(), and tb_transfer_pool_exit().
tb_void_t tb_transfer_pool_kill (tb_transfer_pool_ref_t pool)
kill transfer pool
Parameters
pool the transfer pool
Definition at line 331 of file transfer_pool.c.
References tb_transfer_pool_kill_all().
Referenced by tb_transfer_pool_exit().
tb_void_t tb_transfer_pool_kill_all (tb_transfer_pool_ref_t pool)
kill all working tasks
Parameters
pool the transfer pool handle
Definition at line 344 of file transfer_pool.c.
References tb_list_entry_itor(), and tb_walk_all().
Referenced by tb_transfer_pool_kill().
tb_size_t tb_transfer_pool_maxn (tb_transfer_pool_ref_t pool)
the transfer pool maxn
Parameters
pool the transfer pool
Definition at line 461 of file transfer_pool.c.
tb_size_t tb_transfer_pool_size (tb_transfer_pool_ref_t pool)
the transfer pool size
Parameters
pool the transfer pool
Definition at line 470 of file transfer_pool.c.
tb_long_t tb_transfer_pool_wait_all (tb_transfer_pool_ref_t pool, tb_long_t timeout)
wait all working tasks
Parameters
pool the transfer pool handle
timeout the timeout
Returns
ok: 1, timeout: 0, error: -1
Definition at line 365 of file transfer_pool.c.
References tb_cache_time_spak(), tb_list_entry_itor(), and tb_walk_all().
Referenced by tb_transfer_pool_exit().