TBOX: src/tbox/libc/stdio/stdio.h File Reference
stdio.h File Reference
Libc
#include "prefix.h"
Macros
#define tb_vsnprintf_format(s, n, format, r)
#define tb_vswprintf_format(s, n, format, r)
Functions
tb_long_t tb_puts (tb_char_t const *string)
tb_long_t tb_wputs (tb_wchar_t const *string)
tb_long_t tb_printf (tb_char_t const *format,...)
tb_long_t tb_wprintf (tb_wchar_t const *format,...)
tb_long_t tb_sprintf (tb_char_t *s, tb_char_t const *format,...)
tb_long_t tb_snprintf (tb_char_t *s, tb_size_t n, tb_char_t const *format,...)
tb_long_t tb_vsnprintf (tb_char_t *s, tb_size_t n, tb_char_t const *format, tb_va_list_t args)
tb_long_t tb_swprintf (tb_wchar_t *s, tb_size_t n, tb_wchar_t const *format,...)
tb_long_t tb_vswprintf (tb_wchar_t *s, tb_size_t n, tb_wchar_t const *format, tb_va_list_t args)
Detailed Description
The Treasure Box Library
TBox is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 2.1 of the License, or (at your option) any later version.
TBox is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with TBox; If not, see http://www.gnu.org/licenses/
Copyright (C) 2009 - 2015, ruki All rights reserved.
Author
ruki
Definition in file stdio.h.
Macro Definition Documentation
#define tb_vsnprintf_format (s, n, format, r)
Value:
do \
{ \
    tb_long_t __tb_ret = 0; \
    tb_va_list_t __tb_varg_list; \
    tb_va_start(__tb_varg_list, format); \
    __tb_ret = tb_vsnprintf(s, (n), format, __tb_varg_list); \
    tb_va_end(__tb_varg_list); \
    if (__tb_ret >= 0) s[__tb_ret] = '\0'; \
    *r = __tb_ret > 0? __tb_ret : 0; \
 \
} while (0)
Definition at line 42 of file stdio.h.
#define tb_vswprintf_format (s, n, format, r)
Value:
do \
{ \
    tb_long_t __tb_ret = 0; \
    tb_va_list_t __tb_varg_list; \
    tb_va_start(__tb_varg_list, format); \
    __tb_ret = tb_vswprintf(s, (n), format, __tb_varg_list); \
    tb_va_end(__tb_varg_list); \
    if (__tb_ret >= 0) s[__tb_ret] = L'\0'; \
    *r = __tb_ret > 0? __tb_ret : 0; \
 \
} while (0)
Definition at line 56 of file stdio.h.
Function Documentation
tb_long_t tb_printf (tb_char_t const * format, ...)
printf
Parameters
format the format string
Returns
the real size
Definition at line 35 of file printf.c.
References tb_print().
Referenced by tb_bloom_filter_init(), and tb_object_dump().
tb_long_t tb_puts (tb_char_t const * string)
puts
Parameters
string the string
Returns
the real size
Definition at line 36 of file puts.c.
References tb_printl().
tb_long_t tb_snprintf (tb_char_t * s, tb_size_t n, tb_char_t const * format, ...)
snprintf
Parameters
s the string data
n the string size
format the format string
Returns
the real size
Definition at line 34 of file snprintf.c.
Referenced by tb_ipv4_get(), and tb_trace_done_with_args().
tb_long_t tb_sprintf (tb_char_t * s, tb_char_t const * format, ...)
sprintf
Parameters
s the string data
format the format string
Returns
the real size
Definition at line 34 of file sprintf.c.
tb_long_t tb_swprintf (tb_wchar_t * s, tb_size_t n, tb_wchar_t const * format, ...)
swprintf
Parameters
s the string data
n the string size
format the format string
Returns
the real size
Definition at line 34 of file swprintf.c.
tb_long_t tb_vsnprintf (tb_char_t * s, tb_size_t n, tb_char_t const * fmt, tb_va_list_t args)
vsnprintf
Parameters
s the string data
n the string size
format the format string
args the arguments
Returns
the real size
format a string and place it in a buffer
Parameters
s the buffer to place the result into
n the size of the buffer, including the trailing null space
fmt the format string to use
args arguments for the format string
Returns
the number of characters which would be generated for the given input, excluding the trailing '\0'.
format: %[flags][width][.precision][qualifier]type
flags:
default: right-justified, left-pad the output with spaces until the required length of output is attained. If combined with '0' (see below), it will cause the sign to become a space when positive, but the remaining characters will be zero-padded
-: left-justified, e.g. %-d
+: denote the sign '+' or '-' of a number
0: use 0 instead of spaces to left-fill a fixed-length field
#: add prefix or suffix
%#o => add prefix: 0...
%#x => add prefix: 0x...
%#X => add prefix: 0X...
%#b => add prefix: 0b...
%#B => add prefix: 0B...
%#f => add prefix: 0f...
%#F => add prefix: 0F...
width:
n: n = 1, 2, 3, ..., fill spaces
0n: n = 1, 2, 3, ..., fill 0
*: causes printf to pad the output until it is n characters wide, where n is an integer value stored in the a function argument just preceding that represented by the modified type. e.g. printf("%*d", 5, 10) will result in "10" being printed with a width of 5.
.precision:
.n: for non-integral numeric types, causes the decimal portion of the output to be expressed in at least number digits. for the string type, causes the output to be truncated at number characters. if the precision is zero, nothing is printed for the corresponding argument.
*: same as the above, but uses an integer value in the intaken argument to determine the number of decimal places or maximum string length. e.g. printf("%.*s", 3, "abcdef") will result in "abc" being printed.
qualifier:
h: short integer or single double-point
l: long integer or double double-point
I8: 8-bit integer
I16: 16-bit integer
I32: 32-bit integer
I64/ll: 64-bit integer
Note
support h, l, I8, I16, I32, I64, ll
type(e.g. d x u %% ...):
d, i: print an int as a signed decimal number. 'd' and 'i' are synonymous for output, but are different when used with scanf() for input.
u: print decimal unsigned int.
o: print an unsigned int in octal.
x/X: print an unsigned int as a hexadecimal number. 'x' uses lower-case letters and 'X' uses upper-case.
b/B: print an unsigned binary interger
e/E: print a double value in standard form ([-]d.ddd e[+/-]ddd). An E conversion uses the letter E (rather than e) to introduce the exponent. The exponent always contains at least two digits; if the value is zero, the exponent is 00. e.g. 3.141593e+00
f/F: Print a double in normal (fixed-point) notation. 'f' and 'F' only differs in how the strings for an infinite number or NaN are printed ('inf', 'infinity' and 'nan' for 'f', 'INF', 'INFINITY' and 'NAN' for 'F').
g/G: print a double in either normal or exponential notation, whichever is more appropriate for its magnitude. 'g' uses lower-case letters, 'G' uses upper-case letters. This type differs slightly from fixed-point notation in that insignificant zeroes to the right of the decimal point are not included. Also, the decimal point is not included on whole numbers.
c: print a char (character).
s: print a character string
p: print a void * (pointer to void) in an implementation-defined format.
n: print nothing, but write number of characters successfully written so far into an integer pointer parameter.
%: %
Note
support d, i, u, o, u, x/X, b/B, f/F, c, s
not support e/E, g/G, p, n
e.g.
tb_printf("|hello world|\n");
tb_printf("|%-10s|%%|%10s|\n", "hello", "world");
tb_printf("|%#2c|%2.5c|%*c|\n", 'A', 'B', 5, 'C');
tb_printf("|%#2d|%#8.3o|%*.*d|\n", -56, 56, 10, 5, 56);
tb_printf("|%#-8.5x|%#2.9X|\n", 0x1f, 0x1f);
tb_printf("|%#-8.5b|%#2.9B|\n", 0x1f, 0x1f);
tb_printf("|%-6Id|%5I8u|%#I64x|%#llx|\n", 256, 255, (tb_int64_t)0x8fffffffffff, (tb_int64_t)0x8fffffffffff);
tb_printf("|%lf|\n", -3.1415926535897932384626433832795);
tb_printf("|%lf|%lf|%lf|\n", 3.14, 0, -0);
tb_printf("|%0.9f|\n", 3.1415926535897932384626433832795);
tb_printf("|%16.9f|\n", 3.1415926535897932384626433832795);
tb_printf("|%016.9f|\n", 3.14159);
tb_printf("|%lf|\n", 1.0 / 6.0);
tb_printf("|%lf|\n", 0.0003141596);
Definition at line 1000 of file vsnprintf.c.
Referenced by tb_trace_done_with_args(), and tb_trace_tail().
tb_long_t tb_vswprintf (tb_wchar_t * s, tb_size_t n, tb_wchar_t const * fmt, tb_va_list_t args)
vswprintf
Parameters
s the string data
n the string size
format the format string
args the arguments
Returns
the real size
format a string and place it in a buffer
Parameters
s the buffer to place the result into
n the size of the buffer, including the trailing null space
fmt the format string to use
args arguments for the format string
Returns
the number of characters which would be generated for the given input, excluding the trailing '\0'.
format: %[flags][width][.precision][qualifier]type
flags:
default: right-justified, left-pad the output with spaces until the required length of output is attained. If combined with '0' (see below), it will cause the sign to become a space when positive, but the remaining characters will be zero-padded
-: left-justified, e.g. %-d
+: denote the sign '+' or '-' of a number
0: use 0 instead of spaces to left-fill a fixed-length field
#: add prefix or suffix
%#o => add prefix: 0...
%#x => add prefix: 0x...
%#X => add prefix: 0X...
%#b => add prefix: 0b...
%#B => add prefix: 0B...
%#f => add prefix: 0f...
%#F => add prefix: 0F...
width:
n: n = 1, 2, 3, ..., fill spaces
0n: n = 1, 2, 3, ..., fill 0
*: causes printf to pad the output until it is n characters wide, where n is an integer value stored in the a function argument just preceding that represented by the modified type. e.g. printf("%*d", 5, 10) will result in "10" being printed with a width of 5.
.precision:
.n: for non-integral numeric types, causes the decimal portion of the output to be expressed in at least number digits. for the string type, causes the output to be truncated at number characters. if the precision is zero, nothing is printed for the corresponding argument.
*: same as the above, but uses an integer value in the intaken argument to determine the number of decimal places or maximum string length. e.g. printf("%.*s", 3, "abcdef") will result in "abc" being printed.
qualifier:
h: short integer or single double-point
l: long integer or double double-point
I8: 8-bit integer
I16: 16-bit integer
I32: 32-bit integer
I64/ll: 64-bit integer
Note
support h, l, I8, I16, I32, I64, ll
type(e.g. d x u %% ...):
d, i: print an int as a signed decimal number. 'd' and 'i' are synonymous for output, but are different when used with scanf() for input.
u: print decimal unsigned int.
o: print an unsigned int in octal.
x/X: print an unsigned int as a hexadecimal number. 'x' uses lower-case letters and 'X' uses upper-case.
b/B: print an unsigned binary interger
e/E: print a double value in standard form ([-]d.ddd e[+/-]ddd). An E conversion uses the letter E (rather than e) to introduce the exponent. The exponent always contains at least two digits; if the value is zero, the exponent is 00. e.g. 3.141593e+00
f/F: Print a double in normal (fixed-point) notation. 'f' and 'F' only differs in how the strings for an infinite number or NaN are printed ('inf', 'infinity' and 'nan' for 'f', 'INF', 'INFINITY' and 'NAN' for 'F').
g/G: print a double in either normal or exponential notation, whichever is more appropriate for its magnitude. 'g' uses lower-case letters, 'G' uses upper-case letters. This type differs slightly from fixed-point notation in that insignificant zeroes to the right of the decimal point are not included. Also, the decimal point is not included on whole numbers.
c: print a char (character).
s: print a character string
p: print a void * (pointer to void) in an implementation-defined format.
n: print nothing, but write number of characters successfully written so far into an integer pointer parameter.
%: %
Note
support d, i, u, o, u, x/X, b/B, f/F, c, s
not support e/E, g/G, p, n
e.g.
tb_printf("|hello world|\n");
tb_printf("|%-10s|%%|%10s|\n", "hello", "world");
tb_printf("|%#2c|%2.5c|%*c|\n", 'A', 'B', 5, 'C');
tb_printf("|%#2d|%#8.3o|%*.*d|\n", -56, 56, 10, 5, 56);
tb_printf("|%#-8.5x|%#2.9X|\n", 0x1f, 0x1f);
tb_printf("|%#-8.5b|%#2.9B|\n", 0x1f, 0x1f);
tb_printf("|%-6Id|%5I8u|%#I64x|%#llx|\n", 256, 255, (tb_int64_t)0x8fffffffffff, (tb_int64_t)0x8fffffffffff);
tb_printf("|%lf|\n", -3.1415926535897932384626433832795);
tb_printf("|%lf|%lf|%lf|\n", 3.14, 0, -0);
tb_printf("|%0.9f|\n", 3.1415926535897932384626433832795);
tb_printf("|%16.9f|\n", 3.1415926535897932384626433832795);
tb_printf("|%016.9f|\n", 3.14159);
tb_printf("|%lf|\n", 1.0 / 6.0);
tb_printf("|%lf|\n", 0.0003141596);
Definition at line 1002 of file vswprintf.c.
tb_long_t tb_wprintf (tb_wchar_t const * format, ...)
wprintf
Parameters
format the format string
Returns
the real size
Definition at line 36 of file wprintf.c.
References tb_print().
tb_long_t tb_wputs (tb_wchar_t const * string)
wputs
Parameters
string the string
Returns
the real size
Definition at line 36 of file wputs.c.
References tb_printl().