TBOX: src/tbox/object/number.h File Reference
number.h File Reference
Object
#include "prefix.h"
Enumerations
enum tb_object_number_type_e {
TB_NUMBER_TYPE_NONE = 0, TB_NUMBER_TYPE_UINT8 = 1, TB_NUMBER_TYPE_SINT8 = 2, TB_NUMBER_TYPE_UINT16 = 3,
TB_NUMBER_TYPE_SINT16 = 4, TB_NUMBER_TYPE_UINT32 = 5, TB_NUMBER_TYPE_SINT32 = 6, TB_NUMBER_TYPE_UINT64 = 7,
TB_NUMBER_TYPE_SINT64 = 8, TB_NUMBER_TYPE_FLOAT = 9, TB_NUMBER_TYPE_DOUBLE = 10
}
the number type enum
Functions
tb_object_ref_t tb_object_number_init_from_uint8 (tb_uint8_t value)
tb_object_ref_t tb_object_number_init_from_sint8 (tb_sint8_t value)
tb_object_ref_t tb_object_number_init_from_uint16 (tb_uint16_t value)
tb_object_ref_t tb_object_number_init_from_sint16 (tb_sint16_t value)
tb_object_ref_t tb_object_number_init_from_uint32 (tb_uint32_t value)
tb_object_ref_t tb_object_number_init_from_sint32 (tb_sint32_t value)
tb_object_ref_t tb_object_number_init_from_uint64 (tb_uint64_t value)
tb_object_ref_t tb_object_number_init_from_sint64 (tb_sint64_t value)
tb_object_ref_t tb_object_number_init_from_float (tb_float_t value)
tb_object_ref_t tb_object_number_init_from_double (tb_double_t value)
tb_size_t tb_object_number_type (tb_object_ref_t number)
tb_uint8_t tb_object_number_uint8 (tb_object_ref_t number)
tb_sint8_t tb_object_number_sint8 (tb_object_ref_t number)
tb_uint16_t tb_object_number_uint16 (tb_object_ref_t number)
tb_sint16_t tb_object_number_sint16 (tb_object_ref_t number)
tb_uint32_t tb_object_number_uint32 (tb_object_ref_t number)
tb_sint32_t tb_object_number_sint32 (tb_object_ref_t number)
tb_uint64_t tb_object_number_uint64 (tb_object_ref_t number)
tb_sint64_t tb_object_number_sint64 (tb_object_ref_t number)
tb_float_t tb_object_number_float (tb_object_ref_t number)
tb_double_t tb_object_number_double (tb_object_ref_t number)
tb_bool_t tb_object_number_uint8_set (tb_object_ref_t number, tb_uint8_t value)
tb_bool_t tb_object_number_sint8_set (tb_object_ref_t number, tb_sint8_t value)
tb_bool_t tb_object_number_uint16_set (tb_object_ref_t number, tb_uint16_t value)
tb_bool_t tb_object_number_sint16_set (tb_object_ref_t number, tb_sint16_t value)
tb_bool_t tb_object_number_uint32_set (tb_object_ref_t number, tb_uint32_t value)
tb_bool_t tb_object_number_sint32_set (tb_object_ref_t number, tb_sint32_t value)
tb_bool_t tb_object_number_uint64_set (tb_object_ref_t number, tb_uint64_t value)
tb_bool_t tb_object_number_sint64_set (tb_object_ref_t number, tb_sint64_t value)
tb_bool_t tb_object_number_float_set (tb_object_ref_t number, tb_float_t value)
tb_bool_t tb_object_number_double_set (tb_object_ref_t number, tb_double_t value)
Detailed Description
The Treasure Box Library
TBox is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 2.1 of the License, or (at your option) any later version.
TBox is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with TBox; If not, see http://www.gnu.org/licenses/
Copyright (C) 2009 - 2015, ruki All rights reserved.
Author
ruki
Definition in file number.h.
Function Documentation
tb_double_t tb_object_number_double (tb_object_ref_t number)
the double value of the number
Parameters
object the object pointer
Returns
the number value
Definition at line 513 of file number.c.
tb_bool_t tb_object_number_double_set (tb_object_ref_t number, tb_double_t value)
set the double value
Parameters
object the object pointer
value the number value
Returns
tb_true or tb_false
Definition at line 668 of file number.c.
tb_float_t tb_object_number_float (tb_object_ref_t number)
the float value of the number
Parameters
object the object pointer
Returns
the number value
Definition at line 477 of file number.c.
tb_bool_t tb_object_number_float_set (tb_object_ref_t number, tb_float_t value)
set the float value
Parameters
object the object pointer
value the number value
Returns
tb_true or tb_false
Definition at line 655 of file number.c.
tb_object_ref_t tb_object_number_init_from_double (tb_double_t value)
init number from double
Parameters
value the value
Returns
the number object
Definition at line 350 of file number.c.
tb_object_ref_t tb_object_number_init_from_float (tb_float_t value)
init number from float
Parameters
value the value
Returns
the number object
Definition at line 336 of file number.c.
tb_object_ref_t tb_object_number_init_from_sint16 (tb_sint16_t value)
init number from sint16
Parameters
value the value
Returns
the number object
Definition at line 265 of file number.c.
tb_object_ref_t tb_object_number_init_from_sint32 (tb_sint32_t value)
init number from sint32
Parameters
value the value
Returns
the number object
Definition at line 293 of file number.c.
tb_object_ref_t tb_object_number_init_from_sint64 (tb_sint64_t value)
init number from sint64
Parameters
value the value
Returns
the number object
Definition at line 321 of file number.c.
tb_object_ref_t tb_object_number_init_from_sint8 (tb_sint8_t value)
init number from sint8
Parameters
value the value
Returns
the number object
Definition at line 237 of file number.c.
tb_object_ref_t tb_object_number_init_from_uint16 (tb_uint16_t value)
init number from uint16
Parameters
value the value
Returns
the number object
Definition at line 251 of file number.c.
tb_object_ref_t tb_object_number_init_from_uint32 (tb_uint32_t value)
init number from uint32
Parameters
value the value
Returns
the number object
Definition at line 279 of file number.c.
tb_object_ref_t tb_object_number_init_from_uint64 (tb_uint64_t value)
init number from uint64
Parameters
value the value
Returns
the number object
Definition at line 307 of file number.c.
tb_object_ref_t tb_object_number_init_from_uint8 (tb_uint8_t value)
init number from uint8
Parameters
value the value
Returns
the number object
Definition at line 223 of file number.c.
tb_sint16_t tb_object_number_sint16 (tb_object_ref_t number)
the sint16 value of the number
Parameters
object the object pointer
Returns
the number value
Definition at line 387 of file number.c.
References tb_object_number_sint64().
tb_bool_t tb_object_number_sint16_set (tb_object_ref_t number, tb_sint16_t value)
set the sint16 value
Parameters
object the object pointer
value the number value
Returns
tb_true or tb_false
Definition at line 589 of file number.c.
tb_sint32_t tb_object_number_sint32 (tb_object_ref_t number)
the sint32 value of the number
Parameters
object the object pointer
Returns
the number value
Definition at line 395 of file number.c.
References tb_object_number_sint64().
tb_bool_t tb_object_number_sint32_set (tb_object_ref_t number, tb_sint32_t value)
set the sint32 value
Parameters
object the object pointer
value the number value
Returns
tb_true or tb_false
Definition at line 615 of file number.c.
tb_sint64_t tb_object_number_sint64 (tb_object_ref_t number)
the sint64 value of the number
Parameters
object the object pointer
Returns
the number value
Definition at line 438 of file number.c.
Referenced by tb_object_number_sint16(), tb_object_number_sint32(), and tb_object_number_sint8().
tb_bool_t tb_object_number_sint64_set (tb_object_ref_t number, tb_sint64_t value)
set the sint64 value
Parameters
object the object pointer
value the number value
Returns
tb_true or tb_false
Definition at line 641 of file number.c.
tb_sint8_t tb_object_number_sint8 (tb_object_ref_t number)
the sint8 value of the number
Parameters
object the object pointer
Returns
the number value
Definition at line 379 of file number.c.
References tb_object_number_sint64().
tb_bool_t tb_object_number_sint8_set (tb_object_ref_t number, tb_sint8_t value)
set the sint8 value
Parameters
object the object pointer
value the number value
Returns
tb_true or tb_false
Definition at line 563 of file number.c.
tb_size_t tb_object_number_type (tb_object_ref_t number)
the number type
Parameters
object the object pointer
Returns
the number type
Definition at line 365 of file number.c.
tb_uint16_t tb_object_number_uint16 (tb_object_ref_t number)
the uint16 value of the number
Parameters
object the object pointer
Returns
the number value
Definition at line 383 of file number.c.
References tb_object_number_uint64().
tb_bool_t tb_object_number_uint16_set (tb_object_ref_t number, tb_uint16_t value)
set the uint16 value
Parameters
object the object pointer
value the number value
Returns
tb_true or tb_false
Definition at line 576 of file number.c.
tb_uint32_t tb_object_number_uint32 (tb_object_ref_t number)
the uint32 value of the number
Parameters
object the object pointer
Returns
the number value
Definition at line 391 of file number.c.
References tb_object_number_uint64().
tb_bool_t tb_object_number_uint32_set (tb_object_ref_t number, tb_uint32_t value)
set the uint32 value
Parameters
object the object pointer
value the number value
Returns
tb_true or tb_false
Definition at line 602 of file number.c.
tb_uint64_t tb_object_number_uint64 (tb_object_ref_t number)
the uint64 value of the number
Parameters
object the object pointer
Returns
the number value
Definition at line 399 of file number.c.
Referenced by tb_object_number_uint16(), tb_object_number_uint32(), and tb_object_number_uint8().
tb_bool_t tb_object_number_uint64_set (tb_object_ref_t number, tb_uint64_t value)
set the uint64 value
Parameters
object the object pointer
value the number value
Returns
tb_true or tb_false
Definition at line 628 of file number.c.
tb_uint8_t tb_object_number_uint8 (tb_object_ref_t number)
the uint8 value of the number
Parameters
object the object pointer
Returns
the number value
Definition at line 375 of file number.c.
References tb_object_number_uint64().
tb_bool_t tb_object_number_uint8_set (tb_object_ref_t number, tb_uint8_t value)
set the uint8 value
Parameters
object the object pointer
value the number value
Returns
tb_true or tb_false
Definition at line 550 of file number.c.