TBOX: src/tbox/container/stack.h File Reference
stack.h File Reference
Container
#include "vector.h"
#include "item.h"
Functions
tb_stack_ref_t tb_stack_init (tb_size_t grow, tb_item_func_t func)
tb_void_t tb_stack_exit (tb_stack_ref_t stack)
tb_pointer_t tb_stack_head (tb_stack_ref_t stack)
tb_pointer_t tb_stack_last (tb_stack_ref_t stack)
tb_void_t tb_stack_clear (tb_stack_ref_t stack)
tb_void_t tb_stack_copy (tb_stack_ref_t stack, tb_stack_ref_t copy)
tb_void_t tb_stack_put (tb_stack_ref_t stack, tb_cpointer_t data)
tb_void_t tb_stack_pop (tb_stack_ref_t stack)
tb_pointer_t tb_stack_top (tb_stack_ref_t stack)
tb_bool_t tb_stack_load (tb_stack_ref_t stack, tb_stream_ref_t stream)
tb_bool_t tb_stack_save (tb_stack_ref_t stack, tb_stream_ref_t stream)
tb_size_t tb_stack_size (tb_stack_ref_t stack)
tb_size_t tb_stack_maxn (tb_stack_ref_t stack)
Variables
__tb_extern_c_enter__ typedef
tb_vector_ref_t tb_stack_ref_t
Detailed Description
The Treasure Box Library
TBox is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 2.1 of the License, or (at your option) any later version.
TBox is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with TBox; If not, see http://www.gnu.org/licenses/
Copyright (C) 2009 - 2015, ruki All rights reserved.
Author
ruki
Definition in file stack.h.
Function Documentation
tb_void_t tb_stack_clear (tb_stack_ref_t stack)
clear the stack
Parameters
stack the stack
Definition at line 45 of file stack.c.
References tb_vector_clear().
tb_void_t tb_stack_copy (tb_stack_ref_t stack, tb_stack_ref_t copy)
copy the stack
Parameters
stack the stack
copy the copied stack
Definition at line 49 of file stack.c.
References tb_vector_copy().
tb_void_t tb_stack_exit (tb_stack_ref_t stack)
exit stack
Parameters
stack the stack
Definition at line 41 of file stack.c.
References tb_vector_exit().
tb_pointer_t tb_stack_head (tb_stack_ref_t stack)
the stack head item
Parameters
stack the stack
Returns
the head item
Definition at line 65 of file stack.c.
References tb_vector_head().
tb_stack_ref_t tb_stack_init (tb_size_t grow, tb_item_func_t func)
init stack
Parameters
grow the item grow
func the item func
Returns
the stack
Definition at line 37 of file stack.c.
References tb_vector_init().
tb_pointer_t tb_stack_last (tb_stack_ref_t stack)
the stack last item
Parameters
stack the stack
Returns
the last item
Definition at line 69 of file stack.c.
References tb_vector_last().
tb_bool_t tb_stack_load (tb_stack_ref_t stack, tb_stream_ref_t stream)
load stack from the stream
Parameters
stack the stack
stream the stream
Returns
tb_true or tb_false
Definition at line 81 of file stack.c.
References tb_vector_load().
tb_size_t tb_stack_maxn (tb_stack_ref_t stack)
the stack maxn
Parameters
stack the stack
Returns
the stack maxn
Definition at line 77 of file stack.c.
References tb_vector_maxn().
tb_void_t tb_stack_pop (tb_stack_ref_t stack)
pop the stack item
Parameters
stack the stack
Definition at line 57 of file stack.c.
References tb_vector_remove_last().
tb_void_t tb_stack_put (tb_stack_ref_t stack, tb_cpointer_t data)
put the stack item
Parameters
stack the stack
data the item data
Definition at line 53 of file stack.c.
References tb_vector_insert_tail().
tb_bool_t tb_stack_save (tb_stack_ref_t stack, tb_stream_ref_t stream)
save stack to the stream
Parameters
stack the stack
stream the stream
Returns
tb_true or tb_false
Definition at line 85 of file stack.c.
References tb_vector_save().
tb_size_t tb_stack_size (tb_stack_ref_t stack)
the stack size
Parameters
stack the stack
Returns
the stack size
Definition at line 73 of file stack.c.
References tb_vector_size().
tb_pointer_t tb_stack_top (tb_stack_ref_t stack)
the stack top item
Parameters
stack the stack
Returns
the stack top item
Definition at line 61 of file stack.c.
References tb_vector_last().
Variable Documentation
__tb_extern_c_enter__ typedef tb_vector_ref_t tb_stack_ref_t
the stack ref type
stack: |||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||------|
      head                                                           last    tail
stack: |||||||||||||||||||||||||||||||||||||||||------|
      head                                   last    tail
performance:
push:    fast
pop:     fast
iterator:
next:    fast
prev:    fast
Note
the itor of the same item is fixed
Definition at line 64 of file stack.h.