TBOX: src/tbox/asio/ssl.c File Reference
ssl.c File Reference
Asio
#include "ssl.h"
#include "aico.h"
#include "aicp.h"
#include "../network/network.h"
#include "../platform/platform.h"
Macros
#define TB_TRACE_MODULE_NAME "aicp_ssl"
#define TB_TRACE_MODULE_DEBUG (1)
Functions
tb_aicp_ssl_ref_t tb_aicp_ssl_init (tb_aicp_ref_t aicp, tb_bool_t bserver)
tb_void_t tb_aicp_ssl_kill (tb_aicp_ssl_ref_t ssl)
tb_bool_t tb_aicp_ssl_exit (tb_aicp_ssl_ref_t ssl)
tb_void_t tb_aicp_ssl_set_aico (tb_aicp_ssl_ref_t ssl, tb_aico_ref_t aico)
tb_void_t tb_aicp_ssl_set_timeout (tb_aicp_ssl_ref_t ssl, tb_long_t timeout)
tb_bool_t tb_aicp_ssl_open (tb_aicp_ssl_ref_t ssl, tb_aicp_ssl_open_func_t func, tb_cpointer_t priv)
tb_bool_t tb_aicp_ssl_clos (tb_aicp_ssl_ref_t ssl, tb_aicp_ssl_clos_func_t func, tb_cpointer_t priv)
tb_bool_t tb_aicp_ssl_clos_try (tb_aicp_ssl_ref_t ssl)
tb_bool_t tb_aicp_ssl_read (tb_aicp_ssl_ref_t ssl, tb_byte_t *data, tb_size_t size, tb_aicp_ssl_read_func_t func, tb_cpointer_t priv)
tb_bool_t tb_aicp_ssl_writ (tb_aicp_ssl_ref_t ssl, tb_byte_t const *data, tb_size_t size, tb_aicp_ssl_writ_func_t func, tb_cpointer_t priv)
tb_bool_t tb_aicp_ssl_read_after (tb_aicp_ssl_ref_t ssl, tb_size_t delay, tb_byte_t *data, tb_size_t size, tb_aicp_ssl_read_func_t func, tb_cpointer_t priv)
tb_bool_t tb_aicp_ssl_writ_after (tb_aicp_ssl_ref_t ssl, tb_size_t delay, tb_byte_t const *data, tb_size_t size, tb_aicp_ssl_writ_func_t func, tb_cpointer_t priv)
tb_bool_t tb_aicp_ssl_task (tb_aicp_ssl_ref_t ssl, tb_size_t delay, tb_aicp_ssl_task_func_t func, tb_cpointer_t priv)
tb_bool_t tb_aicp_ssl_open_read (tb_aicp_ssl_ref_t ssl, tb_byte_t *data, tb_size_t size, tb_aicp_ssl_read_func_t func, tb_cpointer_t priv)
tb_bool_t tb_aicp_ssl_open_writ (tb_aicp_ssl_ref_t ssl, tb_byte_t const *data, tb_size_t size, tb_aicp_ssl_writ_func_t func, tb_cpointer_t priv)
tb_aicp_ref_t tb_aicp_ssl_aicp (tb_aicp_ssl_ref_t ssl)
Detailed Description
The Treasure Box Library
TBox is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 2.1 of the License, or (at your option) any later version.
TBox is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with TBox; If not, see http://www.gnu.org/licenses/
Copyright (C) 2009 - 2015, ruki All rights reserved.
Author
ruki
Definition in file ssl.c.
Function Documentation
tb_aicp_ref_t tb_aicp_ssl_aicp (tb_aicp_ssl_ref_t ssl)
the ssl aicp
Parameters
ssl the ssl
Returns
the aicp
Definition at line 1355 of file ssl.c.
tb_bool_t tb_aicp_ssl_clos (tb_aicp_ssl_ref_t ssl, tb_aicp_ssl_clos_func_t func, tb_cpointer_t priv)
close the ssl
Parameters
handle the ssl
func the func
priv the func private data
Returns
tb_true or tb_false
Definition at line 1073 of file ssl.c.
References tb_aicp_ssl_clos_try().
tb_bool_t tb_aicp_ssl_clos_try (tb_aicp_ssl_ref_t ssl)
try closing the ssl
Parameters
ssl the ssl
Returns
tb_true or tb_false
Definition at line 1108 of file ssl.c.
Referenced by tb_aicp_ssl_clos(), and tb_aicp_ssl_exit().
tb_bool_t tb_aicp_ssl_exit (tb_aicp_ssl_ref_t ssl)
exit the ssl
Parameters
ssl the ssl
Returns
tb_true or tb_false
Definition at line 915 of file ssl.c.
References tb_aicp_ssl_clos_try(), tb_buffer_exit(), and tb_ssl_exit().
Referenced by tb_aicp_ssl_init().
tb_aicp_ssl_ref_t tb_aicp_ssl_init (tb_aicp_ref_t aicp, tb_bool_t bserver)
init the ssl
Parameters
aicp the aicp
bserver is server endpoint?
Returns
the ssl
Definition at line 853 of file ssl.c.
References tb_aicp_ssl_exit(), tb_buffer_init(), and tb_ssl_init().
tb_void_t tb_aicp_ssl_kill (tb_aicp_ssl_ref_t ssl)
kill the ssl
Parameters
ssl the ssl
Definition at line 899 of file ssl.c.
References tb_aico_kill().
tb_bool_t tb_aicp_ssl_open (tb_aicp_ssl_ref_t ssl, tb_aicp_ssl_open_func_t func, tb_cpointer_t priv)
open the ssl
Parameters
ssl the ssl
func the func
priv the func data
Returns
tb_true or tb_false
Definition at line 976 of file ssl.c.
References tb_aico_timeout_set(), tb_ssl_open_try(), tb_ssl_set_bio_func(), and tb_ssl_state().
Referenced by tb_aicp_ssl_open_read(), and tb_aicp_ssl_open_writ().
tb_bool_t tb_aicp_ssl_open_read (tb_aicp_ssl_ref_t ssl, tb_byte_t * data, tb_size_t size, tb_aicp_ssl_read_func_t func, tb_cpointer_t priv)
open and read the ssl, open it first if not opened
Parameters
ssl the ssl
data the read data
size the read size
func the func
priv the func data
Returns
tb_true or tb_false
Definition at line 1317 of file ssl.c.
References tb_aicp_ssl_open(), and tb_aicp_ssl_read().
tb_bool_t tb_aicp_ssl_open_writ (tb_aicp_ssl_ref_t ssl, tb_byte_t const * data, tb_size_t size, tb_aicp_ssl_writ_func_t func, tb_cpointer_t priv)
open and writ the ssl, open it first if not opened
Parameters
ssl the ssl
data the data
size the size
func the func
priv the func data
Returns
tb_true or tb_false
Definition at line 1336 of file ssl.c.
References tb_aicp_ssl_open(), and tb_aicp_ssl_writ().
tb_bool_t tb_aicp_ssl_read (tb_aicp_ssl_ref_t ssl, tb_byte_t * data, tb_size_t size, tb_aicp_ssl_read_func_t func, tb_cpointer_t priv)
read the ssl
Parameters
ssl the ssl
data the read data
size the read size
func the func
priv the func data
Returns
tb_true or tb_false
Definition at line 1141 of file ssl.c.
References tb_aicp_ssl_read_after().
Referenced by tb_aicp_ssl_open_read().
tb_bool_t tb_aicp_ssl_read_after (tb_aicp_ssl_ref_t ssl, tb_size_t delay, tb_byte_t * data, tb_size_t size, tb_aicp_ssl_read_func_t func, tb_cpointer_t priv)
read the ssl after the delay time
Parameters
ssl the ssl
delay the delay time, ms
data the read data
size the read size
func the func
priv the func data
Returns
tb_true or tb_false
Definition at line 1149 of file ssl.c.
References tb_ssl_read(), tb_ssl_set_bio_func(), and tb_ssl_state().
Referenced by tb_aicp_ssl_read().
tb_void_t tb_aicp_ssl_set_aico (tb_aicp_ssl_ref_t ssl, tb_aico_ref_t aico)
set the ssl aico
Parameters
ssl the ssl
aico the aico
Definition at line 958 of file ssl.c.
tb_void_t tb_aicp_ssl_set_timeout (tb_aicp_ssl_ref_t ssl, tb_long_t timeout)
set the ssl timeout
Parameters
ssl the ssl
timeout the ssl timeout, using the default timeout if be zero
Definition at line 967 of file ssl.c.
tb_bool_t tb_aicp_ssl_task (tb_aicp_ssl_ref_t ssl, tb_size_t delay, tb_aicp_ssl_task_func_t func, tb_cpointer_t priv)
task the ssl
Parameters
ssl the ssl
delay the delay time, ms
func the func
priv the func data
Returns
tb_true or tb_false
Definition at line 1303 of file ssl.c.
tb_bool_t tb_aicp_ssl_writ (tb_aicp_ssl_ref_t ssl, tb_byte_t const * data, tb_size_t size, tb_aicp_ssl_writ_func_t func, tb_cpointer_t priv)
writ the ssl
Parameters
ssl the ssl
data the data
size the size
func the func
priv the func data
Returns
tb_true or tb_false
Definition at line 1145 of file ssl.c.
References tb_aicp_ssl_writ_after().
Referenced by tb_aicp_ssl_open_writ().
tb_bool_t tb_aicp_ssl_writ_after (tb_aicp_ssl_ref_t ssl, tb_size_t delay, tb_byte_t const * data, tb_size_t size, tb_aicp_ssl_writ_func_t func, tb_cpointer_t priv)
writ the ssl after the delay time
Parameters
ssl the ssl
delay the delay time, ms
data the data
size the size
func the func
priv the func data
Returns
tb_true or tb_false
Definition at line 1226 of file ssl.c.
References tb_ssl_set_bio_func(), tb_ssl_state(), and tb_ssl_writ().
Referenced by tb_aicp_ssl_writ().