#!/bin/bash

function exe_cmd() 
{
    echo $1
    eval $1
}

if [ $# -lt 1 ]; then
    echo "Usage: $0 [ master | tbooxnet ]"
    exit
fi

branch=$1
if [ -z "$branch" ] || [ "$branch" != "master" ]; then
    branch='tbooxorg'
fi

exe_cmd "jekyll build"
if [ ! -d '_site' ];then
    echo "not content to be published!"
    exit
fi

# tboox.net
if [ "$branch" == "master" ]; then
    exe_cmd "perl -pi -e \"s/tboox\.org/tboox\.net/g\" `find _site -type f`"
    exe_cmd "perl -pi -e \"s/tboox\.net/tboox\.org/g\" `find _site/about -name index.html`"
    exe_cmd "perl -pi -e \"s/tboox\.net/tboox\.org/g\" `find _site/cn/about -name index.html`"
    exe_cmd "perl -pi -e \"s/162f1cd478898a0686b0b5d5115e2af2/1f2e7c366588e460fe2b6f4da3a5746d/g\" `find _site -type f`"
fi

# tboox.org
if [ "$branch" == "tbooxorg" ]; then
    exe_cmd "perl -pi -e \"s/Github Pages/Coding Pages/g\" `find _site -name index.html`"
    exe_cmd "perl -pi -e \"s/https:\/\/pages\.github\.com/http:\/\/pages\.coding\.me/g\" `find _site -name index.html`"
fi

# package site.zip
exe_cmd "cd _site"
exe_cmd "zip -qr $branch.zip *"
exe_cmd "cd -"
exe_cmd "mv _site/$branch.zip /tmp/"

exe_cmd "git checkout $branch"
error_code=$?
if [ $error_code != 0 ];then
    echo 'Switch branch fail.'
    exit
else
    ls | grep -v _site|xargs rm -rf
    exe_cmd "cp -r _site/* ."
    exe_cmd "rm -rf _site/"
    exe_cmd "touch .nojekyll"
fi

if [ "$branch" == "master" ]; then
    exe_cmd "perl -pi -e \"s/tboox\.org/tboox\.net/g\" ./CNAME"
fi
