#!/bin/bash

function exe_cmd() 
{
    echo $1
    eval $1
}

if [ $# -lt 1 ]; then
    echo "Usage: $0 [ master | tbooxorg ]"
    exit
fi

branch=$1
if [ -z "$branch" ] || [ "$branch" != "master" ]; then
    branch='master'
fi

exe_cmd "jekyll build"
if [ ! -d '_site' ];then
    echo "not content to be published!"
    exit
fi

# package site.zip
exe_cmd "cd _site"
exe_cmd "zip -qr $branch.zip *"
exe_cmd "cd -"
exe_cmd "mv _site/$branch.zip /tmp/"

exe_cmd "git checkout $branch"
error_code=$?
if [ $error_code != 0 ];then
    echo 'Switch branch fail.'
    exit
else
    ls | grep -v _site|xargs rm -rf
    exe_cmd "cp -r _site/* ."
    exe_cmd "rm -rf _site/"
    exe_cmd "touch .nojekyll"
fi

