#!/bin/bash

function exe_cmd() 
{
    echo $1
    eval $1
}

if [ $# -lt 1 ]; then
    echo "Usage: $0 [ commit message ]"
    exit
fi

message=$1

exe_cmd "git add ."
exe_cmd "git commit -a -m \"$message\""

exe_cmd "./build master"
exe_cmd "git add ."
exe_cmd "git commit -a -m \"$message\""
exe_cmd "git checkout sitesrc"

exe_cmd "git push all master"
exe_cmd "git push all sitesrc"
