TBOX: src/tbox/stream/async_transfer.h File Reference
async_transfer.h File Reference
Stream
#include "prefix.h"
#include "async_stream.h"
Data Structures
struct tb_async_transfer_ref_t
the async transfer ref type
Typedefs
typedef tb_void_t(* tb_async_transfer_clos_func_t)(tb_size_t state, tb_cpointer_t priv)
typedef tb_bool_t(* tb_async_transfer_ctrl_func_t)(tb_async_stream_ref_t istream, tb_async_stream_ref_t ostream, tb_cpointer_t priv)
typedef tb_bool_t(* tb_async_transfer_done_func_t)(tb_size_t state, tb_hize_t offset, tb_hong_t size, tb_hize_t save, tb_size_t rate, tb_cpointer_t priv)
Functions
tb_async_transfer_ref_t tb_async_transfer_init (tb_aicp_ref_t aicp, tb_bool_t autoclosing)
tb_bool_t tb_async_transfer_init_istream (tb_async_transfer_ref_t transfer, tb_async_stream_ref_t stream)
tb_bool_t tb_async_transfer_init_istream_from_url (tb_async_transfer_ref_t transfer, tb_char_t const *url)
tb_bool_t tb_async_transfer_init_istream_from_data (tb_async_transfer_ref_t transfer, tb_byte_t const *data, tb_size_t size)
tb_bool_t tb_async_transfer_init_ostream (tb_async_transfer_ref_t transfer, tb_async_stream_ref_t stream)
tb_bool_t tb_async_transfer_init_ostream_from_url (tb_async_transfer_ref_t transfer, tb_char_t const *url)
tb_bool_t tb_async_transfer_init_ostream_from_data (tb_async_transfer_ref_t transfer, tb_byte_t *data, tb_size_t size)
tb_bool_t tb_async_transfer_ctrl_istream (tb_async_transfer_ref_t transfer, tb_size_t ctrl,...)
tb_bool_t tb_async_transfer_ctrl_ostream (tb_async_transfer_ref_t transfer, tb_size_t ctrl,...)
tb_bool_t tb_async_transfer_ctrl (tb_async_transfer_ref_t transfer, tb_async_transfer_ctrl_func_t func, tb_cpointer_t priv)
tb_bool_t tb_async_transfer_open (tb_async_transfer_ref_t transfer, tb_hize_t offset, tb_async_transfer_open_func_t func, tb_cpointer_t priv)
tb_bool_t tb_async_transfer_clos (tb_async_transfer_ref_t transfer, tb_async_transfer_clos_func_t func, tb_cpointer_t priv)
tb_bool_t tb_async_transfer_clos_try (tb_async_transfer_ref_t transfer)
tb_bool_t tb_async_transfer_done (tb_async_transfer_ref_t transfer, tb_async_transfer_done_func_t func, tb_cpointer_t priv)
tb_bool_t tb_async_transfer_open_done (tb_async_transfer_ref_t transfer, tb_hize_t offset, tb_async_transfer_done_func_t func, tb_cpointer_t priv)
tb_void_t tb_async_transfer_kill (tb_async_transfer_ref_t transfer)
tb_bool_t tb_async_transfer_exit (tb_async_transfer_ref_t transfer)
tb_void_t tb_async_transfer_pause (tb_async_transfer_ref_t transfer)
tb_bool_t tb_async_transfer_resume (tb_async_transfer_ref_t transfer)
tb_void_t tb_async_transfer_limitrate (tb_async_transfer_ref_t transfer, tb_size_t rate)
Variables
__tb_extern_c_enter__ typedef
tb_bool_t(* tb_async_transfer_open_func_t)(tb_size_t state, tb_hize_t offset, tb_hong_t size, tb_cpointer_t priv)
Detailed Description
The Treasure Box Library
TBox is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 2.1 of the License, or (at your option) any later version.
TBox is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with TBox; If not, see http://www.gnu.org/licenses/
Copyright (C) 2009 - 2015, ruki All rights reserved.
Author
ruki
Definition in file async_transfer.h.
Typedef Documentation
typedef tb_void_t(* tb_async_transfer_clos_func_t)(tb_size_t state, tb_cpointer_t priv)
the async transfer clos func type
Parameters
state the stream state
priv the func private data
Definition at line 58 of file async_transfer.h.
typedef tb_bool_t(* tb_async_transfer_ctrl_func_t)(tb_async_stream_ref_t istream, tb_async_stream_ref_t ostream, tb_cpointer_t priv)
the async transfer ctrl func type
Parameters
istream the istream
ostream the ostream
priv the func private data
Returns
tb_true: ok, tb_false: break it
Definition at line 68 of file async_transfer.h.
typedef tb_bool_t(* tb_async_transfer_done_func_t)(tb_size_t state, tb_hize_t offset, tb_hong_t size, tb_hize_t save, tb_size_t rate, tb_cpointer_t priv)
the async transfer done func type
Parameters
state the stream state
offset the istream offset
size the istream size, no size: -1
save the saved size
rate the current rate, bytes/s
priv the func private data
Returns
tb_true: ok and continue it if need, tb_false: break it
Definition at line 81 of file async_transfer.h.
Function Documentation
tb_bool_t tb_async_transfer_clos (tb_async_transfer_ref_t transfer, tb_async_transfer_clos_func_t func, tb_cpointer_t priv)
clos transfer
Parameters
transfer the async transfer
func the clos func
priv the func private data
Returns
tb_true or tb_false
Definition at line 1032 of file async_transfer.c.
References tb_async_stream_clos, and tb_async_transfer_clos_try().
tb_bool_t tb_async_transfer_clos_try (tb_async_transfer_ref_t transfer)
try closing transfer
Parameters
transfer the async transfer
Returns
tb_true or tb_false
Definition at line 1060 of file async_transfer.c.
References tb_async_stream_clos_try().
Referenced by tb_async_transfer_clos(), and tb_async_transfer_exit().
tb_bool_t tb_async_transfer_ctrl (tb_async_transfer_ref_t transfer, tb_async_transfer_ctrl_func_t func, tb_cpointer_t priv)
ctrl transfer
Parameters
transfer the async transfer
offset the start offset
func the ctrl func
priv the func private data
Returns
tb_true or tb_false
Definition at line 1103 of file async_transfer.c.
tb_bool_t tb_async_transfer_ctrl_istream (tb_async_transfer_ref_t transfer, tb_size_t ctrl, ...)
ctrl istream
Note
must call it before opening
Parameters
transfer the async transfer
ctrl the ctrl code, using the stream ctrl code
Returns
tb_true or tb_false
Definition at line 929 of file async_transfer.c.
References tb_async_stream_ctrl_with_args().
tb_bool_t tb_async_transfer_ctrl_ostream (tb_async_transfer_ref_t transfer, tb_size_t ctrl, ...)
ctrl ostream
Note
must call it before opening
Parameters
transfer the async transfer
ctrl the ctrl code, using the stream ctrl code
Returns
tb_true or tb_false
Definition at line 948 of file async_transfer.c.
References tb_async_stream_ctrl_with_args().
tb_bool_t tb_async_transfer_done (tb_async_transfer_ref_t transfer, tb_async_transfer_done_func_t func, tb_cpointer_t priv)
done transfer and will close it automaticly
Parameters
transfer the async transfer
func the save func
priv the func private data
Returns
tb_true or tb_false
Definition at line 1119 of file async_transfer.c.
References tb_async_stream_read.
Referenced by tb_async_transfer_open_done().
tb_bool_t tb_async_transfer_exit (tb_async_transfer_ref_t transfer)
exit transfer
Note
will wait transfer closed and cannot be called in the callback func
Parameters
transfer the async transfer
Returns
tb_true or tb_false
Definition at line 1174 of file async_transfer.c.
References tb_async_stream_exit(), tb_async_transfer_clos_try(), and tb_async_transfer_kill().
tb_async_transfer_ref_t tb_async_transfer_init (tb_aicp_ref_t aicp, tb_bool_t autoclosing)
init async transfer
Parameters
aicp the aicp, using the default aicp if be null
autoclosing auto closing it after finishing transfer
Returns
the async transfer
Definition at line 677 of file async_transfer.c.
References tb_aicp().
tb_bool_t tb_async_transfer_init_istream (tb_async_transfer_ref_t transfer, tb_async_stream_ref_t stream)
init istream
Parameters
transfer the async transfer
stream the stream
Returns
tb_true or tb_false
Definition at line 698 of file async_transfer.c.
References tb_async_stream_exit().
tb_bool_t tb_async_transfer_init_istream_from_data (tb_async_transfer_ref_t transfer, tb_byte_t const * data, tb_size_t size)
init istream from data
Parameters
transfer the async transfer
data the data
size the size
Returns
tb_true or tb_false
Definition at line 775 of file async_transfer.c.
References tb_async_stream_ctrl(), tb_async_stream_exit(), tb_async_stream_init_from_data(), and tb_async_stream_type().
tb_bool_t tb_async_transfer_init_istream_from_url (tb_async_transfer_ref_t transfer, tb_char_t const * url)
init istream from url
Parameters
transfer the async transfer
url the url
Returns
tb_true or tb_false
Definition at line 721 of file async_transfer.c.
References tb_async_stream_ctrl(), tb_async_stream_exit(), tb_async_stream_init_from_url(), and tb_async_stream_type().
Referenced by tb_transfer_pool_done().
tb_bool_t tb_async_transfer_init_ostream (tb_async_transfer_ref_t transfer, tb_async_stream_ref_t stream)
init ostream
Parameters
transfer the async transfer
stream the stream
Returns
the async transfer
Definition at line 810 of file async_transfer.c.
References tb_async_stream_exit().
tb_bool_t tb_async_transfer_init_ostream_from_data (tb_async_transfer_ref_t transfer, tb_byte_t * data, tb_size_t size)
init ostream from data
Parameters
transfer the async transfer
data the data
size the size
Returns
tb_true or tb_false
Definition at line 894 of file async_transfer.c.
References tb_async_stream_ctrl(), tb_async_stream_exit(), tb_async_stream_init_from_data(), and tb_async_stream_type().
tb_bool_t tb_async_transfer_init_ostream_from_url (tb_async_transfer_ref_t transfer, tb_char_t const * url)
init ostream from url
Parameters
transfer the async transfer
url the url
Returns
tb_true or tb_false
Definition at line 833 of file async_transfer.c.
References tb_async_stream_ctrl(), tb_async_stream_exit(), tb_async_stream_init_from_url(), tb_async_stream_type(), TB_FILE_MODE_BINARY, TB_FILE_MODE_CREAT, TB_FILE_MODE_RW, and TB_FILE_MODE_TRUNC.
Referenced by tb_transfer_pool_done().
tb_void_t tb_async_transfer_kill (tb_async_transfer_ref_t transfer)
kill transfer
Parameters
transfer the async transfer
Definition at line 1155 of file async_transfer.c.
References tb_async_stream_kill().
Referenced by tb_async_transfer_exit().
tb_void_t tb_async_transfer_limitrate (tb_async_transfer_ref_t transfer, tb_size_t rate)
limit transfer rate
Parameters
transfer the async transfer
rate the trasfer rate and no limit if 0, bytes/s
Definition at line 1273 of file async_transfer.c.
Referenced by tb_transfer_pool_done().
tb_bool_t tb_async_transfer_open (tb_async_transfer_ref_t transfer, tb_hize_t offset, tb_async_transfer_open_func_t func, tb_cpointer_t priv)
open transfer
Parameters
transfer the async transfer
offset the start offset
func the open func
priv the func private data
Returns
tb_true or tb_false
Definition at line 967 of file async_transfer.c.
References tb_aicp_time(), tb_async_stream_offset(), tb_async_stream_open_seek, and tb_async_stream_size().
Referenced by tb_async_transfer_open_done().
tb_bool_t tb_async_transfer_open_done (tb_async_transfer_ref_t transfer, tb_hize_t offset, tb_async_transfer_done_func_t func, tb_cpointer_t priv)
open and done transfer and will close it automaticly
    static tb_bool_t tb_demo_transfer_done_func(tb_size_t state, tb_hize_t offset, tb_hong_t size, tb_hize_t save, tb_size_t rate, tb_cpointer_t priv)
    {
        // percent
        tb_size_t percent = 0;
        if (size > 0) percent = (offset * 100) / size;
        else if (state == TB_STATE_OK) percent = 100;
        // trace
        tb_trace_i("done: %llu bytes, rate: %lu bytes/s, percent: %lu%%, state: %s", save, rate, percent, tb_state_cstr(state));
        // ok
        return tb_true;
    }
    // init transfer
    tb_async_transfer_ref_t transfer = tb_async_transfer_init(tb_null);
    if (transfer)
    {
        // init stream
        tb_async_transfer_init_istream_from_url(transfer, url);
        tb_async_transfer_init_ostream_from_data(transfer, data, size);
        // ctrl stream
//      tb_async_transfer_ctrl_istream(transfer, TB_STREAM_CTRL_SET_TIMEOUT, 10000);
        // limit rate
//      tb_async_transfer_limitrate(transfer, 256000);
        // open and done transfer
        tb_async_transfer_open_done(transfer, 0, tb_demo_transfer_done_func, tb_null);
        // exit transfer
        tb_async_transfer_exit(transfer);
    }
Parameters
transfer the async transfer
offset the start offset
func the save func
priv the func private data
Returns
tb_true or tb_false
Definition at line 1138 of file async_transfer.c.
References tb_async_transfer_done(), and tb_async_transfer_open().
Referenced by tb_transfer_pool_done().
tb_void_t tb_async_transfer_pause (tb_async_transfer_ref_t transfer)
pause transfer
the save func state will return TB_STATE_PAUSED
Parameters
transfer the async transfer
Definition at line 1220 of file async_transfer.c.
tb_bool_t tb_async_transfer_resume (tb_async_transfer_ref_t transfer)
resume transfer
Parameters
transfer the async transfer
Returns
tb_true or tb_false
Definition at line 1229 of file async_transfer.c.
References tb_aicp_time(), and tb_async_stream_read.
Variable Documentation
__tb_extern_c_enter__ typedef tb_bool_t(* tb_async_transfer_open_func_t)(tb_size_t state, tb_hize_t offset, tb_hong_t size, tb_cpointer_t priv)
the async transfer open func type
Parameters
state the stream state
offset the istream offset
size the istream size, no size: -1
priv the func private data
Returns
tb_true: ok, tb_false: break it
Definition at line 51 of file async_transfer.h.