TBOX: src/tbox/prefix/malloc.h File Reference
malloc.h File Reference
#include "config.h"
#include "keyword.h"
Macros
#define tb_free(data) tb_pool_free_(tb_pool(), (tb_pointer_t)data __tb_debug_vals__)
#define tb_malloc(size) tb_pool_malloc_(tb_pool(), size __tb_debug_vals__)
#define tb_malloc0(size) tb_pool_malloc0_(tb_pool(), size __tb_debug_vals__)
#define tb_nalloc(item, size) tb_pool_nalloc_(tb_pool(), item, size __tb_debug_vals__)
#define tb_nalloc0(item, size) tb_pool_nalloc0_(tb_pool(), item, size __tb_debug_vals__)
#define tb_ralloc(data, size) tb_pool_ralloc_(tb_pool(), (tb_pointer_t)data, size __tb_debug_vals__)
#define tb_malloc_cstr(size) (tb_char_t*)tb_pool_malloc_(tb_pool(), size __tb_debug_vals__)
#define tb_malloc0_cstr(size) (tb_char_t*)tb_pool_malloc0_(tb_pool(), size __tb_debug_vals__)
#define tb_nalloc_cstr(item, size) (tb_char_t*)tb_pool_nalloc_(tb_pool(), item, size __tb_debug_vals__)
#define tb_nalloc0_cstr(item, size) (tb_char_t*)tb_pool_nalloc0_(tb_pool(), item, size __tb_debug_vals__)
#define tb_ralloc_cstr(data, size) (tb_char_t*)tb_pool_ralloc_(tb_pool(), (tb_pointer_t)data, size __tb_debug_vals__)
#define tb_malloc_bytes(size) (tb_byte_t*)tb_pool_malloc_(tb_pool(), size __tb_debug_vals__)
#define tb_malloc0_bytes(size) (tb_byte_t*)tb_pool_malloc0_(tb_pool(), size __tb_debug_vals__)
#define tb_nalloc_bytes(item, size) (tb_byte_t*)tb_pool_nalloc_(tb_pool(), item, size __tb_debug_vals__)
#define tb_nalloc0_bytes(item, size) (tb_byte_t*)tb_pool_nalloc0_(tb_pool(), item, size __tb_debug_vals__)
#define tb_ralloc_bytes(data, size) (tb_byte_t*)tb_pool_ralloc_(tb_pool(), (tb_pointer_t)data, size __tb_debug_vals__)
#define tb_malloc_type(type) (type*)tb_pool_malloc_(tb_pool(), sizeof(type) __tb_debug_vals__)
#define tb_malloc0_type(type) (type*)tb_pool_malloc0_(tb_pool(), sizeof(type) __tb_debug_vals__)
#define tb_nalloc_type(item, type) (type*)tb_pool_nalloc_(tb_pool(), item, sizeof(type) __tb_debug_vals__)
#define tb_nalloc0_type(item, type) (type*)tb_pool_nalloc0_(tb_pool(), item, sizeof(type) __tb_debug_vals__)
#define tb_ralloc_type(data, item, type) (type*)tb_pool_ralloc_(tb_pool(), (tb_pointer_t)data, ((item) * sizeof(type)) __tb_debug_vals__)
#define tb_align_free(data) tb_pool_align_free_(tb_pool(), (tb_pointer_t)data __tb_debug_vals__)
#define tb_align_malloc(size, align) tb_pool_align_malloc_(tb_pool(), size, align __tb_debug_vals__)
#define tb_align_malloc0(size, align) tb_pool_align_malloc0_(tb_pool(), size, align __tb_debug_vals__)
#define tb_align_nalloc(item, size, align) tb_pool_align_nalloc_(tb_pool(), item, size, align __tb_debug_vals__)
#define tb_align_nalloc0(item, size, align) tb_pool_align_nalloc0_(tb_pool(), item, size, align __tb_debug_vals__)
#define tb_align_ralloc(data, size, align) tb_pool_align_ralloc_(tb_pool(), (tb_pointer_t)data, size, align __tb_debug_vals__)
#define tb_align8_free(data) tb_align_free((tb_pointer_t)data)
#define tb_align8_malloc(size) tb_align_malloc(size, 8)
#define tb_align8_malloc0(size) tb_align_malloc0(size, 8)
#define tb_align8_nalloc(item, size) tb_align_nalloc(item, size, 8)
#define tb_align8_nalloc0(item, size) tb_align_nalloc0(item, size, 8)
#define tb_align8_ralloc(data, size) tb_align_ralloc((tb_pointer_t)data, size, 8)
Functions
tb_pool_ref_t tb_pool (tb_noarg_t)
tb_pointer_t tb_pool_malloc_ (tb_pool_ref_t pool, tb_size_t size __tb_debug_decl__)
tb_pointer_t tb_pool_malloc0_ (tb_pool_ref_t pool, tb_size_t size __tb_debug_decl__)
tb_pointer_t tb_pool_nalloc_ (tb_pool_ref_t pool, tb_size_t item, tb_size_t size __tb_debug_decl__)
tb_pointer_t tb_pool_nalloc0_ (tb_pool_ref_t pool, tb_size_t item, tb_size_t size __tb_debug_decl__)
tb_pointer_t tb_pool_ralloc_ (tb_pool_ref_t pool, tb_pointer_t data, tb_size_t size __tb_debug_decl__)
tb_bool_t tb_pool_free_ (tb_pool_ref_t pool, tb_pointer_t data __tb_debug_decl__)
Detailed Description
The Treasure Box Library
TBox is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 2.1 of the License, or (at your option) any later version.
TBox is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with TBox; If not, see http://www.gnu.org/licenses/
Copyright (C) 2009 - 2015, ruki All rights reserved.
Author
ruki
Definition in file malloc.h.
Function Documentation
tb_bool_t tb_pool_free_ (tb_pool_ref_t pool, tb_pointer_t data __tb_debug_decl__)
free data
Parameters
pool the pool
data the data address
Returns
tb_true or tb_false
Definition at line 293 of file pool.c.
References tb_large_pool_free_(), and tb_small_pool_free_().
Referenced by tb_pool_align_free_().
tb_pointer_t tb_pool_malloc0_ (tb_pool_ref_t pool, tb_size_t size __tb_debug_decl__)
malloc data and fill zero
Parameters
pool the pool
size the size
Returns
the data address
Definition at line 166 of file pool.c.
References tb_large_pool_malloc0_(), and tb_small_pool_malloc0_().
tb_pointer_t tb_pool_malloc_ (tb_pool_ref_t pool, tb_size_t size __tb_debug_decl__)
malloc data
Parameters
pool the pool
size the size
Returns
the data address
Definition at line 148 of file pool.c.
References tb_large_pool_malloc_(), and tb_small_pool_malloc_().
Referenced by tb_pool_align_malloc_().
tb_pointer_t tb_pool_nalloc0_ (tb_pool_ref_t pool, tb_size_t item, tb_size_t size __tb_debug_decl__)
malloc data with the item count and fill zero
Parameters
pool the pool
item the item count
size the item size
Returns
the data address
Definition at line 202 of file pool.c.
References tb_large_pool_nalloc0_(), and tb_small_pool_nalloc0_().
tb_pointer_t tb_pool_nalloc_ (tb_pool_ref_t pool, tb_size_t item, tb_size_t size __tb_debug_decl__)
malloc data with the item count
Parameters
pool the pool
item the item count
size the item size
Returns
the data address
Definition at line 184 of file pool.c.
References tb_large_pool_nalloc_(), and tb_small_pool_nalloc_().
tb_pointer_t tb_pool_ralloc_ (tb_pool_ref_t pool, tb_pointer_t data, tb_size_t size __tb_debug_decl__)
realloc data
Parameters
pool the pool
data the data address
size the data size
Returns
the new data address
Definition at line 220 of file pool.c.
References tb_large_pool_free_(), tb_large_pool_malloc_(), tb_large_pool_ralloc_(), tb_small_pool_free_(), tb_small_pool_malloc_(), and tb_small_pool_ralloc_().
Referenced by tb_pool_align_ralloc_().