TBOX: src/xml/writer.h File Reference
writer.h File Reference
Xml
#include "prefix.h"
#include "node.h"
Functions
tb_handle_t tb_xml_writer_init (tb_gstream_t *gst, tb_bool_t bformat)
tb_void_t tb_xml_writer_exit (tb_handle_t writer)
tb_void_t tb_xml_writer_save (tb_handle_t writer, tb_xml_node_t const *node)
tb_void_t tb_xml_writer_document (tb_handle_t writer, tb_char_t const *version, tb_char_t const *encoding)
tb_void_t tb_xml_writer_document_type (tb_handle_t writer, tb_char_t const *type)
tb_void_t tb_xml_writer_cdata (tb_handle_t writer, tb_char_t const *data)
tb_void_t tb_xml_writer_text (tb_handle_t writer, tb_char_t const *text)
tb_void_t tb_xml_writer_comment (tb_handle_t writer, tb_char_t const *comment)
tb_void_t tb_xml_writer_element_empty (tb_handle_t writer, tb_char_t const *name)
tb_void_t tb_xml_writer_element_enter (tb_handle_t writer, tb_char_t const *name)
tb_void_t tb_xml_writer_element_leave (tb_handle_t writer)
tb_void_t tb_xml_writer_attributes_long (tb_handle_t writer, tb_char_t const *name, tb_long_t value)
tb_void_t tb_xml_writer_attributes_bool (tb_handle_t writer, tb_char_t const *name, tb_bool_t value)
tb_void_t tb_xml_writer_attributes_cstr (tb_handle_t writer, tb_char_t const *name, tb_char_t const *value)
tb_void_t tb_xml_writer_attributes_format (tb_handle_t writer, tb_char_t const *name, tb_char_t const *format,...)
tb_void_t tb_xml_writer_attributes_float (tb_handle_t writer, tb_char_t const *name, tb_float_t value)
tb_void_t tb_xml_writer_attributes_double (tb_handle_t writer, tb_char_t const *name, tb_double_t value)
Detailed Description
The Treasure Box Library
TBox is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 2.1 of the License, or (at your option) any later version.
TBox is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with TBox; If not, see http://www.gnu.org/licenses/
Copyright (C) 2009 - 2012, ruki All rights reserved.
Author
ruki
Definition in file writer.h.
Function Documentation
tb_void_t tb_xml_writer_attributes_bool (tb_handle_t writer, tb_char_t const * name, tb_bool_t value)
writ the xml attribute for boolean value
Parameters
writer the xml writer
name the xml attribute name
value the xml attribute value
Definition at line 364 of file writer.c.
References tb_hash_set(), and tb_snprintf().
tb_void_t tb_xml_writer_attributes_cstr (tb_handle_t writer, tb_char_t const * name, tb_char_t const * value)
writ the xml attribute for cstr value
Parameters
writer the xml writer
name the xml attribute name
value the xml attribute value
Definition at line 373 of file writer.c.
References tb_hash_set().
Referenced by tb_xml_writer_save().
tb_void_t tb_xml_writer_attributes_double (tb_handle_t writer, tb_char_t const * name, tb_double_t value)
writ the xml attribute for double value
Parameters
writer the xml writer
name the xml attribute name
value the xml attribute value
Definition at line 400 of file writer.c.
References tb_hash_set(), and tb_snprintf().
tb_void_t tb_xml_writer_attributes_float (tb_handle_t writer, tb_char_t const * name, tb_float_t value)
writ the xml attribute for float value
Parameters
writer the xml writer
name the xml attribute name
value the xml attribute value
Definition at line 391 of file writer.c.
References tb_hash_set(), and tb_snprintf().
tb_void_t tb_xml_writer_attributes_format (tb_handle_t writer, tb_char_t const * name, tb_char_t const * format, ...)
writ the xml attribute for format value
Parameters
writer the xml writer
name the xml attribute name
format the xml attribute format
Definition at line 380 of file writer.c.
References tb_hash_set().
tb_void_t tb_xml_writer_attributes_long (tb_handle_t writer, tb_char_t const * name, tb_long_t value)
writ the xml attribute for long value
Parameters
writer the xml writer
name the xml attribute name
value the xml attribute value
Definition at line 355 of file writer.c.
References tb_hash_set(), and tb_snprintf().
tb_void_t tb_xml_writer_cdata (tb_handle_t writer, tb_char_t const * data)
writ the xml cdata: <![CDATA[...]]>
Parameters
writer the xml writer
data the xml cdata
Definition at line 218 of file writer.c.
References tb_gstream_printf(), and tb_stack_size().
Referenced by tb_xml_writer_save().
tb_void_t tb_xml_writer_comment (tb_handle_t writer, tb_char_t const * comment)
writ the xml comment:
Parameters
writer the xml writer
comment the xml comment
Definition at line 248 of file writer.c.
References tb_gstream_printf(), and tb_stack_size().
Referenced by tb_xml_writer_save().
tb_void_t tb_xml_writer_document (tb_handle_t writer, tb_char_t const * version, tb_char_t const * encoding)
writ the xml document node: <?xml version = "..." encoding = "..." ?>
Parameters
writer the xml writer
version the xml version
encoding the xml encoding
Definition at line 202 of file writer.c.
References tb_gstream_printf().
Referenced by tb_xml_writer_save().
tb_void_t tb_xml_writer_document_type (tb_handle_t writer, tb_char_t const * type)
writ the xml document type: <!DOCTYPE type>
Parameters
writer the xml writer
type the xml document type
Definition at line 210 of file writer.c.
References tb_gstream_printf().
Referenced by tb_xml_writer_save().
tb_void_t tb_xml_writer_element_empty (tb_handle_t writer, tb_char_t const * name)
writ the empty xml element: <name>
Parameters
writer the xml writer
name the xml element name
Definition at line 263 of file writer.c.
References tb_hash_item_t::data, tb_hash_item_t::name, tb_gstream_printf(), tb_hash_clear(), tb_hash_size(), tb_iterator_head(), tb_iterator_item(), tb_iterator_next(), tb_iterator_tail(), and tb_stack_size().
Referenced by tb_xml_writer_save().
tb_void_t tb_xml_writer_element_enter (tb_handle_t writer, tb_char_t const * name)
writ the xml element head: <name> ...
Parameters
writer the xml writer
name the xml element name
Definition at line 296 of file writer.c.
References tb_hash_item_t::data, tb_hash_item_t::name, tb_gstream_printf(), tb_hash_clear(), tb_hash_size(), tb_iterator_head(), tb_iterator_item(), tb_iterator_next(), tb_iterator_tail(), tb_stack_put(), and tb_stack_size().
Referenced by tb_xml_writer_save().
tb_void_t tb_xml_writer_element_leave (tb_handle_t writer)
writ the xml element tail: ... </name>
Parameters
writer the xml writer
Definition at line 332 of file writer.c.
References tb_gstream_printf(), tb_stack_pop(), tb_stack_size(), and tb_stack_top().
Referenced by tb_xml_writer_save().
tb_void_t tb_xml_writer_exit (tb_handle_t writer)
exit the xml writer
Parameters
writer the xml writer
Definition at line 105 of file writer.c.
References tb_hash_exit(), and tb_stack_exit().
Referenced by tb_xml_writer_init().
tb_handle_t tb_xml_writer_init (tb_gstream_t * gst, tb_bool_t bformat)
init the xml writer
Parameters
gst the stream
bformat is format xml?
Returns
the writer handle
Definition at line 73 of file writer.c.
References tb_hash_init(), tb_item_func_str(), tb_stack_init(), and tb_xml_writer_exit().
tb_void_t tb_xml_writer_save (tb_handle_t writer, tb_xml_node_t const * node)
save the xml document or node
Parameters
writer the xml writer
node the xml node
Definition at line 123 of file writer.c.
References tb_xml_document_t::charset, tb_xml_node_t::data, tb_xml_node_t::name, tb_xml_node_t::next, tb_pstring_cstr(), tb_xml_writer_attributes_cstr(), tb_xml_writer_cdata(), tb_xml_writer_comment(), tb_xml_writer_document(), tb_xml_writer_document_type(), tb_xml_writer_element_empty(), tb_xml_writer_element_enter(), tb_xml_writer_element_leave(), tb_xml_writer_save(), tb_xml_writer_text(), tb_xml_node_t::type, tb_xml_document_type_t::type, and tb_xml_document_t::version.
Referenced by tb_xml_writer_save().
tb_void_t tb_xml_writer_text (tb_handle_t writer, tb_char_t const * text)
writ the xml text
Parameters
writer the xml writer
text the xml text
Definition at line 233 of file writer.c.
References tb_gstream_printf(), and tb_stack_size().
Referenced by tb_xml_writer_save().