TBOX: src/tbox/container/list_entry.c File Reference
list_entry.c File Reference
Container
#include "list_entry.h"
#include "../libc/libc.h"
Functions
tb_iterator_ref_t tb_list_entry_itor (tb_list_entry_head_ref_t list)
tb_void_t tb_list_entry_init_ (tb_list_entry_head_ref_t list, tb_size_t entry_offset, tb_size_t entry_size, tb_entry_copy_t copy)
tb_void_t tb_list_entry_exit (tb_list_entry_head_ref_t list)
Detailed Description
The Treasure Box Library
TBox is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 2.1 of the License, or (at your option) any later version.
TBox is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with TBox; If not, see http://www.gnu.org/licenses/
Copyright (C) 2009 - 2015, ruki All rights reserved.
Author
ruki
Definition in file list_entry.c.
Function Documentation
tb_void_t tb_list_entry_exit (tb_list_entry_head_ref_t list)
exit list
Parameters
list the list
Definition at line 174 of file list_entry.c.
References tb_list_entry_head_t::next, tb_list_entry_head_t::prev, and tb_list_entry_head_t::size.
Referenced by tb_thread_pool_exit(), and tb_transfer_pool_exit().
tb_void_t tb_list_entry_init_ (tb_list_entry_head_ref_t list, tb_size_t entry_offset, tb_size_t entry_size, tb_entry_copy_t copy)
init list
Parameters
list the list
entry_offset the entry offset
entry_size the entry size
copy the copy func of the entry for algorithm, .e.g sort
Definition at line 146 of file list_entry.c.
References tb_iterator_t::comp, tb_iterator_t::copy, tb_list_entry_head_t::copy, tb_list_entry_head_t::eoff, tb_iterator_t::head, tb_iterator_t::item, tb_list_entry_head_t::itor, tb_iterator_t::last, tb_iterator_t::mode, tb_iterator_t::next, tb_list_entry_head_t::next, tb_iterator_t::prev, tb_list_entry_head_t::prev, tb_iterator_t::priv, tb_iterator_t::remove, tb_iterator_t::remove_range, tb_iterator_t::size, tb_list_entry_head_t::size, tb_iterator_t::step, tb_iterator_t::tail, TB_ITERATOR_MODE_FORWARD, and TB_ITERATOR_MODE_REVERSE.
Referenced by tb_list_init().
tb_iterator_ref_t tb_list_entry_itor (tb_list_entry_head_ref_t list)
the list iterator
Parameters
list the list
Returns
the list iterator
Definition at line 138 of file list_entry.c.
References tb_list_entry_head_t::itor.
Referenced by tb_fixed_pool_clear(), tb_fixed_pool_walk(), tb_thread_pool_task_wait_all(), tb_transfer_pool_kill_all(), and tb_transfer_pool_wait_all().