TBOX: src/utils/option.h File Reference
option.h File Reference
Utils
#include "prefix.h"
Data Structures
struct tb_option_item_t
the option item type
Enumerations
enum tb_option_mode_e {
TB_OPTION_MODE_END = 0, TB_OPTION_MODE_VAL = 1, TB_OPTION_MODE_KEY = 2, TB_OPTION_MODE_KEY_VAL = 3,
TB_OPTION_MODE_MORE = 4
}
the option mode enum
enum tb_option_type_e {
TB_OPTION_TYPE_NONE = 0, TB_OPTION_TYPE_BOOL = 1, TB_OPTION_TYPE_CSTR = 2, TB_OPTION_TYPE_FLOAT = 3,
TB_OPTION_TYPE_INTEGER = 4
}
the option type enum
Functions
tb_handle_t tb_option_init (tb_char_t const *name, tb_char_t const *help, tb_option_item_t const *opts)
tb_void_t tb_option_exit (tb_handle_t option)
tb_bool_t tb_option_find (tb_handle_t option, tb_char_t const *name)
tb_bool_t tb_option_done (tb_handle_t option, tb_size_t argc, tb_char_t **argv)
tb_void_t tb_option_dump (tb_handle_t option)
tb_void_t tb_option_help (tb_handle_t option)
tb_char_t const * tb_option_item_cstr (tb_handle_t option, tb_char_t const *name)
tb_bool_t tb_option_item_bool (tb_handle_t option, tb_char_t const *name)
tb_uint8_t tb_option_item_uint8 (tb_handle_t option, tb_char_t const *name)
tb_sint8_t tb_option_item_sint8 (tb_handle_t option, tb_char_t const *name)
tb_uint16_t tb_option_item_uint16 (tb_handle_t option, tb_char_t const *name)
tb_sint16_t tb_option_item_sint16 (tb_handle_t option, tb_char_t const *name)
tb_uint32_t tb_option_item_uint32 (tb_handle_t option, tb_char_t const *name)
tb_sint32_t tb_option_item_sint32 (tb_handle_t option, tb_char_t const *name)
tb_uint64_t tb_option_item_uint64 (tb_handle_t option, tb_char_t const *name)
tb_sint64_t tb_option_item_sint64 (tb_handle_t option, tb_char_t const *name)
tb_float_t tb_option_item_float (tb_handle_t option, tb_char_t const *name)
tb_double_t tb_option_item_double (tb_handle_t option, tb_char_t const *name)
Detailed Description
The Treasure Box Library
TBox is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 2.1 of the License, or (at your option) any later version.
TBox is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with TBox; If not, see http://www.gnu.org/licenses/
Copyright (C) 2009 - 2015, ruki All rights reserved.
Author
ruki
Definition in file option.h.
Enumeration Type Documentation
enum tb_option_mode_e
the option mode enum
Enumerator
TB_OPTION_MODE_END
end
TB_OPTION_MODE_VAL
value
TB_OPTION_MODE_KEY
–key or -k
TB_OPTION_MODE_KEY_VAL
–key=value or –key value or -k=value or -k value
TB_OPTION_MODE_MORE
more and end
Definition at line 37 of file option.h.
Function Documentation
tb_bool_t tb_option_done (tb_handle_t option, tb_size_t argc, tb_char_t ** argv)
done option
Parameters
option the option handle
argc the arguments count
argv the arguments value
Returns
tb_true or tb_false
Definition at line 235 of file option.c.
References tb_option_item_t::lname, tb_option_item_t::mode, tb_option_item_t::sname, tb_boolean_init(), tb_dictionary_set(), tb_number_init_from_double(), tb_number_init_from_sint64(), tb_object_inc(), TB_OPTION_MODE_END, TB_OPTION_MODE_KEY_VAL, TB_OPTION_MODE_MORE, TB_OPTION_MODE_VAL, tb_snprintf(), tb_string_init_from_cstr(), and tb_option_item_t::type.
tb_void_t tb_option_dump (tb_handle_t option)
dump option
Parameters
option the option handle
Definition at line 551 of file option.c.
References tb_object_dump().
tb_void_t tb_option_exit (tb_handle_t option)
exit option
Parameters
option the option handle
Definition at line 210 of file option.c.
References tb_object_exit(), and tb_pstring_exit().
Referenced by tb_option_init().
tb_bool_t tb_option_find (tb_handle_t option, tb_char_t const * name)
find the option item
Parameters
option the option handle
name the option name, long name or short name
Returns
tb_true or tb_false
Definition at line 226 of file option.c.
References tb_dictionary_val().
tb_void_t tb_option_help (tb_handle_t option)
help option
Parameters
option the option handle
Definition at line 560 of file option.c.
References tb_option_item_t::help, tb_option_item_t::lname, tb_option_item_t::mode, tb_option_item_t::sname, TB_OPTION_MODE_END, TB_OPTION_MODE_KEY, TB_OPTION_MODE_KEY_VAL, TB_OPTION_MODE_MORE, TB_OPTION_MODE_VAL, tb_printf(), tb_pstring_cstr(), tb_pstring_size(), and tb_option_item_t::type.
tb_handle_t tb_option_init (tb_char_t const * name, tb_char_t const * help, tb_option_item_t const * opts)
init option
Parameters
name the command name
help the command help
opts the option list
Returns
the option handle
Definition at line 182 of file option.c.
References tb_dictionary_init(), tb_option_exit(), tb_pstring_cstrcpy(), and tb_pstring_init().
tb_bool_t tb_option_item_bool (tb_handle_t option, tb_char_t const * name)
the option item - bool
Parameters
option the option handle
name the option name, long name or short name
Returns
tb_true or tb_false
Definition at line 823 of file option.c.
References tb_boolean_bool(), tb_dictionary_val(), and tb_object_type().
tb_char_t const* tb_option_item_cstr (tb_handle_t option, tb_char_t const * name)
the option item - cstr
Parameters
option the option handle
name the option name, long name or short name
Returns
the c-string pointer
Definition at line 809 of file option.c.
References tb_dictionary_val(), tb_object_type(), tb_string_cstr(), and tb_string_size().
tb_double_t tb_option_item_double (tb_handle_t option, tb_char_t const * name)
the option item - sint64
Parameters
option the option handle
name the option name, long name or short name
Returns
the integer value
Definition at line 964 of file option.c.
References tb_dictionary_val(), tb_number_double(), and tb_object_type().
tb_float_t tb_option_item_float (tb_handle_t option, tb_char_t const * name)
the option item - float
Parameters
option the option handle
name the option name, long name or short name
Returns
the integer value
Definition at line 950 of file option.c.
References tb_dictionary_val(), tb_number_float(), and tb_object_type().
tb_sint16_t tb_option_item_sint16 (tb_handle_t option, tb_char_t const * name)
the option item - sint16
Parameters
option the option handle
name the option name, long name or short name
Returns
the integer value
Definition at line 879 of file option.c.
References tb_dictionary_val(), tb_number_sint16(), and tb_object_type().
tb_sint32_t tb_option_item_sint32 (tb_handle_t option, tb_char_t const * name)
the option item - sint32
Parameters
option the option handle
name the option name, long name or short name
Returns
the integer value
Definition at line 907 of file option.c.
References tb_dictionary_val(), tb_number_sint32(), and tb_object_type().
tb_sint64_t tb_option_item_sint64 (tb_handle_t option, tb_char_t const * name)
the option item - sint64
Parameters
option the option handle
name the option name, long name or short name
Returns
the integer value
Definition at line 935 of file option.c.
References tb_dictionary_val(), tb_number_sint64(), and tb_object_type().
tb_sint8_t tb_option_item_sint8 (tb_handle_t option, tb_char_t const * name)
the option item - sint8
Parameters
option the option handle
name the option name, long name or short name
Returns
the integer value
Definition at line 851 of file option.c.
References tb_dictionary_val(), tb_number_sint8(), and tb_object_type().
tb_uint16_t tb_option_item_uint16 (tb_handle_t option, tb_char_t const * name)
the option item - uint16
Parameters
option the option handle
name the option name, long name or short name
Returns
the integer value
Definition at line 865 of file option.c.
References tb_dictionary_val(), tb_number_uint16(), and tb_object_type().
tb_uint32_t tb_option_item_uint32 (tb_handle_t option, tb_char_t const * name)
the option item - uint32
Parameters
option the option handle
name the option name, long name or short name
Returns
the integer value
Definition at line 893 of file option.c.
References tb_dictionary_val(), tb_number_uint32(), and tb_object_type().
tb_uint64_t tb_option_item_uint64 (tb_handle_t option, tb_char_t const * name)
the option item - uint64
Parameters
option the option handle
name the option name, long name or short name
Returns
the integer value
Definition at line 921 of file option.c.
References tb_dictionary_val(), tb_number_uint64(), and tb_object_type().
tb_uint8_t tb_option_item_uint8 (tb_handle_t option, tb_char_t const * name)
the option item - uint8
Parameters
option the option handle
name the option name, long name or short name
Returns
the integer value
Definition at line 837 of file option.c.
References tb_dictionary_val(), tb_number_uint8(), and tb_object_type().