TBOX: src/network/http.h File Reference
http.h File Reference
Network
#include "prefix.h"
#include "url.h"
#include "cookies.h"
#include "../string/string.h"
#include "../container/container.h"
Data Structures
struct tb_http_range_t
the http range type
struct tb_http_sfunc_t
the http ssl func type
struct tb_http_option_t
the http option type
struct tb_http_status_t
Macros
#define TB_HTTP_PORT_DEFAULT (80)
#define TB_HTTPS_PORT_DEFAULT (443)
Enumerations
enum tb_http_method_e {
TB_HTTP_METHOD_GET = 0, TB_HTTP_METHOD_POST = 1, TB_HTTP_METHOD_HEAD = 2, TB_HTTP_METHOD_PUT = 3,
TB_HTTP_METHOD_OPTIONS = 4, TB_HTTP_METHOD_DELETE = 5, TB_HTTP_METHOD_TRACE = 6, TB_HTTP_METHOD_CONNECT = 7
}
the http method enum
enum tb_http_version_e { TB_HTTP_VERSION_10 = 0, TB_HTTP_VERSION_11 = 1 }
the http version enum
enum tb_http_seek_e { TB_HTTP_SEEK_BEG = 0, TB_HTTP_SEEK_CUR = 1, TB_HTTP_SEEK_END = 2 }
the http seek enum
enum tb_http_error_e {
TB_HTTP_ERROR_OK = 0, TB_HTTP_ERROR_RESPONSE_204 = 1, TB_HTTP_ERROR_RESPONSE_300 = 2, TB_HTTP_ERROR_RESPONSE_301 = 3,
TB_HTTP_ERROR_RESPONSE_302 = 4, TB_HTTP_ERROR_RESPONSE_303 = 5, TB_HTTP_ERROR_RESPONSE_304 = 6, TB_HTTP_ERROR_RESPONSE_400 = 7,
TB_HTTP_ERROR_RESPONSE_401 = 8, TB_HTTP_ERROR_RESPONSE_402 = 9, TB_HTTP_ERROR_RESPONSE_403 = 10, TB_HTTP_ERROR_RESPONSE_404 = 11,
TB_HTTP_ERROR_RESPONSE_405 = 12, TB_HTTP_ERROR_RESPONSE_406 = 13, TB_HTTP_ERROR_RESPONSE_407 = 14, TB_HTTP_ERROR_RESPONSE_408 = 15,
TB_HTTP_ERROR_RESPONSE_409 = 16, TB_HTTP_ERROR_RESPONSE_410 = 17, TB_HTTP_ERROR_RESPONSE_411 = 18, TB_HTTP_ERROR_RESPONSE_412 = 19,
TB_HTTP_ERROR_RESPONSE_413 = 20, TB_HTTP_ERROR_RESPONSE_414 = 21, TB_HTTP_ERROR_RESPONSE_415 = 22, TB_HTTP_ERROR_RESPONSE_416 = 23,
TB_HTTP_ERROR_RESPONSE_500 = 24, TB_HTTP_ERROR_RESPONSE_501 = 25, TB_HTTP_ERROR_RESPONSE_502 = 26, TB_HTTP_ERROR_RESPONSE_503 = 27,
TB_HTTP_ERROR_RESPONSE_504 = 28, TB_HTTP_ERROR_RESPONSE_505 = 29, TB_HTTP_ERROR_RESPONSE_506 = 30, TB_HTTP_ERROR_RESPONSE_507 = 31,
TB_HTTP_ERROR_RESPONSE_UNK = 32, TB_HTTP_ERROR_RESPONSE_NUL = 33, TB_HTTP_ERROR_UNKNOWN = 34, TB_HTTP_ERROR_DNS_FAILED = 35,
TB_HTTP_ERROR_SSL_FAILED = 36, TB_HTTP_ERROR_CONNECT_FAILED = 37, TB_HTTP_ERROR_REQUEST_FAILED = 38, TB_HTTP_ERROR_WAIT_FAILED = 39
}
the http error enum
Functions
tb_handle_t tb_http_init (tb_noarg_t)
tb_void_t tb_http_exit (tb_handle_t handle)
tb_long_t tb_http_wait (tb_handle_t handle, tb_size_t aioe, tb_long_t timeout)
tb_long_t tb_http_aopen (tb_handle_t handle)
tb_bool_t tb_http_bopen (tb_handle_t handle)
tb_long_t tb_http_aclose (tb_handle_t handle)
tb_bool_t tb_http_bclose (tb_handle_t handle)
tb_long_t tb_http_aseek (tb_handle_t handle, tb_hize_t offset)
tb_bool_t tb_http_bseek (tb_handle_t handle, tb_hize_t offset)
tb_long_t tb_http_awrit (tb_handle_t handle, tb_byte_t *data, tb_size_t size)
tb_bool_t tb_http_bwrit (tb_handle_t handle, tb_byte_t *data, tb_size_t size)
tb_long_t tb_http_aread (tb_handle_t handle, tb_byte_t *data, tb_size_t size)
tb_bool_t tb_http_bread (tb_handle_t handle, tb_byte_t *data, tb_size_t size)
tb_long_t tb_http_afwrit (tb_handle_t handle, tb_byte_t *data, tb_size_t size)
tb_bool_t tb_http_bfwrit (tb_handle_t handle, tb_byte_t *data, tb_size_t size)
tb_http_option_t * tb_http_option (tb_handle_t handle)
tb_void_t tb_http_option_dump (tb_handle_t handle)
tb_http_status_t const * tb_http_status (tb_handle_t handle)
tb_void_t tb_http_status_dump (tb_handle_t handle)
Detailed Description
The Treasure Box Library
TBox is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 2.1 of the License, or (at your option) any later version.
TBox is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with TBox; If not, see http://www.gnu.org/licenses/
Copyright (C) 2009 - 2012, ruki All rights reserved.
Author
ruki
Definition in file http.h.
Function Documentation
tb_long_t tb_http_aclose (tb_handle_t handle)
async close, allow multiple called
Parameters
handle the http handle
Returns
ok: 1, continue: 0, fail: -1
Definition at line 984 of file http.c.
References tb_gstream_aclose(), tb_gstream_clear(), tb_gstream_exit(), and tb_pstring_clear().
tb_long_t tb_http_afwrit (tb_handle_t handle, tb_byte_t * data, tb_size_t size)
async flush writ
Parameters
handle the http handle
data the data
size the size
Returns
ok: 1, continue: 0, failed: -1
Definition at line 1222 of file http.c.
References tb_gstream_afwrit().
tb_long_t tb_http_aopen (tb_handle_t handle)
async open, allow multiple called before closing
Parameters
handle the http handle
Returns
ok: 1, continue: 0, fail: -1
Definition at line 921 of file http.c.
tb_long_t tb_http_aread (tb_handle_t handle, tb_byte_t * data, tb_size_t size)
async read
Parameters
handle the http handle
data the data
size the size
Returns
ok: real size, continue: 0, fail: -1
Definition at line 1128 of file http.c.
References tb_gstream_aread().
tb_long_t tb_http_aseek (tb_handle_t handle, tb_hize_t offset)
async seek
Parameters
handle the http handle
offset the offset
Returns
ok: 1, continue: 0, fail: -1
Definition at line 1064 of file http.c.
tb_long_t tb_http_awrit (tb_handle_t handle, tb_byte_t * data, tb_size_t size)
async writ
Parameters
handle the http handle
data the data
size the size
Returns
ok: real size, continue: 0, fail: -1
Definition at line 1111 of file http.c.
References tb_gstream_awrit().
tb_bool_t tb_http_bclose (tb_handle_t handle)
block close, allow multiple called
Parameters
handle the http handle
Returns
tb_true or tb_false
Definition at line 1044 of file http.c.
tb_bool_t tb_http_bfwrit (tb_handle_t handle, tb_byte_t * data, tb_size_t size)
block flush writ
Parameters
handle the http handle
data the data
size the size
Returns
tb_true or tb_false
Definition at line 1254 of file http.c.
References tb_gstream_afwrit(), and tb_gstream_wait().
tb_bool_t tb_http_bopen (tb_handle_t handle)
block open, allow multiple called before closing
Parameters
handle the http handle
Returns
tb_true or tb_false
Definition at line 952 of file http.c.
References tb_http_option_dump(), and tb_http_status_dump().
tb_bool_t tb_http_bread (tb_handle_t handle, tb_byte_t * data, tb_size_t size)
block read
Parameters
handle the http handle
data the data
size the size
Returns
tb_true or tb_false
Definition at line 1189 of file http.c.
tb_bool_t tb_http_bseek (tb_handle_t handle, tb_hize_t offset)
block seek
Parameters
handle the http handle
offset the offset
Returns
tb_true or tb_false
Definition at line 1086 of file http.c.
tb_bool_t tb_http_bwrit (tb_handle_t handle, tb_byte_t * data, tb_size_t size)
block writ
Parameters
handle the http handle
data the data
size the size
Returns
tb_true or tb_false
Definition at line 1156 of file http.c.
tb_void_t tb_http_exit (tb_handle_t handle)
exit http
Parameters
handle the http handle
Definition at line 836 of file http.c.
References tb_gstream_exit(), and tb_pstring_exit().
tb_handle_t tb_http_init (tb_noarg_t)
init http
return the http handle
tb_http_option_t* tb_http_option (tb_handle_t handle)
the http option
Parameters
handle the http handle
Returns
the http option
Definition at line 1311 of file http.c.
tb_void_t tb_http_option_dump (tb_handle_t handle)
dump the http option
Parameters
handle the http handle
Referenced by tb_http_bopen().
tb_http_status_t const* tb_http_status (tb_handle_t handle)
the http status
Parameters
handle the http handle
Returns
the http status
Definition at line 1317 of file http.c.
tb_void_t tb_http_status_dump (tb_handle_t handle)
dump the http status
Parameters
handle the http handle
Referenced by tb_http_bopen().
tb_long_t tb_http_wait (tb_handle_t handle, tb_size_t aioe, tb_long_t timeout)
wait the http
blocking wait the single event object, so need not aiop return the event type if ok, otherwise return 0 for timeout
Parameters
handle the http handle
aioe the aioe
timeout the timeout value, return immediately if 0, infinity if -1
Returns
the event type, return 0 if timeout, return -1 if error
Definition at line 873 of file http.c.
References tb_gstream_state(), and tb_gstream_wait().