TBOX: src/tbox/container/list.c File Reference
list.c File Reference
Container
#include "list.h"
#include "list_entry.h"
#include "../libc/libc.h"
#include "../math/math.h"
#include "../memory/memory.h"
#include "../stream/stream.h"
#include "../platform/platform.h"
#include "../algorithm/algorithm.h"
Macros
#define TB_TRACE_MODULE_NAME "list"
#define TB_TRACE_MODULE_DEBUG (0)
#define TB_LIST_GROW (256)
#define TB_LIST_MAXN (1 << 30)
Functions
tb_list_ref_t tb_list_init (tb_size_t grow, tb_item_func_t func)
tb_void_t tb_list_exit (tb_list_ref_t list)
tb_void_t tb_list_clear (tb_list_ref_t list)
tb_pointer_t tb_list_head (tb_list_ref_t list)
tb_pointer_t tb_list_last (tb_list_ref_t list)
tb_size_t tb_list_size (tb_list_ref_t list)
tb_size_t tb_list_maxn (tb_list_ref_t list)
tb_size_t tb_list_insert_prev (tb_list_ref_t list, tb_size_t itor, tb_cpointer_t data)
tb_size_t tb_list_insert_next (tb_list_ref_t list, tb_size_t itor, tb_cpointer_t data)
tb_size_t tb_list_insert_head (tb_list_ref_t list, tb_cpointer_t data)
tb_size_t tb_list_insert_tail (tb_list_ref_t list, tb_cpointer_t data)
tb_void_t tb_list_replace (tb_list_ref_t list, tb_size_t itor, tb_cpointer_t data)
tb_void_t tb_list_replace_head (tb_list_ref_t list, tb_cpointer_t data)
tb_void_t tb_list_replace_last (tb_list_ref_t list, tb_cpointer_t data)
tb_size_t tb_list_remove (tb_list_ref_t list, tb_size_t itor)
tb_void_t tb_list_remove_head (tb_list_ref_t list)
tb_void_t tb_list_remove_last (tb_list_ref_t list)
tb_void_t tb_list_moveto_prev (tb_list_ref_t list, tb_size_t itor, tb_size_t move)
tb_void_t tb_list_moveto_next (tb_list_ref_t list, tb_size_t itor, tb_size_t move)
tb_void_t tb_list_moveto_head (tb_list_ref_t list, tb_size_t move)
tb_void_t tb_list_moveto_tail (tb_list_ref_t list, tb_size_t move)
tb_bool_t tb_list_load (tb_list_ref_t list, tb_stream_ref_t stream)
tb_bool_t tb_list_save (tb_list_ref_t list, tb_stream_ref_t stream)
Detailed Description
The Treasure Box Library
TBox is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 2.1 of the License, or (at your option) any later version.
TBox is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with TBox; If not, see http://www.gnu.org/licenses/
Copyright (C) 2009 - 2015, ruki All rights reserved.
Author
ruki
Definition in file list.c.
Function Documentation
tb_void_t tb_list_clear (tb_list_ref_t list)
clear list
Parameters
list the list
Definition at line 280 of file list.c.
References tb_fixed_pool_clear().
Referenced by tb_list_exit(), and tb_list_load().
tb_void_t tb_list_exit (tb_list_ref_t list)
exit list
Parameters
list the list
Definition at line 265 of file list.c.
References tb_fixed_pool_exit(), tb_list_clear(), and tb_list_ref_t.
Referenced by tb_list_init().
tb_pointer_t tb_list_head (tb_list_ref_t list)
the list head item
Parameters
list the list
Returns
the head item
Definition at line 292 of file list.c.
References tb_iterator_head(), and tb_iterator_item().
tb_list_ref_t tb_list_init (tb_size_t grow, tb_item_func_t func)
init list
Parameters
grow the grow size
func the item func
Returns
the list
Definition at line 206 of file list.c.
References tb_item_func_t::data, tb_item_func_t::dupl, tb_item_func_t::repl, tb_item_func_t::size, tb_fixed_pool_init(), TB_ITERATOR_MODE_FORWARD, TB_ITERATOR_MODE_REVERSE, tb_list_entry_init_(), tb_list_exit(), and tb_list_ref_t.
tb_size_t tb_list_insert_head (tb_list_ref_t list, tb_cpointer_t data)
insert the head item
Parameters
list the list
data the item data
Returns
the item itor
Definition at line 345 of file list.c.
References tb_iterator_head(), and tb_list_insert_prev().
tb_size_t tb_list_insert_next (tb_list_ref_t list, tb_size_t itor, tb_cpointer_t data)
insert the next item
Parameters
list the list
itor the item itor
data the item data
Returns
the item itor
Definition at line 341 of file list.c.
References tb_iterator_next(), and tb_list_insert_prev().
tb_size_t tb_list_insert_prev (tb_list_ref_t list, tb_size_t itor, tb_cpointer_t data)
insert the prev item
Parameters
list the list
itor the item itor
data the item data
Returns
the item itor
Definition at line 315 of file list.c.
References tb_iterator_tail(), tb_list_maxn(), and tb_list_size().
Referenced by tb_list_insert_head(), tb_list_insert_next(), and tb_list_insert_tail().
tb_size_t tb_list_insert_tail (tb_list_ref_t list, tb_cpointer_t data)
insert the tail item
Parameters
list the list
data the item data
Returns
the item itor
Definition at line 349 of file list.c.
References tb_iterator_tail(), and tb_list_insert_prev().
Referenced by tb_list_load().
tb_pointer_t tb_list_last (tb_list_ref_t list)
the list last item
Parameters
list the list
Returns
the last item
Definition at line 296 of file list.c.
References tb_iterator_item(), and tb_iterator_last().
tb_bool_t tb_list_load (tb_list_ref_t list, tb_stream_ref_t stream)
load list from the stream
Parameters
list the list
stream the stream
Returns
tb_true or tb_false
Definition at line 433 of file list.c.
References tb_crc_encode_cstr(), tb_list_clear(), tb_list_insert_tail(), tb_stream_bread_u32_be(), tb_stream_offset(), and tb_stream_seek().
tb_size_t tb_list_maxn (tb_list_ref_t list)
the item max count
Parameters
list the list
Returns
the item max count
Definition at line 310 of file list.c.
Referenced by tb_list_insert_prev().
tb_void_t tb_list_moveto_head (tb_list_ref_t list, tb_size_t move)
moveto the head item
Parameters
list the list
itor the item itor
Definition at line 425 of file list.c.
References tb_iterator_head(), and tb_list_moveto_prev().
tb_void_t tb_list_moveto_next (tb_list_ref_t list, tb_size_t itor, tb_size_t move)
moveto the next item
Parameters
list the list
itor the item itor
move the move itor
Definition at line 421 of file list.c.
References tb_iterator_next(), and tb_list_moveto_prev().
tb_void_t tb_list_moveto_prev (tb_list_ref_t list, tb_size_t itor, tb_size_t move)
moveto the prev item
Parameters
list the list
itor the item itor
move the move itor
Definition at line 404 of file list.c.
Referenced by tb_list_moveto_head(), tb_list_moveto_next(), and tb_list_moveto_tail().
tb_void_t tb_list_moveto_tail (tb_list_ref_t list, tb_size_t move)
moveto the tail item
Parameters
list the list
itor the item itor
Definition at line 429 of file list.c.
References tb_iterator_tail(), and tb_list_moveto_prev().
tb_size_t tb_list_remove (tb_list_ref_t list, tb_size_t itor)
remove the item
Parameters
list the list
itor the item itor
Returns
the next item
Definition at line 374 of file list.c.
References tb_iterator_tail().
Referenced by tb_list_remove_head(), and tb_list_remove_last().
tb_void_t tb_list_remove_head (tb_list_ref_t list)
remove the head item
Parameters
list the list
Definition at line 396 of file list.c.
References tb_iterator_head(), and tb_list_remove().
tb_void_t tb_list_remove_last (tb_list_ref_t list)
remove the last item
Parameters
list the list
Definition at line 400 of file list.c.
References tb_iterator_last(), and tb_list_remove().
tb_void_t tb_list_replace (tb_list_ref_t list, tb_size_t itor, tb_cpointer_t data)
replace the item
Parameters
list the list
itor the item itor
data the item data
Definition at line 353 of file list.c.
Referenced by tb_list_replace_head(), and tb_list_replace_last().
tb_void_t tb_list_replace_head (tb_list_ref_t list, tb_cpointer_t data)
replace the head item
Parameters
list the list
data the item data
Definition at line 366 of file list.c.
References tb_iterator_head(), and tb_list_replace().
tb_void_t tb_list_replace_last (tb_list_ref_t list, tb_cpointer_t data)
replace the tail item
Parameters
list the list
data the item data
Definition at line 370 of file list.c.
References tb_iterator_last(), and tb_list_replace().
tb_bool_t tb_list_save (tb_list_ref_t list, tb_stream_ref_t stream)
save list to the stream
Parameters
list the list
stream the stream
Returns
tb_true or tb_false
Definition at line 523 of file list.c.
References tb_crc_encode_cstr(), tb_for_all, tb_list_size(), tb_stream_bwrit_u32_be(), tb_stream_offset(), and tb_stream_seek().
tb_size_t tb_list_size (tb_list_ref_t list)
the item count
Parameters
list the list
Returns
the item count
Definition at line 300 of file list.c.
References tb_fixed_pool_size().
Referenced by tb_list_insert_prev(), and tb_list_save().