TBOX: src/tbox/platform/thread.h File Reference
thread.h File Reference
Platform
#include "prefix.h"
Functions
__tb_extern_c_enter__
tb_thread_ref_t tb_thread_init (tb_char_t const *name, tb_pointer_t(*func)(tb_cpointer_t), tb_cpointer_t priv, tb_size_t stack)
tb_void_t tb_thread_exit (tb_thread_ref_t thread)
tb_long_t tb_thread_wait (tb_thread_ref_t thread, tb_long_t timeout)
tb_bool_t tb_thread_suspend (tb_thread_ref_t thread)
tb_bool_t tb_thread_resume (tb_thread_ref_t thread)
tb_size_t tb_thread_self (tb_noarg_t)
tb_void_t tb_thread_return (tb_pointer_t value)
Detailed Description
The Treasure Box Library
TBox is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 2.1 of the License, or (at your option) any later version.
TBox is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with TBox; If not, see http://www.gnu.org/licenses/
Copyright (C) 2009 - 2015, ruki All rights reserved.
Author
ruki
Definition in file thread.h.
Function Documentation
tb_void_t tb_thread_exit (tb_thread_ref_t thread)
exit thread
Parameters
thread the thread
Definition at line 65 of file thread.c.
Referenced by tb_thread_pool_exit().
__tb_extern_c_enter__ tb_thread_ref_t tb_thread_init (tb_char_t const * name, tb_pointer_t(*)(tb_cpointer_t) func, tb_cpointer_t priv, tb_size_t stack)
init thread
Parameters
name the thread name, maybe null
func the thread func
priv the thread func private data
stack the thread stack, using the default stack size if be zero
Returns
the thread handle
Definition at line 36 of file thread.c.
tb_bool_t tb_thread_resume (tb_thread_ref_t thread)
resume thread
Parameters
thread the thread
Returns
tb_true or tb_false
Definition at line 102 of file thread.c.
tb_void_t tb_thread_return (tb_pointer_t value)
return the thread value
Parameters
value the value pointer
Definition at line 93 of file thread.c.
tb_size_t tb_thread_self (tb_noarg_t)
the self thread identifier
Returns
the self thread identifier
Referenced by tb_thread_store_setp(), and tb_trace_done_with_args().
tb_bool_t tb_thread_suspend (tb_thread_ref_t thread)
suspend thread
Parameters
thread the thread
Returns
tb_true or tb_false
Definition at line 97 of file thread.c.
tb_long_t tb_thread_wait (tb_thread_ref_t thread, tb_long_t timeout)
wait thread
Parameters
thread the thread
timeout the timeout
Returns
ok: 1, timeout: 0, error: -1
Definition at line 75 of file thread.c.
Referenced by tb_thread_pool_exit().