TBOX: src/tbox/libc/stdlib/stdlib.h File Reference
stdlib.h File Reference
Libc
#include "prefix.h"
Macros
#define tb_s2tou32(s) ((tb_uint32_t)tb_s2tou64(s))
#define tb_s8tou32(s) ((tb_uint32_t)tb_s8tou64(s))
#define tb_s10tou32(s) ((tb_uint32_t)tb_s10tou64(s))
#define tb_s16tou32(s) ((tb_uint32_t)tb_s16tou64(s))
#define tb_stou32(s) ((tb_uint32_t)tb_stou64(s))
#define tb_sbtou32(s, b) ((tb_uint32_t)tb_sbtou64(s, b))
#define tb_s2toi32(s) ((tb_int32_t)tb_s2tou64(s))
#define tb_s8toi32(s) ((tb_int32_t)tb_s8tou64(s))
#define tb_s10toi32(s) ((tb_int32_t)tb_s10tou64(s))
#define tb_s16toi32(s) ((tb_int32_t)tb_s16tou64(s))
#define tb_stoi32(s) ((tb_int32_t)tb_stou64(s))
#define tb_sbtoi32(s, b) ((tb_int32_t)tb_sbtou64(s, b))
#define tb_s2toi64(s) ((tb_int64_t)tb_s2tou64(s))
#define tb_s8toi64(s) ((tb_int64_t)tb_s8tou64(s))
#define tb_s10toi64(s) ((tb_int64_t)tb_s10tou64(s))
#define tb_s16toi64(s) ((tb_int64_t)tb_s16tou64(s))
#define tb_stoi64(s) ((tb_int64_t)tb_stou64(s))
#define tb_sbtoi64(s, b) ((tb_int64_t)tb_sbtou64(s, b))
#define tb_s2tof(s) ((tb_float_t)tb_s2tod(s))
#define tb_s8tof(s) ((tb_float_t)tb_s8tod(s))
#define tb_s10tof(s) ((tb_float_t)tb_s10tod(s))
#define tb_s16tof(s) ((tb_float_t)tb_s16tod(s))
#define tb_stof(s) ((tb_float_t)tb_stod(s))
#define tb_sbtof(s, b) ((tb_float_t)tb_sbtod(s, b))
#define tb_atoi(s) tb_s10toi32(s)
#define tb_atoll(s) tb_s10toi64(s)
#define tb_strtol(s, e, b) tb_sbtoi32(s, b)
#define tb_strtoll(s, e, b) tb_sbtoi64(s, b)
#define tb_atof(s) tb_s10tod(s)
#define tb_strtof(s, e) tb_s10tof(s)
#define tb_strtod(s, e) tb_s10tod(s)
#define tb_atow(s1, s2, n) tb_mbstowcs(s1, s2, n)
#define tb_wtoa(s1, s2, n) tb_wcstombs(s1, s2, n)
#define tb_rand() (tb_int_t)tb_random()
#define tb_srand(seed) tb_srandom(seed)
Functions
tb_uint64_t tb_s2tou64 (tb_char_t const *s)
tb_uint64_t tb_s8tou64 (tb_char_t const *s)
tb_uint64_t tb_s10tou64 (tb_char_t const *s)
tb_uint64_t tb_s16tou64 (tb_char_t const *s)
tb_uint64_t tb_stou64 (tb_char_t const *s)
tb_uint64_t tb_sbtou64 (tb_char_t const *s, tb_int_t base)
tb_double_t tb_s2tod (tb_char_t const *s)
tb_double_t tb_s8tod (tb_char_t const *s)
tb_double_t tb_s10tod (tb_char_t const *s)
tb_double_t tb_s16tod (tb_char_t const *s)
tb_double_t tb_stod (tb_char_t const *s)
tb_double_t tb_sbtod (tb_char_t const *s, tb_int_t base)
tb_size_t tb_mbstowcs (tb_wchar_t *s1, tb_char_t const *s2, tb_size_t n)
tb_size_t tb_wcstombs (tb_char_t *s1, tb_wchar_t const *s2, tb_size_t n)
tb_void_t tb_srandom (tb_size_t seed)
tb_long_t tb_random (tb_noarg_t)
Detailed Description
The Treasure Box Library
TBox is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 2.1 of the License, or (at your option) any later version.
TBox is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with TBox; If not, see http://www.gnu.org/licenses/
Copyright (C) 2009 - 2015, ruki All rights reserved.
Author
ruki
Definition in file stdlib.h.
Function Documentation
tb_size_t tb_mbstowcs (tb_wchar_t * s1, tb_char_t const * s2, tb_size_t n)
mbstowcs, convert string to wstring
Parameters
s1 the wstring data
s2 the string data
n the string length
Returns
the wstring length
Definition at line 40 of file mbstowcs.c.
tb_long_t tb_random (tb_noarg_t)
generate the random with range: [0, max)
Returns
the random value
tb_double_t tb_s10tod (tb_char_t const * s)
convert the decimal string to double
.e.g "9" => 9
Parameters
s the string
Returns
the double number
Definition at line 423 of file stdlib.c.
Referenced by tb_sbtod(), and tb_stod().
tb_uint64_t tb_s10tou64 (tb_char_t const * s)
convert the decimal string to uint64
.e.g "9" => 9
Parameters
s the string
Returns
the uint64 number
Definition at line 112 of file stdlib.c.
Referenced by tb_sbtou64(), and tb_stou64().
tb_double_t tb_s16tod (tb_char_t const * s)
convert the hex string to double
.e.g
"9" => 9
"0x9" => 9
Parameters
s the string
Returns
the double number
Definition at line 510 of file stdlib.c.
Referenced by tb_sbtod(), and tb_stod().
tb_uint64_t tb_s16tou64 (tb_char_t const * s)
convert the hex string to uint64
.e.g
"9" => 9
"0x9" => 9
Parameters
s the string
Returns
the uint64 number
Definition at line 149 of file stdlib.c.
Referenced by tb_sbtou64(), and tb_stou64().
tb_double_t tb_s2tod (tb_char_t const * s)
convert the binary string to double
.e.g
"1001" => 9
"0b1001" => 9
Parameters
s the string
Returns
the double number
Definition at line 249 of file stdlib.c.
Referenced by tb_sbtod(), and tb_stod().
tb_uint64_t tb_s2tou64 (tb_char_t const * s)
convert the binary string to uint64
.e.g
"1001" => 9
"0b1001" => 9
Parameters
s the string
Returns
the uint64 number
Definition at line 34 of file stdlib.c.
Referenced by tb_sbtou64(), and tb_stou64().
tb_double_t tb_s8tod (tb_char_t const * s)
convert the binary string to double
.e.g
"11" => 9
"011" => 9
Parameters
s the string
Returns
the double number
Definition at line 336 of file stdlib.c.
Referenced by tb_sbtod(), and tb_stod().
tb_uint64_t tb_s8tou64 (tb_char_t const * s)
convert the octal string to uint64
.e.g
"11" => 9
"011" => 9
Parameters
s the string
Returns
the uint64 number
Definition at line 75 of file stdlib.c.
Referenced by tb_sbtou64(), and tb_stou64().
tb_double_t tb_sbtod (tb_char_t const * s, tb_int_t base)
convert string to double using the given base number
Parameters
s the string
Returns
the double number
Definition at line 663 of file stdlib.c.
References tb_s10tod(), tb_s16tod(), tb_s2tod(), and tb_s8tod().
tb_uint64_t tb_sbtou64 (tb_char_t const * s, tb_int_t base)
convert string to uint64 using the given base number
Parameters
s the string
Returns
the uint64 number
Definition at line 217 of file stdlib.c.
References tb_s10tou64(), tb_s16tou64(), tb_s2tou64(), and tb_s8tou64().
tb_void_t tb_srandom (tb_size_t seed)
update random seed
Parameters
seed the random seed
Definition at line 34 of file random.c.
References tb_random_generator(), and tb_random_seed().
tb_double_t tb_stod (tb_char_t const * s)
auto convert string to double
.e.g
"0b1001" => 9
"011"    => 9
"9"      => 9
"0x9"    => 9
Parameters
s the string
Returns
the double number
Definition at line 640 of file stdlib.c.
References tb_s10tod(), tb_s16tod(), tb_s2tod(), and tb_s8tod().
Referenced by tb_database_sql_value_double().
tb_uint64_t tb_stou64 (tb_char_t const * s)
auto convert string to uint64
.e.g
"0b1001" => 9
"011"    => 9
"9"      => 9
"0x9"    => 9
Parameters
s the string
Returns
the uint64 number
Definition at line 194 of file stdlib.c.
References tb_s10tou64(), tb_s16tou64(), tb_s2tou64(), and tb_s8tou64().
Referenced by tb_database_sql_value_uint64().
tb_size_t tb_wcstombs (tb_char_t * s1, tb_wchar_t const * s2, tb_size_t n)
wcstombs, convert wstring to string
Parameters
s1 the string data
s2 the wstring data
n the wstring length
Returns
the string length
Definition at line 39 of file wcstombs.c.