TBOX: src/tbox/container/bloom_filter.c File Reference
bloom_filter.c File Reference
Container
#include "bloom_filter.h"
#include "../libc/libc.h"
#include "../libm/libm.h"
#include "../math/math.h"
#include "../utils/utils.h"
#include "../memory/memory.h"
#include "../stream/stream.h"
#include "../platform/platform.h"
#include "../algorithm/algorithm.h"
Macros
#define TB_TRACE_MODULE_NAME "bloom_filter"
#define TB_TRACE_MODULE_DEBUG (1)
#define TB_BLOOM_FILTER_DATA_MAXN (1 << 30)
#define TB_BLOOM_FILTER_ITEM_MAXN_DEFAULT TB_BLOOM_FILTER_ITEM_MAXN_SMALL
#define tb_bloom_filter_set1(data, i) do {(data)[(i) >> 3] |= (0x1 << ((i) & 7));} while (0)
#define tb_bloom_filter_set0(data, i) do {(data)[(i) >> 3] &= ~(0x1 << ((i) & 7));} while (0)
#define tb_bloom_filter_bset(data, i) ((data)[(i) >> 3] & (0x1 << ((i) & 7)))
Functions
tb_bloom_filter_ref_t tb_bloom_filter_init (tb_size_t probability, tb_size_t hash_count, tb_size_t item_maxn, tb_item_func_t func)
tb_void_t tb_bloom_filter_exit (tb_bloom_filter_ref_t handle)
tb_void_t tb_bloom_filter_clear (tb_bloom_filter_ref_t handle)
tb_bool_t tb_bloom_filter_set (tb_bloom_filter_ref_t handle, tb_cpointer_t data)
tb_bool_t tb_bloom_filter_get (tb_bloom_filter_ref_t handle, tb_cpointer_t data)
tb_bool_t tb_bloom_filter_load (tb_bloom_filter_ref_t bloom_filter, tb_stream_ref_t stream)
tb_bool_t tb_bloom_filter_save (tb_bloom_filter_ref_t bloom_filter, tb_stream_ref_t stream)
Detailed Description
The Treasure Box Library
TBox is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 2.1 of the License, or (at your option) any later version.
TBox is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with TBox; If not, see http://www.gnu.org/licenses/
Copyright (C) 2009 - 2015, ruki All rights reserved.
Author
ruki
Definition in file bloom_filter.c.
Function Documentation
tb_void_t tb_bloom_filter_clear (tb_bloom_filter_ref_t bloom_filter)
clear bloom filter
Parameters
bloom_filter the bloom filter
Definition at line 232 of file bloom_filter.c.
Referenced by tb_bloom_filter_load().
tb_void_t tb_bloom_filter_exit (tb_bloom_filter_ref_t bloom_filter)
exit bloom filter
Parameters
bloom_filter the bloom filter
Definition at line 219 of file bloom_filter.c.
Referenced by tb_bloom_filter_init().
tb_bool_t tb_bloom_filter_get (tb_bloom_filter_ref_t bloom_filter, tb_cpointer_t data)
get data to the bloom filter
if (tb_bloom_filter_get(filter, data))
{
    tb_trace_i("this data have been existed, get ok!");
    // note: maybe false positives
}
else
{
    tb_trace_i("this data not exists, get failed!");
}
Parameters
bloom_filter the bloom filter
data the item data
Returns
return tb_true if the data exists, otherwise return tb_false
Definition at line 271 of file bloom_filter.c.
tb_bloom_filter_ref_t tb_bloom_filter_init (tb_size_t probability, tb_size_t hash_count, tb_size_t item_maxn, tb_item_func_t func)
init bloom filter
Note
not supports iterator
Parameters
probability the probability of false positives
hash_count the hash count: < 16
item_maxn the item maxn
func the item func only for hash
Returns
the bloom_filter
Definition at line 100 of file bloom_filter.c.
References tb_item_func_t::hash, tb_bloom_filter_exit(), and tb_printf().
tb_bool_t tb_bloom_filter_load (tb_bloom_filter_ref_t bloom_filter, tb_stream_ref_t stream)
load bloom_filter from the stream
Parameters
bloom_filter the bloom filter
stream the stream
Returns
tb_true or tb_false
Definition at line 293 of file bloom_filter.c.
References tb_bloom_filter_clear(), tb_crc_encode(), tb_crc_encode_cstr(), tb_stream_bread(), tb_stream_bread_u32_be(), tb_stream_offset(), and tb_stream_seek().
tb_bool_t tb_bloom_filter_save (tb_bloom_filter_ref_t bloom_filter, tb_stream_ref_t stream)
save bloom_filter to the stream
Parameters
bloom_filter the bloom filter
stream the stream
Returns
tb_true or tb_false
Definition at line 364 of file bloom_filter.c.
References tb_crc_encode(), tb_crc_encode_cstr(), tb_stream_bwrit(), tb_stream_bwrit_u32_be(), tb_stream_offset(), and tb_stream_seek().
tb_bool_t tb_bloom_filter_set (tb_bloom_filter_ref_t bloom_filter, tb_cpointer_t data)
set data to the bloom filter
if (tb_bloom_filter_set(filter, data))
{
    tb_trace_i("this data not exists, set ok!");
}
else
{
    tb_trace_i("this data have been existed, set failed!");
    // note: maybe false positives
}
Parameters
bloom_filter the bloom filter
data the item data
Returns
return tb_false if the data have been existed, otherwise set it and return tb_true
Definition at line 241 of file bloom_filter.c.