TBOX: src/tbox/platform/platform.c File Reference
platform.c File Reference
Platform
#include "platform.h"
#include "../network/network.h"
Functions
__tb_extern_c_enter__ tb_bool_t tb_socket_context_init (tb_noarg_t)
tb_void_t tb_socket_context_exit (tb_noarg_t)
__tb_extern_c_leave__ tb_bool_t tb_platform_init (tb_handle_t priv)
tb_void_t tb_platform_exit ()
Detailed Description
The Treasure Box Library
TBox is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 2.1 of the License, or (at your option) any later version.
TBox is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with TBox; If not, see http://www.gnu.org/licenses/
Copyright (C) 2009 - 2015, ruki All rights reserved.
Author
ruki
Definition in file platform.c.
Function Documentation
__tb_extern_c_leave__ tb_bool_t tb_platform_init (tb_handle_t priv)
init the platform
Parameters
priv the platform private data pass JNIEnv* env for android pass tb_null for other platform
Returns
tb_true or tb_false
Definition at line 50 of file platform.c.
References tb_android_init(), tb_cache_time_spak(), and tb_thread_store_init().
Referenced by tb_init_().