TBOX: src/network/dns/cache.c File Reference
cache.c File Reference
Network
#include "cache.h"
#include "../../platform/platform.h"
#include "../../container/container.h"
Macros
#define TB_DNS_CACHE_MAXN (256)
Functions
tb_bool_t tb_dns_cache_init ()
tb_void_t tb_dns_cache_exit ()
tb_void_t tb_dns_cache_ctime (tb_bool_t enabled)
tb_bool_t tb_dns_cache_get (tb_char_t const *name, tb_ipv4_t *addr)
tb_void_t tb_dns_cache_set (tb_char_t const *name, tb_ipv4_t const *addr)
Detailed Description
The Treasure Box Library
TBox is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 2.1 of the License, or (at your option) any later version.
TBox is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with TBox; If not, see http://www.gnu.org/licenses/
Copyright (C) 2009 - 2012, ruki All rights reserved.
Author
ruki
Definition in file cache.c.
Function Documentation
tb_void_t tb_dns_cache_ctime (tb_bool_t enabled)
enable ctime?
Parameters
enabled enable ctime? will be lower precision and faster if be enabled and need spak it using tb_ctime_spak
Definition at line 193 of file cache.c.
tb_bool_t tb_dns_cache_get (tb_char_t const * name, tb_ipv4_t * addr)
get addr from cache
Parameters
name the host name
addr the host addr
Returns
tb_true or tb_false
Definition at line 204 of file cache.c.
References tb_hash_get(), tb_hash_size(), tb_ipv4_clr(), and tb_ipv4_set().
Referenced by tb_dns_looker_done().
tb_void_t tb_dns_cache_set (tb_char_t const * name, tb_ipv4_t const * addr)
set addr to cache
Parameters
name the host name
addr the host addr
Definition at line 262 of file cache.c.
References tb_hash_set(), tb_hash_size(), and tb_hash_walk().