TBOX: src/tbox/database/value.h File Reference
value.h File Reference
Database
#include "prefix.h"
#include "../stream/stream.h"
Data Structures
struct tb_database_sql_value_t
the sql database value type
Enumerations
enum tb_database_sql_value_type_e {
TB_DATABASE_SQL_VALUE_TYPE_NULL = 0, TB_DATABASE_SQL_VALUE_TYPE_INT8 = 1, TB_DATABASE_SQL_VALUE_TYPE_INT16 = 2, TB_DATABASE_SQL_VALUE_TYPE_INT32 = 3,
TB_DATABASE_SQL_VALUE_TYPE_INT64 = 4, TB_DATABASE_SQL_VALUE_TYPE_UINT8 = 5, TB_DATABASE_SQL_VALUE_TYPE_UINT16 = 6, TB_DATABASE_SQL_VALUE_TYPE_UINT32 = 7,
TB_DATABASE_SQL_VALUE_TYPE_UINT64 = 8, TB_DATABASE_SQL_VALUE_TYPE_FLOAT = 13, TB_DATABASE_SQL_VALUE_TYPE_DOUBLE = 14, TB_DATABASE_SQL_VALUE_TYPE_BLOB8 = 9,
TB_DATABASE_SQL_VALUE_TYPE_BLOB16 = 10, TB_DATABASE_SQL_VALUE_TYPE_BLOB32 = 11, TB_DATABASE_SQL_VALUE_TYPE_TEXT = 12
}
the sql database value type enum
Functions
tb_size_t tb_database_sql_value_size (tb_database_sql_value_t const *value)
tb_int8_t tb_database_sql_value_int8 (tb_database_sql_value_t const *value)
tb_int16_t tb_database_sql_value_int16 (tb_database_sql_value_t const *value)
tb_int32_t tb_database_sql_value_int32 (tb_database_sql_value_t const *value)
tb_int64_t tb_database_sql_value_int64 (tb_database_sql_value_t const *value)
tb_uint8_t tb_database_sql_value_uint8 (tb_database_sql_value_t const *value)
tb_uint16_t tb_database_sql_value_uint16 (tb_database_sql_value_t const *value)
tb_uint32_t tb_database_sql_value_uint32 (tb_database_sql_value_t const *value)
tb_uint64_t tb_database_sql_value_uint64 (tb_database_sql_value_t const *value)
tb_float_t tb_database_sql_value_float (tb_database_sql_value_t const *value)
tb_double_t tb_database_sql_value_double (tb_database_sql_value_t const *value)
tb_void_t tb_database_sql_value_set_null (tb_database_sql_value_t *value)
tb_void_t tb_database_sql_value_set_int8 (tb_database_sql_value_t *value, tb_int8_t number)
tb_void_t tb_database_sql_value_set_int16 (tb_database_sql_value_t *value, tb_int16_t number)
tb_void_t tb_database_sql_value_set_int32 (tb_database_sql_value_t *value, tb_int32_t number)
tb_void_t tb_database_sql_value_set_int64 (tb_database_sql_value_t *value, tb_int64_t number)
tb_void_t tb_database_sql_value_set_uint8 (tb_database_sql_value_t *value, tb_uint8_t number)
tb_void_t tb_database_sql_value_set_uint16 (tb_database_sql_value_t *value, tb_uint16_t number)
tb_void_t tb_database_sql_value_set_uint32 (tb_database_sql_value_t *value, tb_uint32_t number)
tb_void_t tb_database_sql_value_set_uint64 (tb_database_sql_value_t *value, tb_uint64_t number)
tb_void_t tb_database_sql_value_set_float (tb_database_sql_value_t *value, tb_float_t number)
tb_void_t tb_database_sql_value_set_double (tb_database_sql_value_t *value, tb_double_t number)
tb_void_t tb_database_sql_value_set_text (tb_database_sql_value_t *value, tb_char_t const *text, tb_size_t hint)
tb_void_t tb_database_sql_value_set_blob8 (tb_database_sql_value_t *value, tb_byte_t const *data, tb_size_t size)
tb_void_t tb_database_sql_value_set_blob16 (tb_database_sql_value_t *value, tb_byte_t const *data, tb_size_t size)
tb_void_t tb_database_sql_value_set_blob32 (tb_database_sql_value_t *value, tb_byte_t const *data, tb_size_t size, tb_stream_ref_t stream)
Detailed Description
The Treasure Box Library
TBox is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 2.1 of the License, or (at your option) any later version.
TBox is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with TBox; If not, see http://www.gnu.org/licenses/
Copyright (C) 2009 - 2015, ruki All rights reserved.
Author
ruki
Definition in file value.h.
Function Documentation
tb_double_t tb_database_sql_value_double (tb_database_sql_value_t const * value)
the double value
Parameters
value the value
Returns
the double value
Definition at line 293 of file value.c.
References tb_stod(), tb_database_sql_value_t::type, and tb_database_sql_value_t::u.
tb_float_t tb_database_sql_value_float (tb_database_sql_value_t const * value)
the float value
Parameters
value the value
Returns
the float value
Definition at line 256 of file value.c.
References tb_database_sql_value_t::type, and tb_database_sql_value_t::u.
tb_int16_t tb_database_sql_value_int16 (tb_database_sql_value_t const * value)
the int16 value
Parameters
value the value
Returns
the int16 value
Definition at line 87 of file value.c.
References tb_database_sql_value_int32().
tb_int32_t tb_database_sql_value_int32 (tb_database_sql_value_t const * value)
the int32 value
Parameters
value the value
Returns
the int32 value
Definition at line 91 of file value.c.
References tb_database_sql_value_t::type, and tb_database_sql_value_t::u.
Referenced by tb_database_sql_value_int16(), and tb_database_sql_value_int8().
tb_int64_t tb_database_sql_value_int64 (tb_database_sql_value_t const * value)
the int64 value
Parameters
value the value
Returns
the int64 value
Definition at line 130 of file value.c.
References tb_database_sql_value_t::type, and tb_database_sql_value_t::u.
tb_int8_t tb_database_sql_value_int8 (tb_database_sql_value_t const * value)
the int8 value
Parameters
value the value
Returns
the int8 value
Definition at line 83 of file value.c.
References tb_database_sql_value_int32().
tb_void_t tb_database_sql_value_set_blob16 (tb_database_sql_value_t * value, tb_byte_t const * data, tb_size_t size)
set the blob16 value
Parameters
value the value
data the blob data
size the blob size
Definition at line 455 of file value.c.
References tb_database_sql_value_size(), tb_database_sql_value_t::type, and tb_database_sql_value_t::u.
tb_void_t tb_database_sql_value_set_blob32 (tb_database_sql_value_t * value, tb_byte_t const * data, tb_size_t size, tb_stream_ref_t stream)
set the blob32 value
Parameters
value the value
data the blob data
size the blob size
stream the stream, using it if data == null
Definition at line 469 of file value.c.
References tb_database_sql_value_size(), tb_stream_is_opened(), tb_stream_size(), tb_database_sql_value_t::type, and tb_database_sql_value_t::u.
tb_void_t tb_database_sql_value_set_blob8 (tb_database_sql_value_t * value, tb_byte_t const * data, tb_size_t size)
set the blob8 value
Parameters
value the value
data the blob data
size the blob size
Definition at line 441 of file value.c.
References tb_database_sql_value_size(), tb_database_sql_value_t::type, and tb_database_sql_value_t::u.
tb_void_t tb_database_sql_value_set_double (tb_database_sql_value_t * value, tb_double_t number)
set the double value
Parameters
value the value
number the number
Definition at line 421 of file value.c.
References tb_database_sql_value_t::type, and tb_database_sql_value_t::u.
tb_void_t tb_database_sql_value_set_float (tb_database_sql_value_t * value, tb_float_t number)
set the float value
Parameters
value the value
number the number
Definition at line 412 of file value.c.
References tb_database_sql_value_t::type, and tb_database_sql_value_t::u.
tb_void_t tb_database_sql_value_set_int16 (tb_database_sql_value_t * value, tb_int16_t number)
set the int16 value
Parameters
value the value
number the number
Definition at line 348 of file value.c.
References tb_database_sql_value_t::type, and tb_database_sql_value_t::u.
tb_void_t tb_database_sql_value_set_int32 (tb_database_sql_value_t * value, tb_int32_t number)
set the int32 value
Parameters
value the value
number the number
Definition at line 357 of file value.c.
References tb_database_sql_value_t::type, and tb_database_sql_value_t::u.
tb_void_t tb_database_sql_value_set_int64 (tb_database_sql_value_t * value, tb_int64_t number)
set the int64 value
Parameters
value the value
number the number
Definition at line 366 of file value.c.
References tb_database_sql_value_t::type, and tb_database_sql_value_t::u.
tb_void_t tb_database_sql_value_set_int8 (tb_database_sql_value_t * value, tb_int8_t number)
set the int8 value
Parameters
value the value
number the number
Definition at line 339 of file value.c.
References tb_database_sql_value_t::type, and tb_database_sql_value_t::u.
tb_void_t tb_database_sql_value_set_null (tb_database_sql_value_t * value)
set the null value
Parameters
value the value
number the number
Definition at line 331 of file value.c.
References tb_database_sql_value_t::type.
tb_void_t tb_database_sql_value_set_text (tb_database_sql_value_t * value, tb_char_t const * text, tb_size_t hint)
set the text value
Parameters
value the value
text the text data
hint the text size hint
Definition at line 431 of file value.c.
References tb_database_sql_value_t::type, and tb_database_sql_value_t::u.
tb_void_t tb_database_sql_value_set_uint16 (tb_database_sql_value_t * value, tb_uint16_t number)
set the uint16 value
Parameters
value the value
number the number
Definition at line 384 of file value.c.
References tb_database_sql_value_t::type, and tb_database_sql_value_t::u.
tb_void_t tb_database_sql_value_set_uint32 (tb_database_sql_value_t * value, tb_uint32_t number)
set the uint32 value
Parameters
value the value
number the number
Definition at line 393 of file value.c.
References tb_database_sql_value_t::type, and tb_database_sql_value_t::u.
tb_void_t tb_database_sql_value_set_uint64 (tb_database_sql_value_t * value, tb_uint64_t number)
set the uint64 value
Parameters
value the value
number the number
Definition at line 402 of file value.c.
References tb_database_sql_value_t::type, and tb_database_sql_value_t::u.
tb_void_t tb_database_sql_value_set_uint8 (tb_database_sql_value_t * value, tb_uint8_t number)
set the uint8 value
Parameters
value the value
number the number
Definition at line 375 of file value.c.
References tb_database_sql_value_t::type, and tb_database_sql_value_t::u.
tb_size_t tb_database_sql_value_size (tb_database_sql_value_t const * value)
the value data size
Parameters
value the value
Returns
the value data size
Definition at line 40 of file value.c.
References tb_database_sql_value_t::type, and tb_database_sql_value_t::u.
Referenced by tb_database_sql_value_set_blob16(), tb_database_sql_value_set_blob32(), and tb_database_sql_value_set_blob8().
tb_uint16_t tb_database_sql_value_uint16 (tb_database_sql_value_t const * value)
the uint16 value
Parameters
value the value
Returns
the uint16 value
Definition at line 173 of file value.c.
References tb_database_sql_value_uint32().
tb_uint32_t tb_database_sql_value_uint32 (tb_database_sql_value_t const * value)
the uint32 value
Parameters
value the value
Returns
the uint32 value
Definition at line 177 of file value.c.
References tb_database_sql_value_t::type, and tb_database_sql_value_t::u.
Referenced by tb_database_sql_value_uint16(), and tb_database_sql_value_uint8().
tb_uint64_t tb_database_sql_value_uint64 (tb_database_sql_value_t const * value)
the uint64 value
Parameters
value the value
Returns
the uint64 value
Definition at line 216 of file value.c.
References tb_stou64(), tb_database_sql_value_t::type, and tb_database_sql_value_t::u.
tb_uint8_t tb_database_sql_value_uint8 (tb_database_sql_value_t const * value)
the uint8 value
Parameters
value the value
Returns
the uint8 value
Definition at line 169 of file value.c.
References tb_database_sql_value_uint32().