TBOX: src/tbox/string/static_string.h File Reference
static_string.h File Reference
#include "prefix.h"
#include "../memory/memory.h"
Functions
tb_bool_t tb_static_string_init (tb_static_string_t *string, tb_char_t *data, tb_size_t maxn)
tb_void_t tb_static_string_exit (tb_static_string_t *string)
tb_char_t const * tb_static_string_cstr (tb_static_string_t const *string)
tb_size_t tb_static_string_size (tb_static_string_t const *string)
tb_void_t tb_static_string_clear (tb_static_string_t *string)
tb_char_t const * tb_static_string_strip (tb_static_string_t *string, tb_size_t n)
tb_char_t const * tb_static_string_rtrim (tb_static_string_t *string)
tb_long_t tb_static_string_strchr (tb_static_string_t const *string, tb_size_t p, tb_char_t c)
tb_long_t tb_static_string_strichr (tb_static_string_t const *string, tb_size_t p, tb_char_t c)
tb_long_t tb_static_string_strrchr (tb_static_string_t const *string, tb_size_t p, tb_char_t c)
tb_long_t tb_static_string_strirchr (tb_static_string_t const *string, tb_size_t p, tb_char_t c)
tb_long_t tb_static_string_strstr (tb_static_string_t const *string, tb_size_t p, tb_static_string_t const *s)
tb_long_t tb_static_string_stristr (tb_static_string_t const *string, tb_size_t p, tb_static_string_t const *s)
tb_long_t tb_static_string_cstrstr (tb_static_string_t const *string, tb_size_t p, tb_char_t const *s)
tb_long_t tb_static_string_cstristr (tb_static_string_t const *string, tb_size_t p, tb_char_t const *s)
tb_long_t tb_static_string_strrstr (tb_static_string_t const *string, tb_size_t p, tb_static_string_t const *s)
tb_long_t tb_static_string_strirstr (tb_static_string_t const *string, tb_size_t p, tb_static_string_t const *s)
tb_long_t tb_static_string_cstrrstr (tb_static_string_t const *string, tb_size_t p, tb_char_t const *s)
tb_long_t tb_static_string_cstrirstr (tb_static_string_t const *string, tb_size_t p, tb_char_t const *s)
tb_char_t const * tb_static_string_strcpy (tb_static_string_t *string, tb_static_string_t const *s)
tb_char_t const * tb_static_string_cstrcpy (tb_static_string_t *string, tb_char_t const *s)
tb_char_t const * tb_static_string_cstrncpy (tb_static_string_t *string, tb_char_t const *s, tb_size_t n)
tb_char_t const * tb_static_string_cstrfcpy (tb_static_string_t *string, tb_char_t const *fmt,...)
tb_char_t const * tb_static_string_chrcat (tb_static_string_t *string, tb_char_t c)
tb_char_t const * tb_static_string_chrncat (tb_static_string_t *string, tb_char_t c, tb_size_t n)
tb_char_t const * tb_static_string_strcat (tb_static_string_t *string, tb_static_string_t const *s)
tb_char_t const * tb_static_string_cstrcat (tb_static_string_t *string, tb_char_t const *s)
tb_char_t const * tb_static_string_cstrncat (tb_static_string_t *string, tb_char_t const *s, tb_size_t n)
tb_char_t const * tb_static_string_cstrfcat (tb_static_string_t *string, tb_char_t const *fmt,...)
tb_long_t tb_static_string_strcmp (tb_static_string_t *string, tb_static_string_t const *s)
tb_long_t tb_static_string_strimp (tb_static_string_t *string, tb_static_string_t const *s)
tb_long_t tb_static_string_cstrcmp (tb_static_string_t *string, tb_char_t const *s)
tb_long_t tb_static_string_cstricmp (tb_static_string_t *string, tb_char_t const *s)
tb_long_t tb_static_string_cstrncmp (tb_static_string_t *string, tb_char_t const *s, tb_size_t n)
tb_long_t tb_static_string_cstrnicmp (tb_static_string_t *string, tb_char_t const *s, tb_size_t n)
Variables
__tb_extern_c_enter__ typedef
tb_static_buffer_t tb_static_string_t
the static string type
Detailed Description
The Treasure Box Library
TBox is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 2.1 of the License, or (at your option) any later version.
TBox is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with TBox; If not, see http://www.gnu.org/licenses/
Copyright (C) 2009 - 2015, ruki All rights reserved.
Author
ruki
Definition in file static_string.h.
Function Documentation
tb_char_t const* tb_static_string_chrcat (tb_static_string_t * string, tb_char_t c)
append charactor
Parameters
string the string
c the appended charactor
Returns
the c-string
Definition at line 270 of file static_string.c.
References tb_static_buffer_memnsetp(), and tb_static_string_size().
tb_char_t const* tb_static_string_chrncat (tb_static_string_t * string, tb_char_t c, tb_size_t n)
append charactor with the given size
Parameters
string the string
c the appended charactor
n the appended size
Returns
the c-string
Definition at line 280 of file static_string.c.
References tb_static_buffer_memnsetp(), and tb_static_string_size().
tb_void_t tb_static_string_clear (tb_static_string_t * string)
clear the string
Parameters
string the string
Definition at line 74 of file static_string.c.
References tb_static_buffer_clear(), and tb_static_buffer_data().
Referenced by tb_static_string_rtrim(), and tb_static_string_strcpy().
tb_char_t const* tb_static_string_cstr (tb_static_string_t const * string)
the c-string pointer
Parameters
string the string
Returns
the c-string
Definition at line 57 of file static_string.c.
References tb_static_buffer_data().
Referenced by tb_static_string_cstrirstr(), tb_static_string_cstristr(), tb_static_string_cstrncmp(), tb_static_string_cstrnicmp(), tb_static_string_cstrrstr(), tb_static_string_cstrstr(), tb_static_string_rtrim(), tb_static_string_strcat(), tb_static_string_strchr(), tb_static_string_strcmp(), tb_static_string_strcpy(), tb_static_string_strichr(), tb_static_string_strimp(), tb_static_string_strip(), tb_static_string_strirchr(), tb_static_string_strirstr(), tb_static_string_stristr(), tb_static_string_strrchr(), tb_static_string_strrstr(), and tb_static_string_strstr().
tb_char_t const* tb_static_string_cstrcat (tb_static_string_t * string, tb_char_t const * s)
append c-string
Parameters
string the string
s the appended c-string
Returns
the c-string
Definition at line 296 of file static_string.c.
References tb_static_string_cstrncat().
tb_long_t tb_static_string_cstrcmp (tb_static_string_t * string, tb_char_t const * s)
compare c-string
Parameters
string the string
s the compared c-string
Returns
equal: 0
Definition at line 338 of file static_string.c.
References tb_static_string_cstrncmp().
tb_char_t const* tb_static_string_cstrcpy (tb_static_string_t * string, tb_char_t const * s)
copy c-string
Parameters
string the string
s the copied c-string
Returns
the c-string
Definition at line 238 of file static_string.c.
References tb_static_string_cstrncpy().
Referenced by tb_dns_looker_init().
tb_char_t const* tb_static_string_cstrfcat (tb_static_string_t * string, tb_char_t const * fmt, ...)
append format c-string
Parameters
string the string
fmt the appended format c-string
Returns
the c-string
Definition at line 312 of file static_string.c.
References tb_static_string_cstrncat().
tb_char_t const* tb_static_string_cstrfcpy (tb_static_string_t * string, tb_char_t const * fmt, ...)
copy format c-string
Parameters
string the string
fmt the copied format c-string
Returns
the c-string
Definition at line 256 of file static_string.c.
References tb_static_string_cstrncpy().
tb_long_t tb_static_string_cstricmp (tb_static_string_t * string, tb_char_t const * s)
compare c-string and ignore case
Parameters
string the string
s the compared c-string
Returns
equal: 0
Definition at line 344 of file static_string.c.
References tb_static_string_cstrnicmp().
tb_long_t tb_static_string_cstrirstr (tb_static_string_t const * string, tb_size_t p, tb_char_t const * s)
reverse to find c-string position and ignore case
Parameters
string the string
p the start position
s the finded c-string
Returns
the real position, no find: -1
Definition at line 213 of file static_string.c.
References tb_static_string_cstr(), and tb_static_string_size().
Referenced by tb_static_string_strirstr().
tb_long_t tb_static_string_cstristr (tb_static_string_t const * string, tb_size_t p, tb_char_t const * s)
find c-string position and ignore case
Parameters
string the string
p the start position
s the finded c-string
Returns
the real position, no find: -1
Definition at line 184 of file static_string.c.
References tb_static_string_cstr(), and tb_static_string_size().
Referenced by tb_static_string_stristr().
tb_char_t const* tb_static_string_cstrncat (tb_static_string_t * string, tb_char_t const * s, tb_size_t n)
append c-string with the given size
Parameters
string the string
s the appended c-string
n the appended c-string size
Returns
the c-string
Definition at line 302 of file static_string.c.
References tb_static_buffer_memncpyp(), and tb_static_string_size().
Referenced by tb_static_string_cstrcat(), tb_static_string_cstrfcat(), and tb_static_string_strcat().
tb_long_t tb_static_string_cstrncmp (tb_static_string_t * string, tb_char_t const * s, tb_size_t n)
compare c-string with given size
Parameters
string the string
s the compared c-string #param n the compared c-string size
Returns
equal: 0
Definition at line 350 of file static_string.c.
References tb_static_string_cstr().
Referenced by tb_static_string_cstrcmp(), and tb_static_string_strcmp().
tb_char_t const* tb_static_string_cstrncpy (tb_static_string_t * string, tb_char_t const * s, tb_size_t n)
copy c-string with the given size
Parameters
string the string
s the copied c-string
n the copied c-string size
Returns
the c-string
Definition at line 246 of file static_string.c.
References tb_static_buffer_memncpy(), and tb_static_string_size().
Referenced by tb_static_string_cstrcpy(), tb_static_string_cstrfcpy(), and tb_static_string_strcpy().
tb_long_t tb_static_string_cstrnicmp (tb_static_string_t * string, tb_char_t const * s, tb_size_t n)
compare c-string with given size and ignore case
Parameters
string the string
s the compared c-string #param n the compared c-string size
Returns
equal: 0
Definition at line 356 of file static_string.c.
References tb_static_string_cstr().
Referenced by tb_static_string_cstricmp(), and tb_static_string_strimp().
tb_long_t tb_static_string_cstrrstr (tb_static_string_t const * string, tb_size_t p, tb_char_t const * s)
reverse to find c-string position
Parameters
string the string
p the start position
s the finded c-string
Returns
the real position, no find: -1
Definition at line 202 of file static_string.c.
References tb_static_string_cstr(), and tb_static_string_size().
Referenced by tb_static_string_strrstr().
tb_long_t tb_static_string_cstrstr (tb_static_string_t const * string, tb_size_t p, tb_char_t const * s)
find c-string position
Parameters
string the string
p the start position
s the finded c-string
Returns
the real position, no find: -1
Definition at line 173 of file static_string.c.
References tb_static_string_cstr(), and tb_static_string_size().
Referenced by tb_static_string_strstr().
tb_void_t tb_static_string_exit (tb_static_string_t * string)
exit string
Parameters
string the string
Definition at line 53 of file static_string.c.
References tb_static_buffer_exit().
tb_bool_t tb_static_string_init (tb_static_string_t * string, tb_char_t * data, tb_size_t maxn)
init string
Parameters
string the string
data the data
maxn the maxn
Returns
tb_true or tb_false
Definition at line 45 of file static_string.c.
References tb_static_buffer_init().
Referenced by tb_dns_looker_init().
tb_char_t const* tb_static_string_rtrim (tb_static_string_t * string)
trim the right spaces for string
Parameters
string the string
Returns
the c-string
Definition at line 99 of file static_string.c.
References tb_static_string_clear(), tb_static_string_cstr(), tb_static_string_size(), and tb_static_string_strip().
tb_size_t tb_static_string_size (tb_static_string_t const * string)
the string size
Parameters
string the string
Returns
the string size
Definition at line 65 of file static_string.c.
References tb_static_buffer_size().
Referenced by tb_static_string_chrcat(), tb_static_string_chrncat(), tb_static_string_cstrirstr(), tb_static_string_cstristr(), tb_static_string_cstrncat(), tb_static_string_cstrncpy(), tb_static_string_cstrrstr(), tb_static_string_cstrstr(), tb_static_string_rtrim(), tb_static_string_strcat(), tb_static_string_strchr(), tb_static_string_strcmp(), tb_static_string_strcpy(), tb_static_string_strichr(), tb_static_string_strimp(), tb_static_string_strip(), tb_static_string_strirchr(), and tb_static_string_strrchr().
tb_char_t const* tb_static_string_strcat (tb_static_string_t * string, tb_static_string_t const * s)
append string
Parameters
string the string
s the appended string
Returns
the c-string
Definition at line 290 of file static_string.c.
References tb_static_string_cstr(), tb_static_string_cstrncat(), and tb_static_string_size().
tb_long_t tb_static_string_strchr (tb_static_string_t const * string, tb_size_t p, tb_char_t c)
find charactor position
Parameters
string the string
p the start position
c the finded charactor
Returns
the real position, no find: -1
Definition at line 121 of file static_string.c.
References tb_static_string_cstr(), and tb_static_string_size().
tb_long_t tb_static_string_strcmp (tb_static_string_t * string, tb_static_string_t const * s)
compare string
Parameters
string the string
s the compared string
Returns
equal: 0
Definition at line 326 of file static_string.c.
References tb_static_string_cstr(), tb_static_string_cstrncmp(), and tb_static_string_size().
tb_char_t const* tb_static_string_strcpy (tb_static_string_t * string, tb_static_string_t const * s)
copy string
Parameters
string the string
s the copied string
Returns
the c-string
Definition at line 224 of file static_string.c.
References tb_static_string_clear(), tb_static_string_cstr(), tb_static_string_cstrncpy(), and tb_static_string_size().
tb_long_t tb_static_string_strichr (tb_static_string_t const * string, tb_size_t p, tb_char_t c)
find charactor position and ignore case
Parameters
string the string
p the start position
c the finded charactor
Returns
the real position, no find: -1
Definition at line 132 of file static_string.c.
References tb_static_string_cstr(), and tb_static_string_size().
tb_long_t tb_static_string_strimp (tb_static_string_t * string, tb_static_string_t const * s)
compare string and ignore case
Parameters
string the string
s the compared string
Returns
equal: 0
Definition at line 332 of file static_string.c.
References tb_static_string_cstr(), tb_static_string_cstrnicmp(), and tb_static_string_size().
tb_char_t const* tb_static_string_strip (tb_static_string_t * string, tb_size_t n)
strip the string
Parameters
string the string
n the striped size
Returns
the c-string
Definition at line 86 of file static_string.c.
References tb_static_buffer_resize(), tb_static_string_cstr(), and tb_static_string_size().
Referenced by tb_static_string_rtrim().
tb_long_t tb_static_string_strirchr (tb_static_string_t const * string, tb_size_t p, tb_char_t c)
reverse to find charactor position and ignore case
Parameters
string the string
p the start position
c the finded charactor
Returns
the real position, no find: -1
Definition at line 154 of file static_string.c.
References tb_static_string_cstr(), and tb_static_string_size().
tb_long_t tb_static_string_strirstr (tb_static_string_t const * string, tb_size_t p, tb_static_string_t const * s)
reverse to find string position and ignore case
Parameters
string the string
p the start position
s the finded string
Returns
the real position, no find: -1
Definition at line 198 of file static_string.c.
References tb_static_string_cstr(), and tb_static_string_cstrirstr().
tb_long_t tb_static_string_stristr (tb_static_string_t const * string, tb_size_t p, tb_static_string_t const * s)
find string position and ignore case
Parameters
string the string
p the start position
s the finded string
Returns
the real position, no find: -1
Definition at line 169 of file static_string.c.
References tb_static_string_cstr(), and tb_static_string_cstristr().
tb_long_t tb_static_string_strrchr (tb_static_string_t const * string, tb_size_t p, tb_char_t c)
reverse to find charactor position
Parameters
string the string
p the start position
c the finded charactor
Returns
the real position, no find: -1
Definition at line 143 of file static_string.c.
References tb_static_string_cstr(), and tb_static_string_size().
tb_long_t tb_static_string_strrstr (tb_static_string_t const * string, tb_size_t p, tb_static_string_t const * s)
reverse to find string position
Parameters
string the string
p the start position
s the finded string
Returns
the real position, no find: -1
Definition at line 194 of file static_string.c.
References tb_static_string_cstr(), and tb_static_string_cstrrstr().
tb_long_t tb_static_string_strstr (tb_static_string_t const * string, tb_size_t p, tb_static_string_t const * s)
find string position
Parameters
string the string
p the start position
s the finded string
Returns
the real position, no find: -1
Definition at line 165 of file static_string.c.
References tb_static_string_cstr(), and tb_static_string_cstrstr().