TBOX: src/tbox/container/single_list.h File Reference
single_list.h File Reference
Container
#include "prefix.h"
#include "item.h"
#include "iterator.h"
Functions
tb_single_list_ref_t tb_single_list_init (tb_size_t grow, tb_item_func_t func)
tb_void_t tb_single_list_exit (tb_single_list_ref_t list)
tb_void_t tb_single_list_clear (tb_single_list_ref_t list)
tb_pointer_t tb_single_list_head (tb_single_list_ref_t list)
tb_pointer_t tb_single_list_last (tb_single_list_ref_t list)
tb_size_t tb_single_list_insert_next (tb_single_list_ref_t list, tb_size_t itor, tb_cpointer_t data)
tb_size_t tb_single_list_insert_head (tb_single_list_ref_t list, tb_cpointer_t data)
tb_size_t tb_single_list_insert_tail (tb_single_list_ref_t list, tb_cpointer_t data)
tb_void_t tb_single_list_replace (tb_single_list_ref_t list, tb_size_t itor, tb_cpointer_t data)
tb_void_t tb_single_list_replace_head (tb_single_list_ref_t list, tb_cpointer_t data)
tb_void_t tb_single_list_replace_last (tb_single_list_ref_t list, tb_cpointer_t data)
tb_void_t tb_single_list_remove_next (tb_single_list_ref_t list, tb_size_t itor)
tb_void_t tb_single_list_remove_head (tb_single_list_ref_t list)
tb_bool_t tb_single_list_load (tb_single_list_ref_t list, tb_stream_ref_t stream)
tb_bool_t tb_single_list_save (tb_single_list_ref_t list, tb_stream_ref_t stream)
tb_size_t tb_single_list_size (tb_single_list_ref_t list)
tb_size_t tb_single_list_maxn (tb_single_list_ref_t list)
Variables
__tb_extern_c_enter__ typedef
tb_iterator_ref_t tb_single_list_ref_t
Detailed Description
The Treasure Box Library
TBox is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 2.1 of the License, or (at your option) any later version.
TBox is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with TBox; If not, see http://www.gnu.org/licenses/
Copyright (C) 2009 - 2015, ruki All rights reserved.
Author
ruki
Definition in file single_list.h.
Function Documentation
tb_void_t tb_single_list_clear (tb_single_list_ref_t list)
clear list
Parameters
list the list
Definition at line 271 of file single_list.c.
References tb_fixed_pool_clear().
Referenced by tb_queue_clear(), tb_single_list_exit(), and tb_single_list_load().
tb_void_t tb_single_list_exit (tb_single_list_ref_t list)
exit list
Parameters
list the list
Definition at line 256 of file single_list.c.
References tb_fixed_pool_exit(), tb_single_list_clear(), and tb_single_list_ref_t.
Referenced by tb_queue_exit(), and tb_single_list_init().
tb_pointer_t tb_single_list_head (tb_single_list_ref_t list)
the list head item
Parameters
list the list
Returns
the head item
Definition at line 283 of file single_list.c.
References tb_iterator_head(), and tb_iterator_item().
Referenced by tb_queue_head().
tb_single_list_ref_t tb_single_list_init (tb_size_t grow, tb_item_func_t func)
init list
Parameters
grow the grow size
func the item func
Returns
the list
Definition at line 199 of file single_list.c.
References tb_item_func_t::data, tb_item_func_t::dupl, tb_item_func_t::repl, tb_item_func_t::size, tb_fixed_pool_init(), TB_ITERATOR_MODE_FORWARD, tb_single_list_entry_init_(), tb_single_list_exit(), and tb_single_list_ref_t.
Referenced by tb_queue_init().
tb_size_t tb_single_list_insert_head (tb_single_list_ref_t list, tb_cpointer_t data)
insert the head item
Parameters
list the list
data the item data
Returns
the item itor
Definition at line 332 of file single_list.c.
References tb_iterator_tail(), tb_single_list_maxn(), and tb_single_list_size().
tb_size_t tb_single_list_insert_next (tb_single_list_ref_t list, tb_size_t itor, tb_cpointer_t data)
insert the next item
Parameters
list the list
itor the item itor
data the item data
Returns
the item itor
Definition at line 306 of file single_list.c.
References tb_iterator_tail(), tb_single_list_maxn(), and tb_single_list_size().
tb_size_t tb_single_list_insert_tail (tb_single_list_ref_t list, tb_cpointer_t data)
insert the tail item
Parameters
list the list
data the item data
Returns
the item itor
Definition at line 354 of file single_list.c.
References tb_iterator_tail(), tb_single_list_maxn(), and tb_single_list_size().
Referenced by tb_queue_put(), and tb_single_list_load().
tb_pointer_t tb_single_list_last (tb_single_list_ref_t list)
the list last item
Parameters
list the list
Returns
the last item
Definition at line 287 of file single_list.c.
References tb_iterator_item(), and tb_iterator_last().
Referenced by tb_queue_last().
tb_bool_t tb_single_list_load (tb_single_list_ref_t list, tb_stream_ref_t stream)
load list from the stream
Parameters
list the list
stream the stream
Returns
tb_true or tb_false
Definition at line 433 of file single_list.c.
References tb_crc_encode_cstr(), tb_single_list_clear(), tb_single_list_insert_tail(), tb_stream_bread_u32_be(), tb_stream_offset(), and tb_stream_seek().
Referenced by tb_queue_load().
tb_size_t tb_single_list_maxn (tb_single_list_ref_t list)
the item max count
Parameters
list the list
Returns
the item max count
Definition at line 301 of file single_list.c.
Referenced by tb_queue_full(), tb_queue_maxn(), tb_single_list_insert_head(), tb_single_list_insert_next(), and tb_single_list_insert_tail().
tb_void_t tb_single_list_remove_head (tb_single_list_ref_t list)
remove the head item
Parameters
list the list
Definition at line 417 of file single_list.c.
Referenced by tb_queue_pop().
tb_void_t tb_single_list_remove_next (tb_single_list_ref_t list, tb_size_t itor)
remove the next item
Parameters
list the list
itor the item itor
Definition at line 397 of file single_list.c.
tb_void_t tb_single_list_replace (tb_single_list_ref_t list, tb_size_t itor, tb_cpointer_t data)
replace the item
Parameters
list the list
itor the item itor
data the item data
Definition at line 376 of file single_list.c.
Referenced by tb_single_list_replace_head(), and tb_single_list_replace_last().
tb_void_t tb_single_list_replace_head (tb_single_list_ref_t list, tb_cpointer_t data)
replace the head item
Parameters
list the list
data the item data
Definition at line 389 of file single_list.c.
References tb_iterator_head(), and tb_single_list_replace().
tb_void_t tb_single_list_replace_last (tb_single_list_ref_t list, tb_cpointer_t data)
replace the tail item
Parameters
list the list
data the item data
Definition at line 393 of file single_list.c.
References tb_iterator_last(), and tb_single_list_replace().
tb_bool_t tb_single_list_save (tb_single_list_ref_t list, tb_stream_ref_t stream)
save list to the stream
Parameters
list the list
stream the stream
Returns
tb_true or tb_false
Definition at line 523 of file single_list.c.
References tb_crc_encode_cstr(), tb_for_all, tb_single_list_size(), tb_stream_bwrit_u32_be(), tb_stream_offset(), and tb_stream_seek().
Referenced by tb_queue_save().
tb_size_t tb_single_list_size (tb_single_list_ref_t list)
the item count
Parameters
list the list
Returns
the item count
Definition at line 291 of file single_list.c.
References tb_fixed_pool_size().
Referenced by tb_queue_full(), tb_queue_null(), tb_queue_size(), tb_single_list_insert_head(), tb_single_list_insert_next(), tb_single_list_insert_tail(), and tb_single_list_save().
Variable Documentation
__tb_extern_c_enter__ typedef tb_iterator_ref_t tb_single_list_ref_t
the double list ref type
list: |--—| => |----------------------------------------------—=> |---—| => |---—| => tail
       head                                                                         last
performance:
insert:
insert midd: slow
insert head: fast
insert tail: fast
insert next: fast
remove:
remove midd: slow
remove head: fast
remove last: fast
remove next: fast
iterator:
next: fast
Definition at line 69 of file single_list.h.
Referenced by tb_queue_clear(), tb_queue_exit(), tb_queue_full(), tb_queue_head(), tb_queue_last(), tb_queue_load(), tb_queue_maxn(), tb_queue_null(), tb_queue_pop(), tb_queue_put(), tb_queue_save(), tb_queue_size(), tb_single_list_exit(), and tb_single_list_init().