TBOX: src/xml/reader.c File Reference
reader.c File Reference
Xml
#include "reader.h"
#include "../charset/charset.h"
Macros
#define TB_XML_READER_ATTRIBUTES_MAXN (128)
Functions
tb_handle_t tb_xml_reader_init (tb_gstream_t *gst)
tb_void_t tb_xml_reader_exit (tb_handle_t reader)
tb_void_t tb_xml_reader_clear (tb_handle_t reader)
tb_gstream_t * tb_xml_reader_stream (tb_handle_t reader)
tb_size_t tb_xml_reader_level (tb_handle_t reader)
tb_size_t tb_xml_reader_next (tb_handle_t reader)
tb_bool_t tb_xml_reader_goto (tb_handle_t reader, tb_char_t const *path)
tb_xml_node_t * tb_xml_reader_load (tb_handle_t reader)
tb_char_t const * tb_xml_reader_version (tb_handle_t reader)
tb_char_t const * tb_xml_reader_charset (tb_handle_t reader)
tb_char_t const * tb_xml_reader_comment (tb_handle_t reader)
tb_char_t const * tb_xml_reader_cdata (tb_handle_t reader)
tb_char_t const * tb_xml_reader_text (tb_handle_t reader)
tb_char_t const * tb_xml_reader_element (tb_handle_t reader)
tb_char_t const * tb_xml_reader_doctype (tb_handle_t reader)
tb_xml_node_t const * tb_xml_reader_attributes (tb_handle_t reader)
Detailed Description
The Treasure Box Library
TBox is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 2.1 of the License, or (at your option) any later version.
TBox is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with TBox; If not, see http://www.gnu.org/licenses/
Copyright (C) 2009 - 2012, ruki All rights reserved.
Author
ruki
Definition in file reader.c.
Function Documentation
tb_xml_node_t const* tb_xml_reader_attributes (tb_handle_t reader)
the current xml node attributes
Parameters
reader the xml reader
Returns
the current xml node attributes
Definition at line 714 of file reader.c.
References tb_xml_node_t::next, tb_pstring_chrcat(), tb_pstring_clear(), tb_pstring_cstr(), tb_pstring_exit(), tb_pstring_init(), tb_pstring_size(), and tb_pstring_strcpy().
Referenced by tb_xml_reader_load(), and tb_xml_reader_next().
tb_char_t const* tb_xml_reader_cdata (tb_handle_t reader)
the current xml node cdata
Parameters
reader the xml reader
Returns
the current xml node cdata
Definition at line 660 of file reader.c.
References tb_pstring_cstr(), tb_pstring_cstrncpy(), and tb_pstring_size().
Referenced by tb_xml_reader_load().
tb_char_t const* tb_xml_reader_charset (tb_handle_t reader)
the xml charset
Parameters
reader the xml reader
Returns
the xml charset
Definition at line 638 of file reader.c.
References tb_pstring_cstr().
Referenced by tb_xml_reader_load().
tb_void_t tb_xml_reader_clear (tb_handle_t reader)
clear the xml reader,
Note
the stream will be reseted
Parameters
reader the xml reader
Definition at line 203 of file reader.c.
References tb_xml_node_t::data, tb_xml_node_t::name, tb_gstream_bseek(), and tb_pstring_clear().
tb_char_t const* tb_xml_reader_comment (tb_handle_t reader)
the current xml node comment
Parameters
reader the xml reader
Returns
the current xml node comment
Definition at line 646 of file reader.c.
References tb_pstring_cstr(), tb_pstring_cstrncpy(), and tb_pstring_size().
Referenced by tb_xml_reader_load().
tb_char_t const* tb_xml_reader_doctype (tb_handle_t reader)
the xml document type
Parameters
reader the xml reader
Returns
the xml document type
Definition at line 702 of file reader.c.
References tb_pstring_cstr().
Referenced by tb_xml_reader_load().
tb_char_t const* tb_xml_reader_element (tb_handle_t reader)
the current xml element name
Parameters
reader the xml reader
Returns
the current xml element name
Definition at line 682 of file reader.c.
References tb_pstring_cstr(), tb_pstring_cstrncpy(), and tb_pstring_size().
Referenced by tb_xml_reader_goto(), and tb_xml_reader_load().
tb_void_t tb_xml_reader_exit (tb_handle_t reader)
exit the xml reader
Parameters
reader the xml reader
Definition at line 167 of file reader.c.
References tb_xml_node_t::data, tb_xml_node_t::name, tb_gstream_exit(), and tb_pstring_exit().
tb_bool_t tb_xml_reader_goto (tb_handle_t reader, tb_char_t const * path)
seek to the given node for xml, .e.g /root/node/item
Parameters
reader the reader handle
path the xml path
Returns
tb_true or tb_false
Note
the stream will be reseted
Definition at line 419 of file reader.c.
References tb_gstream_bseek(), tb_gstream_offset(), tb_sstring_chrcat(), tb_sstring_cstr(), tb_sstring_cstrcat(), tb_sstring_cstricmp(), tb_sstring_exit(), tb_sstring_init(), tb_sstring_size(), tb_sstring_strip(), tb_sstring_strrchr(), tb_xml_reader_element(), and tb_xml_reader_next().
tb_handle_t tb_xml_reader_init (tb_gstream_t * gst)
init the xml reader
Parameters
gst the stream
Returns
the reader handle
Definition at line 132 of file reader.c.
References tb_xml_node_t::data, tb_xml_node_t::name, tb_pstring_cstrcpy(), and tb_pstring_init().
tb_size_t tb_xml_reader_level (tb_handle_t reader)
the xml level
Parameters
reader the xml reader
Returns
the xml level for tab spaces
Definition at line 239 of file reader.c.
tb_xml_node_t* tb_xml_reader_load (tb_handle_t reader)
load the xml
Parameters
reader the xml reader
Returns
the xml root node
Definition at line 510 of file reader.c.
References tb_xml_node_t::data, tb_xml_node_t::name, tb_xml_node_t::next, tb_xml_node_t::parent, tb_pstring_cstr(), tb_xml_node_append_atail(), tb_xml_node_append_ctail(), tb_xml_node_exit(), tb_xml_node_init_attribute(), tb_xml_node_init_cdata(), tb_xml_node_init_comment(), tb_xml_node_init_document(), tb_xml_node_init_document_type(), tb_xml_node_init_element(), tb_xml_node_init_text(), tb_xml_reader_attributes(), tb_xml_reader_cdata(), tb_xml_reader_charset(), tb_xml_reader_comment(), tb_xml_reader_doctype(), tb_xml_reader_element(), tb_xml_reader_next(), tb_xml_reader_text(), and tb_xml_reader_version().
tb_size_t tb_xml_reader_next (tb_handle_t reader)
the next iterator for the xml reader
Parameters
reader the xml reader
Returns
the iterator event
// init stream
tb_gstream_t* gst = tb_gstream_init_from_url(argv[1]);
if (gst && tb_gstream_bopen(gst))
{
    // init reader
    tb_handle_t reader = tb_xml_reader_init(gst);
    if (reader)
    {
        // walk
        tb_size_t e = TB_XML_READER_EVENT_NONE;
        while (e = tb_xml_reader_next(reader))
        {
            switch (e)
            {
            case TB_XML_READER_EVENT_DOCUMENT:
                {
                    tb_printf("<?xml version = \"%s\" encoding = \"%s\" ?>\n"
                        , tb_xml_reader_version(reader), tb_xml_reader_encoding(reader));
                }
                break;
            case TB_XML_READER_EVENT_DOCUMENT_TYPE:
                {
                    tb_printf("<!DOCTYPE>\n");
                }
                break;
            case TB_XML_READER_EVENT_ELEMENT_EMPTY:
                {
                    tb_char_t const*        name = tb_xml_reader_element(reader);
                    tb_xml_node_t const*    attr = tb_xml_reader_attributes(reader);
                    if (!attr) tb_printf("<%s/>\n", name);
                    else
                    {
                        tb_printf("<%s", name);
                        for (; attr; attr = attr->next)
                            tb_printf(" %s = \"%s\"", tb_pstring_cstr(&attr->name), tb_pstring_cstr(&attr->data));
                        tb_printf("/>\n");
                    }
                }
                break;
            case TB_XML_READER_EVENT_ELEMENT_BEG:
                {
                    tb_char_t const*        name = tb_xml_reader_element(reader);
                    tb_xml_node_t const*    attr = tb_xml_reader_attributes(reader);
                    if (!attr) tb_printf("<%s>\n", name);
                    else
                    {
                        tb_printf("<%s", name);
                        for (; attr; attr = attr->next)
                            tb_printf(" %s = \"%s\"", tb_pstring_cstr(&attr->name), tb_pstring_cstr(&attr->data));
                        tb_printf(">\n");
                    }
                }
                break;
            case TB_XML_READER_EVENT_ELEMENT_END:
                {
                    tb_printf("</%s>\n", tb_xml_reader_element(reader));
                }
            break;
            case TB_XML_READER_EVENT_TEXT:
                {
                    tb_printf("%s", tb_xml_reader_text(reader));
                }
                break;
            case TB_XML_READER_EVENT_CDATA:
                {
                    tb_printf("<![CDATA[%s]]>", tb_xml_reader_cdata(reader));
                }
                break;
            case TB_XML_READER_EVENT_COMMENT:
                {
                    tb_printf("<!--%s-->", tb_xml_reader_comment(reader));
                }
                break;
            default:
                break;
            }
        }
        // exit reader
        tb_xml_reader_exit(reader);
    }
    // exit stream
    tb_gstream_exit(gst);
}
Definition at line 246 of file reader.c.
References tb_xml_node_t::data, tb_xml_node_t::name, tb_xml_node_t::next, tb_gstream_bneed(), tb_gstream_bopen(), tb_gstream_bread_s8(), tb_pstring_chrcat(), tb_pstring_cstr(), tb_pstring_cstrcmp(), tb_pstring_cstrcpy(), tb_pstring_cstricmp(), tb_pstring_cstrncpy(), tb_pstring_size(), tb_pstring_strcpy(), and tb_xml_reader_attributes().
Referenced by tb_xml_reader_goto(), and tb_xml_reader_load().
tb_gstream_t* tb_xml_reader_stream (tb_handle_t reader)
the xml stream
Parameters
reader the xml reader
Returns
the xml stream
Definition at line 232 of file reader.c.
tb_char_t const* tb_xml_reader_text (tb_handle_t reader)
the current xml node text
Parameters
reader the xml reader
Returns
the current xml node text
Definition at line 674 of file reader.c.
References tb_pstring_cstr().
Referenced by tb_xml_reader_load().
tb_char_t const* tb_xml_reader_version (tb_handle_t reader)
the xml version
Parameters
reader the xml reader
Returns
the xml version
Definition at line 630 of file reader.c.
References tb_pstring_cstr().
Referenced by tb_xml_reader_load().