TBOX: src/tbox/container/circle_queue.c File Reference
circle_queue.c File Reference
Container
#include "circle_queue.h"
#include "../libc/libc.h"
#include "../math/math.h"
#include "../utils/utils.h"
#include "../memory/memory.h"
#include "../stream/stream.h"
#include "../platform/platform.h"
#include "../algorithm/algorithm.h"
Macros
#define TB_CIRCLE_QUEUE_SIZE_DEFAULT (65535)
Functions
tb_circle_queue_ref_t tb_circle_queue_init (tb_size_t maxn, tb_item_func_t func)
tb_void_t tb_circle_queue_exit (tb_circle_queue_ref_t circle_queue)
tb_void_t tb_circle_queue_clear (tb_circle_queue_ref_t circle_queue)
tb_void_t tb_circle_queue_put (tb_circle_queue_ref_t circle_queue, tb_cpointer_t data)
tb_void_t tb_circle_queue_pop (tb_circle_queue_ref_t circle_queue)
tb_pointer_t tb_circle_queue_get (tb_circle_queue_ref_t circle_queue)
tb_pointer_t tb_circle_queue_head (tb_circle_queue_ref_t circle_queue)
tb_pointer_t tb_circle_queue_last (tb_circle_queue_ref_t circle_queue)
tb_size_t tb_circle_queue_size (tb_circle_queue_ref_t circle_queue)
tb_size_t tb_circle_queue_maxn (tb_circle_queue_ref_t circle_queue)
tb_bool_t tb_circle_queue_full (tb_circle_queue_ref_t circle_queue)
tb_bool_t tb_circle_queue_null (tb_circle_queue_ref_t circle_queue)
tb_bool_t tb_circle_queue_load (tb_circle_queue_ref_t circle_queue, tb_stream_ref_t stream)
tb_bool_t tb_circle_queue_save (tb_circle_queue_ref_t circle_queue, tb_stream_ref_t stream)
Detailed Description
The Treasure Box Library
TBox is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 2.1 of the License, or (at your option) any later version.
TBox is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with TBox; If not, see http://www.gnu.org/licenses/
Copyright (C) 2009 - 2015, ruki All rights reserved.
Author
ruki
Definition in file circle_queue.c.
Function Documentation
tb_void_t tb_circle_queue_clear (tb_circle_queue_ref_t queue)
clear the queue
Parameters
queue the queue
Definition at line 230 of file circle_queue.c.
References tb_circle_queue_null(), and tb_circle_queue_pop().
Referenced by tb_circle_queue_exit(), and tb_circle_queue_load().
tb_void_t tb_circle_queue_exit (tb_circle_queue_ref_t queue)
exit queue
Parameters
queue the queue
Definition at line 215 of file circle_queue.c.
References tb_circle_queue_clear().
Referenced by tb_circle_queue_init().
tb_bool_t tb_circle_queue_full (tb_circle_queue_ref_t queue)
the queue full?
Parameters
queue the queue
Returns
tb_true or tb_false
Definition at line 289 of file circle_queue.c.
Referenced by tb_circle_queue_put().
tb_pointer_t tb_circle_queue_get (tb_circle_queue_ref_t queue)
get the queue item
Parameters
queue the queue
Returns
the queue item
Definition at line 261 of file circle_queue.c.
References tb_circle_queue_head().
tb_pointer_t tb_circle_queue_head (tb_circle_queue_ref_t queue)
the queue head item
Parameters
queue the queue
Returns
the head item
Definition at line 265 of file circle_queue.c.
References tb_iterator_head(), and tb_iterator_item().
Referenced by tb_circle_queue_get().
tb_circle_queue_ref_t tb_circle_queue_init (tb_size_t maxn, tb_item_func_t func)
init queue
Parameters
maxn the item maxn, using the default maxn if be zero
func the item func
Returns
the queue
Definition at line 160 of file circle_queue.c.
References tb_item_func_t::data, tb_item_func_t::dupl, tb_item_func_t::size, tb_circle_queue_exit(), TB_ITERATOR_MODE_FORWARD, TB_ITERATOR_MODE_MUTABLE, and TB_ITERATOR_MODE_REVERSE.
tb_pointer_t tb_circle_queue_last (tb_circle_queue_ref_t queue)
the queue last item
Parameters
queue the queue
Returns
the last item
Definition at line 269 of file circle_queue.c.
References tb_iterator_item(), and tb_iterator_last().
tb_bool_t tb_circle_queue_load (tb_circle_queue_ref_t queue, tb_stream_ref_t stream)
load queue from the stream
Parameters
queue the queue
stream the stream
Returns
tb_true or tb_false
Definition at line 305 of file circle_queue.c.
References tb_circle_queue_clear(), tb_circle_queue_put(), tb_crc_encode_cstr(), tb_stream_bread_u32_be(), tb_stream_offset(), and tb_stream_seek().
tb_size_t tb_circle_queue_maxn (tb_circle_queue_ref_t queue)
the queue maxn
Parameters
queue the queue
Returns
the queue maxn
Definition at line 281 of file circle_queue.c.
tb_bool_t tb_circle_queue_null (tb_circle_queue_ref_t queue)
the queue null?
Parameters
queue the queue
Returns
tb_true or tb_false
Definition at line 297 of file circle_queue.c.
Referenced by tb_circle_queue_clear(), and tb_circle_queue_pop().
tb_void_t tb_circle_queue_pop (tb_circle_queue_ref_t queue)
pop the queue item
Parameters
queue the queue
Definition at line 251 of file circle_queue.c.
References tb_circle_queue_null().
Referenced by tb_circle_queue_clear().
tb_void_t tb_circle_queue_put (tb_circle_queue_ref_t queue, tb_cpointer_t data)
put the queue item
Parameters
queue the queue
data the item data
Definition at line 241 of file circle_queue.c.
References tb_circle_queue_full().
Referenced by tb_circle_queue_load().
tb_bool_t tb_circle_queue_save (tb_circle_queue_ref_t queue, tb_stream_ref_t stream)
save queue to the stream
Parameters
queue the queue
stream the stream
Returns
tb_true or tb_false
Definition at line 395 of file circle_queue.c.
References tb_circle_queue_size(), tb_crc_encode_cstr(), tb_for_all, tb_stream_bwrit_u32_be(), tb_stream_offset(), and tb_stream_seek().
tb_size_t tb_circle_queue_size (tb_circle_queue_ref_t queue)
the queue size
Parameters
queue the queue
Returns
the queue size
Definition at line 273 of file circle_queue.c.
Referenced by tb_circle_queue_save().