TBOX: src/tbox/memory/impl/static_fixed_pool.c File Reference
static_fixed_pool.c File Reference
#include "static_fixed_pool.h"
Macros
#define TB_TRACE_MODULE_NAME "static_fixed_pool"
#define TB_TRACE_MODULE_DEBUG (0)
#define tb_static_fixed_pool_used_set1(used, i) do {(used)[(i) >> 3] |= (0x1 << ((i) & 7));} while (0)
#define tb_static_fixed_pool_used_set0(used, i) do {(used)[(i) >> 3] &= ~(0x1 << ((i) & 7));} while (0)
#define tb_static_fixed_pool_used_bset(used, i) ((used)[(i) >> 3] & (0x1 << ((i) & 7)))
#define tb_static_fixed_pool_find_free(v) tb_bits_fb0_le(v)
#define tb_static_fixed_pool_cache_pred(impl, i) do { (impl)->pred_index = ((i) >> TB_CPU_SHIFT) + 1; } while (0)
Typedefs
typedef
__tb_pool_data_aligned__
struct
__tb_static_fixed_pool_impl_t tb_static_fixed_pool_impl_t
Functions
tb_static_fixed_pool_ref_t tb_static_fixed_pool_init (tb_byte_t *data, tb_size_t size, tb_size_t item_size, tb_bool_t for_small_pool)
tb_void_t tb_static_fixed_pool_exit (tb_static_fixed_pool_ref_t pool)
tb_size_t tb_static_fixed_pool_size (tb_static_fixed_pool_ref_t pool)
tb_size_t tb_static_fixed_pool_maxn (tb_static_fixed_pool_ref_t pool)
tb_bool_t tb_static_fixed_pool_full (tb_static_fixed_pool_ref_t pool)
tb_bool_t tb_static_fixed_pool_null (tb_static_fixed_pool_ref_t pool)
tb_void_t tb_static_fixed_pool_clear (tb_static_fixed_pool_ref_t pool)
tb_pointer_t tb_static_fixed_pool_malloc (tb_static_fixed_pool_ref_t pool __tb_debug_decl__)
tb_bool_t tb_static_fixed_pool_free (tb_static_fixed_pool_ref_t pool, tb_pointer_t data __tb_debug_decl__)
tb_void_t tb_static_fixed_pool_walk (tb_static_fixed_pool_ref_t pool, tb_fixed_pool_item_walk_func_t func, tb_cpointer_t priv)
Detailed Description
The Treasure Box Library
TBox is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 2.1 of the License, or (at your option) any later version.
TBox is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with TBox; If not, see http://www.gnu.org/licenses/
Copyright (C) 2009 - 2015, ruki All rights reserved.
Author
ruki
Definition in file static_fixed_pool.c.
Function Documentation
tb_void_t tb_static_fixed_pool_clear (tb_static_fixed_pool_ref_t pool)
clear pool
Parameters
pool the pool
Definition at line 502 of file static_fixed_pool.c.
Referenced by tb_static_fixed_pool_exit().
tb_void_t tb_static_fixed_pool_exit (tb_static_fixed_pool_ref_t pool)
exit pool
Parameters
pool the pool
Definition at line 454 of file static_fixed_pool.c.
References tb_static_fixed_pool_clear().
tb_bool_t tb_static_fixed_pool_free (tb_static_fixed_pool_ref_t pool, tb_pointer_t data __tb_debug_decl__)
free data
Parameters
pool the pool
data the data
Returns
tb_true or tb_false
Definition at line 603 of file static_fixed_pool.c.
Referenced by tb_fixed_pool_free_(), and tb_fixed_pool_malloc_().
tb_bool_t tb_static_fixed_pool_full (tb_static_fixed_pool_ref_t pool)
is full?
Parameters
pool the pool
Returns
tb_true or tb_false
Definition at line 484 of file static_fixed_pool.c.
Referenced by tb_fixed_pool_free_(), tb_fixed_pool_malloc_(), and tb_fixed_pool_walk().
tb_static_fixed_pool_ref_t tb_static_fixed_pool_init (tb_byte_t * data, tb_size_t size, tb_size_t item_size, tb_bool_t for_small_pool)
init pool
Parameters
data the data address
size the data size
item_size the item size
for_small_pool add data size field at head for the small pool
Returns
the pool
Definition at line 376 of file static_fixed_pool.c.
tb_pointer_t tb_static_fixed_pool_malloc (tb_static_fixed_pool_ref_t pool __tb_debug_decl__)
malloc data
Parameters
pool the pool
Returns
the data
Definition at line 528 of file static_fixed_pool.c.
Referenced by tb_fixed_pool_malloc_().
tb_size_t tb_static_fixed_pool_maxn (tb_static_fixed_pool_ref_t pool)
the item maximum count
Parameters
pool the pool
Returns
the item maximum count
Definition at line 475 of file static_fixed_pool.c.
tb_bool_t tb_static_fixed_pool_null (tb_static_fixed_pool_ref_t pool)
is null?
Parameters
pool the pool
Returns
tb_true or tb_false
Definition at line 493 of file static_fixed_pool.c.
Referenced by tb_fixed_pool_free_().
tb_size_t tb_static_fixed_pool_size (tb_static_fixed_pool_ref_t pool)
the item count
Parameters
pool the pool
Returns
the item count
Definition at line 466 of file static_fixed_pool.c.
tb_void_t tb_static_fixed_pool_walk (tb_static_fixed_pool_ref_t pool, tb_fixed_pool_item_walk_func_t func, tb_cpointer_t priv)
walk data
tb_bool_t tb_static_fixed_pool_item_func(tb_pointer_t data, tb_cpointer_t priv)
{
     // ok or break
     return tb_true;
}
Parameters
pool the pool
func the walk func
priv the walk data
Definition at line 671 of file static_fixed_pool.c.
Referenced by tb_fixed_pool_walk().