TBOX: src/tbox/platform/socket.h File Reference
socket.h File Reference
Platform
#include "prefix.h"
#include "../network/ipv4.h"
Enumerations
enum tb_socket_type_e { TB_SOCKET_TYPE_NUL = 0, TB_SOCKET_TYPE_TCP = 1, TB_SOCKET_TYPE_UDP = 2 }
the socket type enum
enum tb_socket_kill_e { TB_SOCKET_KILL_RO = 0, TB_SOCKET_KILL_WO = 1, TB_SOCKET_KILL_RW = 2 }
the socket kill enum
Functions
tb_socket_ref_t tb_socket_init (tb_size_t type)
tb_bool_t tb_socket_exit (tb_socket_ref_t sock)
tb_bool_t tb_socket_pair (tb_size_t type, tb_socket_ref_t pair[2])
tb_size_t tb_socket_recv_buffer_size (tb_socket_ref_t sock)
tb_size_t tb_socket_send_buffer_size (tb_socket_ref_t sock)
tb_void_t tb_socket_block (tb_socket_ref_t sock, tb_bool_t block)
tb_long_t tb_socket_connect (tb_socket_ref_t sock, tb_ipv4_t const *addr, tb_uint16_t port)
tb_size_t tb_socket_bind (tb_socket_ref_t sock, tb_ipv4_t const *addr, tb_uint16_t port)
tb_bool_t tb_socket_listen (tb_socket_ref_t sock, tb_size_t backlog)
tb_socket_ref_t tb_socket_accept (tb_socket_ref_t sock, tb_ipv4_t *addr, tb_uint16_t *port)
tb_bool_t tb_socket_kill (tb_socket_ref_t sock, tb_size_t mode)
tb_long_t tb_socket_recv (tb_socket_ref_t sock, tb_byte_t *data, tb_size_t size)
tb_long_t tb_socket_send (tb_socket_ref_t sock, tb_byte_t const *data, tb_size_t size)
tb_long_t tb_socket_recvv (tb_socket_ref_t sock, tb_iovec_t const *list, tb_size_t size)
tb_long_t tb_socket_sendv (tb_socket_ref_t sock, tb_iovec_t const *list, tb_size_t size)
tb_hong_t tb_socket_sendf (tb_socket_ref_t sock, tb_handle_t file, tb_hize_t offset, tb_hize_t size)
tb_long_t tb_socket_urecv (tb_socket_ref_t sock, tb_ipv4_t const *addr, tb_uint16_t port, tb_byte_t *data, tb_size_t size)
tb_long_t tb_socket_usend (tb_socket_ref_t sock, tb_ipv4_t const *addr, tb_uint16_t port, tb_byte_t const *data, tb_size_t size)
tb_long_t tb_socket_urecvv (tb_socket_ref_t sock, tb_ipv4_t const *addr, tb_uint16_t port, tb_iovec_t const *list, tb_size_t size)
tb_long_t tb_socket_usendv (tb_socket_ref_t sock, tb_ipv4_t const *addr, tb_uint16_t port, tb_iovec_t const *list, tb_size_t size)
Detailed Description
The Treasure Box Library
TBox is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 2.1 of the License, or (at your option) any later version.
TBox is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with TBox; If not, see http://www.gnu.org/licenses/
Copyright (C) 2009 - 2015, ruki All rights reserved.
Author
ruki
Definition in file socket.h.
Function Documentation
tb_socket_ref_t tb_socket_accept (tb_socket_ref_t sock, tb_ipv4_t * addr, tb_uint16_t * port)
accept socket
Parameters
sock the socket
addr the client address
port the client port
Returns
the client socket
Definition at line 253 of file socket.c.
References tb_ipv4_set().
tb_size_t tb_socket_bind (tb_socket_ref_t sock, tb_ipv4_t const * addr, tb_uint16_t port)
bind socket
Parameters
sock the socket
addr the addr
port the bind port, bind a random port if port == 0
Returns
the bound port, failed: 0
Definition at line 200 of file socket.c.
tb_void_t tb_socket_block (tb_socket_ref_t sock, tb_bool_t block)
set the socket block mode
Parameters
sock the socket
block block it?
Definition at line 168 of file socket.c.
tb_long_t tb_socket_connect (tb_socket_ref_t sock, tb_ipv4_t const * addr, tb_uint16_t port)
connect socket
Parameters
sock the socket
addr the addr
port the port
Returns
ok: 1, continue: 0; failed: -1
Definition at line 177 of file socket.c.
tb_bool_t tb_socket_exit (tb_socket_ref_t sock)
exit socket
Parameters
sock the socket
Returns
tb_true or tb_false
Definition at line 313 of file socket.c.
Referenced by tb_aico_open_sock_from_type(), tb_aiop_exit(), and tb_dns_looker_exit().
tb_socket_ref_t tb_socket_init (tb_size_t type)
init socket
Parameters
type the socket type
Returns
the socket
< for iocp
Definition at line 65 of file socket.c.
Referenced by tb_aico_open_sock_from_type(), and tb_dns_looker_init().
tb_bool_t tb_socket_kill (tb_socket_ref_t sock, tb_size_t mode)
kill socket
Parameters
sock the socket
Returns
tb_true or tb_false
Definition at line 278 of file socket.c.
tb_bool_t tb_socket_listen (tb_socket_ref_t sock, tb_size_t backlog)
listen socket
Parameters
sock the socket
backlog the maximum length for the queue of pending connections
Returns
tb_true or tb_false
Definition at line 245 of file socket.c.
tb_bool_t tb_socket_pair (tb_size_t type, tb_socket_ref_t pair[2])
init socket pair
Parameters
type the socket type
pair the socket pair
Returns
the socket handle
Definition at line 111 of file socket.c.
Referenced by tb_aiop_init().
tb_long_t tb_socket_recv (tb_socket_ref_t sock, tb_byte_t * data, tb_size_t size)
recv the socket data for tcp
Parameters
sock the socket
data the data
size the size
Returns
the real size or -1
Definition at line 334 of file socket.c.
tb_size_t tb_socket_recv_buffer_size (tb_socket_ref_t sock)
the socket recv buffer size
Parameters
sock the socket
Returns
the recv size
Definition at line 148 of file socket.c.
tb_long_t tb_socket_recvv (tb_socket_ref_t sock, tb_iovec_t const * list, tb_size_t size)
recvv the socket data for tcp
Parameters
sock the socket
list the iovec list
size the iovec size
Returns
the real size or -1
Definition at line 370 of file socket.c.
tb_long_t tb_socket_send (tb_socket_ref_t sock, tb_byte_t const * data, tb_size_t size)
send the socket data for tcp
Parameters
sock the socket
data the data
size the size
Returns
the real size or -1
Definition at line 352 of file socket.c.
Referenced by tb_aiop_kill(), tb_aiop_spak(), and tb_socket_sendf().
tb_size_t tb_socket_send_buffer_size (tb_socket_ref_t sock)
the socket send buffer size
Parameters
sock the socket
Returns
the recv size
Definition at line 158 of file socket.c.
tb_hong_t tb_socket_sendf (tb_socket_ref_t sock, tb_handle_t file, tb_hize_t offset, tb_hize_t size)
sendf the socket data
Parameters
sock the socket
file the file
offset the offset
size the size
Returns
the real size or -1
Definition at line 414 of file socket.c.
References tb_file_pread(), and tb_socket_send().
tb_long_t tb_socket_sendv (tb_socket_ref_t sock, tb_iovec_t const * list, tb_size_t size)
sendv the socket data for tcp
Parameters
sock the socket
list the iovec list
size the iovec size
Returns
the real size or -1
Definition at line 392 of file socket.c.
tb_long_t tb_socket_urecv (tb_socket_ref_t sock, tb_ipv4_t const * addr, tb_uint16_t port, tb_byte_t * data, tb_size_t size)
recv the socket data for udp
Parameters
sock the socket
addr the addr
port the port
data the data
size the size
Returns
the real size or -1
Definition at line 465 of file socket.c.
tb_long_t tb_socket_urecvv (tb_socket_ref_t sock, tb_ipv4_t const * addr, tb_uint16_t port, tb_iovec_t const * list, tb_size_t size)
urecvv the socket data for udp
Parameters
sock the socket
addr the addr
port the port
list the iovec list
size the iovec size
Returns
the real size or -1
Definition at line 514 of file socket.c.
tb_long_t tb_socket_usend (tb_socket_ref_t sock, tb_ipv4_t const * addr, tb_uint16_t port, tb_byte_t const * data, tb_size_t size)
send the socket data for udp
Parameters
sock the socket
addr the addr
port the port
data the data
size the size
Returns
the real size or -1
Definition at line 490 of file socket.c.
tb_long_t tb_socket_usendv (tb_socket_ref_t sock, tb_ipv4_t const * addr, tb_uint16_t port, tb_iovec_t const * list, tb_size_t size)
usendv the socket data for udp
Parameters
sock the socket
addr the addr
port the port
list the iovec list
size the iovec size
Returns
the real size or -1
Definition at line 547 of file socket.c.