TBOX: src/memory/qbuffer.c File Reference
qbuffer.c File Reference
Memory
#include "qbuffer.h"
#include "malloc.h"
#include "../libc/libc.h"
#include "../utils/utils.h"
Functions
tb_bool_t tb_qbuffer_init (tb_qbuffer_t *buffer, tb_size_t maxn)
tb_void_t tb_qbuffer_exit (tb_qbuffer_t *buffer)
tb_byte_t * tb_qbuffer_data (tb_qbuffer_t const *buffer)
tb_byte_t * tb_qbuffer_head (tb_qbuffer_t const *buffer)
tb_byte_t * tb_qbuffer_tail (tb_qbuffer_t const *buffer)
tb_size_t tb_qbuffer_size (tb_qbuffer_t const *buffer)
tb_size_t tb_qbuffer_maxn (tb_qbuffer_t const *buffer)
tb_size_t tb_qbuffer_left (tb_qbuffer_t const *buffer)
tb_bool_t tb_qbuffer_full (tb_qbuffer_t const *buffer)
tb_bool_t tb_qbuffer_null (tb_qbuffer_t const *buffer)
tb_void_t tb_qbuffer_clear (tb_qbuffer_t *buffer)
tb_byte_t * tb_qbuffer_resize (tb_qbuffer_t *buffer, tb_size_t maxn)
tb_long_t tb_qbuffer_skip (tb_qbuffer_t *buffer, tb_size_t size)
tb_long_t tb_qbuffer_read (tb_qbuffer_t *buffer, tb_byte_t *data, tb_size_t size)
tb_long_t tb_qbuffer_writ (tb_qbuffer_t *buffer, tb_byte_t const *data, tb_size_t size)
tb_byte_t * tb_qbuffer_pull_init (tb_qbuffer_t *buffer, tb_size_t *size)
tb_void_t tb_qbuffer_pull_exit (tb_qbuffer_t *buffer, tb_size_t size)
tb_byte_t * tb_qbuffer_push_init (tb_qbuffer_t *buffer, tb_size_t *size)
tb_void_t tb_qbuffer_push_exit (tb_qbuffer_t *buffer, tb_size_t size)
Detailed Description
The Treasure Box Library
TBox is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 2.1 of the License, or (at your option) any later version.
TBox is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with TBox; If not, see http://www.gnu.org/licenses/
Copyright (C) 2009 - 2015, ruki All rights reserved.
Author
ruki
Definition in file qbuffer.c.
Function Documentation
tb_void_t tb_qbuffer_clear (tb_qbuffer_t * buffer)
clear buffer
Parameters
buffer the buffer
Definition at line 106 of file qbuffer.c.
Referenced by tb_filter_cler(), tb_gstream_clos(), and tb_gstream_seek().
tb_byte_t* tb_qbuffer_data (tb_qbuffer_t const * buffer)
the buffer data
Parameters
buffer the buffer
Returns
the buffer data
Definition at line 62 of file qbuffer.c.
tb_void_t tb_qbuffer_exit (tb_qbuffer_t * buffer)
exit buffer
Parameters
buffer the buffer
Definition at line 50 of file qbuffer.c.
Referenced by tb_filter_exit(), and tb_gstream_exit().
tb_bool_t tb_qbuffer_full (tb_qbuffer_t const * buffer)
the buffer full?
Parameters
buffer the buffer
Returns
tb_true or tb_false
Definition at line 92 of file qbuffer.c.
Referenced by tb_gstream_awrit(), and tb_gstream_wait().
tb_byte_t* tb_qbuffer_head (tb_qbuffer_t const * buffer)
the buffer head
Parameters
buffer the buffer
Returns
the buffer head
Definition at line 67 of file qbuffer.c.
Referenced by tb_gstream_need().
tb_bool_t tb_qbuffer_init (tb_qbuffer_t * buffer, tb_size_t maxn)
init buffer
Parameters
buffer the buffer
maxn the buffer maxn
Returns
tb_true or tb_false
Definition at line 36 of file qbuffer.c.
tb_size_t tb_qbuffer_left (tb_qbuffer_t const * buffer)
the buffer left
Parameters
buffer the buffer
Returns
the buffer left
Definition at line 87 of file qbuffer.c.
tb_size_t tb_qbuffer_maxn (tb_qbuffer_t const * buffer)
the buffer maxn
Parameters
buffer the buffer
Returns
the buffer maxn
Definition at line 82 of file qbuffer.c.
Referenced by tb_filter_spak(), tb_gstream_aread(), tb_gstream_awrit(), tb_gstream_need(), tb_gstream_seek(), tb_gstream_sync(), and tb_gstream_wait().
tb_bool_t tb_qbuffer_null (tb_qbuffer_t const * buffer)
the buffer null?
Parameters
buffer the buffer
Returns
tb_true or tb_false
Definition at line 97 of file qbuffer.c.
Referenced by tb_gstream_aread(), tb_gstream_awrit(), tb_gstream_bread(), tb_gstream_need(), tb_gstream_seek(), tb_gstream_sync(), and tb_gstream_wait().
tb_void_t tb_qbuffer_pull_exit (tb_qbuffer_t * buffer, tb_size_t size)
exit pull buffer for reading
Parameters
buffer the buffer
size the size
Definition at line 249 of file qbuffer.c.
Referenced by tb_filter_spak(), tb_gstream_awrit(), tb_gstream_seek(), and tb_gstream_sync().
tb_byte_t* tb_qbuffer_pull_init (tb_qbuffer_t * buffer, tb_size_t * size)
init pull buffer for reading
Parameters
buffer the buffer
size the size
Returns
the data
Definition at line 234 of file qbuffer.c.
Referenced by tb_filter_spak(), tb_gstream_awrit(), tb_gstream_seek(), and tb_gstream_sync().
tb_void_t tb_qbuffer_push_exit (tb_qbuffer_t * buffer, tb_size_t size)
exit push buffer for writing
Parameters
buffer the buffer
size the size
Definition at line 296 of file qbuffer.c.
Referenced by tb_filter_spak(), tb_gstream_aread(), and tb_gstream_need().
tb_byte_t* tb_qbuffer_push_init (tb_qbuffer_t * buffer, tb_size_t * size)
init push buffer for writing
Parameters
buffer the buffer
size the size
Returns
the data
Definition at line 261 of file qbuffer.c.
Referenced by tb_filter_spak(), tb_gstream_aread(), and tb_gstream_need().
tb_long_t tb_qbuffer_read (tb_qbuffer_t * buffer, tb_byte_t * data, tb_size_t size)
read buffer
Parameters
buffer the buffer
data the data
size the size
Returns
the real size
Definition at line 171 of file qbuffer.c.
Referenced by tb_gstream_aread().
tb_byte_t* tb_qbuffer_resize (tb_qbuffer_t * buffer, tb_size_t maxn)
resize buffer size
Parameters
buffer the buffer
maxn the buffer maxn
Returns
the buffer data
Definition at line 112 of file qbuffer.c.
Referenced by tb_filter_init_from_cache(), and tb_filter_spak().
tb_size_t tb_qbuffer_size (tb_qbuffer_t const * buffer)
the buffer size
Parameters
buffer the buffer
Returns
the buffer size
Definition at line 77 of file qbuffer.c.
Referenced by tb_filter_spak(), and tb_gstream_need().
tb_long_t tb_qbuffer_skip (tb_qbuffer_t * buffer, tb_size_t size)
skip buffer
Parameters
buffer the buffer
size the skiped size
Returns
the real size
Definition at line 148 of file qbuffer.c.
tb_byte_t* tb_qbuffer_tail (tb_qbuffer_t const * buffer)
the buffer tail
Parameters
buffer the buffer
Returns
the buffer tail
Definition at line 72 of file qbuffer.c.
tb_long_t tb_qbuffer_writ (tb_qbuffer_t * buffer, tb_byte_t const * data, tb_size_t size)
writ buffer
Parameters
buffer the buffer
data the data
size the size
Returns
the real size
Definition at line 192 of file qbuffer.c.
Referenced by tb_gstream_awrit().