TBOX: src/tbox/platform/event.h File Reference
event.h File Reference
Platform
#include "prefix.h"
Functions
__tb_extern_c_enter__
tb_event_ref_t tb_event_init (tb_noarg_t)
tb_void_t tb_event_exit (tb_event_ref_t event)
tb_bool_t tb_event_post (tb_event_ref_t event)
tb_long_t tb_event_wait (tb_event_ref_t event, tb_long_t timeout)
Detailed Description
The Treasure Box Library
TBox is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 2.1 of the License, or (at your option) any later version.
TBox is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with TBox; If not, see http://www.gnu.org/licenses/
Copyright (C) 2009 - 2015, ruki All rights reserved.
Author
ruki
Definition in file event.h.
Function Documentation
tb_void_t tb_event_exit (tb_event_ref_t event)
exit event
Parameters
event the event
Definition at line 37 of file event.c.
References tb_semaphore_exit().
Referenced by tb_timer_exit().
__tb_extern_c_enter__ tb_event_ref_t tb_event_init (tb_noarg_t)
init event
Returns
the event
Referenced by tb_timer_loop().
tb_bool_t tb_event_post (tb_event_ref_t event)
post event
Parameters
event the event
Returns
tb_true or tb_false
Definition at line 41 of file event.c.
References tb_semaphore_post().
Referenced by tb_timer_exit(), tb_timer_task_init_at(), and tb_timer_task_post_at().
tb_long_t tb_event_wait (tb_event_ref_t event, tb_long_t timeout)
wait event
Parameters
event the event
timeout the timeout
Returns
ok: 1, timeout: 0, fail: -1
Definition at line 49 of file event.c.
References tb_semaphore_wait().
Referenced by tb_timer_loop().