TBOX: src/tbox/xml/node.h File Reference
node.h File Reference
Xml
#include "prefix.h"
Data Structures
struct tb_xml_node_t
the xml node
struct tb_xml_element_t
the xml element type
struct tb_xml_text_t
the xml text type
struct tb_xml_cdata_t
the xml cdata type
struct tb_xml_comment_t
the xml comment type
struct tb_xml_attribute_t
struct tb_xml_document_t
the xml document type
struct tb_xml_document_type_t
the xml document type type
Typedefs
typedef tb_xml_node_t * tb_xml_node_ref_t
the xml node ref type
Enumerations
enum tb_xml_node_type_t {
TB_XML_NODE_TYPE_NONE = 0, TB_XML_NODE_TYPE_ELEMENT = 1, TB_XML_NODE_TYPE_ATTRIBUTE = 2, TB_XML_NODE_TYPE_TEXT = 3,
TB_XML_NODE_TYPE_CDATA = 4, TB_XML_NODE_TYPE_ENTITY_REFERENCE = 5, TB_XML_NODE_TYPE_ENTITY = 6, TB_XML_NODE_TYPE_PROCESSING_INSTRUCTION = 7,
TB_XML_NODE_TYPE_COMMENT = 8, TB_XML_NODE_TYPE_DOCUMENT = 9, TB_XML_NODE_TYPE_DOCUMENT_TYPE = 10, TB_XML_NODE_TYPE_DOCUMENT_FRAGMENT = 11,
TB_XML_NODE_TYPE_NOTATION = 12
}
Functions
tb_xml_node_ref_t tb_xml_node_init_element (tb_char_t const *name)
tb_xml_node_ref_t tb_xml_node_init_text (tb_char_t const *data)
tb_xml_node_ref_t tb_xml_node_init_cdata (tb_char_t const *cdata)
tb_xml_node_ref_t tb_xml_node_init_comment (tb_char_t const *comment)
tb_xml_node_ref_t tb_xml_node_init_attribute (tb_char_t const *name, tb_char_t const *data)
tb_xml_node_ref_t tb_xml_node_init_document (tb_char_t const *version, tb_char_t const *encoding)
tb_xml_node_ref_t tb_xml_node_init_document_type (tb_char_t const *type)
tb_void_t tb_xml_node_exit (tb_xml_node_ref_t node)
tb_xml_node_ref_t tb_xml_node_goto (tb_xml_node_ref_t node, tb_char_t const *path)
tb_xml_node_ref_t tb_xml_node_chead (tb_xml_node_ref_t node)
tb_size_t tb_xml_node_csize (tb_xml_node_ref_t node)
tb_xml_node_ref_t tb_xml_node_ahead (tb_xml_node_ref_t node)
tb_size_t tb_xml_node_asize (tb_xml_node_ref_t node)
tb_void_t tb_xml_node_insert_next (tb_xml_node_ref_t node, tb_xml_node_ref_t next)
tb_void_t tb_xml_node_remove_next (tb_xml_node_ref_t node)
tb_void_t tb_xml_node_append_chead (tb_xml_node_ref_t node, tb_xml_node_ref_t child)
tb_void_t tb_xml_node_append_ctail (tb_xml_node_ref_t node, tb_xml_node_ref_t child)
tb_void_t tb_xml_node_remove_chead (tb_xml_node_ref_t node)
tb_void_t tb_xml_node_remove_ctail (tb_xml_node_ref_t node)
tb_void_t tb_xml_node_append_ahead (tb_xml_node_ref_t node, tb_xml_node_ref_t attribute)
tb_void_t tb_xml_node_append_atail (tb_xml_node_ref_t node, tb_xml_node_ref_t attribute)
Detailed Description
The Treasure Box Library
TBox is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 2.1 of the License, or (at your option) any later version.
TBox is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with TBox; If not, see http://www.gnu.org/licenses/
Copyright (C) 2009 - 2015, ruki All rights reserved.
Author
ruki
Definition in file node.h.
Enumeration Type Documentation
enum tb_xml_node_type_t
the xml node type
Note
see http://www.w3.org/TR/REC-DOM-Level-1/
Definition at line 46 of file node.h.
Function Documentation
tb_xml_node_ref_t tb_xml_node_ahead (tb_xml_node_ref_t node)
the xml attributes head node
Parameters
node the xml node
Returns
the xml attributes head node
Definition at line 227 of file node.c.
References tb_xml_node_t::ahead.
tb_void_t tb_xml_node_append_ahead (tb_xml_node_ref_t node, tb_xml_node_ref_t attribute)
append the node to the attributes head
Parameters
node the xml node
attribute the xml attribute node
Definition at line 354 of file node.c.
References tb_xml_node_t::ahead, tb_xml_node_t::asize, tb_xml_node_t::atail, tb_xml_node_t::next, and tb_xml_node_t::parent.
tb_void_t tb_xml_node_append_atail (tb_xml_node_ref_t node, tb_xml_node_ref_t attribute)
append the node to the attributes tail
Parameters
node the xml node
attribute the xml attribute node
Definition at line 376 of file node.c.
References tb_xml_node_t::ahead, tb_xml_node_t::asize, tb_xml_node_t::atail, tb_xml_node_t::next, and tb_xml_node_t::parent.
tb_void_t tb_xml_node_append_chead (tb_xml_node_ref_t node, tb_xml_node_ref_t child)
append the node to the childs head
Parameters
node the xml node
child the xml child node
Definition at line 266 of file node.c.
References tb_xml_node_t::chead, tb_xml_node_t::csize, tb_xml_node_t::ctail, tb_xml_node_t::next, and tb_xml_node_t::parent.
tb_void_t tb_xml_node_append_ctail (tb_xml_node_ref_t node, tb_xml_node_ref_t child)
append the node to the childs tail
Parameters
node the xml node
child the xml child node
Definition at line 288 of file node.c.
References tb_xml_node_t::chead, tb_xml_node_t::csize, tb_xml_node_t::ctail, tb_xml_node_t::next, and tb_xml_node_t::parent.
tb_size_t tb_xml_node_asize (tb_xml_node_ref_t node)
the xml attributes count
Parameters
node the xml node
Returns
the xml attributes count
Definition at line 232 of file node.c.
References tb_xml_node_t::asize.
tb_xml_node_ref_t tb_xml_node_chead (tb_xml_node_ref_t node)
the xml childs head node
Parameters
node the xml node
Returns
the xml childs head node
Definition at line 217 of file node.c.
References tb_xml_node_t::chead.
tb_size_t tb_xml_node_csize (tb_xml_node_ref_t node)
the xml childs count
Parameters
node the xml node
Returns
the xml childs count
Definition at line 222 of file node.c.
References tb_xml_node_t::csize.
tb_void_t tb_xml_node_exit (tb_xml_node_ref_t node)
exit the xml node
Parameters
node the element node
Definition at line 157 of file node.c.
References tb_xml_node_t::ahead, tb_xml_node_t::chead, tb_xml_node_t::data, tb_xml_node_t::name, tb_xml_node_t::next, tb_xml_node_exit(), and tb_xml_node_t::type.
Referenced by tb_xml_node_exit(), tb_xml_node_remove_chead(), and tb_xml_node_remove_next().
tb_xml_node_ref_t tb_xml_node_goto (tb_xml_node_ref_t node, tb_char_t const * path)
goto node by the gived path
Parameters
node the root node
Returns
the goto node
Definition at line 400 of file node.c.
References tb_xml_node_t::chead, tb_xml_node_t::name, tb_xml_node_t::next, tb_xml_node_goto(), and tb_xml_node_t::type.
Referenced by tb_xml_node_goto().
tb_xml_node_ref_t tb_xml_node_init_attribute (tb_char_t const * name, tb_char_t const * data)
init attribute node
Parameters
name the attribute name
data the attribute data
Returns
the element node
Definition at line 105 of file node.c.
References tb_xml_node_t::data, tb_xml_node_t::name, and tb_xml_node_t::type.
tb_xml_node_ref_t tb_xml_node_init_cdata (tb_char_t const * cdata)
init cdata node
Parameters
cdata the element cdata
Returns
the element node
Definition at line 73 of file node.c.
References tb_xml_node_t::data, tb_xml_node_t::name, and tb_xml_node_t::type.
tb_xml_node_ref_t tb_xml_node_init_comment (tb_char_t const * comment)
init comment node
Parameters
comment the element comment
Returns
the element node
Definition at line 89 of file node.c.
References tb_xml_node_t::data, tb_xml_node_t::name, and tb_xml_node_t::type.
tb_xml_node_ref_t tb_xml_node_init_document (tb_char_t const * version, tb_char_t const * encoding)
init document node
Parameters
version the xml version
encoding the xml encoding
Returns
the element node
Definition at line 121 of file node.c.
References tb_xml_node_t::data, tb_xml_node_t::name, and tb_xml_node_t::type.
tb_xml_node_ref_t tb_xml_node_init_document_type (tb_char_t const * type)
init document type node
Parameters
type the document type
Returns
the element node
Definition at line 140 of file node.c.
References tb_xml_node_t::data, tb_xml_node_t::name, and tb_xml_node_t::type.
tb_xml_node_ref_t tb_xml_node_init_element (tb_char_t const * name)
init element node
Parameters
name the element name
Returns
the element node
Definition at line 39 of file node.c.
References tb_xml_node_t::data, tb_xml_node_t::name, and tb_xml_node_t::type.
tb_xml_node_ref_t tb_xml_node_init_text (tb_char_t const * data)
init text node
Parameters
data the element text
Returns
the element node
Definition at line 57 of file node.c.
References tb_xml_node_t::data, tb_xml_node_t::name, and tb_xml_node_t::type.
tb_void_t tb_xml_node_insert_next (tb_xml_node_ref_t node, tb_xml_node_ref_t next)
insert to the next node
Parameters
node the xml node
next the xml next node
Definition at line 237 of file node.c.
References tb_xml_node_t::next, and tb_xml_node_t::parent.
tb_void_t tb_xml_node_remove_chead (tb_xml_node_ref_t node)
remove the node from the childs head
Parameters
node the xml node
Definition at line 311 of file node.c.
References tb_xml_node_t::chead, tb_xml_node_t::csize, tb_xml_node_t::ctail, tb_xml_node_t::next, and tb_xml_node_exit().
tb_void_t tb_xml_node_remove_ctail (tb_xml_node_ref_t node)
remove the node from the childs tail
Parameters
node the xml node
Definition at line 350 of file node.c.
tb_void_t tb_xml_node_remove_next (tb_xml_node_ref_t node)
remove the next node
Parameters
node the xml node
Definition at line 249 of file node.c.
References tb_xml_node_t::next, and tb_xml_node_exit().