TBOX: src/tbox/utils/dump.c File Reference
dump.c File Reference
Utils
#include "dump.h"
#include "../asio/asio.h"
#include "../libc/libc.h"
#include "../stream/stream.h"
Functions
tb_void_t tb_dump_data (tb_byte_t const *data, tb_size_t size)
tb_void_t tb_dump_data_from_url (tb_char_t const *url)
tb_void_t tb_dump_data_from_stream (tb_stream_ref_t stream)
Detailed Description
The Treasure Box Library
TBox is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 2.1 of the License, or (at your option) any later version.
TBox is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with TBox; If not, see http://www.gnu.org/licenses/
Copyright (C) 2009 - 2015, ruki All rights reserved.
Author
ruki
Definition in file dump.c.
Function Documentation
tb_void_t tb_dump_data (tb_byte_t const * data, tb_size_t size)
dump data
Parameters
data the data
size the size
Definition at line 37 of file dump.c.
References tb_dump_data_from_stream(), tb_stream_exit(), tb_stream_init_from_data(), and tb_stream_open().
tb_void_t tb_dump_data_from_stream (tb_stream_ref_t stream)
dump data from stream
Parameters
stream the stream
Definition at line 77 of file dump.c.
References tb_stream_beof(), tb_stream_read(), tb_stream_timeout(), and tb_stream_wait().
Referenced by tb_dump_data(), and tb_dump_data_from_url().
tb_void_t tb_dump_data_from_url (tb_char_t const * url)
dump data from url
Parameters
url the url
Definition at line 57 of file dump.c.
References tb_dump_data_from_stream(), tb_stream_exit(), tb_stream_init_from_url(), and tb_stream_open().