TBOX: src/tbox/memory/string_pool.c File Reference
string_pool.c File Reference
Memory
#include "pool.h"
#include "memory.h"
#include "../libc/libc.h"
#include "../utils/utils.h"
#include "../platform/platform.h"
#include "../container/container.h"
#include "../algorithm/algorithm.h"
Macros
#define TB_TRACE_MODULE_NAME "string_pool"
#define TB_TRACE_MODULE_DEBUG (0)
Functions
tb_string_pool_ref_t tb_string_pool_init (tb_bool_t bcase)
tb_void_t tb_string_pool_exit (tb_string_pool_ref_t pool)
tb_void_t tb_string_pool_clear (tb_string_pool_ref_t pool)
tb_char_t const * tb_string_pool_put (tb_string_pool_ref_t pool, tb_char_t const *data)
tb_void_t tb_string_pool_del (tb_string_pool_ref_t pool, tb_char_t const *data)
Detailed Description
The Treasure Box Library
TBox is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 2.1 of the License, or (at your option) any later version.
TBox is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with TBox; If not, see http://www.gnu.org/licenses/
Copyright (C) 2009 - 2015, ruki All rights reserved.
Author
ruki
Definition in file string_pool.c.
Function Documentation
tb_void_t tb_string_pool_clear (tb_string_pool_ref_t pool)
clear the string pool
Parameters
pool the string pool
Definition at line 101 of file string_pool.c.
Referenced by tb_cookies_clear().
tb_void_t tb_string_pool_del (tb_string_pool_ref_t pool, tb_char_t const * data)
remove string from the pool if the reference count be zero
Parameters
pool the string pool
data the string data
Definition at line 157 of file string_pool.c.
References tb_hash_item_t::data, tb_iterator_copy(), tb_iterator_item(), tb_iterator_remove(), and tb_iterator_tail().
tb_void_t tb_string_pool_exit (tb_string_pool_ref_t pool)
exit the string pool
Parameters
pool the string pool
Definition at line 88 of file string_pool.c.
Referenced by tb_cookies_exit(), and tb_string_pool_init().
tb_string_pool_ref_t tb_string_pool_init (tb_bool_t bcase)
init string pool for small, readonly and repeat strings
readonly, strip repeat strings and decrease memory fragmens
Parameters
bcase is case?
Returns
the string pool
Definition at line 57 of file string_pool.c.
References tb_item_func_size(), tb_item_func_str(), and tb_string_pool_exit().
tb_char_t const* tb_string_pool_put (tb_string_pool_ref_t pool, tb_char_t const * data)
put string to the pool and increase the reference count
Parameters
pool the string pool
data the string data
Returns
the string data
Definition at line 110 of file string_pool.c.
References tb_hash_item_t::data, tb_hash_item_t::name, tb_iterator_copy(), tb_iterator_item(), tb_iterator_remove(), and tb_iterator_tail().