TBOX: src/tbox/object/dictionary.h File Reference
dictionary.h File Reference
Object
#include "prefix.h"
Data Structures
struct tb_object_dictionary_item_t
the dictionary item type
Macros
#define TB_OBJECT_DICTIONARY_SIZE_MICRO (64)
#define TB_OBJECT_DICTIONARY_SIZE_SMALL (256)
#define TB_OBJECT_DICTIONARY_SIZE_LARGE (65536)
Functions
tb_object_ref_t tb_object_dictionary_init (tb_size_t size, tb_size_t incr)
tb_size_t tb_object_dictionary_size (tb_object_ref_t dictionary)
tb_void_t tb_object_dictionary_incr (tb_object_ref_t dictionary, tb_bool_t incr)
tb_iterator_ref_t tb_object_dictionary_itor (tb_object_ref_t dictionary)
tb_object_ref_t tb_object_dictionary_val (tb_object_ref_t dictionary, tb_char_t const *key)
tb_void_t tb_object_dictionary_del (tb_object_ref_t dictionary, tb_char_t const *key)
tb_void_t tb_object_dictionary_set (tb_object_ref_t dictionary, tb_char_t const *key, tb_object_ref_t val)
Detailed Description
The Treasure Box Library
TBox is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 2.1 of the License, or (at your option) any later version.
TBox is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with TBox; If not, see http://www.gnu.org/licenses/
Copyright (C) 2009 - 2015, ruki All rights reserved.
Author
ruki
Definition in file dictionary.h.
Function Documentation
tb_void_t tb_object_dictionary_del (tb_object_ref_t dictionary, tb_char_t const * key)
del dictionary item
Parameters
dictionary the dictionary object
key the key
Definition at line 229 of file dictionary.c.
tb_void_t tb_object_dictionary_incr (tb_object_ref_t dictionary, tb_bool_t incr)
set the dictionary incr
Parameters
dictionary the dictionary object
incr is increase refn?
Definition at line 250 of file dictionary.c.
tb_object_ref_t tb_object_dictionary_init (tb_size_t size, tb_size_t incr)
init dictionary
Parameters
size the dictionary size, using the default size if be zero
incr is increase refn?
Returns
the dictionary object
Definition at line 165 of file dictionary.c.
References tb_item_func_obj(), and tb_item_func_str().
tb_iterator_ref_t tb_object_dictionary_itor (tb_object_ref_t dictionary)
the dictionary iterator
Parameters
dictionary the dictionary object
Returns
the dictionary iterator
tb_for_all (tb_object_dictionary_item_t*, item, tb_object_dictionary_itor(dictionary))
{
     if (item)
     {
         tb_char_t const*    key = item->key;
         tb_object_ref_t        val = item->val;
         // ...
     }
}
Definition at line 212 of file dictionary.c.
tb_void_t tb_object_dictionary_set (tb_object_ref_t dictionary, tb_char_t const * key, tb_object_ref_t val)
set dictionary item
Parameters
dictionary the dictionary object
key the key
val the value
Definition at line 238 of file dictionary.c.
References tb_object_dec().
tb_size_t tb_object_dictionary_size (tb_object_ref_t dictionary)
the dictionary size
Parameters
dictionary the dictionary object
Returns
the dictionary size
Definition at line 203 of file dictionary.c.
tb_object_ref_t tb_object_dictionary_val (tb_object_ref_t dictionary, tb_char_t const * key)
the dictionary value
Parameters
dictionary the dictionary object
key the key
Returns
the dictionary value
Definition at line 220 of file dictionary.c.
Referenced by tb_object_seek().