TBOX: src/stream/astream.c File Reference
astream.c File Reference
Stream
#include "stream.h"
#include "../network/network.h"
#include "../platform/platform.h"
Macros
#define TB_TRACE_MODULE_NAME "astream"
#define TB_TRACE_MODULE_DEBUG (1)
Functions
tb_astream_t * tb_astream_init_from_url (tb_aicp_t *aicp, tb_char_t const *url)
tb_void_t tb_astream_clos (tb_astream_t *astream, tb_bool_t bcalling)
tb_void_t tb_astream_exit (tb_astream_t *astream, tb_bool_t bcalling)
tb_bool_t tb_astream_open_try (tb_astream_t *astream)
tb_bool_t tb_astream_open_impl (tb_astream_t *astream, tb_astream_open_func_t func, tb_pointer_t priv __tb_debug_decl__)
tb_bool_t tb_astream_read_impl (tb_astream_t *astream, tb_size_t size, tb_astream_read_func_t func, tb_pointer_t priv __tb_debug_decl__)
tb_bool_t tb_astream_writ_impl (tb_astream_t *astream, tb_byte_t const *data, tb_size_t size, tb_astream_writ_func_t func, tb_pointer_t priv __tb_debug_decl__)
tb_bool_t tb_astream_seek_impl (tb_astream_t *astream, tb_hize_t offset, tb_astream_seek_func_t func, tb_pointer_t priv __tb_debug_decl__)
tb_bool_t tb_astream_sync_impl (tb_astream_t *astream, tb_bool_t bclosing, tb_astream_sync_func_t func, tb_pointer_t priv __tb_debug_decl__)
tb_bool_t tb_astream_task_impl (tb_astream_t *astream, tb_size_t delay, tb_astream_task_func_t func, tb_pointer_t priv __tb_debug_decl__)
tb_bool_t tb_astream_oread_impl (tb_astream_t *astream, tb_size_t size, tb_astream_read_func_t func, tb_pointer_t priv __tb_debug_decl__)
tb_bool_t tb_astream_owrit_impl (tb_astream_t *astream, tb_byte_t const *data, tb_size_t size, tb_astream_writ_func_t func, tb_pointer_t priv __tb_debug_decl__)
tb_bool_t tb_astream_oseek_impl (tb_astream_t *astream, tb_hize_t offset, tb_astream_seek_func_t func, tb_pointer_t priv __tb_debug_decl__)
tb_bool_t tb_astream_read_after_impl (tb_astream_t *astream, tb_size_t delay, tb_size_t size, tb_astream_read_func_t func, tb_pointer_t priv __tb_debug_decl__)
tb_bool_t tb_astream_writ_after_impl (tb_astream_t *astream, tb_size_t delay, tb_byte_t const *data, tb_size_t size, tb_astream_writ_func_t func, tb_pointer_t priv __tb_debug_decl__)
tb_aicp_t * tb_astream_aicp (tb_astream_t *astream)
tb_char_t const * tb_astream_func (tb_astream_t *astream)
tb_char_t const * tb_astream_file (tb_astream_t *astream)
tb_size_t tb_astream_line (tb_astream_t *astream)
Detailed Description
The Treasure Box Library
TBox is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 2.1 of the License, or (at your option) any later version.
TBox is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with TBox; If not, see http://www.gnu.org/licenses/
Copyright (C) 2009 - 2015, ruki All rights reserved.
Author
ruki
Definition in file astream.c.
Function Documentation
tb_aicp_t* tb_astream_aicp (tb_astream_t * astream)
the stream aicp
Parameters
astream the stream
Returns
the stream aicp
Definition at line 755 of file astream.c.
References tb_astream_t::aicp.
Referenced by tb_astream_init_filter_from_cache(), tb_astream_init_filter_from_charset(), tb_astream_init_filter_from_chunked(), tb_astream_init_filter_from_null(), tb_astream_init_filter_from_zip(), tb_tstream_init_au(), tb_tstream_init_da(), tb_tstream_init_ua(), tb_tstream_open(), and tb_tstream_resume().
tb_void_t tb_astream_clos (tb_astream_t * astream, tb_bool_t bcalling)
close stream, will block it if be pending
Parameters
astream the stream
bcalling close it from the calling callback?
Definition at line 439 of file astream.c.
References tb_astream_t::base, tb_stream_t::bopened, tb_astream_t::clos, tb_astream_t::file, tb_astream_t::func, tb_astream_t::line, tb_stream_kill(), and tb_astream_t::wcache_data.
Referenced by tb_astream_exit().
tb_void_t tb_astream_exit (tb_astream_t * astream, tb_bool_t bcalling)
exit stream, will block it if be pending
Parameters
astream the stream
bcalling exit it from the calling callback?
Definition at line 469 of file astream.c.
References tb_astream_t::base, tb_astream_t::exit, tb_astream_t::rcache_data, tb_astream_clos(), tb_stream_t::url, and tb_astream_t::wcache_data.
Referenced by tb_astream_init_data(), tb_astream_init_file(), tb_astream_init_filter(), tb_astream_init_filter_from_cache(), tb_astream_init_filter_from_charset(), tb_astream_init_filter_from_chunked(), tb_astream_init_filter_from_null(), tb_astream_init_filter_from_zip(), tb_astream_init_from_data(), tb_astream_init_from_file(), tb_astream_init_from_http(), tb_astream_init_from_sock(), tb_astream_init_from_url(), tb_astream_init_http(), tb_astream_init_sock(), tb_tstream_exit(), tb_tstream_init_au(), tb_tstream_init_da(), tb_tstream_init_du(), tb_tstream_init_ua(), and tb_tstream_init_uu().
tb_char_t const* tb_astream_file (tb_astream_t * astream)
the stream file name from post for debug
Parameters
astream the stream
Returns
the stream file name
Definition at line 772 of file astream.c.
References tb_astream_t::file.
tb_char_t const* tb_astream_func (tb_astream_t * astream)
the stream func name from post for debug
Parameters
astream the stream
Returns
the stream func name
Definition at line 764 of file astream.c.
References tb_astream_t::func.
tb_astream_t* tb_astream_init_from_url (tb_aicp_t * aicp, tb_char_t const * url)
init stream from url
Parameters
aicp the aicp
url the url
data://base64
file://path or unix path: e.g. /root/xxxx/file
sock://host:port?tcp=
sock://host:port?udp=
socks://host:port
http://host:port/path?arg0=&arg1=...
https://host:port/path?arg0=&arg1=...
Returns
the stream
Definition at line 390 of file astream.c.
References tb_astream_exit(), tb_astream_init_data(), tb_astream_init_file(), tb_astream_init_http(), tb_astream_init_sock(), and tb_stream_ctrl().
Referenced by tb_tstream_init_au(), tb_tstream_init_du(), tb_tstream_init_ua(), and tb_tstream_init_uu().
tb_size_t tb_astream_line (tb_astream_t * astream)
the stream line number from post for debug
Parameters
astream the stream
Returns
the stream line number
Definition at line 780 of file astream.c.
References tb_astream_t::line.
tb_bool_t tb_astream_open_impl (tb_astream_t * astream, tb_astream_open_func_t func, tb_pointer_t priv __tb_debug_decl__)
open the stream
Parameters
astream the stream
func the func
priv the func data
Returns
tb_true or tb_false
Definition at line 520 of file astream.c.
References tb_astream_t::base, tb_stream_t::bopened, tb_stream_t::bstoped, tb_astream_t::file, tb_astream_t::func, tb_astream_t::line, and tb_astream_t::open.
Referenced by tb_astream_oread_impl(), tb_astream_oseek_impl(), and tb_astream_owrit_impl().
tb_bool_t tb_astream_open_try (tb_astream_t * astream)
try to open the stream for stream: file, filter, ...
Parameters
astream the stream
Returns
tb_true or tb_false
Definition at line 499 of file astream.c.
References tb_astream_t::base, tb_stream_t::bopened, tb_stream_t::bstoped, and tb_astream_t::open.
tb_bool_t tb_astream_oread_impl (tb_astream_t * astream, tb_size_t size, tb_astream_read_func_t func, tb_pointer_t priv __tb_debug_decl__)
open and read the stream, open it first if not opened
Parameters
astream the stream
size the read size, using the default size if be zero
func the func
priv the func data
Returns
tb_true or tb_false
Definition at line 652 of file astream.c.
References tb_astream_t::base, tb_stream_t::bopened, tb_astream_oread_t::func, tb_astream_t::open, tb_astream_t::open_and, tb_astream_oread_t::priv, tb_astream_oread_t::size, tb_astream_open_impl(), and tb_astream_read_impl().
tb_bool_t tb_astream_oseek_impl (tb_astream_t * astream, tb_hize_t offset, tb_astream_seek_func_t func, tb_pointer_t priv __tb_debug_decl__)
open and seek the stream, open it first if not opened
Parameters
astream the stream
offset the offset
func the func
priv the func data
Returns
tb_true or tb_false
Definition at line 689 of file astream.c.
References tb_astream_t::base, tb_stream_t::bopened, tb_astream_oseek_t::func, tb_astream_oseek_t::offset, tb_astream_t::open, tb_astream_t::open_and, tb_astream_oseek_t::priv, tb_astream_open_impl(), and tb_astream_seek_impl().
tb_bool_t tb_astream_owrit_impl (tb_astream_t * astream, tb_byte_t const * data, tb_size_t size, tb_astream_writ_func_t func, tb_pointer_t priv __tb_debug_decl__)
open and writ the stream, open it first if not opened
Parameters
astream the stream
data the data
size the size
func the func
priv the func data
Returns
tb_true or tb_false
Definition at line 670 of file astream.c.
References tb_astream_t::base, tb_stream_t::bopened, tb_astream_owrit_t::data, tb_astream_owrit_t::func, tb_astream_t::open, tb_astream_t::open_and, tb_astream_owrit_t::priv, tb_astream_owrit_t::size, tb_astream_open_impl(), and tb_astream_writ_impl().
tb_bool_t tb_astream_read_after_impl (tb_astream_t * astream, tb_size_t delay, tb_size_t size, tb_astream_read_func_t func, tb_pointer_t priv __tb_debug_decl__)
read the stream after the delay time
Parameters
astream the stream
delay the delay time, ms
size the read size, using the default size if be zero
func the func
priv the func data
Returns
tb_true or tb_false
Definition at line 707 of file astream.c.
References tb_astream_t::base, tb_stream_t::bopened, tb_stream_t::bstoped, tb_astream_t::file, tb_astream_oread_t::func, tb_astream_t::func, tb_astream_t::line, tb_astream_oread_t::priv, tb_astream_oread_t::size, tb_astream_t::sync_and, tb_astream_sync_impl(), tb_astream_t::wcache_data, and tb_astream_t::wcache_maxn.
Referenced by tb_astream_read_impl().
tb_bool_t tb_astream_read_impl (tb_astream_t * astream, tb_size_t size, tb_astream_read_func_t func, tb_pointer_t priv __tb_debug_decl__)
read the stream
Parameters
astream the stream
size the read size, using the default size if be zero
func the func
priv the func data
Returns
tb_true or tb_false
Definition at line 548 of file astream.c.
References tb_astream_read_after_impl().
Referenced by tb_astream_oread_impl().
tb_bool_t tb_astream_seek_impl (tb_astream_t * astream, tb_hize_t offset, tb_astream_seek_func_t func, tb_pointer_t priv __tb_debug_decl__)
seek the stream
Parameters
astream the stream
offset the offset
func the func
priv the func data
Returns
tb_true or tb_false
Definition at line 558 of file astream.c.
References tb_astream_t::base, tb_stream_t::bopened, tb_stream_t::bstoped, tb_astream_t::file, tb_astream_oseek_t::func, tb_astream_t::func, tb_astream_t::line, tb_astream_oseek_t::offset, tb_astream_oseek_t::priv, tb_astream_t::sync_and, tb_astream_sync_impl(), tb_stream_offset(), tb_astream_t::wcache_data, and tb_astream_t::wcache_maxn.
Referenced by tb_astream_oseek_impl().
tb_bool_t tb_astream_sync_impl (tb_astream_t * astream, tb_bool_t bclosing, tb_astream_sync_func_t func, tb_pointer_t priv __tb_debug_decl__)
sync the stream
Parameters
astream the stream
bclosing sync the tail data for closing
func the func
priv the func data
Returns
tb_true or tb_false
Definition at line 594 of file astream.c.
References tb_astream_t::base, tb_astream_csync_t::bclosing, tb_stream_t::bopened, tb_stream_t::bstoped, tb_astream_t::file, tb_astream_csync_t::func, tb_astream_t::func, tb_astream_t::line, tb_astream_t::wcache_and, tb_astream_t::wcache_data, and tb_astream_t::wcache_maxn.
Referenced by tb_astream_read_after_impl(), and tb_astream_seek_impl().
tb_bool_t tb_astream_task_impl (tb_astream_t * astream, tb_size_t delay, tb_astream_task_func_t func, tb_pointer_t priv __tb_debug_decl__)
task the stream
Parameters
astream the stream
delay the delay time, ms
func the func
priv the func data
Returns
tb_true or tb_false
Definition at line 633 of file astream.c.
References tb_astream_t::base, tb_stream_t::bopened, tb_stream_t::bstoped, tb_astream_t::file, tb_astream_t::func, tb_astream_t::line, and tb_astream_t::task.
tb_bool_t tb_astream_writ_after_impl (tb_astream_t * astream, tb_size_t delay, tb_byte_t const * data, tb_size_t size, tb_astream_writ_func_t func, tb_pointer_t priv __tb_debug_decl__)
writ the stream after the delay time
Parameters
astream the stream
delay the delay time, ms
data the data
size the size
func the func
priv the func data
Returns
tb_true or tb_false
Definition at line 736 of file astream.c.
References tb_astream_t::base, tb_stream_t::bopened, tb_stream_t::bstoped, tb_astream_t::file, tb_astream_t::func, and tb_astream_t::line.
Referenced by tb_astream_writ_impl().
tb_bool_t tb_astream_writ_impl (tb_astream_t * astream, tb_byte_t const * data, tb_size_t size, tb_astream_writ_func_t func, tb_pointer_t priv __tb_debug_decl__)
writ the stream
Parameters
astream the stream
data the data
size the size
func the func
priv the func data
Returns
tb_true or tb_false
Definition at line 553 of file astream.c.
References tb_astream_writ_after_impl().
Referenced by tb_astream_owrit_impl().