TBOX: src/tbox/platform/thread_pool.h File Reference
thread_pool.h File Reference
Platform
#include "prefix.h"
Data Structures
struct tb_thread_pool_ref_t
the thread pool ref type
struct tb_thread_pool_task_ref_t
the thread pool task ref type
struct tb_thread_pool_worker_ref_t
the thread pool worker ref type
struct tb_thread_pool_task_t
the thread pool task type
Macros
#define TB_THREAD_POOL_WORKER_PRIV_MAXN (32)
the thread pool worker private data maximum count
Typedefs
typedef tb_void_t(* tb_thread_pool_priv_exit_func_t)(tb_thread_pool_worker_ref_t worker, tb_cpointer_t priv)
the thread pool priv exit func type
typedef tb_void_t(* tb_thread_pool_task_done_func_t)(tb_thread_pool_worker_ref_t worker, tb_cpointer_t priv)
the thread pool task done func type
typedef tb_void_t(* tb_thread_pool_task_exit_func_t)(tb_thread_pool_worker_ref_t worker, tb_cpointer_t priv)
the thread pool task exit func type
Functions
tb_thread_pool_ref_t tb_thread_pool (tb_noarg_t)
tb_thread_pool_ref_t tb_thread_pool_init (tb_size_t worker_maxn, tb_size_t stack)
tb_bool_t tb_thread_pool_exit (tb_thread_pool_ref_t pool)
tb_void_t tb_thread_pool_kill (tb_thread_pool_ref_t pool)
tb_size_t tb_thread_pool_worker_size (tb_thread_pool_ref_t pool)
tb_void_t tb_thread_pool_worker_setp (tb_thread_pool_worker_ref_t worker, tb_size_t index, tb_thread_pool_priv_exit_func_t exit, tb_cpointer_t priv)
tb_cpointer_t tb_thread_pool_worker_getp (tb_thread_pool_worker_ref_t worker, tb_size_t index)
tb_size_t tb_thread_pool_task_size (tb_thread_pool_ref_t pool)
tb_bool_t tb_thread_pool_task_post (tb_thread_pool_ref_t pool, tb_char_t const *name, tb_thread_pool_task_done_func_t done, tb_thread_pool_task_exit_func_t exit, tb_cpointer_t priv, tb_bool_t urgent)
tb_size_t tb_thread_pool_task_post_list (tb_thread_pool_ref_t pool, tb_thread_pool_task_t const *list, tb_size_t size)
tb_thread_pool_task_ref_t tb_thread_pool_task_init (tb_thread_pool_ref_t pool, tb_char_t const *name, tb_thread_pool_task_done_func_t done, tb_thread_pool_task_exit_func_t exit, tb_cpointer_t priv, tb_bool_t urgent)
tb_void_t tb_thread_pool_task_kill (tb_thread_pool_ref_t pool, tb_thread_pool_task_ref_t task)
tb_void_t tb_thread_pool_task_kill_all (tb_thread_pool_ref_t pool)
tb_long_t tb_thread_pool_task_wait (tb_thread_pool_ref_t pool, tb_thread_pool_task_ref_t task, tb_long_t timeout)
tb_long_t tb_thread_pool_task_wait_all (tb_thread_pool_ref_t pool, tb_long_t timeout)
tb_void_t tb_thread_pool_task_exit (tb_thread_pool_ref_t pool, tb_thread_pool_task_ref_t task)
Detailed Description
The Treasure Box Library
TBox is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 2.1 of the License, or (at your option) any later version.
TBox is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with TBox; If not, see http://www.gnu.org/licenses/
Copyright (C) 2009 - 2015, ruki All rights reserved.
Author
ruki
Definition in file thread_pool.h.
Function Documentation
tb_thread_pool_ref_t tb_thread_pool (tb_noarg_t)
the thread pool instance
Returns
the thread pool
tb_bool_t tb_thread_pool_exit (tb_thread_pool_ref_t pool)
exit thread pool
Parameters
pool the thread pool
Returns
tb_true or tb_false
Definition at line 815 of file thread_pool.c.
References tb_fixed_pool_exit(), tb_list_entry_exit(), tb_semaphore_exit(), tb_thread_exit(), tb_thread_pool_kill(), tb_thread_pool_task_wait_all(), and tb_thread_wait().
Referenced by tb_thread_pool_init().
tb_thread_pool_ref_t tb_thread_pool_init (tb_size_t worker_maxn, tb_size_t stack)
init thread pool
Parameters
worker_maxn the thread worker max count, using the default count
stack the thread stack, using the default stack size if be zero
Returns
the thread pool
Definition at line 752 of file thread_pool.c.
References tb_fixed_pool_init(), tb_list_entry_init, tb_lock_profiler(), tb_lock_profiler_register(), tb_processor_count(), tb_semaphore_init(), and tb_thread_pool_exit().
tb_void_t tb_thread_pool_kill (tb_thread_pool_ref_t pool)
kill thread pool, all workers and waiting tasks
Parameters
pool the thread pool
Definition at line 898 of file thread_pool.c.
References tb_fixed_pool_walk().
Referenced by tb_thread_pool_exit().
tb_void_t tb_thread_pool_task_exit (tb_thread_pool_ref_t pool, tb_thread_pool_task_ref_t task)
exit the task
Parameters
pool the thread pool
task the thread pool task
Definition at line 1214 of file thread_pool.c.
References tb_thread_pool_task_kill().
tb_thread_pool_task_ref_t tb_thread_pool_task_init (tb_thread_pool_ref_t pool, tb_char_t const * name, tb_thread_pool_task_done_func_t done, tb_thread_pool_task_exit_func_t exit, tb_cpointer_t priv, tb_bool_t urgent)
init one task
Parameters
pool the thread pool
name the task name, optional
done the task done func
exit the task exit func, optional
priv the task private data
urgent is urgent task?
Returns
the thread pool task
Definition at line 1068 of file thread_pool.c.
References tb_thread_pool_task_t::done, tb_thread_pool_task_t::exit, tb_thread_pool_task_t::name, tb_thread_pool_task_t::priv, and tb_thread_pool_task_t::urgent.
tb_void_t tb_thread_pool_task_kill (tb_thread_pool_ref_t pool, tb_thread_pool_task_ref_t task)
kill the waiting task
Parameters
pool the thread pool
task the task handle
Definition at line 1119 of file thread_pool.c.
References tb_state_cstr().
Referenced by tb_thread_pool_task_exit().
tb_void_t tb_thread_pool_task_kill_all (tb_thread_pool_ref_t pool)
kill all waiting tasks
Parameters
pool the thread pool
Definition at line 1131 of file thread_pool.c.
References tb_fixed_pool_walk().
tb_bool_t tb_thread_pool_task_post (tb_thread_pool_ref_t pool, tb_char_t const * name, tb_thread_pool_task_done_func_t done, tb_thread_pool_task_exit_func_t exit, tb_cpointer_t priv, tb_bool_t urgent)
post one task
Parameters
pool the thread pool
name the task name, optional
done the task done func
exit the task exit func, optional
priv the task private data
urgent is urgent task?
Returns
tb_true or tb_false
Definition at line 990 of file thread_pool.c.
References tb_thread_pool_task_t::done, tb_thread_pool_task_t::exit, tb_thread_pool_task_t::name, tb_thread_pool_task_t::priv, and tb_thread_pool_task_t::urgent.
tb_size_t tb_thread_pool_task_post_list (tb_thread_pool_ref_t pool, tb_thread_pool_task_t const * list, tb_size_t size)
post task list
Parameters
pool the thread pool
list the task list
size the task count
Returns
the real posted task count
Definition at line 1035 of file thread_pool.c.
tb_size_t tb_thread_pool_task_size (tb_thread_pool_ref_t pool)
the current waiting task count
Parameters
pool the thread pool
Returns
the current task count
Definition at line 972 of file thread_pool.c.
References tb_fixed_pool_size().
tb_long_t tb_thread_pool_task_wait (tb_thread_pool_ref_t pool, tb_thread_pool_task_ref_t task, tb_long_t timeout)
wait one task
Parameters
pool the thread pool
task the thread pool task
timeout the timeout
Returns
ok: 1, timeout: 0, error: -1
Definition at line 1147 of file thread_pool.c.
References tb_cache_time_spak(), and tb_state_cstr().
tb_long_t tb_thread_pool_task_wait_all (tb_thread_pool_ref_t pool, tb_long_t timeout)
wait all waiting tasks
Parameters
pool the thread pool
timeout the timeout
Returns
ok: 1, timeout: 0, error: -1
Definition at line 1170 of file thread_pool.c.
References tb_cache_time_spak(), tb_fixed_pool_size(), tb_for_all_if, tb_list_entry_itor(), and tb_state_cstr().
Referenced by tb_thread_pool_exit().
tb_cpointer_t tb_thread_pool_worker_getp (tb_thread_pool_worker_ref_t worker, tb_size_t index)
get the worker private data
Parameters
worker the thread pool worker
index the private data index
Returns
the private data
Definition at line 963 of file thread_pool.c.
tb_void_t tb_thread_pool_worker_setp (tb_thread_pool_worker_ref_t worker, tb_size_t index, tb_thread_pool_priv_exit_func_t exit, tb_cpointer_t priv)
set the worker private data
Parameters
worker the thread pool worker
index the private data index
exit the private data exit func
priv the private data
Definition at line 953 of file thread_pool.c.
tb_size_t tb_thread_pool_worker_size (tb_thread_pool_ref_t pool)
the current worker count
Parameters
pool the thread pool
Returns
the current worker count
Definition at line 935 of file thread_pool.c.