TBOX: src/string/pstring.h File Reference
pstring.h File Reference
String
#include "prefix.h"
#include "../memory/memory.h"
Typedefs
typedef tb_pbuffer_t tb_pstring_t
the scoped string type
Functions
tb_bool_t tb_pstring_init (tb_pstring_t *string)
tb_void_t tb_pstring_exit (tb_pstring_t *string)
tb_char_t const * tb_pstring_cstr (tb_pstring_t const *string)
tb_size_t tb_pstring_size (tb_pstring_t const *string)
tb_void_t tb_pstring_clear (tb_pstring_t *string)
tb_char_t const * tb_pstring_strip (tb_pstring_t *string, tb_size_t n)
tb_long_t tb_pstring_strchr (tb_pstring_t const *string, tb_size_t p, tb_char_t c)
tb_long_t tb_pstring_strichr (tb_pstring_t const *string, tb_size_t p, tb_char_t c)
tb_long_t tb_pstring_strrchr (tb_pstring_t const *string, tb_size_t p, tb_char_t c)
tb_long_t tb_pstring_strirchr (tb_pstring_t const *string, tb_size_t p, tb_char_t c)
tb_long_t tb_pstring_strstr (tb_pstring_t const *string, tb_size_t p, tb_pstring_t const *s)
tb_long_t tb_pstring_stristr (tb_pstring_t const *string, tb_size_t p, tb_pstring_t const *s)
tb_long_t tb_pstring_cstrstr (tb_pstring_t const *string, tb_size_t p, tb_char_t const *s)
tb_long_t tb_pstring_cstristr (tb_pstring_t const *string, tb_size_t p, tb_char_t const *s)
tb_long_t tb_pstring_strrstr (tb_pstring_t const *string, tb_size_t p, tb_pstring_t const *s)
tb_long_t tb_pstring_strirstr (tb_pstring_t const *string, tb_size_t p, tb_pstring_t const *s)
tb_long_t tb_pstring_cstrrstr (tb_pstring_t const *string, tb_size_t p, tb_char_t const *s)
tb_long_t tb_pstring_cstrirstr (tb_pstring_t const *string, tb_size_t p, tb_char_t const *s)
tb_char_t const * tb_pstring_strcpy (tb_pstring_t *string, tb_pstring_t const *s)
tb_char_t const * tb_pstring_cstrcpy (tb_pstring_t *string, tb_char_t const *s)
tb_char_t const * tb_pstring_cstrncpy (tb_pstring_t *string, tb_char_t const *s, tb_size_t n)
tb_char_t const * tb_pstring_cstrfcpy (tb_pstring_t *string, tb_char_t const *fmt,...)
tb_char_t const * tb_pstring_chrcat (tb_pstring_t *string, tb_char_t c)
tb_char_t const * tb_pstring_chrncat (tb_pstring_t *string, tb_char_t c, tb_size_t n)
tb_char_t const * tb_pstring_strcat (tb_pstring_t *string, tb_pstring_t const *s)
tb_char_t const * tb_pstring_cstrcat (tb_pstring_t *string, tb_char_t const *s)
tb_char_t const * tb_pstring_cstrncat (tb_pstring_t *string, tb_char_t const *s, tb_size_t n)
tb_char_t const * tb_pstring_cstrfcat (tb_pstring_t *string, tb_char_t const *fmt,...)
tb_long_t tb_pstring_strcmp (tb_pstring_t *string, tb_pstring_t const *s)
tb_long_t tb_pstring_strimp (tb_pstring_t *string, tb_pstring_t const *s)
tb_long_t tb_pstring_cstrcmp (tb_pstring_t *string, tb_char_t const *s)
tb_long_t tb_pstring_cstricmp (tb_pstring_t *string, tb_char_t const *s)
tb_long_t tb_pstring_cstrncmp (tb_pstring_t *string, tb_char_t const *s, tb_size_t n)
tb_long_t tb_pstring_cstrnicmp (tb_pstring_t *string, tb_char_t const *s, tb_size_t n)
Detailed Description
The Treasure Box Library
TBox is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 2.1 of the License, or (at your option) any later version.
TBox is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with TBox; If not, see http://www.gnu.org/licenses/
Copyright (C) 2009 - 2015, ruki All rights reserved.
Author
ruki
Definition in file pstring.h.
Function Documentation
tb_char_t const* tb_pstring_chrcat (tb_pstring_t * string, tb_char_t c)
append charactor
Parameters
string the string
c the appended charactor
Returns
the c-string
Definition at line 249 of file pstring.c.
References tb_pstring_size().
tb_char_t const* tb_pstring_chrncat (tb_pstring_t * string, tb_char_t c, tb_size_t n)
append charactor with the given size
Parameters
string the string
c the appended charactor
n the appended size
Returns
the c-string
Definition at line 258 of file pstring.c.
References tb_pstring_size().
tb_void_t tb_pstring_clear (tb_pstring_t * string)
clear the string
Parameters
string the string
Definition at line 74 of file pstring.c.
Referenced by tb_pstring_strcpy(), and tb_string_cstr_set().
tb_char_t const* tb_pstring_cstr (tb_pstring_t const * string)
the c-string pointer
Parameters
string the string
Returns
the c-string
Definition at line 58 of file pstring.c.
Referenced by tb_option_help(), tb_pstring_cstrirstr(), tb_pstring_cstristr(), tb_pstring_cstrncmp(), tb_pstring_cstrnicmp(), tb_pstring_cstrrstr(), tb_pstring_cstrstr(), tb_pstring_strcat(), tb_pstring_strchr(), tb_pstring_strcmp(), tb_pstring_strcpy(), tb_pstring_strichr(), tb_pstring_strimp(), tb_pstring_strip(), tb_pstring_strirchr(), tb_pstring_strirstr(), tb_pstring_stristr(), tb_pstring_strrchr(), tb_pstring_strrstr(), tb_pstring_strstr(), tb_string_cstr(), tb_string_init_from_pstr(), and tb_xml_node_goto().
tb_char_t const* tb_pstring_cstrcat (tb_pstring_t * string, tb_char_t const * s)
append c-string
Parameters
string the string
s the appended c-string
Returns
the c-string
Definition at line 276 of file pstring.c.
References tb_pstring_cstrncat().
tb_long_t tb_pstring_cstrcmp (tb_pstring_t * string, tb_char_t const * s)
compare c-string
Parameters
string the string
s the compared c-string
Returns
equal: 0
Definition at line 319 of file pstring.c.
References tb_pstring_cstrncmp().
tb_char_t const* tb_pstring_cstrcpy (tb_pstring_t * string, tb_char_t const * s)
copy c-string
Parameters
string the string
s the copied c-string
Returns
the c-string
Definition at line 218 of file pstring.c.
References tb_pstring_cstrncpy().
Referenced by tb_option_init(), tb_xml_node_init_attribute(), tb_xml_node_init_cdata(), tb_xml_node_init_comment(), tb_xml_node_init_document(), tb_xml_node_init_document_type(), tb_xml_node_init_element(), and tb_xml_node_init_text().
tb_char_t const* tb_pstring_cstrfcat (tb_pstring_t * string, tb_char_t const * fmt, ...)
append format c-string
Parameters
string the string
fmt the appended format c-string
Returns
the c-string
Definition at line 290 of file pstring.c.
References tb_pstring_cstrncat().
tb_char_t const* tb_pstring_cstrfcpy (tb_pstring_t * string, tb_char_t const * fmt, ...)
copy format c-string
Parameters
string the string
fmt the copied format c-string
Returns
the c-string
Definition at line 233 of file pstring.c.
References tb_pstring_cstrncpy().
tb_long_t tb_pstring_cstricmp (tb_pstring_t * string, tb_char_t const * s)
compare c-string and ignore case
Parameters
string the string
s the compared c-string
Returns
equal: 0
Definition at line 325 of file pstring.c.
References tb_pstring_cstrnicmp().
tb_long_t tb_pstring_cstrirstr (tb_pstring_t const * string, tb_size_t p, tb_char_t const * s)
reverse to find c-string position and ignore case
Parameters
string the string
p the start position
s the finded c-string
Returns
the real position, no find: -1
Definition at line 192 of file pstring.c.
References tb_pstring_cstr(), and tb_pstring_size().
Referenced by tb_pstring_strirstr().
tb_long_t tb_pstring_cstristr (tb_pstring_t const * string, tb_size_t p, tb_char_t const * s)
find c-string position and ignore case
Parameters
string the string
p the start position
s the finded c-string
Returns
the real position, no find: -1
Definition at line 161 of file pstring.c.
References tb_pstring_cstr(), and tb_pstring_size().
Referenced by tb_pstring_stristr().
tb_char_t const* tb_pstring_cstrncat (tb_pstring_t * string, tb_char_t const * s, tb_size_t n)
append c-string with the given size
Parameters
string the string
s the appended c-string
n the appended c-string size
Returns
the c-string
Definition at line 282 of file pstring.c.
References tb_pstring_size().
Referenced by tb_pstring_cstrcat(), tb_pstring_cstrfcat(), and tb_pstring_strcat().
tb_long_t tb_pstring_cstrncmp (tb_pstring_t * string, tb_char_t const * s, tb_size_t n)
compare c-string with given size
Parameters
string the string
s the compared c-string #param n the compared c-string size
Returns
equal: 0
Definition at line 331 of file pstring.c.
References tb_pstring_cstr().
Referenced by tb_pstring_cstrcmp(), tb_pstring_strcmp(), and tb_xml_node_goto().
tb_char_t const* tb_pstring_cstrncpy (tb_pstring_t * string, tb_char_t const * s, tb_size_t n)
copy c-string with the given size
Parameters
string the string
s the copied c-string
n the copied c-string size
Returns
the c-string
Definition at line 224 of file pstring.c.
References tb_pstring_size().
Referenced by tb_pstring_cstrcpy(), tb_pstring_cstrfcpy(), tb_pstring_strcpy(), tb_string_cstr_set(), and tb_string_init_from_cstr().
tb_long_t tb_pstring_cstrnicmp (tb_pstring_t * string, tb_char_t const * s, tb_size_t n)
compare c-string with given size and ignore case
Parameters
string the string
s the compared c-string #param n the compared c-string size
Returns
equal: 0
Definition at line 337 of file pstring.c.
References tb_pstring_cstr().
Referenced by tb_pstring_cstricmp(), and tb_pstring_strimp().
tb_long_t tb_pstring_cstrrstr (tb_pstring_t const * string, tb_size_t p, tb_char_t const * s)
reverse to find c-string position
Parameters
string the string
p the start position
s the finded c-string
Returns
the real position, no find: -1
Definition at line 183 of file pstring.c.
References tb_pstring_cstr(), and tb_pstring_size().
Referenced by tb_pstring_strrstr().
tb_long_t tb_pstring_cstrstr (tb_pstring_t const * string, tb_size_t p, tb_char_t const * s)
find c-string position
Parameters
string the string
p the start position
s the finded c-string
Returns
the real position, no find: -1
Definition at line 152 of file pstring.c.
References tb_pstring_cstr(), and tb_pstring_size().
Referenced by tb_pstring_strstr().
tb_void_t tb_pstring_exit (tb_pstring_t * string)
exit string
Parameters
string the string
Definition at line 50 of file pstring.c.
Referenced by tb_option_exit(), and tb_xml_node_exit().
tb_bool_t tb_pstring_init (tb_pstring_t * string)
init string
Parameters
string the string
Returns
tb_true or tb_false
Definition at line 45 of file pstring.c.
Referenced by tb_filter_init_from_chunked(), tb_option_init(), tb_string_init_from_cstr(), tb_string_init_from_pstr(), tb_xml_node_init_attribute(), tb_xml_node_init_cdata(), tb_xml_node_init_comment(), tb_xml_node_init_document(), tb_xml_node_init_document_type(), tb_xml_node_init_element(), and tb_xml_node_init_text().
tb_size_t tb_pstring_size (tb_pstring_t const * string)
the string size
Parameters
string the string
Returns
the string size
Definition at line 63 of file pstring.c.
Referenced by tb_option_help(), tb_pstring_chrcat(), tb_pstring_chrncat(), tb_pstring_cstrirstr(), tb_pstring_cstristr(), tb_pstring_cstrncat(), tb_pstring_cstrncpy(), tb_pstring_cstrrstr(), tb_pstring_cstrstr(), tb_pstring_strcat(), tb_pstring_strchr(), tb_pstring_strcmp(), tb_pstring_strcpy(), tb_pstring_strichr(), tb_pstring_strimp(), tb_pstring_strip(), tb_pstring_strirchr(), tb_pstring_strrchr(), tb_string_cstr_set(), tb_string_init_from_pstr(), tb_string_size(), and tb_xml_node_goto().
tb_char_t const* tb_pstring_strcat (tb_pstring_t * string, tb_pstring_t const * s)
append string
Parameters
string the string
s the appended string
Returns
the c-string
Definition at line 270 of file pstring.c.
References tb_pstring_cstr(), tb_pstring_cstrncat(), and tb_pstring_size().
tb_long_t tb_pstring_strchr (tb_pstring_t const * string, tb_size_t p, tb_char_t c)
find charactor position
Parameters
string the string
p the start position
c the finded charactor
Returns
the real position, no find: -1
Definition at line 100 of file pstring.c.
References tb_pstring_cstr(), and tb_pstring_size().
tb_long_t tb_pstring_strcmp (tb_pstring_t * string, tb_pstring_t const * s)
compare string
Parameters
string the string
s the compared string
Returns
equal: 0
Definition at line 307 of file pstring.c.
References tb_pstring_cstr(), tb_pstring_cstrncmp(), and tb_pstring_size().
tb_char_t const* tb_pstring_strcpy (tb_pstring_t * string, tb_pstring_t const * s)
copy string
Parameters
string the string
s the copied string
Returns
the c-string
Definition at line 205 of file pstring.c.
References tb_pstring_clear(), tb_pstring_cstr(), tb_pstring_cstrncpy(), and tb_pstring_size().
Referenced by tb_string_init_from_pstr().
tb_long_t tb_pstring_strichr (tb_pstring_t const * string, tb_size_t p, tb_char_t c)
find charactor position and ignore case
Parameters
string the string
p the start position
c the finded charactor
Returns
the real position, no find: -1
Definition at line 109 of file pstring.c.
References tb_pstring_cstr(), and tb_pstring_size().
tb_long_t tb_pstring_strimp (tb_pstring_t * string, tb_pstring_t const * s)
compare string and ignore case
Parameters
string the string
s the compared string
Returns
equal: 0
Definition at line 313 of file pstring.c.
References tb_pstring_cstr(), tb_pstring_cstrnicmp(), and tb_pstring_size().
tb_char_t const* tb_pstring_strip (tb_pstring_t * string, tb_size_t n)
strip the string
Parameters
string the string
n the striped size
Returns
the c-string
Definition at line 85 of file pstring.c.
References tb_pstring_cstr(), and tb_pstring_size().
tb_long_t tb_pstring_strirchr (tb_pstring_t const * string, tb_size_t p, tb_char_t c)
reverse to find charactor position and ignore case
Parameters
string the string
p the start position
c the finded charactor
Returns
the real position, no find: -1
Definition at line 131 of file pstring.c.
References tb_pstring_cstr(), and tb_pstring_size().
tb_long_t tb_pstring_strirstr (tb_pstring_t const * string, tb_size_t p, tb_pstring_t const * s)
reverse to find string position and ignore case
Parameters
string the string
p the start position
s the finded string
Returns
the real position, no find: -1
Definition at line 178 of file pstring.c.
References tb_pstring_cstr(), and tb_pstring_cstrirstr().
tb_long_t tb_pstring_stristr (tb_pstring_t const * string, tb_size_t p, tb_pstring_t const * s)
find string position and ignore case
Parameters
string the string
p the start position
s the finded string
Returns
the real position, no find: -1
Definition at line 148 of file pstring.c.
References tb_pstring_cstr(), and tb_pstring_cstristr().
tb_long_t tb_pstring_strrchr (tb_pstring_t const * string, tb_size_t p, tb_char_t c)
reverse to find charactor position
Parameters
string the string
p the start position
c the finded charactor
Returns
the real position, no find: -1
Definition at line 122 of file pstring.c.
References tb_pstring_cstr(), and tb_pstring_size().
tb_long_t tb_pstring_strrstr (tb_pstring_t const * string, tb_size_t p, tb_pstring_t const * s)
reverse to find string position
Parameters
string the string
p the start position
s the finded string
Returns
the real position, no find: -1
Definition at line 174 of file pstring.c.
References tb_pstring_cstr(), and tb_pstring_cstrrstr().
tb_long_t tb_pstring_strstr (tb_pstring_t const * string, tb_size_t p, tb_pstring_t const * s)
find string position
Parameters
string the string
p the start position
s the finded string
Returns
the real position, no find: -1
Definition at line 144 of file pstring.c.
References tb_pstring_cstr(), and tb_pstring_cstrstr().