TBOX: src/tbox/container/item.h File Reference
item.h File Reference
Container
#include "prefix.h"
Data Structures
struct tb_item_func_t
the item func type
Typedefs
typedef tb_size_t(* tb_item_func_hash_t)(struct __tb_item_func_t *func, tb_cpointer_t data, tb_size_t mask, tb_size_t index)
typedef tb_long_t(* tb_item_func_comp_t)(struct __tb_item_func_t *func, tb_cpointer_t ldata, tb_cpointer_t rdata)
typedef tb_pointer_t(* tb_item_func_data_t)(struct __tb_item_func_t *func, tb_cpointer_t buff)
typedef tb_char_t const *(* tb_item_func_cstr_t)(struct __tb_item_func_t *func, tb_cpointer_t data, tb_char_t *cstr, tb_size_t maxn)
typedef tb_bool_t(* tb_item_func_load_t)(struct __tb_item_func_t *func, tb_pointer_t buff, tb_stream_ref_t stream)
typedef tb_bool_t(* tb_item_func_save_t)(struct __tb_item_func_t *func, tb_cpointer_t data, tb_stream_ref_t stream)
typedef tb_void_t(* tb_item_func_free_t)(struct __tb_item_func_t *func, tb_pointer_t buff)
typedef tb_void_t(* tb_item_func_dupl_t)(struct __tb_item_func_t *func, tb_pointer_t buff, tb_cpointer_t data)
typedef tb_void_t(* tb_item_func_repl_t)(struct __tb_item_func_t *func, tb_pointer_t buff, tb_cpointer_t data)
typedef tb_void_t(* tb_item_func_copy_t)(struct __tb_item_func_t *func, tb_pointer_t buff, tb_cpointer_t data)
typedef tb_void_t(* tb_item_func_nfree_t)(struct __tb_item_func_t *func, tb_pointer_t buff, tb_size_t size)
typedef tb_void_t(* tb_item_func_ndupl_t)(struct __tb_item_func_t *func, tb_pointer_t buff, tb_cpointer_t data, tb_size_t size)
typedef tb_void_t(* tb_item_func_nrepl_t)(struct __tb_item_func_t *func, tb_pointer_t buff, tb_cpointer_t data, tb_size_t size)
typedef tb_void_t(* tb_item_func_ncopy_t)(struct __tb_item_func_t *func, tb_pointer_t buff, tb_cpointer_t data, tb_size_t size)
Enumerations
enum tb_item_type_t {
TB_ITEM_TYPE_NULL = 0, TB_ITEM_TYPE_LONG = 1, TB_ITEM_TYPE_SIZE = 2, TB_ITEM_TYPE_UINT8 = 3,
TB_ITEM_TYPE_UINT16 = 4, TB_ITEM_TYPE_UINT32 = 5, TB_ITEM_TYPE_STR = 6, TB_ITEM_TYPE_PTR = 7,
TB_ITEM_TYPE_MEM = 8, TB_ITEM_TYPE_OBJ = 9, TB_ITEM_TYPE_TRUE = 10, TB_ITEM_TYPE_USER = 11
}
the item type
Functions
tb_item_func_t tb_item_func_true (tb_noarg_t)
tb_item_func_t tb_item_func_long (tb_noarg_t)
tb_item_func_t tb_item_func_size (tb_noarg_t)
tb_item_func_t tb_item_func_uint8 (tb_noarg_t)
tb_item_func_t tb_item_func_uint16 (tb_noarg_t)
tb_item_func_t tb_item_func_uint32 (tb_noarg_t)
tb_item_func_t tb_item_func_str (tb_bool_t bcase)
tb_item_func_t tb_item_func_ptr (tb_item_func_free_t free, tb_cpointer_t priv)
tb_item_func_t tb_item_func_obj (tb_noarg_t)
tb_item_func_t tb_item_func_mem (tb_size_t size, tb_item_func_free_t free, tb_cpointer_t priv)
Detailed Description
The Treasure Box Library
TBox is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 2.1 of the License, or (at your option) any later version.
TBox is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with TBox; If not, see http://www.gnu.org/licenses/
Copyright (C) 2009 - 2015, ruki All rights reserved.
Author
ruki
Definition in file item.h.
Typedef Documentation
typedef tb_long_t(* tb_item_func_comp_t)(struct __tb_item_func_t *func, tb_cpointer_t ldata, tb_cpointer_t rdata)
the item data compare func type
Parameters
func the item func
ldata the left-hand data
rdata the right-hand data
Returns
equal: 0, 1: >, -1: <
Definition at line 62 of file item.h.
typedef tb_void_t(* tb_item_func_copy_t)(struct __tb_item_func_t *func, tb_pointer_t buff, tb_cpointer_t data)
the item copy func type
only copy the item data and not allocate new item
Parameters
func the item func
buff the item data address
data the item data
Definition at line 143 of file item.h.
typedef tb_char_t const*(* tb_item_func_cstr_t)(struct __tb_item_func_t *func, tb_cpointer_t data, tb_char_t *cstr, tb_size_t maxn)
the item data string func type
Parameters
func the item func
data the item data
cstr the string buffer
maxn the string buffer maximum size
Returns
the string pointer
Definition at line 82 of file item.h.
typedef tb_pointer_t(* tb_item_func_data_t)(struct __tb_item_func_t *func, tb_cpointer_t buff)
the item data func type
Parameters
func the item func
buff the item data address
Returns
the item data
Definition at line 71 of file item.h.
typedef tb_void_t(* tb_item_func_dupl_t)(struct __tb_item_func_t *func, tb_pointer_t buff, tb_cpointer_t data)
the item duplicate func type
allocate a new item and copy the item data
Parameters
func the item func
buff the item buffer
data the item data
Definition at line 123 of file item.h.
typedef tb_void_t(* tb_item_func_free_t)(struct __tb_item_func_t *func, tb_pointer_t buff)
the item free func type
Parameters
func the item func
buff the item buffer
Definition at line 113 of file item.h.
typedef tb_size_t(* tb_item_func_hash_t)(struct __tb_item_func_t *func, tb_cpointer_t data, tb_size_t mask, tb_size_t index)
the item data hash func type
Parameters
func the item func
data the item data
mask the hash mask
index the hash index
Returns
the hash value
Definition at line 52 of file item.h.
typedef tb_bool_t(* tb_item_func_load_t)(struct __tb_item_func_t *func, tb_pointer_t buff, tb_stream_ref_t stream)
the item data load func type
load data to the item from the stream
Parameters
func the item func
buff the item buffer
stream the stream
Returns
tb_true or tb_false
Definition at line 94 of file item.h.
typedef tb_void_t(* tb_item_func_ncopy_t)(struct __tb_item_func_t *func, tb_pointer_t buff, tb_cpointer_t data, tb_size_t size)
the items copy func type
copy some items
Parameters
func the item func
buff the item buffer
data the item data
size the item count
Definition at line 186 of file item.h.
typedef tb_void_t(* tb_item_func_ndupl_t)(struct __tb_item_func_t *func, tb_pointer_t buff, tb_cpointer_t data, tb_size_t size)
the items duplicate func type
duplicate some items
Parameters
func the item func
buff the item buffer
data the item data
size the item count
Definition at line 164 of file item.h.
typedef tb_void_t(* tb_item_func_nfree_t)(struct __tb_item_func_t *func, tb_pointer_t buff, tb_size_t size)
the items free func type
free some items
Parameters
func the item func
buff the item buffer
size the item count
Definition at line 153 of file item.h.
typedef tb_void_t(* tb_item_func_nrepl_t)(struct __tb_item_func_t *func, tb_pointer_t buff, tb_cpointer_t data, tb_size_t size)
the items replace func type
replace some items
Parameters
func the item func
buff the item buffer
data the item data
size the item count
Definition at line 175 of file item.h.
typedef tb_void_t(* tb_item_func_repl_t)(struct __tb_item_func_t *func, tb_pointer_t buff, tb_cpointer_t data)
the item replace func type
free the previous item data and duplicate the new data
Parameters
func the item func
buff the item buffer
data the item data
Definition at line 133 of file item.h.
typedef tb_bool_t(* tb_item_func_save_t)(struct __tb_item_func_t *func, tb_cpointer_t data, tb_stream_ref_t stream)
the item data save func type
save data to the stream
Parameters
func the item func
data the item data
stream the stream
Returns
tb_true or tb_false
Definition at line 106 of file item.h.
Enumeration Type Documentation
enum tb_item_type_t
the item type
Enumerator
TB_ITEM_TYPE_NULL
null
TB_ITEM_TYPE_LONG
integer for tb_long_t
TB_ITEM_TYPE_SIZE
integer for tb_size_t
TB_ITEM_TYPE_UINT8
integer for tb_uint8_t
TB_ITEM_TYPE_UINT16
integer for tb_uint16_t
TB_ITEM_TYPE_UINT32
integer for tb_uint32_t
TB_ITEM_TYPE_STR
string
TB_ITEM_TYPE_PTR
pointer
TB_ITEM_TYPE_MEM
memory
TB_ITEM_TYPE_OBJ
object
TB_ITEM_TYPE_TRUE
true
TB_ITEM_TYPE_USER
the user defined type
Definition at line 189 of file item.h.
Function Documentation
tb_item_func_t tb_item_func_long (tb_noarg_t)
the integer item function for tb_long_t
Returns
the item func
tb_item_func_t tb_item_func_mem (tb_size_t size, tb_item_func_free_t free, tb_cpointer_t priv)
the internal fixed memory item function
storing it in the internal item of the container directly for saving memory
Parameters
size the item size
free the item free func
priv the private data of the item free func
Returns
the item func
Definition at line 164 of file mem.c.
References tb_item_func_t::comp, tb_item_func_t::copy, tb_item_func_t::cstr, tb_item_func_t::data, tb_item_func_t::dupl, tb_item_func_t::flag, tb_item_func_t::free, tb_item_func_t::hash, tb_item_func_t::load, tb_item_func_t::ncopy, tb_item_func_t::ndupl, tb_item_func_t::nfree, tb_item_func_t::nrepl, tb_item_func_t::priv, tb_item_func_t::repl, tb_item_func_t::save, tb_item_func_t::size, TB_ITEM_TYPE_MEM, and tb_item_func_t::type.
tb_item_func_t tb_item_func_obj (tb_noarg_t)
the object item function
Returns
the item func
Referenced by tb_object_array_init(), and tb_object_dictionary_init().
tb_item_func_t tb_item_func_ptr (tb_item_func_free_t free, tb_cpointer_t priv)
the pointer item function
Note
if the free func have been hooked, the nfree need hook too.
Parameters
free the item free func
priv the private data of the item free func
Returns
the item func
Definition at line 139 of file ptr.c.
References tb_item_func_t::comp, tb_item_func_t::copy, tb_item_func_t::cstr, tb_item_func_t::data, tb_item_func_t::dupl, tb_item_func_t::flag, tb_item_func_t::free, tb_item_func_t::hash, tb_item_func_t::ncopy, tb_item_func_t::ndupl, tb_item_func_t::nfree, tb_item_func_t::nrepl, tb_item_func_t::priv, tb_item_func_t::repl, tb_item_func_t::size, tb_item_func_size(), TB_ITEM_TYPE_PTR, and tb_item_func_t::type.
Referenced by tb_ltimer_init(), and tb_timer_init().
tb_item_func_t tb_item_func_size (tb_noarg_t)
the integer item function for tb_size_t
Returns
the item func
Referenced by tb_item_func_ptr(), and tb_string_pool_init().
tb_item_func_t tb_item_func_str (tb_bool_t bcase)
the string item function
Parameters
bcase is case?
Returns
the item func
Definition at line 227 of file str.c.
References tb_item_func_t::comp, tb_item_func_t::copy, tb_item_func_t::cstr, tb_item_func_t::data, tb_item_func_t::dupl, tb_item_func_t::flag, tb_item_func_t::free, tb_item_func_t::hash, tb_item_func_t::load, tb_item_func_t::ncopy, tb_item_func_t::ndupl, tb_item_func_t::nfree, tb_item_func_t::nrepl, tb_item_func_t::repl, tb_item_func_t::save, tb_item_func_t::size, TB_ITEM_TYPE_STR, and tb_item_func_t::type.
Referenced by tb_object_dictionary_init(), and tb_string_pool_init().
tb_item_func_t tb_item_func_true (tb_noarg_t)
the true item function for hash data: null
Returns
the item func
tb_item_func_t tb_item_func_uint16 (tb_noarg_t)
the integer item function for tb_uint16_t
Returns
the item func
tb_item_func_t tb_item_func_uint32 (tb_noarg_t)
the integer item function for tb_uint32_t
Returns
the item func
tb_item_func_t tb_item_func_uint8 (tb_noarg_t)
the integer item function for tb_uint8_t
Returns
the item func