TBOX: src/tbox/network/cookies.c File Reference
cookies.c File Reference
Network
#include "cookies.h"
#include "impl/http/date.h"
#include "url.h"
#include "../libc/libc.h"
#include "../math/math.h"
#include "../utils/utils.h"
#include "../string/string.h"
#include "../platform/platform.h"
#include "../algorithm/algorithm.h"
#include "../container/container.h"
Macros
#define TB_TRACE_MODULE_NAME "cookies"
#define TB_TRACE_MODULE_DEBUG (1)
Functions
tb_cookies_ref_t tb_cookies ()
tb_cookies_ref_t tb_cookies_init ()
tb_void_t tb_cookies_exit (tb_cookies_ref_t cookies)
tb_void_t tb_cookies_clear (tb_cookies_ref_t cookies)
tb_bool_t tb_cookies_set (tb_cookies_ref_t cookies, tb_char_t const *domain, tb_char_t const *path, tb_bool_t secure, tb_char_t const *value)
tb_bool_t tb_cookies_set_from_url (tb_cookies_ref_t cookies, tb_char_t const *url, tb_char_t const *value)
tb_char_t const * tb_cookies_get (tb_cookies_ref_t cookies, tb_char_t const *domain, tb_char_t const *path, tb_bool_t secure, tb_string_t *value)
tb_char_t const * tb_cookies_get_from_url (tb_cookies_ref_t cookies, tb_char_t const *url, tb_string_t *value)
Detailed Description
The Treasure Box Library
TBox is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 2.1 of the License, or (at your option) any later version.
TBox is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with TBox; If not, see http://www.gnu.org/licenses/
Copyright (C) 2009 - 2015, ruki All rights reserved.
Author
ruki
Definition in file cookies.c.
Function Documentation
tb_void_t tb_cookies_clear (tb_cookies_ref_t cookies)
clear cookies
Parameters
cookies the cookies
Definition at line 582 of file cookies.c.
References tb_string_pool_clear().
tb_void_t tb_cookies_exit (tb_cookies_ref_t cookies)
exit cookies
Parameters
cookies the cookies
Definition at line 556 of file cookies.c.
References tb_string_pool_exit().
tb_char_t const* tb_cookies_get (tb_cookies_ref_t cookies, tb_char_t const * domain, tb_char_t const * path, tb_bool_t secure, tb_string_t * value)
get cookies from the given domain and path
Parameters
cookies the cookies
domain the domain, .e.g .xxx.com or xxx.com and compatible www.xxx.com
path the path, .e.g /root/path
secure is secure?
value the cookies value
Returns
the cookies data
Definition at line 679 of file cookies.c.
References tb_value_t::cstr, tb_value_t::ptr, tb_cache_time_spak(), tb_remove_if(), and tb_value_t::ul.
Referenced by tb_cookies_get_from_url().
tb_char_t const* tb_cookies_get_from_url (tb_cookies_ref_t cookies, tb_char_t const * url, tb_string_t * value)
get cookies from the given url
Parameters
cookies the cookies
url the url
value the cookies value
Returns
the cookies data
Definition at line 729 of file cookies.c.
References tb_cookies_get(), and TB_PATH_MAXN.
tb_bool_t tb_cookies_set (tb_cookies_ref_t cookies, tb_char_t const * domain, tb_char_t const * path, tb_bool_t secure, tb_char_t const * value)
set cookies from the given domain and path
Parameters
cookies the cookies
domain the domain, .e.g .xxx.com or xxx.com and compatible www.xxx.com
path the path, .e.g /root/path
secure is secure?
value the value
Returns
tb_true or tb_false
Definition at line 600 of file cookies.c.
Referenced by tb_cookies_set_from_url().
tb_bool_t tb_cookies_set_from_url (tb_cookies_ref_t cookies, tb_char_t const * url, tb_char_t const * value)
set cookies from the given url
Parameters
cookies the cookies
url the url
value the value
Returns
tb_true or tb_false
Definition at line 657 of file cookies.c.
References tb_cookies_set(), and TB_PATH_MAXN.