TBOX: src/tbox/platform/platform.h File Reference
platform.h File Reference
#include "prefix.h"
#include "dns.h"
#include "page.h"
#include "path.h"
#include "file.h"
#include "time.h"
#include "mutex.h"
#include "event.h"
#include "timer.h"
#include "print.h"
#include "ltimer.h"
#include "socket.h"
#include "thread.h"
#include "atomic.h"
#include "memory.h"
#include "barrier.h"
#include "dynamic.h"
#include "process.h"
#include "spinlock.h"
#include "atomic64.h"
#include "hostname.h"
#include "processor.h"
#include "semaphore.h"
#include "backtrace.h"
#include "directory.h"
#include "exception.h"
#include "cache_time.h"
#include "thread_pool.h"
#include "thread_store.h"
Functions
__tb_extern_c_enter__ tb_bool_t tb_platform_init (tb_handle_t priv)
tb_void_t tb_platform_exit (tb_noarg_t)
exit the platform
Detailed Description
The Treasure Box Library
TBox is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 2.1 of the License, or (at your option) any later version.
TBox is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with TBox; If not, see http://www.gnu.org/licenses/
Copyright (C) 2009 - 2015, ruki All rights reserved.
Author
ruki
Definition in file platform.h.
Function Documentation
__tb_extern_c_enter__ tb_bool_t tb_platform_init (tb_handle_t priv)
init the platform
Parameters
priv the platform private data pass JNIEnv* env for android pass tb_null for other platform
Returns
tb_true or tb_false
Definition at line 50 of file platform.c.
References tb_android_init(), tb_cache_time_spak(), and tb_thread_store_init().
Referenced by tb_init_().