TBOX: src/tbox/platform/semaphore.h File Reference
semaphore.h File Reference
Platform
#include "prefix.h"
Functions
__tb_extern_c_enter__
tb_semaphore_ref_t tb_semaphore_init (tb_size_t init)
tb_void_t tb_semaphore_exit (tb_semaphore_ref_t semaphore)
tb_bool_t tb_semaphore_post (tb_semaphore_ref_t semaphore, tb_size_t post)
tb_long_t tb_semaphore_value (tb_semaphore_ref_t semaphore)
tb_long_t tb_semaphore_wait (tb_semaphore_ref_t semaphore, tb_long_t timeout)
Detailed Description
The Treasure Box Library
TBox is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 2.1 of the License, or (at your option) any later version.
TBox is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with TBox; If not, see http://www.gnu.org/licenses/
Copyright (C) 2009 - 2015, ruki All rights reserved.
Author
ruki
Definition in file semaphore.h.
Function Documentation
tb_void_t tb_semaphore_exit (tb_semaphore_ref_t semaphore)
exit semaphore
Parameters
handle the semaphore handle
Definition at line 85 of file semaphore.c.
Referenced by tb_event_exit(), tb_semaphore_init(), and tb_thread_pool_exit().
__tb_extern_c_enter__ tb_semaphore_ref_t tb_semaphore_init (tb_size_t init)
init semaphore
Parameters
init the init semaphore value
Returns
the semaphore handle
Definition at line 52 of file semaphore.c.
References tb_semaphore_exit().
Referenced by tb_thread_pool_init().
tb_bool_t tb_semaphore_post (tb_semaphore_ref_t semaphore, tb_size_t post)
post semaphore
Parameters
handle the semaphore handle
post the post semaphore value
Returns
tb_true or tb_false
Definition at line 97 of file semaphore.c.
Referenced by tb_event_post().
tb_long_t tb_semaphore_value (tb_semaphore_ref_t semaphore)
the semaphore value
Parameters
handle the semaphore handle
Returns
>= 0: the semaphore value, -1: failed
Definition at line 124 of file semaphore.c.
tb_long_t tb_semaphore_wait (tb_semaphore_ref_t semaphore, tb_long_t timeout)
wait semaphore
Parameters
handle the semaphore handle
timeout the timeout
Returns
ok: 1, timeout: 0, fail: -1
Definition at line 133 of file semaphore.c.
Referenced by tb_event_wait().