TBOX: src/stream/gstream.h File Reference
gstream.h File Reference
Stream
#include "prefix.h"
#include "../asio/asio.h"
#include "../libc/libc.h"
#include "../network/url.h"
#include "../memory/memory.h"
Data Structures
struct tb_gstream_t
the generic stream type
Macros
#define TB_GSTREAM_BLOCK_MAXN (8192)
#define tb_gstream_bread_u16_ne(gstream) tb_gstream_bread_u16_le(gstream)
#define tb_gstream_bread_s16_ne(gstream) tb_gstream_bread_s16_le(gstream)
#define tb_gstream_bread_u24_ne(gstream) tb_gstream_bread_u24_le(gstream)
#define tb_gstream_bread_s24_ne(gstream) tb_gstream_bread_s24_le(gstream)
#define tb_gstream_bread_u32_ne(gstream) tb_gstream_bread_u32_le(gstream)
#define tb_gstream_bread_s32_ne(gstream) tb_gstream_bread_s32_le(gstream)
#define tb_gstream_bread_u64_ne(gstream) tb_gstream_bread_u64_le(gstream)
#define tb_gstream_bread_s64_ne(gstream) tb_gstream_bread_s64_le(gstream)
#define tb_gstream_bwrit_u16_ne(gstream, val) tb_gstream_bwrit_u16_le(gstream, val)
#define tb_gstream_bwrit_s16_ne(gstream, val) tb_gstream_bwrit_s16_le(gstream, val)
#define tb_gstream_bwrit_u24_ne(gstream, val) tb_gstream_bwrit_u24_le(gstream, val)
#define tb_gstream_bwrit_s24_ne(gstream, val) tb_gstream_bwrit_s24_le(gstream, val)
#define tb_gstream_bwrit_u32_ne(gstream, val) tb_gstream_bwrit_u32_le(gstream, val)
#define tb_gstream_bwrit_s32_ne(gstream, val) tb_gstream_bwrit_s32_le(gstream, val)
#define tb_gstream_bwrit_u64_ne(gstream, val) tb_gstream_bwrit_u64_le(gstream, val)
#define tb_gstream_bwrit_s64_ne(gstream, val) tb_gstream_bwrit_s64_le(gstream, val)
Enumerations
enum tb_gstream_wait_e { TB_GSTREAM_WAIT_NONE = TB_AIOE_CODE_NONE, TB_GSTREAM_WAIT_READ = TB_AIOE_CODE_RECV, TB_GSTREAM_WAIT_WRIT = TB_AIOE_CODE_SEND, TB_GSTREAM_WAIT_EALL = TB_AIOE_CODE_EALL }
the gstream wait enum
Functions
tb_gstream_t * tb_gstream_init_data (tb_noarg_t)
tb_gstream_t * tb_gstream_init_file (tb_noarg_t)
tb_gstream_t * tb_gstream_init_sock (tb_noarg_t)
tb_gstream_t * tb_gstream_init_http (tb_noarg_t)
tb_gstream_t * tb_gstream_init_filter (tb_noarg_t)
tb_void_t tb_gstream_exit (tb_gstream_t *gstream)
tb_gstream_t * tb_gstream_init_from_url (tb_char_t const *url)
tb_gstream_t * tb_gstream_init_from_data (tb_byte_t const *data, tb_size_t size)
tb_gstream_t * tb_gstream_init_from_file (tb_char_t const *path, tb_size_t mode)
tb_gstream_t * tb_gstream_init_from_sock (tb_char_t const *host, tb_size_t port, tb_size_t type, tb_bool_t bssl)
tb_gstream_t * tb_gstream_init_from_http (tb_char_t const *host, tb_size_t port, tb_char_t const *path, tb_bool_t bssl)
tb_gstream_t * tb_gstream_init_filter_from_null (tb_gstream_t *gstream)
tb_gstream_t * tb_gstream_init_filter_from_zip (tb_gstream_t *gstream, tb_size_t algo, tb_size_t action)
tb_gstream_t * tb_gstream_init_filter_from_cache (tb_gstream_t *gstream, tb_size_t size)
tb_gstream_t * tb_gstream_init_filter_from_charset (tb_gstream_t *gstream, tb_size_t fr, tb_size_t to)
tb_gstream_t * tb_gstream_init_filter_from_chunked (tb_gstream_t *gstream, tb_bool_t dechunked)
tb_long_t tb_gstream_wait (tb_gstream_t *gstream, tb_size_t wait, tb_long_t timeout)
tb_size_t tb_gstream_state (tb_gstream_t *gstream)
tb_bool_t tb_gstream_open (tb_gstream_t *gstream)
tb_bool_t tb_gstream_clos (tb_gstream_t *gstream)
tb_long_t tb_gstream_aread (tb_gstream_t *gstream, tb_byte_t *data, tb_size_t size)
tb_long_t tb_gstream_awrit (tb_gstream_t *gstream, tb_byte_t const *data, tb_size_t size)
tb_bool_t tb_gstream_bread (tb_gstream_t *gstream, tb_byte_t *data, tb_size_t size)
tb_bool_t tb_gstream_bwrit (tb_gstream_t *gstream, tb_byte_t const *data, tb_size_t size)
tb_bool_t tb_gstream_sync (tb_gstream_t *gstream, tb_bool_t bclosing)
tb_bool_t tb_gstream_need (tb_gstream_t *gstream, tb_byte_t **data, tb_size_t size)
tb_bool_t tb_gstream_seek (tb_gstream_t *gstream, tb_hize_t offset)
tb_bool_t tb_gstream_skip (tb_gstream_t *gstream, tb_hize_t size)
tb_long_t tb_gstream_printf (tb_gstream_t *gstream, tb_char_t const *fmt,...)
tb_long_t tb_gstream_bread_line (tb_gstream_t *gstream, tb_char_t *data, tb_size_t size)
tb_long_t tb_gstream_bwrit_line (tb_gstream_t *gstream, tb_char_t *data, tb_size_t size)
tb_uint8_t tb_gstream_bread_u8 (tb_gstream_t *gstream)
tb_sint8_t tb_gstream_bread_s8 (tb_gstream_t *gstream)
tb_uint16_t tb_gstream_bread_u16_le (tb_gstream_t *gstream)
tb_sint16_t tb_gstream_bread_s16_le (tb_gstream_t *gstream)
tb_uint32_t tb_gstream_bread_u24_le (tb_gstream_t *gstream)
tb_sint32_t tb_gstream_bread_s24_le (tb_gstream_t *gstream)
tb_uint32_t tb_gstream_bread_u32_le (tb_gstream_t *gstream)
tb_sint32_t tb_gstream_bread_s32_le (tb_gstream_t *gstream)
tb_uint64_t tb_gstream_bread_u64_le (tb_gstream_t *gstream)
tb_sint64_t tb_gstream_bread_s64_le (tb_gstream_t *gstream)
tb_uint16_t tb_gstream_bread_u16_be (tb_gstream_t *gstream)
tb_sint16_t tb_gstream_bread_s16_be (tb_gstream_t *gstream)
tb_uint32_t tb_gstream_bread_u24_be (tb_gstream_t *gstream)
tb_sint32_t tb_gstream_bread_s24_be (tb_gstream_t *gstream)
tb_uint32_t tb_gstream_bread_u32_be (tb_gstream_t *gstream)
tb_sint32_t tb_gstream_bread_s32_be (tb_gstream_t *gstream)
tb_uint64_t tb_gstream_bread_u64_be (tb_gstream_t *gstream)
tb_sint64_t tb_gstream_bread_s64_be (tb_gstream_t *gstream)
tb_bool_t tb_gstream_bwrit_u8 (tb_gstream_t *gstream, tb_uint8_t val)
tb_bool_t tb_gstream_bwrit_s8 (tb_gstream_t *gstream, tb_sint8_t val)
tb_bool_t tb_gstream_bwrit_u16_le (tb_gstream_t *gstream, tb_uint16_t val)
tb_bool_t tb_gstream_bwrit_s16_le (tb_gstream_t *gstream, tb_sint16_t val)
tb_bool_t tb_gstream_bwrit_u24_le (tb_gstream_t *gstream, tb_uint32_t val)
tb_bool_t tb_gstream_bwrit_s24_le (tb_gstream_t *gstream, tb_sint32_t val)
tb_bool_t tb_gstream_bwrit_u32_le (tb_gstream_t *gstream, tb_uint32_t val)
tb_bool_t tb_gstream_bwrit_s32_le (tb_gstream_t *gstream, tb_sint32_t val)
tb_bool_t tb_gstream_bwrit_u64_le (tb_gstream_t *gstream, tb_uint64_t val)
tb_bool_t tb_gstream_bwrit_s64_le (tb_gstream_t *gstream, tb_sint64_t val)
tb_bool_t tb_gstream_bwrit_u16_be (tb_gstream_t *gstream, tb_uint16_t val)
tb_bool_t tb_gstream_bwrit_s16_be (tb_gstream_t *gstream, tb_sint16_t val)
tb_bool_t tb_gstream_bwrit_u24_be (tb_gstream_t *gstream, tb_uint32_t val)
tb_bool_t tb_gstream_bwrit_s24_be (tb_gstream_t *gstream, tb_sint32_t val)
tb_bool_t tb_gstream_bwrit_u32_be (tb_gstream_t *gstream, tb_uint32_t val)
tb_bool_t tb_gstream_bwrit_s32_be (tb_gstream_t *gstream, tb_sint32_t val)
tb_bool_t tb_gstream_bwrit_u64_be (tb_gstream_t *gstream, tb_uint64_t val)
tb_bool_t tb_gstream_bwrit_s64_be (tb_gstream_t *gstream, tb_sint64_t val)
Detailed Description
The Treasure Box Library
TBox is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 2.1 of the License, or (at your option) any later version.
TBox is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with TBox; If not, see http://www.gnu.org/licenses/
Copyright (C) 2009 - 2015, ruki All rights reserved.
Author
ruki
Definition in file gstream.h.
Function Documentation
tb_long_t tb_gstream_aread (tb_gstream_t * gstream, tb_byte_t * data, tb_size_t size)
async read
Parameters
gstream the stream
data the data
size the size
Returns
the real size or -1
Definition at line 297 of file gstream.c.
References tb_gstream_t::bwrited, tb_gstream_t::cache, tb_gstream_t::offset, tb_gstream_t::read, tb_qbuffer_maxn(), tb_qbuffer_null(), tb_qbuffer_push_exit(), tb_qbuffer_push_init(), tb_qbuffer_read(), and tb_stream_is_opened().
Referenced by tb_dump_data_from_stream(), tb_gstream_bread(), and tb_tstream_save_gg().
tb_long_t tb_gstream_awrit (tb_gstream_t * gstream, tb_byte_t const * data, tb_size_t size)
async writ
Parameters
gstream the stream
data the data
size the size
Returns
the real size or -1
Definition at line 369 of file gstream.c.
References tb_gstream_t::bwrited, tb_gstream_t::cache, tb_gstream_t::offset, tb_qbuffer_full(), tb_qbuffer_maxn(), tb_qbuffer_null(), tb_qbuffer_pull_exit(), tb_qbuffer_pull_init(), tb_qbuffer_writ(), tb_stream_is_opened(), and tb_gstream_t::writ.
Referenced by tb_gstream_bwrit().
tb_bool_t tb_gstream_bread (tb_gstream_t * gstream, tb_byte_t * data, tb_size_t size)
block read
Parameters
gstream the stream
data the data
size the size
Returns
tb_true or tb_false
Definition at line 440 of file gstream.c.
References tb_gstream_t::base, tb_stream_t::bstoped, tb_gstream_t::bwrited, tb_gstream_t::cache, tb_gstream_t::state, tb_gstream_aread(), tb_gstream_sync(), tb_gstream_wait(), tb_qbuffer_null(), tb_stream_left(), and tb_stream_timeout().
Referenced by tb_data_init_from_url(), tb_gstream_bread_s16_be(), tb_gstream_bread_s16_le(), tb_gstream_bread_s24_be(), tb_gstream_bread_s24_le(), tb_gstream_bread_s32_be(), tb_gstream_bread_s32_le(), tb_gstream_bread_s64_be(), tb_gstream_bread_s64_le(), tb_gstream_bread_s8(), tb_gstream_bread_u16_be(), tb_gstream_bread_u16_le(), tb_gstream_bread_u24_be(), tb_gstream_bread_u24_le(), tb_gstream_bread_u32_be(), tb_gstream_bread_u32_le(), tb_gstream_bread_u64_be(), tb_gstream_bread_u64_le(), tb_gstream_bread_u8(), and tb_gstream_seek().
tb_long_t tb_gstream_bread_line (tb_gstream_t * gstream, tb_char_t * data, tb_size_t size)
block read line
Parameters
gstream the stream
data the data
size the size
Returns
the real size
Definition at line 670 of file gstream.c.
References tb_gstream_t::base, tb_stream_t::bstoped, tb_gstream_bread_s8(), and tb_stream_beof().
tb_sint16_t tb_gstream_bread_s16_be (tb_gstream_t * gstream)
block read sint16-be integer
Parameters
gstream the stream
Returns
the sint16-be integer
Definition at line 822 of file gstream.c.
References tb_gstream_bread().
tb_sint16_t tb_gstream_bread_s16_le (tb_gstream_t * gstream)
block read sint16-le integer
Parameters
gstream the stream
Returns
the sint16-le integer
Definition at line 774 of file gstream.c.
References tb_gstream_bread().
tb_sint32_t tb_gstream_bread_s24_be (tb_gstream_t * gstream)
block read sint24-be integer
Parameters
gstream the stream
Returns
the sint24-be integer
Definition at line 834 of file gstream.c.
References tb_gstream_bread().
tb_sint32_t tb_gstream_bread_s24_le (tb_gstream_t * gstream)
block read sint24-le integer
Parameters
gstream the stream
Returns
the sint24-le integer
Definition at line 786 of file gstream.c.
References tb_gstream_bread().
tb_sint32_t tb_gstream_bread_s32_be (tb_gstream_t * gstream)
block read sint32-be integer
Parameters
gstream the stream
Returns
the sint32-be integer
Definition at line 846 of file gstream.c.
References tb_gstream_bread().
tb_sint32_t tb_gstream_bread_s32_le (tb_gstream_t * gstream)
block read sint32-le integer
Parameters
gstream the stream
Returns
the sint32-le integer
Definition at line 798 of file gstream.c.
References tb_gstream_bread().
tb_sint64_t tb_gstream_bread_s64_be (tb_gstream_t * gstream)
block read sint64-be integer
Parameters
gstream the stream
Returns
the sint64-be integer
Definition at line 858 of file gstream.c.
References tb_gstream_bread().
tb_sint64_t tb_gstream_bread_s64_le (tb_gstream_t * gstream)
block read sint64-le integer
Parameters
gstream the stream
Returns
the sint64-le integer
Definition at line 810 of file gstream.c.
References tb_gstream_bread().
tb_sint8_t tb_gstream_bread_s8 (tb_gstream_t * gstream)
block read sint8 integer
Parameters
gstream the stream
Returns
the sint8 integer
Definition at line 761 of file gstream.c.
References tb_gstream_bread().
Referenced by tb_gstream_bread_line().
tb_uint16_t tb_gstream_bread_u16_be (tb_gstream_t * gstream)
block read uint16-be integer
Parameters
gstream the stream
Returns
the uint16-be integer
Definition at line 816 of file gstream.c.
References tb_gstream_bread().
tb_uint16_t tb_gstream_bread_u16_le (tb_gstream_t * gstream)
block read uint16-le integer
Parameters
gstream the stream
Returns
the uint16-le integer
Definition at line 768 of file gstream.c.
References tb_gstream_bread().
tb_uint32_t tb_gstream_bread_u24_be (tb_gstream_t * gstream)
block read uint24-be integer
Parameters
gstream the stream
Returns
the uint24-be integer
Definition at line 828 of file gstream.c.
References tb_gstream_bread().
tb_uint32_t tb_gstream_bread_u24_le (tb_gstream_t * gstream)
block read uint24-le integer
Parameters
gstream the stream
Returns
the uint24-le integer
Definition at line 780 of file gstream.c.
References tb_gstream_bread().
tb_uint32_t tb_gstream_bread_u32_be (tb_gstream_t * gstream)
block read uint32-be integer
Parameters
gstream the stream
Returns
the uint32-be integer
Definition at line 840 of file gstream.c.
References tb_gstream_bread().
tb_uint32_t tb_gstream_bread_u32_le (tb_gstream_t * gstream)
block read uint32-le integer
Parameters
gstream the stream
Returns
the uint32-le integer
Definition at line 792 of file gstream.c.
References tb_gstream_bread().
tb_uint64_t tb_gstream_bread_u64_be (tb_gstream_t * gstream)
block read uint64-be integer
Parameters
gstream the stream
Returns
the uint64-be integer
Definition at line 852 of file gstream.c.
References tb_gstream_bread().
tb_uint64_t tb_gstream_bread_u64_le (tb_gstream_t * gstream)
block read uint64-le integer
Parameters
gstream the stream
Returns
the uint64-le integer
Definition at line 804 of file gstream.c.
References tb_gstream_bread().
tb_uint8_t tb_gstream_bread_u8 (tb_gstream_t * gstream)
block read uint8 integer
Parameters
gstream the stream
Returns
the uint8 integer
Definition at line 755 of file gstream.c.
References tb_gstream_bread().
tb_bool_t tb_gstream_bwrit (tb_gstream_t * gstream, tb_byte_t const * data, tb_size_t size)
block writ
Parameters
gstream the stream
data the data
size the size
Returns
tb_true or tb_false
Definition at line 480 of file gstream.c.
References tb_gstream_t::base, tb_stream_t::bstoped, tb_gstream_t::state, tb_gstream_awrit(), tb_gstream_wait(), and tb_stream_timeout().
Referenced by tb_data_writ_to_url(), tb_gstream_bwrit_line(), tb_gstream_bwrit_s16_be(), tb_gstream_bwrit_s16_le(), tb_gstream_bwrit_s24_be(), tb_gstream_bwrit_s24_le(), tb_gstream_bwrit_s32_be(), tb_gstream_bwrit_s32_le(), tb_gstream_bwrit_s64_be(), tb_gstream_bwrit_s64_le(), tb_gstream_bwrit_s8(), tb_gstream_bwrit_u16_be(), tb_gstream_bwrit_u16_le(), tb_gstream_bwrit_u24_be(), tb_gstream_bwrit_u24_le(), tb_gstream_bwrit_u32_be(), tb_gstream_bwrit_u32_le(), tb_gstream_bwrit_u64_be(), tb_gstream_bwrit_u64_le(), tb_gstream_bwrit_u8(), tb_gstream_printf(), and tb_tstream_save_gg().
tb_long_t tb_gstream_bwrit_line (tb_gstream_t * gstream, tb_char_t * data, tb_size_t size)
block writ line
Parameters
gstream the stream
data the data
size the size
Returns
the real size
Definition at line 708 of file gstream.c.
References tb_gstream_bwrit().
tb_bool_t tb_gstream_bwrit_s16_be (tb_gstream_t * gstream, tb_sint16_t val)
block writ sint16-be integer
Parameters
gstream the stream
val the value
Returns
tb_true or tb_false
Definition at line 933 of file gstream.c.
References tb_gstream_bwrit().
tb_bool_t tb_gstream_bwrit_s16_le (tb_gstream_t * gstream, tb_sint16_t val)
block writ sint16-le integer
Parameters
gstream the stream
val the value
Returns
tb_true or tb_false
Definition at line 883 of file gstream.c.
References tb_gstream_bwrit().
tb_bool_t tb_gstream_bwrit_s24_be (tb_gstream_t * gstream, tb_sint32_t val)
block writ sint24-be integer
Parameters
gstream the stream
val the value
Returns
tb_true or tb_false
Definition at line 946 of file gstream.c.
References tb_gstream_bwrit().
tb_bool_t tb_gstream_bwrit_s24_le (tb_gstream_t * gstream, tb_sint32_t val)
block writ sint24-le integer
Parameters
gstream the stream
val the value
Returns
tb_true or tb_false
Definition at line 896 of file gstream.c.
References tb_gstream_bwrit().
tb_bool_t tb_gstream_bwrit_s32_be (tb_gstream_t * gstream, tb_sint32_t val)
block writ sint32-be integer
Parameters
gstream the stream
val the value
Returns
tb_true or tb_false
Definition at line 958 of file gstream.c.
References tb_gstream_bwrit().
tb_bool_t tb_gstream_bwrit_s32_le (tb_gstream_t * gstream, tb_sint32_t val)
block writ sint32-le integer
Parameters
gstream the stream
val the value
Returns
tb_true or tb_false
Definition at line 909 of file gstream.c.
References tb_gstream_bwrit().
tb_bool_t tb_gstream_bwrit_s64_be (tb_gstream_t * gstream, tb_sint64_t val)
block writ sint64-be integer
Parameters
gstream the stream
val the value
Returns
tb_true or tb_false
Definition at line 970 of file gstream.c.
References tb_gstream_bwrit().
tb_bool_t tb_gstream_bwrit_s64_le (tb_gstream_t * gstream, tb_sint64_t val)
block writ sint64-le integer
Parameters
gstream the stream
val the value
Returns
tb_true or tb_false
Definition at line 921 of file gstream.c.
References tb_gstream_bwrit().
tb_bool_t tb_gstream_bwrit_s8 (tb_gstream_t * gstream, tb_sint8_t val)
block writ sint8 integer
Parameters
gstream the stream
val the value
Returns
tb_true or tb_false
Definition at line 870 of file gstream.c.
References tb_gstream_bwrit().
tb_bool_t tb_gstream_bwrit_u16_be (tb_gstream_t * gstream, tb_uint16_t val)
block writ uint16-be integer
Parameters
gstream the stream
val the value
Returns
tb_true or tb_false
Definition at line 927 of file gstream.c.
References tb_gstream_bwrit().
tb_bool_t tb_gstream_bwrit_u16_le (tb_gstream_t * gstream, tb_uint16_t val)
block writ uint16-le integer
Parameters
gstream the stream
val the value
Returns
tb_true or tb_false
Definition at line 877 of file gstream.c.
References tb_gstream_bwrit().
tb_bool_t tb_gstream_bwrit_u24_be (tb_gstream_t * gstream, tb_uint32_t val)
block writ uint24-be integer
Parameters
gstream the stream
val the value
Returns
tb_true or tb_false
Definition at line 940 of file gstream.c.
References tb_gstream_bwrit().
tb_bool_t tb_gstream_bwrit_u24_le (tb_gstream_t * gstream, tb_uint32_t val)
block writ uint24-le integer
Parameters
gstream the stream
val the value
Returns
tb_true or tb_false
Definition at line 890 of file gstream.c.
References tb_gstream_bwrit().
tb_bool_t tb_gstream_bwrit_u32_be (tb_gstream_t * gstream, tb_uint32_t val)
block writ uint32-be integer
Parameters
gstream the stream
val the value
Returns
tb_true or tb_false
Definition at line 952 of file gstream.c.
References tb_gstream_bwrit().
tb_bool_t tb_gstream_bwrit_u32_le (tb_gstream_t * gstream, tb_uint32_t val)
block writ uint32-le integer
Parameters
gstream the stream
val the value
Returns
tb_true or tb_false
Definition at line 903 of file gstream.c.
References tb_gstream_bwrit().
tb_bool_t tb_gstream_bwrit_u64_be (tb_gstream_t * gstream, tb_uint64_t val)
block writ uint64-be integer
Parameters
gstream the stream
val the value
Returns
tb_true or tb_false
Definition at line 964 of file gstream.c.
References tb_gstream_bwrit().
tb_bool_t tb_gstream_bwrit_u64_le (tb_gstream_t * gstream, tb_uint64_t val)
block writ uint64-le integer
Parameters
gstream the stream
val the value
Returns
tb_true or tb_false
Definition at line 915 of file gstream.c.
References tb_gstream_bwrit().
tb_bool_t tb_gstream_bwrit_u8 (tb_gstream_t * gstream, tb_uint8_t val)
block writ uint8 integer
Parameters
gstream the stream
val the value
Returns
tb_true or tb_false
Definition at line 864 of file gstream.c.
References tb_gstream_bwrit().
tb_bool_t tb_gstream_clos (tb_gstream_t * gstream)
close stream
Parameters
gstream the stream
Returns
tb_true or tb_false
Definition at line 185 of file gstream.c.
References tb_gstream_t::base, tb_stream_t::bopened, tb_stream_t::bstoped, tb_gstream_t::bwrited, tb_gstream_t::cache, tb_gstream_t::clos, tb_gstream_t::offset, tb_gstream_t::state, tb_gstream_sync(), tb_qbuffer_clear(), and tb_stream_is_opened().
Referenced by tb_gstream_exit().
tb_void_t tb_gstream_exit (tb_gstream_t * gstream)
exit stream
Parameters
gstream the stream
Definition at line 95 of file gstream.c.
References tb_gstream_t::base, tb_gstream_t::cache, tb_gstream_t::exit, tb_gstream_clos(), tb_qbuffer_exit(), and tb_stream_t::url.
Referenced by tb_data_init_from_url(), tb_data_writ_to_url(), tb_dump_data(), tb_dump_data_from_url(), tb_gstream_init_filter_from_cache(), tb_gstream_init_filter_from_charset(), tb_gstream_init_filter_from_chunked(), tb_gstream_init_filter_from_null(), tb_gstream_init_filter_from_zip(), tb_gstream_init_from_data(), tb_gstream_init_from_file(), tb_gstream_init_from_http(), tb_gstream_init_from_sock(), tb_gstream_init_from_url(), tb_object_read_from_data(), tb_object_read_from_url(), tb_object_writ_to_data(), tb_object_writ_to_url(), tb_tstream_exit(), tb_tstream_save_dg(), tb_tstream_save_du(), tb_tstream_save_gd(), tb_tstream_save_gu(), tb_tstream_save_ud(), tb_tstream_save_ug(), and tb_tstream_save_uu().
tb_gstream_t* tb_gstream_init_data (tb_noarg_t)
init data stream
Returns
the stream
Referenced by tb_gstream_init_from_data(), and tb_gstream_init_from_url().
tb_gstream_t* tb_gstream_init_file (tb_noarg_t)
init file stream
Returns
the stream
Referenced by tb_gstream_init_from_file(), and tb_gstream_init_from_url().
tb_gstream_t* tb_gstream_init_filter (tb_noarg_t)
init filter stream
Returns
the stream
Referenced by tb_gstream_init_filter_from_cache(), tb_gstream_init_filter_from_charset(), tb_gstream_init_filter_from_chunked(), tb_gstream_init_filter_from_null(), and tb_gstream_init_filter_from_zip().
tb_gstream_t* tb_gstream_init_filter_from_cache (tb_gstream_t * gstream, tb_size_t size)
init filter stream from cache
Parameters
gstream the stream
size the initial cache size, using the default size if be zero
Returns
the stream
Definition at line 440 of file filter.c.
References tb_filter_init_from_cache(), tb_gstream_exit(), tb_gstream_init_filter(), and tb_stream_ctrl().
tb_gstream_t* tb_gstream_init_filter_from_charset (tb_gstream_t * gstream, tb_size_t fr, tb_size_t to)
init filter stream from charset
Parameters
gstream the stream
fr the from charset
to the to charset
Returns
the stream
Definition at line 463 of file filter.c.
References tb_filter_init_from_charset(), tb_gstream_exit(), tb_gstream_init_filter(), and tb_stream_ctrl().
tb_gstream_t* tb_gstream_init_filter_from_chunked (tb_gstream_t * gstream, tb_bool_t dechunked)
init filter stream from chunked
Parameters
gstream the stream
dechunked decode the chunked data?
Returns
the stream
Definition at line 486 of file filter.c.
References tb_filter_init_from_chunked(), tb_gstream_exit(), tb_gstream_init_filter(), and tb_stream_ctrl().
tb_gstream_t* tb_gstream_init_filter_from_null (tb_gstream_t * gstream)
init filter stream from null
Parameters
gstream the stream
Returns
the stream
Definition at line 399 of file filter.c.
References tb_gstream_exit(), tb_gstream_init_filter(), and tb_stream_ctrl().
tb_gstream_t* tb_gstream_init_filter_from_zip (tb_gstream_t * gstream, tb_size_t algo, tb_size_t action)
init filter stream from zip
Parameters
gstream the stream
algo the zip algorithm
action the zip action
Returns
the stream
Definition at line 417 of file filter.c.
References tb_filter_init_from_zip(), tb_gstream_exit(), tb_gstream_init_filter(), and tb_stream_ctrl().
tb_gstream_t* tb_gstream_init_from_data (tb_byte_t const * data, tb_size_t size)
init stream from data
Parameters
data the data
size the size
Returns
the stream
Definition at line 299 of file data.c.
References tb_gstream_exit(), tb_gstream_init_data(), and tb_stream_ctrl().
Referenced by tb_dump_data(), tb_object_read_from_data(), tb_object_writ_to_data(), tb_tstream_save_dg(), tb_tstream_save_du(), tb_tstream_save_gd(), and tb_tstream_save_ud().
tb_gstream_t* tb_gstream_init_from_file (tb_char_t const * path, tb_size_t mode)
init stream from file
Parameters
path the file path
mode the file mode, using the default ro mode if zero
Returns
the stream
Definition at line 255 of file file.c.
References tb_gstream_exit(), tb_gstream_init_file(), and tb_stream_ctrl().
tb_gstream_t* tb_gstream_init_from_http (tb_char_t const * host, tb_size_t port, tb_char_t const * path, tb_bool_t bssl)
init stream from http or https
Parameters
host the host
port the port
path the path
bssl enable ssl?
Returns
the stream
Definition at line 597 of file http.c.
References tb_gstream_exit(), tb_gstream_init_http(), and tb_stream_ctrl().
tb_gstream_t* tb_gstream_init_from_sock (tb_char_t const * host, tb_size_t port, tb_size_t type, tb_bool_t bssl)
init stream from sock
Parameters
host the host
port the port
type the socket type, tcp or udp
bssl enable ssl?
Returns
the stream
Definition at line 638 of file sock.c.
References tb_gstream_exit(), tb_gstream_init_sock(), and tb_stream_ctrl().
tb_gstream_t* tb_gstream_init_from_url (tb_char_t const * url)
init stream from url
Parameters
url the url
data://base64
file://path or unix path: e.g. /root/xxxx/file
sock://host:port?tcp=
sock://host:port?udp=
socks://host:port
http://host:port/path?arg0=&arg1=...
https://host:port/path?arg0=&arg1=...
Returns
the stream
Definition at line 46 of file gstream.c.
References tb_gstream_exit(), tb_gstream_init_data(), tb_gstream_init_file(), tb_gstream_init_http(), tb_gstream_init_sock(), and tb_stream_ctrl().
Referenced by tb_data_init_from_url(), tb_data_writ_to_url(), tb_dump_data_from_url(), tb_object_read_from_url(), tb_object_writ_to_url(), tb_tstream_save_du(), tb_tstream_save_gu(), tb_tstream_save_ud(), tb_tstream_save_ug(), and tb_tstream_save_uu().
tb_gstream_t* tb_gstream_init_http (tb_noarg_t)
init http stream
Returns
the stream
Referenced by tb_gstream_init_from_http(), and tb_gstream_init_from_url().
tb_gstream_t* tb_gstream_init_sock (tb_noarg_t)
init sock stream
Returns
the stream
Referenced by tb_gstream_init_from_sock(), and tb_gstream_init_from_url().
tb_bool_t tb_gstream_need (tb_gstream_t * gstream, tb_byte_t ** data, tb_size_t size)
need stream
Parameters
gstream the stream
data the data
size the size
Returns
tb_true or tb_false
Definition at line 212 of file gstream.c.
References tb_gstream_t::base, tb_stream_t::bstoped, tb_gstream_t::bwrited, tb_gstream_t::cache, tb_gstream_t::read, tb_gstream_t::state, tb_gstream_sync(), tb_qbuffer_head(), tb_qbuffer_maxn(), tb_qbuffer_null(), tb_qbuffer_push_exit(), tb_qbuffer_push_init(), tb_qbuffer_size(), tb_stream_is_opened(), tb_stream_timeout(), and tb_gstream_t::wait.
tb_bool_t tb_gstream_open (tb_gstream_t * gstream)
open stream
Parameters
gstream the stream
Returns
tb_true or tb_false
Definition at line 154 of file gstream.c.
References tb_gstream_t::base, tb_stream_t::bopened, tb_stream_t::bstoped, tb_gstream_t::offset, tb_gstream_t::open, tb_gstream_t::state, and tb_stream_is_opened().
Referenced by tb_data_init_from_url(), tb_data_writ_to_url(), tb_dump_data(), tb_dump_data_from_url(), tb_object_read_from_data(), tb_object_read_from_url(), tb_object_writ_to_data(), tb_object_writ_to_url(), tb_tstream_open(), tb_tstream_save_gg(), and tb_tstream_save_uu().
tb_long_t tb_gstream_printf (tb_gstream_t * gstream, tb_char_t const * fmt, ...)
block writ format data
Parameters
gstream the stream
fmt the format
Returns
the real size, failed: -1
Definition at line 742 of file gstream.c.
References tb_gstream_bwrit().
tb_bool_t tb_gstream_seek (tb_gstream_t * gstream, tb_hize_t offset)
seek stream
Parameters
gstream the stream
offset the offset
Returns
tb_true or tb_false
Definition at line 580 of file gstream.c.
References tb_gstream_t::base, tb_stream_t::bstoped, tb_gstream_t::bwrited, tb_gstream_t::cache, tb_gstream_t::offset, tb_gstream_t::seek, tb_gstream_bread(), tb_gstream_sync(), tb_qbuffer_clear(), tb_qbuffer_maxn(), tb_qbuffer_null(), tb_qbuffer_pull_exit(), tb_qbuffer_pull_init(), tb_stream_is_opened(), tb_stream_offset(), and tb_stream_size().
Referenced by tb_gstream_skip().
tb_bool_t tb_gstream_skip (tb_gstream_t * gstream, tb_hize_t size)
skip stream
Parameters
gstream the stream
size the size
Returns
tb_true or tb_false
Definition at line 666 of file gstream.c.
References tb_gstream_seek(), and tb_stream_offset().
tb_size_t tb_gstream_state (tb_gstream_t * gstream)
the state
Parameters
gstream the stream
Returns
the state
Definition at line 146 of file gstream.c.
References tb_gstream_t::state.
tb_bool_t tb_gstream_sync (tb_gstream_t * gstream, tb_bool_t bclosing)
sync stream
Parameters
gstream the stream
bclosing is closing?
Returns
tb_true or tb_false
Definition at line 512 of file gstream.c.
References tb_gstream_t::base, tb_stream_t::bstoped, tb_gstream_t::bwrited, tb_gstream_t::cache, tb_gstream_t::state, tb_gstream_t::sync, tb_qbuffer_maxn(), tb_qbuffer_null(), tb_qbuffer_pull_exit(), tb_qbuffer_pull_init(), tb_stream_is_opened(), tb_stream_timeout(), tb_gstream_t::wait, and tb_gstream_t::writ.
Referenced by tb_gstream_bread(), tb_gstream_clos(), tb_gstream_need(), tb_gstream_seek(), and tb_tstream_save_gg().
tb_long_t tb_gstream_wait (tb_gstream_t * gstream, tb_size_t wait, tb_long_t timeout)
wait stream
blocking wait the single event object, so need not aiop return the event type if ok, otherwise return 0 for timeout
Parameters
gstream the gstream
wait the wait type
timeout the timeout value, return immediately if 0, infinity if -1
Returns
the event type, return 0 if timeout, return -1 if error
Definition at line 115 of file gstream.c.
References tb_gstream_t::base, tb_stream_t::bstoped, tb_gstream_t::bwrited, tb_gstream_t::cache, tb_gstream_t::state, tb_qbuffer_full(), tb_qbuffer_maxn(), tb_qbuffer_null(), and tb_gstream_t::wait.
Referenced by tb_dump_data_from_stream(), tb_gstream_bread(), tb_gstream_bwrit(), and tb_tstream_save_gg().