TBOX: src/tbox/tbox.h File Reference
tbox.h File Reference
#include "prefix.h"
#include "algorithm/algorithm.h"
#include "container/container.h"
#include "platform/platform.h"
#include "database/database.h"
#include "network/network.h"
#include "charset/charset.h"
#include "memory/memory.h"
#include "stream/stream.h"
#include "string/string.h"
#include "object/object.h"
#include "utils/utils.h"
#include "math/math.h"
#include "libc/libc.h"
#include "libm/libm.h"
#include "asio/asio.h"
#include "xml/xml.h"
#include "zip/zip.h"
Macros
#define TB_MODE_DEBUG (1)
#define TB_MODE_SMALL (2)
#define __tb_mode_debug__ (0)
#define __tb_mode_small__ (0)
#define tb_init(priv, data, size) tb_init_(priv, data, size, (tb_size_t)(__tb_mode_debug__ | __tb_mode_small__), TB_VERSION_BUILD)
Functions
__tb_extern_c_enter__ tb_bool_t tb_init_ (tb_handle_t priv, tb_byte_t *data, tb_size_t size, tb_size_t mode, tb_hize_t build)
tb_void_t tb_exit (tb_noarg_t)
exit the tbox library
tb_version_t const * tb_version (tb_noarg_t)
Detailed Description
The Treasure Box Library
TBox is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 2.1 of the License, or (at your option) any later version.
TBox is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with TBox; If not, see http://www.gnu.org/licenses/
Copyright (C) 2009 - 2015, ruki All rights reserved.
Author
ruki
Definition in file tbox.h.
Macro Definition Documentation
#define tb_init (priv, data, size) tb_init_(priv, data, size, (tb_size_t)(__tb_mode_debug__ | __tb_mode_small__), TB_VERSION_BUILD)
init tbox
Parameters
priv the platform private data pass JNIEnv* env for android pass tb_null for other platform
data the memory data for the memory pool, uses the native memory if be tb_null
size the memory size for the memory pool, uses the native memory if be zero
Returns
tb_true or tb_false
#include "tbox/tbox.h"
int main(int argc, char** argv)
{
    // init tbox
    if (!tb_init(tb_null, tb_null, 0)) return 0;
    // print info with tag
    tb_trace_i("hello tbox");
    // print info only for debug
    tb_trace_d("hello tbox");
    // print error info
    tb_trace_e("hello tbox");
    // init stream
    tb_stream_ref_t stream = tb_stream_init_from_url("http://www.xxxx.com/index.html");
    if (stream)
    {
        // save stream data to file
        tb_transfer_done_to_url(stream, "/home/file/index.html", 0, tb_null, tb_null);
        // exit stream
        tb_stream_exit(stream);
    }
    // block: save http to file
    tb_transfer_done_url("http://www.xxxx.com/index.html", "/home/file/index.html", 0, tb_null, tb_null);
    // async: save http to file
    tb_transfer_pool_done(tb_transfer_pool(), "http://www.xxxx.com/index0.html", "/home/file/index0.html", 0, 0, tb_null, tb_null);
    tb_transfer_pool_done(tb_transfer_pool(), "http://www.xxxx.com/index1.html", "/home/file/index2.html", 0, 0, tb_null, tb_null);
    tb_transfer_pool_done(tb_transfer_pool(), "http://www.xxxx.com/index2.html", "/home/file/index3.html", 0, 0, tb_null, tb_null);
    tb_transfer_pool_done(tb_transfer_pool(), "http://www.xxxx.com/index3.html", "/home/file/index4.html", 0, 0, tb_null, tb_null);
    // ...
    // exit tbox
    tb_exit();
    return 0;
}
Definition at line 123 of file tbox.h.
Function Documentation
__tb_extern_c_enter__ tb_bool_t tb_init_ (tb_handle_t priv, tb_byte_t * data, tb_size_t size, tb_size_t mode, tb_hize_t build)
init the tbox library
Parameters
priv the platform private data pass JNIEnv* env for android pass tb_null for other platform
data the memory data for the memory pool, uses the native memory if be tb_null
size the memory size for the memory pool, uses the native memory if be zero
mode the compile mode for check tb_small and tb_debug
build the build version
Returns
tb_true or tb_false
Definition at line 130 of file tbox.c.
References tb_network_init(), tb_object_context_init(), tb_platform_init(), and tb_singleton_init().
tb_version_t const* tb_version (tb_noarg_t)
the tbox version
Returns
the tbox version