TBOX: src/tbox/container/iterator.h File Reference
iterator.h File Reference
Container
#include "prefix.h"
Data Structures
struct tb_iterator_t
the iterator type
Typedefs
typedef tb_iterator_t * tb_iterator_ref_t
the iterator ref type
typedef tb_long_t(* tb_iterator_comp_t)(tb_iterator_ref_t iterator, tb_cpointer_t ltem, tb_cpointer_t rtem)
the iterator comp func type
Enumerations
enum tb_iterator_mode_t {
TB_ITERATOR_MODE_FORWARD = 1, TB_ITERATOR_MODE_REVERSE = 2, TB_ITERATOR_MODE_RACCESS = 4, TB_ITERATOR_MODE_MUTABLE = 8,
TB_ITERATOR_MODE_READONLY = 16
}
the iterator mode type
Functions
tb_iterator_t tb_iterator_init_long (tb_long_t *data, tb_size_t size)
tb_iterator_t tb_iterator_init_size (tb_size_t *data, tb_size_t size)
tb_iterator_t tb_iterator_init_str (tb_char_t **data, tb_size_t size)
tb_iterator_t tb_iterator_init_ptr (tb_pointer_t *data, tb_size_t size)
tb_iterator_t tb_iterator_init_mem (tb_pointer_t data, tb_size_t size, tb_size_t step)
tb_size_t tb_iterator_mode (tb_iterator_ref_t iterator)
tb_size_t tb_iterator_step (tb_iterator_ref_t iterator)
tb_size_t tb_iterator_size (tb_iterator_ref_t iterator)
tb_size_t tb_iterator_head (tb_iterator_ref_t iterator)
tb_size_t tb_iterator_last (tb_iterator_ref_t iterator)
tb_size_t tb_iterator_tail (tb_iterator_ref_t iterator)
tb_size_t tb_iterator_prev (tb_iterator_ref_t iterator, tb_size_t itor)
tb_size_t tb_iterator_next (tb_iterator_ref_t iterator, tb_size_t itor)
tb_pointer_t tb_iterator_item (tb_iterator_ref_t iterator, tb_size_t itor)
tb_void_t tb_iterator_remove (tb_iterator_ref_t iterator, tb_size_t itor)
tb_void_t tb_iterator_remove_range (tb_iterator_ref_t iterator, tb_size_t prev, tb_size_t next, tb_size_t size)
tb_void_t tb_iterator_copy (tb_iterator_ref_t iterator, tb_size_t itor, tb_cpointer_t item)
tb_long_t tb_iterator_comp (tb_iterator_ref_t iterator, tb_cpointer_t ltem, tb_cpointer_t rtem)
Detailed Description
The Treasure Box Library
TBox is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 2.1 of the License, or (at your option) any later version.
TBox is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with TBox; If not, see http://www.gnu.org/licenses/
Copyright (C) 2009 - 2015, ruki All rights reserved.
Author
ruki
Definition in file iterator.h.
Enumeration Type Documentation
enum tb_iterator_mode_t
the iterator mode type
Enumerator
TB_ITERATOR_MODE_FORWARD
forward iterator
TB_ITERATOR_MODE_REVERSE
reverse iterator
TB_ITERATOR_MODE_RACCESS
random access iterator
TB_ITERATOR_MODE_MUTABLE
mutable iterator, the item of the same iterator is mutable for removing and moving, .e.g vector, hash, ...
TB_ITERATOR_MODE_READONLY
readonly iterator
Definition at line 42 of file iterator.h.
Function Documentation
tb_long_t tb_iterator_comp (tb_iterator_ref_t iterator, tb_cpointer_t ltem, tb_cpointer_t rtem)
compare the iterator item
Parameters
iterator the iterator
itor the item
item the compared item
Returns
=: 0, >: 1, <: -1
Definition at line 130 of file iterator.c.
References tb_iterator_t::comp.
Referenced by tb_binary_find(), tb_binary_find_all(), tb_bubble_sort(), tb_count(), tb_count_all(), tb_find(), tb_find_all(), tb_insert_sort(), tb_quick_sort(), tb_remove(), tb_rfind(), and tb_rfind_all().
tb_void_t tb_iterator_copy (tb_iterator_ref_t iterator, tb_size_t itor, tb_cpointer_t item)
copy the iterator item
Parameters
iterator the iterator
itor the item itor
item the copied item
Definition at line 122 of file iterator.c.
References tb_iterator_t::copy.
Referenced by tb_bubble_sort(), tb_insert_sort(), tb_quick_sort(), tb_string_pool_del(), and tb_string_pool_put().
tb_size_t tb_iterator_head (tb_iterator_ref_t iterator)
the iterator head
Parameters
iterator the iterator
Returns
the iterator head
Definition at line 58 of file iterator.c.
References tb_iterator_t::head.
Referenced by tb_binary_find_all_if(), tb_bubble_sort_all(), tb_circle_queue_head(), tb_count_all_if(), tb_find_all_if(), tb_fixed_pool_clear(), tb_heap_sort_all(), tb_heap_top(), tb_insert_sort_all(), tb_list_head(), tb_list_insert_head(), tb_list_moveto_head(), tb_list_remove_head(), tb_list_replace_head(), tb_quick_sort_all(), tb_remove_if(), tb_rfind_all_if(), tb_rwalk_all(), tb_single_list_head(), tb_single_list_replace_head(), tb_sort_all(), tb_vector_head(), and tb_walk_all().
tb_iterator_t tb_iterator_init_long (tb_long_t * data, tb_size_t size)
init the long iterator
Parameters
data the data
size the size
Returns
the iterator
Definition at line 57 of file long.c.
References tb_iterator_t::comp, tb_iterator_t::copy, tb_iterator_t::data, tb_iterator_t::head, tb_iterator_t::item, tb_iterator_t::mode, tb_iterator_t::next, tb_iterator_t::prev, tb_iterator_t::priv, tb_iterator_t::size, tb_iterator_t::step, tb_iterator_t::tail, tb_iterator_init_ptr(), TB_ITERATOR_MODE_FORWARD, TB_ITERATOR_MODE_MUTABLE, TB_ITERATOR_MODE_RACCESS, and TB_ITERATOR_MODE_REVERSE.
tb_iterator_t tb_iterator_init_mem (tb_pointer_t data, tb_size_t size, tb_size_t step)
init the memory iterator
Parameters
data the data
size the size
Returns
the iterator
Definition at line 63 of file mem.c.
References tb_iterator_t::comp, tb_iterator_t::copy, tb_iterator_t::data, tb_iterator_t::head, tb_iterator_t::item, tb_iterator_t::mode, tb_iterator_t::next, tb_iterator_t::prev, tb_iterator_t::priv, tb_iterator_t::size, tb_iterator_t::step, tb_iterator_t::tail, tb_iterator_init_ptr(), TB_ITERATOR_MODE_FORWARD, TB_ITERATOR_MODE_MUTABLE, TB_ITERATOR_MODE_RACCESS, and TB_ITERATOR_MODE_REVERSE.
tb_iterator_t tb_iterator_init_ptr (tb_pointer_t * data, tb_size_t size)
init the pointer iterator
Parameters
data the data
size the size
Returns
the iterator
Definition at line 96 of file ptr.c.
References tb_iterator_t::comp, tb_iterator_t::copy, tb_iterator_t::data, tb_iterator_t::head, tb_iterator_t::item, tb_iterator_t::mode, tb_iterator_t::next, tb_iterator_t::prev, tb_iterator_t::priv, tb_iterator_t::size, tb_iterator_t::step, tb_iterator_t::tail, TB_ITERATOR_MODE_FORWARD, TB_ITERATOR_MODE_MUTABLE, TB_ITERATOR_MODE_RACCESS, and TB_ITERATOR_MODE_REVERSE.
Referenced by tb_iterator_init_long(), tb_iterator_init_mem(), tb_iterator_init_size(), and tb_iterator_init_str().
tb_iterator_t tb_iterator_init_size (tb_size_t * data, tb_size_t size)
init the size iterator
Parameters
data the data
size the size
Returns
the iterator
Definition at line 59 of file size.c.
References tb_iterator_t::comp, tb_iterator_t::copy, tb_iterator_t::data, tb_iterator_t::head, tb_iterator_t::item, tb_iterator_t::mode, tb_iterator_t::next, tb_iterator_t::prev, tb_iterator_t::priv, tb_iterator_t::size, tb_iterator_t::step, tb_iterator_t::tail, tb_iterator_init_ptr(), TB_ITERATOR_MODE_FORWARD, TB_ITERATOR_MODE_MUTABLE, TB_ITERATOR_MODE_RACCESS, and TB_ITERATOR_MODE_REVERSE.
tb_iterator_t tb_iterator_init_str (tb_char_t ** data, tb_size_t size)
init the string iterator
Parameters
data the data
size the size
Returns
the iterator
Definition at line 44 of file str.c.
References tb_iterator_t::comp, tb_iterator_t::copy, tb_iterator_t::data, tb_iterator_t::head, tb_iterator_t::item, tb_iterator_t::mode, tb_iterator_t::next, tb_iterator_t::prev, tb_iterator_t::priv, tb_iterator_t::size, tb_iterator_t::step, tb_iterator_t::tail, tb_iterator_init_ptr(), TB_ITERATOR_MODE_FORWARD, TB_ITERATOR_MODE_MUTABLE, TB_ITERATOR_MODE_RACCESS, and TB_ITERATOR_MODE_REVERSE.
tb_pointer_t tb_iterator_item (tb_iterator_ref_t iterator, tb_size_t itor)
the iterator item
Parameters
iterator the iterator
itor the item itor
Returns
the iterator item
Definition at line 98 of file iterator.c.
References tb_iterator_t::item.
Referenced by tb_binary_find_if(), tb_bubble_sort(), tb_circle_queue_head(), tb_circle_queue_last(), tb_dns_server_get(), tb_find_if(), tb_fixed_pool_clear(), tb_heap_sort(), tb_heap_top(), tb_insert_sort(), tb_list_head(), tb_list_last(), tb_object_array_item(), tb_quick_sort(), tb_remove_if(), tb_rfind_if(), tb_single_list_head(), tb_single_list_last(), tb_string_pool_del(), tb_string_pool_put(), tb_vector_head(), and tb_vector_last().
tb_size_t tb_iterator_last (tb_iterator_ref_t iterator)
the iterator last
Parameters
iterator the iterator
Returns
the iterator last
Definition at line 66 of file iterator.c.
References tb_iterator_t::last.
Referenced by tb_circle_queue_last(), tb_list_last(), tb_list_remove_last(), tb_list_replace_last(), tb_single_list_last(), tb_single_list_replace_last(), and tb_vector_last().
tb_size_t tb_iterator_mode (tb_iterator_ref_t iterator)
the iterator mode
Parameters
iterator the iterator
Returns
the iterator mode
Definition at line 34 of file iterator.c.
References tb_iterator_t::mode.
Referenced by tb_binary_find_if(), tb_bubble_sort(), tb_count_if(), tb_find_if(), tb_heap_sort(), tb_insert_sort(), tb_quick_sort(), tb_remove_if(), tb_rfind_if(), tb_rwalk(), tb_sort(), and tb_walk().
tb_size_t tb_iterator_next (tb_iterator_ref_t iterator, tb_size_t itor)
the iterator next
Parameters
iterator the iterator
itor the item itor
Returns
the iterator next
Definition at line 90 of file iterator.c.
References tb_iterator_t::next.
Referenced by tb_bubble_sort(), tb_find_if(), tb_fixed_pool_clear(), tb_insert_sort(), tb_list_insert_next(), tb_list_moveto_next(), tb_remove_if(), tb_vector_insert_next(), and tb_vector_ninsert_next().
tb_size_t tb_iterator_prev (tb_iterator_ref_t iterator, tb_size_t itor)
the iterator prev
Parameters
iterator the iterator
itor the item itor
Returns
the iterator prev
Definition at line 82 of file iterator.c.
References tb_iterator_t::prev.
Referenced by tb_insert_sort(), and tb_rfind_if().
tb_void_t tb_iterator_remove (tb_iterator_ref_t iterator, tb_size_t itor)
remove the iterator item
Parameters
iterator the iterator
itor the item itor
Definition at line 106 of file iterator.c.
References tb_iterator_t::remove.
Referenced by tb_string_pool_del(), and tb_string_pool_put().
tb_void_t tb_iterator_remove_range (tb_iterator_ref_t iterator, tb_size_t prev, tb_size_t next, tb_size_t size)
remove the iterator items from range(prev, next)
Parameters
iterator the iterator
prev the prev item
next the next item
size the removed size
Definition at line 114 of file iterator.c.
References tb_iterator_t::remove_range.
Referenced by tb_remove_if().
tb_size_t tb_iterator_size (tb_iterator_ref_t iterator)
the iterator size
Parameters
iterator the iterator
Returns
the iterator size
Definition at line 50 of file iterator.c.
References tb_iterator_t::size.
tb_size_t tb_iterator_step (tb_iterator_ref_t iterator)
the iterator step
Parameters
iterator the iterator
Returns
the iterator step
Definition at line 42 of file iterator.c.
References tb_iterator_t::step.
Referenced by tb_bubble_sort(), tb_heap_sort(), tb_insert_sort(), and tb_quick_sort().
tb_size_t tb_iterator_tail (tb_iterator_ref_t iterator)
the iterator tail
Parameters
iterator the iterator
Returns
the iterator tail
Definition at line 74 of file iterator.c.
References tb_iterator_t::tail.
Referenced by tb_binary_find_all_if(), tb_bubble_sort_all(), tb_count_all_if(), tb_find_all_if(), tb_fixed_pool_clear(), tb_heap_sort_all(), tb_insert_sort_all(), tb_list_insert_prev(), tb_list_insert_tail(), tb_list_moveto_tail(), tb_list_remove(), tb_quick_sort_all(), tb_remove_if(), tb_rfind_all_if(), tb_rwalk_all(), tb_single_list_insert_head(), tb_single_list_insert_next(), tb_single_list_insert_tail(), tb_sort_all(), tb_string_pool_del(), tb_string_pool_put(), tb_timer_task_kill(), and tb_walk_all().