TBOX: src/tbox/object/data.h File Reference
data.h File Reference
Object
#include "prefix.h"
Functions
__tb_extern_c_enter__
tb_object_ref_t tb_object_data_init_from_url (tb_char_t const *url)
tb_object_ref_t tb_object_data_init_from_data (tb_pointer_t data, tb_size_t size)
tb_object_ref_t tb_object_data_init_from_buffer (tb_buffer_t *buffer)
tb_pointer_t tb_object_data_getp (tb_object_ref_t data)
tb_bool_t tb_object_data_setp (tb_object_ref_t data, tb_pointer_t addr, tb_size_t size)
tb_size_t tb_object_data_size (tb_object_ref_t data)
tb_buffer_t * tb_object_data_buffer (tb_object_ref_t data)
tb_bool_t tb_object_data_writ_to_url (tb_object_ref_t data, tb_char_t const *url)
Detailed Description
The Treasure Box Library
TBox is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 2.1 of the License, or (at your option) any later version.
TBox is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with TBox; If not, see http://www.gnu.org/licenses/
Copyright (C) 2009 - 2015, ruki All rights reserved.
Author
ruki
Definition in file data.h.
Function Documentation
tb_buffer_t* tb_object_data_buffer (tb_object_ref_t data)
the data buffer
Parameters
data the data object
Returns
the data buffer
Definition at line 225 of file data.c.
tb_pointer_t tb_object_data_getp (tb_object_ref_t data)
get the data
Parameters
data the data object
Returns
the data address
Definition at line 195 of file data.c.
References tb_buffer_data().
Referenced by tb_object_data_writ_to_url(), and tb_object_dump().
tb_object_ref_t tb_object_data_init_from_buffer (tb_buffer_t * buffer)
init data from buffer
Parameters
buffer the buffer
Returns
the data object
Definition at line 176 of file data.c.
References tb_buffer_init(), and tb_buffer_memcpy().
tb_object_ref_t tb_object_data_init_from_data (tb_pointer_t data, tb_size_t size)
init data from data
Parameters
data the data
size the size
Returns
the data object
Definition at line 157 of file data.c.
References tb_buffer_init(), and tb_buffer_memncpy().
Referenced by tb_object_data(), and tb_object_data_init_from_url().
__tb_extern_c_enter__ tb_object_ref_t tb_object_data_init_from_url (tb_char_t const * url)
init data from url
Parameters
data the data
size the size
Returns
the data object
Definition at line 120 of file data.c.
References tb_object_data_init_from_data(), tb_stream_bread(), tb_stream_exit(), tb_stream_init_from_url(), tb_stream_open(), and tb_stream_size().
tb_bool_t tb_object_data_setp (tb_object_ref_t data, tb_pointer_t addr, tb_size_t size)
set the data
Parameters
data the data object
addr the data address
size the data size
Returns
tb_true or tb_false
Definition at line 204 of file data.c.
References tb_buffer_memncpy().
tb_size_t tb_object_data_size (tb_object_ref_t data)
the data size
Parameters
data the data object
Returns
the data size
Definition at line 216 of file data.c.
References tb_buffer_size().
Referenced by tb_object_data_writ_to_url(), and tb_object_dump().
tb_bool_t tb_object_data_writ_to_url (tb_object_ref_t data, tb_char_t const * url)
writ data to url
Parameters
data the data object
Returns
tb_true or tb_false
Definition at line 234 of file data.c.
References TB_FILE_MODE_CREAT, TB_FILE_MODE_TRUNC, TB_FILE_MODE_WO, tb_object_data_getp(), tb_object_data_size(), tb_stream_bwrit(), tb_stream_ctrl(), tb_stream_exit(), tb_stream_init_from_url(), tb_stream_open(), and tb_stream_type().