TBOX: src/tbox/platform/ltimer.h File Reference
ltimer.h File Reference
Platform
#include "prefix.h"
#include "timer.h"
Data Structures
struct tb_ltimer_ref_t
the ltimer ref type
struct tb_ltimer_task_ref_t
the ltimer task ref type
Typedefs
typedef tb_timer_task_func_t tb_ltimer_task_func_t
the ltimer task func type
Enumerations
enum tb_ltimer_tick_e { TB_LTIMER_TICK_100MS = 100, TB_LTIMER_TICK_S = 1000, TB_LTIMER_TICK_M = 60000, TB_LTIMER_TICK_H = 3600000 }
the timer tick enum
Functions
tb_ltimer_ref_t tb_ltimer_init (tb_size_t maxn, tb_size_t tick, tb_bool_t ctime)
tb_void_t tb_ltimer_exit (tb_ltimer_ref_t timer)
tb_void_t tb_ltimer_clear (tb_ltimer_ref_t timer)
tb_size_t tb_ltimer_limit (tb_ltimer_ref_t timer)
tb_size_t tb_ltimer_delay (tb_ltimer_ref_t timer)
tb_bool_t tb_ltimer_spak (tb_ltimer_ref_t timer)
tb_void_t tb_ltimer_loop (tb_ltimer_ref_t timer)
tb_void_t tb_ltimer_task_post (tb_ltimer_ref_t timer, tb_size_t delay, tb_bool_t repeat, tb_ltimer_task_func_t func, tb_cpointer_t priv)
tb_void_t tb_ltimer_task_post_at (tb_ltimer_ref_t timer, tb_hize_t when, tb_size_t period, tb_bool_t repeat, tb_ltimer_task_func_t func, tb_cpointer_t priv)
tb_void_t tb_ltimer_task_post_after (tb_ltimer_ref_t timer, tb_hize_t after, tb_size_t period, tb_bool_t repeat, tb_ltimer_task_func_t func, tb_cpointer_t priv)
tb_ltimer_task_ref_t tb_ltimer_task_init (tb_ltimer_ref_t timer, tb_size_t delay, tb_bool_t repeat, tb_ltimer_task_func_t func, tb_cpointer_t priv)
tb_ltimer_task_ref_t tb_ltimer_task_init_at (tb_ltimer_ref_t timer, tb_hize_t when, tb_size_t period, tb_bool_t repeat, tb_ltimer_task_func_t func, tb_cpointer_t priv)
tb_ltimer_task_ref_t tb_ltimer_task_init_after (tb_ltimer_ref_t timer, tb_hize_t after, tb_size_t period, tb_bool_t repeat, tb_ltimer_task_func_t func, tb_cpointer_t priv)
tb_void_t tb_ltimer_task_exit (tb_ltimer_ref_t timer, tb_ltimer_task_ref_t task)
tb_void_t tb_ltimer_task_kill (tb_ltimer_ref_t timer, tb_ltimer_task_ref_t task)
Detailed Description
The Treasure Box Library
TBox is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 2.1 of the License, or (at your option) any later version.
TBox is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with TBox; If not, see http://www.gnu.org/licenses/
Copyright (C) 2009 - 2015, ruki All rights reserved.
Author
ruki
Definition in file ltimer.h.
Function Documentation
tb_void_t tb_ltimer_clear (tb_ltimer_ref_t timer)
clear timer
Parameters
timer the timer
Definition at line 421 of file ltimer.c.
References tb_fixed_pool_clear(), and tb_vector_clear().
tb_size_t tb_ltimer_delay (tb_ltimer_ref_t timer)
the timer delay for spak
Parameters
timer the timer
Returns
the timer delay, (tb_size_t)-1: error or no task
Definition at line 458 of file ltimer.c.
Referenced by tb_ltimer_loop().
tb_void_t tb_ltimer_exit (tb_ltimer_ref_t timer)
exit timer
Parameters
timer the timer
Definition at line 375 of file ltimer.c.
References tb_fixed_pool_exit(), and tb_vector_exit().
Referenced by tb_ltimer_init().
tb_ltimer_ref_t tb_ltimer_init (tb_size_t maxn, tb_size_t tick, tb_bool_t ctime)
init timer
lower tick and limit range, but faster
Parameters
maxn the timer maxn
tick the timer tick
ctime using ctime?
Returns
the timer
Definition at line 323 of file ltimer.c.
References tb_fixed_pool_init(), tb_item_func_ptr(), tb_lock_profiler(), tb_lock_profiler_register(), tb_ltimer_exit(), and tb_vector_init().
tb_size_t tb_ltimer_limit (tb_ltimer_ref_t timer)
the timer limit
Parameters
timer the timer
Returns
the timer limit range: [now, now + limit)
Definition at line 449 of file ltimer.c.
tb_void_t tb_ltimer_loop (tb_ltimer_ref_t timer)
loop timer for the external thread
tb_void_t tb_ltimer_thread(tb_cpointer_t priv)
{
     tb_ltimer_loop(timer);
}
Parameters
timer the timer
Returns
tb_true or tb_false
Definition at line 557 of file ltimer.c.
References tb_cache_time_spak(), tb_ltimer_delay(), and tb_ltimer_spak().
tb_bool_t tb_ltimer_spak (tb_ltimer_ref_t timer)
spak timer for the external loop at the single thread
tb_void_t tb_ltimer_loop()
{
     while (1)
     {
         // wait
         wait(tb_ltimer_delay(timer))
         // spak timer
         tb_ltimer_spak(timer);
     }
}
Parameters
timer the timer
Returns
tb_true or tb_false
Definition at line 467 of file ltimer.c.
References tb_fixed_pool_size(), tb_vector_clear(), tb_vector_ref_t, tb_vector_size(), and tb_walk_all().
Referenced by tb_ltimer_loop().
tb_void_t tb_ltimer_task_exit (tb_ltimer_ref_t timer, tb_ltimer_task_ref_t task)
exit timer task, the task will be not called if have been not called
Parameters
timer the timer
task the timer task
Definition at line 696 of file ltimer.c.
tb_ltimer_task_ref_t tb_ltimer_task_init (tb_ltimer_ref_t timer, tb_size_t delay, tb_bool_t repeat, tb_ltimer_task_func_t func, tb_cpointer_t priv)
init and post timer task after delay and need remove it manually
Parameters
timer the timer
delay the delay time, ms
repeat is repeat?
func the timer func
priv the timer priv
Returns
the timer task
Definition at line 586 of file ltimer.c.
References tb_ltimer_task_init_at().
tb_ltimer_task_ref_t tb_ltimer_task_init_after (tb_ltimer_ref_t timer, tb_hize_t after, tb_size_t period, tb_bool_t repeat, tb_ltimer_task_func_t func, tb_cpointer_t priv)
init and post timer task after the relative time and need remove it manually
Parameters
timer the timer
after the after time, ms
period the period time, ms
repeat is repeat?
func the timer func
priv the timer priv
Returns
the timer task
Definition at line 635 of file ltimer.c.
References tb_ltimer_task_init_at().
tb_ltimer_task_ref_t tb_ltimer_task_init_at (tb_ltimer_ref_t timer, tb_hize_t when, tb_size_t period, tb_bool_t repeat, tb_ltimer_task_func_t func, tb_cpointer_t priv)
init and post timer task at the absolute time and need remove it manually
Parameters
timer the timer
when the absolute time, ms
period the period time, ms
repeat is repeat?
func the timer func
priv the timer priv
Returns
the timer task
Definition at line 595 of file ltimer.c.
Referenced by tb_ltimer_task_init(), and tb_ltimer_task_init_after().
tb_void_t tb_ltimer_task_kill (tb_ltimer_ref_t timer, tb_ltimer_task_ref_t task)
kill timer task, the task will be called immediately if have been not called
Parameters
timer the timer
task the timer task
Definition at line 725 of file ltimer.c.
tb_void_t tb_ltimer_task_post (tb_ltimer_ref_t timer, tb_size_t delay, tb_bool_t repeat, tb_ltimer_task_func_t func, tb_cpointer_t priv)
post timer task after delay and will be auto-remove it after be expired
Parameters
timer the timer
delay the delay time, ms
repeat is repeat?
func the timer func
priv the timer priv
Definition at line 644 of file ltimer.c.
References tb_ltimer_task_post_at().
tb_void_t tb_ltimer_task_post_after (tb_ltimer_ref_t timer, tb_hize_t after, tb_size_t period, tb_bool_t repeat, tb_ltimer_task_func_t func, tb_cpointer_t priv)
run timer task after the relative time and will be auto-remove it after be expired
Parameters
timer the timer
after the after time, ms
period the period time, ms
repeat is repeat?
func the timer func
priv the timer priv
Definition at line 687 of file ltimer.c.
References tb_ltimer_task_post_at().
tb_void_t tb_ltimer_task_post_at (tb_ltimer_ref_t timer, tb_hize_t when, tb_size_t period, tb_bool_t repeat, tb_ltimer_task_func_t func, tb_cpointer_t priv)
post timer task at the absolute time and will be auto-remove it after be expired
Parameters
timer the timer
when the absolute time, ms
period the period time, ms
repeat is repeat?
func the timer func
priv the timer priv
Definition at line 653 of file ltimer.c.
Referenced by tb_ltimer_task_post(), and tb_ltimer_task_post_after().