TBOX: src/tbox/utils/trace.c File Reference
trace.c File Reference
Utils
#include "trace.h"
#include "../libc/libc.h"
#include "../platform/platform.h"
Macros
#define TB_TRACE_LINE_MAXN (8192 << 1)
Functions
tb_bool_t tb_trace_init ()
tb_void_t tb_trace_exit ()
tb_size_t tb_trace_mode ()
tb_bool_t tb_trace_mode_set (tb_size_t mode)
tb_handle_t tb_trace_file ()
tb_bool_t tb_trace_file_set (tb_file_ref_t file)
tb_bool_t tb_trace_file_set_path (tb_char_t const *path, tb_bool_t bappend)
tb_void_t tb_trace_done_with_args (tb_char_t const *prefix, tb_char_t const *module, tb_char_t const *format, tb_va_list_t args)
tb_void_t tb_trace_done (tb_char_t const *prefix, tb_char_t const *module, tb_char_t const *format,...)
tb_void_t tb_trace_tail (tb_char_t const *format,...)
tb_void_t tb_trace_sync ()
Detailed Description
The Treasure Box Library
TBox is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 2.1 of the License, or (at your option) any later version.
TBox is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with TBox; If not, see http://www.gnu.org/licenses/
Copyright (C) 2009 - 2015, ruki All rights reserved.
Author
ruki
Definition in file trace.c.
Function Documentation
tb_void_t tb_trace_done (tb_char_t const * prefix, tb_char_t const * module, tb_char_t const * format, ...)
done trace
Parameters
prefix the trace prefix
module the trace module
format the trace format
Definition at line 247 of file trace.c.
References tb_trace_done_with_args().
tb_void_t tb_trace_done_with_args (tb_char_t const * prefix, tb_char_t const * module, tb_char_t const * format, tb_va_list_t args)
done trace with arguments
Parameters
prefix the trace prefix
module the trace module
format the trace format
args the trace arguments
Definition at line 179 of file trace.c.
References tb_file_writ(), tb_localtime(), tb_print(), tb_snprintf(), tb_thread_self(), and tb_vsnprintf().
Referenced by tb_trace_done().
tb_bool_t tb_trace_file_set (tb_file_ref_t file)
set the trace file
Parameters
file the trace file handle
Returns
tb_true or tb_false
Definition at line 134 of file trace.c.
References tb_file_exit().
tb_bool_t tb_trace_file_set_path (tb_char_t const * path, tb_bool_t bappend)
set the trace file path
Parameters
path the trace file path
bappend is appended?
Returns
tb_true or tb_false
Definition at line 155 of file trace.c.
References tb_file_exit(), tb_file_init(), TB_FILE_MODE_APPEND, TB_FILE_MODE_BINARY, TB_FILE_MODE_CREAT, TB_FILE_MODE_RW, and TB_FILE_MODE_TRUNC.
tb_bool_t tb_trace_mode_set (tb_size_t mode)
set the trace mode
Parameters
mode the trace mode
Returns
tb_true or tb_false
Definition at line 106 of file trace.c.
tb_void_t tb_trace_tail (tb_char_t const * format, ...)
done trace tail
Parameters
format the trace format
Definition at line 262 of file trace.c.
References tb_file_writ(), tb_print(), and tb_vsnprintf().