TBOX: src/tbox/platform/cache_time.h File Reference
cache_time.h File Reference
Platform
#include "prefix.h"
Functions
__tb_extern_c_enter__ tb_time_t tb_cache_time (tb_noarg_t)
tb_hong_t tb_cache_time_spak (tb_noarg_t)
tb_hong_t tb_cache_time_mclock (tb_noarg_t)
tb_hong_t tb_cache_time_clock (tb_noarg_t)
Detailed Description
The Treasure Box Library
TBox is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 2.1 of the License, or (at your option) any later version.
TBox is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with TBox; If not, see http://www.gnu.org/licenses/
Copyright (C) 2009 - 2015, ruki All rights reserved.
Author
ruki
Definition in file cache_time.h.
Function Documentation
__tb_extern_c_enter__ tb_time_t tb_cache_time (tb_noarg_t)
the cached time, like tb_time
lower accuracy and faster
Returns
the now time, s
tb_hong_t tb_cache_time_clock (tb_noarg_t)
the cached s-clock
lower accuracy and faster
Returns
the now s-clock
tb_hong_t tb_cache_time_mclock (tb_noarg_t)
the cached ms-clock
lower accuracy and faster
Returns
the now ms-clock
Referenced by tb_aico_task_run_(), and tb_aicp_time().
tb_hong_t tb_cache_time_spak (tb_noarg_t)
spak cached time
update the cached time for the external loop thread
Returns
the now ms-clock
Referenced by tb_aicp_loop_util(), tb_aicp_wait_all(), tb_cookies_get(), tb_ltimer_loop(), tb_platform_init(), tb_thread_pool_task_wait(), tb_thread_pool_task_wait_all(), tb_timer_loop(), tb_transfer_done(), and tb_transfer_pool_wait_all().