TBOX: src/algorithm/pfind.h File Reference
pfind.h File Reference
Algorithm
#include "prefix.h"
Functions
tb_size_t tb_pfind (tb_iterator_t *iterator, tb_size_t *pprev, tb_size_t head, tb_size_t tail, tb_cpointer_t data)
tb_size_t tb_pfind_all (tb_iterator_t *iterator, tb_size_t *pprev, tb_cpointer_t data)
tb_size_t tb_binary_pfind (tb_iterator_t *iterator, tb_size_t *pprev, tb_size_t head, tb_size_t tail, tb_cpointer_t data)
tb_size_t tb_binary_pfind_all (tb_iterator_t *iterator, tb_size_t *pprev, tb_cpointer_t data)
Detailed Description
The Treasure Box Library
TBox is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 2.1 of the License, or (at your option) any later version.
TBox is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with TBox; If not, see http://www.gnu.org/licenses/
Copyright (C) 2009 - 2012, ruki All rights reserved.
Author
ruki
Definition in file pfind.h.
Function Documentation
tb_size_t tb_binary_pfind (tb_iterator_t * iterator, tb_size_t * pprev, tb_size_t head, tb_size_t tail, tb_cpointer_t data)
the binary finder for ascending with prev
find the prev item if be not finded, the prev is tail if be finded
Note
the container must be sorted
Parameters
iterator the iterator
pprev the iterator prev pointer
head the iterator head
tail the iterator tail
data the finded data
Returns
the iterator itor
Definition at line 66 of file pfind.c.
References tb_iterator_t::mode, tb_iterator_comp(), tb_iterator_item(), TB_ITERATOR_MODE_RACCESS, and tb_pfind().
Referenced by tb_binary_pfind_all().
tb_size_t tb_binary_pfind_all (tb_iterator_t * iterator, tb_size_t * pprev, tb_cpointer_t data)
the binary finder for all with prev
find the prev item if be not finded, the prev is tail if be finded
Note
the container must be sorted
Parameters
iterator the iterator
pprev the iterator prev pointer
data the finded data
Returns
the iterator itor
Definition at line 112 of file pfind.c.
References tb_binary_pfind(), tb_iterator_head(), and tb_iterator_tail().
tb_size_t tb_pfind (tb_iterator_t * iterator, tb_size_t * pprev, tb_size_t head, tb_size_t tail, tb_cpointer_t data)
the finder with prev
find the prev item if be not finded, the prev is tail if be finded
Note
the container must be sorted
Parameters
iterator the iterator
pprev the iterator prev pointer
head the iterator head
tail the iterator tail
data the finded data
Returns
the iterator itor
Definition at line 34 of file pfind.c.
References tb_iterator_t::mode, tb_iterator_comp(), tb_iterator_item(), TB_ITERATOR_MODE_FORWARD, and tb_iterator_next().
Referenced by tb_binary_pfind(), and tb_pfind_all().
tb_size_t tb_pfind_all (tb_iterator_t * iterator, tb_size_t * pprev, tb_cpointer_t data)
the finder for all with prev
find the prev item if be not finded, the prev is tail if be finded
Note
the container must be sorted
Parameters
iterator the iterator
pprev the iterator prev pointer
data the finded data
Returns
the iterator itor
Definition at line 62 of file pfind.c.
References tb_iterator_head(), tb_iterator_tail(), and tb_pfind().