TBOX: src/tbox/stream/stream.h File Reference
stream.h File Reference
Stream
#include "prefix.h"
#include "async_stream.h"
#include "static_stream.h"
#include "transfer.h"
#include "transfer_pool.h"
#include "filter.h"
Macros
#define TB_STREAM_BLOCK_MAXN (8192)
#define tb_stream_bread_u16_ne(stream) tb_stream_bread_u16_le(stream)
#define tb_stream_bread_s16_ne(stream) tb_stream_bread_s16_le(stream)
#define tb_stream_bread_u24_ne(stream) tb_stream_bread_u24_le(stream)
#define tb_stream_bread_s24_ne(stream) tb_stream_bread_s24_le(stream)
#define tb_stream_bread_u32_ne(stream) tb_stream_bread_u32_le(stream)
#define tb_stream_bread_s32_ne(stream) tb_stream_bread_s32_le(stream)
#define tb_stream_bread_u64_ne(stream) tb_stream_bread_u64_le(stream)
#define tb_stream_bread_s64_ne(stream) tb_stream_bread_s64_le(stream)
#define tb_stream_bwrit_u16_ne(stream, val) tb_stream_bwrit_u16_le(stream, val)
#define tb_stream_bwrit_s16_ne(stream, val) tb_stream_bwrit_s16_le(stream, val)
#define tb_stream_bwrit_u24_ne(stream, val) tb_stream_bwrit_u24_le(stream, val)
#define tb_stream_bwrit_s24_ne(stream, val) tb_stream_bwrit_s24_le(stream, val)
#define tb_stream_bwrit_u32_ne(stream, val) tb_stream_bwrit_u32_le(stream, val)
#define tb_stream_bwrit_s32_ne(stream, val) tb_stream_bwrit_s32_le(stream, val)
#define tb_stream_bwrit_u64_ne(stream, val) tb_stream_bwrit_u64_le(stream, val)
#define tb_stream_bwrit_s64_ne(stream, val) tb_stream_bwrit_s64_le(stream, val)
#define tb_stream_bread_double_nbe(stream) tb_stream_bread_double_lbe(stream)
#define tb_stream_bread_double_nle(stream) tb_stream_bread_double_lle(stream)
#define tb_stream_bwrit_double_nbe(stream, val) tb_stream_bwrit_double_lbe(stream, val)
#define tb_stream_bwrit_double_nle(stream, val) tb_stream_bwrit_double_lle(stream, val)
#define tb_stream_bread_float_ne(stream) tb_stream_bread_float_le(stream)
#define tb_stream_bwrit_float_ne(stream, val) tb_stream_bwrit_float_le(stream, val)
#define tb_stream_bread_double_nne(stream) tb_stream_bread_double_nle(stream)
#define tb_stream_bread_double_bne(stream) tb_stream_bread_double_ble(stream)
#define tb_stream_bread_double_lne(stream) tb_stream_bread_double_lle(stream)
#define tb_stream_bwrit_double_nne(stream, val) tb_stream_bwrit_double_nle(stream, val)
#define tb_stream_bwrit_double_bne(stream, val) tb_stream_bwrit_double_ble(stream, val)
#define tb_stream_bwrit_double_lne(stream, val) tb_stream_bwrit_double_lle(stream, val)
Functions
tb_stream_ref_t tb_stream_init (tb_size_t type, tb_size_t type_size, tb_size_t cache, tb_bool_t(*open)(tb_stream_ref_t stream), tb_bool_t(*clos)(tb_stream_ref_t stream), tb_void_t(*exit)(tb_stream_ref_t stream), tb_bool_t(*ctrl)(tb_stream_ref_t stream, tb_size_t ctrl, tb_va_list_t args), tb_long_t(*wait)(tb_stream_ref_t stream, tb_size_t wait, tb_long_t timeout), tb_long_t(*read)(tb_stream_ref_t stream, tb_byte_t *data, tb_size_t size), tb_long_t(*writ)(tb_stream_ref_t stream, tb_byte_t const *data, tb_size_t size), tb_bool_t(*seek)(tb_stream_ref_t stream, tb_hize_t offset), tb_bool_t(*sync)(tb_stream_ref_t stream, tb_bool_t bclosing), tb_void_t(*kill)(tb_stream_ref_t stream))
tb_stream_ref_t tb_stream_init_data (tb_noarg_t)
tb_stream_ref_t tb_stream_init_file (tb_noarg_t)
tb_stream_ref_t tb_stream_init_sock (tb_noarg_t)
tb_stream_ref_t tb_stream_init_http (tb_noarg_t)
tb_stream_ref_t tb_stream_init_filter (tb_noarg_t)
tb_void_t tb_stream_exit (tb_stream_ref_t stream)
tb_stream_ref_t tb_stream_init_from_url (tb_char_t const *url)
tb_stream_ref_t tb_stream_init_from_data (tb_byte_t const *data, tb_size_t size)
tb_stream_ref_t tb_stream_init_from_file (tb_char_t const *path, tb_size_t mode)
tb_stream_ref_t tb_stream_init_from_sock (tb_char_t const *host, tb_uint16_t port, tb_size_t type, tb_bool_t bssl)
tb_stream_ref_t tb_stream_init_from_http (tb_char_t const *host, tb_uint16_t port, tb_char_t const *path, tb_bool_t bssl)
tb_stream_ref_t tb_stream_init_filter_from_null (tb_stream_ref_t stream)
tb_stream_ref_t tb_stream_init_filter_from_zip (tb_stream_ref_t stream, tb_size_t algo, tb_size_t action)
tb_stream_ref_t tb_stream_init_filter_from_cache (tb_stream_ref_t stream, tb_size_t size)
tb_stream_ref_t tb_stream_init_filter_from_charset (tb_stream_ref_t stream, tb_size_t fr, tb_size_t to)
tb_stream_ref_t tb_stream_init_filter_from_chunked (tb_stream_ref_t stream, tb_bool_t dechunked)
tb_long_t tb_stream_wait (tb_stream_ref_t stream, tb_size_t wait, tb_long_t timeout)
tb_size_t tb_stream_state (tb_stream_ref_t stream)
tb_void_t tb_stream_state_set (tb_stream_ref_t stream, tb_size_t state)
tb_size_t tb_stream_type (tb_stream_ref_t stream)
tb_hong_t tb_stream_size (tb_stream_ref_t stream)
tb_hize_t tb_stream_left (tb_stream_ref_t stream)
tb_bool_t tb_stream_beof (tb_stream_ref_t stream)
tb_hize_t tb_stream_offset (tb_stream_ref_t stream)
tb_bool_t tb_stream_is_opened (tb_stream_ref_t stream)
tb_bool_t tb_stream_is_closed (tb_stream_ref_t stream)
tb_bool_t tb_stream_is_killed (tb_stream_ref_t stream)
tb_url_t * tb_stream_url (tb_stream_ref_t stream)
tb_long_t tb_stream_timeout (tb_stream_ref_t stream)
tb_bool_t tb_stream_ctrl (tb_stream_ref_t stream, tb_size_t ctrl,...)
tb_bool_t tb_stream_ctrl_with_args (tb_stream_ref_t stream, tb_size_t ctrl, tb_va_list_t args)
tb_void_t tb_stream_kill (tb_stream_ref_t stream)
tb_bool_t tb_stream_open (tb_stream_ref_t stream)
tb_bool_t tb_stream_clos (tb_stream_ref_t stream)
tb_long_t tb_stream_read (tb_stream_ref_t stream, tb_byte_t *data, tb_size_t size)
tb_long_t tb_stream_writ (tb_stream_ref_t stream, tb_byte_t const *data, tb_size_t size)
tb_bool_t tb_stream_bread (tb_stream_ref_t stream, tb_byte_t *data, tb_size_t size)
tb_bool_t tb_stream_bwrit (tb_stream_ref_t stream, tb_byte_t const *data, tb_size_t size)
tb_bool_t tb_stream_sync (tb_stream_ref_t stream, tb_bool_t bclosing)
tb_bool_t tb_stream_need (tb_stream_ref_t stream, tb_byte_t **data, tb_size_t size)
tb_bool_t tb_stream_seek (tb_stream_ref_t stream, tb_hize_t offset)
tb_bool_t tb_stream_skip (tb_stream_ref_t stream, tb_hize_t size)
tb_long_t tb_stream_printf (tb_stream_ref_t stream, tb_char_t const *fmt,...)
tb_long_t tb_stream_bread_line (tb_stream_ref_t stream, tb_char_t *data, tb_size_t size)
tb_long_t tb_stream_bwrit_line (tb_stream_ref_t stream, tb_char_t *data, tb_size_t size)
tb_uint8_t tb_stream_bread_u8 (tb_stream_ref_t stream)
tb_sint8_t tb_stream_bread_s8 (tb_stream_ref_t stream)
tb_uint16_t tb_stream_bread_u16_le (tb_stream_ref_t stream)
tb_sint16_t tb_stream_bread_s16_le (tb_stream_ref_t stream)
tb_uint32_t tb_stream_bread_u24_le (tb_stream_ref_t stream)
tb_sint32_t tb_stream_bread_s24_le (tb_stream_ref_t stream)
tb_uint32_t tb_stream_bread_u32_le (tb_stream_ref_t stream)
tb_sint32_t tb_stream_bread_s32_le (tb_stream_ref_t stream)
tb_uint64_t tb_stream_bread_u64_le (tb_stream_ref_t stream)
tb_sint64_t tb_stream_bread_s64_le (tb_stream_ref_t stream)
tb_uint16_t tb_stream_bread_u16_be (tb_stream_ref_t stream)
tb_sint16_t tb_stream_bread_s16_be (tb_stream_ref_t stream)
tb_uint32_t tb_stream_bread_u24_be (tb_stream_ref_t stream)
tb_sint32_t tb_stream_bread_s24_be (tb_stream_ref_t stream)
tb_uint32_t tb_stream_bread_u32_be (tb_stream_ref_t stream)
tb_sint32_t tb_stream_bread_s32_be (tb_stream_ref_t stream)
tb_uint64_t tb_stream_bread_u64_be (tb_stream_ref_t stream)
tb_sint64_t tb_stream_bread_s64_be (tb_stream_ref_t stream)
tb_bool_t tb_stream_bwrit_u8 (tb_stream_ref_t stream, tb_uint8_t val)
tb_bool_t tb_stream_bwrit_s8 (tb_stream_ref_t stream, tb_sint8_t val)
tb_bool_t tb_stream_bwrit_u16_le (tb_stream_ref_t stream, tb_uint16_t val)
tb_bool_t tb_stream_bwrit_s16_le (tb_stream_ref_t stream, tb_sint16_t val)
tb_bool_t tb_stream_bwrit_u24_le (tb_stream_ref_t stream, tb_uint32_t val)
tb_bool_t tb_stream_bwrit_s24_le (tb_stream_ref_t stream, tb_sint32_t val)
tb_bool_t tb_stream_bwrit_u32_le (tb_stream_ref_t stream, tb_uint32_t val)
tb_bool_t tb_stream_bwrit_s32_le (tb_stream_ref_t stream, tb_sint32_t val)
tb_bool_t tb_stream_bwrit_u64_le (tb_stream_ref_t stream, tb_uint64_t val)
tb_bool_t tb_stream_bwrit_s64_le (tb_stream_ref_t stream, tb_sint64_t val)
tb_bool_t tb_stream_bwrit_u16_be (tb_stream_ref_t stream, tb_uint16_t val)
tb_bool_t tb_stream_bwrit_s16_be (tb_stream_ref_t stream, tb_sint16_t val)
tb_bool_t tb_stream_bwrit_u24_be (tb_stream_ref_t stream, tb_uint32_t val)
tb_bool_t tb_stream_bwrit_s24_be (tb_stream_ref_t stream, tb_sint32_t val)
tb_bool_t tb_stream_bwrit_u32_be (tb_stream_ref_t stream, tb_uint32_t val)
tb_bool_t tb_stream_bwrit_s32_be (tb_stream_ref_t stream, tb_sint32_t val)
tb_bool_t tb_stream_bwrit_u64_be (tb_stream_ref_t stream, tb_uint64_t val)
tb_bool_t tb_stream_bwrit_s64_be (tb_stream_ref_t stream, tb_sint64_t val)
tb_float_t tb_stream_bread_float_le (tb_stream_ref_t stream)
tb_float_t tb_stream_bread_float_be (tb_stream_ref_t stream)
tb_double_t tb_stream_bread_double_ble (tb_stream_ref_t stream)
tb_double_t tb_stream_bread_double_bbe (tb_stream_ref_t stream)
tb_double_t tb_stream_bread_double_lle (tb_stream_ref_t stream)
tb_double_t tb_stream_bread_double_lbe (tb_stream_ref_t stream)
tb_bool_t tb_stream_bwrit_float_le (tb_stream_ref_t stream, tb_float_t val)
tb_bool_t tb_stream_bwrit_float_be (tb_stream_ref_t stream, tb_float_t val)
tb_bool_t tb_stream_bwrit_double_ble (tb_stream_ref_t stream, tb_double_t val)
tb_bool_t tb_stream_bwrit_double_bbe (tb_stream_ref_t stream, tb_double_t val)
tb_bool_t tb_stream_bwrit_double_lle (tb_stream_ref_t stream, tb_double_t val)
tb_bool_t tb_stream_bwrit_double_lbe (tb_stream_ref_t stream, tb_double_t val)
Detailed Description
The Treasure Box Library
TBox is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 2.1 of the License, or (at your option) any later version.
TBox is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with TBox; If not, see http://www.gnu.org/licenses/
Copyright (C) 2009 - 2015, ruki All rights reserved.
Author
ruki
Definition in file stream.h.
Macro Definition Documentation
#define TB_STREAM_BLOCK_MAXN (8192)
architecture
                            wait - loop
                             |
                             |                                          - data
                           [aioo]                                       |
                     --— stream -----— stream --------------------— file
                     |                        |                         |
                                                  - sock
                                                  - http
                                    - charset
                        - filter -  - chunked
transfer ------—
                                    - cache
                      |                                   |
                     |                                    - zip
                     |
                     --— stream
                                              - loop
                                       [asio] |
                                        aicp -| loop
                                         |    |
                                         |    - ...                                  - data
                                       [aico]                                        |
                  -------------------- async_stream -------- async_stream ------------ file
                  |                                       |                          |
                  |                                       |                          - sock
  ----------------                                        |                          |
  |                                                       |                          - http
                --—  transfer                                                    |           - charset
               |           |                                                       |          |
               |           -------------—                                        - filter - |- chunked
               |                           |                                            |     |
 transfer_pool  --—  transfer            |                                            |     |- cache
               |                           |                                            |     |
               |                           |                                            |      - zip
               |                           |                                            |
                --—   ...                |                                            |
                                           |                                         static_stream - [data, size]
                                           |
                                           -----------------— async_stream
url:
data://base64
file://path or unix path: e.g. /root/xxxx/file
sock://host:port?tcp=
sock://host:port?udp=
socks://host:port
http://host:port/path?arg0=&arg1=...
https://host:port/path?arg0=&arg1=...
Definition at line 105 of file stream.h.
Referenced by tb_stream_printf(), tb_stream_seek(), and tb_transfer_done().
Function Documentation
tb_bool_t tb_stream_beof (tb_stream_ref_t stream)
the stream is end?
Parameters
stream the stream
Returns
tb_true or tb_false
Definition at line 286 of file stream.c.
References tb_stream_offset(), and tb_stream_size().
Referenced by tb_dump_data_from_stream(), and tb_stream_bread_line().
tb_bool_t tb_stream_bread (tb_stream_ref_t stream, tb_byte_t * data, tb_size_t size)
block read
Parameters
stream the stream
data the data
size the size
Returns
tb_true or tb_false
Definition at line 890 of file stream.c.
References tb_queue_buffer_null(), tb_stream_left(), tb_stream_read(), tb_stream_sync(), tb_stream_timeout(), and tb_stream_wait().
Referenced by tb_bloom_filter_load(), tb_object_data_init_from_url(), tb_stream_bread_double_bbe(), tb_stream_bread_double_ble(), tb_stream_bread_double_lbe(), tb_stream_bread_double_lle(), tb_stream_bread_float_be(), tb_stream_bread_float_le(), tb_stream_bread_s16_be(), tb_stream_bread_s16_le(), tb_stream_bread_s24_be(), tb_stream_bread_s24_le(), tb_stream_bread_s32_be(), tb_stream_bread_s32_le(), tb_stream_bread_s64_be(), tb_stream_bread_s64_le(), tb_stream_bread_s8(), tb_stream_bread_u16_be(), tb_stream_bread_u16_le(), tb_stream_bread_u24_be(), tb_stream_bread_u24_le(), tb_stream_bread_u32_be(), tb_stream_bread_u32_le(), tb_stream_bread_u64_be(), tb_stream_bread_u64_le(), tb_stream_bread_u8(), and tb_stream_seek().
tb_double_t tb_stream_bread_double_bbe (tb_stream_ref_t stream)
read double-bbe number
Parameters
stream the stream
Returns
the double-bbe number
Definition at line 1448 of file stream.c.
References tb_stream_bread().
tb_double_t tb_stream_bread_double_ble (tb_stream_ref_t stream)
read double-ble number
Parameters
stream the stream
Returns
the double-ble number
Definition at line 1442 of file stream.c.
References tb_stream_bread().
tb_double_t tb_stream_bread_double_lbe (tb_stream_ref_t stream)
read double-lbe number
Parameters
stream the stream
Returns
the double-lbe number
Definition at line 1460 of file stream.c.
References tb_stream_bread().
tb_double_t tb_stream_bread_double_lle (tb_stream_ref_t stream)
read double-lle number
Parameters
stream the stream
Returns
the double-lle number
Definition at line 1454 of file stream.c.
References tb_stream_bread().
tb_float_t tb_stream_bread_float_be (tb_stream_ref_t stream)
read float-be number
Parameters
stream the stream
Returns
the float-be number
Definition at line 1436 of file stream.c.
References tb_stream_bread().
tb_float_t tb_stream_bread_float_le (tb_stream_ref_t stream)
read float-le number
Parameters
stream the stream
Returns
the float-le number
Definition at line 1430 of file stream.c.
References tb_stream_bread().
tb_long_t tb_stream_bread_line (tb_stream_ref_t stream, tb_char_t * data, tb_size_t size)
block read line
Parameters
stream the stream
data the data
size the size
Returns
the real size
Definition at line 1124 of file stream.c.
References tb_stream_beof(), and tb_stream_bread_s8().
tb_sint16_t tb_stream_bread_s16_be (tb_stream_ref_t stream)
block read sint16-be integer
Parameters
stream the stream
Returns
the sint16-be integer
Definition at line 1279 of file stream.c.
References tb_stream_bread().
tb_sint16_t tb_stream_bread_s16_le (tb_stream_ref_t stream)
block read sint16-le integer
Parameters
stream the stream
Returns
the sint16-le integer
Definition at line 1231 of file stream.c.
References tb_stream_bread().
tb_sint32_t tb_stream_bread_s24_be (tb_stream_ref_t stream)
block read sint24-be integer
Parameters
stream the stream
Returns
the sint24-be integer
Definition at line 1291 of file stream.c.
References tb_stream_bread().
tb_sint32_t tb_stream_bread_s24_le (tb_stream_ref_t stream)
block read sint24-le integer
Parameters
stream the stream
Returns
the sint24-le integer
Definition at line 1243 of file stream.c.
References tb_stream_bread().
tb_sint32_t tb_stream_bread_s32_be (tb_stream_ref_t stream)
block read sint32-be integer
Parameters
stream the stream
Returns
the sint32-be integer
Definition at line 1303 of file stream.c.
References tb_stream_bread().
tb_sint32_t tb_stream_bread_s32_le (tb_stream_ref_t stream)
block read sint32-le integer
Parameters
stream the stream
Returns
the sint32-le integer
Definition at line 1255 of file stream.c.
References tb_stream_bread().
tb_sint64_t tb_stream_bread_s64_be (tb_stream_ref_t stream)
block read sint64-be integer
Parameters
stream the stream
Returns
the sint64-be integer
Definition at line 1315 of file stream.c.
References tb_stream_bread().
tb_sint64_t tb_stream_bread_s64_le (tb_stream_ref_t stream)
block read sint64-le integer
Parameters
stream the stream
Returns
the sint64-le integer
Definition at line 1267 of file stream.c.
References tb_stream_bread().
tb_sint8_t tb_stream_bread_s8 (tb_stream_ref_t stream)
block read sint8 integer
Parameters
stream the stream
Returns
the sint8 integer
Definition at line 1219 of file stream.c.
References tb_stream_bread().
Referenced by tb_stream_bread_line().
tb_uint16_t tb_stream_bread_u16_be (tb_stream_ref_t stream)
block read uint16-be integer
Parameters
stream the stream
Returns
the uint16-be integer
Definition at line 1273 of file stream.c.
References tb_stream_bread().
tb_uint16_t tb_stream_bread_u16_le (tb_stream_ref_t stream)
block read uint16-le integer
Parameters
stream the stream
Returns
the uint16-le integer
Definition at line 1225 of file stream.c.
References tb_stream_bread().
tb_uint32_t tb_stream_bread_u24_be (tb_stream_ref_t stream)
block read uint24-be integer
Parameters
stream the stream
Returns
the uint24-be integer
Definition at line 1285 of file stream.c.
References tb_stream_bread().
tb_uint32_t tb_stream_bread_u24_le (tb_stream_ref_t stream)
block read uint24-le integer
Parameters
stream the stream
Returns
the uint24-le integer
Definition at line 1237 of file stream.c.
References tb_stream_bread().
tb_uint32_t tb_stream_bread_u32_be (tb_stream_ref_t stream)
block read uint32-be integer
Parameters
stream the stream
Returns
the uint32-be integer
Definition at line 1297 of file stream.c.
References tb_stream_bread().
Referenced by tb_bloom_filter_load(), tb_circle_queue_load(), tb_heap_load(), tb_list_load(), tb_single_list_load(), and tb_vector_load().
tb_uint32_t tb_stream_bread_u32_le (tb_stream_ref_t stream)
block read uint32-le integer
Parameters
stream the stream
Returns
the uint32-le integer
Definition at line 1249 of file stream.c.
References tb_stream_bread().
tb_uint64_t tb_stream_bread_u64_be (tb_stream_ref_t stream)
block read uint64-be integer
Parameters
stream the stream
Returns
the uint64-be integer
Definition at line 1309 of file stream.c.
References tb_stream_bread().
tb_uint64_t tb_stream_bread_u64_le (tb_stream_ref_t stream)
block read uint64-le integer
Parameters
stream the stream
Returns
the uint64-le integer
Definition at line 1261 of file stream.c.
References tb_stream_bread().
tb_uint8_t tb_stream_bread_u8 (tb_stream_ref_t stream)
block read uint8 integer
Parameters
stream the stream
Returns
the uint8 integer
Definition at line 1213 of file stream.c.
References tb_stream_bread().
tb_bool_t tb_stream_bwrit (tb_stream_ref_t stream, tb_byte_t const * data, tb_size_t size)
block writ
Parameters
stream the stream
data the data
size the size
Returns
tb_true or tb_false
Definition at line 931 of file stream.c.
References tb_stream_timeout(), tb_stream_wait(), and tb_stream_writ().
Referenced by tb_bloom_filter_save(), tb_object_data_writ_to_url(), tb_stream_bwrit_double_bbe(), tb_stream_bwrit_double_ble(), tb_stream_bwrit_double_lbe(), tb_stream_bwrit_double_lle(), tb_stream_bwrit_float_be(), tb_stream_bwrit_float_le(), tb_stream_bwrit_line(), tb_stream_bwrit_s16_be(), tb_stream_bwrit_s16_le(), tb_stream_bwrit_s24_be(), tb_stream_bwrit_s24_le(), tb_stream_bwrit_s32_be(), tb_stream_bwrit_s32_le(), tb_stream_bwrit_s64_be(), tb_stream_bwrit_s64_le(), tb_stream_bwrit_s8(), tb_stream_bwrit_u16_be(), tb_stream_bwrit_u16_le(), tb_stream_bwrit_u24_be(), tb_stream_bwrit_u24_le(), tb_stream_bwrit_u32_be(), tb_stream_bwrit_u32_le(), tb_stream_bwrit_u64_be(), tb_stream_bwrit_u64_le(), tb_stream_bwrit_u8(), tb_stream_printf(), and tb_transfer_done().
tb_bool_t tb_stream_bwrit_double_bbe (tb_stream_ref_t stream, tb_double_t val)
writ double-bbe number
Parameters
stream the stream
val the value
Returns
tb_true or tb_false
Definition at line 1484 of file stream.c.
References tb_stream_bwrit().
tb_bool_t tb_stream_bwrit_double_ble (tb_stream_ref_t stream, tb_double_t val)
writ double-ble number
Parameters
stream the stream
val the value
Returns
tb_true or tb_false
Definition at line 1478 of file stream.c.
References tb_stream_bwrit().
tb_bool_t tb_stream_bwrit_double_lbe (tb_stream_ref_t stream, tb_double_t val)
writ double-lbe number
Parameters
stream the stream
val the value
Returns
tb_true or tb_false
Definition at line 1496 of file stream.c.
References tb_stream_bwrit().
tb_bool_t tb_stream_bwrit_double_lle (tb_stream_ref_t stream, tb_double_t val)
writ double-lle number
Parameters
stream the stream
val the value
Returns
tb_true or tb_false
Definition at line 1490 of file stream.c.
References tb_stream_bwrit().
tb_bool_t tb_stream_bwrit_float_be (tb_stream_ref_t stream, tb_float_t val)
writ float-be number
Parameters
stream the stream
val the value
Returns
tb_true or tb_false
Definition at line 1472 of file stream.c.
References tb_stream_bwrit().
tb_bool_t tb_stream_bwrit_float_le (tb_stream_ref_t stream, tb_float_t val)
writ float-le number
Parameters
stream the stream
val the value
Returns
tb_true or tb_false
Definition at line 1466 of file stream.c.
References tb_stream_bwrit().
tb_long_t tb_stream_bwrit_line (tb_stream_ref_t stream, tb_char_t * data, tb_size_t size)
block writ line
Parameters
stream the stream
data the data
size the size
Returns
the real size
Definition at line 1166 of file stream.c.
References tb_stream_bwrit().
tb_bool_t tb_stream_bwrit_s16_be (tb_stream_ref_t stream, tb_sint16_t val)
block writ sint16-be integer
Parameters
stream the stream
val the value
Returns
tb_true or tb_false
Definition at line 1387 of file stream.c.
References tb_stream_bwrit().
tb_bool_t tb_stream_bwrit_s16_le (tb_stream_ref_t stream, tb_sint16_t val)
block writ sint16-le integer
Parameters
stream the stream
val the value
Returns
tb_true or tb_false
Definition at line 1339 of file stream.c.
References tb_stream_bwrit().
tb_bool_t tb_stream_bwrit_s24_be (tb_stream_ref_t stream, tb_sint32_t val)
block writ sint24-be integer
Parameters
stream the stream
val the value
Returns
tb_true or tb_false
Definition at line 1399 of file stream.c.
References tb_stream_bwrit().
tb_bool_t tb_stream_bwrit_s24_le (tb_stream_ref_t stream, tb_sint32_t val)
block writ sint24-le integer
Parameters
stream the stream
val the value
Returns
tb_true or tb_false
Definition at line 1351 of file stream.c.
References tb_stream_bwrit().
tb_bool_t tb_stream_bwrit_s32_be (tb_stream_ref_t stream, tb_sint32_t val)
block writ sint32-be integer
Parameters
stream the stream
val the value
Returns
tb_true or tb_false
Definition at line 1411 of file stream.c.
References tb_stream_bwrit().
tb_bool_t tb_stream_bwrit_s32_le (tb_stream_ref_t stream, tb_sint32_t val)
block writ sint32-le integer
Parameters
stream the stream
val the value
Returns
tb_true or tb_false
Definition at line 1363 of file stream.c.
References tb_stream_bwrit().
tb_bool_t tb_stream_bwrit_s64_be (tb_stream_ref_t stream, tb_sint64_t val)
block writ sint64-be integer
Parameters
stream the stream
val the value
Returns
tb_true or tb_false
Definition at line 1423 of file stream.c.
References tb_stream_bwrit().
tb_bool_t tb_stream_bwrit_s64_le (tb_stream_ref_t stream, tb_sint64_t val)
block writ sint64-le integer
Parameters
stream the stream
val the value
Returns
tb_true or tb_false
Definition at line 1375 of file stream.c.
References tb_stream_bwrit().
tb_bool_t tb_stream_bwrit_s8 (tb_stream_ref_t stream, tb_sint8_t val)
block writ sint8 integer
Parameters
stream the stream
val the value
Returns
tb_true or tb_false
Definition at line 1327 of file stream.c.
References tb_stream_bwrit().
tb_bool_t tb_stream_bwrit_u16_be (tb_stream_ref_t stream, tb_uint16_t val)
block writ uint16-be integer
Parameters
stream the stream
val the value
Returns
tb_true or tb_false
Definition at line 1381 of file stream.c.
References tb_stream_bwrit().
tb_bool_t tb_stream_bwrit_u16_le (tb_stream_ref_t stream, tb_uint16_t val)
block writ uint16-le integer
Parameters
stream the stream
val the value
Returns
tb_true or tb_false
Definition at line 1333 of file stream.c.
References tb_stream_bwrit().
tb_bool_t tb_stream_bwrit_u24_be (tb_stream_ref_t stream, tb_uint32_t val)
block writ uint24-be integer
Parameters
stream the stream
val the value
Returns
tb_true or tb_false
Definition at line 1393 of file stream.c.
References tb_stream_bwrit().
tb_bool_t tb_stream_bwrit_u24_le (tb_stream_ref_t stream, tb_uint32_t val)
block writ uint24-le integer
Parameters
stream the stream
val the value
Returns
tb_true or tb_false
Definition at line 1345 of file stream.c.
References tb_stream_bwrit().
tb_bool_t tb_stream_bwrit_u32_be (tb_stream_ref_t stream, tb_uint32_t val)
block writ uint32-be integer
Parameters
stream the stream
val the value
Returns
tb_true or tb_false
Definition at line 1405 of file stream.c.
References tb_stream_bwrit().
Referenced by tb_bloom_filter_save(), tb_circle_queue_save(), tb_heap_save(), tb_list_save(), tb_single_list_save(), and tb_vector_save().
tb_bool_t tb_stream_bwrit_u32_le (tb_stream_ref_t stream, tb_uint32_t val)
block writ uint32-le integer
Parameters
stream the stream
val the value
Returns
tb_true or tb_false
Definition at line 1357 of file stream.c.
References tb_stream_bwrit().
tb_bool_t tb_stream_bwrit_u64_be (tb_stream_ref_t stream, tb_uint64_t val)
block writ uint64-be integer
Parameters
stream the stream
val the value
Returns
tb_true or tb_false
Definition at line 1417 of file stream.c.
References tb_stream_bwrit().
tb_bool_t tb_stream_bwrit_u64_le (tb_stream_ref_t stream, tb_uint64_t val)
block writ uint64-le integer
Parameters
stream the stream
val the value
Returns
tb_true or tb_false
Definition at line 1369 of file stream.c.
References tb_stream_bwrit().
tb_bool_t tb_stream_bwrit_u8 (tb_stream_ref_t stream, tb_uint8_t val)
block writ uint8 integer
Parameters
stream the stream
val the value
Returns
tb_true or tb_false
Definition at line 1321 of file stream.c.
References tb_stream_bwrit().
tb_bool_t tb_stream_clos (tb_stream_ref_t stream)
close stream
Parameters
stream the stream
Returns
tb_true or tb_false
Definition at line 629 of file stream.c.
References tb_queue_buffer_clear(), tb_stream_is_opened(), and tb_stream_sync().
Referenced by tb_stream_exit().
tb_bool_t tb_stream_ctrl (tb_stream_ref_t stream, tb_size_t ctrl, ...)
ctrl stream
Parameters
stream the stream
ctrl the ctrl code
Returns
tb_true or tb_false
Definition at line 361 of file stream.c.
References tb_stream_ctrl_with_args().
Referenced by tb_object_data_writ_to_url(), tb_object_writ_to_url(), tb_stream_init_filter_from_cache(), tb_stream_init_filter_from_charset(), tb_stream_init_filter_from_chunked(), tb_stream_init_filter_from_null(), tb_stream_init_filter_from_zip(), tb_stream_init_from_data(), tb_stream_init_from_file(), tb_stream_init_from_http(), tb_stream_init_from_sock(), tb_stream_init_from_url(), tb_stream_offset(), tb_stream_size(), tb_stream_timeout(), tb_transfer_done_data_to_url(), tb_transfer_done_to_url(), and tb_transfer_done_url().
tb_bool_t tb_stream_ctrl_with_args (tb_stream_ref_t stream, tb_size_t ctrl, tb_va_list_t args)
ctrl stream with arguments
Parameters
stream the stream
ctrl the ctrl code
args the ctrl args
Returns
tb_true or tb_false
Definition at line 380 of file stream.c.
References tb_stream_is_closed().
Referenced by tb_stream_ctrl().
tb_void_t tb_stream_exit (tb_stream_ref_t stream)
exit stream
Parameters
stream the stream
Definition at line 181 of file stream.c.
References tb_queue_buffer_exit(), and tb_stream_clos().
Referenced by tb_dump_data(), tb_dump_data_from_url(), tb_object_data_init_from_url(), tb_object_data_writ_to_url(), tb_object_read_from_data(), tb_object_read_from_url(), tb_object_writ_to_data(), tb_object_writ_to_url(), tb_stream_init(), tb_stream_init_filter_from_cache(), tb_stream_init_filter_from_charset(), tb_stream_init_filter_from_chunked(), tb_stream_init_filter_from_null(), tb_stream_init_filter_from_zip(), tb_stream_init_from_data(), tb_stream_init_from_file(), tb_stream_init_from_http(), tb_stream_init_from_sock(), tb_stream_init_from_url(), tb_transfer_done_data_to_stream(), tb_transfer_done_data_to_url(), tb_transfer_done_to_data(), tb_transfer_done_to_url(), tb_transfer_done_url(), tb_transfer_done_url_to_data(), and tb_transfer_done_url_to_stream().
tb_stream_ref_t tb_stream_init (tb_size_t type, tb_size_t type_size, tb_size_t cache, tb_bool_t(*)(tb_stream_ref_t stream) open, tb_bool_t(*)(tb_stream_ref_t stream) clos, tb_void_t(*)(tb_stream_ref_t stream) exit, tb_bool_t(*)(tb_stream_ref_t stream, tb_size_t ctrl, tb_va_list_t args) ctrl, tb_long_t(*)(tb_stream_ref_t stream, tb_size_t wait, tb_long_t timeout) wait, tb_long_t(*)(tb_stream_ref_t stream, tb_byte_t *data, tb_size_t size) read, tb_long_t(*)(tb_stream_ref_t stream, tb_byte_t const *data, tb_size_t size) writ, tb_bool_t(*)(tb_stream_ref_t stream, tb_hize_t offset) seek, tb_bool_t(*)(tb_stream_ref_t stream, tb_bool_t bclosing) sync, tb_void_t(*)(tb_stream_ref_t stream) kill)
init stream
Parameters
type the stream type
type_size the stream type size
cache the cache size
open the stream impl func: open
clos the stream impl func: clos
exit the stream impl func: exit, optional
ctrl the stream impl func: ctrl
wait the stream impl func: wait
read the stream impl func: read
writ the stream impl func: writ
seek the stream impl func: seek, optional
sync the stream impl func: sync, optional
kill the stream impl func: kill, optional
Returns
the stream
// the custom xxxx stream type
typedef struct __tb_stream_xxxx_impl_t
{
    // the xxxx data
    tb_handle_t         xxxx;
}tb_stream_xxxx_impl_t;
static tb_bool_t tb_stream_xxxx_impl_open(tb_stream_ref_t stream)
{
    // check
    tb_stream_xxxx_impl_t* impl = (tb_stream_xxxx_impl_t*)stream;
    tb_assert_and_check_return_val(impl, tb_false);
    // ok
    return tb_true;
}
static tb_bool_t tb_stream_xxxx_impl_clos(tb_stream_ref_t stream)
{
    // check
    tb_stream_xxxx_impl_t* impl = (tb_stream_xxxx_impl_t*)stream;
    tb_assert_and_check_return_val(impl, tb_false);
    // ok
    return tb_true;
}
// define other xxxx stream func
// ...
// init stream
tb_stream_ref_t stream = tb_stream_init(TB_STREAM_TYPE_XXXX
                                        ,   sizeof(tb_stream_xxxx_impl_t)
                                        ,   0
                                        ,   tb_stream_xxxx_impl_open
                                        ,   tb_stream_xxxx_impl_clos
                                        ,   tb_stream_xxxx_impl_exit
                                        ,   tb_stream_xxxx_impl_ctrl
                                        ,   tb_stream_xxxx_impl_wait
                                        ,   tb_stream_xxxx_impl_read
                                        ,   tb_stream_xxxx_impl_writ
                                        ,   tb_stream_xxxx_impl_seek
                                        ,   tb_stream_xxxx_impl_sync
                                        ,   tb_stream_xxxx_impl_kill);
// using stream
// ...
Definition at line 47 of file stream.c.
References tb_queue_buffer_init(), and tb_stream_exit().
tb_stream_ref_t tb_stream_init_data (tb_noarg_t)
init data stream
Returns
the stream
Referenced by tb_stream_init_from_data(), and tb_stream_init_from_url().
tb_stream_ref_t tb_stream_init_file (tb_noarg_t)
init file stream
Returns
the stream
Referenced by tb_stream_init_from_file(), and tb_stream_init_from_url().
tb_stream_ref_t tb_stream_init_filter (tb_noarg_t)
init filter stream
Returns
the stream
Referenced by tb_stream_init_filter_from_cache(), tb_stream_init_filter_from_charset(), tb_stream_init_filter_from_chunked(), tb_stream_init_filter_from_null(), and tb_stream_init_filter_from_zip().
tb_stream_ref_t tb_stream_init_filter_from_cache (tb_stream_ref_t stream, tb_size_t size)
init filter stream from cache
Parameters
stream the stream
size the initial cache size, using the default size if be zero
Returns
the stream
Definition at line 463 of file filter.c.
References tb_stream_ctrl(), tb_stream_exit(), tb_stream_filter_init_from_cache(), and tb_stream_init_filter().
tb_stream_ref_t tb_stream_init_filter_from_charset (tb_stream_ref_t stream, tb_size_t fr, tb_size_t to)
init filter stream from charset
Parameters
stream the stream
fr the from charset
to the to charset
Returns
the stream
Definition at line 502 of file filter.c.
References tb_stream_ctrl(), tb_stream_exit(), tb_stream_filter_init_from_charset(), and tb_stream_init_filter().
tb_stream_ref_t tb_stream_init_filter_from_chunked (tb_stream_ref_t stream, tb_bool_t dechunked)
init filter stream from chunked
Parameters
stream the stream
dechunked decode the chunked data?
Returns
the stream
Definition at line 541 of file filter.c.
References tb_stream_ctrl(), tb_stream_exit(), tb_stream_filter_init_from_chunked(), and tb_stream_init_filter().
tb_stream_ref_t tb_stream_init_filter_from_null (tb_stream_ref_t stream)
init filter stream from null
Parameters
stream the stream
Returns
the stream
Definition at line 390 of file filter.c.
References tb_stream_ctrl(), tb_stream_exit(), and tb_stream_init_filter().
tb_stream_ref_t tb_stream_init_filter_from_zip (tb_stream_ref_t stream, tb_size_t algo, tb_size_t action)
init filter stream from zip
Parameters
stream the stream
algo the zip algorithm
action the zip action
Returns
the stream
Definition at line 424 of file filter.c.
References tb_stream_ctrl(), tb_stream_exit(), tb_stream_filter_init_from_zip(), and tb_stream_init_filter().
tb_stream_ref_t tb_stream_init_from_data (tb_byte_t const * data, tb_size_t size)
init stream from data
Parameters
data the data
size the size
Returns
the stream
Definition at line 276 of file data.c.
References tb_stream_ctrl(), tb_stream_exit(), and tb_stream_init_data().
Referenced by tb_dump_data(), tb_object_read_from_data(), tb_object_writ_to_data(), tb_transfer_done_data_to_stream(), tb_transfer_done_data_to_url(), tb_transfer_done_to_data(), and tb_transfer_done_url_to_data().
tb_stream_ref_t tb_stream_init_from_file (tb_char_t const * path, tb_size_t mode)
init stream from file
Parameters
path the file path
mode the file mode, using the default ro mode if zero
Returns
the stream
Definition at line 228 of file file.c.
References tb_stream_ctrl(), tb_stream_exit(), and tb_stream_init_file().
tb_stream_ref_t tb_stream_init_from_http (tb_char_t const * host, tb_uint16_t port, tb_char_t const * path, tb_bool_t bssl)
init stream from http or https
Parameters
host the host
port the port
path the path
bssl enable ssl?
Returns
the stream
Definition at line 621 of file http.c.
References tb_stream_ctrl(), tb_stream_exit(), and tb_stream_init_http().
tb_stream_ref_t tb_stream_init_from_sock (tb_char_t const * host, tb_uint16_t port, tb_size_t type, tb_bool_t bssl)
init stream from sock
Parameters
host the host
port the port
type the socket type, tcp or udp
bssl enable ssl?
Returns
the stream
Definition at line 626 of file sock.c.
References tb_stream_ctrl(), tb_stream_exit(), and tb_stream_init_sock().
tb_stream_ref_t tb_stream_init_from_url (tb_char_t const * url)
init stream from url
Parameters
url the url
data://base64
file://path or unix path: e.g. /root/xxxx/file
sock://host:port?tcp=
sock://host:port?udp=
socks://host:port
http://host:port/path?arg0=&arg1=...
https://host:port/path?arg0=&arg1=...
Returns
the stream
Definition at line 122 of file stream.c.
References tb_stream_ctrl(), tb_stream_exit(), tb_stream_init_data(), tb_stream_init_file(), tb_stream_init_http(), and tb_stream_init_sock().
Referenced by tb_dump_data_from_url(), tb_object_data_init_from_url(), tb_object_data_writ_to_url(), tb_object_read_from_url(), tb_object_writ_to_url(), tb_transfer_done_data_to_url(), tb_transfer_done_to_url(), tb_transfer_done_url(), tb_transfer_done_url_to_data(), and tb_transfer_done_url_to_stream().
tb_stream_ref_t tb_stream_init_http (tb_noarg_t)
init http stream
Returns
the stream
Referenced by tb_stream_init_from_http(), and tb_stream_init_from_url().
tb_stream_ref_t tb_stream_init_sock (tb_noarg_t)
init sock stream
Returns
the stream
Referenced by tb_stream_init_from_sock(), and tb_stream_init_from_url().
tb_bool_t tb_stream_is_closed (tb_stream_ref_t stream)
is closed?
Parameters
stream the stream
Returns
tb_true or tb_false
Definition at line 337 of file stream.c.
Referenced by tb_stream_ctrl_with_args(), and tb_transfer_done().
tb_bool_t tb_stream_is_killed (tb_stream_ref_t stream)
is killed?
Parameters
stream the stream
Returns
tb_true or tb_false
Definition at line 349 of file stream.c.
tb_bool_t tb_stream_is_opened (tb_stream_ref_t stream)
is opened?
Parameters
stream the stream
Returns
tb_true or tb_false
Definition at line 325 of file stream.c.
Referenced by tb_database_sql_value_set_blob32(), tb_stream_clos(), tb_stream_need(), tb_stream_open(), tb_stream_read(), tb_stream_seek(), tb_stream_sync(), and tb_stream_writ().
tb_void_t tb_stream_kill (tb_stream_ref_t stream)
kill stream
Parameters
stream the stream
Definition at line 569 of file stream.c.
References tb_state_cstr().
tb_hize_t tb_stream_left (tb_stream_ref_t stream)
the stream left size and not seeking it
Parameters
stream the stream
Returns
the stream left size, no size: infinity, empty or end: 0
Definition at line 270 of file stream.c.
References tb_stream_offset(), and tb_stream_size().
Referenced by tb_stream_bread(), and tb_transfer_done().
tb_bool_t tb_stream_need (tb_stream_ref_t stream, tb_byte_t ** data, tb_size_t size)
need stream
Parameters
stream the stream
data the data
size the size
Returns
tb_true or tb_false
Definition at line 656 of file stream.c.
References tb_queue_buffer_head(), tb_queue_buffer_maxn(), tb_queue_buffer_null(), tb_queue_buffer_push_exit(), tb_queue_buffer_push_init(), tb_queue_buffer_resize(), tb_queue_buffer_size(), tb_stream_is_opened(), tb_stream_sync(), and tb_stream_timeout().
tb_hize_t tb_stream_offset (tb_stream_ref_t stream)
the stream offset
the offset is read + writ and using seek for modifying it if size != -1, .e.g: data, file, .. the offset is calculated from the last read/writ and not seeking it if size == -1, .e.g: sock, filter, ..
Parameters
stream the stream
Returns
the stream offset
Definition at line 298 of file stream.c.
References tb_stream_ctrl().
Referenced by tb_bloom_filter_load(), tb_bloom_filter_save(), tb_circle_queue_load(), tb_circle_queue_save(), tb_heap_load(), tb_heap_save(), tb_list_load(), tb_list_save(), tb_single_list_load(), tb_single_list_save(), tb_stream_beof(), tb_stream_left(), tb_stream_seek(), tb_stream_skip(), tb_transfer_done(), tb_vector_load(), and tb_vector_save().
tb_bool_t tb_stream_open (tb_stream_ref_t stream)
open stream
Parameters
stream the stream
Returns
tb_true or tb_false
Definition at line 602 of file stream.c.
References tb_stream_is_opened().
Referenced by tb_dump_data(), tb_dump_data_from_url(), tb_object_data_init_from_url(), tb_object_data_writ_to_url(), tb_object_read_from_data(), tb_object_read_from_url(), tb_object_writ_to_data(), tb_object_writ_to_url(), tb_transfer_done(), and tb_transfer_done_url().
tb_long_t tb_stream_printf (tb_stream_ref_t stream, tb_char_t const * fmt, ...)
block writ format data
Parameters
stream the stream
fmt the format
Returns
the real size, failed: -1
Definition at line 1200 of file stream.c.
References TB_STREAM_BLOCK_MAXN, and tb_stream_bwrit().
tb_long_t tb_stream_read (tb_stream_ref_t stream, tb_byte_t * data, tb_size_t size)
read data, non-blocking
Parameters
stream the stream
data the data
size the size
Returns
the real size or -1
Definition at line 745 of file stream.c.
References tb_queue_buffer_maxn(), tb_queue_buffer_null(), tb_queue_buffer_push_exit(), tb_queue_buffer_push_init(), tb_queue_buffer_read(), and tb_stream_is_opened().
Referenced by tb_dump_data_from_stream(), tb_stream_bread(), and tb_transfer_done().
tb_bool_t tb_stream_seek (tb_stream_ref_t stream, tb_hize_t offset)
seek stream
Parameters
stream the stream
offset the offset
Returns
tb_true or tb_false
Definition at line 1033 of file stream.c.
References tb_queue_buffer_clear(), tb_queue_buffer_maxn(), tb_queue_buffer_null(), tb_queue_buffer_pull_exit(), tb_queue_buffer_pull_init(), TB_STREAM_BLOCK_MAXN, tb_stream_bread(), tb_stream_is_opened(), tb_stream_offset(), tb_stream_size(), and tb_stream_sync().
Referenced by tb_bloom_filter_load(), tb_bloom_filter_save(), tb_circle_queue_load(), tb_circle_queue_save(), tb_heap_load(), tb_heap_save(), tb_list_load(), tb_list_save(), tb_single_list_load(), tb_single_list_save(), tb_stream_skip(), tb_vector_load(), and tb_vector_save().
tb_hong_t tb_stream_size (tb_stream_ref_t stream)
the stream size and not seeking it
Parameters
stream the stream
Returns
the stream size, no size: -1, empty or error: 0
Definition at line 261 of file stream.c.
References tb_stream_ctrl().
Referenced by tb_database_sql_value_set_blob32(), tb_object_data_init_from_url(), tb_stream_beof(), tb_stream_left(), tb_stream_seek(), and tb_transfer_done().
tb_bool_t tb_stream_skip (tb_stream_ref_t stream, tb_hize_t size)
skip stream
Parameters
stream the stream
size the size
Returns
tb_true or tb_false
Definition at line 1120 of file stream.c.
References tb_stream_offset(), and tb_stream_seek().
tb_size_t tb_stream_state (tb_stream_ref_t stream)
the state
Parameters
stream the stream
Returns
the state
Definition at line 234 of file stream.c.
tb_void_t tb_stream_state_set (tb_stream_ref_t stream, tb_size_t state)
set the state
Parameters
stream the stream
state the state
Definition at line 243 of file stream.c.
tb_bool_t tb_stream_sync (tb_stream_ref_t stream, tb_bool_t bclosing)
sync stream
Parameters
stream the stream
bclosing is closing?
Returns
tb_true or tb_false
Definition at line 964 of file stream.c.
References tb_queue_buffer_maxn(), tb_queue_buffer_null(), tb_queue_buffer_pull_exit(), tb_queue_buffer_pull_init(), tb_stream_is_opened(), and tb_stream_timeout().
Referenced by tb_stream_bread(), tb_stream_clos(), tb_stream_need(), tb_stream_seek(), and tb_transfer_done().
tb_long_t tb_stream_timeout (tb_stream_ref_t stream)
the stream timeout
Parameters
stream the stream
Returns
the stream timeout
Definition at line 316 of file stream.c.
References tb_stream_ctrl().
Referenced by tb_dump_data_from_stream(), tb_stream_bread(), tb_stream_bwrit(), tb_stream_need(), tb_stream_sync(), and tb_transfer_done().
tb_size_t tb_stream_type (tb_stream_ref_t stream)
the stream type
Parameters
stream the stream
Returns
the stream type
Definition at line 252 of file stream.c.
Referenced by tb_object_data_writ_to_url(), tb_object_writ_to_url(), tb_transfer_done_data_to_url(), tb_transfer_done_to_url(), and tb_transfer_done_url().
tb_url_t* tb_stream_url (tb_stream_ref_t stream)
the stream url
Parameters
stream the stream
Returns
the stream url
Definition at line 307 of file stream.c.
tb_long_t tb_stream_wait (tb_stream_ref_t stream, tb_size_t wait, tb_long_t timeout)
wait stream
blocking wait the single event object, so need not aiop return the event type if ok, otherwise return 0 for timeout
Parameters
stream the stream
wait the wait type
timeout the timeout value, return immediately if 0, infinity if -1
Returns
the event type, return 0 if timeout, return -1 if error
Definition at line 202 of file stream.c.
References tb_queue_buffer_full(), tb_queue_buffer_maxn(), and tb_queue_buffer_null().
Referenced by tb_dump_data_from_stream(), tb_stream_bread(), tb_stream_bwrit(), and tb_transfer_done().
tb_long_t tb_stream_writ (tb_stream_ref_t stream, tb_byte_t const * data, tb_size_t size)
writ data, non-blocking
Parameters
stream the stream
data the data
size the size
Returns
the real size or -1
Definition at line 818 of file stream.c.
References tb_queue_buffer_full(), tb_queue_buffer_maxn(), tb_queue_buffer_null(), tb_queue_buffer_pull_exit(), tb_queue_buffer_pull_init(), tb_queue_buffer_writ(), and tb_stream_is_opened().
Referenced by tb_stream_bwrit().