TBOX: src/tbox/libc/stdlib/stdlib.c File Reference
stdlib.c File Reference
Libc
#include "stdlib.h"
#include "../../libm/libm.h"
Functions
tb_uint64_t tb_s2tou64 (tb_char_t const *s)
tb_uint64_t tb_s8tou64 (tb_char_t const *s)
tb_uint64_t tb_s10tou64 (tb_char_t const *s)
tb_uint64_t tb_s16tou64 (tb_char_t const *s)
tb_uint64_t tb_stou64 (tb_char_t const *s)
tb_uint64_t tb_sbtou64 (tb_char_t const *s, tb_int_t base)
tb_double_t tb_s2tod (tb_char_t const *s)
tb_double_t tb_s8tod (tb_char_t const *s)
tb_double_t tb_s10tod (tb_char_t const *s)
tb_double_t tb_s16tod (tb_char_t const *s)
tb_double_t tb_stod (tb_char_t const *s)
tb_double_t tb_sbtod (tb_char_t const *s, tb_int_t base)
Detailed Description
The Treasure Box Library
TBox is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 2.1 of the License, or (at your option) any later version.
TBox is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with TBox; If not, see http://www.gnu.org/licenses/
Copyright (C) 2009 - 2015, ruki All rights reserved.
Author
ruki
Definition in file stdlib.c.
Function Documentation
tb_double_t tb_s10tod (tb_char_t const * s)
convert the decimal string to double
.e.g "9" => 9
Parameters
s the string
Returns
the double number
Definition at line 423 of file stdlib.c.
Referenced by tb_sbtod(), and tb_stod().
tb_uint64_t tb_s10tou64 (tb_char_t const * s)
convert the decimal string to uint64
.e.g "9" => 9
Parameters
s the string
Returns
the uint64 number
Definition at line 112 of file stdlib.c.
Referenced by tb_sbtou64(), and tb_stou64().
tb_double_t tb_s16tod (tb_char_t const * s)
convert the hex string to double
.e.g
"9" => 9
"0x9" => 9
Parameters
s the string
Returns
the double number
Definition at line 510 of file stdlib.c.
Referenced by tb_sbtod(), and tb_stod().
tb_uint64_t tb_s16tou64 (tb_char_t const * s)
convert the hex string to uint64
.e.g
"9" => 9
"0x9" => 9
Parameters
s the string
Returns
the uint64 number
Definition at line 149 of file stdlib.c.
Referenced by tb_sbtou64(), and tb_stou64().
tb_double_t tb_s2tod (tb_char_t const * s)
convert the binary string to double
.e.g
"1001" => 9
"0b1001" => 9
Parameters
s the string
Returns
the double number
Definition at line 249 of file stdlib.c.
Referenced by tb_sbtod(), and tb_stod().
tb_uint64_t tb_s2tou64 (tb_char_t const * s)
convert the binary string to uint64
.e.g
"1001" => 9
"0b1001" => 9
Parameters
s the string
Returns
the uint64 number
Definition at line 34 of file stdlib.c.
Referenced by tb_sbtou64(), and tb_stou64().
tb_double_t tb_s8tod (tb_char_t const * s)
convert the binary string to double
.e.g
"11" => 9
"011" => 9
Parameters
s the string
Returns
the double number
Definition at line 336 of file stdlib.c.
Referenced by tb_sbtod(), and tb_stod().
tb_uint64_t tb_s8tou64 (tb_char_t const * s)
convert the octal string to uint64
.e.g
"11" => 9
"011" => 9
Parameters
s the string
Returns
the uint64 number
Definition at line 75 of file stdlib.c.
Referenced by tb_sbtou64(), and tb_stou64().
tb_double_t tb_sbtod (tb_char_t const * s, tb_int_t base)
convert string to double using the given base number
Parameters
s the string
Returns
the double number
Definition at line 663 of file stdlib.c.
References tb_s10tod(), tb_s16tod(), tb_s2tod(), and tb_s8tod().
tb_uint64_t tb_sbtou64 (tb_char_t const * s, tb_int_t base)
convert string to uint64 using the given base number
Parameters
s the string
Returns
the uint64 number
Definition at line 217 of file stdlib.c.
References tb_s10tou64(), tb_s16tou64(), tb_s2tou64(), and tb_s8tou64().
tb_double_t tb_stod (tb_char_t const * s)
auto convert string to double
.e.g
"0b1001" => 9
"011"    => 9
"9"      => 9
"0x9"    => 9
Parameters
s the string
Returns
the double number
Definition at line 640 of file stdlib.c.
References tb_s10tod(), tb_s16tod(), tb_s2tod(), and tb_s8tod().
Referenced by tb_database_sql_value_double().
tb_uint64_t tb_stou64 (tb_char_t const * s)
auto convert string to uint64
.e.g
"0b1001" => 9
"011"    => 9
"9"      => 9
"0x9"    => 9
Parameters
s the string
Returns
the uint64 number
Definition at line 194 of file stdlib.c.
References tb_s10tou64(), tb_s16tou64(), tb_s2tou64(), and tb_s8tou64().
Referenced by tb_database_sql_value_uint64().