TBOX: src/tbox/platform/timer.h File Reference
timer.h File Reference
Platform
#include "prefix.h"
Data Structures
struct tb_timer_ref_t
the timer ref type
struct tb_timer_task_ref_t
the timer task ref type
Functions
tb_timer_ref_t tb_timer_init (tb_size_t maxn, tb_bool_t ctime)
tb_void_t tb_timer_exit (tb_timer_ref_t timer)
tb_void_t tb_timer_clear (tb_timer_ref_t timer)
tb_size_t tb_timer_delay (tb_timer_ref_t timer)
tb_hize_t tb_timer_top (tb_timer_ref_t timer)
tb_bool_t tb_timer_spak (tb_timer_ref_t timer)
tb_void_t tb_timer_loop (tb_timer_ref_t timer)
tb_void_t tb_timer_task_post (tb_timer_ref_t timer, tb_size_t delay, tb_bool_t repeat, tb_timer_task_func_t func, tb_cpointer_t priv)
tb_void_t tb_timer_task_post_at (tb_timer_ref_t timer, tb_hize_t when, tb_size_t period, tb_bool_t repeat, tb_timer_task_func_t func, tb_cpointer_t priv)
tb_void_t tb_timer_task_post_after (tb_timer_ref_t timer, tb_hize_t after, tb_size_t period, tb_bool_t repeat, tb_timer_task_func_t func, tb_cpointer_t priv)
tb_timer_task_ref_t tb_timer_task_init (tb_timer_ref_t timer, tb_size_t delay, tb_bool_t repeat, tb_timer_task_func_t func, tb_cpointer_t priv)
tb_timer_task_ref_t tb_timer_task_init_at (tb_timer_ref_t timer, tb_hize_t when, tb_size_t period, tb_bool_t repeat, tb_timer_task_func_t func, tb_cpointer_t priv)
tb_timer_task_ref_t tb_timer_task_init_after (tb_timer_ref_t timer, tb_hize_t after, tb_size_t period, tb_bool_t repeat, tb_timer_task_func_t func, tb_cpointer_t priv)
tb_void_t tb_timer_task_exit (tb_timer_ref_t timer, tb_timer_task_ref_t task)
tb_void_t tb_timer_task_kill (tb_timer_ref_t timer, tb_timer_task_ref_t task)
Variables
__tb_extern_c_enter__ typedef
tb_void_t(* tb_timer_task_func_t)(tb_bool_t killed, tb_cpointer_t priv)
Detailed Description
The Treasure Box Library
TBox is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 2.1 of the License, or (at your option) any later version.
TBox is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with TBox; If not, see http://www.gnu.org/licenses/
Copyright (C) 2009 - 2015, ruki All rights reserved.
Author
ruki
Definition in file timer.h.
Function Documentation
tb_void_t tb_timer_clear (tb_timer_ref_t timer)
clear timer
Parameters
timer the timer
Definition at line 227 of file timer.c.
References tb_fixed_pool_clear(), and tb_heap_clear().
tb_size_t tb_timer_delay (tb_timer_ref_t timer)
the timer delay for spak
Parameters
timer the timer
Returns
the timer delay, (tb_size_t)-1: error or no task
Definition at line 272 of file timer.c.
References tb_heap_size(), and tb_heap_top().
Referenced by tb_timer_loop().
tb_void_t tb_timer_exit (tb_timer_ref_t timer)
exit timer
Parameters
timer the timer
Definition at line 181 of file timer.c.
References tb_event_exit(), tb_event_post(), tb_fixed_pool_exit(), and tb_heap_exit().
Referenced by tb_timer_init().
tb_timer_ref_t tb_timer_init (tb_size_t maxn, tb_bool_t ctime)
init timer
lower tick and limit range, but faster
Parameters
maxn the timer maxn
ctime using ctime?
Returns
the timer
Definition at line 132 of file timer.c.
References tb_item_func_t::comp, tb_fixed_pool_init(), tb_heap_init(), tb_item_func_ptr(), tb_lock_profiler(), tb_lock_profiler_register(), and tb_timer_exit().
tb_void_t tb_timer_loop (tb_timer_ref_t timer)
loop timer for the external thread
tb_void_t tb_timer_thread(tb_cpointer_t priv)
{
     tb_timer_loop(timer);
}
Parameters
timer the timer
Returns
tb_true or tb_false
Definition at line 387 of file timer.c.
References tb_cache_time_spak(), tb_event_init(), tb_event_wait(), tb_timer_delay(), and tb_timer_spak().
tb_bool_t tb_timer_spak (tb_timer_ref_t timer)
spak timer for the external loop at the single thread
tb_void_t tb_timer_loop()
{
     while (1)
     {
         // wait
         wait(tb_timer_delay(timer))
         // spak timer
         tb_timer_spak(timer);
     }
}
Parameters
timer the timer
Returns
tb_true or tb_false
Definition at line 306 of file timer.c.
References tb_heap_pop(), tb_heap_put(), tb_heap_size(), tb_heap_top(), and tb_timer_task_func_t.
Referenced by tb_timer_loop().
tb_void_t tb_timer_task_exit (tb_timer_ref_t timer, tb_timer_task_ref_t task)
exit timer task, the task will be not called if have been not called
Parameters
timer the timer
task the timer task
Definition at line 561 of file timer.c.
tb_timer_task_ref_t tb_timer_task_init (tb_timer_ref_t timer, tb_size_t delay, tb_bool_t repeat, tb_timer_task_func_t func, tb_cpointer_t priv)
init and post timer task after delay and need remove it manually
Parameters
timer the timer
delay the delay time, ms
repeat is repeat?
func the timer func
priv the timer priv
Returns
the timer task
Definition at line 428 of file timer.c.
References tb_timer_task_init_at().
tb_timer_task_ref_t tb_timer_task_init_after (tb_timer_ref_t timer, tb_hize_t after, tb_size_t period, tb_bool_t repeat, tb_timer_task_func_t func, tb_cpointer_t priv)
init and post timer task after the relative time and need remove it manually
Parameters
timer the timer
after the after time, ms
period the period time, ms
repeat is repeat?
func the timer func
priv the timer priv
Returns
the timer task
Definition at line 487 of file timer.c.
References tb_timer_task_init_at().
tb_timer_task_ref_t tb_timer_task_init_at (tb_timer_ref_t timer, tb_hize_t when, tb_size_t period, tb_bool_t repeat, tb_timer_task_func_t func, tb_cpointer_t priv)
init and post timer task at the absolute time and need remove it manually
Parameters
timer the timer
when the absolute time, ms
period the period time, ms
repeat is repeat?
func the timer func
priv the timer priv
Returns
the timer task
Definition at line 437 of file timer.c.
References tb_event_post(), tb_heap_put(), tb_heap_size(), and tb_heap_top().
Referenced by tb_timer_task_init(), and tb_timer_task_init_after().
tb_void_t tb_timer_task_kill (tb_timer_ref_t timer, tb_timer_task_ref_t task)
kill timer task, the task will be called immediately if have been not called
Parameters
timer the timer
task the timer task
Definition at line 591 of file timer.c.
References tb_find_all_if(), tb_heap_del(), tb_heap_put(), and tb_iterator_tail().
tb_void_t tb_timer_task_post (tb_timer_ref_t timer, tb_size_t delay, tb_bool_t repeat, tb_timer_task_func_t func, tb_cpointer_t priv)
post timer task after delay and will be auto-remove it after be expired
Parameters
timer the timer
delay the delay time, ms
repeat is repeat?
func the timer func
priv the timer priv
Definition at line 496 of file timer.c.
References tb_timer_task_post_at().
tb_void_t tb_timer_task_post_after (tb_timer_ref_t timer, tb_hize_t after, tb_size_t period, tb_bool_t repeat, tb_timer_task_func_t func, tb_cpointer_t priv)
post timer task after the relative time and will be auto-remove it after be expired
Parameters
timer the timer
after the after time, ms
period the period time, ms
repeat is repeat?
func the timer func
priv the timer priv
Definition at line 552 of file timer.c.
References tb_timer_task_post_at().
tb_void_t tb_timer_task_post_at (tb_timer_ref_t timer, tb_hize_t when, tb_size_t period, tb_bool_t repeat, tb_timer_task_func_t func, tb_cpointer_t priv)
post timer task at the absolute time and will be auto-remove it after be expired
Parameters
timer the timer
when the absolute time, ms
period the period time, ms
repeat is repeat?
func the timer func
priv the timer priv
Definition at line 505 of file timer.c.
References tb_event_post(), tb_heap_put(), tb_heap_size(), and tb_heap_top().
Referenced by tb_timer_task_post(), and tb_timer_task_post_after().
tb_hize_t tb_timer_top (tb_timer_ref_t timer)
the timer top when
Parameters
timer the timer
Returns
the top when, -1: no task
Definition at line 245 of file timer.c.
References tb_heap_size(), and tb_heap_top().
Variable Documentation
__tb_extern_c_enter__ typedef tb_void_t(* tb_timer_task_func_t)(tb_bool_t killed, tb_cpointer_t priv)
the timer task func type
Parameters
killed is killed?
data the timer data
Definition at line 46 of file timer.h.
Referenced by tb_timer_spak().