TBOX: src/tbox/memory/buffer.c File Reference
buffer.c File Reference
Memory
#include "memory.h"
#include "../libc/libc.h"
#include "../utils/utils.h"
Macros
#define TB_BUFFER_GROW_SIZE (256)
Functions
tb_bool_t tb_buffer_init (tb_buffer_t *buffer)
tb_void_t tb_buffer_exit (tb_buffer_t *buffer)
tb_byte_t * tb_buffer_data (tb_buffer_t *buffer)
tb_size_t tb_buffer_size (tb_buffer_t const *buffer)
tb_size_t tb_buffer_maxn (tb_buffer_t const *buffer)
tb_void_t tb_buffer_clear (tb_buffer_t *buffer)
tb_byte_t * tb_buffer_resize (tb_buffer_t *buffer, tb_size_t size)
tb_byte_t * tb_buffer_memset (tb_buffer_t *buffer, tb_byte_t b)
tb_byte_t * tb_buffer_memsetp (tb_buffer_t *buffer, tb_size_t p, tb_byte_t b)
tb_byte_t * tb_buffer_memnset (tb_buffer_t *buffer, tb_byte_t b, tb_size_t n)
tb_byte_t * tb_buffer_memnsetp (tb_buffer_t *buffer, tb_size_t p, tb_byte_t b, tb_size_t n)
tb_byte_t * tb_buffer_memcpy (tb_buffer_t *buffer, tb_buffer_t *b)
tb_byte_t * tb_buffer_memcpyp (tb_buffer_t *buffer, tb_size_t p, tb_buffer_t *b)
tb_byte_t * tb_buffer_memncpy (tb_buffer_t *buffer, tb_byte_t const *b, tb_size_t n)
tb_byte_t * tb_buffer_memncpyp (tb_buffer_t *buffer, tb_size_t p, tb_byte_t const *b, tb_size_t n)
tb_byte_t * tb_buffer_memmov (tb_buffer_t *buffer, tb_size_t b)
tb_byte_t * tb_buffer_memmovp (tb_buffer_t *buffer, tb_size_t p, tb_size_t b)
tb_byte_t * tb_buffer_memnmov (tb_buffer_t *buffer, tb_size_t b, tb_size_t n)
tb_byte_t * tb_buffer_memnmovp (tb_buffer_t *buffer, tb_size_t p, tb_size_t b, tb_size_t n)
tb_byte_t * tb_buffer_memcat (tb_buffer_t *buffer, tb_buffer_t *b)
tb_byte_t * tb_buffer_memncat (tb_buffer_t *buffer, tb_byte_t const *b, tb_size_t n)
Detailed Description
The Treasure Box Library
TBox is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 2.1 of the License, or (at your option) any later version.
TBox is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with TBox; If not, see http://www.gnu.org/licenses/
Copyright (C) 2009 - 2015, ruki All rights reserved.
Author
ruki
Definition in file buffer.c.
Function Documentation
tb_void_t tb_buffer_clear (tb_buffer_t * buffer)
clear the buffer
Parameters
buffer the scoped buffer
Definition at line 98 of file buffer.c.
References tb_buffer_t::size.
Referenced by tb_buffer_exit(), tb_buffer_memnmovp(), tb_stream_filter_clos(), and tb_stream_filter_spak().
tb_byte_t* tb_buffer_data (tb_buffer_t * buffer)
the buffer data
Parameters
buffer the scoped buffer
Returns
the buffer data address
Definition at line 74 of file buffer.c.
References tb_buffer_t::data.
Referenced by tb_async_stream_sync_(), tb_buffer_memcat(), tb_buffer_memcpy(), tb_buffer_memcpyp(), tb_buffer_memncat(), tb_buffer_memncpyp(), tb_buffer_memnmovp(), tb_buffer_memnsetp(), tb_object_data_getp(), and tb_stream_filter_spak().
tb_void_t tb_buffer_exit (tb_buffer_t * buffer)
exit the scoped buffer
Parameters
buffer the scoped buffer
Definition at line 58 of file buffer.c.
References tb_buffer_t::buff, tb_buffer_t::data, tb_buffer_t::maxn, tb_buffer_t::size, and tb_buffer_clear().
Referenced by tb_aicp_ssl_exit(), tb_async_stream_exit(), and tb_stream_filter_exit().
tb_bool_t tb_buffer_init (tb_buffer_t * buffer)
init the scoped buffer
Parameters
buffer the scoped buffer
Returns
tb_true or tb_false
Definition at line 45 of file buffer.c.
References tb_buffer_t::buff, tb_buffer_t::data, tb_buffer_t::maxn, and tb_buffer_t::size.
Referenced by tb_aicp_ssl_init(), tb_async_stream_init(), tb_object_data_init_from_buffer(), and tb_object_data_init_from_data().
tb_size_t tb_buffer_maxn (tb_buffer_t const * buffer)
the buffer data maxn
Parameters
buffer the scoped buffer
Returns
the buffer data maxn
Definition at line 90 of file buffer.c.
References tb_buffer_t::maxn.
tb_byte_t* tb_buffer_memcat (tb_buffer_t * buffer, tb_buffer_t * b)
memcat: b +=> e ...
Parameters
buffer the scoped buffer
b the concated buffer
Returns
the buffer data address
Definition at line 292 of file buffer.c.
References tb_buffer_data(), tb_buffer_memncat(), and tb_buffer_size().
tb_byte_t* tb_buffer_memcpy (tb_buffer_t * buffer, tb_buffer_t * b)
memcpy: b => 0 ...
Parameters
buffer the scoped buffer
b the copied buffer
Returns
the buffer data address
Definition at line 223 of file buffer.c.
References tb_buffer_data(), tb_buffer_memncpyp(), and tb_buffer_size().
Referenced by tb_object_data_init_from_buffer().
tb_byte_t* tb_buffer_memcpyp (tb_buffer_t * buffer, tb_size_t p, tb_buffer_t * b)
memcpy: b => p ...
Parameters
buffer the scoped buffer
p the start position
b the copied buffer
Returns
the buffer data address
Definition at line 227 of file buffer.c.
References tb_buffer_data(), tb_buffer_memncpyp(), and tb_buffer_size().
tb_byte_t* tb_buffer_memmov (tb_buffer_t * buffer, tb_size_t b)
memmov: b ... e => 0 ...
Parameters
buffer the scoped buffer
b the moved start position
Returns
the buffer data address
Definition at line 253 of file buffer.c.
References tb_buffer_memnmovp(), and tb_buffer_size().
tb_byte_t* tb_buffer_memmovp (tb_buffer_t * buffer, tb_size_t p, tb_size_t b)
memmov: b ... e => p ...
Parameters
buffer the scoped buffer
p the moved destination position
b the moved start position
Returns
the buffer data address
Definition at line 259 of file buffer.c.
References tb_buffer_memnmovp(), and tb_buffer_size().
tb_byte_t* tb_buffer_memncat (tb_buffer_t * buffer, tb_byte_t const * b, tb_size_t n)
memcat: b ... n +=> e ...
Parameters
buffer the scoped buffer
b the concated buffer
n the concated count
Returns
the buffer data address
Definition at line 296 of file buffer.c.
References tb_buffer_data(), tb_buffer_memncpy(), tb_buffer_resize(), and tb_buffer_size().
Referenced by tb_buffer_memcat(), tb_stream_filter_push(), and tb_stream_filter_spak().
tb_byte_t* tb_buffer_memncpy (tb_buffer_t * buffer, tb_byte_t const * b, tb_size_t n)
memcpy: b ... n => 0 ...
Parameters
buffer the scoped buffer
b the copied buffer
n the copied count
Returns
the buffer data address
Definition at line 231 of file buffer.c.
References tb_buffer_memncpyp().
Referenced by tb_buffer_memncat(), tb_object_data_init_from_data(), and tb_object_data_setp().
tb_byte_t* tb_buffer_memncpyp (tb_buffer_t * buffer, tb_size_t p, tb_byte_t const * b, tb_size_t n)
memcpy: b ... n => p ...
Parameters
buffer the scoped buffer
p the start position
b the copied buffer
n the copied count
Returns
the buffer data address
Definition at line 235 of file buffer.c.
References tb_buffer_data(), and tb_buffer_resize().
Referenced by tb_buffer_memcpy(), tb_buffer_memcpyp(), and tb_buffer_memncpy().
tb_byte_t* tb_buffer_memnmov (tb_buffer_t * buffer, tb_size_t b, tb_size_t n)
memmov: b ... n => 0 ...
Parameters
buffer the scoped buffer
b the moved start position
n the moved count
Returns
the buffer data address
Definition at line 265 of file buffer.c.
References tb_buffer_memnmovp().
Referenced by tb_stream_filter_spak().
tb_byte_t* tb_buffer_memnmovp (tb_buffer_t * buffer, tb_size_t p, tb_size_t b, tb_size_t n)
memmov: b ... n => p ...
Parameters
buffer the scoped buffer
p the moved destination position
b the moved start position
n the moved count
Returns
the buffer data address
Definition at line 269 of file buffer.c.
References tb_buffer_clear(), tb_buffer_data(), tb_buffer_resize(), and tb_buffer_size().
Referenced by tb_buffer_memmov(), tb_buffer_memmovp(), and tb_buffer_memnmov().
tb_byte_t* tb_buffer_memnset (tb_buffer_t * buffer, tb_byte_t b, tb_size_t n)
memset: b => 0 ... n
Parameters
buffer the scoped buffer
b the filled byte
n the filled count
Returns
the buffer data address
Definition at line 201 of file buffer.c.
References tb_buffer_memnsetp().
tb_byte_t* tb_buffer_memnsetp (tb_buffer_t * buffer, tb_size_t p, tb_byte_t b, tb_size_t n)
memset: b => p ... n
Parameters
buffer the scoped buffer
p the start position
b the filled byte
n the filled count
Returns
the buffer data address
Definition at line 205 of file buffer.c.
References tb_buffer_data(), and tb_buffer_resize().
Referenced by tb_buffer_memnset(), tb_buffer_memset(), and tb_buffer_memsetp().
tb_byte_t* tb_buffer_memset (tb_buffer_t * buffer, tb_byte_t b)
memset: b => 0 ... e
Parameters
buffer the scoped buffer
b the filled byte
Returns
the buffer data address
Definition at line 193 of file buffer.c.
References tb_buffer_memnsetp(), and tb_buffer_size().
tb_byte_t* tb_buffer_memsetp (tb_buffer_t * buffer, tb_size_t p, tb_byte_t b)
memset: b => p ... e
Parameters
buffer the scoped buffer
p the start position
b the filled byte
Returns
the buffer data address
Definition at line 197 of file buffer.c.
References tb_buffer_memnsetp(), and tb_buffer_size().
tb_byte_t* tb_buffer_resize (tb_buffer_t * buffer, tb_size_t size)
resize the buffer size
Parameters
buffer the scoped buffer
size the new buffer size
Returns
the buffer data address
Definition at line 106 of file buffer.c.
References tb_buffer_t::buff, tb_buffer_t::data, tb_buffer_t::maxn, and tb_buffer_t::size.
Referenced by tb_buffer_memncat(), tb_buffer_memncpyp(), tb_buffer_memnmovp(), and tb_buffer_memnsetp().
tb_size_t tb_buffer_size (tb_buffer_t const * buffer)
the buffer data size
Parameters
buffer the scoped buffer
Returns
the buffer data size
Definition at line 82 of file buffer.c.
References tb_buffer_t::size.
Referenced by tb_async_stream_read_after_(), tb_async_stream_seek_(), tb_async_stream_sync_(), tb_buffer_memcat(), tb_buffer_memcpy(), tb_buffer_memcpyp(), tb_buffer_memmov(), tb_buffer_memmovp(), tb_buffer_memncat(), tb_buffer_memnmovp(), tb_buffer_memset(), tb_buffer_memsetp(), tb_object_data_size(), and tb_stream_filter_spak().