TBOX: src/tbox/platform/file.h File Reference
file.h File Reference
Platform
#include "prefix.h"
Data Structures
struct tb_file_info_t
the file info type
Macros
#define TB_FILE_DIRECT_ASIZE (512)
the aligned size for direct mode
#define TB_FILE_DIRECT_CSIZE (1 << 17)
the cached size for direct mode
Enumerations
enum tb_file_mode_t {
TB_FILE_MODE_RO = 1, TB_FILE_MODE_WO = 2, TB_FILE_MODE_RW = 4, TB_FILE_MODE_CREAT = 8,
TB_FILE_MODE_APPEND = 16, TB_FILE_MODE_TRUNC = 32, TB_FILE_MODE_BINARY = 64, TB_FILE_MODE_DIRECT = 128,
TB_FILE_MODE_ASIO = 256
}
the file mode type
enum tb_file_seek_flag_t { TB_FILE_SEEK_BEG = 0, TB_FILE_SEEK_CUR = 1, TB_FILE_SEEK_END = 2 }
the file seek type
enum tb_file_type_t {
TB_FILE_TYPE_NONE = 0, TB_FILE_TYPE_DIRECTORY = 1, TB_FILE_TYPE_FILE = 2, TB_FILE_TYPE_DOT = 3,
TB_FILE_TYPE_DOT2 = 4
}
the file type
Functions
tb_file_ref_t tb_file_init (tb_char_t const *path, tb_size_t mode)
tb_bool_t tb_file_exit (tb_file_ref_t file)
tb_long_t tb_file_read (tb_file_ref_t file, tb_byte_t *data, tb_size_t size)
tb_long_t tb_file_writ (tb_file_ref_t file, tb_byte_t const *data, tb_size_t size)
tb_long_t tb_file_pread (tb_file_ref_t file, tb_byte_t *data, tb_size_t size, tb_hize_t offset)
tb_long_t tb_file_pwrit (tb_file_ref_t file, tb_byte_t const *data, tb_size_t size, tb_hize_t offset)
tb_long_t tb_file_readv (tb_file_ref_t file, tb_iovec_t const *list, tb_size_t size)
tb_long_t tb_file_writv (tb_file_ref_t file, tb_iovec_t const *list, tb_size_t size)
tb_hong_t tb_file_writf (tb_file_ref_t file, tb_file_ref_t ifile, tb_hize_t offset, tb_hize_t size)
tb_long_t tb_file_preadv (tb_file_ref_t file, tb_iovec_t const *list, tb_size_t size, tb_hize_t offset)
tb_long_t tb_file_pwritv (tb_file_ref_t file, tb_iovec_t const *list, tb_size_t size, tb_hize_t offset)
tb_hong_t tb_file_seek (tb_file_ref_t file, tb_hong_t offset, tb_size_t mode)
tb_bool_t tb_file_sync (tb_file_ref_t file)
tb_hize_t tb_file_size (tb_file_ref_t file)
tb_hong_t tb_file_offset (tb_file_ref_t file)
tb_bool_t tb_file_info (tb_char_t const *path, tb_file_info_t *info)
tb_bool_t tb_file_copy (tb_char_t const *path, tb_char_t const *dest)
tb_bool_t tb_file_create (tb_char_t const *path)
tb_bool_t tb_file_remove (tb_char_t const *path)
tb_bool_t tb_file_rename (tb_char_t const *path, tb_char_t const *dest)
tb_char_t const * tb_file_full (tb_char_t const *path, tb_char_t *full, tb_size_t maxn)
tb_bool_t tb_file_link (tb_char_t const *path, tb_char_t const *dest)
Detailed Description
The Treasure Box Library
TBox is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 2.1 of the License, or (at your option) any later version.
TBox is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with TBox; If not, see http://www.gnu.org/licenses/
Copyright (C) 2009 - 2015, ruki All rights reserved.
Author
ruki
Definition in file file.h.
Enumeration Type Documentation
enum tb_file_mode_t
the file mode type
Enumerator
TB_FILE_MODE_RO
read only
TB_FILE_MODE_WO
writ only
TB_FILE_MODE_RW
read and writ
TB_FILE_MODE_CREAT
create
TB_FILE_MODE_APPEND
append
TB_FILE_MODE_TRUNC
truncate
TB_FILE_MODE_BINARY
binary
TB_FILE_MODE_DIRECT
direct, no cache,
Note
data & size must be aligned by TB_FILE_DIRECT_ASIZE
TB_FILE_MODE_ASIO
support for asio
Definition at line 56 of file file.h.
Function Documentation
tb_bool_t tb_file_copy (tb_char_t const * path, tb_char_t const * dest)
copy the file
Parameters
path the file path
dest the dest path
Returns
tb_true or tb_false
Definition at line 394 of file file.c.
References tb_file_exit(), tb_file_init(), TB_FILE_MODE_BINARY, TB_FILE_MODE_CREAT, TB_FILE_MODE_RW, TB_FILE_MODE_TRUNC, tb_file_size(), tb_file_writf(), and tb_transfer_done_url().
tb_bool_t tb_file_create (tb_char_t const * path)
create the file
Parameters
path the file path
Returns
tb_true or tb_false
Definition at line 431 of file file.c.
References tb_file_exit(), tb_file_init(), TB_FILE_MODE_CREAT, TB_FILE_MODE_TRUNC, and TB_FILE_MODE_WO.
tb_bool_t tb_file_exit (tb_file_ref_t file)
exit the file
Parameters
file the file
Returns
tb_true or tb_false
Definition at line 121 of file file.c.
Referenced by tb_aico_open_file_from_path(), tb_file_copy(), tb_file_create(), tb_trace_file_set(), and tb_trace_file_set_path().
tb_char_t const* tb_file_full (tb_char_t const * path, tb_char_t * full, tb_size_t maxn)
the file full path
Parameters
path the file path
full the full path
maxn the path maxn
Returns
the full path
tb_bool_t tb_file_info (tb_char_t const * path, tb_file_info_t * info)
the file info for file or directory
Parameters
file the file handle
info the file info
Returns
tb_true or tb_false
Definition at line 353 of file file.c.
References tb_file_info_t::atime, tb_file_info_t::mtime, tb_file_info_t::size, TB_PATH_MAXN, and tb_file_info_t::type.
Referenced by tb_directory_create(), tb_directory_walk(), and tb_file_init().
tb_file_ref_t tb_file_init (tb_char_t const * path, tb_size_t mode)
init the file
Parameters
path the file path
mode the file mode
Returns
the file
Definition at line 46 of file file.c.
References tb_file_info(), TB_FILE_MODE_APPEND, TB_FILE_MODE_ASIO, TB_FILE_MODE_CREAT, TB_FILE_MODE_DIRECT, TB_FILE_MODE_RO, TB_FILE_MODE_RW, TB_FILE_MODE_TRUNC, TB_FILE_MODE_WO, and TB_PATH_MAXN.
Referenced by tb_aico_open_file_from_path(), tb_file_copy(), tb_file_create(), and tb_trace_file_set_path().
tb_bool_t tb_file_link (tb_char_t const * path, tb_char_t const * dest)
link the file
Parameters
path the source file path
dest the destination file path
Returns
tb_true or tb_false
Definition at line 474 of file file.c.
References TB_PATH_MAXN.
tb_hong_t tb_file_offset (tb_file_ref_t file)
the file offset
Parameters
file the file
Returns
the file offset or -1
Definition at line 336 of file file.c.
References tb_file_seek().
Referenced by tb_file_preadv(), and tb_file_pwritv().
tb_long_t tb_file_pread (tb_file_ref_t file, tb_byte_t * data, tb_size_t size, tb_hize_t offset)
pread the file data
Parameters
file the file
data the data
size the size
offset the offset, the file offset will not be changed
Returns
the real size or -1
Definition at line 158 of file file.c.
Referenced by tb_file_writf(), and tb_socket_sendf().
tb_long_t tb_file_preadv (tb_file_ref_t file, tb_iovec_t const * list, tb_size_t size, tb_hize_t offset)
preadv the file data
Parameters
file the file
list the iovec list
size the iovec size
offset the offset, the file offset will not be changed
Returns
the real size or -1
Definition at line 248 of file file.c.
References tb_file_offset(), tb_file_readv(), and tb_file_seek().
tb_long_t tb_file_pwrit (tb_file_ref_t file, tb_byte_t const * data, tb_size_t size, tb_hize_t offset)
pwrit the file data
Parameters
file the file
data the data
size the size
offset the offset, the file offset will not be changed
Returns
the real size or -1
Definition at line 170 of file file.c.
tb_long_t tb_file_pwritv (tb_file_ref_t file, tb_iovec_t const * list, tb_size_t size, tb_hize_t offset)
pwritv the file data
Parameters
file the file
list the iovec list
size the iovec size
offset the offset, the file offset will not be changed
Returns
the real size or -1
Definition at line 282 of file file.c.
References tb_file_offset(), tb_file_seek(), and tb_file_writv().
tb_long_t tb_file_read (tb_file_ref_t file, tb_byte_t * data, tb_size_t size)
read the file data
Parameters
file the file
data the data
size the size
Returns
the real size or -1
Definition at line 142 of file file.c.
tb_long_t tb_file_readv (tb_file_ref_t file, tb_iovec_t const * list, tb_size_t size)
readv the file data
Parameters
file the file
list the iovec list
size the iovec size
Returns
the real size or -1
Definition at line 182 of file file.c.
Referenced by tb_file_preadv().
tb_bool_t tb_file_remove (tb_char_t const * path)
remove the file
Parameters
path the file path
Returns
tb_true or tb_false
Definition at line 443 of file file.c.
References TB_PATH_MAXN.
tb_bool_t tb_file_rename (tb_char_t const * path, tb_char_t const * dest)
rename the file
Parameters
path the source file path
dest the destination file path
Returns
tb_true or tb_false
Definition at line 456 of file file.c.
References TB_PATH_MAXN.
tb_hong_t tb_file_seek (tb_file_ref_t file, tb_hong_t offset, tb_size_t mode)
seek the file offset
Parameters
file the file
offset the file offset
mode the seek mode
Returns
the real offset or -1
Definition at line 328 of file file.c.
Referenced by tb_file_offset(), tb_file_preadv(), and tb_file_pwritv().
tb_hize_t tb_file_size (tb_file_ref_t file)
the file size
Parameters
file the file
Returns
the file size
Definition at line 344 of file file.c.
Referenced by tb_file_copy().
tb_bool_t tb_file_sync (tb_file_ref_t file)
fsync the file
Parameters
file the file
Definition at line 316 of file file.c.
tb_long_t tb_file_writ (tb_file_ref_t file, tb_byte_t const * data, tb_size_t size)
writ the file data
Parameters
file the file
data the data
size the size
Returns
the real size or -1
Definition at line 150 of file file.c.
Referenced by tb_file_writf(), tb_trace_done_with_args(), and tb_trace_tail().
tb_hong_t tb_file_writf (tb_file_ref_t file, tb_file_ref_t ifile, tb_hize_t offset, tb_hize_t size)
writf the file data
Parameters
file the file
ifile the input file
offset the input file offset, the file offset will not be changed
size the writed size
Returns
the real size or -1
Definition at line 208 of file file.c.
References tb_file_pread(), and tb_file_writ().
Referenced by tb_file_copy().
tb_long_t tb_file_writv (tb_file_ref_t file, tb_iovec_t const * list, tb_size_t size)
writv the file data
Parameters
file the file
list the iovec list
size the iovec size
Returns
the real size or -1
Definition at line 195 of file file.c.
Referenced by tb_file_pwritv().