TBOX: src/tbox/container/heap.h File Reference
heap.h File Reference
Container
#include "prefix.h"
#include "item.h"
#include "iterator.h"
Functions
tb_heap_ref_t tb_heap_init (tb_size_t grow, tb_item_func_t func)
tb_void_t tb_heap_exit (tb_heap_ref_t heap)
tb_void_t tb_heap_clear (tb_heap_ref_t heap)
tb_size_t tb_heap_size (tb_heap_ref_t heap)
tb_size_t tb_heap_grow (tb_heap_ref_t heap)
tb_size_t tb_heap_maxn (tb_heap_ref_t heap)
tb_pointer_t tb_heap_top (tb_heap_ref_t heap)
tb_void_t tb_heap_put (tb_heap_ref_t heap, tb_cpointer_t data)
tb_void_t tb_heap_pop (tb_heap_ref_t heap)
tb_void_t tb_heap_del (tb_heap_ref_t heap, tb_size_t itor)
tb_bool_t tb_heap_load (tb_heap_ref_t heap, tb_stream_ref_t stream)
tb_bool_t tb_heap_save (tb_heap_ref_t heap, tb_stream_ref_t stream)
Variables
__tb_extern_c_enter__ typedef
tb_iterator_ref_t tb_heap_ref_t
Detailed Description
The Treasure Box Library
TBox is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 2.1 of the License, or (at your option) any later version.
TBox is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with TBox; If not, see http://www.gnu.org/licenses/
Copyright (C) 2009 - 2015, ruki All rights reserved.
Author
ruki
Definition in file heap.h.
Function Documentation
tb_void_t tb_heap_clear (tb_heap_ref_t heap)
clear the heap
Parameters
heap the heap
Definition at line 484 of file heap.c.
Referenced by tb_heap_exit(), tb_heap_load(), and tb_timer_clear().
tb_void_t tb_heap_del (tb_heap_ref_t heap, tb_size_t itor)
del the heap item
Parameters
heap the heap
itor the itor
Definition at line 674 of file heap.c.
Referenced by tb_timer_task_kill().
tb_void_t tb_heap_exit (tb_heap_ref_t heap)
exist heap
Parameters
heap the heap
Definition at line 468 of file heap.c.
References tb_heap_clear().
Referenced by tb_heap_init(), and tb_timer_exit().
tb_size_t tb_heap_grow (tb_heap_ref_t heap)
the heap grow
Parameters
heap the heap
Returns
the heap grow
Definition at line 506 of file heap.c.
tb_heap_ref_t tb_heap_init (tb_size_t grow, tb_item_func_t func)
init heap, default: minheap
Parameters
grow the item grow
func the item func
Returns
the heap
Definition at line 411 of file heap.c.
References tb_item_func_t::data, tb_item_func_t::dupl, tb_item_func_t::repl, tb_item_func_t::size, tb_heap_exit(), tb_heap_ref_t, TB_ITERATOR_MODE_FORWARD, TB_ITERATOR_MODE_MUTABLE, TB_ITERATOR_MODE_RACCESS, and TB_ITERATOR_MODE_REVERSE.
Referenced by tb_timer_init().
tb_bool_t tb_heap_load (tb_heap_ref_t heap, tb_stream_ref_t stream)
load heap from the stream
Parameters
heap the heap
stream the stream
Returns
tb_true or tb_false
Definition at line 678 of file heap.c.
References tb_crc_encode_cstr(), tb_heap_clear(), tb_heap_put(), tb_stream_bread_u32_be(), tb_stream_offset(), and tb_stream_seek().
tb_size_t tb_heap_maxn (tb_heap_ref_t heap)
the heap maxn
Parameters
heap the heap
Returns
the heap maxn
Definition at line 515 of file heap.c.
tb_void_t tb_heap_pop (tb_heap_ref_t heap)
pop the heap item
Parameters
heap the heap
Definition at line 670 of file heap.c.
Referenced by tb_timer_spak().
tb_void_t tb_heap_put (tb_heap_ref_t heap, tb_cpointer_t data)
put the heap item
Parameters
heap the heap
data the item data
put impl
init:
                                     1(head)
                          -------------------------
                         |                         |
                         4                         2
                   --------------             -------------
                  |              |           |             |
                  6(parent)      9           7             8
              ---------
             |         |
             10(last) (hole) <= 5(val)
after:
                                     1(head)
                          -------------------------
                         |                         |
                         4                         2
                   --------------             -------------
                  |              |           |             |
                  5(hole)      9           7             8
              ---------
             |         |
             10(last)  6(last)
Definition at line 557 of file heap.c.
Referenced by tb_heap_load(), tb_timer_spak(), tb_timer_task_init_at(), tb_timer_task_kill(), and tb_timer_task_post_at().
tb_bool_t tb_heap_save (tb_heap_ref_t heap, tb_stream_ref_t stream)
save heap to the stream
Parameters
heap the heap
stream the stream
Returns
tb_true or tb_false
Definition at line 768 of file heap.c.
References tb_crc_encode_cstr(), tb_for_all, tb_heap_size(), tb_stream_bwrit_u32_be(), tb_stream_offset(), and tb_stream_seek().
tb_size_t tb_heap_size (tb_heap_ref_t heap)
the heap size
Parameters
heap the heap
Returns
the heap size
Definition at line 497 of file heap.c.
Referenced by tb_heap_save(), tb_timer_delay(), tb_timer_spak(), tb_timer_task_init_at(), tb_timer_task_post_at(), and tb_timer_top().
tb_pointer_t tb_heap_top (tb_heap_ref_t heap)
the heap top item
Parameters
heap the heap
Returns
the heap top item
Definition at line 524 of file heap.c.
References tb_iterator_head(), and tb_iterator_item().
Referenced by tb_timer_delay(), tb_timer_spak(), tb_timer_task_init_at(), tb_timer_task_post_at(), and tb_timer_top().
Variable Documentation
__tb_extern_c_enter__ typedef tb_iterator_ref_t tb_heap_ref_t
the head ref type
heap:    1      4      2      6       9       7       8       10       14       16
                                         1(head)
                              -------------------------
                             |                         |
                             4                         2
                       --------------             -------------
                      |              |           |             |
                      6       (last / 2 - 1)9    7             8
                  ---------       ----
                 |         |     |
                 10        14    16(last - 1)
performance:
put: O(lgn) pop: O(1) top: O(1)
iterator:
next: fast prev: fast
Note
the itor of the same item is mutable
Definition at line 75 of file heap.h.
Referenced by tb_heap_init().