TBOX: src/tbox/algorithm/count.h File Reference
count.h File Reference
Algorithm
#include "prefix.h"
Functions
__tb_extern_c_enter__ tb_size_t tb_count (tb_iterator_ref_t iterator, tb_size_t head, tb_size_t tail, tb_cpointer_t item)
tb_size_t tb_count_all (tb_iterator_ref_t iterator, tb_cpointer_t item)
Detailed Description
The Treasure Box Library
TBox is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 2.1 of the License, or (at your option) any later version.
TBox is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with TBox; If not, see http://www.gnu.org/licenses/
Copyright (C) 2009 - 2015, ruki All rights reserved.
Author
ruki
Definition in file count.h.
Function Documentation
__tb_extern_c_enter__ tb_size_t tb_count (tb_iterator_ref_t iterator, tb_size_t head, tb_size_t tail, tb_cpointer_t item)
count item
Parameters
iterator the iterator
head the iterator head
tail the iterator tail
item the counted item
Returns
the real count
Definition at line 34 of file count.c.
References tb_count_if(), and tb_iterator_comp().
tb_size_t tb_count_all (tb_iterator_ref_t iterator, tb_cpointer_t item)
count item for all
Parameters
iterator the iterator
item the counted item
Returns
the real count
Definition at line 38 of file count.c.
References tb_count_all_if(), and tb_iterator_comp().