TBOX: src/tbox/stream/async_stream.h File Reference
async_stream.h File Reference
Stream
#include "prefix.h"
#include "../asio/asio.h"
#include "../libc/libc.h"
#include "../network/url.h"
#include "../memory/memory.h"
Macros
#define tb_async_stream_open(stream, func, priv) tb_async_stream_open_(stream, func, priv __tb_debug_vals__)
open
#define tb_async_stream_clos(stream, func, priv) tb_async_stream_clos_(stream, func, priv __tb_debug_vals__)
clos
#define tb_async_stream_read(stream, size, func, priv) tb_async_stream_read_(stream, size, func, priv __tb_debug_vals__)
read
#define tb_async_stream_writ(stream, data, size, func, priv) tb_async_stream_writ_(stream, data, size, func, priv __tb_debug_vals__)
writ
#define tb_async_stream_seek(stream, offset, func, priv) tb_async_stream_seek_(stream, offset, func, priv __tb_debug_vals__)
seek
#define tb_async_stream_sync(stream, bclosing, func, priv) tb_async_stream_sync_(stream, bclosing, func, priv __tb_debug_vals__)
sync
#define tb_async_stream_task(stream, delay, func, priv) tb_async_stream_task_(stream, delay, func, priv __tb_debug_vals__)
task
#define tb_async_stream_open_read(stream, size, func, priv) tb_async_stream_open_read_(stream, size, func, priv __tb_debug_vals__)
open and read
#define tb_async_stream_open_writ(stream, data, size, func, priv) tb_async_stream_open_writ_(stream, data, size, func, priv __tb_debug_vals__)
open and writ
#define tb_async_stream_open_seek(stream, offset, func, priv) tb_async_stream_open_seek_(stream, offset, func, priv __tb_debug_vals__)
open and seek
#define tb_async_stream_read_after(stream, delay, size, func, priv) tb_async_stream_read_after_(stream, delay, size, func, priv __tb_debug_vals__)
read after delay
#define tb_async_stream_writ_after(stream, delay, data, size, func, priv) tb_async_stream_writ_after_(stream, delay, data, size, func, priv __tb_debug_vals__)
writ after delay
Typedefs
typedef tb_bool_t(* tb_async_stream_open_func_t)(tb_async_stream_ref_t stream, tb_size_t state, tb_cpointer_t priv)
typedef tb_void_t(* tb_async_stream_clos_func_t)(tb_async_stream_ref_t stream, tb_size_t state, tb_cpointer_t priv)
typedef tb_bool_t(* tb_async_stream_read_func_t)(tb_async_stream_ref_t stream, tb_size_t state, tb_byte_t const *data, tb_size_t real, tb_size_t size, tb_cpointer_t priv)
typedef tb_bool_t(* tb_async_stream_writ_func_t)(tb_async_stream_ref_t stream, tb_size_t state, tb_byte_t const *data, tb_size_t real, tb_size_t size, tb_cpointer_t priv)
typedef tb_bool_t(* tb_async_stream_seek_func_t)(tb_async_stream_ref_t stream, tb_size_t state, tb_hize_t offset, tb_cpointer_t priv)
typedef tb_bool_t(* tb_async_stream_sync_func_t)(tb_async_stream_ref_t stream, tb_size_t state, tb_bool_t bclosing, tb_cpointer_t priv)
typedef tb_bool_t(* tb_async_stream_task_func_t)(tb_async_stream_ref_t stream, tb_size_t state, tb_cpointer_t priv)
Functions
tb_async_stream_ref_t tb_async_stream_init (tb_aicp_ref_t aicp, tb_size_t type, tb_size_t type_size, tb_size_t rcache, tb_size_t wcache, tb_bool_t(*open_try)(tb_async_stream_ref_t stream), tb_bool_t(*clos_try)(tb_async_stream_ref_t stream), tb_bool_t(*open)(tb_async_stream_ref_t stream, tb_async_stream_open_func_t func, tb_cpointer_t priv), tb_bool_t(*clos)(tb_async_stream_ref_t stream, tb_async_stream_clos_func_t func, tb_cpointer_t priv), tb_bool_t(*exit)(tb_async_stream_ref_t stream), tb_void_t(*kill)(tb_async_stream_ref_t stream), tb_bool_t(*ctrl)(tb_async_stream_ref_t stream, tb_size_t ctrl, tb_va_list_t args), tb_bool_t(*read)(tb_async_stream_ref_t stream, tb_size_t delay, tb_byte_t *data, tb_size_t size, tb_async_stream_read_func_t func, tb_cpointer_t priv), tb_bool_t(*writ)(tb_async_stream_ref_t stream, tb_size_t delay, tb_byte_t const *data, tb_size_t size, tb_async_stream_writ_func_t func, tb_cpointer_t priv), tb_bool_t(*seek)(tb_async_stream_ref_t stream, tb_hize_t offset, tb_async_stream_seek_func_t func, tb_cpointer_t priv), tb_bool_t(*sync)(tb_async_stream_ref_t stream, tb_bool_t bclosing, tb_async_stream_sync_func_t func, tb_cpointer_t priv), tb_bool_t(*task)(tb_async_stream_ref_t stream, tb_size_t delay, tb_async_stream_task_func_t func, tb_cpointer_t priv))
tb_async_stream_ref_t tb_async_stream_init_data (tb_aicp_ref_t aicp)
tb_async_stream_ref_t tb_async_stream_init_file (tb_aicp_ref_t aicp)
tb_async_stream_ref_t tb_async_stream_init_sock (tb_aicp_ref_t aicp)
tb_async_stream_ref_t tb_async_stream_init_http (tb_aicp_ref_t aicp)
tb_async_stream_ref_t tb_async_stream_init_filter (tb_aicp_ref_t aicp)
tb_bool_t tb_async_stream_exit (tb_async_stream_ref_t stream)
tb_async_stream_ref_t tb_async_stream_init_from_url (tb_aicp_ref_t aicp, tb_char_t const *url)
tb_async_stream_ref_t tb_async_stream_init_from_data (tb_aicp_ref_t aicp, tb_byte_t const *data, tb_size_t size)
tb_async_stream_ref_t tb_async_stream_init_from_file (tb_aicp_ref_t aicp, tb_char_t const *path, tb_size_t mode)
tb_async_stream_ref_t tb_async_stream_init_from_sock (tb_aicp_ref_t aicp, tb_char_t const *host, tb_uint16_t port, tb_size_t type, tb_bool_t bssl)
tb_async_stream_ref_t tb_async_stream_init_from_http (tb_aicp_ref_t aicp, tb_char_t const *host, tb_uint16_t port, tb_char_t const *path, tb_bool_t bssl)
tb_async_stream_ref_t tb_async_stream_init_filter_from_null (tb_async_stream_ref_t stream)
tb_async_stream_ref_t tb_async_stream_init_filter_from_zip (tb_async_stream_ref_t stream, tb_size_t algo, tb_size_t action)
tb_async_stream_ref_t tb_async_stream_init_filter_from_cache (tb_async_stream_ref_t stream, tb_size_t size)
tb_async_stream_ref_t tb_async_stream_init_filter_from_charset (tb_async_stream_ref_t stream, tb_size_t fr, tb_size_t to)
tb_async_stream_ref_t tb_async_stream_init_filter_from_chunked (tb_async_stream_ref_t stream, tb_bool_t dechunked)
tb_url_t * tb_async_stream_url (tb_async_stream_ref_t stream)
tb_size_t tb_async_stream_type (tb_async_stream_ref_t stream)
tb_hong_t tb_async_stream_size (tb_async_stream_ref_t stream)
tb_hize_t tb_async_stream_left (tb_async_stream_ref_t stream)
tb_bool_t tb_async_stream_beof (tb_async_stream_ref_t stream)
tb_hize_t tb_async_stream_offset (tb_async_stream_ref_t stream)
tb_bool_t tb_async_stream_is_opened (tb_async_stream_ref_t stream)
tb_bool_t tb_async_stream_is_closed (tb_async_stream_ref_t stream)
tb_bool_t tb_async_stream_is_killed (tb_async_stream_ref_t stream)
tb_long_t tb_async_stream_timeout (tb_async_stream_ref_t stream)
tb_bool_t tb_async_stream_ctrl (tb_async_stream_ref_t stream, tb_size_t ctrl,...)
tb_bool_t tb_async_stream_ctrl_with_args (tb_async_stream_ref_t stream, tb_size_t ctrl, tb_va_list_t args)
tb_void_t tb_async_stream_kill (tb_async_stream_ref_t stream)
tb_bool_t tb_async_stream_open_try (tb_async_stream_ref_t stream)
tb_bool_t tb_async_stream_open_ (tb_async_stream_ref_t stream, tb_async_stream_open_func_t func, tb_cpointer_t priv __tb_debug_decl__)
tb_bool_t tb_async_stream_clos_try (tb_async_stream_ref_t stream)
tb_bool_t tb_async_stream_clos_ (tb_async_stream_ref_t stream, tb_async_stream_clos_func_t func, tb_cpointer_t priv __tb_debug_decl__)
tb_bool_t tb_async_stream_read_ (tb_async_stream_ref_t stream, tb_size_t size, tb_async_stream_read_func_t func, tb_cpointer_t priv __tb_debug_decl__)
tb_bool_t tb_async_stream_writ_ (tb_async_stream_ref_t stream, tb_byte_t const *data, tb_size_t size, tb_async_stream_writ_func_t func, tb_cpointer_t priv __tb_debug_decl__)
tb_bool_t tb_async_stream_seek_ (tb_async_stream_ref_t stream, tb_hize_t offset, tb_async_stream_seek_func_t func, tb_cpointer_t priv __tb_debug_decl__)
tb_bool_t tb_async_stream_sync_ (tb_async_stream_ref_t stream, tb_bool_t bclosing, tb_async_stream_sync_func_t func, tb_cpointer_t priv __tb_debug_decl__)
tb_bool_t tb_async_stream_task_ (tb_async_stream_ref_t stream, tb_size_t delay, tb_async_stream_task_func_t func, tb_cpointer_t priv __tb_debug_decl__)
tb_bool_t tb_async_stream_open_read_ (tb_async_stream_ref_t stream, tb_size_t size, tb_async_stream_read_func_t func, tb_cpointer_t priv __tb_debug_decl__)
tb_bool_t tb_async_stream_open_writ_ (tb_async_stream_ref_t stream, tb_byte_t const *data, tb_size_t size, tb_async_stream_writ_func_t func, tb_cpointer_t priv __tb_debug_decl__)
tb_bool_t tb_async_stream_open_seek_ (tb_async_stream_ref_t stream, tb_hize_t offset, tb_async_stream_seek_func_t func, tb_cpointer_t priv __tb_debug_decl__)
tb_bool_t tb_async_stream_read_after_ (tb_async_stream_ref_t stream, tb_size_t delay, tb_size_t size, tb_async_stream_read_func_t func, tb_cpointer_t priv __tb_debug_decl__)
tb_bool_t tb_async_stream_writ_after_ (tb_async_stream_ref_t stream, tb_size_t delay, tb_byte_t const *data, tb_size_t size, tb_async_stream_writ_func_t func, tb_cpointer_t priv __tb_debug_decl__)
tb_aicp_ref_t tb_async_stream_aicp (tb_async_stream_ref_t stream)
Detailed Description
The Treasure Box Library
TBox is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 2.1 of the License, or (at your option) any later version.
TBox is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with TBox; If not, see http://www.gnu.org/licenses/
Copyright (C) 2009 - 2015, ruki All rights reserved.
Author
ruki
Definition in file async_stream.h.
Typedef Documentation
typedef tb_void_t(* tb_async_stream_clos_func_t)(tb_async_stream_ref_t stream, tb_size_t state, tb_cpointer_t priv)
the stream clos func type
Parameters
stream the stream
state the state
priv the func private data
Definition at line 101 of file async_stream.h.
typedef tb_bool_t(* tb_async_stream_open_func_t)(tb_async_stream_ref_t stream, tb_size_t state, tb_cpointer_t priv)
the stream open func type
Parameters
stream the stream
state the state
priv the func private data
Returns
tb_true: ok, tb_false: error, but not break aicp
Definition at line 93 of file async_stream.h.
typedef tb_bool_t(* tb_async_stream_read_func_t)(tb_async_stream_ref_t stream, tb_size_t state, tb_byte_t const *data, tb_size_t real, tb_size_t size, tb_cpointer_t priv)
the stream read func type
Parameters
stream the stream
state the state
data the readed data
real the real size, maybe zero
size the need size
priv the func private data
Returns
tb_true: ok and continue it if need, tb_false: break it, but not break aicp
Definition at line 114 of file async_stream.h.
typedef tb_bool_t(* tb_async_stream_seek_func_t)(tb_async_stream_ref_t stream, tb_size_t state, tb_hize_t offset, tb_cpointer_t priv)
the stream seek func type
Parameters
stream the stream
state the state
offset the real offset
priv the func private data
Returns
tb_true: ok, tb_false: error, but not break aicp
Definition at line 138 of file async_stream.h.
typedef tb_bool_t(* tb_async_stream_sync_func_t)(tb_async_stream_ref_t stream, tb_size_t state, tb_bool_t bclosing, tb_cpointer_t priv)
the stream sync func type
Parameters
stream the stream
state the state
bclosing is closing?
priv the func private data
Returns
tb_true: ok, tb_false: error, but not break aicp
Definition at line 149 of file async_stream.h.
typedef tb_bool_t(* tb_async_stream_task_func_t)(tb_async_stream_ref_t stream, tb_size_t state, tb_cpointer_t priv)
the stream task func type
Parameters
stream the stream
state the state
priv the func private data
Returns
tb_true: ok, tb_false: error, but not break aicp
Definition at line 159 of file async_stream.h.
typedef tb_bool_t(* tb_async_stream_writ_func_t)(tb_async_stream_ref_t stream, tb_size_t state, tb_byte_t const *data, tb_size_t real, tb_size_t size, tb_cpointer_t priv)
the stream writ func type
Parameters
stream the stream
state the state
data the writed data
real the real size, maybe zero
size the need size
priv the func private data
Returns
tb_true: ok and continue it if need, tb_false: break it, but not break aicp
Definition at line 127 of file async_stream.h.
Function Documentation
tb_aicp_ref_t tb_async_stream_aicp (tb_async_stream_ref_t stream)
the stream aicp
Parameters
stream the stream
Returns
the stream aicp
Definition at line 1302 of file async_stream.c.
Referenced by tb_async_stream_init_filter_from_cache(), tb_async_stream_init_filter_from_charset(), tb_async_stream_init_filter_from_chunked(), tb_async_stream_init_filter_from_null(), tb_async_stream_init_filter_from_zip(), and tb_async_stream_init_http().
tb_bool_t tb_async_stream_beof (tb_async_stream_ref_t stream)
the stream is end?
Parameters
stream the stream
Returns
tb_true or tb_false
Definition at line 678 of file async_stream.c.
References tb_async_stream_offset(), and tb_async_stream_size().
tb_bool_t tb_async_stream_clos_ (tb_async_stream_ref_t stream, tb_async_stream_clos_func_t func, tb_cpointer_t priv __tb_debug_decl__)
close the stream
Parameters
stream the stream
func the func
priv the func data
Returns
tb_true or tb_false
Definition at line 1065 of file async_stream.c.
References tb_async_stream_clos_try().
tb_bool_t tb_async_stream_clos_try (tb_async_stream_ref_t stream)
try closing the stream for stream: file, filter, or closed stream...
Parameters
stream the stream
Returns
tb_true or tb_false
Definition at line 1031 of file async_stream.c.
References tb_async_stream_is_closed().
Referenced by tb_async_stream_clos_(), tb_async_stream_exit(), and tb_async_transfer_clos_try().
tb_bool_t tb_async_stream_ctrl (tb_async_stream_ref_t stream, tb_size_t ctrl, ...)
ctrl stream
Parameters
stream the stream
ctrl the ctrl code
Returns
tb_true or tb_false
Definition at line 744 of file async_stream.c.
References tb_async_stream_ctrl_with_args().
Referenced by tb_async_stream_init_filter_from_cache(), tb_async_stream_init_filter_from_charset(), tb_async_stream_init_filter_from_chunked(), tb_async_stream_init_filter_from_null(), tb_async_stream_init_filter_from_zip(), tb_async_stream_init_from_data(), tb_async_stream_init_from_file(), tb_async_stream_init_from_http(), tb_async_stream_init_from_sock(), tb_async_stream_init_from_url(), tb_async_stream_offset(), tb_async_stream_size(), tb_async_stream_timeout(), tb_async_transfer_init_istream_from_data(), tb_async_transfer_init_istream_from_url(), tb_async_transfer_init_ostream_from_data(), and tb_async_transfer_init_ostream_from_url().
tb_bool_t tb_async_stream_ctrl_with_args (tb_async_stream_ref_t stream, tb_size_t ctrl, tb_va_list_t args)
ctrl stream with arguments
Parameters
stream the stream
ctrl the ctrl code
args the ctrl args
Returns
tb_true or tb_false
Definition at line 763 of file async_stream.c.
References tb_async_stream_is_closed().
Referenced by tb_async_stream_ctrl(), tb_async_transfer_ctrl_istream(), and tb_async_transfer_ctrl_ostream().
tb_bool_t tb_async_stream_exit (tb_async_stream_ref_t stream)
exit stream
Parameters
stream the stream
Returns
tb_true or tb_false
Definition at line 585 of file async_stream.c.
References tb_async_stream_clos_try(), tb_async_stream_kill(), and tb_buffer_exit().
Referenced by tb_async_stream_init(), tb_async_stream_init_filter_from_cache(), tb_async_stream_init_filter_from_charset(), tb_async_stream_init_filter_from_chunked(), tb_async_stream_init_filter_from_null(), tb_async_stream_init_filter_from_zip(), tb_async_stream_init_from_data(), tb_async_stream_init_from_file(), tb_async_stream_init_from_http(), tb_async_stream_init_from_sock(), tb_async_stream_init_from_url(), tb_async_stream_init_http(), tb_async_transfer_exit(), tb_async_transfer_init_istream(), tb_async_transfer_init_istream_from_data(), tb_async_transfer_init_istream_from_url(), tb_async_transfer_init_ostream(), tb_async_transfer_init_ostream_from_data(), and tb_async_transfer_init_ostream_from_url().
tb_async_stream_ref_t tb_async_stream_init (tb_aicp_ref_t aicp, tb_size_t type, tb_size_t type_size, tb_size_t rcache, tb_size_t wcache, tb_bool_t(*)(tb_async_stream_ref_t stream) open_try, tb_bool_t(*)(tb_async_stream_ref_t stream) clos_try, tb_bool_t(*)(tb_async_stream_ref_t stream, tb_async_stream_open_func_t func, tb_cpointer_t priv) open, tb_bool_t(*)(tb_async_stream_ref_t stream, tb_async_stream_clos_func_t func, tb_cpointer_t priv) clos, tb_bool_t(*)(tb_async_stream_ref_t stream) exit, tb_void_t(*)(tb_async_stream_ref_t stream) kill, tb_bool_t(*)(tb_async_stream_ref_t stream, tb_size_t ctrl, tb_va_list_t args) ctrl, tb_bool_t(*)(tb_async_stream_ref_t stream, tb_size_t delay, tb_byte_t *data, tb_size_t size, tb_async_stream_read_func_t func, tb_cpointer_t priv) read, tb_bool_t(*)(tb_async_stream_ref_t stream, tb_size_t delay, tb_byte_t const *data, tb_size_t size, tb_async_stream_writ_func_t func, tb_cpointer_t priv) writ, tb_bool_t(*)(tb_async_stream_ref_t stream, tb_hize_t offset, tb_async_stream_seek_func_t func, tb_cpointer_t priv) seek, tb_bool_t(*)(tb_async_stream_ref_t stream, tb_bool_t bclosing, tb_async_stream_sync_func_t func, tb_cpointer_t priv) sync, tb_bool_t(*)(tb_async_stream_ref_t stream, tb_size_t delay, tb_async_stream_task_func_t func, tb_cpointer_t priv) task)
init async stream
Parameters
aicp the aicp
type the stream type
type_size the stream type size
rcache the read cache size
wcache the writ cache size
open the stream impl func: open
clos the stream impl func: clos
exit the stream impl func: exit, optional
ctrl the stream impl func: ctrl
wait the stream impl func: wait
read the stream impl func: read
writ the stream impl func: writ
seek the stream impl func: seek, optional
sync the stream impl func: sync, optional
kill the stream impl func: kill, optional
Returns
the stream
// the custom xxxx async stream type
typedef struct __tb_async_stream_xxxx_impl_t
{
    // the xxxx data
    tb_handle_t         xxxx;
}tb_async_stream_xxxx_impl_t;
static tb_bool_t tb_async_stream_xxxx_impl_open(tb_async_stream_ref_t stream, tb_async_stream_open_func_t func, tb_cpointer_t priv)
{
    // check
    tb_async_stream_xxxx_impl_t* impl = (tb_async_stream_xxxx_impl_t*)stream;
    tb_assert_and_check_return_val(impl, tb_false);
    // ok
    return tb_true;
}
static tb_bool_t tb_async_stream_xxxx_impl_clos(tb_async_stream_ref_t stream, tb_async_stream_clos_func_t, tb_cpointer_t priv)
{
    // check
    tb_async_stream_xxxx_impl_t* impl = (tb_async_stream_xxxx_impl_t*)stream;
    tb_assert_and_check_return_val(impl, tb_false);
    // ok
    return tb_true;
}
// define other xxxx async stream func
// ...
// init async stream
tb_async_stream_ref_t stream = tb_async_stream_init(tb_aicp()
                                                    ,   TB_STREAM_TYPE_XXXX
                                                    ,   sizeof(tb_async_stream_xxxx_impl_t)
                                                    ,   0
                                                    ,   0
                                                    ,   tb_async_stream_xxxx_impl_open_try
                                                    ,   tb_async_stream_xxxx_impl_clos_try
                                                    ,   tb_async_stream_xxxx_impl_open
                                                    ,   tb_async_stream_xxxx_impl_clos
                                                    ,   tb_async_stream_xxxx_impl_exit
                                                    ,   tb_async_stream_xxxx_impl_kill
                                                    ,   tb_async_stream_xxxx_impl_ctrl
                                                    ,   tb_async_stream_xxxx_impl_read
                                                    ,   tb_async_stream_xxxx_impl_writ
                                                    ,   tb_async_stream_xxxx_impl_seek
                                                    ,   tb_async_stream_xxxx_impl_sync
                                                    ,   tb_async_stream_xxxx_impl_task
                                                    );
// using async stream
// ...
Definition at line 436 of file async_stream.c.
References tb_aicp(), tb_async_stream_exit(), and tb_buffer_init().
Referenced by tb_async_stream_init_data(), tb_async_stream_init_file(), tb_async_stream_init_filter(), tb_async_stream_init_http(), and tb_async_stream_init_sock().
tb_async_stream_ref_t tb_async_stream_init_data (tb_aicp_ref_t aicp)
init data stream
Parameters
aicp the aicp, using the default aicp if be null
Returns
the stream
Definition at line 652 of file data.c.
References tb_async_stream_init().
Referenced by tb_async_stream_init_from_data(), and tb_async_stream_init_from_url().
tb_async_stream_ref_t tb_async_stream_init_file (tb_aicp_ref_t aicp)
init file stream
Parameters
aicp the aicp, using the default aicp if be null
Returns
the stream
Definition at line 554 of file file.c.
References tb_async_stream_init(), TB_FILE_MODE_BINARY, and TB_FILE_MODE_RO.
Referenced by tb_async_stream_init_from_file(), and tb_async_stream_init_from_url().
tb_async_stream_ref_t tb_async_stream_init_filter (tb_aicp_ref_t aicp)
init filter stream
Parameters
aicp the aicp, using the default aicp if be null
Returns
the stream
Definition at line 683 of file filter.c.
References tb_async_stream_init().
Referenced by tb_async_stream_init_filter_from_cache(), tb_async_stream_init_filter_from_charset(), tb_async_stream_init_filter_from_chunked(), tb_async_stream_init_filter_from_null(), and tb_async_stream_init_filter_from_zip().
tb_async_stream_ref_t tb_async_stream_init_filter_from_cache (tb_async_stream_ref_t stream, tb_size_t size)
init filter stream from cache
Parameters
stream the stream
size the initial cache size, using the default size if be zero
Returns
the stream
Definition at line 787 of file filter.c.
References tb_async_stream_aicp(), tb_async_stream_ctrl(), tb_async_stream_exit(), tb_async_stream_init_filter(), and tb_stream_filter_init_from_cache().
tb_async_stream_ref_t tb_async_stream_init_filter_from_charset (tb_async_stream_ref_t stream, tb_size_t fr, tb_size_t to)
init filter stream from charset
Parameters
stream the stream
fr the from charset
to the to charset
Returns
the stream
Definition at line 830 of file filter.c.
References tb_async_stream_aicp(), tb_async_stream_ctrl(), tb_async_stream_exit(), tb_async_stream_init_filter(), and tb_stream_filter_init_from_charset().
tb_async_stream_ref_t tb_async_stream_init_filter_from_chunked (tb_async_stream_ref_t stream, tb_bool_t dechunked)
init filter stream from chunked
Parameters
stream the stream
dechunked decode the chunked data?
Returns
the stream
Definition at line 873 of file filter.c.
References tb_async_stream_aicp(), tb_async_stream_ctrl(), tb_async_stream_exit(), tb_async_stream_init_filter(), and tb_stream_filter_init_from_chunked().
tb_async_stream_ref_t tb_async_stream_init_filter_from_null (tb_async_stream_ref_t stream)
init filter stream from null
Parameters
stream the stream
Returns
the stream
Definition at line 703 of file filter.c.
References tb_async_stream_aicp(), tb_async_stream_ctrl(), tb_async_stream_exit(), and tb_async_stream_init_filter().
tb_async_stream_ref_t tb_async_stream_init_filter_from_zip (tb_async_stream_ref_t stream, tb_size_t algo, tb_size_t action)
init filter stream from zip
Parameters
stream the stream
algo the zip algorithm
action the zip action
Returns
the stream
Definition at line 744 of file filter.c.
References tb_async_stream_aicp(), tb_async_stream_ctrl(), tb_async_stream_exit(), tb_async_stream_init_filter(), and tb_stream_filter_init_from_zip().
tb_async_stream_ref_t tb_async_stream_init_from_data (tb_aicp_ref_t aicp, tb_byte_t const * data, tb_size_t size)
init stream from data
Parameters
aicp the aicp, using the default aicp if be null
data the data
size the size
Returns
the stream
Definition at line 672 of file data.c.
References tb_async_stream_ctrl(), tb_async_stream_exit(), and tb_async_stream_init_data().
Referenced by tb_async_transfer_init_istream_from_data(), and tb_async_transfer_init_ostream_from_data().
tb_async_stream_ref_t tb_async_stream_init_from_file (tb_aicp_ref_t aicp, tb_char_t const * path, tb_size_t mode)
init stream from file
Parameters
aicp the aicp, using the default aicp if be null
path the file path
mode the file mode, using the default ro mode if zero
Returns
the stream
Definition at line 587 of file file.c.
References tb_async_stream_ctrl(), tb_async_stream_exit(), and tb_async_stream_init_file().
tb_async_stream_ref_t tb_async_stream_init_from_http (tb_aicp_ref_t aicp, tb_char_t const * host, tb_uint16_t port, tb_char_t const * path, tb_bool_t bssl)
init stream from http or https
Parameters
aicp the aicp, using the default aicp if be null
host the host
port the port
path the path
bssl enable ssl?
Returns
the stream
Definition at line 807 of file http.c.
References tb_async_stream_ctrl(), tb_async_stream_exit(), and tb_async_stream_init_http().
tb_async_stream_ref_t tb_async_stream_init_from_sock (tb_aicp_ref_t aicp, tb_char_t const * host, tb_uint16_t port, tb_size_t type, tb_bool_t bssl)
init stream from sock
Parameters
aicp the aicp, using the default aicp if be null
host the host
port the port
type the socket type, tcp or udp
bssl enable ssl?
Returns
the stream
Definition at line 1188 of file sock.c.
References tb_async_stream_ctrl(), tb_async_stream_exit(), and tb_async_stream_init_sock().
tb_async_stream_ref_t tb_async_stream_init_from_url (tb_aicp_ref_t aicp, tb_char_t const * url)
init stream from url
Parameters
aicp the aicp, using the default aicp if be null
url the url
data://base64
file://path or unix path: e.g. /root/xxxx/file
sock://host:port?tcp=
sock://host:port?udp=
socks://host:port
http://host:port/path?arg0=&arg1=...
https://host:port/path?arg0=&arg1=...
Returns
the stream
Definition at line 526 of file async_stream.c.
References tb_async_stream_ctrl(), tb_async_stream_exit(), tb_async_stream_init_data(), tb_async_stream_init_file(), tb_async_stream_init_http(), and tb_async_stream_init_sock().
Referenced by tb_async_transfer_init_istream_from_url(), and tb_async_transfer_init_ostream_from_url().
tb_async_stream_ref_t tb_async_stream_init_http (tb_aicp_ref_t aicp)
init http stream
Parameters
aicp the aicp, using the default aicp if be null
Returns
the stream
Definition at line 756 of file http.c.
References tb_async_stream_aicp(), tb_async_stream_exit(), and tb_async_stream_init().
Referenced by tb_async_stream_init_from_http(), and tb_async_stream_init_from_url().
tb_async_stream_ref_t tb_async_stream_init_sock (tb_aicp_ref_t aicp)
init sock stream
Parameters
aicp the aicp, using the default aicp if be null
Returns
the stream
Definition at line 1155 of file sock.c.
References tb_async_stream_init().
Referenced by tb_async_stream_init_from_sock(), and tb_async_stream_init_from_url().
tb_bool_t tb_async_stream_is_closed (tb_async_stream_ref_t stream)
is closed?
Parameters
stream the stream
Returns
tb_true or tb_false
Definition at line 711 of file async_stream.c.
Referenced by tb_async_stream_clos_try(), and tb_async_stream_ctrl_with_args().
tb_bool_t tb_async_stream_is_killed (tb_async_stream_ref_t stream)
is killed?
Parameters
stream the stream
Returns
tb_true or tb_false
Definition at line 723 of file async_stream.c.
tb_bool_t tb_async_stream_is_opened (tb_async_stream_ref_t stream)
is opened?
Parameters
stream the stream
Returns
tb_true or tb_false
Definition at line 699 of file async_stream.c.
Referenced by tb_async_stream_open_try().
tb_void_t tb_async_stream_kill (tb_async_stream_ref_t stream)
kill stream
Parameters
stream the stream
Definition at line 942 of file async_stream.c.
References tb_state_cstr().
Referenced by tb_async_stream_exit(), and tb_async_transfer_kill().
tb_hize_t tb_async_stream_left (tb_async_stream_ref_t stream)
the stream left size and not seeking it
Parameters
stream the stream
Returns
the stream left size, no size: infinity, empty or end: 0
Definition at line 662 of file async_stream.c.
References tb_async_stream_offset(), and tb_async_stream_size().
tb_hize_t tb_async_stream_offset (tb_async_stream_ref_t stream)
the stream offset
the offset is read + writ and using seek for modifying it if size != -1, .e.g: data, file, .. the offset is calculated from the last read/writ and not seeking it if size == -1, .e.g: sock, filter, ..
Parameters
stream the stream
Returns
the stream offset
Definition at line 690 of file async_stream.c.
References tb_async_stream_ctrl().
Referenced by tb_async_stream_beof(), tb_async_stream_left(), tb_async_stream_seek_(), and tb_async_transfer_open().
tb_bool_t tb_async_stream_open_ (tb_async_stream_ref_t stream, tb_async_stream_open_func_t func, tb_cpointer_t priv __tb_debug_decl__)
open the stream
Parameters
stream the stream
func the func
priv the func data
Returns
tb_true or tb_false
Definition at line 1005 of file async_stream.c.
References tb_async_stream_open_try().
Referenced by tb_async_stream_open_read_(), tb_async_stream_open_seek_(), and tb_async_stream_open_writ_().
tb_bool_t tb_async_stream_open_read_ (tb_async_stream_ref_t stream, tb_size_t size, tb_async_stream_read_func_t func, tb_cpointer_t priv __tb_debug_decl__)
open and read the stream, open it first if not opened
Parameters
stream the stream
size the size, using the default size be zero
func the func
priv the func data
Returns
tb_true or tb_false
Definition at line 1196 of file async_stream.c.
References tb_async_stream_open_(), and tb_async_stream_read_().
tb_bool_t tb_async_stream_open_seek_ (tb_async_stream_ref_t stream, tb_hize_t offset, tb_async_stream_seek_func_t func, tb_cpointer_t priv __tb_debug_decl__)
open and seek the stream, open it first if not opened
Parameters
stream the stream
offset the offset
func the func
priv the func data
Returns
tb_true or tb_false
Definition at line 1235 of file async_stream.c.
References tb_async_stream_open_(), and tb_async_stream_seek_().
tb_bool_t tb_async_stream_open_try (tb_async_stream_ref_t stream)
try opening the stream for stream: file, filter, ...
Parameters
stream the stream
Returns
tb_true or tb_false
Definition at line 975 of file async_stream.c.
References tb_async_stream_is_opened().
Referenced by tb_async_stream_open_().
tb_bool_t tb_async_stream_open_writ_ (tb_async_stream_ref_t stream, tb_byte_t const * data, tb_size_t size, tb_async_stream_writ_func_t func, tb_cpointer_t priv __tb_debug_decl__)
open and writ the stream, open it first if not opened
Parameters
stream the stream
data the data
size the size
func the func
priv the func data
Returns
tb_true or tb_false
Definition at line 1215 of file async_stream.c.
References tb_async_stream_open_(), and tb_async_stream_writ_().
tb_bool_t tb_async_stream_read_ (tb_async_stream_ref_t stream, tb_size_t size, tb_async_stream_read_func_t func, tb_cpointer_t priv __tb_debug_decl__)
read the stream
Parameters
stream the stream
size the read size, using the default size if be zero
func the func
priv the func data
Returns
tb_true or tb_false
open and read the stream, open it first if not opened
Parameters
stream the stream
size the read size, using the default size if be zero
func the func
priv the func data
Returns
tb_true or tb_false
Definition at line 1092 of file async_stream.c.
References tb_async_stream_read_after_().
Referenced by tb_async_stream_open_read_().
tb_bool_t tb_async_stream_read_after_ (tb_async_stream_ref_t stream, tb_size_t delay, tb_size_t size, tb_async_stream_read_func_t func, tb_cpointer_t priv __tb_debug_decl__)
read the stream after the delay time
Parameters
stream the stream
delay the delay time, ms
size the read size, using the default size if be zero
func the func
priv the func data
Returns
tb_true or tb_false
Definition at line 1254 of file async_stream.c.
References tb_async_stream_sync_(), and tb_buffer_size().
Referenced by tb_async_stream_read_().
tb_bool_t tb_async_stream_seek_ (tb_async_stream_ref_t stream, tb_hize_t offset, tb_async_stream_seek_func_t func, tb_cpointer_t priv __tb_debug_decl__)
seek the stream
Parameters
stream the stream
offset the offset
func the func
priv the func data
Returns
tb_true or tb_false
Definition at line 1102 of file async_stream.c.
References tb_async_stream_offset(), tb_async_stream_sync_(), and tb_buffer_size().
Referenced by tb_async_stream_open_seek_().
tb_hong_t tb_async_stream_size (tb_async_stream_ref_t stream)
the stream size and not seeking it
Parameters
stream the stream
Returns
the stream size, no size: -1, empty or error: 0
Definition at line 653 of file async_stream.c.
References tb_async_stream_ctrl().
Referenced by tb_async_stream_beof(), tb_async_stream_left(), and tb_async_transfer_open().
tb_bool_t tb_async_stream_sync_ (tb_async_stream_ref_t stream, tb_bool_t bclosing, tb_async_stream_sync_func_t func, tb_cpointer_t priv __tb_debug_decl__)
sync the stream
Parameters
stream the stream
bclosing sync the tail data for closing
func the func
priv the func data
Returns
tb_true or tb_false
Definition at line 1138 of file async_stream.c.
References tb_buffer_data(), and tb_buffer_size().
Referenced by tb_async_stream_read_after_(), and tb_async_stream_seek_().
tb_bool_t tb_async_stream_task_ (tb_async_stream_ref_t stream, tb_size_t delay, tb_async_stream_task_func_t func, tb_cpointer_t priv __tb_debug_decl__)
task the stream
Parameters
stream the stream
delay the delay time, ms
func the func
priv the func data
Returns
tb_true or tb_false
Definition at line 1177 of file async_stream.c.
tb_long_t tb_async_stream_timeout (tb_async_stream_ref_t stream)
the stream timeout
Parameters
stream the stream
Returns
the stream timeout
Definition at line 735 of file async_stream.c.
References tb_async_stream_ctrl().
tb_size_t tb_async_stream_type (tb_async_stream_ref_t stream)
the stream type
Parameters
stream the stream
Returns
the stream type
Definition at line 644 of file async_stream.c.
Referenced by tb_async_transfer_init_istream_from_data(), tb_async_transfer_init_istream_from_url(), tb_async_transfer_init_ostream_from_data(), and tb_async_transfer_init_ostream_from_url().
tb_url_t* tb_async_stream_url (tb_async_stream_ref_t stream)
the stream url
Parameters
stream the stream
Returns
the stream url
Definition at line 635 of file async_stream.c.
tb_bool_t tb_async_stream_writ_ (tb_async_stream_ref_t stream, tb_byte_t const * data, tb_size_t size, tb_async_stream_writ_func_t func, tb_cpointer_t priv __tb_debug_decl__)
writ the stream
Parameters
stream the stream
data the data
size the size
func the func
priv the func data
Returns
tb_true or tb_false
Definition at line 1097 of file async_stream.c.
References tb_async_stream_writ_after_().
Referenced by tb_async_stream_open_writ_().
tb_bool_t tb_async_stream_writ_after_ (tb_async_stream_ref_t stream, tb_size_t delay, tb_byte_t const * data, tb_size_t size, tb_async_stream_writ_func_t func, tb_cpointer_t priv __tb_debug_decl__)
writ the stream after the delay time
Parameters
stream the stream
delay the delay time, ms
data the data
size the size
func the func
priv the func data
Returns
tb_true or tb_false
Definition at line 1283 of file async_stream.c.
Referenced by tb_async_stream_writ_().