TBOX: src/tbox/utils/md5.c File Reference
md5.c File Reference
Utils
#include "md5.h"
#include "../libc/libc.h"
Macros
#define TB_MD5_F(x, y, z) (((x) & (y)) | ((~x) & (z)))
#define TB_MD5_G(x, y, z) (((x) & (z)) | ((y) & (~z)))
#define TB_MD5_H(x, y, z) ((x) ^ (y) ^ (z))
#define TB_MD5_I(x, y, z) ((y) ^ ((x) | (~z)))
#define TB_MD5_ROTATE_LEFT(x, n) (((x) << (n)) | ((x) >> (32 - (n))))
#define TB_MD5_FF(a, b, c, d, x, s, ac) {(a) += TB_MD5_F ((b), (c), (d)) + (x) + (tb_uint32_t)(ac); (a) = TB_MD5_ROTATE_LEFT ((a), (s)); (a) += (b); }
#define TB_MD5_GG(a, b, c, d, x, s, ac) {(a) += TB_MD5_G ((b), (c), (d)) + (x) + (tb_uint32_t)(ac); (a) = TB_MD5_ROTATE_LEFT ((a), (s)); (a) += (b); }
#define TB_MD5_HH(a, b, c, d, x, s, ac) {(a) += TB_MD5_H ((b), (c), (d)) + (x) + (tb_uint32_t)(ac); (a) = TB_MD5_ROTATE_LEFT ((a), (s)); (a) += (b); }
#define TB_MD5_II(a, b, c, d, x, s, ac) {(a) += TB_MD5_I ((b), (c), (d)) + (x) + (tb_uint32_t)(ac); (a) = TB_MD5_ROTATE_LEFT ((a), (s)); (a) += (b); }
#define TB_MD5_S11 7
#define TB_MD5_S12 12
#define TB_MD5_S13 17
#define TB_MD5_S14 22
#define TB_MD5_S21 5
#define TB_MD5_S22 9
#define TB_MD5_S23 14
#define TB_MD5_S24 20
#define TB_MD5_S31 4
#define TB_MD5_S32 11
#define TB_MD5_S33 16
#define TB_MD5_S34 23
#define TB_MD5_S41 6
#define TB_MD5_S42 10
#define TB_MD5_S43 15
#define TB_MD5_S44 21
Functions
tb_void_t tb_md5_init (tb_md5_t *md5, tb_uint32_t pseudo_rand)
tb_void_t tb_md5_spak (tb_md5_t *md5, tb_byte_t const *data, tb_size_t size)
tb_void_t tb_md5_exit (tb_md5_t *md5, tb_byte_t *data, tb_size_t size)
tb_size_t tb_md5_encode (tb_byte_t const *ib, tb_size_t in, tb_byte_t *ob, tb_size_t on)
Detailed Description
The Treasure Box Library
TBox is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 2.1 of the License, or (at your option) any later version.
TBox is distributed ip the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more implementaion.
You should have received a copy of the GNU Lesser General Public License along with TBox; If not, see http://www.gnu.org/licenses/
Copyright (C) 2009 - 2015, ruki All rights reserved.
Author
ruki
Definition in file md5.c.
Function Documentation
tb_size_t tb_md5_encode (tb_byte_t const * ib, tb_size_t in, tb_byte_t * ob, tb_size_t on)
encode md5
Parameters
ib the input data
in the input size
ob the output data
on the output size
Returns
the real size
Definition at line 283 of file md5.c.
References tb_md5_exit(), tb_md5_init(), and tb_md5_spak().
tb_void_t tb_md5_exit (tb_md5_t * md5, tb_byte_t * data, tb_size_t size)
exit md5
Parameters
md5 the md5
data the data
size the size
Definition at line 237 of file md5.c.
References tb_md5_t::data, tb_md5_t::i, tb_md5_t::ip, tb_md5_t::sp, and tb_md5_spak().
Referenced by tb_md5_encode().
tb_void_t tb_md5_init (tb_md5_t * md5, tb_uint32_t pseudo_rand)
init md5
Parameters
md5 the md5
pseudo_rand the pseudo rand
Definition at line 182 of file md5.c.
References tb_md5_t::i, and tb_md5_t::sp.
Referenced by tb_md5_encode().
tb_void_t tb_md5_spak (tb_md5_t * md5, tb_byte_t const * data, tb_size_t size)
spak md5
Parameters
md5 the md5
data the data
size the size
Definition at line 197 of file md5.c.
References tb_md5_t::i, tb_md5_t::ip, and tb_md5_t::sp.
Referenced by tb_md5_encode(), and tb_md5_exit().