TBOX: src/container/item.c File Reference
item.c File Reference
Container
#include "item.h"
#include "../libc/libc.h"
#include "../utils/utils.h"
#include "../memory/memory.h"
#include "../object/object.h"
#include "../platform/platform.h"
Functions
tb_item_func_t tb_item_func_true ()
tb_item_func_t tb_item_func_long ()
tb_item_func_t tb_item_func_size ()
tb_item_func_t tb_item_func_uint8 ()
tb_item_func_t tb_item_func_uint16 ()
tb_item_func_t tb_item_func_uint32 ()
tb_item_func_t tb_item_func_str (tb_bool_t bcase, tb_handle_t spool)
tb_item_func_t tb_item_func_ptr (tb_item_func_free_t free, tb_pointer_t priv)
tb_item_func_t tb_item_func_obj ()
tb_item_func_t tb_item_func_efm (tb_size_t size, tb_handle_t rpool)
tb_item_func_t tb_item_func_ifm (tb_size_t size, tb_item_func_free_t free, tb_pointer_t priv)
tb_item_func_t tb_item_func_scache (tb_bool_t bcase)
Detailed Description
The Treasure Box Library
TBox is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 2.1 of the License, or (at your option) any later version.
TBox is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with TBox; If not, see http://www.gnu.org/licenses/
Copyright (C) 2009 - 2015, ruki All rights reserved.
Author
ruki
Definition in file item.c.
Function Documentation
tb_item_func_t tb_item_func_efm (tb_size_t size, tb_handle_t rpool)
the external fixed memory item function
storing the index value in the internal item of the container
using tb_malloc if the rpool is null, using tb_rpool_malloc if the rpool exists
Parameters
size the item size
rpool the item rpool
Returns
the item func
Definition at line 938 of file item.c.
References tb_item_func_t::copy, tb_item_func_t::dupl, tb_item_func_t::hash, tb_item_func_t::pool, tb_item_func_t::priv, tb_item_func_t::repl, tb_item_func_t::size, TB_ITEM_TYPE_EFM, and tb_item_func_t::type.
tb_item_func_t tb_item_func_ifm (tb_size_t size, tb_item_func_free_t free, tb_pointer_t priv)
the internal fixed memory item function
storing it in the internal item of the container directly for saving memory
Parameters
size the item size
free the item free func
priv the private data of the item free func
Returns
the item func
Definition at line 965 of file item.c.
References tb_item_func_t::copy, tb_item_func_t::dupl, tb_item_func_t::hash, tb_item_func_t::priv, tb_item_func_t::repl, tb_item_func_t::size, TB_ITEM_TYPE_IFM, and tb_item_func_t::type.
Referenced by tb_epool_init().
tb_item_func_t tb_item_func_ptr (tb_item_func_free_t free, tb_pointer_t priv)
the pointer item function
Note
if the free func have been hooked, the nfree need hook too.
Parameters
free the item free func
priv the private data of the item free func
Returns
the item func
Definition at line 887 of file item.c.
References tb_item_func_t::copy, tb_item_func_t::dupl, tb_item_func_t::hash, tb_item_func_t::priv, tb_item_func_t::repl, tb_item_func_t::size, TB_ITEM_TYPE_PTR, and tb_item_func_t::type.
Referenced by tb_ltimer_init(), tb_mstream_done(), tb_mstream_init(), tb_mstream_kill(), and tb_timer_init().
tb_item_func_t tb_item_func_scache (tb_bool_t bcase)
the string item function for scache
Parameters
bcase is case?
Returns
the item func
Definition at line 991 of file item.c.
References tb_item_func_t::copy, tb_item_func_t::dupl, tb_item_func_t::hash, tb_item_func_t::priv, tb_item_func_t::repl, tb_item_func_t::size, TB_ITEM_TYPE_SCACHE, and tb_item_func_t::type.
Referenced by tb_dictionary_init().
tb_item_func_t tb_item_func_str (tb_bool_t bcase, tb_handle_t spool)
the string item function
using tb_strdup if the spool is null, using tb_spool_strdup if the spool exists
Parameters
bcase is case?
spool the string pool
Returns
the item func
Definition at line 861 of file item.c.
References tb_item_func_t::copy, tb_item_func_t::dupl, tb_item_func_t::hash, tb_item_func_t::pool, tb_item_func_t::priv, tb_item_func_t::repl, tb_item_func_t::size, TB_ITEM_TYPE_STR, and tb_item_func_t::type.
Referenced by tb_scache_init().