TBOX: src/tbox/memory/pool.h File Reference
pool.h File Reference
Memory
#include "prefix.h"
#include "large_pool.h"
Macros
#define tb_pool_malloc(pool, size) tb_pool_malloc_(pool, size __tb_debug_vals__)
#define tb_pool_malloc0(pool, size) tb_pool_malloc0_(pool, size __tb_debug_vals__)
#define tb_pool_nalloc(pool, item, size) tb_pool_nalloc_(pool, item, size __tb_debug_vals__)
#define tb_pool_nalloc0(pool, item, size) tb_pool_nalloc0_(pool, item, size __tb_debug_vals__)
#define tb_pool_ralloc(pool, data, size) tb_pool_ralloc_(pool, (tb_pointer_t)(data), size __tb_debug_vals__)
#define tb_pool_free(pool, data) tb_pool_free_(pool, (tb_pointer_t)(data) __tb_debug_vals__)
Functions
tb_pool_ref_t tb_pool ()
tb_pool_ref_t tb_pool_init (tb_large_pool_ref_t large_pool)
tb_void_t tb_pool_exit (tb_pool_ref_t pool)
tb_pointer_t tb_pool_malloc_ (tb_pool_ref_t pool, tb_size_t size __tb_debug_decl__)
tb_pointer_t tb_pool_malloc0_ (tb_pool_ref_t pool, tb_size_t size __tb_debug_decl__)
tb_pointer_t tb_pool_nalloc_ (tb_pool_ref_t pool, tb_size_t item, tb_size_t size __tb_debug_decl__)
tb_pointer_t tb_pool_nalloc0_ (tb_pool_ref_t pool, tb_size_t item, tb_size_t size __tb_debug_decl__)
tb_pointer_t tb_pool_ralloc_ (tb_pool_ref_t pool, tb_pointer_t data, tb_size_t size __tb_debug_decl__)
tb_bool_t tb_pool_free_ (tb_pool_ref_t pool, tb_pointer_t data __tb_debug_decl__)
tb_pointer_t tb_pool_align_malloc_ (tb_pool_ref_t pool, tb_size_t size, tb_size_t align __tb_debug_decl__)
tb_pointer_t tb_pool_align_malloc0_ (tb_pool_ref_t pool, tb_size_t size, tb_size_t align __tb_debug_decl__)
tb_pointer_t tb_pool_align_nalloc_ (tb_pool_ref_t pool, tb_size_t item, tb_size_t size, tb_size_t align __tb_debug_decl__)
tb_pointer_t tb_pool_align_nalloc0_ (tb_pool_ref_t pool, tb_size_t item, tb_size_t size, tb_size_t align __tb_debug_decl__)
tb_pointer_t tb_pool_align_ralloc_ (tb_pool_ref_t pool, tb_pointer_t data, tb_size_t size, tb_size_t align __tb_debug_decl__)
tb_bool_t tb_pool_align_free_ (tb_pool_ref_t pool, tb_pointer_t data __tb_debug_decl__)
Detailed Description
The Treasure Box Library
TBox is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 2.1 of the License, or (at your option) any later version.
TBox is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with TBox; If not, see http://www.gnu.org/licenses/
Copyright (C) 2009 - 2015, ruki All rights reserved.
Author
ruki
Definition in file pool.h.
Function Documentation
tb_pool_ref_t tb_pool ()
the pool
| native memory  | or |                         data                          |
        |             if data be null             |
        `------------------------------------—> |
|
|                                large pool[lock]                             |
                            |                     |
                            |          ------------------------------------—
                            |         |               small pool              |
                            |          ------------------------------------—
|                              |
|                         >3KB        |                 <=3KB                 |
|--------------------------------------------------------------------------—|
|                                  pool[lock]                                 |
the pool instance
Returns
the pool
Definition at line 79 of file pool.c.
References tb_singleton_instance().
tb_bool_t tb_pool_align_free_ (tb_pool_ref_t pool, tb_pointer_t data __tb_debug_decl__)
align free data
Parameters
pool the pool
data the data address
Returns
tb_true or tb_false
Definition at line 427 of file pool.c.
References tb_pool_free_().
tb_pointer_t tb_pool_align_malloc0_ (tb_pool_ref_t pool, tb_size_t size, tb_size_t align __tb_debug_decl__)
align malloc data and fill zero
Parameters
pool the pool
size the size
align the alignment bytes
Returns
the data address
Definition at line 361 of file pool.c.
References tb_pool_align_malloc_().
tb_pointer_t tb_pool_align_malloc_ (tb_pool_ref_t pool, tb_size_t size, tb_size_t align __tb_debug_decl__)
align malloc data
Parameters
pool the pool
size the size
align the alignment bytes
Returns
the data address
Definition at line 336 of file pool.c.
References tb_pool_malloc_().
Referenced by tb_pool_align_malloc0_(), and tb_pool_align_nalloc_().
tb_pointer_t tb_pool_align_nalloc0_ (tb_pool_ref_t pool, tb_size_t item, tb_size_t size, tb_size_t align __tb_debug_decl__)
align malloc data with the item count and fill zero
Parameters
pool the pool
item the item count
size the item size
align the alignment bytes
Returns
the data address
Definition at line 377 of file pool.c.
References tb_pool_align_nalloc_().
tb_pointer_t tb_pool_align_nalloc_ (tb_pool_ref_t pool, tb_size_t item, tb_size_t size, tb_size_t align __tb_debug_decl__)
align malloc data with the item count
Parameters
pool the pool
item the item count
size the item size
align the alignment bytes
Returns
the data address
Definition at line 373 of file pool.c.
References tb_pool_align_malloc_().
Referenced by tb_pool_align_nalloc0_().
tb_pointer_t tb_pool_align_ralloc_ (tb_pool_ref_t pool, tb_pointer_t data, tb_size_t size, tb_size_t align __tb_debug_decl__)
align realloc data
Parameters
pool the pool
data the data address
size the data size
Returns
the new data address
Definition at line 389 of file pool.c.
References tb_pool_ralloc_().
tb_void_t tb_pool_exit (tb_pool_ref_t pool)
exit the pool
Parameters
pool the pool
Definition at line 126 of file pool.c.
References tb_small_pool_exit().
Referenced by tb_pool_init().
tb_bool_t tb_pool_free_ (tb_pool_ref_t pool, tb_pointer_t data __tb_debug_decl__)
free data
Parameters
pool the pool
data the data address
Returns
tb_true or tb_false
Definition at line 293 of file pool.c.
tb_pool_ref_t tb_pool_init (tb_large_pool_ref_t large_pool)
init the pool
Parameters
large_pool the large pool, using the default large pool if be null
Returns
the pool
Definition at line 83 of file pool.c.
References tb_large_pool(), tb_lock_profiler(), tb_lock_profiler_register(), tb_pool_exit(), and tb_small_pool_init().
tb_pointer_t tb_pool_malloc0_ (tb_pool_ref_t pool, tb_size_t size __tb_debug_decl__)
malloc data and fill zero
Parameters
pool the pool
size the size
Returns
the data address
Definition at line 166 of file pool.c.
tb_pointer_t tb_pool_malloc_ (tb_pool_ref_t pool, tb_size_t size __tb_debug_decl__)
malloc data
Parameters
pool the pool
size the size
Returns
the data address
Definition at line 148 of file pool.c.
tb_pointer_t tb_pool_nalloc0_ (tb_pool_ref_t pool, tb_size_t item, tb_size_t size __tb_debug_decl__)
malloc data with the item count and fill zero
Parameters
pool the pool
item the item count
size the item size
Returns
the data address
Definition at line 202 of file pool.c.
tb_pointer_t tb_pool_nalloc_ (tb_pool_ref_t pool, tb_size_t item, tb_size_t size __tb_debug_decl__)
malloc data with the item count
Parameters
pool the pool
item the item count
size the item size
Returns
the data address
Definition at line 184 of file pool.c.
tb_pointer_t tb_pool_ralloc_ (tb_pool_ref_t pool, tb_pointer_t data, tb_size_t size __tb_debug_decl__)
realloc data
Parameters
pool the pool
data the data address
size the data size
Returns
the new data address
Definition at line 220 of file pool.c.