TBOX: src/stream/mstream.h File Reference
mstream.h File Reference
Stream
#include "prefix.h"
#include "tstream.h"
#include "../asio/asio.h"
Functions
tb_handle_t tb_mstream_init (tb_aicp_t *aicp, tb_size_t conc, tb_long_t timeout)
tb_void_t tb_mstream_exit (tb_handle_t mstream)
tb_void_t tb_mstream_kill (tb_handle_t mstream)
tb_size_t tb_mstream_size (tb_handle_t mstream)
tb_bool_t tb_mstream_done (tb_handle_t mstream, tb_char_t const *iurl, tb_char_t const *ourl, tb_hize_t offset, tb_tstream_save_func_t func, tb_pointer_t priv)
Detailed Description
The Treasure Box Library
TBox is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 2.1 of the License, or (at your option) any later version.
TBox is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with TBox; If not, see http://www.gnu.org/licenses/
Copyright (C) 2009 - 2015, ruki All rights reserved.
Author
ruki
Definition in file mstream.h.
Function Documentation
tb_bool_t tb_mstream_done (tb_handle_t mstream, tb_char_t const * iurl, tb_char_t const * ourl, tb_hize_t offset, tb_tstream_save_func_t func, tb_pointer_t priv)
done transfer from iurl to ourl
Parameters
mstream the mstream
iurl the input url
ourl the output url
offset the offset
func the save func
priv the func private data
Returns
tb_true or tb_false
Definition at line 472 of file mstream.c.
References tb_dlist_insert_tail(), tb_dlist_remove(), tb_dlist_size(), tb_item_func_ptr(), tb_iterator_tail(), tb_rpool_malloc0(), tb_slist_init(), tb_slist_insert_tail(), tb_slist_size(), tb_thread_init(), tb_tstream_init_uu(), tb_tstream_osave(), and tb_tstream_timeout_set().
tb_void_t tb_mstream_exit (tb_handle_t mstream)
exit mstream
Parameters
mstream the mstream
Definition at line 358 of file mstream.c.
References tb_aicp_exit(), tb_aicp_kill(), tb_dlist_exit(), tb_dlist_size(), tb_mstream_kill(), tb_rpool_exit(), tb_slist_exit(), tb_thread_exit(), tb_thread_kill(), tb_thread_wait(), and tb_walk_all().
Referenced by tb_mstream_init().
tb_handle_t tb_mstream_init (tb_aicp_t * aicp, tb_size_t conc, tb_long_t timeout)
init mstream
the multi-stream for the stream transfer
Parameters
aicp the aicp, will make it if be null
conc the concurrent transfer count, no limit if be zero
timeout the timeout, using the default timeout if be zero
Returns
the mstream
Definition at line 272 of file mstream.c.
References tb_aicp_init(), tb_dlist_init(), tb_item_func_ptr(), tb_mstream_exit(), and tb_rpool_init().
tb_void_t tb_mstream_kill (tb_handle_t mstream)
kill mstream
Parameters
mstream the mstream
Definition at line 321 of file mstream.c.
References tb_dlist_exit(), tb_dlist_init(), tb_dlist_size(), tb_item_func_ptr(), and tb_walk_all().
Referenced by tb_mstream_exit().
tb_size_t tb_mstream_size (tb_handle_t mstream)
the mstream size
Parameters
mstream the mstream
Definition at line 454 of file mstream.c.
References tb_rpool_size().