TBOX: src/memory/fpool.c File Reference
fpool.c File Reference
Memory
#include "fpool.h"
#include "../libc/libc.h"
#include "../math/math.h"
#include "../utils/utils.h"
#include "../platform/platform.h"
Macros
#define TB_FPOOL_MAGIC (0xdeaf)
#define TB_FPOOL_ALIGN_MAXN (128)
#define tb_fpool_used_set1(used, i) do {(used)[(i) >> 3] |= (0x1 << ((i) & 7));} while (0)
#define tb_fpool_used_set0(used, i) do {(used)[(i) >> 3] &= ~(0x1 << ((i) & 7));} while (0)
#define tb_fpool_used_bset(used, i) ((used)[(i) >> 3] & (0x1 << ((i) & 7)))
Functions
tb_handle_t tb_fpool_init (tb_byte_t *data, tb_size_t size, tb_size_t step, tb_size_t align)
tb_void_t tb_fpool_exit (tb_handle_t handle)
tb_void_t tb_fpool_clear (tb_handle_t handle)
tb_size_t tb_fpool_size (tb_handle_t handle)
tb_pointer_t tb_fpool_malloc (tb_handle_t handle)
tb_pointer_t tb_fpool_malloc0 (tb_handle_t handle)
tb_pointer_t tb_fpool_memdup (tb_handle_t handle, tb_cpointer_t data)
tb_bool_t tb_fpool_free (tb_handle_t handle, tb_pointer_t data)
tb_void_t tb_fpool_walk (tb_handle_t handle, tb_bool_t(*func)(tb_pointer_t item, tb_pointer_t data), tb_pointer_t data)
tb_void_t tb_fpool_dump (tb_handle_t handle)
Detailed Description
The Treasure Box Library
TBox is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 2.1 of the License, or (at your option) any later version.
TBox is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with TBox; If not, see http://www.gnu.org/licenses/
Copyright (C) 2009 - 2015, ruki All rights reserved.
Author
ruki
Definition in file fpool.c.
Function Documentation
tb_void_t tb_fpool_clear (tb_handle_t handle)
clear fixed pool
Parameters
handle the pool handle
Definition at line 341 of file fpool.c.
Referenced by tb_fpool_exit(), and tb_rpool_clear().
tb_void_t tb_fpool_dump (tb_handle_t handle)
dump fixed pool
Parameters
handle the pool handle
Definition at line 522 of file fpool.c.
Referenced by tb_rpool_dump().
tb_void_t tb_fpool_exit (tb_handle_t handle)
exit fixed pool
Parameters
handle the pool handle
Definition at line 328 of file fpool.c.
References tb_fpool_clear().
Referenced by tb_rpool_exit(), and tb_rpool_malloc().
tb_bool_t tb_fpool_free (tb_handle_t handle, tb_pointer_t data)
free fixed pool data
Parameters
handle the pool handle
data the pool item data
Returns
tb_true or tb_false
Definition at line 437 of file fpool.c.
Referenced by tb_rpool_free().
tb_handle_t tb_fpool_init (tb_byte_t * data, tb_size_t size, tb_size_t step, tb_size_t align)
init fixed pool
Parameters
data the data
size the size
step the step
align the align
Returns
the pool handle
Definition at line 257 of file fpool.c.
Referenced by tb_rpool_malloc().
tb_pointer_t tb_fpool_malloc (tb_handle_t handle)
malloc fixed pool data
Parameters
handle the pool handle
Returns
the data pointer
Definition at line 376 of file fpool.c.
Referenced by tb_fpool_malloc0(), tb_fpool_memdup(), and tb_rpool_malloc().
tb_pointer_t tb_fpool_malloc0 (tb_handle_t handle)
malloc fixed pool data and clear it
Parameters
handle the pool handle
Returns
the data pointer
Definition at line 406 of file fpool.c.
References tb_fpool_malloc().
tb_pointer_t tb_fpool_memdup (tb_handle_t handle, tb_cpointer_t data)
duplicate fixed pool data
Parameters
handle the pool handle
data the data pointer
Returns
the duplicated data pointer
Definition at line 421 of file fpool.c.
References tb_fpool_malloc().
tb_size_t tb_fpool_size (tb_handle_t handle)
the fixed pool item count
Parameters
handle the pool handle
Returns
the item count
Definition at line 367 of file fpool.c.
tb_void_t tb_fpool_walk (tb_handle_t handle, tb_bool_t(*)(tb_pointer_t item, tb_pointer_t data) func, tb_pointer_t data)
walk fixed pool item
tb_bool_t tb_fpool_item_func(tb_pointer_t item, tb_pointer_t data)
{
        // is tail?
        if (!item) ;
        // ok
        return tb_true;
fail:
        // break
        return tb_false;
}
Parameters
handle the pool handle
func the walk func
data the walk data
Definition at line 469 of file fpool.c.
Referenced by tb_rpool_walk().