TBOX: src/tbox/network/impl/ssl/openssl.c File Reference
openssl.c File Reference
Network
#include "prefix.h"
#include <openssl/bio.h>
#include <openssl/ssl.h>
#include <openssl/err.h>
#include <openssl/x509v3.h>
#include "../../../asio/asio.h"
#include "../../../utils/utils.h"
#include "../../../platform/platform.h"
Macros
#define TB_TRACE_MODULE_NAME "openssl"
#define TB_TRACE_MODULE_DEBUG (1)
Functions
tb_ssl_ref_t tb_ssl_init (tb_bool_t bserver)
tb_void_t tb_ssl_exit (tb_ssl_ref_t ssl)
tb_void_t tb_ssl_set_bio_sock (tb_ssl_ref_t ssl, tb_socket_ref_t sock)
tb_void_t tb_ssl_set_bio_func (tb_ssl_ref_t ssl, tb_ssl_func_read_t read, tb_ssl_func_writ_t writ, tb_ssl_func_wait_t wait, tb_cpointer_t priv)
tb_void_t tb_ssl_set_timeout (tb_ssl_ref_t ssl, tb_long_t timeout)
tb_bool_t tb_ssl_open (tb_ssl_ref_t ssl)
tb_long_t tb_ssl_open_try (tb_ssl_ref_t ssl)
tb_bool_t tb_ssl_clos (tb_ssl_ref_t ssl)
tb_long_t tb_ssl_clos_try (tb_ssl_ref_t ssl)
tb_long_t tb_ssl_read (tb_ssl_ref_t ssl, tb_byte_t *data, tb_size_t size)
tb_long_t tb_ssl_writ (tb_ssl_ref_t ssl, tb_byte_t const *data, tb_size_t size)
tb_long_t tb_ssl_wait (tb_ssl_ref_t ssl, tb_size_t code, tb_long_t timeout)
tb_size_t tb_ssl_state (tb_ssl_ref_t ssl)
Detailed Description
The Treasure Box Library
TBox is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 2.1 of the License, or (at your option) any later version.
TBox is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with TBox; If not, see http://www.gnu.org/licenses/
Copyright (C) 2009 - 2015, ruki All rights reserved.
Author
ruki
Definition in file openssl.c.
Function Documentation
tb_bool_t tb_ssl_clos (tb_ssl_ref_t ssl)
clos ssl
Parameters
ssl the ssl handle
Returns
tb_true or tb_false
Definition at line 567 of file openssl.c.
References tb_ssl_clos_try(), and tb_ssl_wait().
Referenced by tb_ssl_exit().
tb_long_t tb_ssl_clos_try (tb_ssl_ref_t ssl)
try closing ssl using non-blocking mode
// open it
tb_long_t ok = -1;
while (!(ok = tb_ssl_clos_try(handle)))
{
    // wait it
    ok = tb_ssl_wait(handle, TB_AIOE_CODE_RECV | TB_AIOE_CODE_SEND, timeout);
    tb_check_break(ok > 0);
}
Parameters
ssl the ssl handle
Returns
ok: 1, continue: 0, failed: -1
Definition at line 585 of file openssl.c.
Referenced by tb_ssl_clos().
tb_void_t tb_ssl_exit (tb_ssl_ref_t ssl)
exit ssl
Parameters
ssl the ssl handle
Definition at line 419 of file openssl.c.
References tb_ssl_clos().
Referenced by tb_aicp_ssl_exit(), and tb_ssl_init().
tb_ssl_ref_t tb_ssl_init (tb_bool_t bserver)
init ssl
Parameters
bserver is server endpoint?
Returns
the ssl handle
Definition at line 361 of file openssl.c.
References tb_ssl_exit().
Referenced by tb_aicp_ssl_init().
tb_bool_t tb_ssl_open (tb_ssl_ref_t ssl)
open ssl using blocking mode
Note
need wait func
Parameters
ssl the ssl handle
Returns
tb_true or tb_false
Definition at line 469 of file openssl.c.
References tb_ssl_open_try(), and tb_ssl_wait().
tb_long_t tb_ssl_open_try (tb_ssl_ref_t ssl)
try opening ssl using non-blocking mode
// open it
tb_long_t ok = -1;
while (!(ok = tb_ssl_open_try(handle)))
{
    // wait it
    ok = tb_ssl_wait(handle, TB_AIOE_CODE_RECV | TB_AIOE_CODE_SEND, timeout);
    tb_check_break(ok > 0);
}
Parameters
ssl the ssl handle
Returns
ok: 1, continue: 0, failed: -1
Definition at line 487 of file openssl.c.
Referenced by tb_aicp_ssl_open(), and tb_ssl_open().
tb_long_t tb_ssl_read (tb_ssl_ref_t ssl, tb_byte_t * data, tb_size_t size)
read ssl data
Parameters
ssl the ssl handle
data the data
size the size
Returns
the real size, no data: 0 and see state for waiting, failed: -1
Definition at line 668 of file openssl.c.
Referenced by tb_aicp_ssl_read_after().
tb_void_t tb_ssl_set_bio_func (tb_ssl_ref_t ssl, tb_ssl_func_read_t read, tb_ssl_func_writ_t writ, tb_ssl_func_wait_t wait, tb_cpointer_t priv)
set ssl bio read and writ func
Parameters
ssl the ssl handle
read the read func
writ the writ func #param wait the wait func only for tb_ssl_open and tb_ssl_wait
priv the priv data
Definition at line 448 of file openssl.c.
Referenced by tb_aicp_ssl_open(), tb_aicp_ssl_read_after(), tb_aicp_ssl_writ_after(), and tb_ssl_set_bio_sock().
tb_void_t tb_ssl_set_bio_sock (tb_ssl_ref_t ssl, tb_socket_ref_t sock)
set ssl bio sock
Parameters
ssl the ssl handle
sock the sock handle, non-blocking
Definition at line 439 of file openssl.c.
References tb_ssl_set_bio_func().
tb_void_t tb_ssl_set_timeout (tb_ssl_ref_t ssl, tb_long_t timeout)
set ssl timeout for opening
Parameters
ssl the ssl handle
timeout the timeout
Definition at line 460 of file openssl.c.
tb_size_t tb_ssl_state (tb_ssl_ref_t ssl)
the ssl state see the stream ssl state
Parameters
ssl the ssl handle
Returns
the ssl state
Definition at line 835 of file openssl.c.
Referenced by tb_aicp_ssl_open(), tb_aicp_ssl_read_after(), and tb_aicp_ssl_writ_after().
tb_long_t tb_ssl_wait (tb_ssl_ref_t ssl, tb_size_t code, tb_long_t timeout)
wait ssl data
Parameters
ssl the ssl handle
code the aioe code
timeout the timeout
Returns
the real code, no event: 0, failed or closed: -1
Definition at line 794 of file openssl.c.
Referenced by tb_ssl_clos(), and tb_ssl_open().
tb_long_t tb_ssl_writ (tb_ssl_ref_t ssl, tb_byte_t const * data, tb_size_t size)
writ ssl data
Parameters
ssl the ssl handle
data the data
size the size
Returns
the real size, no data: 0 and see state for waiting, failed: -1
Definition at line 731 of file openssl.c.
Referenced by tb_aicp_ssl_writ_after().