TBOX: src/memory/scache.h File Reference
scache.h File Reference
Memory
#include "prefix.h"
Functions
tb_bool_t tb_scache_init (tb_size_t align)
tb_void_t tb_scache_exit (tb_noarg_t)
exit scache
tb_void_t tb_scache_clear (tb_noarg_t)
clear scache
tb_char_t const * tb_scache_put (tb_char_t const *data)
tb_void_t tb_scache_del (tb_char_t const *data)
tb_void_t tb_scache_dump (tb_noarg_t)
dump scache
Detailed Description
The Treasure Box Library
TBox is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 2.1 of the License, or (at your option) any later version.
TBox is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with TBox; If not, see http://www.gnu.org/licenses/
Copyright (C) 2009 - 2015, ruki All rights reserved.
Author
ruki
Definition in file scache.h.
Function Documentation
tb_void_t tb_scache_del (tb_char_t const * data)
del string from scache
Parameters
data the string data
Definition at line 151 of file scache.c.
References tb_hash_item_t::data, tb_hash_itor(), tb_iterator_copy(), tb_iterator_delt(), and tb_iterator_item().
Referenced by tb_string_cstr_set().
tb_bool_t tb_scache_init (tb_size_t align)
init string cache for small, readonly and repeat strings
readonly, strip repeat strings and decrease memory fragmens
Parameters
align the cpu align bytes
Returns
tb_true or tb_false
Definition at line 51 of file scache.c.
References tb_hash_init(), tb_item_func_size(), and tb_item_func_str().
Referenced by tb_memory_init().
tb_char_t const* tb_scache_put (tb_char_t const * data)
put string to scache
Parameters
data the string data
Returns
the string data
Definition at line 99 of file scache.c.
References tb_hash_item_t::data, tb_hash_item_t::name, tb_hash_itor(), tb_hash_set(), tb_iterator_copy(), tb_iterator_delt(), and tb_iterator_item().
Referenced by tb_string_cstr_set(), tb_string_init_from_cstr(), and tb_string_init_from_pstr().