TBOX: src/tbox/math/random/random.h File Reference
random.h File Reference
Math
#include "prefix.h"
Functions
tb_handle_t tb_random_generator (tb_noarg_t)
tb_handle_t tb_random_init (tb_size_t type, tb_size_t seed)
tb_void_t tb_random_exit (tb_handle_t random)
tb_void_t tb_random_seed (tb_handle_t random, tb_size_t seed)
tb_void_t tb_random_clear (tb_handle_t random)
tb_long_t tb_random_range (tb_handle_t random, tb_long_t beg, tb_long_t end)
tb_float_t tb_random_rangef (tb_handle_t random, tb_float_t beg, tb_float_t end)
tb_long_t tb_random_value (tb_handle_t random)
Detailed Description
The Treasure Box Library
TBox is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 2.1 of the License, or (at your option) any later version.
TBox is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with TBox; If not, see http://www.gnu.org/licenses/
Copyright (C) 2009 - 2015, ruki All rights reserved.
Author
ruki
Definition in file random.h.
Function Documentation
tb_void_t tb_random_clear (tb_handle_t random)
clear cache value and reset to the initial value
Parameters
random the random handle
Definition at line 87 of file random.c.
References tb_random_t::clear.
tb_void_t tb_random_exit (tb_handle_t random)
exit random
Parameters
random the random handle
Definition at line 69 of file random.c.
References tb_random_t::exit.
tb_handle_t tb_random_generator (tb_noarg_t)
the random generator instance
Returns
the random handle
Referenced by tb_srandom().
tb_handle_t tb_random_init (tb_size_t type, tb_size_t seed)
init random
Parameters
type the generator type
seed the random seed
Returns
the random handle
Definition at line 56 of file random.c.
tb_long_t tb_random_range (tb_handle_t random, tb_long_t beg, tb_long_t end)
generate the random with range: [beg, end)
Parameters
random the random handle
beg the begin value
end the end value
Returns
the random value
Definition at line 96 of file random.c.
References tb_random_t::range.
Referenced by tb_random_rangef(), and tb_random_value().
tb_float_t tb_random_rangef (tb_handle_t random, tb_float_t beg, tb_float_t end)
generate the float random with range: [beg, end)
Parameters
random the random handle
beg the begin value
end the end value
Returns
the random value
Definition at line 106 of file random.c.
References tb_random_range().
tb_void_t tb_random_seed (tb_handle_t random, tb_size_t seed)
update random seed
Parameters
random the random handle
seed the random seed
Definition at line 78 of file random.c.
References tb_random_t::seed.
Referenced by tb_srandom().
tb_long_t tb_random_value (tb_handle_t random)
generate the random with range: [0, max)
Parameters
random the random handle
Returns
the random value
Definition at line 118 of file random.c.
References tb_random_range().