TBOX: src/tbox/object/object.h File Reference
object.h File Reference
#include "prefix.h"
#include "null.h"
#include "data.h"
#include "date.h"
#include "array.h"
#include "string.h"
#include "number.h"
#include "boolean.h"
#include "dictionary.h"
#include "reader/reader.h"
#include "writer/writer.h"
Functions
__tb_extern_c_enter__ tb_bool_t tb_object_context_init (tb_noarg_t)
tb_void_t tb_object_context_exit (tb_noarg_t)
exit object context
tb_bool_t tb_object_init (tb_object_ref_t object, tb_size_t flag, tb_size_t type)
tb_void_t tb_object_exit (tb_object_ref_t object)
tb_void_t tb_object_cler (tb_object_ref_t object)
tb_void_t tb_object_setp (tb_object_ref_t object, tb_cpointer_t priv)
tb_cpointer_t tb_object_getp (tb_object_ref_t object)
tb_object_ref_t tb_object_read (tb_stream_ref_t stream)
tb_object_ref_t tb_object_read_from_url (tb_char_t const *url)
tb_object_ref_t tb_object_read_from_data (tb_byte_t const *data, tb_size_t size)
tb_long_t tb_object_writ (tb_object_ref_t object, tb_stream_ref_t stream, tb_size_t format)
tb_long_t tb_object_writ_to_url (tb_object_ref_t object, tb_char_t const *url, tb_size_t format)
tb_long_t tb_object_writ_to_data (tb_object_ref_t object, tb_byte_t *data, tb_size_t size, tb_size_t format)
tb_object_ref_t tb_object_copy (tb_object_ref_t object)
tb_size_t tb_object_type (tb_object_ref_t object)
tb_object_ref_t tb_object_data (tb_object_ref_t object, tb_size_t format)
tb_object_ref_t tb_object_seek (tb_object_ref_t object, tb_char_t const *path, tb_size_t type)
tb_object_ref_t tb_object_dump (tb_object_ref_t object)
tb_size_t tb_object_ref (tb_object_ref_t object)
tb_void_t tb_object_inc (tb_object_ref_t object)
tb_void_t tb_object_dec (tb_object_ref_t object)
Detailed Description
The Treasure Box Library
TBox is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 2.1 of the License, or (at your option) any later version.
TBox is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with TBox; If not, see http://www.gnu.org/licenses/
Copyright (C) 2009 - 2015, ruki All rights reserved.
Author
ruki
Definition in file object.h.
Function Documentation
tb_void_t tb_object_cler (tb_object_ref_t object)
cler object
Parameters
object the object
Definition at line 107 of file object.c.
References tb_object_t::cler, and tb_object_t::flag.
__tb_extern_c_enter__ tb_bool_t tb_object_context_init (tb_noarg_t)
init object context
Returns
tb_true or tb_false
Referenced by tb_init_().
tb_object_ref_t tb_object_copy (tb_object_ref_t object)
copy object
Parameters
object the object
Returns
the object copy
Definition at line 130 of file object.c.
References tb_object_t::copy.
tb_object_ref_t tb_object_data (tb_object_ref_t object, tb_size_t format)
the object data
Parameters
object the object
format the format
Returns
the data object
Definition at line 143 of file object.c.
References tb_object_data_init_from_data(), and tb_object_writ_to_data().
Referenced by tb_object_dump().
tb_void_t tb_object_dec (tb_object_ref_t object)
decrease the object reference count, will free it if –refn == 0
Parameters
object the object
Definition at line 313 of file object.c.
References tb_object_t::exit, tb_object_t::flag, and tb_object_t::refn.
Referenced by tb_object_array_append(), tb_object_array_insert(), tb_object_array_replace(), tb_object_dictionary_set(), and tb_object_exit().
tb_object_ref_t tb_object_dump (tb_object_ref_t object)
dump the object
Parameters
object the object
Returns
the object
Definition at line 258 of file object.c.
References tb_object_data(), tb_object_data_getp(), tb_object_data_size(), tb_object_exit(), and tb_printf().
tb_void_t tb_object_exit (tb_object_ref_t object)
exit object
Parameters
object the object
Note
the reference count must be one
Definition at line 96 of file object.c.
References tb_object_t::flag, and tb_object_dec().
Referenced by tb_object_dump().
tb_cpointer_t tb_object_getp (tb_object_ref_t object)
get the object private data
Parameters
object the object
Returns
the private data
Definition at line 124 of file object.c.
tb_void_t tb_object_inc (tb_object_ref_t object)
increase the object reference count
Parameters
object the object
Definition at line 302 of file object.c.
References tb_object_t::flag.
tb_bool_t tb_object_init (tb_object_ref_t object, tb_size_t flag, tb_size_t type)
init object
Parameters
object the object
flag the object flag
type the object type
Returns
tb_true or tb_false
Definition at line 82 of file object.c.
tb_object_ref_t tb_object_read (tb_stream_ref_t stream)
read object
Parameters
stream the stream
Returns
the object
Definition at line 330 of file object.c.
Referenced by tb_object_read_from_data(), and tb_object_read_from_url().
tb_object_ref_t tb_object_read_from_data (tb_byte_t const * data, tb_size_t size)
read object from data
Parameters
data the data
size the size
Returns
the object
Definition at line 359 of file object.c.
References tb_object_read(), tb_stream_exit(), tb_stream_init_from_data(), and tb_stream_open().
tb_object_ref_t tb_object_read_from_url (tb_char_t const * url)
read object from url
Parameters
url the url
Returns
the object
Definition at line 338 of file object.c.
References tb_object_read(), tb_stream_exit(), tb_stream_init_from_url(), and tb_stream_open().
tb_size_t tb_object_ref (tb_object_ref_t object)
the object reference count
Parameters
object the object
Returns
the object reference count
Definition at line 297 of file object.c.
tb_object_ref_t tb_object_seek (tb_object_ref_t object, tb_char_t const * path, tb_size_t type)
seek to the object for the gived path
xml:
<dict>
     <key>string</key>
     <string>hello wolrd!</string>
     <key>com.xxx.xxx</key>
     <string>hello wolrd!</string>
     <key>integer</key>
     <number>31415926</number>
     <key>array</key>
     <array>
         <string>hello wolrd!</string>
         <number>31415926</number>
         <number>3.1415926</number>
         <false>
         <true>
         <dict>
             <key>string</key>
             <string>hello wolrd!</string>
         </dict>
     </array>
 </dict>
path:
1. ".string"             : hello wolrd!
2. ".array[1]"           : 31415926
3. ".array[5].string"    : hello wolrd!
4. ".com\\.xxx\\.xxx"    : hello wolrd!
Parameters
object the object
path the object path
type the object type, check it if not TB_OBJECT_TYPE_NONE
tb_object_ref_t object = tb_object_seek(root, ".array[5].string", TB_OBJECT_TYPE_STRING); if (object) { tb_trace_d("%s", tb_object_string_cstr(object)); } <endcode>
Returns
the object
Definition at line 175 of file object.c.
References tb_object_array_item(), tb_object_array_size(), tb_object_dictionary_val(), and tb_object_type().
tb_void_t tb_object_setp (tb_object_ref_t object, tb_cpointer_t priv)
set the object private data
Parameters
object the object
priv the private data
Definition at line 118 of file object.c.
tb_size_t tb_object_type (tb_object_ref_t object)
the object type
Parameters
object the object
Returns
the object type
Definition at line 138 of file object.c.
Referenced by tb_object_seek().
tb_long_t tb_object_writ (tb_object_ref_t object, tb_stream_ref_t stream, tb_size_t format)
writ object
Parameters
object the object
stream the stream
format the object format
Returns
the writed size, failed: -1
Definition at line 380 of file object.c.
Referenced by tb_object_writ_to_data(), and tb_object_writ_to_url().
tb_long_t tb_object_writ_to_data (tb_object_ref_t object, tb_byte_t * data, tb_size_t size, tb_size_t format)
writ object to data
Parameters
object the object
data the data
size the size
format the format
Returns
the writed size, failed: -1
Definition at line 412 of file object.c.
References tb_object_writ(), tb_stream_exit(), tb_stream_init_from_data(), and tb_stream_open().
Referenced by tb_object_data().
tb_long_t tb_object_writ_to_url (tb_object_ref_t object, tb_char_t const * url, tb_size_t format)
writ object to url
Parameters
object the object
url the url
format the format
Returns
the writed size, failed: -1
Definition at line 388 of file object.c.
References TB_FILE_MODE_BINARY, TB_FILE_MODE_CREAT, TB_FILE_MODE_RW, TB_FILE_MODE_TRUNC, tb_object_writ(), tb_stream_ctrl(), tb_stream_exit(), tb_stream_init_from_url(), tb_stream_open(), and tb_stream_type().