TBOX: src/tbox/stream/filter.h File Reference
filter.h File Reference
#include "prefix.h"
Data Structures
struct tb_stream_filter_ref_t
the stream filter ref type
Macros
#define TB_STREAM_FILTER_CTRL(type, ctrl) (((type) << 16) | (ctrl))
the stream filter ctrl
Enumerations
enum tb_stream_filter_type_e {
TB_STREAM_FILTER_TYPE_NONE = 0, TB_STREAM_FILTER_TYPE_ZIP = 1, TB_STREAM_FILTER_TYPE_CACHE = 2, TB_STREAM_FILTER_TYPE_CHARSET = 3,
TB_STREAM_FILTER_TYPE_CHUNKED = 4
}
the filter type enum
enum tb_stream_filter_ctrl_e {
TB_STREAM_FILTER_CTRL_NONE = 0, TB_STREAM_FILTER_CTRL_ZIP_GET_ALGO = TB_STREAM_FILTER_CTRL(TB_STREAM_FILTER_TYPE_ZIP, 1), TB_STREAM_FILTER_CTRL_ZIP_GET_ACTION = TB_STREAM_FILTER_CTRL(TB_STREAM_FILTER_TYPE_ZIP, 2), TB_STREAM_FILTER_CTRL_ZIP_SET_ALGO = TB_STREAM_FILTER_CTRL(TB_STREAM_FILTER_TYPE_ZIP, 3),
TB_STREAM_FILTER_CTRL_ZIP_SET_ACTION = TB_STREAM_FILTER_CTRL(TB_STREAM_FILTER_TYPE_ZIP, 4), TB_STREAM_FILTER_CTRL_CHARSET_GET_FTYPE = TB_STREAM_FILTER_CTRL(TB_STREAM_FILTER_TYPE_CHARSET, 1), TB_STREAM_FILTER_CTRL_CHARSET_GET_TTYPE = TB_STREAM_FILTER_CTRL(TB_STREAM_FILTER_TYPE_CHARSET, 2), TB_STREAM_FILTER_CTRL_CHARSET_SET_FTYPE = TB_STREAM_FILTER_CTRL(TB_STREAM_FILTER_TYPE_CHARSET, 3),
TB_STREAM_FILTER_CTRL_CHARSET_SET_TTYPE = TB_STREAM_FILTER_CTRL(TB_STREAM_FILTER_TYPE_CHARSET, 4)
}
the filter ctrl enum
Functions
tb_stream_filter_ref_t tb_stream_filter_init_from_zip (tb_size_t algo, tb_size_t action)
tb_stream_filter_ref_t tb_stream_filter_init_from_charset (tb_size_t fr, tb_size_t to)
tb_stream_filter_ref_t tb_stream_filter_init_from_chunked (tb_bool_t dechunked)
tb_stream_filter_ref_t tb_stream_filter_init_from_cache (tb_size_t size)
tb_void_t tb_stream_filter_exit (tb_stream_filter_ref_t filter)
tb_bool_t tb_stream_filter_open (tb_stream_filter_ref_t filter)
tb_void_t tb_stream_filter_clos (tb_stream_filter_ref_t filter)
tb_bool_t tb_stream_filter_ctrl (tb_stream_filter_ref_t filter, tb_size_t ctrl,...)
tb_bool_t tb_stream_filter_beof (tb_stream_filter_ref_t filter)
tb_void_t tb_stream_filter_limit (tb_stream_filter_ref_t filter, tb_hong_t limit)
tb_bool_t tb_stream_filter_push (tb_stream_filter_ref_t filter, tb_byte_t const *data, tb_size_t size)
tb_long_t tb_stream_filter_spak (tb_stream_filter_ref_t filter, tb_byte_t const *data, tb_size_t size, tb_byte_t const **pdata, tb_size_t need, tb_long_t sync)
Detailed Description
The Treasure Box Library
TBox is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 2.1 of the License, or (at your option) any later version.
TBox is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with TBox; If not, see http://www.gnu.org/licenses/
Copyright (C) 2009 - 2015, ruki All rights reserved.
Author
ruki
Definition in file filter.h.
Function Documentation
tb_bool_t tb_stream_filter_beof (tb_stream_filter_ref_t filter)
is eof for the filter input data, but the output maybe exists the left data and need flush it
Parameters
filter the filter
Returns
tb_true or tb_false
Definition at line 300 of file filter.c.
tb_void_t tb_stream_filter_clos (tb_stream_filter_ref_t filter)
clos filter
Parameters
filter the filter
Definition at line 55 of file filter.c.
References tb_buffer_clear(), and tb_queue_buffer_clear().
tb_bool_t tb_stream_filter_ctrl (tb_stream_filter_ref_t filter, tb_size_t ctrl, ...)
ctrl filter
Parameters
filter the filter
ctrl the ctrl code
Returns
tb_true or tb_false
Definition at line 103 of file filter.c.
tb_void_t tb_stream_filter_exit (tb_stream_filter_ref_t filter)
exit filter
Parameters
filter the filter
Definition at line 85 of file filter.c.
References tb_buffer_exit(), and tb_queue_buffer_exit().
Referenced by tb_stream_filter_init_from_cache(), tb_stream_filter_init_from_charset(), tb_stream_filter_init_from_chunked(), and tb_stream_filter_init_from_zip().
tb_stream_filter_ref_t tb_stream_filter_init_from_cache (tb_size_t size)
init filter from cache
Parameters
size the initial cache size, using the default size if be zero
Returns
the filter
Definition at line 93 of file cache.c.
References tb_queue_buffer_resize(), and tb_stream_filter_exit().
Referenced by tb_async_stream_init_filter_from_cache(), and tb_stream_init_filter_from_cache().
tb_stream_filter_ref_t tb_stream_filter_init_from_charset (tb_size_t fr, tb_size_t to)
init filter from charset
Parameters
fr the from charset
to the to charset
Returns
the filter
Definition at line 129 of file charset.c.
References tb_stream_filter_exit().
Referenced by tb_async_stream_init_filter_from_charset(), and tb_stream_init_filter_from_charset().
tb_stream_filter_ref_t tb_stream_filter_init_from_chunked (tb_bool_t dechunked)
init filter from chunked
Parameters
dechunked decode the chunked data?
Returns
the filter
Definition at line 235 of file chunked.c.
References tb_stream_filter_exit().
Referenced by tb_async_stream_init_filter_from_chunked(), and tb_stream_init_filter_from_chunked().
tb_stream_filter_ref_t tb_stream_filter_init_from_zip (tb_size_t algo, tb_size_t action)
init filter from zip
Parameters
algo the zip algorithm
action the zip action
Returns
the filter
Definition at line 160 of file zip.c.
References tb_stream_filter_exit().
Referenced by tb_async_stream_init_filter_from_zip(), and tb_stream_init_filter_from_zip().
tb_void_t tb_stream_filter_limit (tb_stream_filter_ref_t filter, tb_hong_t limit)
limit the input size for filter
Parameters
filter the filter
limit the input limit size
Definition at line 309 of file filter.c.
tb_bool_t tb_stream_filter_open (tb_stream_filter_ref_t filter)
open filter
Parameters
filter the filter
Returns
tb_true or tb_false
Definition at line 40 of file filter.c.
tb_bool_t tb_stream_filter_push (tb_stream_filter_ref_t filter, tb_byte_t const * data, tb_size_t size)
push data to the filter input data
Parameters
filter the filter
Returns
tb_true or tb_false
Definition at line 285 of file filter.c.
References tb_buffer_memncat().
tb_long_t tb_stream_filter_spak (tb_stream_filter_ref_t filter, tb_byte_t const * data, tb_size_t size, tb_byte_t const ** pdata, tb_size_t need, tb_long_t sync)
spak filter
Parameters
filter the filter
data the input data, maybe null
size the input size, maybe zero
pdata the output data
need the need output size, using the default size if zero
sync sync? 1: sync, 0: no sync, -1: end
Returns
> 0: the output size, 0: continue, -1: end
Definition at line 122 of file filter.c.
References tb_buffer_clear(), tb_buffer_data(), tb_buffer_memncat(), tb_buffer_memnmov(), tb_buffer_size(), tb_queue_buffer_maxn(), tb_queue_buffer_pull_exit(), tb_queue_buffer_pull_init(), tb_queue_buffer_push_exit(), tb_queue_buffer_push_init(), tb_queue_buffer_resize(), tb_queue_buffer_size(), tb_static_stream_init(), tb_static_stream_left(), tb_static_stream_offset(), and tb_static_stream_pos().