TBOX: src/tbox/algorithm/binary_find_if.c File Reference
binary_find_if.c File Reference
Algorithm
#include "binary_find_if.h"
Functions
tb_size_t tb_binary_find_if (tb_iterator_ref_t iterator, tb_size_t head, tb_size_t tail, tb_iterator_comp_t comp, tb_cpointer_t priv)
tb_size_t tb_binary_find_all_if (tb_iterator_ref_t iterator, tb_iterator_comp_t comp, tb_cpointer_t priv)
Detailed Description
The Treasure Box Library
TBox is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 2.1 of the License, or (at your option) any later version.
TBox is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with TBox; If not, see http://www.gnu.org/licenses/
Copyright (C) 2009 - 2015, ruki All rights reserved.
Author
ruki
Definition in file binary_find_if.c.
Function Documentation
tb_size_t tb_binary_find_all_if (tb_iterator_ref_t iterator, tb_iterator_comp_t comp, tb_cpointer_t priv)
binary find item for all if !comp(item, priv)
Parameters
iterator the iterator
comp the comparer func
priv the comparer data
Returns
the iterator itor
Definition at line 58 of file binary_find_if.c.
References tb_binary_find_if(), tb_iterator_head(), and tb_iterator_tail().
Referenced by tb_binary_find_all().
tb_size_t tb_binary_find_if (tb_iterator_ref_t iterator, tb_size_t head, tb_size_t tail, tb_iterator_comp_t comp, tb_cpointer_t priv)
binary find item if !comp(item, priv)
Parameters
iterator the iterator
head the iterator head
tail the iterator tail
comp the comparer func
priv the comparer data
Returns
the iterator itor
Definition at line 33 of file binary_find_if.c.
References tb_iterator_item(), tb_iterator_mode(), and TB_ITERATOR_MODE_RACCESS.
Referenced by tb_binary_find(), and tb_binary_find_all_if().