TBOX: src/tbox/memory/queue_buffer.c File Reference
queue_buffer.c File Reference
Memory
#include "memory.h"
#include "../libc/libc.h"
#include "../utils/utils.h"
Functions
tb_bool_t tb_queue_buffer_init (tb_queue_buffer_t *buffer, tb_size_t maxn)
tb_void_t tb_queue_buffer_exit (tb_queue_buffer_t *buffer)
tb_byte_t * tb_queue_buffer_data (tb_queue_buffer_t const *buffer)
tb_byte_t * tb_queue_buffer_head (tb_queue_buffer_t const *buffer)
tb_byte_t * tb_queue_buffer_tail (tb_queue_buffer_t const *buffer)
tb_size_t tb_queue_buffer_size (tb_queue_buffer_t const *buffer)
tb_size_t tb_queue_buffer_maxn (tb_queue_buffer_t const *buffer)
tb_size_t tb_queue_buffer_left (tb_queue_buffer_t const *buffer)
tb_bool_t tb_queue_buffer_full (tb_queue_buffer_t const *buffer)
tb_bool_t tb_queue_buffer_null (tb_queue_buffer_t const *buffer)
tb_void_t tb_queue_buffer_clear (tb_queue_buffer_t *buffer)
tb_byte_t * tb_queue_buffer_resize (tb_queue_buffer_t *buffer, tb_size_t maxn)
tb_long_t tb_queue_buffer_skip (tb_queue_buffer_t *buffer, tb_size_t size)
tb_long_t tb_queue_buffer_read (tb_queue_buffer_t *buffer, tb_byte_t *data, tb_size_t size)
tb_long_t tb_queue_buffer_writ (tb_queue_buffer_t *buffer, tb_byte_t const *data, tb_size_t size)
tb_byte_t * tb_queue_buffer_pull_init (tb_queue_buffer_t *buffer, tb_size_t *size)
tb_void_t tb_queue_buffer_pull_exit (tb_queue_buffer_t *buffer, tb_size_t size)
tb_byte_t * tb_queue_buffer_push_init (tb_queue_buffer_t *buffer, tb_size_t *size)
tb_void_t tb_queue_buffer_push_exit (tb_queue_buffer_t *buffer, tb_size_t size)
Detailed Description
The Treasure Box Library
TBox is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 2.1 of the License, or (at your option) any later version.
TBox is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with TBox; If not, see http://www.gnu.org/licenses/
Copyright (C) 2009 - 2015, ruki All rights reserved.
Author
ruki
Definition in file queue_buffer.c.
Function Documentation
tb_void_t tb_queue_buffer_clear (tb_queue_buffer_t * buffer)
clear buffer
Parameters
buffer the buffer
Definition at line 105 of file queue_buffer.c.
Referenced by tb_stream_clos(), tb_stream_filter_clos(), and tb_stream_seek().
tb_byte_t* tb_queue_buffer_data (tb_queue_buffer_t const * buffer)
the buffer data
Parameters
buffer the buffer
Returns
the buffer data
Definition at line 61 of file queue_buffer.c.
tb_void_t tb_queue_buffer_exit (tb_queue_buffer_t * buffer)
exit buffer
Parameters
buffer the buffer
Definition at line 49 of file queue_buffer.c.
Referenced by tb_stream_exit(), and tb_stream_filter_exit().
tb_bool_t tb_queue_buffer_full (tb_queue_buffer_t const * buffer)
the buffer full?
Parameters
buffer the buffer
Returns
tb_true or tb_false
Definition at line 91 of file queue_buffer.c.
Referenced by tb_stream_wait(), and tb_stream_writ().
tb_byte_t* tb_queue_buffer_head (tb_queue_buffer_t const * buffer)
the buffer head
Parameters
buffer the buffer
Returns
the buffer head
Definition at line 66 of file queue_buffer.c.
Referenced by tb_stream_need().
tb_bool_t tb_queue_buffer_init (tb_queue_buffer_t * buffer, tb_size_t maxn)
init buffer
Parameters
buffer the buffer
maxn the buffer maxn
Returns
tb_true or tb_false
Definition at line 35 of file queue_buffer.c.
Referenced by tb_stream_init().
tb_size_t tb_queue_buffer_left (tb_queue_buffer_t const * buffer)
the buffer left
Parameters
buffer the buffer
Returns
the buffer left
Definition at line 86 of file queue_buffer.c.
tb_size_t tb_queue_buffer_maxn (tb_queue_buffer_t const * buffer)
the buffer maxn
Parameters
buffer the buffer
Returns
the buffer maxn
Definition at line 81 of file queue_buffer.c.
Referenced by tb_stream_filter_spak(), tb_stream_need(), tb_stream_read(), tb_stream_seek(), tb_stream_sync(), tb_stream_wait(), and tb_stream_writ().
tb_bool_t tb_queue_buffer_null (tb_queue_buffer_t const * buffer)
the buffer null?
Parameters
buffer the buffer
Returns
tb_true or tb_false
Definition at line 96 of file queue_buffer.c.
Referenced by tb_stream_bread(), tb_stream_need(), tb_stream_read(), tb_stream_seek(), tb_stream_sync(), tb_stream_wait(), and tb_stream_writ().
tb_void_t tb_queue_buffer_pull_exit (tb_queue_buffer_t * buffer, tb_size_t size)
exit pull buffer for reading
Parameters
buffer the buffer
size the size
Definition at line 248 of file queue_buffer.c.
Referenced by tb_stream_filter_spak(), tb_stream_seek(), tb_stream_sync(), and tb_stream_writ().
tb_byte_t* tb_queue_buffer_pull_init (tb_queue_buffer_t * buffer, tb_size_t * size)
init pull buffer for reading
Parameters
buffer the buffer
size the size
Returns
the data
Definition at line 233 of file queue_buffer.c.
Referenced by tb_stream_filter_spak(), tb_stream_seek(), tb_stream_sync(), and tb_stream_writ().
tb_void_t tb_queue_buffer_push_exit (tb_queue_buffer_t * buffer, tb_size_t size)
exit push buffer for writing
Parameters
buffer the buffer
size the size
Definition at line 295 of file queue_buffer.c.
Referenced by tb_stream_filter_spak(), tb_stream_need(), and tb_stream_read().
tb_byte_t* tb_queue_buffer_push_init (tb_queue_buffer_t * buffer, tb_size_t * size)
init push buffer for writing
Parameters
buffer the buffer
size the size
Returns
the data
Definition at line 260 of file queue_buffer.c.
Referenced by tb_stream_filter_spak(), tb_stream_need(), and tb_stream_read().
tb_long_t tb_queue_buffer_read (tb_queue_buffer_t * buffer, tb_byte_t * data, tb_size_t size)
read buffer
Parameters
buffer the buffer
data the data
size the size
Returns
the real size
Definition at line 170 of file queue_buffer.c.
Referenced by tb_stream_read().
tb_byte_t* tb_queue_buffer_resize (tb_queue_buffer_t * buffer, tb_size_t maxn)
resize buffer size
Parameters
buffer the buffer
maxn the buffer maxn
Returns
the buffer data
Definition at line 111 of file queue_buffer.c.
Referenced by tb_stream_filter_init_from_cache(), tb_stream_filter_spak(), and tb_stream_need().
tb_size_t tb_queue_buffer_size (tb_queue_buffer_t const * buffer)
the buffer size
Parameters
buffer the buffer
Returns
the buffer size
Definition at line 76 of file queue_buffer.c.
Referenced by tb_stream_filter_spak(), and tb_stream_need().
tb_long_t tb_queue_buffer_skip (tb_queue_buffer_t * buffer, tb_size_t size)
skip buffer
Parameters
buffer the buffer
size the skiped size
Returns
the real size
Definition at line 147 of file queue_buffer.c.
tb_byte_t* tb_queue_buffer_tail (tb_queue_buffer_t const * buffer)
the buffer tail
Parameters
buffer the buffer
Returns
the buffer tail
Definition at line 71 of file queue_buffer.c.
tb_long_t tb_queue_buffer_writ (tb_queue_buffer_t * buffer, tb_byte_t const * data, tb_size_t size)
writ buffer
Parameters
buffer the buffer
data the data
size the size
Returns
the real size
Definition at line 191 of file queue_buffer.c.
Referenced by tb_stream_writ().