TBOX: src/container/slist.c File Reference
slist.c File Reference
Container
#include "slist.h"
#include "../libc/libc.h"
#include "../utils/utils.h"
#include "../memory/memory.h"
#include "../platform/platform.h"
Functions
tb_slist_t * tb_slist_init (tb_size_t grow, tb_item_func_t func)
tb_void_t tb_slist_exit (tb_slist_t *handle)
tb_void_t tb_slist_clear (tb_slist_t *handle)
tb_pointer_t tb_slist_head (tb_slist_t const *handle)
tb_pointer_t tb_slist_last (tb_slist_t const *handle)
tb_size_t tb_slist_size (tb_slist_t const *handle)
tb_size_t tb_slist_maxn (tb_slist_t const *handle)
tb_size_t tb_slist_insert_prev (tb_slist_t *handle, tb_size_t itor, tb_cpointer_t data)
tb_size_t tb_slist_insert_next (tb_slist_t *handle, tb_size_t itor, tb_cpointer_t data)
tb_size_t tb_slist_insert_head (tb_slist_t *handle, tb_cpointer_t data)
tb_size_t tb_slist_insert_tail (tb_slist_t *handle, tb_cpointer_t data)
tb_size_t tb_slist_ninsert_prev (tb_slist_t *handle, tb_size_t itor, tb_cpointer_t data, tb_size_t size)
tb_size_t tb_slist_ninsert_next (tb_slist_t *handle, tb_size_t itor, tb_cpointer_t data, tb_size_t size)
tb_size_t tb_slist_ninsert_head (tb_slist_t *handle, tb_cpointer_t data, tb_size_t size)
tb_size_t tb_slist_ninsert_tail (tb_slist_t *handle, tb_cpointer_t data, tb_size_t size)
tb_size_t tb_slist_replace (tb_slist_t *handle, tb_size_t itor, tb_cpointer_t data)
tb_size_t tb_slist_replace_head (tb_slist_t *handle, tb_cpointer_t data)
tb_size_t tb_slist_replace_last (tb_slist_t *handle, tb_cpointer_t data)
tb_size_t tb_slist_nreplace (tb_slist_t *handle, tb_size_t itor, tb_cpointer_t data, tb_size_t size)
tb_size_t tb_slist_nreplace_head (tb_slist_t *handle, tb_cpointer_t data, tb_size_t size)
tb_size_t tb_slist_nreplace_last (tb_slist_t *handle, tb_cpointer_t data, tb_size_t size)
tb_size_t tb_slist_remove (tb_slist_t *handle, tb_size_t itor)
tb_size_t tb_slist_remove_next (tb_slist_t *handle, tb_size_t itor)
tb_size_t tb_slist_remove_head (tb_slist_t *handle)
tb_size_t tb_slist_remove_last (tb_slist_t *handle)
tb_size_t tb_slist_nremove (tb_slist_t *handle, tb_size_t itor, tb_size_t size)
tb_size_t tb_slist_nremove_next (tb_slist_t *handle, tb_size_t itor, tb_size_t size)
tb_size_t tb_slist_nremove_head (tb_slist_t *handle, tb_size_t size)
tb_size_t tb_slist_nremove_last (tb_slist_t *handle, tb_size_t size)
tb_size_t tb_slist_moveto_prev (tb_slist_t *handle, tb_size_t itor, tb_size_t move)
tb_size_t tb_slist_moveto_next (tb_slist_t *handle, tb_size_t itor, tb_size_t move)
tb_size_t tb_slist_moveto_head (tb_slist_t *handle, tb_size_t move)
tb_size_t tb_slist_moveto_tail (tb_slist_t *handle, tb_size_t move)
tb_void_t tb_slist_walk (tb_slist_t *handle, tb_bool_t(*func)(tb_slist_t *slist, tb_pointer_t item, tb_bool_t *bdel, tb_pointer_t priv), tb_pointer_t priv)
Detailed Description
The Treasure Box Library
TBox is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 2.1 of the License, or (at your option) any later version.
TBox is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with TBox; If not, see http://www.gnu.org/licenses/
Copyright (C) 2009 - 2015, ruki All rights reserved.
Author
ruki
Definition in file slist.c.
Function Documentation
tb_void_t tb_slist_clear (tb_slist_t * slist)
clear slist
Parameters
slist the slist
Definition at line 369 of file slist.c.
References tb_rpool_clear().
Referenced by tb_slist_exit().
tb_void_t tb_slist_exit (tb_slist_t * slist)
exit slist
Parameters
slist the slist
Definition at line 354 of file slist.c.
References tb_rpool_exit(), and tb_slist_clear().
Referenced by tb_mstream_exit(), and tb_slist_init().
tb_pointer_t tb_slist_head (tb_slist_t const * slist)
the slist head item
Parameters
slist the slist
Returns
the head item
Definition at line 399 of file slist.c.
References tb_iterator_head(), and tb_iterator_item().
tb_slist_t* tb_slist_init (tb_size_t grow, tb_item_func_t func)
init slist
Parameters
grow the item grow
func the item func
Returns
the slist
Definition at line 315 of file slist.c.
References tb_item_func_t::dupl, tb_item_func_t::repl, tb_item_func_t::size, TB_ITERATOR_MODE_FORWARD, TB_ITERATOR_MODE_REVERSE, tb_rpool_init(), and tb_slist_exit().
Referenced by tb_mstream_done().
tb_size_t tb_slist_insert_head (tb_slist_t * slist, tb_cpointer_t data)
insert the head item
Parameters
slist the slist
data the item data
Returns
the item itor
Definition at line 466 of file slist.c.
References tb_iterator_head(), and tb_slist_insert_prev().
tb_size_t tb_slist_insert_next (tb_slist_t * slist, tb_size_t itor, tb_cpointer_t data)
insert the next item
Parameters
slist the slist
itor the item itor
data the item data
Returns
the item itor
Definition at line 447 of file slist.c.
References tb_rpool_malloc().
Referenced by tb_slist_insert_prev(), and tb_slist_ninsert_next().
tb_size_t tb_slist_insert_prev (tb_slist_t * slist, tb_size_t itor, tb_cpointer_t data)
insert the prev item
Parameters
slist the slist
itor the item itor
data the item data
Returns
the item itor
Definition at line 443 of file slist.c.
References tb_iterator_prev(), and tb_slist_insert_next().
Referenced by tb_slist_insert_head(), and tb_slist_insert_tail().
tb_size_t tb_slist_insert_tail (tb_slist_t * slist, tb_cpointer_t data)
insert the tail item
Parameters
slist the slist
data the item data
Returns
the item itor
Definition at line 470 of file slist.c.
References tb_iterator_tail(), and tb_slist_insert_prev().
Referenced by tb_mstream_done().
tb_pointer_t tb_slist_last (tb_slist_t const * slist)
the slist last item
Parameters
slist the slist
Returns
the last item
Definition at line 403 of file slist.c.
References tb_iterator_item(), and tb_iterator_last().
tb_size_t tb_slist_maxn (tb_slist_t const * slist)
the item max count
Parameters
slist the slist
Returns
the item max count
Definition at line 413 of file slist.c.
tb_size_t tb_slist_moveto_head (tb_slist_t * slist, tb_size_t move)
moveto the head item
Parameters
slist the slist
itor the item itor
Returns
the move itor
Definition at line 665 of file slist.c.
References tb_iterator_head(), and tb_slist_moveto_prev().
tb_size_t tb_slist_moveto_next (tb_slist_t * slist, tb_size_t itor, tb_size_t move)
moveto the next item
Parameters
slist the slist
itor the item itor
move the move itor
Returns
the move itor
Definition at line 652 of file slist.c.
References tb_iterator_prev().
Referenced by tb_slist_moveto_prev().
tb_size_t tb_slist_moveto_prev (tb_slist_t * slist, tb_size_t itor, tb_size_t move)
moveto the prev item
Parameters
slist the slist
itor the item itor
move the move itor
Returns
the move itor
Definition at line 648 of file slist.c.
References tb_iterator_prev(), and tb_slist_moveto_next().
Referenced by tb_slist_moveto_head(), and tb_slist_moveto_tail().
tb_size_t tb_slist_moveto_tail (tb_slist_t * slist, tb_size_t move)
moveto the tail item
Parameters
slist the slist
itor the item itor
Returns
the move itor
Definition at line 669 of file slist.c.
References tb_iterator_tail(), and tb_slist_moveto_prev().
tb_size_t tb_slist_ninsert_head (tb_slist_t * slist, tb_cpointer_t data, tb_size_t size)
insert the head items
Parameters
slist the slist
data the item data
size the item count
Returns
the first item itor
Definition at line 491 of file slist.c.
References tb_iterator_head(), and tb_slist_ninsert_prev().
tb_size_t tb_slist_ninsert_next (tb_slist_t * slist, tb_size_t itor, tb_cpointer_t data, tb_size_t size)
insert the next items
Parameters
slist the slist
itor the prev item itor
data the item data
size the item count
Returns
the first item itor
Definition at line 478 of file slist.c.
References tb_slist_insert_next().
Referenced by tb_slist_ninsert_prev().
tb_size_t tb_slist_ninsert_prev (tb_slist_t * slist, tb_size_t itor, tb_cpointer_t data, tb_size_t size)
insert the prev items
Parameters
slist the slist
itor the prev item itor
data the item data
size the item count
Returns
the first item itor
Definition at line 474 of file slist.c.
References tb_iterator_prev(), and tb_slist_ninsert_next().
Referenced by tb_slist_ninsert_head(), and tb_slist_ninsert_tail().
tb_size_t tb_slist_ninsert_tail (tb_slist_t * slist, tb_cpointer_t data, tb_size_t size)
insert the tail items
Parameters
slist the slist
data the item data
size the item count
Returns
the first item itor
Definition at line 495 of file slist.c.
References tb_iterator_tail(), and tb_slist_ninsert_prev().
tb_size_t tb_slist_nremove (tb_slist_t * slist, tb_size_t itor, tb_size_t size)
remove the next items
Parameters
slist the slist
itor the item itor
size the item count
Returns
the prev item itor
Definition at line 611 of file slist.c.
References tb_iterator_prev(), and tb_slist_nremove_next().
Referenced by tb_slist_nremove_head().
tb_size_t tb_slist_nremove_head (tb_slist_t * slist, tb_size_t size)
remove the head items
Parameters
slist the slist
size the item count
Returns
the head item itor
Definition at line 625 of file slist.c.
References tb_iterator_head(), and tb_slist_nremove().
tb_size_t tb_slist_nremove_last (tb_slist_t * slist, tb_size_t size)
remove the last items
Parameters
slist the slist
size the item count
Returns
the last item itor
Definition at line 630 of file slist.c.
References tb_iterator_head(), tb_iterator_last(), tb_iterator_next(), tb_iterator_tail(), tb_slist_nremove_next(), and tb_slist_size().
tb_size_t tb_slist_nremove_next (tb_slist_t * slist, tb_size_t itor, tb_size_t size)
remove the next items
Parameters
slist the slist
itor the item itor
size the item count
Returns
the prev item itor
Definition at line 615 of file slist.c.
References tb_slist_remove_next().
Referenced by tb_slist_nremove(), and tb_slist_nremove_last().
tb_size_t tb_slist_nreplace (tb_slist_t * slist, tb_size_t itor, tb_cpointer_t data, tb_size_t size)
replace the items
Parameters
slist the slist
itor the first item itor
data the item data
size the item count
Returns
the first item itor
Definition at line 522 of file slist.c.
References tb_iterator_next(), tb_iterator_tail(), and tb_slist_replace().
Referenced by tb_slist_nreplace_head(), and tb_slist_nreplace_last().
tb_size_t tb_slist_nreplace_head (tb_slist_t * slist, tb_cpointer_t data, tb_size_t size)
replace the head items
Parameters
slist the slist
data the item data
size the item count
Returns
the first item itor
Definition at line 534 of file slist.c.
References tb_iterator_head(), and tb_slist_nreplace().
tb_size_t tb_slist_nreplace_last (tb_slist_t * slist, tb_cpointer_t data, tb_size_t size)
replace the tail items
Parameters
slist the slist
data the item data
size the item count
Returns
the first item itor
Definition at line 538 of file slist.c.
References tb_iterator_head(), tb_iterator_next(), tb_iterator_tail(), tb_slist_nreplace(), and tb_slist_size().
tb_size_t tb_slist_remove (tb_slist_t * slist, tb_size_t itor)
remove the item
Parameters
slist the slist
itor the item itor
Returns
the prev item itor
Definition at line 576 of file slist.c.
References tb_iterator_prev(), and tb_slist_remove_next().
Referenced by tb_slist_remove_head(), and tb_slist_remove_last().
tb_size_t tb_slist_remove_head (tb_slist_t * slist)
remove the head item
Parameters
slist the slist
Returns
the head item itor
Definition at line 603 of file slist.c.
References tb_iterator_head(), and tb_slist_remove().
tb_size_t tb_slist_remove_last (tb_slist_t * slist)
remove the last item
Parameters
slist the slist
Returns
the last item itor
Definition at line 607 of file slist.c.
References tb_iterator_last(), and tb_slist_remove().
tb_size_t tb_slist_remove_next (tb_slist_t * slist, tb_size_t itor)
remove the next item
Parameters
slist the slist
itor the item itor
Returns
the prev item itor
Definition at line 580 of file slist.c.
References tb_iterator_next(), and tb_rpool_free().
Referenced by tb_slist_nremove_next(), and tb_slist_remove().
tb_size_t tb_slist_replace (tb_slist_t * slist, tb_size_t itor, tb_cpointer_t data)
replace the item
Parameters
slist the slist
itor the item itor
data the item data
Returns
the item itor
Definition at line 499 of file slist.c.
Referenced by tb_slist_nreplace(), tb_slist_replace_head(), and tb_slist_replace_last().
tb_size_t tb_slist_replace_head (tb_slist_t * slist, tb_cpointer_t data)
replace the head item
Parameters
slist the slist
data the item data
Returns
the item itor
Definition at line 514 of file slist.c.
References tb_iterator_head(), and tb_slist_replace().
tb_size_t tb_slist_replace_last (tb_slist_t * slist, tb_cpointer_t data)
replace the tail item
Parameters
slist the slist
data the item data
Returns
the item itor
Definition at line 518 of file slist.c.
References tb_iterator_last(), and tb_slist_replace().
tb_size_t tb_slist_size (tb_slist_t const * slist)
the item count
Parameters
slist the slist
Returns
the item count
Definition at line 407 of file slist.c.
References tb_rpool_size().
Referenced by tb_mstream_done(), tb_slist_nremove_last(), and tb_slist_nreplace_last().
tb_void_t tb_slist_walk (tb_slist_t * slist, tb_bool_t(*)(tb_slist_t *slist, tb_pointer_t item, tb_bool_t *bdel, tb_pointer_t priv) func, tb_pointer_t priv)
walk list items
be faster than the iterator mode, optimizate to remove items for walking
tb_bool_t tb_slist_item_func(tb_slist_t* slist, tb_pointer_t item, tb_bool_t* bdel, tb_pointer_t priv)
{
    tb_assert_and_check_return_val(slist && bdel, tb_false);
        // delete it?
        // *bdel = tb_true;
        // continue or break
        return tb_true;
}
Parameters
slist the slist
func the walk func
priv the walk priv
Definition at line 673 of file slist.c.
References tb_rpool_free().