TBOX: src/tbox/asio/aico.h File Reference
aico.h File Reference
Asio
#include "prefix.h"
#include "../network/ipv4.h"
Macros
#define tb_aico_clos(aico, func, priv) tb_aico_clos_(aico, func, priv __tb_debug_vals__)
#define tb_aico_acpt(aico, func, priv) tb_aico_acpt_(aico, func, priv __tb_debug_vals__)
#define tb_aico_conn(aico, addr, port, func, priv) tb_aico_conn_(aico, addr, port, func, priv __tb_debug_vals__)
#define tb_aico_recv(aico, data, size, func, priv) tb_aico_recv_(aico, data, size, func, priv __tb_debug_vals__)
#define tb_aico_send(aico, data, size, func, priv) tb_aico_send_(aico, data, size, func, priv __tb_debug_vals__)
#define tb_aico_urecv(aico, addr, port, data, size, func, priv) tb_aico_urecv_(aico, addr, port, data, size, func, priv __tb_debug_vals__)
#define tb_aico_usend(aico, addr, port, data, size, func, priv) tb_aico_usend_(aico, addr, port, data, size, func, priv __tb_debug_vals__)
#define tb_aico_recvv(aico, list, size, func, priv) tb_aico_recvv_(aico, list, size, func, priv __tb_debug_vals__)
#define tb_aico_sendv(aico, list, size, func, priv) tb_aico_sendv_(aico, list, size, func, priv __tb_debug_vals__)
#define tb_aico_urecvv(aico, addr, port, list, size, func, priv) tb_aico_urecvv_(aico, addr, port, list, size, func, priv __tb_debug_vals__)
#define tb_aico_usendv(aico, addr, port, list, size, func, priv) tb_aico_usendv_(aico, addr, port, list, size, func, priv __tb_debug_vals__)
#define tb_aico_sendf(aico, file, seek, size, func, priv) tb_aico_sendf_(aico, file, seek, size, func, priv __tb_debug_vals__)
#define tb_aico_read(aico, seek, data, size, func, priv) tb_aico_read_(aico, seek, data, size, func, priv __tb_debug_vals__)
#define tb_aico_writ(aico, seek, data, size, func, priv) tb_aico_writ_(aico, seek, data, size, func, priv __tb_debug_vals__)
#define tb_aico_readv(aico, seek, list, size, func, priv) tb_aico_readv_(aico, seek, list, size, func, priv __tb_debug_vals__)
#define tb_aico_writv(aico, seek, list, size, func, priv) tb_aico_writv_(aico, seek, list, size, func, priv __tb_debug_vals__)
#define tb_aico_fsync(aico, func, priv) tb_aico_fsync_(aico, func, priv __tb_debug_vals__)
#define tb_aico_clos_after(aico, delay, func, priv) tb_aico_clos_after_(aico, delay, func, priv __tb_debug_vals__)
#define tb_aico_acpt_after(aico, delay, func, priv) tb_aico_acpt_after_(aico, delay, func, priv __tb_debug_vals__)
#define tb_aico_conn_after(aico, delay, addr, port, func, priv) tb_aico_conn_after_(aico, delay, addr, port, func, priv __tb_debug_vals__)
#define tb_aico_recv_after(aico, delay, data, size, func, priv) tb_aico_recv_after_(aico, delay, data, size, func, priv __tb_debug_vals__)
#define tb_aico_send_after(aico, delay, data, size, func, priv) tb_aico_send_after_(aico, delay, data, size, func, priv __tb_debug_vals__)
#define tb_aico_urecv_after(aico, delay, addr, port, data, size, func, priv) tb_aico_urecv_after_(aico, delay, addr, port, data, size, func, priv __tb_debug_vals__)
#define tb_aico_usend_after(aico, delay, addr, port, data, size, func, priv) tb_aico_usend_after_(aico, delay, addr, port, data, size, func, priv __tb_debug_vals__)
#define tb_aico_recvv_after(aico, delay, list, size, func, priv) tb_aico_recvv_after_(aico, delay, list, size, func, priv __tb_debug_vals__)
#define tb_aico_sendv_after(aico, delay, list, size, func, priv) tb_aico_sendv_after_(aico, delay, list, size, func, priv __tb_debug_vals__)
#define tb_aico_urecvv_after(aico, delay, addr, port, list, size, func, priv) tb_aico_urecvv_after_(aico, delay, addr, port, list, size, func, priv __tb_debug_vals__)
#define tb_aico_usendv_after(aico, delay, addr, port, list, size, func, priv) tb_aico_usendv_after_(aico, delay, addr, port, list, size, func, priv __tb_debug_vals__)
#define tb_aico_sendf_after(aico, delay, file, seek, size, func, priv) tb_aico_sendf_after_(aico, delay, file, seek, size, func, priv __tb_debug_vals__)
#define tb_aico_read_after(aico, delay, seek, data, size, func, priv) tb_aico_read_after_(aico, delay, seek, data, size, func, priv __tb_debug_vals__)
#define tb_aico_writ_after(aico, delay, seek, data, size, func, priv) tb_aico_writ_after_(aico, delay, seek, data, size, func, priv __tb_debug_vals__)
#define tb_aico_readv_after(aico, delay, seek, list, size, func, priv) tb_aico_readv_after_(aico, delay, seek, list, size, func, priv __tb_debug_vals__)
#define tb_aico_writv_after(aico, delay, seek, list, size, func, priv) tb_aico_writv_after_(aico, delay, seek, list, size, func, priv __tb_debug_vals__)
#define tb_aico_fsync_after(aico, delay, func, priv) tb_aico_fsync_after_(aico, delay, func, priv __tb_debug_vals__)
#define tb_aico_task_run(aico, delay, func, priv) tb_aico_task_run_(aico, delay, func, priv __tb_debug_vals__)
Typedefs
typedef tb_bool_t(* tb_aico_func_t)(struct __tb_aice_t const *aice)
the aico func type
Enumerations
enum tb_aico_type_e {
TB_AICO_TYPE_NONE = 0, TB_AICO_TYPE_SOCK = 1, TB_AICO_TYPE_FILE = 2, TB_AICO_TYPE_TASK = 3,
TB_AICO_TYPE_MAXN = 4
}
the aico type enum
enum tb_aico_timeout_e { TB_AICO_TIMEOUT_CONN = 0, TB_AICO_TIMEOUT_RECV = 1, TB_AICO_TIMEOUT_SEND = 2, TB_AICO_TIMEOUT_MAXN = 3 }
the aico timeout enum, only for sock
Functions
tb_aico_ref_t tb_aico_init (tb_aicp_ref_t aicp)
tb_bool_t tb_aico_open_sock (tb_aico_ref_t aico, tb_socket_ref_t sock)
tb_bool_t tb_aico_open_sock_from_type (tb_aico_ref_t aico, tb_size_t type)
tb_bool_t tb_aico_open_file (tb_aico_ref_t aico, tb_file_ref_t file)
tb_bool_t tb_aico_open_file_from_path (tb_aico_ref_t aico, tb_char_t const *path, tb_size_t mode)
tb_bool_t tb_aico_open_task (tb_aico_ref_t aico, tb_bool_t ltimer)
tb_void_t tb_aico_kill (tb_aico_ref_t aico)
tb_void_t tb_aico_exit (tb_aico_ref_t aico)
tb_aicp_ref_t tb_aico_aicp (tb_aico_ref_t aico)
tb_size_t tb_aico_type (tb_aico_ref_t aico)
tb_socket_ref_t tb_aico_sock (tb_aico_ref_t aico)
tb_file_ref_t tb_aico_file (tb_aico_ref_t aico)
tb_bool_t tb_aico_clos_try (tb_aico_ref_t aico)
tb_long_t tb_aico_timeout (tb_aico_ref_t aico, tb_size_t type)
tb_void_t tb_aico_timeout_set (tb_aico_ref_t aico, tb_size_t type, tb_long_t timeout)
tb_bool_t tb_aico_clos_ (tb_aico_ref_t aico, tb_aico_func_t func, tb_cpointer_t priv __tb_debug_decl__)
tb_bool_t tb_aico_acpt_ (tb_aico_ref_t aico, tb_aico_func_t func, tb_cpointer_t priv __tb_debug_decl__)
tb_bool_t tb_aico_conn_ (tb_aico_ref_t aico, tb_ipv4_t const *addr, tb_uint16_t port, tb_aico_func_t func, tb_cpointer_t priv __tb_debug_decl__)
tb_bool_t tb_aico_recv_ (tb_aico_ref_t aico, tb_byte_t *data, tb_size_t size, tb_aico_func_t func, tb_cpointer_t priv __tb_debug_decl__)
tb_bool_t tb_aico_send_ (tb_aico_ref_t aico, tb_byte_t const *data, tb_size_t size, tb_aico_func_t func, tb_cpointer_t priv __tb_debug_decl__)
tb_bool_t tb_aico_urecv_ (tb_aico_ref_t aico, tb_ipv4_t const *addr, tb_uint16_t port, tb_byte_t *data, tb_size_t size, tb_aico_func_t func, tb_cpointer_t priv __tb_debug_decl__)
tb_bool_t tb_aico_usend_ (tb_aico_ref_t aico, tb_ipv4_t const *addr, tb_uint16_t port, tb_byte_t const *data, tb_size_t size, tb_aico_func_t func, tb_cpointer_t priv __tb_debug_decl__)
tb_bool_t tb_aico_recvv_ (tb_aico_ref_t aico, tb_iovec_t const *list, tb_size_t size, tb_aico_func_t func, tb_cpointer_t priv __tb_debug_decl__)
tb_bool_t tb_aico_sendv_ (tb_aico_ref_t aico, tb_iovec_t const *list, tb_size_t size, tb_aico_func_t func, tb_cpointer_t priv __tb_debug_decl__)
tb_bool_t tb_aico_urecvv_ (tb_aico_ref_t aico, tb_ipv4_t const *addr, tb_uint16_t port, tb_iovec_t const *list, tb_size_t size, tb_aico_func_t func, tb_cpointer_t priv __tb_debug_decl__)
tb_bool_t tb_aico_usendv_ (tb_aico_ref_t aico, tb_ipv4_t const *addr, tb_uint16_t port, tb_iovec_t const *list, tb_size_t size, tb_aico_func_t func, tb_cpointer_t priv __tb_debug_decl__)
tb_bool_t tb_aico_sendf_ (tb_aico_ref_t aico, tb_file_ref_t file, tb_hize_t seek, tb_hize_t size, tb_aico_func_t func, tb_cpointer_t priv __tb_debug_decl__)
tb_bool_t tb_aico_read_ (tb_aico_ref_t aico, tb_hize_t seek, tb_byte_t *data, tb_size_t size, tb_aico_func_t func, tb_cpointer_t priv __tb_debug_decl__)
tb_bool_t tb_aico_writ_ (tb_aico_ref_t aico, tb_hize_t seek, tb_byte_t const *data, tb_size_t size, tb_aico_func_t func, tb_cpointer_t priv __tb_debug_decl__)
tb_bool_t tb_aico_readv_ (tb_aico_ref_t aico, tb_hize_t seek, tb_iovec_t const *list, tb_size_t size, tb_aico_func_t func, tb_cpointer_t priv __tb_debug_decl__)
tb_bool_t tb_aico_writv_ (tb_aico_ref_t aico, tb_hize_t seek, tb_iovec_t const *list, tb_size_t size, tb_aico_func_t func, tb_cpointer_t priv __tb_debug_decl__)
tb_bool_t tb_aico_fsync_ (tb_aico_ref_t aico, tb_aico_func_t func, tb_cpointer_t priv __tb_debug_decl__)
tb_bool_t tb_aico_clos_after_ (tb_aico_ref_t aico, tb_size_t delay, tb_aico_func_t func, tb_cpointer_t priv __tb_debug_decl__)
tb_bool_t tb_aico_acpt_after_ (tb_aico_ref_t aico, tb_size_t delay, tb_aico_func_t func, tb_cpointer_t priv __tb_debug_decl__)
tb_bool_t tb_aico_conn_after_ (tb_aico_ref_t aico, tb_size_t delay, tb_ipv4_t const *addr, tb_uint16_t port, tb_aico_func_t func, tb_cpointer_t priv __tb_debug_decl__)
tb_bool_t tb_aico_recv_after_ (tb_aico_ref_t aico, tb_size_t delay, tb_byte_t *data, tb_size_t size, tb_aico_func_t func, tb_cpointer_t priv __tb_debug_decl__)
tb_bool_t tb_aico_send_after_ (tb_aico_ref_t aico, tb_size_t delay, tb_byte_t const *data, tb_size_t size, tb_aico_func_t func, tb_cpointer_t priv __tb_debug_decl__)
tb_bool_t tb_aico_urecv_after_ (tb_aico_ref_t aico, tb_size_t delay, tb_ipv4_t const *addr, tb_uint16_t port, tb_byte_t *data, tb_size_t size, tb_aico_func_t func, tb_cpointer_t priv __tb_debug_decl__)
tb_bool_t tb_aico_usend_after_ (tb_aico_ref_t aico, tb_size_t delay, tb_ipv4_t const *addr, tb_uint16_t port, tb_byte_t const *data, tb_size_t size, tb_aico_func_t func, tb_cpointer_t priv __tb_debug_decl__)
tb_bool_t tb_aico_recvv_after_ (tb_aico_ref_t aico, tb_size_t delay, tb_iovec_t const *list, tb_size_t size, tb_aico_func_t func, tb_cpointer_t priv __tb_debug_decl__)
tb_bool_t tb_aico_sendv_after_ (tb_aico_ref_t aico, tb_size_t delay, tb_iovec_t const *list, tb_size_t size, tb_aico_func_t func, tb_cpointer_t priv __tb_debug_decl__)
tb_bool_t tb_aico_urecvv_after_ (tb_aico_ref_t aico, tb_size_t delay, tb_ipv4_t const *addr, tb_uint16_t port, tb_iovec_t const *list, tb_size_t size, tb_aico_func_t func, tb_cpointer_t priv __tb_debug_decl__)
tb_bool_t tb_aico_usendv_after_ (tb_aico_ref_t aico, tb_size_t delay, tb_ipv4_t const *addr, tb_uint16_t port, tb_iovec_t const *list, tb_size_t size, tb_aico_func_t func, tb_cpointer_t priv __tb_debug_decl__)
tb_bool_t tb_aico_sendf_after_ (tb_aico_ref_t aico, tb_size_t delay, tb_file_ref_t file, tb_hize_t seek, tb_hize_t size, tb_aico_func_t func, tb_cpointer_t priv __tb_debug_decl__)
tb_bool_t tb_aico_read_after_ (tb_aico_ref_t aico, tb_size_t delay, tb_hize_t seek, tb_byte_t *data, tb_size_t size, tb_aico_func_t func, tb_cpointer_t priv __tb_debug_decl__)
tb_bool_t tb_aico_writ_after_ (tb_aico_ref_t aico, tb_size_t delay, tb_hize_t seek, tb_byte_t const *data, tb_size_t size, tb_aico_func_t func, tb_cpointer_t priv __tb_debug_decl__)
tb_bool_t tb_aico_readv_after_ (tb_aico_ref_t aico, tb_size_t delay, tb_hize_t seek, tb_iovec_t const *list, tb_size_t size, tb_aico_func_t func, tb_cpointer_t priv __tb_debug_decl__)
tb_bool_t tb_aico_writv_after_ (tb_aico_ref_t aico, tb_size_t delay, tb_hize_t seek, tb_iovec_t const *list, tb_size_t size, tb_aico_func_t func, tb_cpointer_t priv __tb_debug_decl__)
tb_bool_t tb_aico_fsync_after_ (tb_aico_ref_t aico, tb_size_t delay, tb_aico_func_t func, tb_cpointer_t priv __tb_debug_decl__)
tb_bool_t tb_aico_task_run_ (tb_aico_ref_t aico, tb_size_t delay, tb_aico_func_t func, tb_cpointer_t priv __tb_debug_decl__)
Detailed Description
The Treasure Box Library
TBox is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 2.1 of the License, or (at your option) any later version.
TBox is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with TBox; If not, see http://www.gnu.org/licenses/
Copyright (C) 2009 - 2015, ruki All rights reserved.
Author
ruki
Definition in file aico.h.
Enumeration Type Documentation
enum tb_aico_type_e
the aico type enum
Enumerator
TB_AICO_TYPE_NONE
null
TB_AICO_TYPE_SOCK
sock
TB_AICO_TYPE_FILE
file
TB_AICO_TYPE_TASK
task
Definition at line 88 of file aico.h.
Function Documentation
tb_bool_t tb_aico_acpt_ (tb_aico_ref_t aico, tb_aico_func_t func, tb_cpointer_t priv __tb_debug_decl__)
post the acpt
Parameters
aico the aico
func the callback func
priv the callback data
Returns
tb_true or tb_false
Definition at line 412 of file aico.c.
References tb_aice_t::aico, tb_aice_t::code, tb_aice_t::func, tb_aice_t::priv, tb_aice_t::state, TB_AICE_CODE_ACPT, and tb_aicp_post_().
tb_bool_t tb_aico_acpt_after_ (tb_aico_ref_t aico, tb_size_t delay, tb_aico_func_t func, tb_cpointer_t priv __tb_debug_decl__)
post the acpt after the delay time
Parameters
aico the aico
delay the delay time, ms
func the callback func
priv the callback data
Returns
tb_true or tb_false
Definition at line 742 of file aico.c.
References tb_aice_t::aico, tb_aice_t::code, tb_aice_t::func, tb_aice_t::priv, tb_aice_t::state, TB_AICE_CODE_ACPT, and tb_aicp_post_after_().
tb_aicp_ref_t tb_aico_aicp (tb_aico_ref_t aico)
the aico aicp
Parameters
aico the aico
Returns
the aico aicp
Definition at line 319 of file aico.c.
tb_bool_t tb_aico_clos_ (tb_aico_ref_t aico, tb_aico_func_t func, tb_cpointer_t priv __tb_debug_decl__)
post the clos
Parameters
aicp the aicp
func the func
priv the func private data
Returns
tb_true or tb_false
Definition at line 382 of file aico.c.
References tb_aice_t::aico, tb_aice_t::code, tb_aice_t::func, tb_aice_t::priv, tb_aice_t::state, TB_AICE_CODE_CLOS, tb_aico_clos_try(), and tb_aicp_post_().
tb_bool_t tb_aico_clos_after_ (tb_aico_ref_t aico, tb_size_t delay, tb_aico_func_t func, tb_cpointer_t priv __tb_debug_decl__)
post the clos after the delay time
Parameters
aico the aico
delay the delay time, ms
func the callback func
priv the callback data
Returns
tb_true or tb_false
Definition at line 725 of file aico.c.
References tb_aice_t::aico, tb_aice_t::code, tb_aice_t::func, tb_aice_t::priv, tb_aice_t::state, TB_AICE_CODE_CLOS, and tb_aicp_post_after_().
tb_bool_t tb_aico_clos_try (tb_aico_ref_t aico)
try to close it
Parameters
aico the aico
Returns
tb_true or tb_false
Definition at line 373 of file aico.c.
References tb_aico_impl_t::state.
Referenced by tb_aico_clos_().
tb_bool_t tb_aico_conn_ (tb_aico_ref_t aico, tb_ipv4_t const * addr, tb_uint16_t port, tb_aico_func_t func, tb_cpointer_t priv __tb_debug_decl__)
post the conn
Parameters
aico the aico
addr the addr
port the port
func the callback func
priv the callback data
Returns
tb_true or tb_false
Definition at line 429 of file aico.c.
References tb_aice_conn_t::addr, tb_aice_t::aico, tb_aice_t::code, tb_aice_t::func, tb_aice_conn_t::port, tb_aice_t::priv, tb_aice_t::state, TB_AICE_CODE_CONN, tb_aicp_post_(), and tb_aice_t::u.
tb_bool_t tb_aico_conn_after_ (tb_aico_ref_t aico, tb_size_t delay, tb_ipv4_t const * addr, tb_uint16_t port, tb_aico_func_t func, tb_cpointer_t priv __tb_debug_decl__)
post the conn after the delay time
Parameters
aico the aico
delay the delay time, ms
addr the addr
port the port
func the callback func
priv the callback data
Returns
tb_true or tb_false
Definition at line 759 of file aico.c.
References tb_aice_conn_t::addr, tb_aice_t::aico, tb_aice_t::code, tb_aice_t::func, tb_aice_conn_t::port, tb_aice_t::priv, tb_aice_t::state, TB_AICE_CODE_CONN, tb_aicp_post_after_(), and tb_aice_t::u.
tb_void_t tb_aico_exit (tb_aico_ref_t aico)
exit the aico
Parameters
aico the aico
Definition at line 256 of file aico.c.
References tb_aico_impl_t::state, tb_aico_type(), and tb_state_cstr().
tb_file_ref_t tb_aico_file (tb_aico_ref_t aico)
get the file if the aico is file type
Parameters
aico the aico
Returns
the file
Definition at line 346 of file aico.c.
References TB_AICO_TYPE_FILE.
tb_bool_t tb_aico_fsync_ (tb_aico_ref_t aico, tb_aico_func_t func, tb_cpointer_t priv __tb_debug_decl__)
post the fsync for file
Parameters
aico the aico
func the callback func
priv the callback data
Returns
tb_true or tb_false
Definition at line 708 of file aico.c.
References tb_aice_t::aico, tb_aice_t::code, tb_aice_t::func, tb_aice_t::priv, tb_aice_t::state, TB_AICE_CODE_FSYNC, and tb_aicp_post_().
tb_bool_t tb_aico_fsync_after_ (tb_aico_ref_t aico, tb_size_t delay, tb_aico_func_t func, tb_cpointer_t priv __tb_debug_decl__)
post the fsync for file after the delay time
Parameters
aico the aico
delay the delay time, ms
func the callback func
priv the callback data
Returns
tb_true or tb_false
Definition at line 1038 of file aico.c.
References tb_aice_t::aico, tb_aice_t::code, tb_aice_t::func, tb_aice_t::priv, tb_aice_t::state, TB_AICE_CODE_FSYNC, and tb_aicp_post_after_().
tb_aico_ref_t tb_aico_init (tb_aicp_ref_t aicp)
init the aico
Parameters
aicp the aicp
Returns
the aico
Definition at line 42 of file aico.c.
References tb_aico_impl_t::state, and TB_AICO_TYPE_NONE.
tb_void_t tb_aico_kill (tb_aico_ref_t aico)
kill the aico
Parameters
aico the aico
Definition at line 290 of file aico.c.
References tb_aico_impl_t::state, tb_aico_type(), and tb_state_cstr().
Referenced by tb_aicp_ssl_kill().
tb_bool_t tb_aico_open_file (tb_aico_ref_t aico, tb_file_ref_t file)
open the file aico
Parameters
aicp the aicp
file the file
Returns
tb_true or tb_false
Definition at line 149 of file aico.c.
References tb_aico_impl_t::state, and TB_AICO_TYPE_FILE.
tb_bool_t tb_aico_open_file_from_path (tb_aico_ref_t aico, tb_char_t const * path, tb_size_t mode)
open the file aico from path
Parameters
aicp the aicp
path the file path
mode the file mode
Returns
tb_true or tb_false
Definition at line 180 of file aico.c.
References tb_aico_impl_t::state, TB_AICO_TYPE_FILE, tb_file_exit(), tb_file_init(), and TB_FILE_MODE_ASIO.
tb_bool_t tb_aico_open_sock (tb_aico_ref_t aico, tb_socket_ref_t sock)
open the sock aico
Parameters
aicp the aicp
sock the socket
Returns
tb_true or tb_false
Definition at line 74 of file aico.c.
References tb_aico_impl_t::state, and TB_AICO_TYPE_SOCK.
tb_bool_t tb_aico_open_sock_from_type (tb_aico_ref_t aico, tb_size_t type)
open the sock aico from the socket type
Parameters
aicp the aicp
type the socket type
Returns
tb_true or tb_false
Definition at line 105 of file aico.c.
References tb_aico_impl_t::state, TB_AICO_TYPE_SOCK, tb_socket_exit(), and tb_socket_init().
tb_bool_t tb_aico_open_task (tb_aico_ref_t aico, tb_bool_t ltimer)
open the task aico
Parameters
aicp the aicp
ltimer is the lower precision timer?
Returns
tb_true or tb_false
Definition at line 224 of file aico.c.
References tb_aico_impl_t::state, and TB_AICO_TYPE_TASK.
tb_bool_t tb_aico_read_ (tb_aico_ref_t aico, tb_hize_t seek, tb_byte_t * data, tb_size_t size, tb_aico_func_t func, tb_cpointer_t priv __tb_debug_decl__)
post the read for file
Parameters
aico the aico
seek the seek
data the data
size the size
func the callback func
priv the callback data
Returns
tb_true or tb_false
Definition at line 628 of file aico.c.
References tb_aice_t::aico, tb_aice_t::code, tb_aice_read_t::data, tb_aice_t::func, tb_aice_t::priv, tb_aice_read_t::seek, tb_aice_read_t::size, tb_aice_t::state, TB_AICE_CODE_READ, tb_aicp_post_(), and tb_aice_t::u.
tb_bool_t tb_aico_read_after_ (tb_aico_ref_t aico, tb_size_t delay, tb_hize_t seek, tb_byte_t * data, tb_size_t size, tb_aico_func_t func, tb_cpointer_t priv __tb_debug_decl__)
post the read for file after the delay time
Parameters
aico the aico
delay the delay time, ms
seek the seek
data the data
size the size
func the callback func
priv the callback data
Returns
tb_true or tb_false
Definition at line 958 of file aico.c.
References tb_aice_t::aico, tb_aice_t::code, tb_aice_read_t::data, tb_aice_t::func, tb_aice_t::priv, tb_aice_read_t::seek, tb_aice_read_t::size, tb_aice_t::state, TB_AICE_CODE_READ, tb_aicp_post_after_(), and tb_aice_t::u.
tb_bool_t tb_aico_readv_ (tb_aico_ref_t aico, tb_hize_t seek, tb_iovec_t const * list, tb_size_t size, tb_aico_func_t func, tb_cpointer_t priv __tb_debug_decl__)
post the readv for file
Parameters
aico the aico
seek the seek
list the list
size the size
func the callback func
priv the callback data
Returns
tb_true or tb_false
Definition at line 668 of file aico.c.
References tb_aice_t::aico, tb_aice_t::code, tb_aice_t::func, tb_aice_readv_t::list, tb_aice_t::priv, tb_aice_readv_t::seek, tb_aice_readv_t::size, tb_aice_t::state, TB_AICE_CODE_READV, tb_aicp_post_(), and tb_aice_t::u.
tb_bool_t tb_aico_readv_after_ (tb_aico_ref_t aico, tb_size_t delay, tb_hize_t seek, tb_iovec_t const * list, tb_size_t size, tb_aico_func_t func, tb_cpointer_t priv __tb_debug_decl__)
post the readv for file after the delay time
Parameters
aico the aico
delay the delay time, ms
seek the seek
list the list
size the size
func the callback func
priv the callback data
Returns
tb_true or tb_false
Definition at line 998 of file aico.c.
References tb_aice_t::aico, tb_aice_t::code, tb_aice_t::func, tb_aice_readv_t::list, tb_aice_t::priv, tb_aice_readv_t::seek, tb_aice_readv_t::size, tb_aice_t::state, TB_AICE_CODE_READV, tb_aicp_post_after_(), and tb_aice_t::u.
tb_bool_t tb_aico_recv_ (tb_aico_ref_t aico, tb_byte_t * data, tb_size_t size, tb_aico_func_t func, tb_cpointer_t priv __tb_debug_decl__)
post the recv for sock
Parameters
aico the aico
data the data
size the size
func the callback func
priv the callback data
Returns
tb_true or tb_false
Definition at line 448 of file aico.c.
References tb_aice_t::aico, tb_aice_t::code, tb_aice_recv_t::data, tb_aice_t::func, tb_aice_t::priv, tb_aice_recv_t::size, tb_aice_t::state, TB_AICE_CODE_RECV, tb_aicp_post_(), and tb_aice_t::u.
tb_bool_t tb_aico_recv_after_ (tb_aico_ref_t aico, tb_size_t delay, tb_byte_t * data, tb_size_t size, tb_aico_func_t func, tb_cpointer_t priv __tb_debug_decl__)
post the recv for sock after the delay time
Parameters
aico the aico
delay the delay time, ms
data the data
size the size
func the callback func
priv the callback data
Returns
tb_true or tb_false
Definition at line 778 of file aico.c.
References tb_aice_t::aico, tb_aice_t::code, tb_aice_recv_t::data, tb_aice_t::func, tb_aice_t::priv, tb_aice_recv_t::size, tb_aice_t::state, TB_AICE_CODE_RECV, tb_aicp_post_after_(), and tb_aice_t::u.
tb_bool_t tb_aico_recvv_ (tb_aico_ref_t aico, tb_iovec_t const * list, tb_size_t size, tb_aico_func_t func, tb_cpointer_t priv __tb_debug_decl__)
post the recvv for sock
Parameters
aico the aico
list the list
size the size
func the callback func
priv the callback data
Returns
tb_true or tb_false
Definition at line 528 of file aico.c.
References tb_aice_t::aico, tb_aice_t::code, tb_aice_t::func, tb_aice_recvv_t::list, tb_aice_t::priv, tb_aice_recvv_t::size, tb_aice_t::state, TB_AICE_CODE_RECVV, tb_aicp_post_(), and tb_aice_t::u.
tb_bool_t tb_aico_recvv_after_ (tb_aico_ref_t aico, tb_size_t delay, tb_iovec_t const * list, tb_size_t size, tb_aico_func_t func, tb_cpointer_t priv __tb_debug_decl__)
post the recvv for sock after the delay time
Parameters
aico the aico
delay the delay time, ms
list the list
size the size
func the callback func
priv the callback data
Returns
tb_true or tb_false
Definition at line 858 of file aico.c.
References tb_aice_t::aico, tb_aice_t::code, tb_aice_t::func, tb_aice_recvv_t::list, tb_aice_t::priv, tb_aice_recvv_t::size, tb_aice_t::state, TB_AICE_CODE_RECVV, tb_aicp_post_after_(), and tb_aice_t::u.
tb_bool_t tb_aico_send_ (tb_aico_ref_t aico, tb_byte_t const * data, tb_size_t size, tb_aico_func_t func, tb_cpointer_t priv __tb_debug_decl__)
post the send for sock
Parameters
aico the aico
data the data
size the size, send the left file data if size == 0
func the callback func
priv the callback data
Returns
tb_true or tb_false
Definition at line 467 of file aico.c.
References tb_aice_t::aico, tb_aice_t::code, tb_aice_send_t::data, tb_aice_t::func, tb_aice_t::priv, tb_aice_send_t::size, tb_aice_t::state, TB_AICE_CODE_SEND, tb_aicp_post_(), and tb_aice_t::u.
tb_bool_t tb_aico_send_after_ (tb_aico_ref_t aico, tb_size_t delay, tb_byte_t const * data, tb_size_t size, tb_aico_func_t func, tb_cpointer_t priv __tb_debug_decl__)
post the send for sock after the delay time
Parameters
aico the aico
delay the delay time, ms
data the data
size the size, send the left file data if size == 0
func the callback func
priv the callback data
Returns
tb_true or tb_false
Definition at line 797 of file aico.c.
References tb_aice_t::aico, tb_aice_t::code, tb_aice_send_t::data, tb_aice_t::func, tb_aice_t::priv, tb_aice_send_t::size, tb_aice_t::state, TB_AICE_CODE_SEND, tb_aicp_post_after_(), and tb_aice_t::u.
tb_bool_t tb_aico_sendf_ (tb_aico_ref_t aico, tb_file_ref_t file, tb_hize_t seek, tb_hize_t size, tb_aico_func_t func, tb_cpointer_t priv __tb_debug_decl__)
post the sendfile for sock
Parameters
aico the aico
file the file handle
seek the seek
size the size, send the left data if size == 0
func the callback func
priv the callback data
Returns
tb_true or tb_false
Definition at line 608 of file aico.c.
References tb_aice_t::aico, tb_aice_t::code, tb_aice_sendf_t::file, tb_aice_t::func, tb_aice_t::priv, tb_aice_sendf_t::seek, tb_aice_sendf_t::size, tb_aice_t::state, TB_AICE_CODE_SENDF, tb_aicp_post_(), and tb_aice_t::u.
tb_bool_t tb_aico_sendf_after_ (tb_aico_ref_t aico, tb_size_t delay, tb_file_ref_t file, tb_hize_t seek, tb_hize_t size, tb_aico_func_t func, tb_cpointer_t priv __tb_debug_decl__)
post the sendfile for sock after the delay time
Parameters
aico the aico
delay the delay time, ms
file the file handle
seek the seek
size the size, send the left data if size == 0
func the callback func
priv the callback data
Returns
tb_true or tb_false
Definition at line 938 of file aico.c.
References tb_aice_t::aico, tb_aice_t::code, tb_aice_sendf_t::file, tb_aice_t::func, tb_aice_t::priv, tb_aice_sendf_t::seek, tb_aice_sendf_t::size, tb_aice_t::state, TB_AICE_CODE_SENDF, tb_aicp_post_after_(), and tb_aice_t::u.
tb_bool_t tb_aico_sendv_ (tb_aico_ref_t aico, tb_iovec_t const * list, tb_size_t size, tb_aico_func_t func, tb_cpointer_t priv __tb_debug_decl__)
post the sendv for sock
Parameters
aico the aico
list the list
size the size
func the callback func
priv the callback data
Returns
tb_true or tb_false
Definition at line 547 of file aico.c.
References tb_aice_t::aico, tb_aice_t::code, tb_aice_t::func, tb_aice_sendv_t::list, tb_aice_t::priv, tb_aice_sendv_t::size, tb_aice_t::state, TB_AICE_CODE_SENDV, tb_aicp_post_(), and tb_aice_t::u.
tb_bool_t tb_aico_sendv_after_ (tb_aico_ref_t aico, tb_size_t delay, tb_iovec_t const * list, tb_size_t size, tb_aico_func_t func, tb_cpointer_t priv __tb_debug_decl__)
post the sendv for sock after the delay time
Parameters
aico the aico
delay the delay time, ms
list the list
size the size
func the callback func
priv the callback data
Returns
tb_true or tb_false
Definition at line 877 of file aico.c.
References tb_aice_t::aico, tb_aice_t::code, tb_aice_t::func, tb_aice_sendv_t::list, tb_aice_t::priv, tb_aice_sendv_t::size, tb_aice_t::state, TB_AICE_CODE_SENDV, tb_aicp_post_after_(), and tb_aice_t::u.
tb_socket_ref_t tb_aico_sock (tb_aico_ref_t aico)
get the socket if the aico is socket type
Parameters
aico the aico
Returns
the socket
Definition at line 337 of file aico.c.
References TB_AICO_TYPE_SOCK.
tb_bool_t tb_aico_task_run_ (tb_aico_ref_t aico, tb_size_t delay, tb_aico_func_t func, tb_cpointer_t priv __tb_debug_decl__)
run aico task after timeout and will be auto-remove it after be expired
only once, need continue to call it again if want to repeat task
Parameters
aico the aico
delay the delay time, ms
func the callback func
priv the callback data
Returns
tb_true or tb_false
Definition at line 1056 of file aico.c.
References tb_aice_t::aico, tb_aice_t::code, tb_aice_runtask_t::delay, tb_aice_t::func, tb_aice_t::priv, tb_aice_t::state, TB_AICE_CODE_RUNTASK, tb_aicp_post_(), tb_cache_time_mclock(), tb_aice_t::u, and tb_aice_runtask_t::when.
Referenced by tb_aicp_post_after_().
tb_long_t tb_aico_timeout (tb_aico_ref_t aico, tb_size_t type)
the aico timeout
Parameters
aico the aico
type the timeout type
Returns
the timeout
Definition at line 355 of file aico.c.
tb_void_t tb_aico_timeout_set (tb_aico_ref_t aico, tb_size_t type, tb_long_t timeout)
set the aico timeout
Parameters
aico the aico
type the timeout type
timeout the timeout
Definition at line 364 of file aico.c.
Referenced by tb_aicp_ssl_open().
tb_size_t tb_aico_type (tb_aico_ref_t aico)
the aico type
Parameters
aico the aico
Returns
the aico type
Definition at line 328 of file aico.c.
References TB_AICO_TYPE_NONE.
Referenced by tb_aico_exit(), tb_aico_kill(), and tb_aicp_post_().
tb_bool_t tb_aico_urecv_ (tb_aico_ref_t aico, tb_ipv4_t const * addr, tb_uint16_t port, tb_byte_t * data, tb_size_t size, tb_aico_func_t func, tb_cpointer_t priv __tb_debug_decl__)
post the urecv for sock
Parameters
aico the aico
addr the addr
port the port
data the data
size the size
func the callback func
priv the callback data
Returns
tb_true or tb_false
Definition at line 486 of file aico.c.
References tb_aice_urecv_t::addr, tb_aice_t::aico, tb_aice_t::code, tb_aice_urecv_t::data, tb_aice_t::func, tb_aice_urecv_t::port, tb_aice_t::priv, tb_aice_urecv_t::size, tb_aice_t::state, TB_AICE_CODE_URECV, tb_aicp_post_(), and tb_aice_t::u.
tb_bool_t tb_aico_urecv_after_ (tb_aico_ref_t aico, tb_size_t delay, tb_ipv4_t const * addr, tb_uint16_t port, tb_byte_t * data, tb_size_t size, tb_aico_func_t func, tb_cpointer_t priv __tb_debug_decl__)
post the urecv for sock after the delay time
Parameters
aico the aico
delay the delay time, ms
addr the addr
port the port
data the data
size the size
func the callback func
priv the callback data
Returns
tb_true or tb_false
Definition at line 816 of file aico.c.
References tb_aice_urecv_t::addr, tb_aice_t::aico, tb_aice_t::code, tb_aice_urecv_t::data, tb_aice_t::func, tb_aice_urecv_t::port, tb_aice_t::priv, tb_aice_urecv_t::size, tb_aice_t::state, TB_AICE_CODE_URECV, tb_aicp_post_after_(), and tb_aice_t::u.
tb_bool_t tb_aico_urecvv_ (tb_aico_ref_t aico, tb_ipv4_t const * addr, tb_uint16_t port, tb_iovec_t const * list, tb_size_t size, tb_aico_func_t func, tb_cpointer_t priv __tb_debug_decl__)
post the urecvv for sock
Parameters
aico the aico
addr the addr
port the port
list the list
size the size
func the callback func
priv the callback data
Returns
tb_true or tb_false
Definition at line 566 of file aico.c.
References tb_aice_urecvv_t::addr, tb_aice_t::aico, tb_aice_t::code, tb_aice_t::func, tb_aice_urecvv_t::list, tb_aice_urecvv_t::port, tb_aice_t::priv, tb_aice_urecvv_t::size, tb_aice_t::state, TB_AICE_CODE_URECVV, tb_aicp_post_(), and tb_aice_t::u.
tb_bool_t tb_aico_urecvv_after_ (tb_aico_ref_t aico, tb_size_t delay, tb_ipv4_t const * addr, tb_uint16_t port, tb_iovec_t const * list, tb_size_t size, tb_aico_func_t func, tb_cpointer_t priv __tb_debug_decl__)
post the urecvv for sock after the delay time
Parameters
aico the aico
delay the delay time, ms
addr the addr
port the port
list the list
size the size
func the callback func
priv the callback data
Returns
tb_true or tb_false
Definition at line 896 of file aico.c.
References tb_aice_urecvv_t::addr, tb_aice_t::aico, tb_aice_t::code, tb_aice_t::func, tb_aice_urecvv_t::list, tb_aice_urecvv_t::port, tb_aice_t::priv, tb_aice_urecvv_t::size, tb_aice_t::state, TB_AICE_CODE_URECVV, tb_aicp_post_after_(), and tb_aice_t::u.
tb_bool_t tb_aico_usend_ (tb_aico_ref_t aico, tb_ipv4_t const * addr, tb_uint16_t port, tb_byte_t const * data, tb_size_t size, tb_aico_func_t func, tb_cpointer_t priv __tb_debug_decl__)
post the usend for sock
Parameters
aico the aico
addr the addr
port the port
data the data
size the size, send the left file data if size == 0
func the callback func
priv the callback data
Returns
tb_true or tb_false
Definition at line 507 of file aico.c.
References tb_aice_usend_t::addr, tb_aice_t::aico, tb_aice_t::code, tb_aice_usend_t::data, tb_aice_t::func, tb_aice_usend_t::port, tb_aice_t::priv, tb_aice_usend_t::size, tb_aice_t::state, TB_AICE_CODE_USEND, tb_aicp_post_(), and tb_aice_t::u.
tb_bool_t tb_aico_usend_after_ (tb_aico_ref_t aico, tb_size_t delay, tb_ipv4_t const * addr, tb_uint16_t port, tb_byte_t const * data, tb_size_t size, tb_aico_func_t func, tb_cpointer_t priv __tb_debug_decl__)
post the usend for sock after the delay time
Parameters
aico the aico
delay the delay time, ms
addr the addr
port the port
data the data
size the size, send the left file data if size == 0
func the callback func
priv the callback data
Returns
tb_true or tb_false
Definition at line 837 of file aico.c.
References tb_aice_usend_t::addr, tb_aice_t::aico, tb_aice_t::code, tb_aice_usend_t::data, tb_aice_t::func, tb_aice_usend_t::port, tb_aice_t::priv, tb_aice_usend_t::size, tb_aice_t::state, TB_AICE_CODE_USEND, tb_aicp_post_after_(), and tb_aice_t::u.
tb_bool_t tb_aico_usendv_ (tb_aico_ref_t aico, tb_ipv4_t const * addr, tb_uint16_t port, tb_iovec_t const * list, tb_size_t size, tb_aico_func_t func, tb_cpointer_t priv __tb_debug_decl__)
post the usendv for sock
Parameters
aico the aico
addr the addr
port the port
list the list
size the size
func the callback func
priv the callback data
Returns
tb_true or tb_false
Definition at line 587 of file aico.c.
References tb_aice_usendv_t::addr, tb_aice_t::aico, tb_aice_t::code, tb_aice_t::func, tb_aice_usendv_t::list, tb_aice_usendv_t::port, tb_aice_t::priv, tb_aice_usendv_t::size, tb_aice_t::state, TB_AICE_CODE_USENDV, tb_aicp_post_(), and tb_aice_t::u.
tb_bool_t tb_aico_usendv_after_ (tb_aico_ref_t aico, tb_size_t delay, tb_ipv4_t const * addr, tb_uint16_t port, tb_iovec_t const * list, tb_size_t size, tb_aico_func_t func, tb_cpointer_t priv __tb_debug_decl__)
post the usendv for sock after the delay time
Parameters
aico the aico
delay the delay time, ms
addr the addr
port the port
list the list
size the size
func the callback func
priv the callback data
Returns
tb_true or tb_false
Definition at line 917 of file aico.c.
References tb_aice_usendv_t::addr, tb_aice_t::aico, tb_aice_t::code, tb_aice_t::func, tb_aice_usendv_t::list, tb_aice_usendv_t::port, tb_aice_t::priv, tb_aice_usendv_t::size, tb_aice_t::state, TB_AICE_CODE_USENDV, tb_aicp_post_after_(), and tb_aice_t::u.
tb_bool_t tb_aico_writ_ (tb_aico_ref_t aico, tb_hize_t seek, tb_byte_t const * data, tb_size_t size, tb_aico_func_t func, tb_cpointer_t priv __tb_debug_decl__)
post the writ for file
Parameters
aico the aico
seek the seek
data the data
size the size
func the callback func
priv the callback data
Returns
tb_true or tb_false
Definition at line 648 of file aico.c.
References tb_aice_t::aico, tb_aice_t::code, tb_aice_writ_t::data, tb_aice_t::func, tb_aice_t::priv, tb_aice_writ_t::seek, tb_aice_writ_t::size, tb_aice_t::state, TB_AICE_CODE_WRIT, tb_aicp_post_(), and tb_aice_t::u.
tb_bool_t tb_aico_writ_after_ (tb_aico_ref_t aico, tb_size_t delay, tb_hize_t seek, tb_byte_t const * data, tb_size_t size, tb_aico_func_t func, tb_cpointer_t priv __tb_debug_decl__)
post the writ for file after the delay time
Parameters
aico the aico
delay the delay time, ms
seek the seek
data the data
size the size
func the callback func
priv the callback data
Returns
tb_true or tb_false
Definition at line 978 of file aico.c.
References tb_aice_t::aico, tb_aice_t::code, tb_aice_writ_t::data, tb_aice_t::func, tb_aice_t::priv, tb_aice_writ_t::seek, tb_aice_writ_t::size, tb_aice_t::state, TB_AICE_CODE_WRIT, tb_aicp_post_after_(), and tb_aice_t::u.
tb_bool_t tb_aico_writv_ (tb_aico_ref_t aico, tb_hize_t seek, tb_iovec_t const * list, tb_size_t size, tb_aico_func_t func, tb_cpointer_t priv __tb_debug_decl__)
post the writv for file
Parameters
aico the aico
seek the seek
list the list
size the size
func the callback func
priv the callback data
Returns
tb_true or tb_false
Definition at line 688 of file aico.c.
References tb_aice_t::aico, tb_aice_t::code, tb_aice_t::func, tb_aice_writv_t::list, tb_aice_t::priv, tb_aice_writv_t::seek, tb_aice_writv_t::size, tb_aice_t::state, TB_AICE_CODE_WRITV, tb_aicp_post_(), and tb_aice_t::u.
tb_bool_t tb_aico_writv_after_ (tb_aico_ref_t aico, tb_size_t delay, tb_hize_t seek, tb_iovec_t const * list, tb_size_t size, tb_aico_func_t func, tb_cpointer_t priv __tb_debug_decl__)
post the writv for file after the delay time
Parameters
aico the aico
delay the delay time, ms
seek the seek
list the list
size the size
func the callback func
priv the callback data
Returns
tb_true or tb_false
Definition at line 1018 of file aico.c.
References tb_aice_t::aico, tb_aice_t::code, tb_aice_t::func, tb_aice_writv_t::list, tb_aice_t::priv, tb_aice_writv_t::seek, tb_aice_writv_t::size, tb_aice_t::state, TB_AICE_CODE_WRITV, tb_aicp_post_after_(), and tb_aice_t::u.