TBOX: src/tbox/network/dns/looker.c File Reference
looker.c File Reference
Network
#include "looker.h"
#include "cache.h"
#include "server.h"
#include "../../asio/asio.h"
#include "../../string/string.h"
#include "../../memory/memory.h"
#include "../../platform/platform.h"
Macros
#define TB_TRACE_MODULE_NAME "dns_looker"
#define TB_TRACE_MODULE_DEBUG (0)
#define TB_DNS_LOOKER_TIMEOUT (5000)
Enumerations
enum tb_dns_looker_step_e { TB_DNS_LOOKER_STEP_NONE = 0, TB_DNS_LOOKER_STEP_REQT = 1, TB_DNS_LOOKER_STEP_RESP = 2, TB_DNS_LOOKER_STEP_NEVT = 4 }
Functions
tb_handle_t tb_dns_looker_init (tb_char_t const *name)
tb_long_t tb_dns_looker_spak (tb_handle_t handle, tb_ipv4_t *addr)
tb_long_t tb_dns_looker_wait (tb_handle_t handle, tb_long_t timeout)
tb_void_t tb_dns_looker_exit (tb_handle_t handle)
tb_bool_t tb_dns_looker_done (tb_char_t const *name, tb_ipv4_t *addr)
Detailed Description
The Treasure Box Library
TBox is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 2.1 of the License, or (at your option) any later version.
TBox is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with TBox; If not, see http://www.gnu.org/licenses/
Copyright (C) 2009 - 2015, ruki All rights reserved.
Author
ruki
Definition in file looker.c.
Function Documentation
tb_bool_t tb_dns_looker_done (tb_char_t const * name, tb_ipv4_t * addr)
look ipv4 from the host name, block
try to look it from cache first
Parameters
name the host name
addr the ipv4 addr
Returns
tb_true or tb_false
Definition at line 651 of file looker.c.
References tb_dns_looker_exit(), tb_dns_looker_init(), tb_dns_looker_spak(), and tb_dns_looker_wait().
tb_void_t tb_dns_looker_exit (tb_handle_t handle)
exit the looker
Parameters
handle the looker handle
Definition at line 637 of file looker.c.
References tb_socket_exit().
Referenced by tb_dns_looker_done(), and tb_dns_looker_init().
tb_handle_t tb_dns_looker_init (tb_char_t const * name)
init for looking ipv4 from the host name, non-block
Parameters
name the host name
Returns
the looker handle
Definition at line 510 of file looker.c.
References tb_dns_looker_exit(), tb_dns_server_get(), tb_ipv4_set(), tb_socket_init(), tb_static_buffer_init(), tb_static_string_cstrcpy(), and tb_static_string_init().
Referenced by tb_dns_looker_done().
tb_long_t tb_dns_looker_spak (tb_handle_t handle, tb_ipv4_t * addr)
spak the looker
Parameters
handle the looker handle
addr the ipv4 addr
Returns
1: ok, 0: continue: -1: failed
Definition at line 564 of file looker.c.
References tb_static_buffer_clear().
Referenced by tb_dns_looker_done().
tb_long_t tb_dns_looker_wait (tb_handle_t handle, tb_long_t timeout)
wait the looker
Parameters
handle the looker handle
timeout the timeout
Returns
1: ok, 0: continue: -1: failed
Definition at line 609 of file looker.c.
References tb_aioo_wait().
Referenced by tb_dns_looker_done().