TBOX: src/tbox/libc/stdio/printf.c File Reference
printf.c File Reference
Libc
#include "stdio.h"
#include "../../platform/platform.h"
Functions
tb_long_t tb_printf (tb_char_t const *format,...)
Detailed Description
The Treasure Arch Library
TArch is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
TArch is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with TArch; If not, see http://www.gnu.org/licenses/
Copyright (C) 2009 - 2015, ruki All rights reserved.
Author
ruki
Definition in file printf.c.
Function Documentation
tb_long_t tb_printf (tb_char_t const * format, ...)
printf
Parameters
format the format string
Returns
the real size
Definition at line 35 of file printf.c.
References tb_print().
Referenced by tb_bloom_filter_init(), and tb_object_dump().