TBOX: src/tbox/memory/fixed_pool.h File Reference
fixed_pool.h File Reference
Memory
#include "large_pool.h"
Data Structures
struct tb_fixed_pool_ref_t
Macros
#define tb_fixed_pool_malloc(pool) tb_fixed_pool_malloc_(pool __tb_debug_vals__)
#define tb_fixed_pool_malloc0(pool) tb_fixed_pool_malloc0_(pool __tb_debug_vals__)
#define tb_fixed_pool_free(pool, item) tb_fixed_pool_free_(pool, (tb_pointer_t)(item) __tb_debug_vals__)
Typedefs
typedef tb_bool_t(* tb_fixed_pool_item_init_func_t)(tb_pointer_t data, tb_cpointer_t priv)
the item init func type
typedef tb_void_t(* tb_fixed_pool_item_exit_func_t)(tb_pointer_t data, tb_cpointer_t priv)
the item exit func type
typedef tb_bool_t(* tb_fixed_pool_item_walk_func_t)(tb_pointer_t data, tb_cpointer_t priv)
the item walk func type
Functions
tb_fixed_pool_ref_t tb_fixed_pool_init (tb_large_pool_ref_t large_pool, tb_size_t slot_size, tb_size_t item_size, tb_fixed_pool_item_init_func_t item_init, tb_fixed_pool_item_exit_func_t item_exit, tb_cpointer_t priv)
tb_void_t tb_fixed_pool_exit (tb_fixed_pool_ref_t pool)
tb_size_t tb_fixed_pool_size (tb_fixed_pool_ref_t pool)
tb_size_t tb_fixed_pool_item_size (tb_fixed_pool_ref_t pool)
tb_void_t tb_fixed_pool_clear (tb_fixed_pool_ref_t pool)
tb_pointer_t tb_fixed_pool_malloc_ (tb_fixed_pool_ref_t pool __tb_debug_decl__)
tb_pointer_t tb_fixed_pool_malloc0_ (tb_fixed_pool_ref_t pool __tb_debug_decl__)
tb_bool_t tb_fixed_pool_free_ (tb_fixed_pool_ref_t pool, tb_pointer_t data __tb_debug_decl__)
tb_void_t tb_fixed_pool_walk (tb_fixed_pool_ref_t pool, tb_fixed_pool_item_walk_func_t func, tb_cpointer_t priv)
Detailed Description
The Treasure Box Library
TBox is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 2.1 of the License, or (at your option) any later version.
TBox is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with TBox; If not, see http://www.gnu.org/licenses/
Copyright (C) 2009 - 2015, ruki All rights reserved.
Author
ruki
Definition in file fixed_pool.h.
Function Documentation
tb_void_t tb_fixed_pool_clear (tb_fixed_pool_ref_t pool)
clear pool
Parameters
pool the pool
Definition at line 431 of file fixed_pool.c.
References tb_fixed_pool_walk(), tb_iterator_head(), tb_iterator_item(), tb_iterator_next(), tb_iterator_tail(), and tb_list_entry_itor().
Referenced by tb_aiop_cler(), tb_fixed_pool_exit(), tb_list_clear(), tb_ltimer_clear(), tb_single_list_clear(), tb_small_pool_clear(), and tb_timer_clear().
tb_void_t tb_fixed_pool_exit (tb_fixed_pool_ref_t pool)
exit pool
Parameters
pool the pool
Definition at line 395 of file fixed_pool.c.
References tb_fixed_pool_clear(), and tb_large_pool().
Referenced by tb_aicp_exit(), tb_aiop_exit(), tb_list_exit(), tb_ltimer_exit(), tb_single_list_exit(), tb_small_pool_exit(), tb_thread_pool_exit(), tb_timer_exit(), and tb_transfer_pool_exit().
tb_bool_t tb_fixed_pool_free_ (tb_fixed_pool_ref_t pool, tb_pointer_t data __tb_debug_decl__)
free data
Parameters
pool the pool
data the data
Returns
tb_true or tb_false
Definition at line 590 of file fixed_pool.c.
References tb_static_fixed_pool_free(), tb_static_fixed_pool_full(), and tb_static_fixed_pool_null().
Referenced by tb_small_pool_free_(), and tb_small_pool_ralloc_().
tb_fixed_pool_ref_t tb_fixed_pool_init (tb_large_pool_ref_t large_pool, tb_size_t slot_size, tb_size_t item_size, tb_fixed_pool_item_init_func_t item_init, tb_fixed_pool_item_exit_func_t item_exit, tb_cpointer_t priv)
init fixed pool
Parameters
large_pool the large pool, using the default large pool if be null
slot_size the item count per-slot, using the default size if be zero
item_size the item size
item_init the item init func
item_exit the item exit func
priv the private data
Returns
the pool
Definition at line 391 of file fixed_pool.c.
Referenced by tb_aicp_init(), tb_aiop_init(), tb_list_init(), tb_ltimer_init(), tb_single_list_init(), tb_thread_pool_init(), and tb_timer_init().
tb_size_t tb_fixed_pool_item_size (tb_fixed_pool_ref_t pool)
the item size
Parameters
pool the pool
Returns
the item size
Definition at line 422 of file fixed_pool.c.
Referenced by tb_small_pool_free_(), and tb_small_pool_ralloc_().
tb_pointer_t tb_fixed_pool_malloc0_ (tb_fixed_pool_ref_t pool __tb_debug_decl__)
malloc data and clear it
Parameters
pool the pool
Returns
the data
Definition at line 574 of file fixed_pool.c.
References tb_fixed_pool_malloc_().
Referenced by tb_small_pool_malloc0_(), and tb_small_pool_nalloc0_().
tb_pointer_t tb_fixed_pool_malloc_ (tb_fixed_pool_ref_t pool __tb_debug_decl__)
malloc data
Parameters
pool the pool
Returns
the data
Definition at line 502 of file fixed_pool.c.
References tb_list_entry, tb_static_fixed_pool_free(), tb_static_fixed_pool_full(), and tb_static_fixed_pool_malloc().
Referenced by tb_fixed_pool_malloc0_(), tb_small_pool_malloc_(), tb_small_pool_nalloc_(), and tb_small_pool_ralloc_().
tb_size_t tb_fixed_pool_size (tb_fixed_pool_ref_t pool)
the item count
Parameters
pool the pool
Returns
the item count
Definition at line 413 of file fixed_pool.c.
Referenced by tb_aicp_wait_all(), tb_list_size(), tb_ltimer_spak(), tb_single_list_size(), tb_thread_pool_task_size(), and tb_thread_pool_task_wait_all().
tb_void_t tb_fixed_pool_walk (tb_fixed_pool_ref_t pool, tb_fixed_pool_item_walk_func_t func, tb_cpointer_t priv)
walk item
tb_bool_t tb_fixed_pool_item_func(tb_pointer_t data, tb_cpointer_t priv)
{
    // ok or break
    return tb_true;
}
Parameters
pool the pool
func the walk func
priv the private data
Definition at line 660 of file fixed_pool.c.
References tb_for_all_if, tb_list_entry_itor(), tb_static_fixed_pool_full(), and tb_static_fixed_pool_walk().
Referenced by tb_aicp_exit(), tb_aicp_kill_all(), tb_fixed_pool_clear(), tb_thread_pool_kill(), tb_thread_pool_task_kill_all(), and tb_transfer_pool_exit().