TBOX: src/tbox/utils/sha.c File Reference
sha.c File Reference
Utils
#include "sha.h"
#include "bits.h"
#include "../libc/libc.h"
Macros
#define rol(v, b) (((v) << (b)) | ((v) >> (32 - (b))))
#define blk0(i) (block[i] = tb_bits_be_to_ne_u32(((tb_uint32_t const*)buffer)[i]))
#define blk(i) (block[i] = rol(block[i - 3] ^ block[i - 8] ^ block[i - 14] ^ block[i - 16], 1))
#define R0(v, w, x, y, z, i) z += ((w & (x ^ y)) ^ y) + blk0(i) + 0x5a827999 + rol(v, 5); w = rol(w, 30);
#define R1(v, w, x, y, z, i) z += ((w &(x ^ y)) ^ y) + blk(i) + 0x5a827999 + rol(v, 5); w = rol(w, 30);
#define R2(v, w, x, y, z, i) z += (w ^ x ^ y) + blk(i) + 0x6ed9eba1 + rol(v, 5); w = rol(w, 30);
#define R3(v, w, x, y, z, i) z += (((w | x) & y) | (w & x)) + blk(i) + 0x8f1bbcdc + rol(v, 5); w = rol(w, 30);
#define R4(v, w, x, y, z, i) z += (w ^ x ^ y) + blk(i) + 0xca62c1d6 + rol(v, 5); w = rol(w, 30);
#define Ch(x, y, z) (((x) & ((y) ^ (z))) ^ (z))
#define Maj(x, y, z) ((((x) | (y)) & (z)) | ((x) & (y)))
#define Sigma0_256(x) (rol((x), 30) ^ rol((x), 19) ^ rol((x), 10))
#define Sigma1_256(x) (rol((x), 26) ^ rol((x), 21) ^ rol((x), 7))
#define sigma0_256(x) (rol((x), 25) ^ rol((x), 14) ^ ((x) >> 3))
#define sigma1_256(x) (rol((x), 15) ^ rol((x), 13) ^ ((x) >> 10))
#define blk(i) (block[i] = block[i - 16] + sigma0_256(block[i - 15]) + sigma1_256(block[i - 2]) + block[i - 7])
#define ROUND256(a, b, c, d, e, f, g, h)
#define ROUND256_0_TO_15(a, b, c, d, e, f, g, h)
#define ROUND256_16_TO_63(a, b, c, d, e, f, g, h)
Functions
tb_void_t tb_sha_init (tb_sha_t *sha, tb_size_t mode)
tb_void_t tb_sha_exit (tb_sha_t *sha, tb_byte_t *data, tb_size_t size)
tb_void_t tb_sha_spak (tb_sha_t *sha, tb_byte_t const *data, tb_size_t size)
tb_size_t tb_sha_encode (tb_size_t mode, tb_byte_t const *ib, tb_size_t in, tb_byte_t *ob, tb_size_t on)
Detailed Description
The Treasure Box Library
TBox is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 2.1 of the License, or (at your option) any later version.
TBox is distributed ip the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with TBox; If not, see http://www.gnu.org/licenses/
Copyright (C) 2009 - 2015, ruki All rights reserved.
Author
ruki
Definition in file sha.c.
Macro Definition Documentation
#define ROUND256 (a, b, c, d, e, f, g, h)
Value:
T1 += (h) + Sigma1_256(e) + Ch((e), (f), (g)) + g_sha_k256[i]; \
    (d) += T1; \
    (h) = T1 + Sigma0_256(a) + Maj((a), (b), (c)); \
    i++
Definition at line 59 of file sha.c.
#define ROUND256_0_TO_15 (a, b, c, d, e, f, g, h)
Value:
T1 = blk0(i); \
    ROUND256(a,b,c,d,e,f,g,h)
Definition at line 65 of file sha.c.
#define ROUND256_16_TO_63 (a, b, c, d, e, f, g, h)
Value:
T1 = blk(i); \
    ROUND256(a,b,c,d,e,f,g,h)
Definition at line 69 of file sha.c.
Function Documentation
tb_size_t tb_sha_encode (tb_size_t mode, tb_byte_t const * ib, tb_size_t ip, tb_byte_t * ob, tb_size_t on)
encode sha
Parameters
ib the input data
in the input size
ob the output data
on the output size
Returns
the real size
Definition at line 354 of file sha.c.
References tb_sha_t::digest_len, tb_sha_exit(), tb_sha_init(), and tb_sha_spak().
tb_void_t tb_sha_exit (tb_sha_t * sha, tb_byte_t * data, tb_size_t size)
exit sha
Parameters
sha the sha
data the data
size the size
Definition at line 306 of file sha.c.
References tb_sha_t::count, tb_sha_t::digest_len, tb_sha_t::state, and tb_sha_spak().
Referenced by tb_sha_encode().
tb_void_t tb_sha_init (tb_sha_t * sha, tb_size_t mode)
init sha
Parameters
sha the sha
mode the mode
Definition at line 264 of file sha.c.
References tb_sha_t::count, tb_sha_t::digest_len, and tb_sha_t::state.
Referenced by tb_sha_encode().
tb_void_t tb_sha_spak (tb_sha_t * sha, tb_byte_t const * data, tb_size_t size)
spak sha
Parameters
sha the sha
data the data
size the size
Definition at line 323 of file sha.c.
References tb_sha_t::buffer, tb_sha_t::count, and tb_sha_t::state.
Referenced by tb_sha_encode(), and tb_sha_exit().