TBOX: src/tbox/container/iterator.c File Reference
iterator.c File Reference
Container
#include "iterator.h"
#include "../libc/libc.h"
Functions
tb_size_t tb_iterator_mode (tb_iterator_ref_t iterator)
tb_size_t tb_iterator_step (tb_iterator_ref_t iterator)
tb_size_t tb_iterator_size (tb_iterator_ref_t iterator)
tb_size_t tb_iterator_head (tb_iterator_ref_t iterator)
tb_size_t tb_iterator_last (tb_iterator_ref_t iterator)
tb_size_t tb_iterator_tail (tb_iterator_ref_t iterator)
tb_size_t tb_iterator_prev (tb_iterator_ref_t iterator, tb_size_t itor)
tb_size_t tb_iterator_next (tb_iterator_ref_t iterator, tb_size_t itor)
tb_pointer_t tb_iterator_item (tb_iterator_ref_t iterator, tb_size_t itor)
tb_void_t tb_iterator_remove (tb_iterator_ref_t iterator, tb_size_t itor)
tb_void_t tb_iterator_remove_range (tb_iterator_ref_t iterator, tb_size_t prev, tb_size_t next, tb_size_t size)
tb_void_t tb_iterator_copy (tb_iterator_ref_t iterator, tb_size_t itor, tb_cpointer_t item)
tb_long_t tb_iterator_comp (tb_iterator_ref_t iterator, tb_cpointer_t ltem, tb_cpointer_t rtem)
Detailed Description
The Treasure Box Library
TBox is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 2.1 of the License, or (at your option) any later version.
TBox is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with TBox; If not, see http://www.gnu.org/licenses/
Copyright (C) 2009 - 2015, ruki All rights reserved.
Author
ruki
Definition in file iterator.c.
Function Documentation
tb_long_t tb_iterator_comp (tb_iterator_ref_t iterator, tb_cpointer_t ltem, tb_cpointer_t rtem)
compare the iterator item
Parameters
iterator the iterator
itor the item
item the compared item
Returns
=: 0, >: 1, <: -1
Definition at line 130 of file iterator.c.
References tb_iterator_t::comp.
Referenced by tb_binary_find(), tb_binary_find_all(), tb_bubble_sort(), tb_count(), tb_count_all(), tb_find(), tb_find_all(), tb_insert_sort(), tb_quick_sort(), tb_remove(), tb_rfind(), and tb_rfind_all().
tb_void_t tb_iterator_copy (tb_iterator_ref_t iterator, tb_size_t itor, tb_cpointer_t item)
copy the iterator item
Parameters
iterator the iterator
itor the item itor
item the copied item
Definition at line 122 of file iterator.c.
References tb_iterator_t::copy.
Referenced by tb_bubble_sort(), tb_insert_sort(), tb_quick_sort(), tb_string_pool_del(), and tb_string_pool_put().
tb_size_t tb_iterator_head (tb_iterator_ref_t iterator)
the iterator head
Parameters
iterator the iterator
Returns
the iterator head
Definition at line 58 of file iterator.c.
References tb_iterator_t::head.
Referenced by tb_binary_find_all_if(), tb_bubble_sort_all(), tb_circle_queue_head(), tb_count_all_if(), tb_find_all_if(), tb_fixed_pool_clear(), tb_heap_sort_all(), tb_heap_top(), tb_insert_sort_all(), tb_list_head(), tb_list_insert_head(), tb_list_moveto_head(), tb_list_remove_head(), tb_list_replace_head(), tb_quick_sort_all(), tb_remove_if(), tb_rfind_all_if(), tb_rwalk_all(), tb_single_list_head(), tb_single_list_replace_head(), tb_sort_all(), tb_vector_head(), and tb_walk_all().
tb_pointer_t tb_iterator_item (tb_iterator_ref_t iterator, tb_size_t itor)
the iterator item
Parameters
iterator the iterator
itor the item itor
Returns
the iterator item
Definition at line 98 of file iterator.c.
References tb_iterator_t::item.
Referenced by tb_binary_find_if(), tb_bubble_sort(), tb_circle_queue_head(), tb_circle_queue_last(), tb_dns_server_get(), tb_find_if(), tb_fixed_pool_clear(), tb_heap_sort(), tb_heap_top(), tb_insert_sort(), tb_list_head(), tb_list_last(), tb_object_array_item(), tb_quick_sort(), tb_remove_if(), tb_rfind_if(), tb_single_list_head(), tb_single_list_last(), tb_string_pool_del(), tb_string_pool_put(), tb_vector_head(), and tb_vector_last().
tb_size_t tb_iterator_last (tb_iterator_ref_t iterator)
the iterator last
Parameters
iterator the iterator
Returns
the iterator last
Definition at line 66 of file iterator.c.
References tb_iterator_t::last.
Referenced by tb_circle_queue_last(), tb_list_last(), tb_list_remove_last(), tb_list_replace_last(), tb_single_list_last(), tb_single_list_replace_last(), and tb_vector_last().
tb_size_t tb_iterator_mode (tb_iterator_ref_t iterator)
the iterator mode
Parameters
iterator the iterator
Returns
the iterator mode
Definition at line 34 of file iterator.c.
References tb_iterator_t::mode.
Referenced by tb_binary_find_if(), tb_bubble_sort(), tb_count_if(), tb_find_if(), tb_heap_sort(), tb_insert_sort(), tb_quick_sort(), tb_remove_if(), tb_rfind_if(), tb_rwalk(), tb_sort(), and tb_walk().
tb_size_t tb_iterator_next (tb_iterator_ref_t iterator, tb_size_t itor)
the iterator next
Parameters
iterator the iterator
itor the item itor
Returns
the iterator next
Definition at line 90 of file iterator.c.
References tb_iterator_t::next.
Referenced by tb_bubble_sort(), tb_find_if(), tb_fixed_pool_clear(), tb_insert_sort(), tb_list_insert_next(), tb_list_moveto_next(), tb_remove_if(), tb_vector_insert_next(), and tb_vector_ninsert_next().
tb_size_t tb_iterator_prev (tb_iterator_ref_t iterator, tb_size_t itor)
the iterator prev
Parameters
iterator the iterator
itor the item itor
Returns
the iterator prev
Definition at line 82 of file iterator.c.
References tb_iterator_t::prev.
Referenced by tb_insert_sort(), and tb_rfind_if().
tb_void_t tb_iterator_remove (tb_iterator_ref_t iterator, tb_size_t itor)
remove the iterator item
Parameters
iterator the iterator
itor the item itor
Definition at line 106 of file iterator.c.
References tb_iterator_t::remove.
Referenced by tb_string_pool_del(), and tb_string_pool_put().
tb_void_t tb_iterator_remove_range (tb_iterator_ref_t iterator, tb_size_t prev, tb_size_t next, tb_size_t size)
remove the iterator items from range(prev, next)
Parameters
iterator the iterator
prev the prev item
next the next item
size the removed size
Definition at line 114 of file iterator.c.
References tb_iterator_t::remove_range.
Referenced by tb_remove_if().
tb_size_t tb_iterator_size (tb_iterator_ref_t iterator)
the iterator size
Parameters
iterator the iterator
Returns
the iterator size
Definition at line 50 of file iterator.c.
References tb_iterator_t::size.
tb_size_t tb_iterator_step (tb_iterator_ref_t iterator)
the iterator step
Parameters
iterator the iterator
Returns
the iterator step
Definition at line 42 of file iterator.c.
References tb_iterator_t::step.
Referenced by tb_bubble_sort(), tb_heap_sort(), tb_insert_sort(), and tb_quick_sort().
tb_size_t tb_iterator_tail (tb_iterator_ref_t iterator)
the iterator tail
Parameters
iterator the iterator
Returns
the iterator tail
Definition at line 74 of file iterator.c.
References tb_iterator_t::tail.
Referenced by tb_binary_find_all_if(), tb_bubble_sort_all(), tb_count_all_if(), tb_find_all_if(), tb_fixed_pool_clear(), tb_heap_sort_all(), tb_insert_sort_all(), tb_list_insert_prev(), tb_list_insert_tail(), tb_list_moveto_tail(), tb_list_remove(), tb_quick_sort_all(), tb_remove_if(), tb_rfind_all_if(), tb_rwalk_all(), tb_single_list_insert_head(), tb_single_list_insert_next(), tb_single_list_insert_tail(), tb_sort_all(), tb_string_pool_del(), tb_string_pool_put(), tb_timer_task_kill(), and tb_walk_all().