TBOX: src/tbox/algorithm/sort.c File Reference
sort.c File Reference
Algorithm
#include "sort.h"
#include "heap_sort.h"
#include "quick_sort.h"
#include "insert_sort.h"
#include "bubble_sort.h"
#include "../libc/libc.h"
Functions
tb_void_t tb_sort (tb_iterator_ref_t iterator, tb_size_t head, tb_size_t tail, tb_iterator_comp_t comp)
tb_void_t tb_sort_all (tb_iterator_ref_t iterator, tb_iterator_comp_t comp)
Detailed Description
The Treasure Box Library
TBox is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 2.1 of the License, or (at your option) any later version.
TBox is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with TBox; If not, see http://www.gnu.org/licenses/
Copyright (C) 2009 - 2015, ruki All rights reserved.
Author
ruki
Definition in file sort.c.
Function Documentation
tb_void_t tb_sort (tb_iterator_ref_t iterator, tb_size_t head, tb_size_t tail, tb_iterator_comp_t comp)
the sorter
Parameters
iterator the iterator
head the iterator head
tail the iterator tail
comp the comparer
<
Note
the recursive stack size is limit
Definition at line 38 of file sort.c.
References tb_bubble_sort(), tb_heap_sort(), tb_iterator_mode(), TB_ITERATOR_MODE_RACCESS, TB_ITERATOR_MODE_READONLY, and tb_quick_sort().
Referenced by tb_sort_all().
tb_void_t tb_sort_all (tb_iterator_ref_t iterator, tb_iterator_comp_t comp)
the sorter for all
Parameters
iterator the iterator
head the iterator head
tail the iterator tail
comp the comparer
Definition at line 54 of file sort.c.
References tb_iterator_head(), tb_iterator_tail(), and tb_sort().