TBOX: src/tbox/network/ipv4.c File Reference
ipv4.c File Reference
Network
#include "ipv4.h"
#include "../libc/libc.h"
#include "../math/math.h"
#include "../utils/utils.h"
#include "../string/string.h"
#include "../platform/platform.h"
Macros
#define TB_TRACE_MODULE_NAME "ipv4"
#define TB_TRACE_MODULE_DEBUG (0)
Functions
tb_void_t tb_ipv4_clr (tb_ipv4_t *ipv4)
tb_uint32_t tb_ipv4_set (tb_ipv4_t *ipv4, tb_char_t const *ip)
tb_char_t const * tb_ipv4_get (tb_ipv4_t const *ipv4, tb_char_t *data, tb_size_t maxn)
Detailed Description
The Treasure Box Library
TBox is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 2.1 of the License, or (at your option) any later version.
TBox is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with TBox; If not, see http://www.gnu.org/licenses/
Copyright (C) 2009 - 2015, ruki All rights reserved.
Author
ruki
Definition in file ipv4.c.
Function Documentation
tb_void_t tb_ipv4_clr (tb_ipv4_t * ipv4)
clear the ipv4
Parameters
ipv4 the ipv4
Definition at line 45 of file ipv4.c.
tb_char_t const* tb_ipv4_get (tb_ipv4_t const * ipv4, tb_char_t * data, tb_size_t maxn)
get the ipv4 address
Parameters
ipv4 the ipv4
data the ipv4 data
maxn the data maxn
Returns
the ipv4 address
Definition at line 96 of file ipv4.c.
References tb_snprintf().
tb_uint32_t tb_ipv4_set (tb_ipv4_t * ipv4, tb_char_t const * ip)
set the ipv4 from the ip address
Parameters
ipv4 the ipv4
ip the ip address
Returns
the ipv4 value
Definition at line 49 of file ipv4.c.
Referenced by tb_dns_looker_init(), tb_dns_server_add(), and tb_socket_accept().