TBOX: src/tbox/container/vector.h File Reference
vector.h File Reference
Container
#include "prefix.h"
#include "item.h"
#include "iterator.h"
Functions
tb_vector_ref_t tb_vector_init (tb_size_t grow, tb_item_func_t func)
tb_void_t tb_vector_exit (tb_vector_ref_t vector)
tb_pointer_t tb_vector_data (tb_vector_ref_t vector)
tb_pointer_t tb_vector_head (tb_vector_ref_t vector)
tb_pointer_t tb_vector_last (tb_vector_ref_t vector)
tb_bool_t tb_vector_resize (tb_vector_ref_t vector, tb_size_t size)
tb_void_t tb_vector_clear (tb_vector_ref_t vector)
tb_void_t tb_vector_copy (tb_vector_ref_t vector, tb_vector_ref_t copy)
tb_void_t tb_vector_insert_prev (tb_vector_ref_t vector, tb_size_t itor, tb_cpointer_t data)
tb_void_t tb_vector_insert_next (tb_vector_ref_t vector, tb_size_t itor, tb_cpointer_t data)
tb_void_t tb_vector_insert_head (tb_vector_ref_t vector, tb_cpointer_t data)
tb_void_t tb_vector_insert_tail (tb_vector_ref_t vector, tb_cpointer_t data)
tb_void_t tb_vector_ninsert_prev (tb_vector_ref_t vector, tb_size_t itor, tb_cpointer_t data, tb_size_t size)
tb_void_t tb_vector_ninsert_next (tb_vector_ref_t vector, tb_size_t itor, tb_cpointer_t data, tb_size_t size)
tb_void_t tb_vector_ninsert_head (tb_vector_ref_t vector, tb_cpointer_t data, tb_size_t size)
tb_void_t tb_vector_ninsert_tail (tb_vector_ref_t vector, tb_cpointer_t data, tb_size_t size)
tb_void_t tb_vector_replace (tb_vector_ref_t vector, tb_size_t itor, tb_cpointer_t data)
tb_void_t tb_vector_replace_head (tb_vector_ref_t vector, tb_cpointer_t data)
tb_void_t tb_vector_replace_last (tb_vector_ref_t vector, tb_cpointer_t data)
tb_void_t tb_vector_nreplace (tb_vector_ref_t vector, tb_size_t itor, tb_cpointer_t data, tb_size_t size)
tb_void_t tb_vector_nreplace_head (tb_vector_ref_t vector, tb_cpointer_t data, tb_size_t size)
tb_void_t tb_vector_nreplace_last (tb_vector_ref_t vector, tb_cpointer_t data, tb_size_t size)
tb_void_t tb_vector_remove (tb_vector_ref_t vector, tb_size_t itor)
tb_void_t tb_vector_remove_head (tb_vector_ref_t vector)
tb_void_t tb_vector_remove_last (tb_vector_ref_t vector)
tb_void_t tb_vector_nremove (tb_vector_ref_t vector, tb_size_t itor, tb_size_t size)
tb_void_t tb_vector_nremove_head (tb_vector_ref_t vector, tb_size_t size)
tb_void_t tb_vector_nremove_last (tb_vector_ref_t vector, tb_size_t size)
tb_bool_t tb_vector_load (tb_vector_ref_t vector, tb_stream_ref_t stream)
tb_bool_t tb_vector_save (tb_vector_ref_t vector, tb_stream_ref_t stream)
tb_size_t tb_vector_size (tb_vector_ref_t vector)
tb_size_t tb_vector_grow (tb_vector_ref_t vector)
tb_size_t tb_vector_maxn (tb_vector_ref_t vector)
Variables
__tb_extern_c_enter__ typedef
tb_iterator_ref_t tb_vector_ref_t
Detailed Description
The Treasure Box Library
TBox is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 2.1 of the License, or (at your option) any later version.
TBox is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with TBox; If not, see http://www.gnu.org/licenses/
Copyright (C) 2009 - 2015, ruki All rights reserved.
Author
ruki
Definition in file vector.h.
Function Documentation
tb_void_t tb_vector_clear (tb_vector_ref_t vector)
clear the vector
Parameters
vector the vector
Definition at line 248 of file vector.c.
Referenced by tb_ltimer_clear(), tb_ltimer_spak(), tb_stack_clear(), tb_vector_copy(), tb_vector_exit(), tb_vector_load(), tb_vector_nremove(), tb_vector_nremove_head(), and tb_vector_nremove_last().
tb_void_t tb_vector_copy (tb_vector_ref_t vector, tb_vector_ref_t copy)
copy the vector
Parameters
vector the vector
copy the copied vector
Definition at line 261 of file vector.c.
References tb_vector_clear(), and tb_vector_resize().
Referenced by tb_stack_copy().
tb_pointer_t tb_vector_data (tb_vector_ref_t vector)
the vector data
Parameters
vector the vector
Returns
the vector data
Definition at line 293 of file vector.c.
tb_void_t tb_vector_exit (tb_vector_ref_t vector)
exist vector
Parameters
vector the vector
Definition at line 232 of file vector.c.
References tb_vector_clear().
Referenced by tb_ltimer_exit(), tb_stack_exit(), and tb_vector_init().
tb_size_t tb_vector_grow (tb_vector_ref_t vector)
the vector grow
Parameters
vector the vector
Returns
the vector grow
Definition at line 319 of file vector.c.
tb_pointer_t tb_vector_head (tb_vector_ref_t vector)
the vector head item
Parameters
vector the vector
Returns
the vector head item
Definition at line 302 of file vector.c.
References tb_iterator_head(), and tb_iterator_item().
Referenced by tb_stack_head().
tb_vector_ref_t tb_vector_init (tb_size_t grow, tb_item_func_t func)
init vector
Parameters
grow the item grow
func the item func
Returns
the vector
Definition at line 174 of file vector.c.
References tb_item_func_t::data, tb_item_func_t::dupl, tb_item_func_t::ndupl, tb_item_func_t::nrepl, tb_item_func_t::repl, tb_item_func_t::size, TB_ITERATOR_MODE_FORWARD, TB_ITERATOR_MODE_MUTABLE, TB_ITERATOR_MODE_RACCESS, TB_ITERATOR_MODE_REVERSE, tb_vector_exit(), and tb_vector_ref_t.
Referenced by tb_ltimer_init(), tb_object_array_init(), and tb_stack_init().
tb_void_t tb_vector_insert_head (tb_vector_ref_t vector, tb_cpointer_t data)
insert the vector head item
Parameters
vector the vector
itor the item itor
data the item data
Definition at line 401 of file vector.c.
References tb_vector_insert_prev().
tb_void_t tb_vector_insert_next (tb_vector_ref_t vector, tb_size_t itor, tb_cpointer_t data)
insert the vector next item
Parameters
vector the vector
itor the item itor
data the item data
Definition at line 397 of file vector.c.
References tb_iterator_next(), and tb_vector_insert_prev().
tb_void_t tb_vector_insert_prev (tb_vector_ref_t vector, tb_size_t itor, tb_cpointer_t data)
insert the vector prev item
Parameters
vector the vector
itor the item itor
data the item data
Definition at line 375 of file vector.c.
References tb_vector_resize().
Referenced by tb_object_array_insert(), tb_vector_insert_head(), tb_vector_insert_next(), and tb_vector_insert_tail().
tb_void_t tb_vector_insert_tail (tb_vector_ref_t vector, tb_cpointer_t data)
insert the vector tail item
Parameters
vector the vector
itor the item itor
data the item data
Definition at line 405 of file vector.c.
References tb_vector_insert_prev(), and tb_vector_size().
Referenced by tb_dns_server_add(), tb_object_array_append(), tb_stack_put(), and tb_vector_load().
tb_pointer_t tb_vector_last (tb_vector_ref_t vector)
the vector last item
Parameters
vector the vector
Returns
the vector last item
Definition at line 306 of file vector.c.
References tb_iterator_item(), and tb_iterator_last().
Referenced by tb_stack_last(), and tb_stack_top().
tb_bool_t tb_vector_load (tb_vector_ref_t vector, tb_stream_ref_t stream)
load vector from the stream
Parameters
vector the vector
stream the stream
Returns
tb_true or tb_false
Definition at line 593 of file vector.c.
References tb_crc_encode_cstr(), tb_stream_bread_u32_be(), tb_stream_offset(), tb_stream_seek(), tb_vector_clear(), and tb_vector_insert_tail().
Referenced by tb_stack_load().
tb_size_t tb_vector_maxn (tb_vector_ref_t vector)
the vector maxn
Parameters
vector the vector
Returns
the vector maxn
Definition at line 328 of file vector.c.
Referenced by tb_stack_maxn().
tb_void_t tb_vector_ninsert_head (tb_vector_ref_t vector, tb_cpointer_t data, tb_size_t size)
insert the vector head items
Parameters
vector the vector
itor the item itor
data the item data
size the item count
Definition at line 435 of file vector.c.
References tb_vector_ninsert_prev().
tb_void_t tb_vector_ninsert_next (tb_vector_ref_t vector, tb_size_t itor, tb_cpointer_t data, tb_size_t size)
insert the vector next items
Parameters
vector the vector
itor the item itor
data the item data
size the item count
Definition at line 431 of file vector.c.
References tb_iterator_next(), and tb_vector_ninsert_prev().
tb_void_t tb_vector_ninsert_prev (tb_vector_ref_t vector, tb_size_t itor, tb_cpointer_t data, tb_size_t size)
insert the vector prev items
Parameters
vector the vector
itor the item itor
data the item data
size the item count
Definition at line 409 of file vector.c.
References tb_vector_resize().
Referenced by tb_vector_ninsert_head(), tb_vector_ninsert_next(), and tb_vector_ninsert_tail().
tb_void_t tb_vector_ninsert_tail (tb_vector_ref_t vector, tb_cpointer_t data, tb_size_t size)
insert the vector tail items
Parameters
vector the vector
itor the item itor
data the item data
size the item count
Definition at line 439 of file vector.c.
References tb_vector_ninsert_prev(), and tb_vector_size().
tb_void_t tb_vector_nremove (tb_vector_ref_t vector, tb_size_t itor, tb_size_t size)
remove the vector items
Parameters
vector the vector
itor the item itor
size the item count
Definition at line 527 of file vector.c.
References tb_vector_clear().
Referenced by tb_vector_nremove_head(), and tb_vector_nremove_last().
tb_void_t tb_vector_nremove_head (tb_vector_ref_t vector, tb_size_t size)
remove the vector head items
Parameters
vector the vector
size the item count
Definition at line 561 of file vector.c.
References tb_vector_clear(), and tb_vector_nremove().
tb_void_t tb_vector_nremove_last (tb_vector_ref_t vector, tb_size_t size)
remove the vector last items
Parameters
vector the vector
size the item count
Definition at line 577 of file vector.c.
References tb_vector_clear(), and tb_vector_nremove().
tb_void_t tb_vector_nreplace (tb_vector_ref_t vector, tb_size_t itor, tb_cpointer_t data, tb_size_t size)
replace the vector items
Parameters
vector the vector
itor the item itor
data the item data
size the item count
Definition at line 465 of file vector.c.
Referenced by tb_vector_nreplace_head(), and tb_vector_nreplace_last().
tb_void_t tb_vector_nreplace_head (tb_vector_ref_t vector, tb_cpointer_t data, tb_size_t size)
replace the vector head items
Parameters
vector the vector
itor the item itor
data the item data
size the item count
Definition at line 477 of file vector.c.
References tb_vector_nreplace().
tb_void_t tb_vector_nreplace_last (tb_vector_ref_t vector, tb_cpointer_t data, tb_size_t size)
replace the vector last items
Parameters
vector the vector
itor the item itor
data the item data
size the item count
Definition at line 481 of file vector.c.
References tb_vector_nreplace().
tb_void_t tb_vector_remove (tb_vector_ref_t vector, tb_size_t itor)
remove the vector item
Parameters
vector the vector
itor the item itor
Definition at line 490 of file vector.c.
Referenced by tb_object_array_remove(), and tb_vector_remove_head().
tb_void_t tb_vector_remove_head (tb_vector_ref_t vector)
remove the vector head item
Parameters
vector the vector
Definition at line 508 of file vector.c.
References tb_vector_remove().
tb_void_t tb_vector_remove_last (tb_vector_ref_t vector)
remove the vector last item
Parameters
vector the vector
Definition at line 512 of file vector.c.
Referenced by tb_stack_pop().
tb_void_t tb_vector_replace (tb_vector_ref_t vector, tb_size_t itor, tb_cpointer_t data)
replace the vector item
Parameters
vector the vector
itor the item itor
data the item data
Definition at line 443 of file vector.c.
Referenced by tb_object_array_replace(), tb_vector_replace_head(), and tb_vector_replace_last().
tb_void_t tb_vector_replace_head (tb_vector_ref_t vector, tb_cpointer_t data)
replace the vector head item
Parameters
vector the vector
itor the item itor
data the item data
Definition at line 452 of file vector.c.
References tb_vector_replace().
tb_void_t tb_vector_replace_last (tb_vector_ref_t vector, tb_cpointer_t data)
replace the vector last item
Parameters
vector the vector
itor the item itor
data the item data
Definition at line 456 of file vector.c.
References tb_vector_replace().
tb_bool_t tb_vector_resize (tb_vector_ref_t vector, tb_size_t size)
resize the vector
Parameters
vector the vector
size the vector size
Returns
tb_true or tb_false
Definition at line 337 of file vector.c.
Referenced by tb_vector_copy(), tb_vector_insert_prev(), and tb_vector_ninsert_prev().
tb_bool_t tb_vector_save (tb_vector_ref_t vector, tb_stream_ref_t stream)
save vector to the stream
Parameters
vector the vector
stream the stream
Returns
tb_true or tb_false
Definition at line 683 of file vector.c.
References tb_crc_encode_cstr(), tb_for_all, tb_stream_bwrit_u32_be(), tb_stream_offset(), tb_stream_seek(), and tb_vector_size().
Referenced by tb_stack_save().
tb_size_t tb_vector_size (tb_vector_ref_t vector)
the vector size
Parameters
vector the vector
Returns
the vector size
Definition at line 310 of file vector.c.
Referenced by tb_dns_server_get(), tb_ltimer_spak(), tb_object_array_size(), tb_stack_size(), tb_vector_insert_tail(), tb_vector_ninsert_tail(), and tb_vector_save().
Variable Documentation
__tb_extern_c_enter__ typedef tb_iterator_ref_t tb_vector_ref_t
the vector ref type
vector: |-----|--------------------------------------------------------|------|
      head                                                           last    tail
performance:
insert:
insert midd: slow
insert head: slow
insert tail: fast
ninsert:
ninsert midd: fast
ninsert head: fast
ninsert tail: fast
remove:
remove midd: slow
remove head: slow
remove last: fast
nremove:
nremove midd: fast
nremove head: fast
nremove last: fast
iterator:
next: fast
prev: fast
Note
the itor of the same item is mutable
Definition at line 79 of file vector.h.
Referenced by tb_ltimer_spak(), and tb_vector_init().