TBOX: src/tbox/prefix/assert.h File Reference
assert.h File Reference
#include "config.h"
#include "trace.h"
#include "abort.h"
#include "check.h"
#include "keyword.h"
Macros
#define TB_ASSERT_BACKTRACE_PREFIX " "
#define TB_ASSERT_BACKTRACE_NFRAME (16)
#define tb_assert_backtrace_dump() tb_backtrace_dump(TB_ASSERT_BACKTRACE_PREFIX, tb_null, TB_ASSERT_BACKTRACE_NFRAME)
#define tb_assertf
#define tb_assertf_abort
#define tb_assertf_return
#define tb_assertf_return_val
#define tb_assertf_goto
#define tb_assertf_break
#define tb_assertf_continue
#define tb_assertf_and_check_abort tb_abort();
#define tb_assertf_and_check_return tb_abort();
#define tb_assertf_and_check_return_val tb_abort();
#define tb_assertf_and_check_goto tb_abort();
#define tb_assertf_and_check_break tb_abort();
#define tb_assertf_and_check_continue tb_abort();
#define tb_assert(x)
#define tb_assert_abort(x)
#define tb_assert_return(x)
#define tb_assert_return_val(x, v)
#define tb_assert_goto(x, b)
#define tb_assert_break(x)
#define tb_assert_continue(x)
#define tb_assert_break_state(x, s, v)
#define tb_assert_and_check_abort(x) tb_check_abort(x)
#define tb_assert_and_check_return(x) tb_check_return(x)
#define tb_assert_and_check_return_val(x, v) tb_check_return_val(x, v)
#define tb_assert_and_check_goto(x, b) tb_check_goto(x, b)
#define tb_assert_and_check_break(x) tb_check_break(x)
#define tb_assert_and_check_continue(x) tb_check_continue(x)
#define tb_assert_and_check_break_state(x, s, v) tb_check_break_state(x, s, v)
#define tb_assert_static(x) do { typedef int __tb_static_assert__[(x)? 1 : -1]; __tb_volatile__ __tb_static_assert__ __a; tb_used(__a); } while(0)
Functions
tb_void_t tb_backtrace_dump (tb_char_t const *prefix, tb_pointer_t *frames, tb_size_t nframe)
Detailed Description
The Treasure Box Library
TBox is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 2.1 of the License, or (at your option) any later version.
TBox is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with TBox; If not, see http://www.gnu.org/licenses/
Copyright (C) 2009 - 2015, ruki All rights reserved.
Author
ruki
Definition in file assert.h.
Function Documentation
tb_void_t tb_backtrace_dump (tb_char_t const * prefix, tb_pointer_t * frames, tb_size_t nframe)
dump backtrace
Parameters
prefix the backtrace prefix
frames the backtrace frames, dump the current frames if null
nframe the backtrace frame count
Definition at line 38 of file backtrace.c.
References tb_backtrace_frames(), tb_backtrace_symbols_exit(), tb_backtrace_symbols_init(), and tb_backtrace_symbols_name().