TBOX: src/tbox/asio/aiop.h File Reference
aiop.h File Reference
Asio
#include "prefix.h"
#include "aioo.h"
#include "aioe.h"
#include "../platform/prefix.h"
#include "../container/container.h"
Functions
__tb_extern_c_enter__ tb_aiop_ref_t tb_aiop_init (tb_size_t maxn)
tb_void_t tb_aiop_exit (tb_aiop_ref_t aiop)
tb_void_t tb_aiop_cler (tb_aiop_ref_t aiop)
tb_void_t tb_aiop_kill (tb_aiop_ref_t aiop)
tb_void_t tb_aiop_spak (tb_aiop_ref_t aiop)
tb_bool_t tb_aiop_have (tb_aiop_ref_t aiop, tb_size_t code)
tb_aioo_ref_t tb_aiop_addo (tb_aiop_ref_t aiop, tb_socket_ref_t sock, tb_size_t code, tb_cpointer_t priv)
tb_void_t tb_aiop_delo (tb_aiop_ref_t aiop, tb_aioo_ref_t aioo)
tb_bool_t tb_aiop_post (tb_aiop_ref_t aiop, tb_aioe_t const *aioe)
tb_bool_t tb_aiop_sete (tb_aiop_ref_t aiop, tb_aioo_ref_t aioo, tb_size_t code, tb_cpointer_t priv)
tb_long_t tb_aiop_wait (tb_aiop_ref_t aiop, tb_aioe_t *list, tb_size_t maxn, tb_long_t timeout)
Detailed Description
The Treasure Box Library
TBox is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 2.1 of the License, or (at your option) any later version.
TBox is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with TBox; If not, see http://www.gnu.org/licenses/
Copyright (C) 2009 - 2015, ruki All rights reserved.
Author
ruki
Definition in file aiop.h.
Function Documentation
tb_aioo_ref_t tb_aiop_addo (tb_aiop_ref_t aiop, tb_socket_ref_t sock, tb_size_t code, tb_cpointer_t priv)
addo the aioo
Parameters
aiop the aiop
sock the socket
code the code
priv the private data
Returns
the aioo
Definition at line 240 of file aiop.c.
References tb_aiop_have().
Referenced by tb_aiop_cler(), and tb_aiop_init().
tb_void_t tb_aiop_cler (tb_aiop_ref_t aiop)
cler the aiop
Parameters
aiop the aiop
Definition at line 171 of file aiop.c.
References tb_aiop_addo(), and tb_fixed_pool_clear().
tb_void_t tb_aiop_delo (tb_aiop_ref_t aiop, tb_aioo_ref_t aioo)
delo the aioo
Parameters
aiop the aiop
aioo the aioo
Definition at line 274 of file aiop.c.
tb_void_t tb_aiop_exit (tb_aiop_ref_t aiop)
exit the aiop
Parameters
aiop the aiop
Definition at line 143 of file aiop.c.
References tb_fixed_pool_exit(), and tb_socket_exit().
Referenced by tb_aiop_init().
tb_bool_t tb_aiop_have (tb_aiop_ref_t aiop, tb_size_t code)
the aioe code is supported for the aiop?
Parameters
aiop the aiop
Returns
tb_true or tb_false
Definition at line 189 of file aiop.c.
Referenced by tb_aiop_addo(), and tb_aiop_post().
__tb_extern_c_enter__ tb_aiop_ref_t tb_aiop_init (tb_size_t maxn)
init the aiop
Parameters
maxn the maximum number of concurrent objects
Returns
the aiop
Definition at line 88 of file aiop.c.
References tb_aiop_addo(), tb_aiop_exit(), tb_fixed_pool_init(), tb_lock_profiler(), tb_lock_profiler_register(), and tb_socket_pair().
tb_void_t tb_aiop_kill (tb_aiop_ref_t aiop)
kill the aiop
Parameters
aiop the aiop
Definition at line 198 of file aiop.c.
References tb_socket_send().
tb_bool_t tb_aiop_post (tb_aiop_ref_t aiop, tb_aioe_t const * aioe)
post the aioe
Parameters
aiop the aiop
aioe the aioe
Returns
tb_true or tb_false
Definition at line 283 of file aiop.c.
References tb_aioe_t::code, and tb_aiop_have().
Referenced by tb_aiop_sete().
tb_bool_t tb_aiop_sete (tb_aiop_ref_t aiop, tb_aioo_ref_t aioo, tb_size_t code, tb_cpointer_t priv)
set the aioe
Parameters
aiop the aiop
aioo the aioo
code the code
priv the private data
Returns
tb_true or tb_false
Definition at line 293 of file aiop.c.
References tb_aioe_t::aioo, tb_aioe_t::code, tb_aioe_t::priv, tb_aioo_sock(), and tb_aiop_post().
tb_void_t tb_aiop_spak (tb_aiop_ref_t aiop)
spak the aiop, break the wait
Parameters
aiop the aiop
Definition at line 219 of file aiop.c.
References tb_socket_send().
tb_long_t tb_aiop_wait (tb_aiop_ref_t aiop, tb_aioe_t * list, tb_size_t maxn, tb_long_t timeout)
wait the asio objects in the pool
blocking wait the multiple event objects return the event number if ok, otherwise return 0 for timeout
Parameters
aiop the aiop
list the aioe list
maxn the aioe maxn
timeout the timeout, infinity: -1
Returns
> 0: the aioe list size, 0: timeout, -1: failed
Definition at line 308 of file aiop.c.