TBOX: src/tbox/stream/impl/filter/chunked.c File Reference
chunked.c File Reference
#include "prefix.h"
Macros
#define TB_TRACE_MODULE_NAME "chunked"
#define TB_TRACE_MODULE_DEBUG (1)
Functions
tb_stream_filter_ref_t tb_stream_filter_init_from_chunked (tb_bool_t dechunked)
Detailed Description
The Treasure Box Library
TBox is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 2.1 of the License, or (at your option) any later version.
TBox is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with TBox; If not, see http://www.gnu.org/licenses/
Copyright (C) 2009 - 2015, ruki All rights reserved.
Author
ruki
Definition in file chunked.c.
Function Documentation
tb_stream_filter_ref_t tb_stream_filter_init_from_chunked (tb_bool_t dechunked)
init filter from chunked
Parameters
dechunked decode the chunked data?
Returns
the filter
Definition at line 235 of file chunked.c.
References tb_stream_filter_exit().
Referenced by tb_async_stream_init_filter_from_chunked(), and tb_stream_init_filter_from_chunked().