TBOX: src/tbox/stream/static_stream.h File Reference
static_stream.h File Reference
Stream
#include "prefix.h"
#include "../utils/utils.h"
Data Structures
struct tb_static_stream_t
the static stream type
Macros
#define tb_static_stream_read_u16_ne(stream) tb_static_stream_read_u16_le(stream)
#define tb_static_stream_read_s16_ne(stream) tb_static_stream_read_s16_le(stream)
#define tb_static_stream_read_u24_ne(stream) tb_static_stream_read_u24_le(stream)
#define tb_static_stream_read_s24_ne(stream) tb_static_stream_read_s24_le(stream)
#define tb_static_stream_read_u32_ne(stream) tb_static_stream_read_u32_le(stream)
#define tb_static_stream_read_s32_ne(stream) tb_static_stream_read_s32_le(stream)
#define tb_static_stream_read_u64_ne(stream) tb_static_stream_read_u64_le(stream)
#define tb_static_stream_read_s64_ne(stream) tb_static_stream_read_s64_le(stream)
#define tb_static_stream_writ_u16_ne(stream, val) tb_static_stream_writ_u16_le(stream, val)
#define tb_static_stream_writ_s16_ne(stream, val) tb_static_stream_writ_s16_le(stream, val)
#define tb_static_stream_writ_u24_ne(stream, val) tb_static_stream_writ_u24_le(stream, val)
#define tb_static_stream_writ_s24_ne(stream, val) tb_static_stream_writ_s24_le(stream, val)
#define tb_static_stream_writ_u32_ne(stream, val) tb_static_stream_writ_u32_le(stream, val)
#define tb_static_stream_writ_s32_ne(stream, val) tb_static_stream_writ_s32_le(stream, val)
#define tb_static_stream_writ_u64_ne(stream, val) tb_static_stream_writ_u64_le(stream, val)
#define tb_static_stream_writ_s64_ne(stream, val) tb_static_stream_writ_s64_le(stream, val)
#define tb_static_stream_read_double_nbe(stream) tb_static_stream_read_double_lbe(stream)
#define tb_static_stream_read_double_nle(stream) tb_static_stream_read_double_lle(stream)
#define tb_static_stream_writ_double_nbe(stream, val) tb_static_stream_writ_double_lbe(stream, val)
#define tb_static_stream_writ_double_nle(stream, val) tb_static_stream_writ_double_lle(stream, val)
#define tb_static_stream_read_float_ne(stream) tb_static_stream_read_float_le(stream)
#define tb_static_stream_writ_float_ne(stream, val) tb_static_stream_writ_float_le(stream, val)
#define tb_static_stream_read_double_nne(stream) tb_static_stream_read_double_nle(stream)
#define tb_static_stream_read_double_bne(stream) tb_static_stream_read_double_ble(stream)
#define tb_static_stream_read_double_lne(stream) tb_static_stream_read_double_lle(stream)
#define tb_static_stream_writ_double_nne(stream, val) tb_static_stream_writ_double_nle(stream, val)
#define tb_static_stream_writ_double_bne(stream, val) tb_static_stream_writ_double_ble(stream, val)
#define tb_static_stream_writ_double_lne(stream, val) tb_static_stream_writ_double_lle(stream, val)
Typedefs
typedef tb_static_stream_t * tb_static_stream_ref_t
the static stream ref type
Functions
tb_bool_t tb_static_stream_init (tb_static_stream_ref_t stream, tb_byte_t *data, tb_size_t size)
tb_bool_t tb_static_stream_goto (tb_static_stream_ref_t stream, tb_byte_t *data)
tb_bool_t tb_static_stream_sync (tb_static_stream_ref_t stream)
tb_byte_t const * tb_static_stream_beg (tb_static_stream_ref_t stream)
tb_byte_t const * tb_static_stream_pos (tb_static_stream_ref_t stream)
tb_byte_t const * tb_static_stream_end (tb_static_stream_ref_t stream)
tb_size_t tb_static_stream_offset (tb_static_stream_ref_t stream)
tb_size_t tb_static_stream_size (tb_static_stream_ref_t stream)
tb_size_t tb_static_stream_left (tb_static_stream_ref_t stream)
tb_size_t tb_static_stream_left_bits (tb_static_stream_ref_t stream)
tb_bool_t tb_static_stream_valid (tb_static_stream_ref_t stream)
tb_bool_t tb_static_stream_skip (tb_static_stream_ref_t stream, tb_size_t size)
tb_bool_t tb_static_stream_skip_bits (tb_static_stream_ref_t stream, tb_size_t nbits)
tb_bool_t tb_static_stream_skip_cstr (tb_static_stream_ref_t stream)
tb_uint32_t tb_static_stream_peek_ubits32 (tb_static_stream_ref_t stream, tb_size_t nbits)
tb_sint32_t tb_static_stream_peek_sbits32 (tb_static_stream_ref_t stream, tb_size_t nbits)
tb_char_t const * tb_static_stream_read_cstr (tb_static_stream_ref_t stream)
tb_size_t tb_static_stream_read_data (tb_static_stream_ref_t stream, tb_byte_t *data, tb_size_t size)
tb_uint32_t tb_static_stream_read_ubits32 (tb_static_stream_ref_t stream, tb_size_t nbits)
tb_sint32_t tb_static_stream_read_sbits32 (tb_static_stream_ref_t stream, tb_size_t nbits)
tb_uint8_t tb_static_stream_read_u1 (tb_static_stream_ref_t stream)
tb_uint8_t tb_static_stream_read_u8 (tb_static_stream_ref_t stream)
tb_sint8_t tb_static_stream_read_s8 (tb_static_stream_ref_t stream)
tb_uint16_t tb_static_stream_read_u16_be (tb_static_stream_ref_t stream)
tb_sint16_t tb_static_stream_read_s16_be (tb_static_stream_ref_t stream)
tb_uint16_t tb_static_stream_read_u16_le (tb_static_stream_ref_t stream)
tb_sint16_t tb_static_stream_read_s16_le (tb_static_stream_ref_t stream)
tb_uint32_t tb_static_stream_read_u24_be (tb_static_stream_ref_t stream)
tb_sint32_t tb_static_stream_read_s24_be (tb_static_stream_ref_t stream)
tb_uint32_t tb_static_stream_read_u24_le (tb_static_stream_ref_t stream)
tb_sint32_t tb_static_stream_read_s24_le (tb_static_stream_ref_t stream)
tb_uint32_t tb_static_stream_read_u32_be (tb_static_stream_ref_t stream)
tb_sint32_t tb_static_stream_read_s32_be (tb_static_stream_ref_t stream)
tb_uint32_t tb_static_stream_read_u32_le (tb_static_stream_ref_t stream)
tb_sint32_t tb_static_stream_read_s32_le (tb_static_stream_ref_t stream)
tb_uint64_t tb_static_stream_read_u64_be (tb_static_stream_ref_t stream)
tb_sint64_t tb_static_stream_read_s64_be (tb_static_stream_ref_t stream)
tb_uint64_t tb_static_stream_read_u64_le (tb_static_stream_ref_t stream)
tb_sint64_t tb_static_stream_read_s64_le (tb_static_stream_ref_t stream)
tb_char_t * tb_static_stream_writ_cstr (tb_static_stream_ref_t stream, tb_char_t const *cstr)
tb_size_t tb_static_stream_writ_data (tb_static_stream_ref_t stream, tb_byte_t const *data, tb_size_t size)
tb_bool_t tb_static_stream_writ_ubits32 (tb_static_stream_ref_t stream, tb_uint32_t val, tb_size_t nbits)
tb_bool_t tb_static_stream_writ_sbits32 (tb_static_stream_ref_t stream, tb_sint32_t val, tb_size_t nbits)
tb_bool_t tb_static_stream_writ_u1 (tb_static_stream_ref_t stream, tb_uint8_t val)
tb_bool_t tb_static_stream_writ_u8 (tb_static_stream_ref_t stream, tb_uint8_t val)
tb_bool_t tb_static_stream_writ_s8 (tb_static_stream_ref_t stream, tb_sint8_t val)
tb_bool_t tb_static_stream_writ_u16_be (tb_static_stream_ref_t stream, tb_uint16_t val)
tb_bool_t tb_static_stream_writ_s16_be (tb_static_stream_ref_t stream, tb_sint16_t val)
tb_bool_t tb_static_stream_writ_u16_le (tb_static_stream_ref_t stream, tb_uint16_t val)
tb_bool_t tb_static_stream_writ_s16_le (tb_static_stream_ref_t stream, tb_sint16_t val)
tb_bool_t tb_static_stream_writ_u24_be (tb_static_stream_ref_t stream, tb_uint32_t val)
tb_bool_t tb_static_stream_writ_s24_be (tb_static_stream_ref_t stream, tb_sint32_t val)
tb_bool_t tb_static_stream_writ_u24_le (tb_static_stream_ref_t stream, tb_uint32_t val)
tb_bool_t tb_static_stream_writ_s24_le (tb_static_stream_ref_t stream, tb_sint32_t val)
tb_bool_t tb_static_stream_writ_u32_be (tb_static_stream_ref_t stream, tb_uint32_t val)
tb_bool_t tb_static_stream_writ_s32_be (tb_static_stream_ref_t stream, tb_sint32_t val)
tb_bool_t tb_static_stream_writ_u32_le (tb_static_stream_ref_t stream, tb_uint32_t val)
tb_bool_t tb_static_stream_writ_s32_le (tb_static_stream_ref_t stream, tb_sint32_t val)
tb_bool_t tb_static_stream_writ_u64_be (tb_static_stream_ref_t stream, tb_uint64_t val)
tb_bool_t tb_static_stream_writ_s64_be (tb_static_stream_ref_t stream, tb_sint64_t val)
tb_bool_t tb_static_stream_writ_u64_le (tb_static_stream_ref_t stream, tb_uint64_t val)
tb_bool_t tb_static_stream_writ_s64_le (tb_static_stream_ref_t stream, tb_sint64_t val)
tb_float_t tb_static_stream_read_float_le (tb_static_stream_ref_t stream)
tb_float_t tb_static_stream_read_float_be (tb_static_stream_ref_t stream)
tb_double_t tb_static_stream_read_double_ble (tb_static_stream_ref_t stream)
tb_double_t tb_static_stream_read_double_bbe (tb_static_stream_ref_t stream)
tb_double_t tb_static_stream_read_double_lle (tb_static_stream_ref_t stream)
tb_double_t tb_static_stream_read_double_lbe (tb_static_stream_ref_t stream)
tb_bool_t tb_static_stream_writ_float_le (tb_static_stream_ref_t stream, tb_float_t val)
tb_bool_t tb_static_stream_writ_float_be (tb_static_stream_ref_t stream, tb_float_t val)
tb_bool_t tb_static_stream_writ_double_ble (tb_static_stream_ref_t stream, tb_double_t val)
tb_bool_t tb_static_stream_writ_double_bbe (tb_static_stream_ref_t stream, tb_double_t val)
tb_bool_t tb_static_stream_writ_double_lle (tb_static_stream_ref_t stream, tb_double_t val)
tb_bool_t tb_static_stream_writ_double_lbe (tb_static_stream_ref_t stream, tb_double_t val)
Detailed Description
The Treasure Box Library
TBox is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 2.1 of the License, or (at your option) any later version.
TBox is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with TBox; If not, see http://www.gnu.org/licenses/
Copyright (C) 2009 - 2015, ruki All rights reserved.
Author
ruki
Definition in file static_stream.h.
Function Documentation
tb_byte_t const* tb_static_stream_beg (tb_static_stream_ref_t stream)
the stream start data address
Parameters
stream the stream
Returns
the start data address
Definition at line 84 of file static_stream.c.
References tb_static_stream_t::e, and tb_static_stream_t::n.
tb_byte_t const* tb_static_stream_end (tb_static_stream_ref_t stream)
the stream end data address
Parameters
stream the stream
Returns
the end data address
Definition at line 103 of file static_stream.c.
References tb_static_stream_t::e.
tb_bool_t tb_static_stream_goto (tb_static_stream_ref_t stream, tb_byte_t * data)
goto the new data address for updating the stream position
Parameters
stream the stream
data the data address
Returns
tb_true or tb_false
Definition at line 53 of file static_stream.c.
References tb_static_stream_t::b, and tb_static_stream_t::p.
tb_bool_t tb_static_stream_init (tb_static_stream_ref_t stream, tb_byte_t * data, tb_size_t size)
init the static stream
Parameters
stream the stream
data the data address
size the data size
Returns
tb_true or tb_false
Definition at line 39 of file static_stream.c.
References tb_static_stream_t::b, tb_static_stream_t::e, tb_static_stream_t::n, and tb_static_stream_t::p.
Referenced by tb_charset_conv_data(), and tb_stream_filter_spak().
tb_size_t tb_static_stream_left (tb_static_stream_ref_t stream)
the stream left size
Parameters
stream the stream
Returns
the left size
Definition at line 130 of file static_stream.c.
References tb_static_stream_t::e, tb_static_stream_t::p, and tb_static_stream_sync().
Referenced by tb_charset_conv_bst(), and tb_stream_filter_spak().
tb_size_t tb_static_stream_left_bits (tb_static_stream_ref_t stream)
the stream left bits
Parameters
stream the stream
Returns
the left bits
Definition at line 141 of file static_stream.c.
References tb_static_stream_t::b, tb_static_stream_t::e, and tb_static_stream_t::p.
tb_size_t tb_static_stream_offset (tb_static_stream_ref_t stream)
the stream offset
Parameters
stream the stream
Returns
the offset
Definition at line 119 of file static_stream.c.
References tb_static_stream_t::e, tb_static_stream_t::n, tb_static_stream_t::p, and tb_static_stream_sync().
Referenced by tb_stream_filter_spak().
tb_sint32_t tb_static_stream_peek_sbits32 (tb_static_stream_ref_t stream, tb_size_t nbits)
peek sbits value for sint32
Parameters
stream the stream
nbits the bits count
Returns
the sbits value
Definition at line 225 of file static_stream.c.
References tb_static_stream_t::b, tb_static_stream_t::p, and tb_static_stream_read_sbits32().
tb_uint32_t tb_static_stream_peek_ubits32 (tb_static_stream_ref_t stream, tb_size_t nbits)
peek ubits value for uint32
Parameters
stream the stream
nbits the bits count
Returns
the ubits value
Definition at line 203 of file static_stream.c.
References tb_static_stream_t::b, tb_static_stream_t::p, and tb_static_stream_read_ubits32().
tb_byte_t const* tb_static_stream_pos (tb_static_stream_ref_t stream)
the stream current data address
Parameters
stream the stream
Returns
the current data address
Definition at line 92 of file static_stream.c.
References tb_static_stream_t::e, tb_static_stream_t::p, and tb_static_stream_sync().
Referenced by tb_charset_conv_bst(), and tb_stream_filter_spak().
tb_char_t const* tb_static_stream_read_cstr (tb_static_stream_ref_t stream)
read c-string
Parameters
stream the stream
Returns
the c-string
Definition at line 275 of file static_stream.c.
References tb_static_stream_t::e, tb_static_stream_t::p, tb_static_stream_skip(), and tb_static_stream_sync().
Referenced by tb_static_stream_skip_cstr().
tb_size_t tb_static_stream_read_data (tb_static_stream_ref_t stream, tb_byte_t * data, tb_size_t size)
read data
Parameters
stream the stream
data the data
size the size
Returns
the data real size
Definition at line 295 of file static_stream.c.
References tb_static_stream_t::e, tb_static_stream_t::p, tb_static_stream_skip(), and tb_static_stream_sync().
tb_double_t tb_static_stream_read_double_bbe (tb_static_stream_ref_t stream)
read double-bbe number
Parameters
stream the stream
Returns
the double-bbe number
Definition at line 866 of file static_stream.c.
References tb_static_stream_t::b, tb_static_stream_t::e, and tb_static_stream_t::p.
tb_double_t tb_static_stream_read_double_ble (tb_static_stream_ref_t stream)
read double-ble number
Parameters
stream the stream
Returns
the double-ble number
Definition at line 855 of file static_stream.c.
References tb_static_stream_t::b, tb_static_stream_t::e, and tb_static_stream_t::p.
tb_double_t tb_static_stream_read_double_lbe (tb_static_stream_ref_t stream)
read double-lbe number
Parameters
stream the stream
Returns
the double-lbe number
Definition at line 888 of file static_stream.c.
References tb_static_stream_t::b, tb_static_stream_t::e, and tb_static_stream_t::p.
tb_double_t tb_static_stream_read_double_lle (tb_static_stream_ref_t stream)
read double-lle number
Parameters
stream the stream
Returns
the double-lle number
Definition at line 877 of file static_stream.c.
References tb_static_stream_t::b, tb_static_stream_t::e, and tb_static_stream_t::p.
tb_float_t tb_static_stream_read_float_be (tb_static_stream_ref_t stream)
read float-be number
Parameters
stream the stream
Returns
the float-be number
Definition at line 844 of file static_stream.c.
References tb_static_stream_t::b, tb_static_stream_t::e, and tb_static_stream_t::p.
tb_float_t tb_static_stream_read_float_le (tb_static_stream_ref_t stream)
read float-le number
Parameters
stream the stream
Returns
the float-le number
Definition at line 833 of file static_stream.c.
References tb_static_stream_t::b, tb_static_stream_t::e, and tb_static_stream_t::p.
tb_sint16_t tb_static_stream_read_s16_be (tb_static_stream_ref_t stream)
read sint16-be integer
Parameters
stream the stream
Returns
the sint16-be integer
Definition at line 371 of file static_stream.c.
References tb_static_stream_t::b, tb_static_stream_t::e, and tb_static_stream_t::p.
tb_sint16_t tb_static_stream_read_s16_le (tb_static_stream_ref_t stream)
read sint16-le integer
Parameters
stream the stream
Returns
the sint16-le integer
Definition at line 393 of file static_stream.c.
References tb_static_stream_t::b, tb_static_stream_t::e, and tb_static_stream_t::p.
tb_sint32_t tb_static_stream_read_s24_be (tb_static_stream_ref_t stream)
read sint24-be integer
Parameters
stream the stream
Returns
the sint24-be integer
Definition at line 415 of file static_stream.c.
References tb_static_stream_t::b, tb_static_stream_t::e, and tb_static_stream_t::p.
tb_sint32_t tb_static_stream_read_s24_le (tb_static_stream_ref_t stream)
read sint24-le integer
Parameters
stream the stream
Returns
the sint24-le integer
Definition at line 437 of file static_stream.c.
References tb_static_stream_t::b, tb_static_stream_t::e, and tb_static_stream_t::p.
tb_sint32_t tb_static_stream_read_s32_be (tb_static_stream_ref_t stream)
read sint32-be integer
Parameters
stream the stream
Returns
the sint32-be integer
Definition at line 459 of file static_stream.c.
References tb_static_stream_t::b, tb_static_stream_t::e, and tb_static_stream_t::p.
tb_sint32_t tb_static_stream_read_s32_le (tb_static_stream_ref_t stream)
read sint32-le integer
Parameters
stream the stream
Returns
the sint32-le integer
Definition at line 481 of file static_stream.c.
References tb_static_stream_t::b, tb_static_stream_t::e, and tb_static_stream_t::p.
tb_sint64_t tb_static_stream_read_s64_be (tb_static_stream_ref_t stream)
read sint64-be integer
Parameters
stream the stream
Returns
the sint64-be integer
Definition at line 503 of file static_stream.c.
References tb_static_stream_t::b, tb_static_stream_t::e, and tb_static_stream_t::p.
tb_sint64_t tb_static_stream_read_s64_le (tb_static_stream_ref_t stream)
read sint64-le integer
Parameters
stream the stream
Returns
the sint64-le integer
Definition at line 525 of file static_stream.c.
References tb_static_stream_t::b, tb_static_stream_t::e, and tb_static_stream_t::p.
tb_sint8_t tb_static_stream_read_s8 (tb_static_stream_ref_t stream)
read sint8 integer
Parameters
stream the stream
Returns
the sint8 integer
Definition at line 352 of file static_stream.c.
References tb_static_stream_t::b, tb_static_stream_t::e, and tb_static_stream_t::p.
tb_sint32_t tb_static_stream_read_sbits32 (tb_static_stream_ref_t stream, tb_size_t nbits)
read sbits value for sint32
Parameters
stream the stream
nbits the bits count
Returns
the sbits value
Definition at line 261 of file static_stream.c.
References tb_static_stream_t::b, tb_static_stream_t::e, tb_static_stream_t::p, and tb_static_stream_skip_bits().
Referenced by tb_static_stream_peek_sbits32().
tb_uint8_t tb_static_stream_read_u1 (tb_static_stream_ref_t stream)
read ubits1 value
Parameters
stream the stream
Returns
the ubits1 value
Definition at line 321 of file static_stream.c.
References tb_static_stream_t::b, tb_static_stream_t::e, and tb_static_stream_t::p.
tb_uint16_t tb_static_stream_read_u16_be (tb_static_stream_ref_t stream)
read uint16-be integer
Parameters
stream the stream
Returns
the uint16-be integer
Definition at line 360 of file static_stream.c.
References tb_static_stream_t::b, tb_static_stream_t::e, and tb_static_stream_t::p.
tb_uint16_t tb_static_stream_read_u16_le (tb_static_stream_ref_t stream)
read uint16-le integer
Parameters
stream the stream
Returns
the uint16-le integer
Definition at line 382 of file static_stream.c.
References tb_static_stream_t::b, tb_static_stream_t::e, and tb_static_stream_t::p.
tb_uint32_t tb_static_stream_read_u24_be (tb_static_stream_ref_t stream)
read uint24-be integer
Parameters
stream the stream
Returns
the uint24-be integer
Definition at line 404 of file static_stream.c.
References tb_static_stream_t::b, tb_static_stream_t::e, and tb_static_stream_t::p.
tb_uint32_t tb_static_stream_read_u24_le (tb_static_stream_ref_t stream)
read uint24-le integer
Parameters
stream the stream
Returns
the uint24-le integer
Definition at line 426 of file static_stream.c.
References tb_static_stream_t::b, tb_static_stream_t::e, and tb_static_stream_t::p.
tb_uint32_t tb_static_stream_read_u32_be (tb_static_stream_ref_t stream)
read uint32-be integer
Parameters
stream the stream
Returns
the uint32-be integer
Definition at line 448 of file static_stream.c.
References tb_static_stream_t::b, tb_static_stream_t::e, and tb_static_stream_t::p.
tb_uint32_t tb_static_stream_read_u32_le (tb_static_stream_ref_t stream)
read uint32-le integer
Parameters
stream the stream
Returns
the uint32-le integer
Definition at line 470 of file static_stream.c.
References tb_static_stream_t::b, tb_static_stream_t::e, and tb_static_stream_t::p.
tb_uint64_t tb_static_stream_read_u64_be (tb_static_stream_ref_t stream)
read uint64-be integer
Parameters
stream the stream
Returns
the uint64-be integer
Definition at line 492 of file static_stream.c.
References tb_static_stream_t::b, tb_static_stream_t::e, and tb_static_stream_t::p.
tb_uint64_t tb_static_stream_read_u64_le (tb_static_stream_ref_t stream)
read uint64-le integer
Parameters
stream the stream
Returns
the uint64-le integer
Definition at line 514 of file static_stream.c.
References tb_static_stream_t::b, tb_static_stream_t::e, and tb_static_stream_t::p.
tb_uint8_t tb_static_stream_read_u8 (tb_static_stream_ref_t stream)
read uint8 integer
Parameters
stream the stream
Returns
the uint8 integer
Definition at line 344 of file static_stream.c.
References tb_static_stream_t::b, tb_static_stream_t::e, and tb_static_stream_t::p.
tb_uint32_t tb_static_stream_read_ubits32 (tb_static_stream_ref_t stream, tb_size_t nbits)
read ubits value for uint32
Parameters
stream the stream
nbits the bits count
Returns
the ubits value
Definition at line 247 of file static_stream.c.
References tb_static_stream_t::b, tb_static_stream_t::e, tb_static_stream_t::p, and tb_static_stream_skip_bits().
Referenced by tb_static_stream_peek_ubits32().
tb_size_t tb_static_stream_size (tb_static_stream_ref_t stream)
the stream data size
Parameters
stream the stream
Returns
the data size
Definition at line 111 of file static_stream.c.
References tb_static_stream_t::n.
tb_bool_t tb_static_stream_skip (tb_static_stream_ref_t stream, tb_size_t size)
skip the given size
Parameters
stream the stream
size the skiped size
Returns
tb_true or tb_false
Definition at line 161 of file static_stream.c.
References tb_static_stream_t::p, and tb_static_stream_sync().
Referenced by tb_static_stream_read_cstr(), tb_static_stream_read_data(), and tb_static_stream_writ_data().
tb_bool_t tb_static_stream_skip_bits (tb_static_stream_ref_t stream, tb_size_t nbits)
skip the given bits
Parameters
stream the stream
nbits the skiped bits count
Returns
tb_true or tb_false
Definition at line 178 of file static_stream.c.
References tb_static_stream_t::b, tb_static_stream_t::e, and tb_static_stream_t::p.
Referenced by tb_static_stream_read_sbits32(), tb_static_stream_read_ubits32(), tb_static_stream_writ_sbits32(), and tb_static_stream_writ_ubits32().
tb_bool_t tb_static_stream_skip_cstr (tb_static_stream_ref_t stream)
skip the given c-string
Parameters
stream the stream
Returns
tb_true or tb_false
Definition at line 195 of file static_stream.c.
References tb_static_stream_read_cstr(), and tb_static_stream_valid().
tb_bool_t tb_static_stream_sync (tb_static_stream_ref_t stream)
sync the stream position if update some bits offset
Parameters
stream the stream
Returns
tb_true or tb_false
Definition at line 65 of file static_stream.c.
References tb_static_stream_t::b, tb_static_stream_t::e, and tb_static_stream_t::p.
Referenced by tb_static_stream_left(), tb_static_stream_offset(), tb_static_stream_pos(), tb_static_stream_read_cstr(), tb_static_stream_read_data(), tb_static_stream_skip(), tb_static_stream_writ_cstr(), and tb_static_stream_writ_data().
tb_bool_t tb_static_stream_valid (tb_static_stream_ref_t stream)
the stream is valid?
Parameters
stream the stream
Returns
tb_true or tb_false
Definition at line 149 of file static_stream.c.
References tb_static_stream_t::b, tb_static_stream_t::e, and tb_static_stream_t::p.
Referenced by tb_charset_conv_bst(), and tb_static_stream_skip_cstr().
tb_char_t* tb_static_stream_writ_cstr (tb_static_stream_ref_t stream, tb_char_t const * cstr)
writ c-string
Parameters
stream the stream
cstr the c-string
Returns
the writed c-string address
Definition at line 584 of file static_stream.c.
References tb_static_stream_t::e, tb_static_stream_t::p, and tb_static_stream_sync().
tb_size_t tb_static_stream_writ_data (tb_static_stream_ref_t stream, tb_byte_t const * data, tb_size_t size)
writ data
Parameters
stream the stream
data the data
size the size
Returns
the writed data size
Definition at line 558 of file static_stream.c.
References tb_static_stream_t::e, tb_static_stream_t::p, tb_static_stream_skip(), and tb_static_stream_sync().
tb_bool_t tb_static_stream_writ_double_bbe (tb_static_stream_ref_t stream, tb_double_t val)
writ double-bbe number
Parameters
stream the stream
val the value
Returns
tb_true or tb_false
Definition at line 932 of file static_stream.c.
References tb_static_stream_t::b, tb_static_stream_t::e, and tb_static_stream_t::p.
tb_bool_t tb_static_stream_writ_double_ble (tb_static_stream_ref_t stream, tb_double_t val)
writ double-ble number
Parameters
stream the stream
val the value
Returns
tb_true or tb_false
Definition at line 921 of file static_stream.c.
References tb_static_stream_t::b, tb_static_stream_t::e, and tb_static_stream_t::p.
tb_bool_t tb_static_stream_writ_double_lbe (tb_static_stream_ref_t stream, tb_double_t val)
writ double-lbe number
Parameters
stream the stream
val the value
Returns
tb_true or tb_false
Definition at line 954 of file static_stream.c.
References tb_static_stream_t::b, tb_static_stream_t::e, and tb_static_stream_t::p.
tb_bool_t tb_static_stream_writ_double_lle (tb_static_stream_ref_t stream, tb_double_t val)
writ double-lle number
Parameters
stream the stream
val the value
Returns
tb_true or tb_false
Definition at line 943 of file static_stream.c.
References tb_static_stream_t::b, tb_static_stream_t::e, and tb_static_stream_t::p.
tb_bool_t tb_static_stream_writ_float_be (tb_static_stream_ref_t stream, tb_float_t val)
writ float-be number
Parameters
stream the stream
val the value
Returns
tb_true or tb_false
Definition at line 910 of file static_stream.c.
References tb_static_stream_t::b, tb_static_stream_t::e, and tb_static_stream_t::p.
tb_bool_t tb_static_stream_writ_float_le (tb_static_stream_ref_t stream, tb_float_t val)
writ float-le number
Parameters
stream the stream
val the value
Returns
tb_true or tb_false
Definition at line 899 of file static_stream.c.
References tb_static_stream_t::b, tb_static_stream_t::e, and tb_static_stream_t::p.
tb_bool_t tb_static_stream_writ_s16_be (tb_static_stream_ref_t stream, tb_sint16_t val)
writ sint16-be integer
Parameters
stream the stream
val the value
Returns
tb_true or tb_false
Definition at line 665 of file static_stream.c.
References tb_static_stream_t::b, tb_static_stream_t::e, and tb_static_stream_t::p.
tb_bool_t tb_static_stream_writ_s16_le (tb_static_stream_ref_t stream, tb_sint16_t val)
writ sint16-le integer
Parameters
stream the stream
val the value
Returns
tb_true or tb_false
Definition at line 688 of file static_stream.c.
References tb_static_stream_t::b, tb_static_stream_t::e, and tb_static_stream_t::p.
tb_bool_t tb_static_stream_writ_s24_be (tb_static_stream_ref_t stream, tb_sint32_t val)
writ sint24-be integer
Parameters
stream the stream
val the value
Returns
tb_true or tb_false
Definition at line 710 of file static_stream.c.
References tb_static_stream_t::b, tb_static_stream_t::e, and tb_static_stream_t::p.
tb_bool_t tb_static_stream_writ_s24_le (tb_static_stream_ref_t stream, tb_sint32_t val)
writ sint24-le integer
Parameters
stream the stream
val the value
Returns
tb_true or tb_false
Definition at line 732 of file static_stream.c.
References tb_static_stream_t::b, tb_static_stream_t::e, and tb_static_stream_t::p.
tb_bool_t tb_static_stream_writ_s32_be (tb_static_stream_ref_t stream, tb_sint32_t val)
writ sint32-be integer
Parameters
stream the stream
val the value
Returns
tb_true or tb_false
Definition at line 754 of file static_stream.c.
References tb_static_stream_t::b, tb_static_stream_t::e, and tb_static_stream_t::p.
tb_bool_t tb_static_stream_writ_s32_le (tb_static_stream_ref_t stream, tb_sint32_t val)
writ sint32-le integer
Parameters
stream the stream
val the value
Returns
tb_true or tb_false
Definition at line 776 of file static_stream.c.
References tb_static_stream_t::b, tb_static_stream_t::e, and tb_static_stream_t::p.
tb_bool_t tb_static_stream_writ_s64_be (tb_static_stream_ref_t stream, tb_sint64_t val)
writ sint64-be integer
Parameters
stream the stream
val the value
Returns
tb_true or tb_false
Definition at line 798 of file static_stream.c.
References tb_static_stream_t::b, tb_static_stream_t::e, and tb_static_stream_t::p.
tb_bool_t tb_static_stream_writ_s64_le (tb_static_stream_ref_t stream, tb_sint64_t val)
writ sint64-le integer
Parameters
stream the stream
val the value
Returns
tb_true or tb_false
Definition at line 820 of file static_stream.c.
References tb_static_stream_t::b, tb_static_stream_t::e, and tb_static_stream_t::p.
tb_bool_t tb_static_stream_writ_s8 (tb_static_stream_ref_t stream, tb_sint8_t val)
writ sint8 integer
Parameters
stream the stream
val the value
Returns
tb_true or tb_false
Definition at line 643 of file static_stream.c.
References tb_static_stream_t::b, tb_static_stream_t::e, and tb_static_stream_t::p.
tb_bool_t tb_static_stream_writ_sbits32 (tb_static_stream_ref_t stream, tb_sint32_t val, tb_size_t nbits)
writ sbits for sint32
Parameters
stream the stream
val the value
nbits the bits count
Returns
tb_true or tb_false
Definition at line 547 of file static_stream.c.
References tb_static_stream_t::b, tb_static_stream_t::e, tb_static_stream_t::p, and tb_static_stream_skip_bits().
tb_bool_t tb_static_stream_writ_u1 (tb_static_stream_ref_t stream, tb_uint8_t val)
writ ubits1 value
Parameters
stream the stream
val the value
Returns
tb_true or tb_false
Definition at line 608 of file static_stream.c.
References tb_static_stream_t::b, tb_static_stream_t::e, and tb_static_stream_t::p.
tb_bool_t tb_static_stream_writ_u16_be (tb_static_stream_ref_t stream, tb_uint16_t val)
writ uint16-be integer
Parameters
stream the stream
val the value
Returns
tb_true or tb_false
Definition at line 654 of file static_stream.c.
References tb_static_stream_t::b, tb_static_stream_t::e, and tb_static_stream_t::p.
tb_bool_t tb_static_stream_writ_u16_le (tb_static_stream_ref_t stream, tb_uint16_t val)
writ uint16-le integer
Parameters
stream the stream
val the value
Returns
tb_true or tb_false
Definition at line 677 of file static_stream.c.
References tb_static_stream_t::b, tb_static_stream_t::e, and tb_static_stream_t::p.
tb_bool_t tb_static_stream_writ_u24_be (tb_static_stream_ref_t stream, tb_uint32_t val)
writ uint24-be integer
Parameters
stream the stream
val the value
Returns
tb_true or tb_false
Definition at line 699 of file static_stream.c.
References tb_static_stream_t::b, tb_static_stream_t::e, and tb_static_stream_t::p.
tb_bool_t tb_static_stream_writ_u24_le (tb_static_stream_ref_t stream, tb_uint32_t val)
writ uint24-le integer
Parameters
stream the stream
val the value
Returns
tb_true or tb_false
Definition at line 721 of file static_stream.c.
References tb_static_stream_t::b, tb_static_stream_t::e, and tb_static_stream_t::p.
tb_bool_t tb_static_stream_writ_u32_be (tb_static_stream_ref_t stream, tb_uint32_t val)
writ uint32-be integer
Parameters
stream the stream
val the value
Returns
tb_true or tb_false
Definition at line 743 of file static_stream.c.
References tb_static_stream_t::b, tb_static_stream_t::e, and tb_static_stream_t::p.
tb_bool_t tb_static_stream_writ_u32_le (tb_static_stream_ref_t stream, tb_uint32_t val)
writ uint32-le integer
Parameters
stream the stream
val the value
Returns
tb_true or tb_false
Definition at line 765 of file static_stream.c.
References tb_static_stream_t::b, tb_static_stream_t::e, and tb_static_stream_t::p.
tb_bool_t tb_static_stream_writ_u64_be (tb_static_stream_ref_t stream, tb_uint64_t val)
writ uint64-be integer
Parameters
stream the stream
val the value
Returns
tb_true or tb_false
Definition at line 787 of file static_stream.c.
References tb_static_stream_t::b, tb_static_stream_t::e, and tb_static_stream_t::p.
tb_bool_t tb_static_stream_writ_u64_le (tb_static_stream_ref_t stream, tb_uint64_t val)
writ uint64-le integer
Parameters
stream the stream
val the value
Returns
tb_true or tb_false
Definition at line 809 of file static_stream.c.
References tb_static_stream_t::b, tb_static_stream_t::e, and tb_static_stream_t::p.
tb_bool_t tb_static_stream_writ_u8 (tb_static_stream_ref_t stream, tb_uint8_t val)
writ uint8 integer
Parameters
stream the stream
val the value
Returns
tb_true or tb_false
Definition at line 632 of file static_stream.c.
References tb_static_stream_t::b, tb_static_stream_t::e, and tb_static_stream_t::p.
tb_bool_t tb_static_stream_writ_ubits32 (tb_static_stream_ref_t stream, tb_uint32_t val, tb_size_t nbits)
writ ubits for uint32
Parameters
stream the stream
val the value
nbits the bits count
Returns
tb_true or tb_false
Definition at line 536 of file static_stream.c.
References tb_static_stream_t::b, tb_static_stream_t::e, tb_static_stream_t::p, and tb_static_stream_skip_bits().