TBOX: src/tbox/asio/aicp.h File Reference
aicp.h File Reference
Asio
#include "prefix.h"
#include "aice.h"
#include "../platform/timer.h"
#include "../container/container.h"
Macros
#define tb_aicp_post(aicp, aice) tb_aicp_post_(aicp, aice __tb_debug_vals__)
post
#define tb_aicp_post_after(aicp, delay, aice) tb_aicp_post_after_(aicp, delay, aice __tb_debug_vals__)
Functions
tb_aicp_ref_t tb_aicp (tb_noarg_t)
tb_aicp_ref_t tb_aicp_init (tb_size_t maxn)
tb_bool_t tb_aicp_exit (tb_aicp_ref_t aicp)
tb_size_t tb_aicp_maxn (tb_aicp_ref_t aicp)
tb_bool_t tb_aicp_post_ (tb_aicp_ref_t aicp, tb_aice_t const *aice __tb_debug_decl__)
tb_bool_t tb_aicp_post_after_ (tb_aicp_ref_t aicp, tb_size_t delay, tb_aice_t const *aice __tb_debug_decl__)
tb_void_t tb_aicp_loop (tb_aicp_ref_t aicp)
tb_void_t tb_aicp_loop_util (tb_aicp_ref_t aicp, tb_bool_t(*stop)(tb_cpointer_t priv), tb_cpointer_t priv)
tb_void_t tb_aicp_kill (tb_aicp_ref_t aicp)
tb_void_t tb_aicp_kill_all (tb_aicp_ref_t aicp)
tb_long_t tb_aicp_wait_all (tb_aicp_ref_t aicp, tb_long_t timeout)
tb_hong_t tb_aicp_time (tb_aicp_ref_t aicp)
Detailed Description
The Treasure Box Library
TBox is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 2.1 of the License, or (at your option) any later version.
TBox is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with TBox; If not, see http://www.gnu.org/licenses/
Copyright (C) 2009 - 2015, ruki All rights reserved.
Author
ruki
Definition in file aicp.h.
Function Documentation
tb_aicp_ref_t tb_aicp (tb_noarg_t)
the aicp instance
Returns
the aicp
Referenced by tb_async_stream_init(), tb_async_transfer_init(), and tb_transfer_pool_init().
tb_bool_t tb_aicp_exit (tb_aicp_ref_t aicp)
exit the aicp
Parameters
aicp the aicp
Returns
tb_true or tb_false
Definition at line 303 of file aicp.c.
References tb_aicp_kill(), tb_aicp_kill_all(), tb_aicp_wait_all(), tb_fixed_pool_exit(), and tb_fixed_pool_walk().
Referenced by tb_aicp_init().
tb_aicp_ref_t tb_aicp_init (tb_size_t maxn)
init the aicp
Parameters
maxn the aico maxn, using the default maxn if be zero
Returns
the aicp
Definition at line 225 of file aicp.c.
References tb_aicp_exit(), tb_fixed_pool_init(), tb_lock_profiler(), and tb_lock_profiler_register().
tb_void_t tb_aicp_kill (tb_aicp_ref_t aicp)
kill loop
Parameters
aicp the aicp
Definition at line 520 of file aicp.c.
References tb_aicp_kill_all().
Referenced by tb_aicp_exit(), and tb_aicp_loop_util().
tb_void_t tb_aicp_kill_all (tb_aicp_ref_t aicp)
kill all and cannot continue to post it, but not kill loop
Parameters
aicp the aicp
Definition at line 539 of file aicp.c.
References tb_fixed_pool_walk().
Referenced by tb_aicp_exit(), and tb_aicp_kill().
tb_void_t tb_aicp_loop (tb_aicp_ref_t aicp)
loop aicp for the external thread
tb_pointer_t tb_aicp_worker_thread(tb_pointer_t)
{
     tb_aicp_loop(aicp);
}
Parameters
aicp the aicp
Definition at line 427 of file aicp.c.
References tb_aicp_loop_util().
tb_void_t tb_aicp_loop_util (tb_aicp_ref_t aicp, tb_bool_t(*)(tb_cpointer_t priv) stop, tb_cpointer_t priv)
loop aicp util ... for the external thread
tb_bool_t tb_aicp_stop_func(tb_pointer_t)
{
    if (...) return tb_true;
    return tb_false;
}
tb_pointer_t tb_aicp_worker_thread(tb_pointer_t)
{
     tb_aicp_loop_util(aicp, stop_func, tb_null);
}
Parameters
aicp the aicp
Definition at line 431 of file aicp.c.
References tb_aice_t::aico, tb_aice_t::code, tb_aice_t::func, tb_aico_impl_t::state, tb_aice_t::state, TB_AICE_CODE_ACPT, tb_aicp_kill(), tb_cache_time_spak(), and tb_state_cstr().
Referenced by tb_aicp_loop().
tb_size_t tb_aicp_maxn (tb_aicp_ref_t aicp)
the aico maxn
Parameters
aicp the aicp
Returns
the aico maxn
Definition at line 352 of file aicp.c.
Referenced by tb_transfer_pool_init().
tb_bool_t tb_aicp_post_ (tb_aicp_ref_t aicp, tb_aice_t const *aice __tb_debug_decl__)
post the aice
Parameters
aicp the aicp
aice the aice
Returns
tb_true or tb_false
Definition at line 361 of file aicp.c.
References tb_aice_t::aico, tb_aice_t::code, tb_aico_impl_t::state, tb_aico_type(), and tb_state_cstr().
Referenced by tb_aico_acpt_(), tb_aico_clos_(), tb_aico_conn_(), tb_aico_fsync_(), tb_aico_read_(), tb_aico_readv_(), tb_aico_recv_(), tb_aico_recvv_(), tb_aico_send_(), tb_aico_sendf_(), tb_aico_sendv_(), tb_aico_task_run_(), tb_aico_urecv_(), tb_aico_urecvv_(), tb_aico_usend_(), tb_aico_usendv_(), tb_aico_writ_(), tb_aico_writv_(), and tb_aicp_post_after_().
tb_bool_t tb_aicp_post_after_ (tb_aicp_ref_t aicp, tb_size_t delay, tb_aice_t const *aice __tb_debug_decl__)
post the aice
Parameters
aicp the aicp
delay the delay time, ms
aice the aice
Returns
tb_true or tb_false
Definition at line 400 of file aicp.c.
References tb_aice_t::aico, tb_aico_task_run_(), and tb_aicp_post_().
Referenced by tb_aico_acpt_after_(), tb_aico_clos_after_(), tb_aico_conn_after_(), tb_aico_fsync_after_(), tb_aico_read_after_(), tb_aico_readv_after_(), tb_aico_recv_after_(), tb_aico_recvv_after_(), tb_aico_send_after_(), tb_aico_sendf_after_(), tb_aico_sendv_after_(), tb_aico_urecv_after_(), tb_aico_urecvv_after_(), tb_aico_usend_after_(), tb_aico_usendv_after_(), tb_aico_writ_after_(), and tb_aico_writv_after_().
tb_hong_t tb_aicp_time (tb_aicp_ref_t aicp)
the spak time
Parameters
aicp the aicp
Returns
the time
Definition at line 592 of file aicp.c.
References tb_cache_time_mclock().
Referenced by tb_async_transfer_open(), and tb_async_transfer_resume().
tb_long_t tb_aicp_wait_all (tb_aicp_ref_t aicp, tb_long_t timeout)
wait all exiting
Parameters
aicp the aicp
timeout the timeout
Returns
ok: > 0, timeout: 0, failed: -1
Definition at line 556 of file aicp.c.
References tb_cache_time_spak(), and tb_fixed_pool_size().
Referenced by tb_aicp_exit().