TBOX: src/stream/astream.h File Reference
astream.h File Reference
Stream
#include "prefix.h"
#include "../asio/asio.h"
#include "../libc/libc.h"
#include "../network/url.h"
#include "../memory/memory.h"
Data Structures
struct tb_astream_oread_t
the astream open and read type
struct tb_astream_owrit_t
the astream open and writ type
struct tb_astream_oseek_t
the astream open and seek type
struct tb_astream_cwrit_t
the astream cache and writ type
struct tb_astream_csync_t
the astream cache and sync type
struct tb_astream_sread_t
the astream sync and read type
struct tb_astream_sseek_t
the astream sync and seek type
struct tb_astream_t
the asio stream type
Macros
#define tb_astream_open(astream, func, priv) tb_astream_open_impl(astream, func, priv __tb_debug_vals__)
open
#define tb_astream_read(astream, size, func, priv) tb_astream_read_impl(astream, size, func, priv __tb_debug_vals__)
read
#define tb_astream_writ(astream, data, size, func, priv) tb_astream_writ_impl(astream, data, size, func, priv __tb_debug_vals__)
writ
#define tb_astream_seek(astream, offset, func, priv) tb_astream_seek_impl(astream, offset, func, priv __tb_debug_vals__)
seek
#define tb_astream_sync(astream, bclosing, func, priv) tb_astream_sync_impl(astream, bclosing, func, priv __tb_debug_vals__)
sync
#define tb_astream_task(astream, delay, func, priv) tb_astream_task_impl(astream, delay, func, priv __tb_debug_vals__)
task
#define tb_astream_oread(astream, size, func, priv) tb_astream_oread_impl(astream, size, func, priv __tb_debug_vals__)
open and read
#define tb_astream_owrit(astream, data, size, func, priv) tb_astream_owrit_impl(astream, data, size, func, priv __tb_debug_vals__)
open and writ
#define tb_astream_oseek(astream, offset, func, priv) tb_astream_oseek_impl(astream, offset, func, priv __tb_debug_vals__)
open and seek
#define tb_astream_read_after(astream, delay, size, func, priv) tb_astream_read_after_impl(astream, delay, size, func, priv __tb_debug_vals__)
read after delay
#define tb_astream_writ_after(astream, delay, data, size, func, priv) tb_astream_writ_after_impl(astream, delay, data, size, func, priv __tb_debug_vals__)
writ after delay
Typedefs
typedef tb_bool_t(* tb_astream_open_func_t)(struct __tb_astream_t *astream, tb_size_t state, tb_pointer_t priv)
typedef tb_bool_t(* tb_astream_read_func_t)(struct __tb_astream_t *astream, tb_size_t state, tb_byte_t const *data, tb_size_t real, tb_size_t size, tb_pointer_t priv)
typedef tb_bool_t(* tb_astream_writ_func_t)(struct __tb_astream_t *astream, tb_size_t state, tb_byte_t const *data, tb_size_t real, tb_size_t size, tb_pointer_t priv)
typedef tb_bool_t(* tb_astream_seek_func_t)(struct __tb_astream_t *astream, tb_size_t state, tb_hize_t offset, tb_pointer_t priv)
typedef tb_bool_t(* tb_astream_sync_func_t)(struct __tb_astream_t *astream, tb_size_t state, tb_bool_t bclosing, tb_pointer_t priv)
typedef tb_bool_t(* tb_astream_task_func_t)(struct __tb_astream_t *astream, tb_size_t state, tb_pointer_t priv)
Functions
tb_astream_t * tb_astream_init_data (tb_aicp_t *aicp)
tb_astream_t * tb_astream_init_file (tb_aicp_t *aicp)
tb_astream_t * tb_astream_init_sock (tb_aicp_t *aicp)
tb_astream_t * tb_astream_init_http (tb_aicp_t *aicp)
tb_astream_t * tb_astream_init_filter (tb_aicp_t *aicp)
tb_void_t tb_astream_clos (tb_astream_t *astream, tb_bool_t bcalling)
tb_void_t tb_astream_exit (tb_astream_t *astream, tb_bool_t bcalling)
tb_astream_t * tb_astream_init_from_url (tb_aicp_t *aicp, tb_char_t const *url)
tb_astream_t * tb_astream_init_from_data (tb_aicp_t *aicp, tb_byte_t const *data, tb_size_t size)
tb_astream_t * tb_astream_init_from_file (tb_aicp_t *aicp, tb_char_t const *path, tb_size_t mode)
tb_astream_t * tb_astream_init_from_sock (tb_aicp_t *aicp, tb_char_t const *host, tb_size_t port, tb_size_t type, tb_bool_t bssl)
tb_astream_t * tb_astream_init_from_http (tb_aicp_t *aicp, tb_char_t const *host, tb_size_t port, tb_char_t const *path, tb_bool_t bssl)
tb_astream_t * tb_astream_init_filter_from_null (tb_astream_t *astream)
tb_astream_t * tb_astream_init_filter_from_zip (tb_astream_t *astream, tb_size_t algo, tb_size_t action)
tb_astream_t * tb_astream_init_filter_from_cache (tb_astream_t *astream, tb_size_t size)
tb_astream_t * tb_astream_init_filter_from_charset (tb_astream_t *astream, tb_size_t fr, tb_size_t to)
tb_astream_t * tb_astream_init_filter_from_chunked (tb_astream_t *astream, tb_bool_t dechunked)
tb_bool_t tb_astream_open_try (tb_astream_t *astream)
tb_bool_t tb_astream_open_impl (tb_astream_t *astream, tb_astream_open_func_t func, tb_pointer_t priv __tb_debug_decl__)
tb_bool_t tb_astream_read_impl (tb_astream_t *astream, tb_size_t size, tb_astream_read_func_t func, tb_pointer_t priv __tb_debug_decl__)
tb_bool_t tb_astream_writ_impl (tb_astream_t *astream, tb_byte_t const *data, tb_size_t size, tb_astream_writ_func_t func, tb_pointer_t priv __tb_debug_decl__)
tb_bool_t tb_astream_seek_impl (tb_astream_t *astream, tb_hize_t offset, tb_astream_seek_func_t func, tb_pointer_t priv __tb_debug_decl__)
tb_bool_t tb_astream_sync_impl (tb_astream_t *astream, tb_bool_t bclosing, tb_astream_sync_func_t func, tb_pointer_t priv __tb_debug_decl__)
tb_bool_t tb_astream_task_impl (tb_astream_t *astream, tb_size_t delay, tb_astream_task_func_t func, tb_pointer_t priv __tb_debug_decl__)
tb_bool_t tb_astream_oread_impl (tb_astream_t *astream, tb_size_t size, tb_astream_read_func_t func, tb_pointer_t priv __tb_debug_decl__)
tb_bool_t tb_astream_owrit_impl (tb_astream_t *astream, tb_byte_t const *data, tb_size_t size, tb_astream_writ_func_t func, tb_pointer_t priv __tb_debug_decl__)
tb_bool_t tb_astream_oseek_impl (tb_astream_t *astream, tb_hize_t offset, tb_astream_seek_func_t func, tb_pointer_t priv __tb_debug_decl__)
tb_bool_t tb_astream_read_after_impl (tb_astream_t *astream, tb_size_t delay, tb_size_t size, tb_astream_read_func_t func, tb_pointer_t priv __tb_debug_decl__)
tb_bool_t tb_astream_writ_after_impl (tb_astream_t *astream, tb_size_t delay, tb_byte_t const *data, tb_size_t size, tb_astream_writ_func_t func, tb_pointer_t priv __tb_debug_decl__)
tb_aicp_t * tb_astream_aicp (tb_astream_t *astream)
tb_char_t const * tb_astream_func (tb_astream_t *astream)
tb_char_t const * tb_astream_file (tb_astream_t *astream)
tb_size_t tb_astream_line (tb_astream_t *astream)
Detailed Description
The Treasure Box Library
TBox is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 2.1 of the License, or (at your option) any later version.
TBox is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with TBox; If not, see http://www.gnu.org/licenses/
Copyright (C) 2009 - 2015, ruki All rights reserved.
Author
ruki
Definition in file astream.h.
Typedef Documentation
typedef tb_bool_t(* tb_astream_open_func_t)(struct __tb_astream_t *astream, tb_size_t state, tb_pointer_t priv)
the astream open func type
Parameters
astream the astream
state the state
priv the func private data
Returns
tb_true: ok, tb_false: error, but not break aicp
Definition at line 88 of file astream.h.
typedef tb_bool_t(* tb_astream_read_func_t)(struct __tb_astream_t *astream, tb_size_t state, tb_byte_t const *data, tb_size_t real, tb_size_t size, tb_pointer_t priv)
the astream read func type
Parameters
astream the astream
state the state
data the readed data
real the real size, maybe zero
size the need size
priv the func private data
Returns
tb_true: ok and continue it if need, tb_false: break it, but not break aicp
Definition at line 101 of file astream.h.
typedef tb_bool_t(* tb_astream_seek_func_t)(struct __tb_astream_t *astream, tb_size_t state, tb_hize_t offset, tb_pointer_t priv)
the astream seek func type
Parameters
astream the astream
state the state
offset the real offset
priv the func private data
Returns
tb_true: ok, tb_false: error, but not break aicp
Definition at line 125 of file astream.h.
typedef tb_bool_t(* tb_astream_sync_func_t)(struct __tb_astream_t *astream, tb_size_t state, tb_bool_t bclosing, tb_pointer_t priv)
the astream sync func type
Parameters
astream the astream
state the state
bclosing is closing?
priv the func private data
Returns
tb_true: ok, tb_false: error, but not break aicp
Definition at line 136 of file astream.h.
typedef tb_bool_t(* tb_astream_task_func_t)(struct __tb_astream_t *astream, tb_size_t state, tb_pointer_t priv)
the astream task func type
Parameters
astream the astream
state the state
priv the func private data
Returns
tb_true: ok, tb_false: error, but not break aicp
Definition at line 146 of file astream.h.
typedef tb_bool_t(* tb_astream_writ_func_t)(struct __tb_astream_t *astream, tb_size_t state, tb_byte_t const *data, tb_size_t real, tb_size_t size, tb_pointer_t priv)
the astream writ func type
Parameters
astream the astream
state the state
data the writed data
real the real size, maybe zero
size the need size
priv the func private data
Returns
tb_true: ok and continue it if need, tb_false: break it, but not break aicp
Definition at line 114 of file astream.h.
Function Documentation
tb_aicp_t* tb_astream_aicp (tb_astream_t * astream)
the stream aicp
Parameters
astream the stream
Returns
the stream aicp
Definition at line 755 of file astream.c.
References tb_astream_t::aicp.
Referenced by tb_astream_init_filter_from_cache(), tb_astream_init_filter_from_charset(), tb_astream_init_filter_from_chunked(), tb_astream_init_filter_from_null(), tb_astream_init_filter_from_zip(), tb_tstream_init_au(), tb_tstream_init_da(), tb_tstream_init_ua(), tb_tstream_open(), and tb_tstream_resume().
tb_void_t tb_astream_clos (tb_astream_t * astream, tb_bool_t bcalling)
close stream, will block it if be pending
Parameters
astream the stream
bcalling close it from the calling callback?
Definition at line 439 of file astream.c.
References tb_astream_t::base, tb_stream_t::bopened, tb_astream_t::clos, tb_astream_t::file, tb_astream_t::func, tb_astream_t::line, tb_stream_kill(), and tb_astream_t::wcache_data.
Referenced by tb_astream_exit().
tb_void_t tb_astream_exit (tb_astream_t * astream, tb_bool_t bcalling)
exit stream, will block it if be pending
Parameters
astream the stream
bcalling exit it from the calling callback?
Definition at line 469 of file astream.c.
References tb_astream_t::base, tb_astream_t::exit, tb_astream_t::rcache_data, tb_astream_clos(), tb_stream_t::url, and tb_astream_t::wcache_data.
Referenced by tb_astream_init_data(), tb_astream_init_file(), tb_astream_init_filter(), tb_astream_init_filter_from_cache(), tb_astream_init_filter_from_charset(), tb_astream_init_filter_from_chunked(), tb_astream_init_filter_from_null(), tb_astream_init_filter_from_zip(), tb_astream_init_from_data(), tb_astream_init_from_file(), tb_astream_init_from_http(), tb_astream_init_from_sock(), tb_astream_init_from_url(), tb_astream_init_http(), tb_astream_init_sock(), tb_tstream_exit(), tb_tstream_init_au(), tb_tstream_init_da(), tb_tstream_init_du(), tb_tstream_init_ua(), and tb_tstream_init_uu().
tb_char_t const* tb_astream_file (tb_astream_t * astream)
the stream file name from post for debug
Parameters
astream the stream
Returns
the stream file name
Definition at line 772 of file astream.c.
References tb_astream_t::file.
tb_char_t const* tb_astream_func (tb_astream_t * astream)
the stream func name from post for debug
Parameters
astream the stream
Returns
the stream func name
Definition at line 764 of file astream.c.
References tb_astream_t::func.
tb_astream_t* tb_astream_init_data (tb_aicp_t * aicp)
init data stream
Parameters
aicp the aicp
Returns
the stream
Definition at line 551 of file data.c.
References tb_astream_exit().
Referenced by tb_astream_init_from_data(), and tb_astream_init_from_url().
tb_astream_t* tb_astream_init_file (tb_aicp_t * aicp)
init file stream
Parameters
aicp the aicp
Returns
the stream
Definition at line 453 of file file.c.
References tb_astream_exit(), TB_FILE_MODE_BINARY, and TB_FILE_MODE_RO.
Referenced by tb_astream_init_from_file(), and tb_astream_init_from_url().
tb_astream_t* tb_astream_init_filter (tb_aicp_t * aicp)
init filter stream
Parameters
aicp the aicp
Returns
the stream
Definition at line 552 of file filter.c.
References tb_astream_exit().
Referenced by tb_astream_init_filter_from_cache(), tb_astream_init_filter_from_charset(), tb_astream_init_filter_from_chunked(), tb_astream_init_filter_from_null(), and tb_astream_init_filter_from_zip().
tb_astream_t* tb_astream_init_filter_from_cache (tb_astream_t * astream, tb_size_t size)
init filter stream from cache
Parameters
astream the stream
size the initial cache size, using the default size if be zero
Returns
the stream
Definition at line 630 of file filter.c.
References tb_astream_aicp(), tb_astream_exit(), tb_astream_init_filter(), tb_filter_init_from_cache(), and tb_stream_ctrl().
tb_astream_t* tb_astream_init_filter_from_charset (tb_astream_t * astream, tb_size_t fr, tb_size_t to)
init filter stream from charset
Parameters
astream the stream
fr the from charset
to the to charset
Returns
the stream
Definition at line 657 of file filter.c.
References tb_astream_aicp(), tb_astream_exit(), tb_astream_init_filter(), tb_filter_init_from_charset(), and tb_stream_ctrl().
tb_astream_t* tb_astream_init_filter_from_chunked (tb_astream_t * astream, tb_bool_t dechunked)
init filter stream from chunked
Parameters
astream the stream
dechunked decode the chunked data?
Returns
the stream
Definition at line 684 of file filter.c.
References tb_astream_aicp(), tb_astream_exit(), tb_astream_init_filter(), tb_filter_init_from_chunked(), and tb_stream_ctrl().
tb_astream_t* tb_astream_init_filter_from_null (tb_astream_t * astream)
init filter stream from null
Parameters
astream the stream
Returns
the stream
Definition at line 580 of file filter.c.
References tb_astream_aicp(), tb_astream_exit(), tb_astream_init_filter(), and tb_stream_ctrl().
tb_astream_t* tb_astream_init_filter_from_zip (tb_astream_t * astream, tb_size_t algo, tb_size_t action)
init filter stream from zip
Parameters
astream the stream
algo the zip algorithm
action the zip action
Returns
the stream
Definition at line 603 of file filter.c.
References tb_astream_aicp(), tb_astream_exit(), tb_astream_init_filter(), tb_filter_init_from_zip(), and tb_stream_ctrl().
tb_astream_t* tb_astream_init_from_data (tb_aicp_t * aicp, tb_byte_t const * data, tb_size_t size)
init stream from data
Parameters
aicp the aicp
data the data
size the size
Returns
the stream
Definition at line 579 of file data.c.
References tb_astream_exit(), tb_astream_init_data(), and tb_stream_ctrl().
Referenced by tb_tstream_init_da(), and tb_tstream_init_du().
tb_astream_t* tb_astream_init_from_file (tb_aicp_t * aicp, tb_char_t const * path, tb_size_t mode)
init stream from file
Parameters
aicp the aicp
path the file path
mode the file mode, using the default ro mode if zero
Returns
the stream
Definition at line 482 of file file.c.
References tb_astream_exit(), tb_astream_init_file(), and tb_stream_ctrl().
tb_astream_t* tb_astream_init_from_http (tb_aicp_t * aicp, tb_char_t const * host, tb_size_t port, tb_char_t const * path, tb_bool_t bssl)
init stream from http or https
Parameters
aicp the aicp
host the host
port the port
path the path
bssl enable ssl?
Returns
the stream
Definition at line 711 of file http.c.
References tb_astream_exit(), tb_astream_init_http(), and tb_stream_ctrl().
tb_astream_t* tb_astream_init_from_sock (tb_aicp_t * aicp, tb_char_t const * host, tb_size_t port, tb_size_t type, tb_bool_t bssl)
init stream from sock
Parameters
aicp the aicp
host the host
port the port
type the socket type, tcp or udp
bssl enable ssl?
Returns
the stream
Definition at line 1008 of file sock.c.
References tb_astream_exit(), tb_astream_init_sock(), and tb_stream_ctrl().
tb_astream_t* tb_astream_init_from_url (tb_aicp_t * aicp, tb_char_t const * url)
init stream from url
Parameters
aicp the aicp
url the url
data://base64
file://path or unix path: e.g. /root/xxxx/file
sock://host:port?tcp=
sock://host:port?udp=
socks://host:port
http://host:port/path?arg0=&arg1=...
https://host:port/path?arg0=&arg1=...
Returns
the stream
Definition at line 390 of file astream.c.
References tb_astream_exit(), tb_astream_init_data(), tb_astream_init_file(), tb_astream_init_http(), tb_astream_init_sock(), and tb_stream_ctrl().
Referenced by tb_tstream_init_au(), tb_tstream_init_du(), tb_tstream_init_ua(), and tb_tstream_init_uu().
tb_astream_t* tb_astream_init_http (tb_aicp_t * aicp)
init http stream
Parameters
aicp the aicp
Returns
the stream
Definition at line 680 of file http.c.
References tb_astream_exit().
Referenced by tb_astream_init_from_http(), and tb_astream_init_from_url().
tb_astream_t* tb_astream_init_sock (tb_aicp_t * aicp)
init sock stream
Parameters
aicp the aicp
Returns
the stream
Definition at line 978 of file sock.c.
References tb_astream_exit().
Referenced by tb_astream_init_from_sock(), and tb_astream_init_from_url().
tb_size_t tb_astream_line (tb_astream_t * astream)
the stream line number from post for debug
Parameters
astream the stream
Returns
the stream line number
Definition at line 780 of file astream.c.
References tb_astream_t::line.
tb_bool_t tb_astream_open_impl (tb_astream_t * astream, tb_astream_open_func_t func, tb_pointer_t priv __tb_debug_decl__)
open the stream
Parameters
astream the stream
func the func
priv the func data
Returns
tb_true or tb_false
Definition at line 520 of file astream.c.
References tb_astream_t::base, tb_stream_t::bopened, tb_stream_t::bstoped, tb_astream_t::file, tb_astream_t::func, tb_astream_t::line, and tb_astream_t::open.
Referenced by tb_astream_oread_impl(), tb_astream_oseek_impl(), and tb_astream_owrit_impl().
tb_bool_t tb_astream_open_try (tb_astream_t * astream)
try to open the stream for stream: file, filter, ...
Parameters
astream the stream
Returns
tb_true or tb_false
Definition at line 499 of file astream.c.
References tb_astream_t::base, tb_stream_t::bopened, tb_stream_t::bstoped, and tb_astream_t::open.
tb_bool_t tb_astream_oread_impl (tb_astream_t * astream, tb_size_t size, tb_astream_read_func_t func, tb_pointer_t priv __tb_debug_decl__)
open and read the stream, open it first if not opened
Parameters
astream the stream
size the read size, using the default size if be zero
func the func
priv the func data
Returns
tb_true or tb_false
Definition at line 652 of file astream.c.
References tb_astream_t::base, tb_stream_t::bopened, tb_astream_oread_t::func, tb_astream_t::open, tb_astream_t::open_and, tb_astream_oread_t::priv, tb_astream_oread_t::size, tb_astream_open_impl(), and tb_astream_read_impl().
tb_bool_t tb_astream_oseek_impl (tb_astream_t * astream, tb_hize_t offset, tb_astream_seek_func_t func, tb_pointer_t priv __tb_debug_decl__)
open and seek the stream, open it first if not opened
Parameters
astream the stream
offset the offset
func the func
priv the func data
Returns
tb_true or tb_false
Definition at line 689 of file astream.c.
References tb_astream_t::base, tb_stream_t::bopened, tb_astream_oseek_t::func, tb_astream_oseek_t::offset, tb_astream_t::open, tb_astream_t::open_and, tb_astream_oseek_t::priv, tb_astream_open_impl(), and tb_astream_seek_impl().
tb_bool_t tb_astream_owrit_impl (tb_astream_t * astream, tb_byte_t const * data, tb_size_t size, tb_astream_writ_func_t func, tb_pointer_t priv __tb_debug_decl__)
open and writ the stream, open it first if not opened
Parameters
astream the stream
data the data
size the size
func the func
priv the func data
Returns
tb_true or tb_false
Definition at line 670 of file astream.c.
References tb_astream_t::base, tb_stream_t::bopened, tb_astream_owrit_t::data, tb_astream_owrit_t::func, tb_astream_t::open, tb_astream_t::open_and, tb_astream_owrit_t::priv, tb_astream_owrit_t::size, tb_astream_open_impl(), and tb_astream_writ_impl().
tb_bool_t tb_astream_read_after_impl (tb_astream_t * astream, tb_size_t delay, tb_size_t size, tb_astream_read_func_t func, tb_pointer_t priv __tb_debug_decl__)
read the stream after the delay time
Parameters
astream the stream
delay the delay time, ms
size the read size, using the default size if be zero
func the func
priv the func data
Returns
tb_true or tb_false
Definition at line 707 of file astream.c.
References tb_astream_t::base, tb_stream_t::bopened, tb_stream_t::bstoped, tb_astream_t::file, tb_astream_oread_t::func, tb_astream_t::func, tb_astream_t::line, tb_astream_oread_t::priv, tb_astream_oread_t::size, tb_astream_t::sync_and, tb_astream_sync_impl(), tb_astream_t::wcache_data, and tb_astream_t::wcache_maxn.
Referenced by tb_astream_read_impl().
tb_bool_t tb_astream_read_impl (tb_astream_t * astream, tb_size_t size, tb_astream_read_func_t func, tb_pointer_t priv __tb_debug_decl__)
read the stream
Parameters
astream the stream
size the read size, using the default size if be zero
func the func
priv the func data
Returns
tb_true or tb_false
Definition at line 548 of file astream.c.
References tb_astream_read_after_impl().
Referenced by tb_astream_oread_impl().
tb_bool_t tb_astream_seek_impl (tb_astream_t * astream, tb_hize_t offset, tb_astream_seek_func_t func, tb_pointer_t priv __tb_debug_decl__)
seek the stream
Parameters
astream the stream
offset the offset
func the func
priv the func data
Returns
tb_true or tb_false
Definition at line 558 of file astream.c.
References tb_astream_t::base, tb_stream_t::bopened, tb_stream_t::bstoped, tb_astream_t::file, tb_astream_oseek_t::func, tb_astream_t::func, tb_astream_t::line, tb_astream_oseek_t::offset, tb_astream_oseek_t::priv, tb_astream_t::sync_and, tb_astream_sync_impl(), tb_stream_offset(), tb_astream_t::wcache_data, and tb_astream_t::wcache_maxn.
Referenced by tb_astream_oseek_impl().
tb_bool_t tb_astream_sync_impl (tb_astream_t * astream, tb_bool_t bclosing, tb_astream_sync_func_t func, tb_pointer_t priv __tb_debug_decl__)
sync the stream
Parameters
astream the stream
bclosing sync the tail data for closing
func the func
priv the func data
Returns
tb_true or tb_false
Definition at line 594 of file astream.c.
References tb_astream_t::base, tb_astream_csync_t::bclosing, tb_stream_t::bopened, tb_stream_t::bstoped, tb_astream_t::file, tb_astream_csync_t::func, tb_astream_t::func, tb_astream_t::line, tb_astream_t::wcache_and, tb_astream_t::wcache_data, and tb_astream_t::wcache_maxn.
Referenced by tb_astream_read_after_impl(), and tb_astream_seek_impl().
tb_bool_t tb_astream_task_impl (tb_astream_t * astream, tb_size_t delay, tb_astream_task_func_t func, tb_pointer_t priv __tb_debug_decl__)
task the stream
Parameters
astream the stream
delay the delay time, ms
func the func
priv the func data
Returns
tb_true or tb_false
Definition at line 633 of file astream.c.
References tb_astream_t::base, tb_stream_t::bopened, tb_stream_t::bstoped, tb_astream_t::file, tb_astream_t::func, tb_astream_t::line, and tb_astream_t::task.
tb_bool_t tb_astream_writ_after_impl (tb_astream_t * astream, tb_size_t delay, tb_byte_t const * data, tb_size_t size, tb_astream_writ_func_t func, tb_pointer_t priv __tb_debug_decl__)
writ the stream after the delay time
Parameters
astream the stream
delay the delay time, ms
data the data
size the size
func the func
priv the func data
Returns
tb_true or tb_false
Definition at line 736 of file astream.c.
References tb_astream_t::base, tb_stream_t::bopened, tb_stream_t::bstoped, tb_astream_t::file, tb_astream_t::func, and tb_astream_t::line.
Referenced by tb_astream_writ_impl().
tb_bool_t tb_astream_writ_impl (tb_astream_t * astream, tb_byte_t const * data, tb_size_t size, tb_astream_writ_func_t func, tb_pointer_t priv __tb_debug_decl__)
writ the stream
Parameters
astream the stream
data the data
size the size
func the func
priv the func data
Returns
tb_true or tb_false
Definition at line 553 of file astream.c.
References tb_astream_writ_after_impl().
Referenced by tb_astream_owrit_impl().