TBOX: src/platform/ctime.c File Reference
ctime.c File Reference
Platform
#include "ctime.h"
#include "time.h"
#include "atomic64.h"
#include "../libc/libc.h"
Functions
tb_hong_t tb_ctime_spak (tb_noarg_t)
tb_hong_t tb_ctime_time (tb_noarg_t)
Detailed Description
The Treasure Box Library
TBox is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 2.1 of the License, or (at your option) any later version.
TBox is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with TBox; If not, see http://www.gnu.org/licenses/
Copyright (C) 2009 - 2015, ruki All rights reserved.
Author
ruki
Definition in file ctime.c.
Function Documentation
tb_hong_t tb_ctime_spak (tb_noarg_t)
spak ctime
update the cached time for the external loop thread
Returns
the old ctime value
Definition at line 43 of file ctime.c.
References tb_timeval_t::tv_sec.
Referenced by tb_ltimer_loop(), and tb_timer_loop().
tb_hong_t tb_ctime_time (tb_noarg_t)
the time as the number of ms since the epoch
cache time, lower accuracy and faster
Returns
the now ctime value
Definition at line 55 of file ctime.c.
Referenced by tb_aico_task_run_impl(), and tb_aicp_time().