TBOX: src/object/string.c File Reference
string.c File Reference
Object
#include "object.h"
#include "../string/string.h"
Macros
#define TB_TRACE_MODULE_NAME "object_string"
#define TB_TRACE_MODULE_DEBUG (0)
#define TB_STRING_SCACHE_SIZE (64)
Functions
tb_object_t * tb_string_init_from_cstr (tb_char_t const *cstr)
tb_object_t * tb_string_init_from_pstr (tb_pstring_t *pstr)
tb_char_t const * tb_string_cstr (tb_object_t *object)
tb_size_t tb_string_cstr_set (tb_object_t *object, tb_char_t const *cstr)
tb_size_t tb_string_size (tb_object_t *object)
Detailed Description
The Treasure Box Library
TBox is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 2.1 of the License, or (at your option) any later version.
TBox is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with TBox; If not, see http://www.gnu.org/licenses/
Copyright (C) 2009 - 2015, ruki All rights reserved.
Author
ruki
Definition in file string.c.
Function Documentation
tb_char_t const* tb_string_cstr (tb_object_t * string)
the c-string
Parameters
string the string object
Returns
the c-string
Definition at line 188 of file string.c.
References tb_pstring_cstr().
Referenced by tb_option_item_cstr().
tb_size_t tb_string_cstr_set (tb_object_t * string, tb_char_t const * cstr)
set the c-string
Parameters
string the string object
cstr the c-string
Returns
the string size
Definition at line 197 of file string.c.
References tb_pstring_clear(), tb_pstring_cstrncpy(), tb_pstring_size(), tb_scache_del(), and tb_scache_put().
tb_object_t* tb_string_init_from_cstr (tb_char_t const * cstr)
init string from c-string
Parameters
cstr the c-string
Returns
the string object
Definition at line 119 of file string.c.
References tb_pstring_cstrncpy(), tb_pstring_init(), and tb_scache_put().
Referenced by tb_option_done().
tb_object_t* tb_string_init_from_pstr (tb_pstring_t * pstr)
init string from pstring
Parameters
pstr the pstring
Returns
the string object
Definition at line 155 of file string.c.
References tb_pstring_cstr(), tb_pstring_init(), tb_pstring_size(), tb_pstring_strcpy(), and tb_scache_put().
tb_size_t tb_string_size (tb_object_t * string)
the string size
Parameters
string the string object
Returns
the string size
Definition at line 248 of file string.c.
References tb_pstring_size().
Referenced by tb_option_item_cstr().