TBOX: src/memory/rpool.c File Reference
rpool.c File Reference
Memory
#include "rpool.h"
#include "fpool.h"
#include "malloc.h"
#include "../libc/libc.h"
#include "../math/math.h"
#include "../utils/utils.h"
#include "../platform/platform.h"
Macros
#define TB_RPOOL_CHUNK_GROW (8)
Functions
tb_handle_t tb_rpool_init (tb_size_t grow, tb_size_t step, tb_size_t align)
tb_void_t tb_rpool_exit (tb_handle_t handle)
tb_void_t tb_rpool_clear (tb_handle_t handle)
tb_size_t tb_rpool_size (tb_handle_t handle)
tb_pointer_t tb_rpool_malloc (tb_handle_t handle)
tb_pointer_t tb_rpool_malloc0 (tb_handle_t handle)
tb_bool_t tb_rpool_free (tb_handle_t handle, tb_pointer_t data)
tb_pointer_t tb_rpool_memdup (tb_handle_t handle, tb_cpointer_t data)
tb_void_t tb_rpool_walk (tb_handle_t handle, tb_bool_t(*func)(tb_pointer_t item, tb_pointer_t data), tb_pointer_t data)
tb_void_t tb_rpool_dump (tb_handle_t handle)
Detailed Description
The Treasure Box Library
TBox is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 2.1 of the License, or (at your option) any later version.
TBox is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with TBox; If not, see http://www.gnu.org/licenses/
Copyright (C) 2009 - 2015, ruki All rights reserved.
Author
ruki
Definition in file rpool.c.
Function Documentation
tb_void_t tb_rpool_clear (tb_handle_t handle)
clear regular pool
Parameters
handle the pool handle
Definition at line 206 of file rpool.c.
References tb_fpool_clear().
Referenced by tb_aiop_cler(), tb_dlist_clear(), tb_ltimer_clear(), tb_rpool_exit(), tb_slist_clear(), and tb_timer_clear().
tb_void_t tb_rpool_dump (tb_handle_t handle)
dump regular pool
Parameters
handle the pool handle
Definition at line 484 of file rpool.c.
References tb_fpool_dump().
tb_void_t tb_rpool_exit (tb_handle_t handle)
exit regular pool
Parameters
handle the pool handle
Definition at line 177 of file rpool.c.
References tb_fpool_exit(), and tb_rpool_clear().
Referenced by tb_aicp_exit(), tb_aiop_exit(), tb_dlist_exit(), tb_ltimer_exit(), tb_mstream_exit(), tb_rpool_init(), tb_slist_exit(), and tb_timer_exit().
tb_bool_t tb_rpool_free (tb_handle_t handle, tb_pointer_t data)
free regular pool data
Parameters
handle the pool handle
data the pool item data
Returns
tb_true or tb_false
Definition at line 381 of file rpool.c.
References tb_fpool_free().
Referenced by tb_dlist_remove(), tb_dlist_walk(), tb_ltimer_task_add_at(), tb_ltimer_task_del(), tb_ltimer_task_run_at(), tb_slist_remove_next(), tb_slist_walk(), tb_timer_spak(), and tb_timer_task_del().
tb_handle_t tb_rpool_init (tb_size_t grow, tb_size_t step, tb_size_t align)
init regular pool
Parameters
grow the grow
step the step
align the align
Returns
the pool handle
Definition at line 133 of file rpool.c.
References tb_rpool_exit().
Referenced by tb_aicp_init(), tb_aiop_init(), tb_dlist_init(), tb_ltimer_init(), tb_mstream_init(), tb_slist_init(), and tb_timer_init().
tb_pointer_t tb_rpool_malloc (tb_handle_t handle)
malloc regular pool data
Parameters
handle the pool handle
Returns
the data pointer
Definition at line 245 of file rpool.c.
References tb_fpool_exit(), tb_fpool_init(), and tb_fpool_malloc().
Referenced by tb_dlist_insert_prev(), tb_rpool_malloc0(), tb_rpool_memdup(), and tb_slist_insert_next().
tb_pointer_t tb_rpool_malloc0 (tb_handle_t handle)
malloc regular pool data and clear it
Parameters
handle the pool handle
Returns
the data pointer
Definition at line 365 of file rpool.c.
References tb_rpool_malloc().
Referenced by tb_ltimer_task_add_at(), tb_ltimer_task_run_at(), tb_mstream_done(), tb_timer_task_add_at(), and tb_timer_task_run_at().
tb_pointer_t tb_rpool_memdup (tb_handle_t handle, tb_cpointer_t data)
duplicate regular pool data
Parameters
handle the pool handle
data the data pointer
Returns
the duplicated data pointer
Definition at line 441 of file rpool.c.
References tb_rpool_malloc().
tb_size_t tb_rpool_size (tb_handle_t handle)
the regular pool item count
Parameters
handle the pool handle
Returns
the item count
Definition at line 237 of file rpool.c.
Referenced by tb_dlist_size(), tb_ltimer_spak(), tb_mstream_size(), and tb_slist_size().
tb_void_t tb_rpool_walk (tb_handle_t handle, tb_bool_t(*)(tb_pointer_t item, tb_pointer_t data) func, tb_pointer_t data)
walk regular pool item
tb_bool_t tb_rpool_item_func(tb_pointer_t item, tb_pointer_t data)
{
        // is tail?
        if (!item) ;
        // ok
        return tb_true;
fail:
        // break
        return tb_false;
}
Parameters
handle the pool handle
func the walk func
data the walk data
Definition at line 457 of file rpool.c.
References tb_fpool_walk().