TBOX: src/tbox/algorithm/bubble_sort.c File Reference
bubble_sort.c File Reference
Algorithm
#include "bubble_sort.h"
#include "../libc/libc.h"
Functions
tb_void_t tb_bubble_sort (tb_iterator_ref_t iterator, tb_size_t head, tb_size_t tail, tb_iterator_comp_t comp)
tb_void_t tb_bubble_sort_all (tb_iterator_ref_t iterator, tb_iterator_comp_t comp)
Detailed Description
The Treasure Box Library
TBox is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 2.1 of the License, or (at your option) any later version.
TBox is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with TBox; If not, see http://www.gnu.org/licenses/
Copyright (C) 2009 - 2015, ruki All rights reserved.
Author
ruki
Definition in file bubble_sort.c.
Function Documentation
tb_void_t tb_bubble_sort (tb_iterator_ref_t iterator, tb_size_t head, tb_size_t tail, tb_iterator_comp_t comp)
the bubble sorter, O(n^2)
Parameters
iterator the iterator
head the iterator head
tail the iterator tail
comp the comparer
Definition at line 35 of file bubble_sort.c.
References tb_iterator_comp(), tb_iterator_copy(), tb_iterator_item(), tb_iterator_mode(), TB_ITERATOR_MODE_FORWARD, tb_iterator_next(), and tb_iterator_step().
Referenced by tb_bubble_sort_all(), and tb_sort().
tb_void_t tb_bubble_sort_all (tb_iterator_ref_t iterator, tb_iterator_comp_t comp)
the bubble sorter for all
Parameters
iterator the iterator
head the iterator head
tail the iterator tail
comp the comparer
Definition at line 68 of file bubble_sort.c.
References tb_bubble_sort(), tb_iterator_head(), and tb_iterator_tail().