TBOX: src/tbox/container/queue.h File Reference
queue.h File Reference
Container | Container
#include "prefix.h"
#include "item.h"
#include "iterator.h"
#include "single_list.h"
Functions
tb_queue_ref_t tb_queue_init (tb_size_t grow, tb_item_func_t func)
tb_void_t tb_queue_exit (tb_queue_ref_t queue)
tb_pointer_t tb_queue_head (tb_queue_ref_t queue)
tb_pointer_t tb_queue_last (tb_queue_ref_t queue)
tb_void_t tb_queue_clear (tb_queue_ref_t queue)
tb_void_t tb_queue_put (tb_queue_ref_t queue, tb_cpointer_t data)
tb_void_t tb_queue_pop (tb_queue_ref_t queue)
tb_pointer_t tb_queue_get (tb_queue_ref_t queue)
tb_bool_t tb_queue_load (tb_queue_ref_t queue, tb_stream_ref_t stream)
tb_bool_t tb_queue_save (tb_queue_ref_t queue, tb_stream_ref_t stream)
tb_size_t tb_queue_size (tb_queue_ref_t queue)
tb_size_t tb_queue_maxn (tb_queue_ref_t queue)
tb_bool_t tb_queue_full (tb_queue_ref_t queue)
tb_bool_t tb_queue_null (tb_queue_ref_t queue)
Variables
__tb_extern_c_enter__ typedef
tb_single_list_ref_t tb_queue_ref_t
Detailed Description
The Treasure Box Library
TBox is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 2.1 of the License, or (at your option) any later version.
TBox is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with TBox; If not, see http://www.gnu.org/licenses/
Copyright (C) 2009 - 2015, ruki All rights reserved.
Author
ruki
Definition in file queue.h.
Function Documentation
tb_void_t tb_queue_clear (tb_queue_ref_t queue)
clear the queue
Parameters
queue the queue
Definition at line 40 of file queue.c.
References tb_single_list_clear(), and tb_single_list_ref_t.
tb_void_t tb_queue_exit (tb_queue_ref_t queue)
exit queue
Parameters
queue the queue
Definition at line 36 of file queue.c.
References tb_single_list_exit(), and tb_single_list_ref_t.
tb_bool_t tb_queue_full (tb_queue_ref_t queue)
the queue full?
Parameters
queue the queue
Returns
tb_true or tb_false
Definition at line 72 of file queue.c.
References tb_single_list_maxn(), tb_single_list_ref_t, and tb_single_list_size().
tb_pointer_t tb_queue_get (tb_queue_ref_t queue)
get the queue item
Parameters
queue the queue
Returns
the queue item
Definition at line 52 of file queue.c.
References tb_queue_head().
tb_pointer_t tb_queue_head (tb_queue_ref_t queue)
the queue head item
Parameters
queue the queue
Returns
the head item
Definition at line 56 of file queue.c.
References tb_single_list_head(), and tb_single_list_ref_t.
Referenced by tb_queue_get().
tb_queue_ref_t tb_queue_init (tb_size_t grow, tb_item_func_t func)
init queue
Parameters
grow the grow size, using the default grow size if be zero
func the item func
Returns
the queue
Definition at line 32 of file queue.c.
References tb_queue_ref_t, and tb_single_list_init().
tb_pointer_t tb_queue_last (tb_queue_ref_t queue)
the queue last item
Parameters
queue the queue
Returns
the last item
Definition at line 60 of file queue.c.
References tb_single_list_last(), and tb_single_list_ref_t.
tb_bool_t tb_queue_load (tb_queue_ref_t queue, tb_stream_ref_t stream)
load queue from the stream
Parameters
queue the queue
stream the stream
Returns
tb_true or tb_false
Definition at line 80 of file queue.c.
References tb_single_list_load(), and tb_single_list_ref_t.
tb_size_t tb_queue_maxn (tb_queue_ref_t queue)
the queue maxn
Parameters
queue the queue
Returns
the queue maxn
Definition at line 68 of file queue.c.
References tb_single_list_maxn(), and tb_single_list_ref_t.
tb_bool_t tb_queue_null (tb_queue_ref_t queue)
the queue null?
Parameters
queue the queue
Returns
tb_true or tb_false
Definition at line 76 of file queue.c.
References tb_single_list_ref_t, and tb_single_list_size().
tb_void_t tb_queue_pop (tb_queue_ref_t queue)
pop the queue item
Parameters
queue the queue
Definition at line 48 of file queue.c.
References tb_single_list_ref_t, and tb_single_list_remove_head().
tb_void_t tb_queue_put (tb_queue_ref_t queue, tb_cpointer_t data)
put the queue item
Parameters
queue the queue
data the item data
Definition at line 44 of file queue.c.
References tb_single_list_insert_tail(), and tb_single_list_ref_t.
tb_bool_t tb_queue_save (tb_queue_ref_t queue, tb_stream_ref_t stream)
save queue to the stream
Parameters
queue the queue
stream the stream
Returns
tb_true or tb_false
Definition at line 84 of file queue.c.
References tb_single_list_ref_t, and tb_single_list_save().
tb_size_t tb_queue_size (tb_queue_ref_t queue)
the queue size
Parameters
queue the queue
Returns
the queue size
Definition at line 64 of file queue.c.
References tb_single_list_ref_t, and tb_single_list_size().
Variable Documentation
__tb_extern_c_enter__ typedef tb_single_list_ref_t tb_queue_ref_t
the queue ref type
queue: |--—| => |--—| => ...                                 => |--—| => tail
        head                                                          last
performance:
put: O(1)
pop: O(1)
iterator:
next: fast
prev: fast
Definition at line 62 of file queue.h.
Referenced by tb_queue_init().