TBOX: src/tbox/utils/lock_profiler.h File Reference
lock_profiler.h File Reference
Utils
#include "prefix.h"
Functions
__tb_extern_c_enter__ tb_handle_t tb_lock_profiler (tb_noarg_t)
tb_handle_t tb_lock_profiler_init (tb_noarg_t)
tb_void_t tb_lock_profiler_exit (tb_handle_t profiler)
tb_void_t tb_lock_profiler_dump (tb_handle_t profiler)
tb_void_t tb_lock_profiler_register (tb_handle_t profiler, tb_pointer_t lock, tb_char_t const *name)
tb_void_t tb_lock_profiler_occupied (tb_handle_t profiler, tb_pointer_t lock)
Detailed Description
The Treasure Box Library
TBox is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 2.1 of the License, or (at your option) any later version.
TBox is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with TBox; If not, see http://www.gnu.org/licenses/
Copyright (C) 2009 - 2015, ruki All rights reserved.
Author
ruki
Definition in file lock_profiler.h.
Function Documentation
__tb_extern_c_enter__ tb_handle_t tb_lock_profiler (tb_noarg_t)
the lock profiler instance
Returns
the lock profiler handle
Referenced by tb_aicp_init(), tb_aiop_init(), tb_ltimer_init(), tb_pool_init(), tb_thread_pool_init(), tb_timer_init(), and tb_transfer_pool_init().
tb_void_t tb_lock_profiler_dump (tb_handle_t profiler)
dump lock profiler
Parameters
profiler the lock profiler handle
Definition at line 108 of file lock_profiler.c.
tb_void_t tb_lock_profiler_exit (tb_handle_t profiler)
exit lock profiler
Parameters
profiler the lock profiler handle
Definition at line 103 of file lock_profiler.c.
tb_handle_t tb_lock_profiler_init (tb_noarg_t)
init lock profiler
Note
be used for the debug mode generally
Returns
the lock profiler handle
tb_void_t tb_lock_profiler_occupied (tb_handle_t profiler, tb_pointer_t lock)
the lock be occupied
Parameters
profiler the lock profiler handle
lock the lock address
Definition at line 177 of file lock_profiler.c.
tb_void_t tb_lock_profiler_register (tb_handle_t profiler, tb_pointer_t lock, tb_char_t const * name)
register the lock to the lock profiler
Parameters
profiler the lock profiler handle
lock the lock address
name the lock name
Definition at line 134 of file lock_profiler.c.
Referenced by tb_aicp_init(), tb_aiop_init(), tb_ltimer_init(), tb_pool_init(), tb_thread_pool_init(), tb_timer_init(), and tb_transfer_pool_init().