TBOX: src/container/hash.c File Reference
hash.c File Reference
Container
#include "hash.h"
#include "../libc/libc.h"
#include "../math/math.h"
#include "../utils/utils.h"
#include "../memory/memory.h"
#include "../platform/platform.h"
#include "../algorithm/algorithm.h"
Macros
#define TB_HASH_INDEX_MAKE(buck, item) (((tb_size_t)((item) & 0xffff) << 16) | (buck) & 0xffff)
#define TB_HASH_INDEX_BUCK(index) ((index) & 0xffff)
#define TB_HASH_INDEX_ITEM(index) (((index) >> 16) & 0xffff)
#define TB_HASH_GROW_MIN (8)
Functions
tb_hash_t * tb_hash_init (tb_size_t size, tb_item_func_t name_func, tb_item_func_t data_func)
tb_void_t tb_hash_exit (tb_hash_t *handle)
tb_void_t tb_hash_clear (tb_hash_t *handle)
tb_size_t tb_hash_itor (tb_hash_t const *handle, tb_cpointer_t name)
tb_pointer_t tb_hash_get (tb_hash_t const *handle, tb_cpointer_t name)
tb_void_t tb_hash_del (tb_hash_t *handle, tb_cpointer_t name)
tb_size_t tb_hash_set (tb_hash_t *handle, tb_cpointer_t name, tb_cpointer_t data)
tb_size_t tb_hash_size (tb_hash_t const *handle)
tb_size_t tb_hash_maxn (tb_hash_t const *handle)
tb_void_t tb_hash_walk (tb_hash_t *handle, tb_bool_t(*func)(tb_hash_t *hash, tb_hash_item_t *item, tb_bool_t *bdel, tb_pointer_t priv), tb_pointer_t priv)
tb_void_t tb_hash_dump (tb_hash_t const *handle)
Detailed Description
The Treasure Box Library
TBox is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 2.1 of the License, or (at your option) any later version.
TBox is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with TBox; If not, see http://www.gnu.org/licenses/
Copyright (C) 2009 - 2015, ruki All rights reserved.
Author
ruki
Definition in file hash.c.
Function Documentation
tb_void_t tb_hash_clear (tb_hash_t * hash)
clear hash
Parameters
hash the hash
Definition at line 443 of file hash.c.
Referenced by tb_hash_exit().
tb_void_t tb_hash_del (tb_hash_t * hash, tb_cpointer_t name)
del hash item
Parameters
hash the hash
name the hash item name
Definition at line 512 of file hash.c.
Referenced by tb_dictionary_del().
tb_void_t tb_hash_dump (tb_hash_t const * hash)
dump hash
Parameters
hash the hash
Definition at line 741 of file hash.c.
References tb_for_all.
tb_void_t tb_hash_exit (tb_hash_t * hash)
exit hash
Parameters
hash the hash
Definition at line 428 of file hash.c.
References tb_hash_clear().
Referenced by tb_hash_init().
tb_pointer_t tb_hash_get (tb_hash_t const * hash, tb_cpointer_t name)
get hash item data
Parameters
hash the hash
name the hash item name
Returns
the hash item data
Definition at line 496 of file hash.c.
Referenced by tb_dictionary_val(), and tb_dns_cache_get().
tb_hash_t* tb_hash_init (tb_size_t size, tb_item_func_t name_func, tb_item_func_t data_func)
init hash
Parameters
size the hash size
name_func the hash name func
data_func the hash data func
Returns
the hash
Definition at line 385 of file hash.c.
References tb_item_func_t::dupl, tb_item_func_t::hash, tb_item_func_t::repl, tb_item_func_t::size, tb_hash_exit(), and TB_ITERATOR_MODE_FORWARD.
Referenced by tb_dictionary_init(), and tb_scache_init().
tb_size_t tb_hash_itor (tb_hash_t const * hash, tb_cpointer_t name)
get hash item itor
Parameters
hash the hash
name the hash item name
Returns
the hash itor,
Note
: itor => item maybe changed if insert or remove item
Definition at line 485 of file hash.c.
Referenced by tb_scache_del(), and tb_scache_put().
tb_size_t tb_hash_maxn (tb_hash_t const * hash)
the hash maxn
Parameters
hash the hash
Returns
the hash maxn
Definition at line 622 of file hash.c.
tb_size_t tb_hash_set (tb_hash_t * hash, tb_cpointer_t name, tb_cpointer_t data)
set hash item
Parameters
hash the hash
name the hash item name
data the hash item data
Returns
the hash itor,
Note
: itor => item maybe changed if insert or remove item
Definition at line 524 of file hash.c.
Referenced by tb_dictionary_set(), tb_dns_cache_set(), tb_scache_put(), and tb_tstore_setp().
tb_size_t tb_hash_size (tb_hash_t const * hash)
the hash size
Parameters
hash the hash
Returns
the hash size
Definition at line 616 of file hash.c.
Referenced by tb_dictionary_size(), tb_dns_cache_get(), and tb_dns_cache_set().
tb_void_t tb_hash_walk (tb_hash_t * hash, tb_bool_t(*)(tb_hash_t *hash, tb_hash_item_t *item, tb_bool_t *bdel, tb_pointer_t priv) func, tb_pointer_t priv)
walk hash items
be faster than the iterator mode, optimizate to remove items for walking
tb_bool_t tb_hash_item_func(tb_hash_t* hash, tb_hash_item_t* item, tb_bool_t* bdel, tb_pointer_t priv)
{
        tb_assert_and_check_return_val(hash && bdel, tb_false);
        // delete it?
        // *bdel = tb_true;
        // continue or break
        return tb_true;
}
Parameters
hash the hash
func the walk callback func
data the walk callback data
Definition at line 628 of file hash.c.
References tb_hash_item_t::data, and tb_hash_item_t::name.
Referenced by tb_dns_cache_set().