TBOX: src/stream/tstream.h File Reference
tstream.h File Reference
Stream
#include "prefix.h"
#include "gstream.h"
#include "astream.h"
Typedefs
typedef tb_bool_t(* tb_tstream_open_func_t)(tb_size_t state, tb_hize_t offset, tb_hong_t size, tb_pointer_t priv)
typedef tb_bool_t(* tb_tstream_save_func_t)(tb_size_t state, tb_hize_t offset, tb_hong_t size, tb_hize_t save, tb_size_t rate, tb_pointer_t priv)
Functions
tb_hong_t tb_tstream_save_gg (tb_gstream_t *istream, tb_gstream_t *ostream, tb_size_t lrate, tb_tstream_save_func_t func, tb_pointer_t priv)
tb_hong_t tb_tstream_save_gu (tb_gstream_t *istream, tb_char_t const *ourl, tb_size_t lrate, tb_tstream_save_func_t func, tb_pointer_t priv)
tb_hong_t tb_tstream_save_gd (tb_gstream_t *istream, tb_byte_t *odata, tb_size_t osize, tb_size_t lrate, tb_tstream_save_func_t func, tb_pointer_t priv)
tb_hong_t tb_tstream_save_uu (tb_char_t const *iurl, tb_char_t const *ourl, tb_size_t lrate, tb_tstream_save_func_t func, tb_pointer_t priv)
tb_hong_t tb_tstream_save_ug (tb_char_t const *iurl, tb_gstream_t *ostream, tb_size_t lrate, tb_tstream_save_func_t func, tb_pointer_t priv)
tb_hong_t tb_tstream_save_ud (tb_char_t const *iurl, tb_byte_t *odata, tb_size_t osize, tb_size_t lrate, tb_tstream_save_func_t func, tb_pointer_t priv)
tb_hong_t tb_tstream_save_du (tb_byte_t const *idata, tb_size_t isize, tb_char_t const *ourl, tb_size_t lrate, tb_tstream_save_func_t func, tb_pointer_t priv)
tb_hong_t tb_tstream_save_dg (tb_byte_t const *idata, tb_size_t isize, tb_gstream_t *ostream, tb_size_t lrate, tb_tstream_save_func_t func, tb_pointer_t priv)
tb_handle_t tb_tstream_init_aa (tb_astream_t *istream, tb_astream_t *ostream, tb_hize_t offset)
tb_handle_t tb_tstream_init_ag (tb_astream_t *istream, tb_gstream_t *ostream, tb_hize_t offset)
tb_handle_t tb_tstream_init_au (tb_astream_t *istream, tb_char_t const *ourl, tb_hize_t offset)
tb_handle_t tb_tstream_init_uu (tb_aicp_t *aicp, tb_char_t const *iurl, tb_char_t const *ourl, tb_hize_t offset)
tb_handle_t tb_tstream_init_ua (tb_char_t const *iurl, tb_astream_t *ostream, tb_hize_t offset)
tb_handle_t tb_tstream_init_du (tb_aicp_t *aicp, tb_byte_t const *idata, tb_size_t isize, tb_char_t const *ourl, tb_hize_t offset)
tb_handle_t tb_tstream_init_da (tb_byte_t const *idata, tb_size_t isize, tb_astream_t *ostream, tb_hize_t offset)
tb_bool_t tb_tstream_open (tb_handle_t tstream, tb_tstream_open_func_t func, tb_pointer_t priv)
tb_bool_t tb_tstream_save (tb_handle_t tstream, tb_tstream_save_func_t func, tb_pointer_t priv)
tb_bool_t tb_tstream_osave (tb_handle_t tstream, tb_tstream_save_func_t func, tb_pointer_t priv)
tb_void_t tb_tstream_kill (tb_handle_t tstream)
tb_void_t tb_tstream_exit (tb_handle_t tstream, tb_bool_t bcalling)
tb_void_t tb_tstream_pause (tb_handle_t tstream)
tb_bool_t tb_tstream_resume (tb_handle_t tstream)
tb_void_t tb_tstream_limitrate (tb_handle_t tstream, tb_size_t rate)
tb_void_t tb_tstream_timeout_set (tb_handle_t tstream, tb_long_t timeout)
Detailed Description
The Treasure Box Library
TBox is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 2.1 of the License, or (at your option) any later version.
TBox is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with TBox; If not, see http://www.gnu.org/licenses/
Copyright (C) 2009 - 2015, ruki All rights reserved.
Author
ruki
Definition in file tstream.h.
Typedef Documentation
typedef tb_bool_t(* tb_tstream_open_func_t)(tb_size_t state, tb_hize_t offset, tb_hong_t size, tb_pointer_t priv)
the tstream open func type
Parameters
state the stream state
offset the istream offset
size the istream size, no size: -1
priv the func private data
Returns
tb_true: ok, tb_false: break it
Definition at line 47 of file tstream.h.
typedef tb_bool_t(* tb_tstream_save_func_t)(tb_size_t state, tb_hize_t offset, tb_hong_t size, tb_hize_t save, tb_size_t rate, tb_pointer_t priv)
the tstream save func type
Parameters
state the stream state
offset the istream offset
size the istream size, no size: -1
save the saved size
rate the current rate, bytes/s
priv the func private data
Returns
tb_true: ok and continue it if need, tb_false: break it
Definition at line 60 of file tstream.h.
Function Documentation
tb_void_t tb_tstream_exit (tb_handle_t tstream, tb_bool_t bcalling)
exit tstream
Parameters
tstream the tstream
bcalling exit it at the self callback?
Definition at line 1336 of file tstream.c.
References tb_astream_exit(), tb_gstream_exit(), tb_stream_mode(), and tb_tstream_kill().
tb_handle_t tb_tstream_init_aa (tb_astream_t * istream, tb_astream_t * ostream, tb_hize_t offset)
init tstream from astream to astream, async transfer
Parameters
istream the istream
ostream the ostream
offset the offset
Returns
the tstream
Definition at line 930 of file tstream.c.
tb_handle_t tb_tstream_init_ag (tb_astream_t * istream, tb_gstream_t * ostream, tb_hize_t offset)
init tstream from astream to gstream, async transfer
Parameters
istream the istream
ostream the ostream
offset the offset
Returns
the tstream
Definition at line 956 of file tstream.c.
References tb_gstream_t::offset.
tb_handle_t tb_tstream_init_au (tb_astream_t * istream, tb_char_t const * ourl, tb_hize_t offset)
init tstream from astream to url, async transfer
Parameters
istream the istream
ourl the output url
offset the offset
Returns
the tstream
Definition at line 982 of file tstream.c.
References tb_astream_aicp(), tb_astream_exit(), tb_astream_init_from_url(), TB_FILE_MODE_BINARY, TB_FILE_MODE_CREAT, TB_FILE_MODE_RW, TB_FILE_MODE_TRUNC, tb_stream_ctrl(), and tb_stream_type().
tb_handle_t tb_tstream_init_da (tb_byte_t const * idata, tb_size_t isize, tb_astream_t * ostream, tb_hize_t offset)
init tstream from data to astream, async transfer
Parameters
idata the input data
isize the input size
ostream the ostream
offset the offset
Returns
the tstream
Definition at line 1175 of file tstream.c.
References tb_astream_aicp(), tb_astream_exit(), and tb_astream_init_from_data().
tb_handle_t tb_tstream_init_du (tb_aicp_t * aicp, tb_byte_t const * idata, tb_size_t isize, tb_char_t const * ourl, tb_hize_t offset)
init tstream from data to url, async transfer
Parameters
aicp the aicp
idata the input data
isize the input size
ourl the output url
offset the offset
Returns
the tstream
Definition at line 1120 of file tstream.c.
References tb_astream_exit(), tb_astream_init_from_data(), tb_astream_init_from_url(), TB_FILE_MODE_BINARY, TB_FILE_MODE_CREAT, TB_FILE_MODE_RW, TB_FILE_MODE_TRUNC, tb_stream_ctrl(), and tb_stream_type().
tb_handle_t tb_tstream_init_ua (tb_char_t const * iurl, tb_astream_t * ostream, tb_hize_t offset)
init tstream from url to astream, async transfer
Parameters
iurl the input url
ostream the ostream
offset the offset
Returns
the tstream
Definition at line 1082 of file tstream.c.
References tb_astream_aicp(), tb_astream_exit(), and tb_astream_init_from_url().
tb_handle_t tb_tstream_init_uu (tb_aicp_t * aicp, tb_char_t const * iurl, tb_char_t const * ourl, tb_hize_t offset)
init tstream from url to url, async transfer
Parameters
aicp the aicp
iurl the input url
ourl the output url
offset the offset
Returns
the tstream
Definition at line 1027 of file tstream.c.
References tb_astream_exit(), tb_astream_init_from_url(), TB_FILE_MODE_BINARY, TB_FILE_MODE_CREAT, TB_FILE_MODE_RW, TB_FILE_MODE_TRUNC, tb_stream_ctrl(), and tb_stream_type().
Referenced by tb_mstream_done().
tb_void_t tb_tstream_kill (tb_handle_t tstream)
kill tstream
Parameters
tstream the tstream
Definition at line 1315 of file tstream.c.
References tb_stream_kill(), and tb_stream_mode().
Referenced by tb_tstream_exit().
tb_void_t tb_tstream_limitrate (tb_handle_t tstream, tb_size_t rate)
limit tstream rate
Parameters
tstream the tstream
rate the trasfer rate and no limit if 0, bytes/s
Definition at line 1424 of file tstream.c.
tb_bool_t tb_tstream_open (tb_handle_t tstream, tb_tstream_open_func_t func, tb_pointer_t priv)
open tstream
Parameters
tstream the tstream
func the open func
priv the func private data
Returns
tb_true or tb_false
Definition at line 1213 of file tstream.c.
References tb_aicp_time(), tb_astream_aicp(), tb_astream_open, tb_astream_oseek, tb_gstream_open(), tb_stream_is_opened(), and tb_stream_mode().
Referenced by tb_tstream_osave().
tb_bool_t tb_tstream_osave (tb_handle_t tstream, tb_tstream_save_func_t func, tb_pointer_t priv)
open and save tstream
Parameters
tstream the tstream
func the save func
priv the func private data
Returns
tb_true or tb_false
Definition at line 1297 of file tstream.c.
References tb_tstream_open(), and tb_tstream_save().
Referenced by tb_mstream_done().
tb_void_t tb_tstream_pause (tb_handle_t tstream)
pause tstream
the save func state will return TB_STATE_PAUSED
Parameters
tstream the tstream
Definition at line 1368 of file tstream.c.
tb_bool_t tb_tstream_resume (tb_handle_t tstream)
resume tstream
Parameters
tstream the tstream
Returns
tb_true or tb_false
Definition at line 1380 of file tstream.c.
References tb_aicp_time(), tb_astream_aicp(), and tb_astream_read.
tb_bool_t tb_tstream_save (tb_handle_t tstream, tb_tstream_save_func_t func, tb_pointer_t priv)
save tstream
Parameters
tstream the tstream
func the save func
priv the func private data
Returns
tb_true or tb_false
Definition at line 1277 of file tstream.c.
References tb_astream_read.
Referenced by tb_tstream_osave().
tb_hong_t tb_tstream_save_dg (tb_byte_t const * idata, tb_size_t isize, tb_gstream_t * ostream, tb_size_t lrate, tb_tstream_save_func_t func, tb_pointer_t priv)
save data to gstream, block transfer
Parameters
idata the input data
isize the input size
ostream the ostream
lrate the limit rate and no limit if 0, bytes/s
func the save func and be optional
priv the func private data
Returns
the saved size, failed: -1
Definition at line 904 of file tstream.c.
References tb_gstream_exit(), tb_gstream_init_from_data(), and tb_tstream_save_gg().
tb_hong_t tb_tstream_save_du (tb_byte_t const * idata, tb_size_t isize, tb_char_t const * ourl, tb_size_t lrate, tb_tstream_save_func_t func, tb_pointer_t priv)
save data to url, block transfer
Parameters
idata the input data
isize the input size
ourl the output url
lrate the limit rate and no limit if 0, bytes/s
func the save func and be optional
priv the func private data
Returns
the saved size, failed: -1
Definition at line 862 of file tstream.c.
References TB_FILE_MODE_BINARY, TB_FILE_MODE_CREAT, TB_FILE_MODE_RW, TB_FILE_MODE_TRUNC, tb_gstream_exit(), tb_gstream_init_from_data(), tb_gstream_init_from_url(), tb_stream_ctrl(), tb_stream_type(), and tb_tstream_save_gg().
tb_hong_t tb_tstream_save_gd (tb_gstream_t * istream, tb_byte_t * odata, tb_size_t osize, tb_size_t lrate, tb_tstream_save_func_t func, tb_pointer_t priv)
save gstream to data, block transfer
Parameters
istream the istream
odata the output data
osize the output size
lrate the limit rate and no limit if 0, bytes/s
func the save func and be optional
priv the func private data
Returns
the saved size, failed: -1
Definition at line 727 of file tstream.c.
References tb_gstream_exit(), tb_gstream_init_from_data(), and tb_tstream_save_gg().
tb_hong_t tb_tstream_save_gg (tb_gstream_t * istream, tb_gstream_t * ostream, tb_size_t lrate, tb_tstream_save_func_t func, tb_pointer_t priv)
save gstream to gstream, block transfer
Parameters
istream the istream
ostream the ostream
lrate the limit rate and no limit if 0, bytes/s
func the save func and be optional
priv the func private data
Returns
the saved size, failed: -1
Definition at line 577 of file tstream.c.
References tb_gstream_aread(), tb_gstream_bwrit(), tb_gstream_open(), tb_gstream_sync(), tb_gstream_wait(), tb_stream_is_opened(), tb_stream_left(), tb_stream_offset(), tb_stream_size(), and tb_stream_timeout().
Referenced by tb_tstream_save_dg(), tb_tstream_save_du(), tb_tstream_save_gd(), tb_tstream_save_gu(), tb_tstream_save_ud(), tb_tstream_save_ug(), and tb_tstream_save_uu().
tb_hong_t tb_tstream_save_gu (tb_gstream_t * istream, tb_char_t const * ourl, tb_size_t lrate, tb_tstream_save_func_t func, tb_pointer_t priv)
save gstream to url, block transfer
Parameters
istream the istream
ourl the output url
lrate the limit rate and no limit if 0, bytes/s
func the save func and be optional
priv the func private data
Returns
the saved size, failed: -1
Definition at line 694 of file tstream.c.
References TB_FILE_MODE_BINARY, TB_FILE_MODE_CREAT, TB_FILE_MODE_RW, TB_FILE_MODE_TRUNC, tb_gstream_exit(), tb_gstream_init_from_url(), tb_stream_ctrl(), tb_stream_type(), and tb_tstream_save_gg().
tb_hong_t tb_tstream_save_ud (tb_char_t const * iurl, tb_byte_t * odata, tb_size_t osize, tb_size_t lrate, tb_tstream_save_func_t func, tb_pointer_t priv)
save url to data, block transfer
Parameters
iurl the input url
odata the output data
osize the output size
lrate the limit rate and no limit if 0, bytes/s
func the save func and be optional
priv the func private data
Returns
the saved size, failed: -1
Definition at line 827 of file tstream.c.
References tb_gstream_exit(), tb_gstream_init_from_data(), tb_gstream_init_from_url(), and tb_tstream_save_gg().
tb_hong_t tb_tstream_save_ug (tb_char_t const * iurl, tb_gstream_t * ostream, tb_size_t lrate, tb_tstream_save_func_t func, tb_pointer_t priv)
save url to gstream, block transfer
Parameters
iurl the input url
ostream the ostream
lrate the limit rate and no limit if 0, bytes/s
func the save func and be optional
priv the func private data
Returns
the saved size, failed: -1
Definition at line 801 of file tstream.c.
References tb_gstream_exit(), tb_gstream_init_from_url(), and tb_tstream_save_gg().
tb_hong_t tb_tstream_save_uu (tb_char_t const * iurl, tb_char_t const * ourl, tb_size_t lrate, tb_tstream_save_func_t func, tb_pointer_t priv)
save url to url, block transfer
Parameters
iurl the input url
ourl the output url
lrate the limit rate and no limit if 0, bytes/s
func the save func and be optional
priv the func private data
Returns
the saved size, failed: -1
Definition at line 753 of file tstream.c.
References TB_FILE_MODE_BINARY, TB_FILE_MODE_CREAT, TB_FILE_MODE_RW, TB_FILE_MODE_TRUNC, tb_gstream_exit(), tb_gstream_init_from_url(), tb_gstream_open(), tb_stream_ctrl(), tb_stream_type(), and tb_tstream_save_gg().
Referenced by tb_file_copy().
tb_void_t tb_tstream_timeout_set (tb_handle_t tstream, tb_long_t timeout)
set tstream timeout
Parameters
tstream the tstream
timeout the timeout, using the default timeout if be zero
Definition at line 1433 of file tstream.c.
References tb_stream_ctrl().
Referenced by tb_mstream_done().