TBOX: src/tbox/object/array.c File Reference
array.c File Reference
Object
#include "object.h"
#include "../algorithm/algorithm.h"
Macros
#define TB_TRACE_MODULE_NAME "object_array"
#define TB_TRACE_MODULE_DEBUG (0)
Functions
tb_object_ref_t tb_object_array_init (tb_size_t grow, tb_bool_t incr)
tb_size_t tb_object_array_size (tb_object_ref_t object)
tb_object_ref_t tb_object_array_item (tb_object_ref_t object, tb_size_t index)
tb_iterator_ref_t tb_object_array_itor (tb_object_ref_t object)
tb_void_t tb_object_array_remove (tb_object_ref_t object, tb_size_t index)
tb_void_t tb_object_array_append (tb_object_ref_t object, tb_object_ref_t item)
tb_void_t tb_object_array_insert (tb_object_ref_t object, tb_size_t index, tb_object_ref_t item)
tb_void_t tb_object_array_replace (tb_object_ref_t object, tb_size_t index, tb_object_ref_t item)
tb_void_t tb_object_array_incr (tb_object_ref_t object, tb_bool_t incr)
Detailed Description
The Treasure Box Library
TBox is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 2.1 of the License, or (at your option) any later version.
TBox is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with TBox; If not, see http://www.gnu.org/licenses/
Copyright (C) 2009 - 2015, ruki All rights reserved.
Author
ruki
Definition in file array.c.
Function Documentation
tb_void_t tb_object_array_append (tb_object_ref_t array, tb_object_ref_t item)
append item to array
Parameters
array the array object
index the array index
Definition at line 221 of file array.c.
References tb_object_dec(), and tb_vector_insert_tail().
tb_void_t tb_object_array_incr (tb_object_ref_t array, tb_bool_t incr)
set the array incr
Parameters
array the array object
incr is increase refn?
Definition at line 257 of file array.c.
tb_object_ref_t tb_object_array_init (tb_size_t grow, tb_bool_t incr)
init array
Parameters
grow the array grow
incr is increase refn?
Returns
the array object
Definition at line 148 of file array.c.
References tb_item_func_obj(), and tb_vector_init().
tb_void_t tb_object_array_insert (tb_object_ref_t array, tb_size_t index, tb_object_ref_t item)
insert item to array
Parameters
array the array object
index the array index
item the array item
Definition at line 233 of file array.c.
References tb_object_dec(), and tb_vector_insert_prev().
tb_object_ref_t tb_object_array_item (tb_object_ref_t array, tb_size_t index)
the array item at index
Parameters
array the array object
index the array index
Returns
the array item
Definition at line 194 of file array.c.
References tb_iterator_item().
Referenced by tb_object_seek().
tb_iterator_ref_t tb_object_array_itor (tb_object_ref_t array)
the array iterator
Parameters
array the array object
Returns
the array iterator
tb_for_all (tb_object_ref_t, item, tb_object_array_itor(array))
{
     if (item)
     {
         // ...
     }
}
Definition at line 203 of file array.c.
tb_void_t tb_object_array_remove (tb_object_ref_t array, tb_size_t index)
remove the item from index
Parameters
array the array object
index the array index
Definition at line 212 of file array.c.
References tb_vector_remove().
tb_void_t tb_object_array_replace (tb_object_ref_t array, tb_size_t index, tb_object_ref_t item)
replace item to array
Parameters
array the array object
index the array index
item the array item
Definition at line 245 of file array.c.
References tb_object_dec(), and tb_vector_replace().
tb_size_t tb_object_array_size (tb_object_ref_t array)
the array size
Parameters
array the array object
Returns
the array size
Definition at line 185 of file array.c.
References tb_vector_size().
Referenced by tb_object_seek().