TBOX: src/tbox/stream/transfer.h File Reference
transfer.h File Reference
Stream
#include "prefix.h"
#include "async_stream.h"
#include "async_transfer.h"
Functions
tb_hong_t tb_transfer_done (tb_stream_ref_t istream, tb_stream_ref_t ostream, tb_size_t lrate, tb_transfer_done_func_t func, tb_cpointer_t priv)
tb_hong_t tb_transfer_done_to_url (tb_stream_ref_t istream, tb_char_t const *ourl, tb_size_t lrate, tb_transfer_done_func_t func, tb_cpointer_t priv)
tb_hong_t tb_transfer_done_to_data (tb_stream_ref_t istream, tb_byte_t *odata, tb_size_t osize, tb_size_t lrate, tb_transfer_done_func_t func, tb_cpointer_t priv)
tb_hong_t tb_transfer_done_url (tb_char_t const *iurl, tb_char_t const *ourl, tb_size_t lrate, tb_transfer_done_func_t func, tb_cpointer_t priv)
tb_hong_t tb_transfer_done_url_to_stream (tb_char_t const *iurl, tb_stream_ref_t ostream, tb_size_t lrate, tb_transfer_done_func_t func, tb_cpointer_t priv)
tb_hong_t tb_transfer_done_url_to_data (tb_char_t const *iurl, tb_byte_t *odata, tb_size_t osize, tb_size_t lrate, tb_transfer_done_func_t func, tb_cpointer_t priv)
tb_hong_t tb_transfer_done_data_to_url (tb_byte_t const *idata, tb_size_t isize, tb_char_t const *ourl, tb_size_t lrate, tb_transfer_done_func_t func, tb_cpointer_t priv)
tb_hong_t tb_transfer_done_data_to_stream (tb_byte_t const *idata, tb_size_t isize, tb_stream_ref_t ostream, tb_size_t lrate, tb_transfer_done_func_t func, tb_cpointer_t priv)
Variables
__tb_extern_c_enter__ typedef
tb_bool_t(* tb_transfer_done_func_t)(tb_size_t state, tb_hize_t offset, tb_hong_t size, tb_hize_t save, tb_size_t rate, tb_cpointer_t priv)
Detailed Description
The Treasure Box Library
TBox is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation; either version 2.1 of the License, or (at your option) any later version.
TBox is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.
You should have received a copy of the GNU Lesser General Public License along with TBox; If not, see http://www.gnu.org/licenses/
Copyright (C) 2009 - 2015, ruki All rights reserved.
Author
ruki
Definition in file transfer.h.
Function Documentation
tb_hong_t tb_transfer_done (tb_stream_ref_t istream, tb_stream_ref_t ostream, tb_size_t lrate, tb_transfer_done_func_t func, tb_cpointer_t priv)
done transfer from stream to stream
Parameters
istream the istream
ostream the ostream
lrate the limit rate and no limit if 0, bytes/s
func the save func and be optional
priv the func private data
Returns
the saved size, failed: -1
Definition at line 42 of file transfer.c.
References tb_cache_time_spak(), TB_STREAM_BLOCK_MAXN, tb_stream_bwrit(), tb_stream_is_closed(), tb_stream_left(), tb_stream_offset(), tb_stream_open(), tb_stream_read(), tb_stream_size(), tb_stream_sync(), tb_stream_timeout(), and tb_stream_wait().
Referenced by tb_transfer_done_data_to_stream(), tb_transfer_done_data_to_url(), tb_transfer_done_to_data(), tb_transfer_done_to_url(), tb_transfer_done_url(), tb_transfer_done_url_to_data(), and tb_transfer_done_url_to_stream().
tb_hong_t tb_transfer_done_data_to_stream (tb_byte_t const * idata, tb_size_t isize, tb_stream_ref_t ostream, tb_size_t lrate, tb_transfer_done_func_t func, tb_cpointer_t priv)
done transfer from data to stream
Parameters
idata the input data
isize the input size
ostream the ostream
lrate the limit rate and no limit if 0, bytes/s
func the save func and be optional
priv the func private data
Returns
the saved size, failed: -1
Definition at line 369 of file transfer.c.
References tb_stream_exit(), tb_stream_init_from_data(), and tb_transfer_done().
tb_hong_t tb_transfer_done_data_to_url (tb_byte_t const * idata, tb_size_t isize, tb_char_t const * ourl, tb_size_t lrate, tb_transfer_done_func_t func, tb_cpointer_t priv)
done transfer from data to url
Parameters
idata the input data
isize the input size
ourl the output url
lrate the limit rate and no limit if 0, bytes/s
func the save func and be optional
priv the func private data
Returns
the saved size, failed: -1
Definition at line 327 of file transfer.c.
References TB_FILE_MODE_BINARY, TB_FILE_MODE_CREAT, TB_FILE_MODE_RW, TB_FILE_MODE_TRUNC, tb_stream_ctrl(), tb_stream_exit(), tb_stream_init_from_data(), tb_stream_init_from_url(), tb_stream_type(), and tb_transfer_done().
tb_hong_t tb_transfer_done_to_data (tb_stream_ref_t istream, tb_byte_t * odata, tb_size_t osize, tb_size_t lrate, tb_transfer_done_func_t func, tb_cpointer_t priv)
done transfer from stream to data
Parameters
istream the istream
odata the output data
osize the output size
lrate the limit rate and no limit if 0, bytes/s
func the save func and be optional
priv the func private data
Returns
the saved size, failed: -1
Definition at line 192 of file transfer.c.
References tb_stream_exit(), tb_stream_init_from_data(), and tb_transfer_done().
tb_hong_t tb_transfer_done_to_url (tb_stream_ref_t istream, tb_char_t const * ourl, tb_size_t lrate, tb_transfer_done_func_t func, tb_cpointer_t priv)
done transfer from stream to url
Parameters
istream the istream
ourl the output url
lrate the limit rate and no limit if 0, bytes/s
func the save func and be optional
priv the func private data
Returns
the saved size, failed: -1
Definition at line 159 of file transfer.c.
References TB_FILE_MODE_BINARY, TB_FILE_MODE_CREAT, TB_FILE_MODE_RW, TB_FILE_MODE_TRUNC, tb_stream_ctrl(), tb_stream_exit(), tb_stream_init_from_url(), tb_stream_type(), and tb_transfer_done().
tb_hong_t tb_transfer_done_url (tb_char_t const * iurl, tb_char_t const * ourl, tb_size_t lrate, tb_transfer_done_func_t func, tb_cpointer_t priv)
done transfer from url to url
Parameters
iurl the input url
ourl the output url
lrate the limit rate and no limit if 0, bytes/s
func the save func and be optional
priv the func private data
Returns
the saved size, failed: -1
Definition at line 218 of file transfer.c.
References TB_FILE_MODE_BINARY, TB_FILE_MODE_CREAT, TB_FILE_MODE_RW, TB_FILE_MODE_TRUNC, tb_stream_ctrl(), tb_stream_exit(), tb_stream_init_from_url(), tb_stream_open(), tb_stream_type(), and tb_transfer_done().
Referenced by tb_file_copy().
tb_hong_t tb_transfer_done_url_to_data (tb_char_t const * iurl, tb_byte_t * odata, tb_size_t osize, tb_size_t lrate, tb_transfer_done_func_t func, tb_cpointer_t priv)
done transfer from url to data
Parameters
iurl the input url
odata the output data
osize the output size
lrate the limit rate and no limit if 0, bytes/s
func the save func and be optional
priv the func private data
Returns
the saved size, failed: -1
Definition at line 292 of file transfer.c.
References tb_stream_exit(), tb_stream_init_from_data(), tb_stream_init_from_url(), and tb_transfer_done().
tb_hong_t tb_transfer_done_url_to_stream (tb_char_t const * iurl, tb_stream_ref_t ostream, tb_size_t lrate, tb_transfer_done_func_t func, tb_cpointer_t priv)
done transfer from url to stream
Parameters
iurl the input url
ostream the ostream
lrate the limit rate and no limit if 0, bytes/s
func the save func and be optional
priv the func private data
Returns
the saved size, failed: -1
Definition at line 266 of file transfer.c.
References tb_stream_exit(), tb_stream_init_from_url(), and tb_transfer_done().
Variable Documentation
__tb_extern_c_enter__ typedef tb_bool_t(* tb_transfer_done_func_t)(tb_size_t state, tb_hize_t offset, tb_hong_t size, tb_hize_t save, tb_size_t rate, tb_cpointer_t priv)
the basic transfer done func type
Parameters
state the stream state
offset the istream offset
size the istream size, no size: -1
save the saved size
rate the current rate, bytes/s
priv the func private data
Returns
tb_true: ok and continue it if need, tb_false: break it
Definition at line 54 of file transfer.h.